### ISSUE TITLE
How to edit prometheus configs?

### ISSUE THREAD

**Issue by heckad** [canonical/microk8s#1074]
I want to add job in Prometheus but I can't find config map with Prometheus configs. Where is it?

**Comment by balchua** [comment]
The Prometheus addon is using the prometheus operator.  I haven't personally used it.  But here's the link to prometheus operator docs. https://github.com/coreos/kube-prometheus/blob/master/README.md

**Comment by peix2** [comment]
@heckad you need to create "service monitor" for the "thing" you want to be monitored by existing prometheus. Have a look for existing service monitors being deployed on your cluster to get the ides about the syntax.

**Comment by frequencebanane** [comment]
@heckad Did you solve your problem ? I have exactly the same, no way to find the config of prometheus

**Comment by heckad** [comment]
@fabrichter, hi, I can't solve this problem.

**Comment by vshynkar** [comment]
I have the same problem and not information on how to change Prometheus configs to add a new job.

**Comment by eduyayo** [comment]
you have to add a servicemonitor for the scraper to go to your actuators https://medium.com/vividcode/monitor-spring-boot-apps-using-prometheus-on-kubernetes-a7c1b58c8511
