### ISSUE TITLE
Add command `microk8s about` or `microk8s version` 

### ISSUE THREAD

**Issue by tringuyen-yw** [canonical/microk8s#1236]
Currently using microk8s 1.18.2. trying `microk8s version` got an error saying it is not a valid command. I think it would make sense to have a `microk8s about` command which give a quick "about" of the microk8s cluster:
- microk8s version and snap channel
- addon, enabled (or not) and version of the addon
- cluster info

**Comment by balchua** [comment]
To see what microk8s version i use, i usually do `snap info microk8s`.  It will show u the channels available and what is installed.

**Comment by tringuyen-yw** [comment]
Fair enough, but is your microk8s version in sync with the snap repo?

Here is what I got when running `sudo snap info microk8s`. Tracking `latest/edge` which is ` v1.18.4`. How to verify that the Microk8S version I am running is really `1.18.4`?

**Comment by BioGeek** [comment]
The command `snap info microk8s` doesn't work when you have installed microk8s on Windows. So I would also appreciate a `microk8s version` command.

**Comment by jdallen-a10** [comment]
This isn't working in my 1.20.2 version:

```
root@mkube1:~# cat ingress-dashboard.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ redirect;
spec:
  # https://kubernetes.io/docs/concepts/services-networking/ingress/
  # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
  rules:
  - http:
      paths:
      - path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443

root@mkube1:~# microk8s kubectl apply -f ingress-dashboard.yaml
ingress.networking.k8s.io/dashboard created
root@mkube1:~# microk8s kubectl get ing -A
NAMESPACE     NAME        CLASS    HOSTS   ADDRESS   PORTS   AGE
kube-system   dashboard   <none>   *                 80      11s

```

Last lines of the ingress container logs:
```
I0225 21:04:04.660923       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583555", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress kube-system/dashboard
I0225 21:04:04.661260       6 controller.go:141] Configuration changes detected, backend reload required.
I0225 21:04:04.745626       6 controller.go:157] Backend successfully reloaded.
I0225 21:04:28.628083       6 status.go:275] updating Ingress kube-system/dashboard status from [] to [{127.0.0.1 }]
I0225 21:04:28.641134       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583595", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/dashboard
```

What am I doing wrong here?

**Comment by rcompos** [comment]
Implementing a CLI version argument would be a courtesy to the entire microk8s community.  The ability to query the version of a CLI command is near ubiquitous and just makes sense.  I found this issue after attempting to determine the microk8s version myself, being in disbelief that a version argument was excluded, then googling for the official method.

Verifying the version at the system level with snap  info doesn't provide a definitive value.  It provides an assumption.

**Comment by ktsakalozos** [comment]
Hi, there is also the `microk8s kubectl version` command that will get you the version of the Kubernetes cluster.

**Comment by kamyar** [comment]
Was very confused when `microk8s version` did not work, please add this command.

**Comment by glebsts** [comment]
I came here with same problem. Actually found this fresh (~2 weeks) PR: https://github.com/canonical/microk8s/pull/3078

**Comment by neoaggelos** [comment]
Came here due to stale bot, this issues seems to have flown under the radar. MicroK8s has for a number of releases now had:

```
$ microk8s version
MicroK8s v1.26.1 revision 4595
```
