### ISSUE TITLE
microk8s reset is slow

### ISSUE THREAD

**Issue by cmars** [canonical/microk8s#1291]
`microk8s reset` takes at least several minutes on my laptop and heats it up considerably. I've only deployed a modest application with 3 application pods, postgres and a cronjob.

`sudo snap remove microk8s && sudo snap install microk8s --classic && microk8s enable ...` takes way less time. Definitely under a minute, and not resource intensive at al.

**Comment by balchua** [comment]
Hi, `microk8s reset` tries to disable all addons if it is enabled and then remove all workloads, crds, apiservices etc interacting with the cluster using `kubectl`.  It goes through all standard kubernetes checks and validations.  Yes it tends to be intensive most especially if you have lots of workloads or kubernetes resources in the cluster.

The difference between `microk8s reset` and `snap remove` is that the former keeps all your customized configurations of the cluster components such as kubelet, api server, containerd intact.

While `snap remove` will just nuke it,  leaving nothing behind, except the snap backup (if you don't specify `--purge`).

That is why `snap remove` is faster.  Personally if i don't need to retain the customizations i had or i just use all defaults, i use `snap remove`.

**Comment by EnziinSystem** [comment]
Me too,  spent 30+ minutes with a simple application.

**Comment by ktsakalozos** [comment]
In most cases I've seen `microk8s.reset` gets stuck because when a namespaces cannot be deleted [1]. There are some proposed workarounds in the upstream issue.

I wonder if instead of waiting for a "clean" reset by kubernetes we may be able to erase the etcd database in our reset script.

[1] https://github.com/kubernetes/kubernetes/issues/60807

**Comment by balchua** [comment]
That would mean we need 2 different clean approach, one for etcd and one for dqlite.

**Comment by GrowingDev** [comment]
Run after the installation microk8s reset!

**Comment by gerrywastaken** [comment]
> The difference between `microk8s reset` and `snap remove` is that the former keeps all your customized configurations of the cluster components such as kubelet, api server, containerd intact.

That's not really the docs make it sound:

> This command is used to return the MicroK8s node to the default initial state.
> [...]
> All addons will be disabled and the configuration will be reinitialised.
-- https://microk8s.io/docs/commands#heading--microk8s-reset

> That is why `snap remove` is faster.

From the docs I got the impression that the point of reset was that it was easier than having to reinstall everything.

> This commands makes it easy to revert your MicroK8s to an ‘install fresh’ state without having to reinstall anything.
-- https://microk8s.io/docs/commands#heading--microk8s-reset

Your comment comes across very differently to the docs and I suspect most people trying to use reset likely don't actually want the thing that reset does and actually want a full reset.
