### ISSUE TITLE
microk8s cleaner/clearer failure on vanilla LXD

### ISSUE THREAD

**Issue by doismellburning** [canonical/microk8s#1404]
I recently installed the microk8s snap on a vanilla LXD container. At the time I hadn't come across https://microk8s.io/docs/lxd and it took a little while before I noticed that some components hadn't started up properly and I found my way to that doc.

Having found the documentation, it's excellent, thank you - following the instructions there left me with a very happy microk8s instance. From a usability perspective however, I'd really appreciate it if microk8s were able to perform some kind of initial check and flag up the potential problem (and direct me to the appropriate doc)

As it stands, my rough debugging process looked like:

1. Realise my instance wasn't fully running
2. Run `microk8s status` and be told `microk8s is not running. Use microk8s inspect for a deeper inspection.`
3. Run `microk8s inspect` as instructed and see `FAIL:  Service snap.microk8s.daemon-kubelet is not running`, `For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelet`
4. Run `sudo journalctl -u snap.microk8s.daemon-kubelet` and see `server.go:274] failed to run Kubelet: failed to create kubelet: open /dev/kmsg: no such file or directory`
5. Realise that I probably needed to look at my LXD setup and found https://microk8s.io/docs/lxd

The guidance microk8s gave me from steps 2 to 4 was incredibly nice - I'd just really appreciate an initial "looks like you're on LXD but you haven't done these things" check please!

**Comment by ktsakalozos** [comment]
Hi @doismellburning 

Thank you for the suggestion. Here is how we could approach this.

In the suggest_fixes of the inspect script [1], we could cat the `/proc/1/environ` and if we see something like `container=lxc` we would know if we are on an lxc container. Then we could try to see if `/dev/kmsg` is available. If not show a message that possibly the profile is missing and point the user to the docs page.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh#L106

**Comment by nwneisen** [comment]
Based on #1425, is this issue completely finished?

**Comment by ktsakalozos** [comment]
There is no initial check as it was requested. The missing profile is detected if you call `microk8s instpect`.
