### ISSUE TITLE
OCI runtime exec failed: apparmor failed to apply profile: write /proc/self/attr/exec

### ISSUE THREAD

**Issue by tringuyen-yw** [canonical/microk8s#1454]
Maybe this is a duplicate of #784 and #1214 This issue give you a way to reproduce the issue easily

```
$ snap list microk8s
Name      Version  Rev   Tracking     Publisher   Notes
microk8s  v1.18.6  1574  latest/edge  canonical✓  classic
```

Install Cassandra Operator:
```
$ kubectl apply -f https://raw.githubusercontent.com/datastax/cass-operator/v1.3.0/docs/user/cass-operator-manifests-v1.18.yaml
```

This operator creates a pod, which fails to start because Readiness and Liveness probes failed:

```
$ kubectl describe pod -l name=cass-operator

... etc ...
  Warning  Unhealthy  47s                kubelet, silverbullet  Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "e31b61839ad0e69bd1ff347909cf4d5e806b6aafdc9dad77c9b5e01915e4d2a9": OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "apparmor failed to apply profile: write /proc/self/attr/exec: operation not permitted": unknown

  Warning  Unhealthy  42s                kubelet, silverbullet  Readiness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "386494f90b0664325f012247856fca14e90313948b4113442505c261c0b6b8d4": OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "apparmor failed to apply profile: write /proc/self/attr/exec: operation not permitted": unknown
```

From #784 and #1214 I applied this workaround, which has fixed the issue. But yesterday, the pod could start but still failed the health check.

```
$ sudo apparmor_parser -R /var/lib/snapd/apparmor/profiles/snap.microk8s.daemon-containerd
$ sudo apparmor_parser -a /var/lib/snapd/apparmor/profiles/snap.microk8s.daemon-containerd
```

[inspection-report-20200730_105048.tar.gz](https://github.com/ubuntu/microk8s/files/5001972/inspection-report-20200730_105048.tar.gz)

**Comment by kfirfer** [comment]
Im getting the same errors, the workaround isn't sufficient
the pods keep getting the errors

**Comment by tringuyen-yw** [comment]
@kfirfer that was what I encounter yesterday too. But today the workaround seems to work OK. However, the most stable workaround is to comment out the line `allowPrivilegeEscalation: false` (around line 6380 in the yaml)

Hope to have some feedbacks of the microk8s dev team. This bug is long standing and doesn't show up when using KIND.

**Comment by yagya23** [comment]
Any update on issue?

**Comment by woshidama323** [comment]
Any update on issue?
