### ISSUE TITLE
microk8s.kubectl completion bash isn't working

### ISSUE THREAD

**Issue by vijaynagbs** [canonical/microk8s#1574]
Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20200916_172134.tar.gz](https://github.com/ubuntu/microk8s/files/5231947/inspection-report-20200916_172134.tar.gz)

`source <(microk8s.kubectl completion bash)` 
executing the above command has no effect. 

`microk8s.kubectl version`
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-34+09a4aa08bb9e93", GitCommit:"09a4aa08bb9e9328ae83e818c400278f5c43db3a", GitTreeState:"clean", BuildDate:"2020-09-02T11:29:54Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by balchua** [comment]
This is how i update my `microk8s kubectl` completion.

```shell
source <(microk8s kubectl completion bash | sed "s/complete -o default -F __start_kubectl kubectl/complete -o default -F __start_kubectl microk8s kubectl/g")
```
So far it works for me.

**Comment by ktsakalozos** [comment]
Thank you for spotting this @vijaynagbs.

I am testing now that `microk8s.kubectl <tab><tab>` works. What does not work is the `microk8s kubectl <tab><tab>` (without the dot). Until we get this fixed, the current workaround is to use the command shared above https://github.com/ubuntu/microk8s/issues/1574#issuecomment-695161786

**Comment by GuoLiuFang** [comment]
`vim ~/.bash_aliases`
# add the fllowing 
alias kubectl='microk8s kubectl'
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
source /usr/share/bash-completion/bash_completion
source <(kubectl completion bash)
