### ISSUE TITLE
enable cilium plugin hangs 

### ISSUE THREAD

**Issue by belsakn** [canonical/microk8s#1603]
Hey, 

When I try to enable the cilium plugin the process hangs forever. 
The problem is that cilium pod can't run `kubectl -n kube-system logs cilium-8hv45`:
```
level=warning msg="+ ip link set cilium_vxlan up" subsys=daemon
level=warning msg="RTNETLINK answers: Address already in use" subsys=daemon
level=error msg="Error while initializing daemon" error="exit status 2" subsys=daemon
level=fatal msg="Error while creating daemon" error="exit status 2" subsys=daemon
```
Here are the tarball logs from `microk8s.inspect`: [inspection-report-20200928_092626.tar.gz](https://github.com/ubuntu/microk8s/files/5290567/inspection-report-20200928_092626.tar.gz)
Not sure what is going on, hope someone can help

**Comment by ktsakalozos** [comment]
Hi @belsakn 

Issue [1] describes the problem. The enable script in [2, 3] removes any vxlan interfaces.

Is this issue reproducible? Can you share what exactly the output of the `microk8s enable cilium` command is?

[1] https://github.com/cilium/cilium/issues/8990
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.cilium.sh#L27
[3] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L58

**Comment by belsakn** [comment]
@ktsakalozos yes it's reproducible at least on my machine. I wanted to re-deploy microk8s and it started to happen, and now i can't deploy microk8s with cilium.

`microk8s enable cilium` :
```
Enabling Helm 3
Fetching helm version v3.0.2.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0   150k      0  0:01:18  0:01:18 --:--:--  525k
Helm 3 is enabled
Restarting kube-apiserver
Restarting kubelet
Enabling Cilium
Fetching cilium version v1.6.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    241      0 --:--:-- --:--:-- --:--:--   241
100 21.1M    0 21.1M    0     0   874k      0 --:--:--  0:00:24 --:--:--  662k
Deploying /var/snap/microk8s/1710/actions/cilium.yaml. This may take several minutes.
configmap/cilium-config created
serviceaccount/cilium created
serviceaccount/cilium-operator created
clusterrole.rbac.authorization.k8s.io/cilium created
clusterrole.rbac.authorization.k8s.io/cilium-operator created
clusterrolebinding.rbac.authorization.k8s.io/cilium created
clusterrolebinding.rbac.authorization.k8s.io/cilium-operator created
daemonset.apps/cilium created
deployment.apps/cilium-operator created
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
Waiting for daemon set "cilium" rollout to finish: 0 of 1 updated pods are available...
```

**Comment by ktsakalozos** [comment]
@belsakn does this happen on `latest/stable` and `1.18/stable` channels as well?

**Comment by belsakn** [comment]
@ktsakalozos yes it is the same problem

**Comment by belsakn** [comment]
But i see when i deploy `latest/stable` there atre

**Comment by belsakn** [comment]
@ktsakalozosi did a test on fresh install ubuntu and with `1.18/stable` i didn't have any problems. I will test it with `latest/stable` and see
BTW why is `calico` enabled by default in `latest/stable` i see pods being deployed to `kube-system` namespace in fresh microk8s installation ?

**Comment by balchua** [comment]
@belsakn from 1.19 calico is the default cni.

**Comment by fuomag9** [comment]
I still get the same issue in the `latest/stable`
