### ISSUE TITLE
FAIL:  Service snap.microk8s.daemon-apiserver is not running

### ISSUE THREAD

**Issue by rasoolasik** [canonical/microk8s#1627]
@ktsakalozos @freeekanayaka  Hi I am new to microk8s..facing the same issue from morning  which mention above i have attached my tarball
```
microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1710/inspection-report-20201006_105830.tar.gz

```
from master:
```
ubuntu@ip-xxxx:~/s2Shape_Stacks/engine-2.0$ microk8s kubectl get nodes
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

from node :
```
kubectl get node
NAME               STATUS     ROLES    AGE    VERSION
ip-x-x-x-x      NotReady   <none>   11d    v1.19.2-34+1b3fa60b402c1c
ip-x-x-x-x   Ready      <none>   9d     [v1.19.2-34+1b3fa60b402c1c
ip-x-x-x-x    Ready      <none>   5d6h   v1.19.2-34+1b3fa60b402c1c

```
[inspection-report-20201006_105830.tar.gz](https://github.com/ubuntu/microk8s/files/5333335/inspection-report-20201006_105830.tar.gz)

**Comment by balchua** [comment]
Hi @rasoolasik 
Thanks for using MicroK8s.

Based on the logs of the apiserver, this seems to be similar to #1598 

Currently the team is working on resolving that issue.  You can follow the details in the issue mentioned above.

The channel `latest/edge` comes with the fixes which according to some users looks promising.  You may want to try that channel out.

Just a word of caution, when there is a push to the master branch, your cluster will get some updates and may cause some temporary disruptions.  

Apologies for the inconvenience.

**Comment by rasoolasik** [comment]
@balchua 

Hi thanks for the reply.. refreshing to channel latest/edge same problem remains at the end.. 
```
$ sudo snap refresh microk8s --channel=latest/edge
error: cannot perform the following tasks:
- Run configure hook of "microk8s" snap if present (run hook "configure":
-----
++ date +%s
+ start_timer=1601993720
+ timeout=120
+ KUBECTL='/snap/microk8s/1745/kubectl --kubeconfig=/var/snap/microk8s/1745/credentials/client.config'
+ sleep 5
++ date +%s
+ now=1601993730
+ [[ 1601993730 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993735
+ [[ 1601993735 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993740
+ [[ 1601993740 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993745
+ [[ 1601993745 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993750
+ [[ 1601993750 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993755
+ [[ 1601993755 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993760
+ [[ 1601993760 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993765
+ [[ 1601993765 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993770
+ [[ 1601993770 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993775
+ [[ 1601993775 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993780
+ [[ 1601993780 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993785
+ [[ 1601993785 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993790
+ [[ 1601993790 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993796
+ [[ 1601993796 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993801
+ [[ 1601993801 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993806
+ [[ 1601993806 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993811
+ [[ 1601993811 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993816
+ [[ 1601993816 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993821
+ [[ 1601993821 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993826
+ [[ 1601993826 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993831
+ [[ 1601993831 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993836
+ [[ 1601993836 > 1601993840 ]]
+ sleep 5
++ date +%s
+ now=1601993841
+ [[ 1601993841 > 1601993840 ]]
+ break
+ /snap/microk8s/1745/kubectl --kubeconfig=/var/snap/microk8s/1745/credentials/client.config apply -f /var/snap/microk8s/1745/args/cni-network/cni.yaml
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
-----)

```

is there any quick fix ?.. and i had deployed apps on the cluster.. is that gone already ? i was trying to fix this problem without reinstalling .. Thanks

**Comment by ktsakalozos** [comment]
Hi @rasoolasik, you cannot refresh to the `latest/edge` channel because the API server in that node is crashing. You need to `snap remove microk8s` on the failing node. Then call `microk8s remove-node <failing-node> --force` from a working node so as to remove it from the k8s cluster. Then `snap install microk8s --classic --channel=latest/edge` and have the new node join the cluster again.

**Comment by rasoolasik** [comment]
@ktsakalozos Thanks for point out those things.. my master got crashed.. how to make that server as master agian..

**Comment by ktsakalozos** [comment]
> how to make that server as master agian.

If you go into any other node, does `microk8s.kubectl get all -A -o wide` work? In an HA setup any node should be able to act as master.

**Comment by rasoolasik** [comment]
@ktsakalozos i was waiting for your reply.. as i dnt have time yesterday i downgrade to 1.18/stable.. but i don't know the fact that it was acting as an HA cluster...and  in 1.19 it was working on all the nodes.. and i changed to 1.18 yesterday.. and my cluster has one master where i used `microk8s add-node`

**Comment by ktsakalozos** [comment]
@rasoolasik apologies for not replying. Going to 1.18/stable is a good choice while we address the 1.19 issues.

**Comment by krk628** [comment]
It's a CNI issue.  CNI isn't coming up, so the apiserver never listens on 16443, and kubelet never joins.

**Comment by marquestanislau** [comment]
> Hi @rasoolasik, you cannot refresh to the `latest/edge` channel because the API server in that node is crashing. You need to `snap remove microk8s` on the failing node. Then call `microk8s remove-node <failing-node> --force` from a working node so as to remove it from the k8s cluster. Then `snap install microk8s --classic --channel=latest/edge` and have the new node join the cluster again.
> 
> The pods on the failing node should have been rescheduled on the Ready nodes. You can confirm this with `microk8s.kubectl get all -A -o wide`

It worked for me. Thank you!

**Comment by koralgooll** [comment]
I have similar problem with version 1.25. I have use those commands. As unexpected side effect I have seen downgrade of version to 1.24.
```bash
snap remove --purge microk8s
sudo snap install microk8s --classic
```
