### ISSUE TITLE
Failed to enable dns (undefined symbol: p11_kit_uri_get_slot_info)

### ISSUE THREAD

**Issue by thibgc** [canonical/microk8s#1651]
Unable to enable DNS in the 1.18 track on Fedora 32:

```
[lockss@localhost thib]$ sudo snap install microk8s --classic --channel=1.18/stable
[sudo] password for lockss: 
microk8s (1.18/stable) v1.18.9 from Canonical✓ installed
[lockss@localhost thib]$ microk8s enable dns
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
systemctl: /snap/microk8s/1702/usr/lib/x86_64-linux-gnu/libp11-kit.so.0: no version information available (required by /usr/lib/systemd/libsystemd-shared-245.so)
systemctl: symbol lookup error: /usr/lib/systemd/libsystemd-shared-245.so: undefined symbol: p11_kit_uri_get_slot_info, version LIBP11_KIT_1.0
Failed to enable dns
```

This error message is identical to those reported in #1034 which led to a fix in v1.18.3. Because that issue is marked Closed, new comments posted about v1.18.9 may not get noticed, so I thought it would be better to open a new issue.

`microk8s inspect` tarball attached: [inspection-report-20201015_095152.tar.gz](https://github.com/ubuntu/microk8s/files/5386565/inspection-report-20201015_095152.tar.gz)

I'm pretty sure this is also happening on Arch Linux, but not CentOS 7.6, CentOS 8, Ubuntu 20.04 LTS, Debian 10.

(Please note that this came up as part of an application that requires installing MicroK8s from the 1.18/stable channel -- "switch to 1.19" won't solve the problem.)

Cc: @danberindei

**Comment by sbharathi** [comment]
Yes. Happening in Arch Linux. I am using microk8s 1.17/stable
> systemctl: /snap/microk8s/1701/usr/lib/x86_64-linux-gnu/libp11-kit.so.0: no version information available (required by /usr/lib/systemd/libsystemd-shared-246.so)
> systemctl: symbol lookup error: /usr/lib/systemd/libsystemd-shared-246.so: undefined symbol: p11_kit_uri_get_slot_info, version LIBP11_KIT_1.0
> Failed to enable dns

**Comment by twaananen** [comment]
I have this same issue with v1.20.6 on manjaro linux.

**Comment by ktsakalozos** [comment]
> I have this same issue with v1.20.6 on manjaro linux.

Can you try the `latest/edge` channel?

`sudo snap install microk8s --classic --channel=latest/edge`
