### ISSUE TITLE
VolumeSnapshot support

### ISSUE THREAD

**Issue by nemo83** [canonical/microk8s#1686]
Hi,

first of all thanks for the great project. I'm running a 3 nodes k8s cluster on rpi4 and it's a fantastic to have such powerful k8s just running on a desk at home.

I'm using quite a few PVC on this clusters and it would be amazing if I could use `VolumeSnapshot` too. 

I'm running Microk8s 1.19 and I *think* Snapshot should be supported from 1.17.

This is what I see when I try to install:

```
ubuntu@rpi-one:~/cardano-node-builder$ cat snap-test.yaml
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
  namespace: cardano-relay
spec:
  source:
    persistentVolumeClaimName: cardano-node-tau
ubuntu@rpi-one:~/cardano-node-builder$ k apply -f snap-test.yaml
error: unable to recognize "snap-test.yaml": no matches for kind "VolumeSnapshot" in version "snapshot.storage.k8s.io/v1beta1"
```

Am I doing anything wrong?

**Comment by balchua** [comment]
As it is a CRD I think you need to install the controller.
https://github.com/kubernetes-csi/external-snapshotter/blob/master/README.md#usage

**Comment by nemo83** [comment]
> As it is a CRD I think you need to install the controller.
> https://github.com/kubernetes-csi/external-snapshotter/blob/master/README.md#usage

Thanks, I thought it didn't come w/ the vanilla microk8s installation... it would be nice though if it was available as a plugin...

**Comment by balchua** [comment]
You're right it maybe nice to have it as an addon.

**Comment by balchua** [comment]
@nemo83 did the volumesnapshot worked for you?

**Comment by nemo83** [comment]
I haven't had a chance to test yet. Will hopefully try during the weekend.

:fingers-crossed:

Il giorno gio 29 ott 2020 alle ore 14:06 balchua <notifications@github.com>
ha scritto:

**Comment by nemo83** [comment]
> @nemo83 did the volumesnapshot worked for you?

Had some time in the last couple of days to try it out. Did some progress, but I get stuck at the creation of the initial PV/PVC.

It's my understanding that only csi-created volumes can be snapshotted ... for some reason, the driver creates both PV and PVC, it even binds it to the POD, but the POD fails to launch with the following error:
```
  Warning  FailedScheduling    3m32s (x2 over 3m32s)  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           3m29s                  default-scheduler        Successfully assigned default/sts-test-0 to pi-one
  Warning  FailedAttachVolume  89s                    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7a34eaf5-1b4a-4311-bc78-9ada94bdac5e" : attachdetachment timeout for volume ef36da64-35b8-11eb-9008-7e9e5b188750
  Warning  FailedMount         86s                    kubelet                  Unable to attach or mount volumes: unmounted volumes=[sts-test], unattached volumes=[sts-test default-token-jgcs6]: timed out waiting for the condition
```

But PV and PVC seem ok:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                               STORAGECLASS        REASON   AGE
pvc-7a34eaf5-1b4a-4311-bc78-9ada94bdac5e   100Mi      RWO            Delete           Bound    default/sts-test-sts-test-0                         csi-hostpath-sc              4m3s
ubuntu@pi-one:~$ k get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
sts-test-sts-test-0   Bound    pvc-7a34eaf5-1b4a-4311-bc78-9ada94bdac5e   100Mi      RWO            csi-hostpath-sc   4m5s
```

**Comment by nemo83** [comment]
Thanks for the pointer @balchua. After a month I finally had time to work on this and I'm delighted to announce I managed to create a helm chart, microk8s and raspberry pi compatible, that contains all that is needed to install and manage CSI Drivers, storage classes, volume storage class and snapshot controller: https://github.com/speedwing/csi-hostpath-helm

Using this chart it should be kinda ez to create a microk8s plugin/addon.

**Comment by balchua** [comment]
That's great @nemo83. 👍.
I don't know much about `VolumeSnapshot` but wondering if this is an alternative to the `storage` addon?
Thanks!

**Comment by nemo83** [comment]
Not exactly.

Storage addon installs a default `StorageClass` object that allows you to
automatically create/delete PV and PVC, without having to worry about
creating them manually.

VolumeSnapshot (well CRDs, plugin, driver and controller) allow you to
backup these volumes, clone them etc etc.

Now, unfortunately, specs for this plugin requires a specific driver,
called CSIDriver. There are multiple flavours and I guess, cloud provider,
will have their own. On microk8s we need to use the csi driver hostpath,
and unfortunately the default storage class, wont work coz it's not a CSI
Driver.

So if you want to use VolumSnapthots, you need to create a specific
storageclass.

The storage addon installs a storage class that can anyway co-exist with
the VolumeSnaphot one.


Il giorno lun 7 dic 2020 alle ore 10:35 balchua <notifications@github.com>
ha scritto:

**Comment by tdewin** [comment]
Hi, for those following this but don't want to apply something beta/modified, I actually found the openebs to be very useful:
https://github.com/openebs/zfs-localpv

The documentation mentions to modify the paths when you are using microk8s. You can modify the paths quite easily with a sed (hence why I'm posting, for my own ref). 
```
wget https://openebs.github.io/charts/zfs-operator.yaml
cat zfs-operator.yaml | sed  's#/var/lib/kubelet/#/var/snap/microk8s/common/var/lib/kubelet/#g' > zfs-operator-microk8s.yaml
```

You will have to also apply the storage snapshot yaml found here if you want to have snapshot support
https://github.com/openebs/zfs-localpv/blob/master/docs/snapshot.md

**Comment by Neirth** [comment]
I am reopening this issue as I have encountered the same problem. It would be interesting that the default cluster with the 'hostpath-storage' addon or similar supported by Canonical have this resource available.

In my case I am considering a productive deployment with no Space Quotas for the Edge, in prototyping phase. I was looking at the possibility of using Fairwind Gemini, but I'm afraid that without this possibility, little will be possible to do.
