### ISSUE TITLE
Cannot wait for MicroK8s install to be ready for use in script

### ISSUE THREAD

**Issue by dave-yotta** [canonical/microk8s#1710]
I'm starting microk8s in a CI pipeline [(Standard_DS2_v2,](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) basically 7gb ram, 2 vCPU cores, 14gb SSD.)

```
sudo snap install microk8s --classic
sudo microk8s status --wait-ready
sudo microk8s enable dns registry storage
sudo microk8s status --wait-ready
```

As per guidance on microk8s quickstart - however it does not wait for registry,storage and dns to be ready, which causes our pipeline to fail,e.g.:

```
Error: Get "https://10.1.0.4:16443/api/v1/namespaces/default/persistentvolumeclaims/local-mongo-pv-claim": dial tcp 10.1.0.4:16443: connect: connection refused
```
```
error when creating "/root/snap/microk8s/1769/tmp/temp.coredns.yaml": Post "https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterroles?fieldManager=kubectl-client-side-apply": read tcp 127.0.0.1:48292->127.0.0.1:16443: read: connection reset by peer
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "coredns", Namespace: ""
from server for: "/root/snap/microk8s/1769/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/coredns": dial tcp 127.0.0.1:16443: connect: connection refused
Failed to enable dns
```

Using normal kubernetes cli like this:
```
kube=$HOME/.kube
sudo rm -rf $kube
mkdir $kube
sudo microk8s kubectl config view --raw > $kube/config
sudo chmod 777 ~/.kube/config
```

Running  `kubectl get pods --all-namespaces` following the above outputs:
```
NAMESPACE            NAME                                          READY   STATUS              RESTARTS   AGE
kube-system          pod/calico-node-lmz2v                         0/1     Running             0          49s
kube-system          pod/calico-kube-controllers-847c8c99d-dp98t   0/1     ContainerCreating   0          49s
kube-system          pod/coredns-86f78bb79c-x7rl4                  0/1     ContainerCreating   0          25s
container-registry   pod/registry-9b57d9df8-ct8p2                  0/1     Pending             0          4s
kube-system          pod/hostpath-provisioner-5c65fbdb4f-xf224     0/1     ContainerCreating   0          3s
```

So I tried instead waiting for all pods:
```
for n in `kubectl get namespaces -o name`; do
    ns=${n:10}
    echo checking namespace $ns
    for p in `kubectl get pods -n $ns -o name`; do
        echo waiting for pod $p to be ready
        kubectl wait --for=condition=ready $p -n $ns  --timeout=-1s
    done
done
```

But this just gives me:
```
checking namespace kube-system
waiting for pod pod/calico-node-lmz2v to be ready
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
waiting for pod pod/calico-kube-controllers-847c8c99d-dp98t to be ready
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
waiting for pod pod/coredns-86f78bb79c-x7rl4 to be ready
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
waiting for pod pod/hostpath-provisioner-5c65fbdb4f-xf224 to be ready
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
checking namespace kube-public
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
checking namespace kube-node-lease
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
checking namespace default
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
checking namespace container-registry
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

Edit: Managed to get the tarball
[inspection-report-20201103_102630.tar.gz](https://github.com/ubuntu/microk8s/files/5480586/inspection-report-20201103_102630.tar.gz)

**Comment by balchua** [comment]
It looks like the network has changed.  Coz i can see this in the apiserver-kicker log

```
Nov 03 10:25:52 fv-az92-660 microk8s.daemon-apiserver-kicker[2792]: CSR change detected. Reconfiguring the kube-apiserver
```
When the kicker detects some change in the network it will reconfigure and restart the apiserver.  This is to help those who are moving from one network to another.

Im wondering whether you wait for the network to stabilize.

**Comment by dave-yotta** [comment]
Hmm I have no idea how to wait for the network to stabilize - can I turn off this kicker detection thing?  I only require access to the cluster from the node host I'm running from.

**Comment by balchua** [comment]
I think yes you can turn it off `systemctl stop snap.microk8s-daemon-apiservice-kicker`
You can give that a try though.
It might present a problem in the `latest/edge` channel wherein the apiservice-kicker will continue to install calico, when the snap configure phase is not able to install calico successfully in 2 mins.
This usually manifest on a slow server.

**Comment by dave-yotta** [comment]
Yeah just tried `sudo snap stop --disable microk8s.daemon-apiserver-kicker`.  Can we increase the 2min timeout on the snap install phase there, or install calcio manually?

**Comment by balchua** [comment]
As far as i know there is a snap install limit which is 5 mins.  

You can install calico manually the cni file is located in `/var/snap/microk8s/current/args/cni-network/cni.yaml`

For now can you check if the apiserver is stable when you stop the kicker?

**Comment by dave-yotta** [comment]
Thanks, I can document this incase it happens in the future - It would be helpful to have an install method without any timeouts however.

Lastly, in the case that the configure hook gets a timeout installing calcio, will `microk8s status --wait-ready` return a failure?

**Comment by dave-yotta** [comment]
Workaround looks good, thankyou @balchua !!! :)

**Comment by balchua** [comment]
I think `microk8s status` will fail if `kubectl get no` returns `NotReady`.  This will happen when cni is not installed.

**Comment by balchua** [comment]
@dave-yotta do you by any chance have `ipv6` on the machine?  For example when you do `hostname -I` does it show ips which are not ipv4?

**Comment by dave-yotta** [comment]
These are hosted build agents so I guess it depends on the image used (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md) - should be able to turn off ipv6 though.  Testing it would mean a chance for our pipelines to break though so we won't be doing that anytime soon :)

**Comment by johngrabner** [comment]
> @dave-yotta do you by any chance have `ipv6` enabled on the machine? For example when you do `hostname -I` does it show ips which are not ipv4? This can be the reason why the kicker is constantly restarting the apiservice.
> 
> If you can turn off ipv6 and then re-enable the kicker it shouldn't restart the apiservice.

My system is reporting "daemon-apiserver-kicker[33342]: CSR change detected" every 10 to 15 minutes but sporadically. I will turn off IP v6 to see if it helps, but for my edification what does ipv6 have to do this?

**Comment by balchua** [comment]
@johngrabner if you want to turn disable the kicker from detecting network changes you can follow the instructions below.  See if this helps.

https://github.com/ubuntu/microk8s/issues/1822#issuecomment-745335208

**Comment by dave-yotta** [comment]
Hi All, sorry I don't know, we're using kind now.
