### ISSUE TITLE
Microk8s install can fail with docker hub rate limiting

### ISSUE THREAD

**Issue by markbeierl** [canonical/microk8s#1711]
When installing Microk8s from a common infrastructure where many users share the same external IP address, it is very easy to trigger the new DockerHub pull rate limit policy.  Once that happens, it is no longer possible to install Microk8s.

Example output from microk8s.kubectl describe pod -n kube-system calico-node-mghbl:

```
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned kube-system/calico-node-mghbl to cicd3
  Normal   Pulling    12m (x4 over 14m)     kubelet            Pulling image "calico/cni:v3.13.2"
  Warning  Failed     12m (x4 over 14m)     kubelet            Error: ErrImagePull
  Warning  Failed     12m (x4 over 14m)     kubelet            Failed to pull image "calico/cni:v3.13.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/calico/cni:v3.13.2": failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/calico/cni/manifests/sha256:bbf7e3ac3f80d0a356a6c27b095bd313d1106f8ed84f85850816ed79295843c1: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Normal   BackOff    12m (x7 over 14m)     kubelet            Back-off pulling image "calico/cni:v3.13.2"
  Warning  Failed     4m33s (x39 over 14m)  kubelet            Error: ImagePullBackOff
```
[inspection-report-20201104_180022.tar.gz](https://github.com/ubuntu/microk8s/files/5489666/inspection-report-20201104_180022.tar.gz)

**Comment by balchua** [comment]
Thanks for reporting this one.  In this case, one should pre download the image tarball and load it using `microk8s ctr` command.

`microk8s ctr <the image tarball>`

***Note that there is no need to specify the `ctr` namespace as the `microk8s ctr` wrapper already provide it.***

Important images:

*  `calico/cni:v3.13.2`
*  `calico/node:v3.13.2`
*  `calico/kube-controllers:v3.13.2`
*  `coredns/coredns:1.6.6`

@ktsakalozos if we have option in the snap `configure` stage to sideload images located in `$SNAP_USER_HOME/images` (as an example). And make sure that the manifests are set with `imagePullPolicy: IfNotPresent` then we can reduce the rate limit policy when installing MicroK8s.
This may not be applicable for windows or mac MicroK8s.  Wdyt?

**Comment by markbeierl** [comment]
Of course, once this is hit, it is no longer possible to "pre" download the image :(

I would need to go to another machine that uses a different IP address when accessing docker hub and pull the image there and scp it over.  That is a workaround, but pretty clunky and needs to be properly documented.

**Comment by ktsakalozos** [comment]
Another approach to work around the dockerhub late limit is to have containerd login with a dockerhub account. That should involve updating `/var/snap/microk8s/current/args/containerd-template.toml` and restarting `microk8s.stop; microk8s.start`. Haven't tried it though.

Side loading images is something that would be very beneficial in the case of off-line deployments. Although I suspect you will have a private registry in such setups.

On the long run we should address the the dockerhub rate limit by moving some critical/often-used images into 
the https://rocks.canonical.com image registry.

**Comment by markbeierl** [comment]
Rocks is a good idea.  No action on the end user part would be required.

**Comment by markbeierl** [comment]
Once microk8s is installed, this will update it to use a specific registry for all further requests, but it does not solve the initial problem of installation if the rate limit has already been triggered:

```
sudo snap install microk8s --classic
sudo microk8s.status --wait-ready
sudo sed -i "s|https://registry-1.docker.io|http://YOUR_MIRROR:MIRROR_PORT|" /var/snap/microk8s/current/args/containerd-template.toml
sudo systemctl restart snap.microk8s.daemon-containerd.service
```

**Comment by eskaaren** [comment]
Replacing the mirror or adding auth doesn't work, seems like https://registry-1.docker.io without auth is hardcoded for docker.io. Also see:
https://github.com/ubuntu/microk8s/issues/1525
https://github.com/containerd/containerd/issues/4011

**Comment by shanewow** [comment]
Having same issue. Adding auth for docker.io is not working.

**Comment by aintbrokedontfix** [comment]
Any updates on this? The docker hub rate limits are really annoying.

**Comment by yanivpaz** [comment]
@balchua  is there any option to know in advance which images are needed?
I want to use your tip to try using https://gallery.ecr.aws/?searchTerm=projectcalico

**Comment by ktsakalozos** [comment]
Hi @yanivpaz, would you be interested in submitting a patch to use the calico images from ecr? The calico manifest is at https://github.com/ubuntu/microk8s/tree/master/upgrade-scripts/000-switch-to-calico/resources

**Comment by IanniF** [comment]
Hi, I've also encountered and struggled a lot on this issue and managed to find a way to add auth for docker's repositry. 
As mentioned @ktsakalozos, you can edit your `/var/snap/microk8s/current/args/containerd-template.toml` to add authentication to your docker repository.
The thing is that containerd's version has changed since microk8s 1.19 (from 1.2.5 to 1.3.7) so its configuration.
You can configure your authentication like so : 
```
...
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry-1.docker.io", ]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:32000"]
        endpoint = ["http://localhost:32000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."registry-1.docker.io".auth]
        username = "xxxxx"
        password = "xxxxx"
...
```
The "key" you mention for the "configs" part should match your hostname used in the endpoint array (without "https://").

Then you should restart your microk8s with `microk8s.stop; microk8s.start`.

**Comment by yanivpaz** [comment]
@ktsakalozos  The ECR solution will be good only for my accounts.
see: "Data transferred out from public repositories is limited by source IP when an AWS account is not used." ([link](https://aws.amazon.com/ecr/pricing/)) .

so we need another solution.  What about your previous solution to use https://rocks.canonical.com/ ?

**Comment by yanivpaz** [comment]
the workaround I temporarily used  :  
1. Identify which images are needed 
```
sudo microk8s kubectl  get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c
```

2. load the images from quay.io to local microk8s:
```
sudo microk8s start
podman pull  quay.io/calico/node:v3.13.2
podman save --quiet -o node_v3.13.2.tar quay.io/calico/node:v3.13.2
sudo microk8s ctr  images import --base-name calico/node:v3.13.2 ./node_v3.13.2.tar

podman pull  quay.io/calico/kube-controllers:v3.13.2
podman save --quiet -o kube-controllers_v3.13.2.tar quay.io/calico/kube-controllers:v3.13.2
sudo microk8s ctr  images import --base-name calico/kube-controllers:v3.13.2 ./kube-controllers_v3.13.2.tar
```

**Comment by johnatswoopsrch** [comment]
I am still hitting this issue, and will have to try to implement one of the hacks mentioned.

**Comment by neoaggelos** [comment]
Hi @johnatswoopsrch, you can also have a look at the documentation https://microk8s.io/docs/dockerhub-limits

**Comment by hyp3ri0n-ng** [comment]
That's a good resource from @neoaggelos, but it only works if you didn't (like me), try the stupid installation steps first. I jotted down some notes on what to do if you already did `microk8s start` and how to get around it in a stupid and annoying way, but hey it works so whatever.

#Notes on microk8s:

## installation:

`microk8s` start is broken start them up with `microk8s start`, it'll take a minute
run `microk8s.kubectl get pod --all-namespaces` and you'll see a bunch of pods failing
You officially have 5 minutes to edit the coredns pod or you're fu***d and need to delete
it and do this again. First set your editor so you don't end up a broken, sad person using vim,
so `export EDITOR=nano` or `emacs-nox`. Use the command `k edit pod coredns-864597b5fd-5pj5h -n kube-system` or
whatever the stupid pods name is, and search for "images" there will be two places to
change. Replace those stupid values with the right ones. Coredns doesn't supply an image
registry so you have to do it, only one that worked for me was EKR here:
`public.ecr.aws/eks-distro/coredns/coredns:v1.10.1-eks-1-28-latest`. This will quickly
become outdated so check out `https://gallery.ecr.aws/eks-distro/coredns/coredns` for
whatever version you want. You can do microk8s inspect and then do a find for the word
"error" like `find . -type f -exec grep -C 1 -i --color "error"` to get all the pulls that
failed - i.e. everything that canonical screwed up and doesn't seem to want to fix. Once
you edit that thing (again you have 5 minutes lol, it's like a movie bomb) it should pull
and start running. If you miss that time window just delete the stupid pod Then edit the others just like that one, they should just start to automatically pull.
Note the other ones explicitly define `docker.io/image_name`, I replaced docker with quay,
so `quay.io/image_name` (make sure you search the file for "docker" and replace it
anywhere you see it, it's in a bunch of places). They should start to pull, seemed like
they had a less aggressive pull retry backoff policy so not much rush on that. You should
be good to go now, for good measure i did `microk8s stop && microk8s start && microk8s
status` and it came back as all good.

Alternatively if you know you're going to install this just use `microk8s ctr image pull
quay.io/image_name` or even docker.io to pull them and
`public.ecr.aws/eks-distro/coredns/coredns:v1.10.1-eks-1-28-latest` for coredns,
BEFORE installing and it should just use the cache (i think, untested).
