### ISSUE TITLE
High Availability not working?

### ISSUE THREAD

**Issue by nguyenorlab** [canonical/microk8s#1717]
Hi all,
I have 3 nodes using Ubuntu 18.04 (Ram 4GB, SSD 30GB) on AWS. I have already install microk8s and basic setting (add repo, enable dns, enable storage, enable helm3) and focus to run Rocket.Chat on microk8s cluster. I facing with 2 issue as below flow:

1. 
--> Using helm3 to deploy Rocket.Chat on node01 (mongodb and rocketchat pod running OK)
--> HA cluster so I run the microk8s add-node command on node02 and node03 respectively
--> HA cluster status OK. I can get nodes and pods on every nodes.
--> I patch Rocket.Chat pod to NodePort for internet access OK.
--> So now, I created a AWS LoadBalancer with target is 3 nodes that I have 
--> health check of AWS LoadBalancer indicated that only node01 (the node has deployed Rocket.Chat) is healthy and node02, node03 are unhealthy. (health checks failed or Request timed out)
--> I try access Rocket.Chat via AWS LoadBalancer DNS (after add NodePort's port to AWS security) --> access OK
--> because the node02 and node03 is not healthy so the LoadBalancer makes no sense when I turn off node01, HA features have no meaning.
❓ In this case, have I lacked anything else? Please help me.

2. 
--> HA cluster via microk8s add-node command
--> HA cluster status OK. I can get nodes and pods on every nodes.
--> Using helm3 to deploy Rocket.Chat on node01
--> Pods have error "CrashLoopBackOff"
❓ In this case, what's problem is going on?

I attach my tarball of all nodes. Please check it and recommend for me. Thank you in advance.

![node02-after](https://user-images.githubusercontent.com/35364604/98353954-a904c000-2052-11eb-97e3-707e5b938451.PNG)
![node03-after](https://user-images.githubusercontent.com/35364604/98353963-ab671a00-2052-11eb-974d-0107f8b5762a.PNG)
[node02-after-inspection-report-20201106_100518.tar.gz](https://github.com/ubuntu/microk8s/files/5500608/node02-after-inspection-report-20201106_100518.tar.gz)
[node03-after-inspection-report-20201106_100523.tar.gz](https://github.com/ubuntu/microk8s/files/5500610/node03-after-inspection-report-20201106_100523.tar.gz)
[node01-inspection-report-20201106_094328.tar.gz](https://github.com/ubuntu/microk8s/files/5500612/node01-inspection-report-20201106_094328.tar.gz)
[node02-inspection-report-20201106_094332.tar.gz](https://github.com/ubuntu/microk8s/files/5500613/node02-inspection-report-20201106_094332.tar.gz)
[node03-inspection-report-20201106_094338.tar.gz](https://github.com/ubuntu/microk8s/files/5500614/node03-inspection-report-20201106_094338.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @nguyenorlab,

Since node01 is the one reporting "NotReady", could you attach its inspection tarball after the incident?

**Comment by nguyenorlab** [comment]
Hi @ktsakalozos,
Here is node01's tarball after I restart the instance. Thank you.
[inspection-report-20201106_113802.tar.gz](https://github.com/ubuntu/microk8s/files/5501034/inspection-report-20201106_113802.tar.gz)

**Comment by balchua** [comment]
I can see some logs from the apiservice-kicker restarting the apiserver.

```
CSR change detected. Reconfiguring the kube-apiserver
```
Wonder if there are some network changes happening in node1.

**Comment by balchua** [comment]
@nguyenorlab ignore my previous comment.  I looked at the last tarball you gave, it looks like `node01` is `Ready`.

**Comment by nguyenorlab** [comment]
@balchua thank you for your recommend.
Actually, as I mentioned in my post, I have enabled basic features for all 3 nodes (storage, dns, helm3)...
So what I should do in this case?

**Comment by balchua** [comment]
There are some ways that you nay want to try.

* Pin your mongodb together with the hostpath provisioner pod.  Make sure that they are always scheduled on the same node.  But there are repercussions to this.  If the node goes down they will not be scheduled elsewhere.
* You can setup an nfs server or use an nfs provisioner.  Again you dont want this to be scheduled elsewhere or the file system is lost.
* Try openebs or rook.
* Or use aws persistent storage.

*

**Comment by balchua** [comment]
@nguyenorlab are you still experiencing issues with regards to your storage?  From MicroK8s 1.21, we have included OpenEBS so you can use it for your multi node storage setup.

**Comment by nguyenorlab** [comment]
@balchua thank you for support. So now, I am using another method to run Rocket.Chat for test period. I will try to use MicroK8s v1.21 in near future.
Regards.
