### ISSUE TITLE
CNI not working

### ISSUE THREAD

**Issue by silborynirmata** [canonical/microk8s#1793]
I'm running 20.10 with btrfs.  I added  '--feature-gates="LocalStorageCapacityIsolation=false"' to /var/snap/microk8s/current/args/kubelet .  That gets kubelet working, but I'm unable to get a CNI working.  This was also an issue with flannel in a prior release.  The same node works with kubeadm and canal.

ssilbory@tower:~/nirmata/custom-scripts$ microk8s.kubectl -n kube-system get pods -A
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   calico-node-f47wk                         1/1     Running            0          9m11s
kube-system   calico-kube-controllers-847c8c99d-vv6qm   0/1     CrashLoopBackOff   6          9m11s
ssilbory@tower:~/nirmata/custom-scripts$ microk8s.kubectl -n kube-system -n kube-system logs calico-kube-controllers-847c8c99d-vv6qm
2020-12-04 19:13:02.923 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", HealthEnabled:true, SyncNodeLabels:true, DatastoreType:"kubernetes"}
W1204 19:13:02.924602       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-12-04 19:13:02.925 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2020-12-04 19:13:12.925 [ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-12-04 19:13:12.925 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
ssilbory@tower:~/nirmata/custom-scripts$ microk8s.inspect 
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

# Warning: iptables-legacy tables present, use iptables-legacy to see them
Building the report tarball
  Report tarball is at /var/snap/microk8s/1791/inspection-report-20201204_111525.tar.gz
ssilbory@tower:~/nirmata/custom-scripts$

**Comment by silborynirmata** [comment]
ssilbory@tower:~/nirmata/custom-scripts$ microk8s.inspect 
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

# Warning: iptables-legacy tables present, use iptables-legacy to see them
Building the report tarball
  Report tarball is at /var/snap/microk8s/1791
/inspection-report-20201204_111525.tar.gz

[inspection-report-20201204_111525.tar.gz](https://github.com/ubuntu/microk8s/files/5644962/inspection-report-20201204_111525.tar.gz)

**Comment by balchua** [comment]
@silborynirmata care to disable nftables.? See if it works.

https://v1-15.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend

**Comment by jcdutton** [comment]
How many nodes in the cluster?
If less that 3. Try with:
microk8s disable ha-cluster

**Comment by daramir** [comment]
> How many nodes in the cluster?
> If less that 3. Try with:
> microk8s disable ha-cluster

This worked for me and it's sad :joy:
