### ISSUE TITLE
Can't use gitlab-runner

### ISSUE THREAD

**Issue by bvp416** [canonical/microk8s#1814]
I am unable to communicate with the API using kubectl from the gitlab-runner that I have registered.
I cannot ping the host but I can ping public IPs

From a debug pod, I can ping the host, other hosts on the LAN, and curl the API. I can even use kubectl.

I have coreDNS enabled. I also edited the config to include my router IP in the forward directive.
Seems to only be an issue from within the gitlab-runner on microk8s

[tarball.txt](https://github.com/ubuntu/microk8s/files/5682440/tarball.txt)

**Comment by balchua** [comment]
Your `gitlab-runner` is running inside a pod?  And it couldn't reach where?
Sorry im just trying to understand your setup.

**Comment by joes** [comment]
I am at least able to use Gitlab Runner in our cluster (version 1.20).
