### ISSUE TITLE
Microk8s error frequently

### ISSUE THREAD

**Issue by falgifaisal** [canonical/microk8s#1822]
Hi all,

I have some question.

Why my microk8s error frequently ?
Why i need to restart it a few times for it to work properly ? This is different from microk8s on other servers where I only need to restart once it works properly
Thank you
[inspection-report-20201210_091512.tar.gz](https://github.com/ubuntu/microk8s/files/5694193/inspection-report-20201210_091512.tar.gz)

This is the log. Thank you

**Comment by ktsakalozos** [comment]
Hi @falgifaisal 

MIcroK8s has a service that periodically check for changes on your network, reconfigures and restarts the API server if needed. Looking at this services logs (`journalctl -n 1000 -u snap.microk8s.daemon-apiserver-kicker`) I see a few restarts. To stop the API server restarts even if the network changes you can configure it to use a specific interface. To do so, edit `/var/snap/microk8s/currect/args/kube-apiserver` and add one of the arguments `--advertise-address`, `--bind-address` as described in [1]; then do a `microk8s.stop; microk8s.start`.


[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by falgifaisal** [comment]
> Hi @falgifaisal
> 
> MIcroK8s has a service that periodically check for changes on your network, reconfigures and restarts the API server if needed. Looking at this services logs (`journalctl -n 1000 -u snap.microk8s.daemon-apiserver-kicker`) I see a few restarts. To stop the API server restarts even if the network changes you can configure it to use a specific interface. To do so, edit `/var/snap/microk8s/currect/args/kube-apiserver` and add one of the arguments `--advertise-address`, `--bind-address` as described in [1]; then do a `microk8s.stop; microk8s.start`.
> 
> [1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

Hi, 

Thank you for the response.

I did a few restarted because my pod got error "Out of memory" for java before i can find how to increase jvm for my deployment. So i stop and start microk8s to drop the error.

And do you know why when I use local repository like localhost:32000 for my deployment, the pod takes too long to run ? 
But if i not use local repository, it just takes about 15 - 20 minutes to up and running. But if I use local repository like localhost:32000 it can takes more than 20 minutes ? so I have to restart several times to get up and running for my pod.

Thank you for your help.

Regards,

Falgi Faisal

**Comment by johngrabner** [comment]
@ktsakalozos ktsakalozos

I am experiencing lots (every 2 minutes to 15 minutes) of CSR change detected in the snap.microk8s.daemon-apiserver-kicker logs.

```
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: Signature ok
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: Getting CA Private Key
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: unable to write 'random state'
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: Signature ok
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: subject=/CN=front-proxy-client
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: Getting CA Private Key
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: unable to write 'random state'
Apr 19 16:07:40 john-trx40-designair microk8s.daemon-apiserver-kicker[1653]: CSR change detected. Reconfiguring the kube-apiserver
```

So suspect it's the same issue.  But I'm not sure how to set the bind address as per your instructions.  My host IP address is 99.153.71.9, so is this what I place in the bind address ?

2095/args/kube-apiserver with the bind address addition:

```
--cert-dir=${SNAP_DATA}/certs
--service-cluster-ip-range=10.152.183.0/24
--authorization-mode=AlwaysAllow
--service-account-key-file=${SNAP_DATA}/certs/serviceaccount.key
--client-ca-file=${SNAP_DATA}/certs/ca.crt
--tls-cert-file=${SNAP_DATA}/certs/server.crt
--tls-private-key-file=${SNAP_DATA}/certs/server.key
--kubelet-client-certificate=${SNAP_DATA}/certs/server.crt
--kubelet-client-key=${SNAP_DATA}/certs/server.key
--secure-port=16443
--token-auth-file=${SNAP_DATA}/credentials/known_tokens.csv
--insecure-port=0
--storage-backend=dqlite
--storage-dir=${SNAP_DATA}/var/kubernetes/backend/
--allow-privileged=true
--bind-address=99.153.71.9

# Enable the aggregation layer
--requestheader-client-ca-file=${SNAP_DATA}/certs/front-proxy-ca.crt
--requestheader-allowed-names=front-proxy-client
--requestheader-extra-headers-prefix=X-Remote-Extra-
--requestheader-group-headers=X-Remote-Group
--requestheader-username-headers=X-Remote-User
--proxy-client-cert-file=${SNAP_DATA}/certs/front-proxy-client.crt
--proxy-client-key-file=${SNAP_DATA}/certs/front-proxy-client.key
#~Enable the aggregation layer
```

After microk8s stop and start, kubectl commands all fail:

```
microk8s kubectl get pods
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

I would appreciate your experitze to point me in the correct direction.

**Comment by johngrabner** [comment]
@balchua
You referred me here but as you can see not sure what bind address to use.

Also, is kicker seeing real network changes? None of my other apps complain of connectivity. Any way to see what changes kicker is seeing? Are they even real?

Finally, I suspect the kicker is causing many to have failures and these failure are obfuscated by all the daemonds being restarted.

**Comment by balchua** [comment]
@johngrabner try `--bind-address=0.0.0.0`

**Comment by erulabs** [comment]
Thanks @balasu - I believe I solved it! Setting a bind address bypasses the issue, but for a more real fix:

It does seem like "CSR change detected" is firing too often. I took a look:

https://github.com/ubuntu/microk8s/blob/c9d10eaa89c014cd3a159f1829a65f5125ee754c/microk8s-resources/actions/common/utils.sh#L393-L443

Which seems to generate a CSR based on the results of "get_ips": https://github.com/ubuntu/microk8s/blob/c9d10eaa89c014cd3a159f1829a65f5125ee754c/microk8s-resources/actions/common/utils.sh#L360-L379

And on my RaspberryPi OS, I seem to be gaining and losing a `169.` address every few seconds:

```
root@pibox:~# ip -o -4 addr list vxlan.calico
5: vxlan.calico    inet 10.1.173.192/32 brd 10.1.173.192 scope global vxlan.calico\       valid_lft forever preferred_lft forever
root@pibox:~# ip -o -4 addr list vxlan.calico
5: vxlan.calico    inet 10.1.173.192/32 brd 10.1.173.192 scope global vxlan.calico\       valid_lft forever preferred_lft forever
5: vxlan.calico    inet 169.254.5.20/16 brd 169.254.255.255 scope global noprefixroute vxlan.calico\       valid_lft forever preferred_lft forever
root@pibox:~# ip -o -4 addr list vxlan.calico
5: vxlan.calico    inet 10.1.173.192/32 brd 10.1.173.192 scope global vxlan.calico\       valid_lft forever preferred_lft forever
```

(Those commands are executed after about a second back to back)

Scratching my head a little, I remembered `169.254` is a DHCP failure address - so I checked and sure enough, this OS has `dhcpcd` setup to probe all interfaces!

So, while I don't expect microk8s can do much about dhcpcd on the system, I do think a good "fix" is to make `get_ips()` just ignore any address with a `169.254` address. This should resolve the CSR re-generations, the API restarts, the high load, and all of the other issues caused by this.

**Comment by erulabs** [comment]
Hey @ktsakalozos - I wonder if you wouldn't mind taking a peek at the solution in #2617 ? I believe it ought to fix the problem for many users  👯 

Thank you!

**Comment by johngrabner** [comment]
I can test later this week.  How can I get the current install version and confirm that it is still available to reinstall if the new version does not workout?

**Comment by falgifaisal** [comment]
> Heya @falgifaisal and @johngrabner - I wonder if you're still seeing this issue with the newest release and #2617 patched? You can use `snap install microk8s --channel=latest/edge --classic` to test the latest version which has that patch and hopefully fixes the api-server restarting issue!

Hi,

thanks for this information, i'll test in soon. 
but, to prevent this issue in the future, should i setting a bind address in /var/snap/microk8s/current/args/kube-apiserver ?

**Comment by mkalcok** [comment]
I'm running **strictly confined** microk8s (`v1.27.4`) and I've ran into the same issue of `apiserver-kicker` frequently restarting api server. I decided to bind the api server to single interface (via `--bind-address` argument) as suggested by @johngrabner and ran into similar issue of other services failing to connect to apiserver because they were trying to use `127.0.0.1:16443` address.

What helped me fix this was updating credential configs in `/var/snap/microk8s/current/credentials`. All these files have entry like this: `server: https://127.0.0.1:16443`. Updating it to the IP used for `--bind-address` and restarting `microk8s` fixed the issue for me.

**Comment by elirenato** [comment]
@ktsakalozos Just to let you know that has been passed almost 4 years and your comment is still useful. :) 

All containers of my microk8s environment used to restart from time to time but after I added `--bind-address=0.0.0.0` to `/var/snap/microk8s/current/args/kube-apiserver` file, it's working fine now.

Thanks.

**Comment by zeitmeister** [comment]
Yes, thank you @ktsakalozos!

Your comment also saved my project. Also added --bind-address=0.0.0.0 to the kube-apiserver file and no restarts anymore.
