### ISSUE TITLE
Microk8s crashes when attempting to join cluster

### ISSUE THREAD

**Issue by sean-abbott** [canonical/microk8s#1880]
I'm attempting to set up a mixed architecture microk8s cluster. I have an x86 node that I'm using as the starting leader node and 2 rasppi4b nodes.

Attempting to join one of the pik8s nodes has failed 3 times and worked once. 

The latest attempt looked like:
```
buntu@pidev2:~$ microk8s join 192.168.1.5:25000/<token>
Contacting cluster at 192.168.1.5
Waiting for this node to finish joining the cluster. ..  
ubuntu@pidev2:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
ubuntu@pidev2:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT 
The change can be made persistent with: sudo apt-get install iptables-persistent
WARNING:  Docker is installed. 
File "/etc/docker/daemon.json" does not exist. 
You should create it and add the following lines: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/1892/inspection-report-20210109_232609.tar.gz
ubuntu@pidev2:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

This is the second attempt on this node. The second attempt on a another rasppi node succeeded. 

The nodes are identical (set up with ansible) and I've verified I can connect from both to the leader node on 25000. ufw is not running on any node.

I'll attach the inspection reports as soon as I figure out ow to get githbu to let me.

**Comment by sean-abbott** [comment]
Well, github hates me so: https://drive.google.com/drive/folders/1Q1gPFVpJBnewOLCEDn01Uq0EgckT4pvo?usp=sharing

**Comment by ktsakalozos** [comment]
Looking at the logs `journalctl -u snap.microk8s.daemon-cluster-agent` I see this strange error https://pastebin.ubuntu.com/p/Yjgt5CsxTp/

What can you tell me about the nodes? Are the ansible scripts available online?

**Comment by sean-abbott** [comment]
They're ubuntu 20.04 running on raspberry pi B 4gb, they used to be joined to a different cluster, but I completely uninstalled and re-installed microk8s before attempting to join them to this cluster.

https://github.com/sean-abbott/pi-k8s/tree/add_dev_cluster/ansible

(that repo should have no private info available, so please let me know if I missed something) 

The recent work to set them up is in the linked branch.

**Comment by sean-abbott** [comment]
Do you want the logs from the node where I ran "add-node'?

**Comment by kquinsland** [comment]
I'm a +1 for this issue.

I've just had a node fall out of the cluster and I can't add it back. `microk8s stop/reset` and `snap remove --purge` does not work. I always get a return code of `0` after i run the `microk8s join` call, but when tailing the `snap.microk8s.daemon-apiserver.service` logs on any of the nodes already in the cluster, i see messages like this:

```
Jan 12 22:21:25 node01 microk8s.daemon-apiserver[64883]: I0112 22:21:25.106599   64883 clientconn.go:948] ClientConn switching balancer to "pick_first"
Jan 12 22:21:38 node01 microk8s.daemon-apiserver[64883]: I0112 22:21:38.844459   64883 log.go:181] [ERROR] dqlite: proxy: first: remote -> local: read tcp node01IPV4:19001->node03IPV4:53250: read: connection reset by peer
```

where `node03` is the node I wish to (re-)add to the cluster and `node01` is the node i'm currently viewing the log on.

And when i check on the node that was attempting to join, this is what I see:


```shell
root@node03:/home/karl# microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
root@node03:/home/karl# microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1910/inspection-report-20210113_023002.tar.gz
```



[inspection-report-20210113_023002.tar.gz](https://github.com/ubuntu/microk8s/files/5806068/inspection-report-20210113_023002.tar.gz)

**Comment by ktsakalozos** [comment]
Could you look in `/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml` to see if the node that is failing to join is already referenced there?

**Comment by sean-abbott** [comment]
On the lead node, where I ran "add-node"?

**Comment by kquinsland** [comment]
Yep, i have the "already added" node present as well:

```
root@node01:/home/karl# cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml | grep -A2 "88.53"
- Address: xx.yy.88.53:19001
  ID: 13766631665405994632
  Role: 1
```

**Comment by sean-abbott** [comment]
Interesting, mine is showing as Role: 0. No idea what that diff means.

**Comment by kquinsland** [comment]
> Interesting, mine is showing as Role: 0. No idea what that diff means.


If i had to guess, it's the flag for primary or backup/standby.  When i run `microk8s status` i get 3 IPs as "datastore master" and 3 as "datastore stand by". The `Role: 0` matches up perfectly with the active nodes and `Role: 1` matches up perfectly with the standby nodes.

**Comment by ktsakalozos** [comment]
The command to forcefully remove a dqlite (the datastore) node from the cluster is:
```
/snap/microk8s/current/bin/dqlite -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -f json k8s ".remove <node-ip-with-port-19001>"
```
The ` <node-ip-with-port-19001>` is the Address you see in `cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`.

I am interested to understand how the cluster got into this state so we can guard against it. Would anyone of you recall the exact steps you took? I am looking for a way to reproduce this problem.

**Comment by sean-abbott** [comment]
I literally ran the ansible that I linked. When the ansible playbook to
create the cluster failed, I stopped and restarted microk8s and tried again
on the first pi node, and it worked. I then proceeded to manually try the
second and it failed.

Completely fresh install.

**Comment by kquinsland** [comment]
> The command to forcefully remove a dqlite (the datastore) node from the cluster is:
> 
> ```
> /snap/microk8s/current/bin/dqlite -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -f json k8s ".remove <node-ip-with-port-19001>"
> ```

Thanks. This is a lot better than the the hacky 'add fake node' approach I was going to try.  I assume that i'll need to manually edit the yml file as well?



> I am interested to understand how the cluster got into this state so we can guard against it. Would anyone of you recall the exact steps you took? I am looking for a way to reproduce this problem.

I would like to know as well... I didn't even notice that the node fell out until I posted [this](https://github.com/ubuntu/microk8s/issues/1884#issuecomment-758919800). The `node03` node _was_ running fine until all of a sudden it was not. When i ran `microk8s inspect` the api server was not running and it had the typically unhelpful output as seen [here](https://github.com/ubuntu/microk8s/issues/1598#issuecomment-724258951).

**Comment by devZer0** [comment]
i can confirm this problem, i setup microk8s on proxmox vm's with ubuntu server 20.04 lts and when joining a node, i had repeated crashes of the first node

**Comment by katlego-maleka** [comment]
This worked for me:

firewall-cmd --add-port=19001/tcp --permanent
firewall-cmd --reload

**Comment by usersina** [comment]
> The command to forcefully remove a dqlite (the datastore) node from the cluster is:
> 
> ```
> /snap/microk8s/current/bin/dqlite -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -f json k8s ".remove <node-ip-with-port-19001>"
> ```
> 
> The ` <node-ip-with-port-19001>` is the Address you see in `cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`.
> 
> I am interested to understand how the cluster got into this state so we can guard against it. Would anyone of you recall the exact steps you took? I am looking for a way to reproduce this problem.

You can reproduce it by adding a worker node to the cluster, creating a deployment that runs on the newly added node then changing the `hostname` and `/etc/hosts` of said node.
