### ISSUE TITLE
Containerd restart unexpected in my ci/cd environment

### ISSUE THREAD

**Issue by njleon007** [canonical/microk8s#1901]
1.  I use microk8s to set my gitlab-ci/cd environment to run CI jobs.

2. Cluster has 1 master ,7 nodes. 
I find kubelet/containerd  restarted more frequently in nodes.

3. logs:
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28.045556402+08:00" level=info msg="Stop CRI service"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28.045787578+08:00" level=info msg="Stop CRI service"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28.045825671+08:00" level=info msg="Event monitor stopped"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28.045869641+08:00" level=info msg="Stream server stopped"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
systemd[1]: Started Service for snap application microk8s.daemon-containerd.
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
microk8s.daemon-containerd[42151]: time="2021-01-15T15:37:28+08:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="cleaning up after dead shim" bundle="/var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/756c6be0ad7386b47be31b59e0ec4d702f6f79
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix
level=error msg="connecting to shim" error="dial unix

4. attach microk8s.inspect tar
[inspection-report-20210115_065445.tar.gz](https://github.com/ubuntu/microk8s/files/5820351/inspection-report-20210115_065445.tar.gz)

5. thanks for help to diagnose

**Comment by balchua** [comment]
Hi @njleon007
Thanks for using MicroK8s.
Unfortunately, i couldn't find the logs you pasted above in the inspect tarball.

Just a question, could it be that you maybe running out of disk space on `/var/snap/microk8s`?

Btw this path is where all microk8s stuffs are stored.
How often does it restart happen and has it always been like this?
Thanks

**Comment by njleon007** [comment]
Hi @balchua 

I did not check disk space, but sure be enough for linux root filesystem, and also /var/snap/microk8s is not mount separately.

I guess different node restart once a month, but different node can be a backup for my CI/CD system.

 CI/CD system is not stable, I suffered a lot, So I ask for help to find the problem.

I can support some kubelet/containerd system logs for you.

kubelet.log
Jan 12 23:31:45 ubuntu126 microk8s.daemon-kubelet[20887]: W0112 23:31:45.136870   20887 watcher.go:87] Error while processing event ("/sys/fs/cgroup/devices/system.slice/run-r7f6f7081502940d9a1443b276c6a2c4a.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/system.slice/run-r7f6f7081502940d9a1443b276c6a2c4a.scope: no space left on device

containerd.log
Jan 14 22:41:28 ubuntu126 systemd[1]: snap.microk8s.daemon-containerd.service: Failed to add inotify watch descriptor for control group /system.slice/snap.microk8s.daemon-containerd.service: No space left on device


attachlogs
[kubelet-containerd.zip](https://github.com/ubuntu/microk8s/files/5824196/kubelet-containerd.zip)


Thanks

**Comment by njleon007** [comment]
I find a cgroup leaking issue

**Comment by balchua** [comment]
You spotted the issue.
```
Jan 14 22:41:28 ubuntu126 systemd[1]: snap.microk8s.daemon-containerd.service: Failed to add inotify watch descriptor for control group /system.slice/snap.microk8s.daemon-containerd.service: No space left on device
```

**Comment by njleon007** [comment]
thanks for your time,  I will learn to get it  workaround.

**Comment by njleon007** [comment]
hi, @balchua , I fix cgroup leak, but containerd still stopped, don't know why.

Feb 14 18:44:55 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-14T18:44:55.405149224-05:00" level=error msg="An error occurs during waiting for container "95297e4839d50219defb0f6e3eecd6833b9eed212ea640901b327c7c8eefec8f" to be stopped" error="wait container "95297e4839d50219defb0f6e3eecd6833b9eed212ea640901b327c7c8eefec8f" stop timeout"
Feb 15 06:21:33 ubuntu126 systemd[1]: **Stopping Service for snap application microk8s.daemon-containerd...**
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33.188427319-05:00" level=warning msg="cleaning up after killed shim" id=a67c456213eebe2863672cc73f2ab057f5b284b6c820e2b46533ac5323c03415 namespace=k8s.io
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 microk8s.daemon-containerd[24558]: time="2021-02-15T06:21:33-05:00" level=fatal msg="containerd-shim: ttrpc server failure" error="ttrpc: server closed"
Feb 15 06:21:33 ubuntu126 systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
Feb 15 06:21:40 ubuntu126 systemd[1]: Started Service for snap application microk8s.daemon-containerd.

**Comment by njleon007** [comment]
sudo systemctl stop snap.microk8s.daemon-apiserver-kicker.service
I stop apiserver-kicker service to check if some network issue
