### ISSUE TITLE
Internal error occurred: failed to allocate a serviceIP: range is full

### ISSUE THREAD

**Issue by rdeepc** [canonical/microk8s#1917]
Can't deploy more than **252**(around) Services because **service-cluster-ip-range 10.152.183.0/24** by default, which is **254** hosts.
So it runs **out of ip address** for the services.

To fix the problem I had to use **service-cluster-ip-range=10.152.0.0/16** in **microk8s-resources/default-args/kube-apiserver** to increase the number of ip address. Also set IP according to the range in some other files. 

It would be helpful if it is **service-cluster-ip-range=10.152.0.0/16** by default.

**microk8s inspect**
[inspection-report-20210120_043107.tar.gz](https://github.com/ubuntu/microk8s/files/5840179/inspection-report-20210120_043107.tar.gz)

**Comment by balchua** [comment]
@rdeepc thanks for this one.  Are you interested on putting up a PR for this?  Its just right that you get credited for this work.
Thanks!

**Comment by mac2000** [comment]
`/var/snap/microk8s/current/args/kube-apiserver` is the path for configuration file that needs to be modified
