### ISSUE TITLE
Exclude secondary IP from produce_certs (and node service restarts)

### ISSUE THREAD

**Issue by ngbrown** [canonical/microk8s#1943]
Currently, MicroK8s is rebuilding the node certificates and restarting all the MicroK8s services on a node if any IP address changes.  This conflicts with the operation of the [PureLB Load Balancer](https://purelb.gitlab.io/docs/) when allocating local addresses.

When PureLB is installed and needs to assign an local IP address for load balancing use, it adds a secondary IP address to the ethernet adapter with a default route.  This IP address change is triggering the `daemon-apiserver-kicker` to restart all the services. It then makes the running pods all go un-healthy so the pool IP allocation is removed and then reattempted on another node (or when this node comes back), and a never-ending cycle starts.

https://github.com/ubuntu/microk8s/blob/700359017d2c7f839638422e9d0ae876b4f7e632/microk8s-resources/wrappers/apiservice-kicker#L50-L68

Adding `--advertise-address` or `--bind-address` to `args/kube-apiserver`, while stopping the above process, seems to prevent a node join, I assume because the certificates do need to be rebuilt and the services restarted.

I propose that the fix is to adjust the `get_ips()` that `produce_certs()` uses to exclude any secondary IPs. This is how the function looks currently:

https://github.com/ubuntu/microk8s/blob/8d0b9e5d6cfdb61b855b0d1ad657b43c4db73583/microk8s-resources/actions/common/utils.sh#L330-L350

This is how the ip list looks on a node that PureLB's `lbnodeagent` has allocated an ip address (10.3.50.193) based on a Load Balancer demand:

```
$ hostname -I
10.3.50.68 10.3.50.193 10.1.233.192
$ ip -o addr list
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever
2: eth0    inet 10.3.50.68/24 brd 10.3.50.255 scope global eth0\       valid_lft forever preferred_lft forever
2: eth0    inet 10.3.50.193/24 brd 10.3.50.255 scope global secondary eth0\       valid_lft forever preferred_lft forever
2: eth0    inet6 fe80::215:5dff:fe32:800/64 scope link \       valid_lft forever preferred_lft forever
6: vxlan.calico    inet 10.1.233.192/32 brd 10.1.233.192 scope global vxlan.calico\       valid_lft forever preferred_lft forever
6: vxlan.calico    inet6 fe80::641a:d3ff:fe93:5639/64 scope link \       valid_lft forever preferred_lft forever
7: calieeedeb80fed    inet6 fe80::ecee:eeff:feee:eeee/64 scope link \       valid_lft forever preferred_lft forever
16: kube-lb0    inet6 fe80::dc6c:83ff:fec8:c3df/64 scope link \       valid_lft forever preferred_lft forever
```

Are there any cases where the secondary ip addresses should be in the certificate?

`hostname -I` could return ipv6 addresses and PureLB can allocate ipv6 addresses, so my use of `ip` above includes both ipv4 and ipv6 instead of using `-4`.

Also, while I haven't used it yet, PureLB can assign [global virtual addresses](https://purelb.gitlab.io/docs/how_it_works/virtint/) to it's `kube-lb0` adapter, and those would need to be excluded from the reconfiguration as well.

cc: @adamdunstan as a PureLB developer.

**Comment by ngbrown** [comment]
I'm no bash expert, but maybe insert something like this?

```bash
get_ips() {

# ... rest of function ...

        local SECONDARY_IP="$($SNAP/sbin/ip -o addr list secondary | $SNAP/usr/bin/gawk '{ORS=" "}{print gensub(/^([^\/]*)\/[0-9]*$/, "\\1", 1, $4)}')"
        if [[ -n "$SECONDARY_IP" ]]
        then
          for s_ip in $SECONDARY_IP
          do
            local ips="";
            for ip in $IP_ADDR
            do
              [ "$ip" != "$s_ip" ] && ips+="${ips:+ }$ip";
            done
            IP_ADDR="$ips"
          done
        fi

        echo "${IP_ADDR}"
    fi
}
```

**Comment by ktsakalozos** [comment]
Thank you for digging into this @ngbrown. If we remove the secondary addresses from the certificates list we would not allow anyone accessing Kubernetes from there. I am not so sure this is what we want. Maybe it would be enough not to restart the containerd from the apiserver kicker [1]. Another approach that might work in your case is to remove the the `#MOREIPS` line from `/var/snap/microk8s/current/certs/csr.conf.template` .

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker#L60

**Comment by adamdunstan** [comment]
@ngbrown thanks for logging this ticket, we had experienced the problem a while back while testing PureLB on various distribution, figured out the cause, disabled the api-kicker, but did not look any deeper.   

My question to the mk8s maintainers.  I think I understand why the api-kicker is there. **However the api-kicker is taking ownership of the default interface of the host**. Why is it necessary to assume that all of the addresses are use for k8s access by default, that doesnt seem like correct behavior.  Adding additional addresses for other purposes not related to k8s-apiserver is a valid use case.   Instead of watching the interface, would the correct behavior be to watch check for addresses that are in use by k8s then run the kicker to update should the address disappear and have the kicker pickup the primary address only, or perhaps only an address allocated by dhcp, as that would be the addresses that would be changing?

**Comment by rcludwick** [comment]
I just hit this with microk8s 1.20 on an RPI.  Trying to debug this was not a very developer-friendly experience.   Every 40 seconds it would reconfigure and no pods would ever show as "running".  

I'd also get errors that looked like this:

`rob@u:~ $ microk8s kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-847c8c99d-2895m   0/1     Running   2          7m24s
kube-system   calico-node-7z6q8                         0/1     Unknown   3          7m24s
rob@u:~ $ microk8s kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-847c8c99d-2895m   0/1     Running   2          7m25s
kube-system   calico-node-7z6q8                         0/1     Unknown   3          7m25s
rob@u:~ $ microk8s kubectl get pods -A
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
rob@u:~ $ microk8s kubectl get pods -A
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
`

This was the logs where apiserver-kicker is restarting everything every 40 seconds or so.

`May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:08:35 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:09:17 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:09:45 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:10:25 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:11:08 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: Signature ok
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: subject=/CN=front-proxy-client
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: Getting CA Private Key
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: unable to write 'random state'
May 08 21:11:58 u microk8s.daemon-apiserver-kicker[1717]: CSR change detected. Reconfiguring the kube-apiserver
`

**Comment by ktsakalozos** [comment]
On v1.21+ in a multi-node cluster will will stop monitoring the available interfaces [1] as this is causing a lot of confusion.

[1] https://github.com/ubuntu/microk8s/pull/2217

**Comment by devZer0** [comment]
recent activity because stale bots suck
