### ISSUE TITLE
Cannot add 5th node to cluster 

### ISSUE THREAD

**Issue by RyzeNGrind** [canonical/microk8s#1967]
Adding 5th node to my microk8s cluster causes some problems that prevents the services from running. I have tried to uninstall, and reinstall several times to no avail.

I have attached the tarball.gz inspection report from my Raspberry Pi 8GB 4B+ arm64 running Ubuntu 20.04LTS.

When i enter join token command on cluster is when everything stops working on the node. Any help would be appreciated. Thanks in advance. 

[inspection-report-20210202_122759.tar.gz](https://github.com/ubuntu/microk8s/files/5920598/inspection-report-20210202_122759.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @RyzeNGrind. Could you also attach a `microk8s.inspect` tarball taken from the node you are trying to join to? 
 Could you also provide the contents of `/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`? You should make sure the IP of the new node is not in that file. Thanks.

**Comment by RyzeNGrind** [comment]
Hello @ktsakalozos Thanks for the prompt response. It seems the IP of the new node is already in the aforementioned `cluster.yaml` file.

I have attached the files as requsted. Should I remove the IP of the 5th node `192.168.20.6`? Thanks. 
[inspection-report-20210204_211526.tar.gz](https://github.com/ubuntu/microk8s/files/5928581/inspection-report-20210204_211526.tar.gz)

Contents of the cluster.yaml file on pc0 (master node):
`- Address: 192.168.20.2:19001
  ID: 3297041220608546238
  Role: 0
- Address: 192.168.20.3:19001
  ID: 12619250446949860614
  Role: 0
- Address: 192.168.20.4:19001
  ID: 7886624854705267048
  Role: 0
- Address: 192.168.20.5:19001
  ID: 13722032205925992099
  Role: 1
- Address: 192.168.20.6:19001
  ID: 17836803442849221058
  Role: 1`

**Comment by RyzeNGrind** [comment]
I tried to remove the IP in the cluster.yaml file, but everytime I save and recheck the file the entry is already automatically inserted in to the file. Not sure how I can proceed. Any advice would be greatly appreciated.

**Comment by RyzeNGrind** [comment]
@ktsakalozos Hi any updates regarding this issue?

**Comment by ktsakalozos** [comment]
@RyzeNGrind I missed this thread, sorry. Could you try to remove the node with `microk8s.remove-node --force` ? 

I am also interested to know of a way to reproduce this.
