### ISSUE TITLE
Racing condition joining microk8s nodes

### ISSUE THREAD

**Issue by davigar15** [canonical/microk8s#1970]
Hello,

I tried to create a microk8s cluster of 3 nodes following the instructions [here](https://microk8s.io/docs/high-availability). One of the nodes succeeded joining the cluster, but the other one did not. Might be because of a racing condition.

I'm attaching the inspection report for the primary node, the failed node and the node that succeeded the joining process.

Kind regards,
David

[failed_joining_node.tar.gz](https://github.com/ubuntu/microk8s/files/5927481/failed_joining_node.tar.gz)
[primary_node.tar.gz](https://github.com/ubuntu/microk8s/files/5927482/primary_node.tar.gz)
[successfully_joined_node.tar.gz](https://github.com/ubuntu/microk8s/files/5927483/successfully_joined_node.tar.gz)

**Comment by balchua** [comment]
I see this too when im trying to automate the cluster formation.  There's a recent fix wherein the apiserver is bounced by the kicker when the calico network comes up.  That could be the case.

https://github.com/ubuntu/microk8s/pull/2091
I don't know if it already landed on `1.20/stable`
Are you still experiencing this?
Thanks
