### ISSUE TITLE
microk8s memory violation

### ISSUE THREAD

**Issue by BitRacer** [canonical/microk8s#1984]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by BitRacer** [comment]
from  /var/log/apport.log 

ERROR: apport (pid 153694) Sun Feb  7 02:39:27 2021: executable does not belong to a package, ignoring
ERROR: apport (pid 153814) Sun Feb  7 02:39:29 2021: called for pid 153719, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 153814) Sun Feb  7 02:39:29 2021: executable: /snap/microk8s/1908/kube-apiserver (command line "/snap/microk8s/1908/kube-apiserver --cert-dir=/var/snap/microk8s/1908/certs --service-cluster-ip-range=10.152.183.0/24 --authorization-mode=AlwaysAllow --service-account-key-file=/var/snap/microk8s/1908/certs/serviceaccount.key --client-ca-file=/var/snap/microk8s/1908/certs/ca.crt --tls-cert-file=/var/snap/microk8s/1908/certs/server.crt --tls-private-key-file=/var/snap/microk8s/1908/certs/server.key --kubelet-client-certificate=/var/snap/microk8s/1908/certs/server.crt --kubelet-client-key=/var/snap/microk8s/1908/certs/server.key --secure-port=16443 --token-auth-file=/var/snap/microk8s/1908/credentials/known_tokens.csv --insecure-port=0 --storage-backend=dqlite --storage-dir=/var/snap/microk8s/1908/var/kubernetes/backend/ --allow-privileged=true --service-account-issuer=https://kubernetes.default.svc --service-account-signing-key-file=/var/snap/microk8s/1908/certs/serviceaccount.key --feature-gates=RemoveSelfLink=false --requestheader-client-ca-file=/var/snap/microk8s/1908/certs/front-proxy-ca.crt --requestheader-allowed-names=front-proxy-client --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --proxy-client-cert-file=/var/snap/microk8s/1908/certs/front-proxy-client.crt --proxy-client-key-file=/var/snap/microk8s/1908/certs/front-proxy-client.key")

ubuntu@worker1:~$ k get no
NAME      STATUS     ROLES    AGE     VERSION
master    Ready      <none>   8d      v1.20.1-34+97978f80232b01
worker2   Ready      <none>   8d      v1.20.1-34+97978f80232b01
worker3   Ready      <none>   8d      v1.20.1-34+97978f80232b01
worker1   NotReady   <none>   7h34m   v1.20.1-34+97978f80232b01
ubuntu@worker1:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.1.100:19001 192.168.1.102:19001 192.168.1.103:19001
  datastore standby nodes: 192.168.1.101:19001
addons:
  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    rbac                 # Role-Based Access Control for authorisation
  disabled:
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
    traefik              # traefik Ingress controller for external access

microk8s shows node is up, but it doe snot seem to be working with the cluster.


[inspection-report-20210207_223707.tar.gz](https://github.com/ubuntu/microk8s/files/5940195/inspection-report-20210207_223707.tar.gz)

**Comment by balchua** [comment]
Hi, are you still experiencing this issue?  There were quite some fixes in dqlite that was ported to 1.20 channel since you last reported this.

**Comment by bitvilag** [comment]
I faced this issue on 1.20.4. 
I installed 1.19 instead as the only fix I found to restart the apiserver on each node once it reaches a certain limit. 
Issue happened with a brand new x64 install on ubuntu 20.04 using snap.

It seems memory increases by 100M every 1-5 seconds which is shocking.
