### ISSUE TITLE
MicroK8s v1.20.1 : Stale endpoints of Deployment Pod IP address are present at Kubernetes Service

### ISSUE THREAD

**Issue by sansindia85** [canonical/microk8s#1991]
Microk8s Kubernetes V1.20.1 (Stable channel).

Issue: 
On deletion of Kubernetes resources  (Deployment with replica size 1 and Service manually) and create them again manually.  This process is repeated two to three times:
The old endpoint (IP address of POD) at Kubernetes service is not getting deleted. 
This resulted in two end points at Kubernetes Service. One is new IP Address of POD. Other is older IP address of POD. 

Workaround:
By changing the POD name, deployment name, service name and selectors from APP to RUN resolved the issue. The older IP address of Pods gets removed from Kubernetes Service. It will have only one IP address at Kubernetes Service that points to the present IP address of POD.

Did anyone face this issue in MicroK8s?

**Comment by prajapatin** [comment]
Yes, faced same issue and redeployment of service/pod solved our issue. This should not happen in any case because kubernetes engine should take care of removing POD endpoint when POD itself is not running.

**Comment by balchua** [comment]
@prajapatin and @sansindia85 are you still facing this issue?  There were several fixes to the 1.20 channel since you last reported.
Thanks again.

**Comment by sansindia85** [comment]
@balchua  : Observed it only once. Recently, no.
