### ISSUE TITLE
Unable to access notebook servers

### ISSUE THREAD

**Issue by danudeep90** [canonical/microk8s#1995]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

I installed microk8s on a VM using 
sudo snap remove microk8s --purge
sudo snap install microk8s --classic
microk8s enable dns dashboard storage
microk8s enable kubeflow

Kubeflow got enabled successfully,

I created a socks proxy and opened the UI on my browser. All tabs work fine apart from Notebook server page
i cant see anything on this page and attaching the screenshot of console on firefox browser
[Uploading inspection-report-20210209_112637.tar.gz…]()
<img width="1790" alt="Screenshot 2021-02-09 at 4 52 27 PM" src="https://user-images.githubusercontent.com/10043245/107359082-3e07d100-6afa-11eb-8e81-60f24f1143b2.png">
<img width="877" alt="Screenshot 2021-02-09 at 11 07 50 AM" src="https://user-images.githubusercontent.com/10043245/107359101-46f8a280-6afa-11eb-9cf4-a3ade6abd12f.png">

**Comment by knkski** [comment]
@danudeep90: This issue should be fixed on the latest version of microk8s. Can you try again after refreshing the snap? `sudo snap refresh microk8s --channel latest/edge` will get you the latest version.
