### ISSUE TITLE
microk8s v1.20 changed nginx ingress class name from default

### ISSUE THREAD

**Issue by abierbaum** [canonical/microk8s#2035]
It appears that in the v1.20 release cycle, the ingress.yaml configuration was modified in a way that sets an ingress class name that does not match the default nginx-ingress value of 'nginx'.  Instead it is now set explicitly to 'public'.

This caused all of our deployments to start failing upon upgrading to 1.20 because we were assuming the defaults documents in nginx-ingress.  I am not sure if it should be changed back to default values or not, but wanted to note it in case it was a bug and to help other people that run into this issue.

The change was made here: https://github.com/ubuntu/microk8s/commit/b4e93d105169c48862234040ad46dc51cc5ebab1#diff-6fec6aff020a1e6535d96d04cbd21a1ae402c4d1c9da526c071d22fdcd930d5fR221

Previous to this, the ingress was using the default value as described here: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/#multiple-ingress-nginx-controllers  (ie. 'nginx')

If this isn't a bug and is expected behavior, then I think it would be very useful to updated the addon documentation to make clear to people that if they have code from other k8s clusters that use an ingress.class of 'nginx' it will not work here.  (the ingress will be ignored)

**Comment by rockkoca** [comment]
I spent at least half-day on this issue until I checked the logs of ingress which expects public instead of nginx.

**Comment by abierbaum** [comment]
@rockkoca That is how I found it too.  It wasn't obvious though since the logs don't say the class name.  Definitely a huge surprise that broke everything and made microk8s behave differently from default ngix-ingress (and it's documentation)

**Comment by djmcgreal-cc** [comment]
See https://github.com/ubuntu/microk8s/issues/1890 too

**Comment by jetpackdanger** [comment]
I just lost a bunch of time to this myself: installed microk8s 1.20 to start a new project, and my ingresses mysteriously don't work, even though the "public" ingress class is [marked as the default class](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class).

Only when I checked the controller's code did I discover that the nginx ingress controller doesn't look at this property at all and instead hard-codes the default class to "nginx".

Certainly, it's documented upstream, but it's not exactly prominent, but microk8s is generally such a pleasant out-of-the-box experience that this is quite jarring!

**Comment by mryan43** [comment]
Just checking in here as another one who lost a few hours on this...

**Comment by dud225** [comment]
> Only when I checked the controller's code did I discover that the nginx ingress controller doesn't look at this property at all and instead hard-codes the default class to "nginx".

I stumbled upon a word about this on the Kubernetes doc:
> There are some ingress controllers, that work without the definition of a default IngressClass. For example, the Ingress-NGINX controller can be configured with a [flag](https://kubernetes.github.io/ingress-nginx/#what-is-the-flag-watch-ingress-without-class) --watch-ingress-without-class. It is [recommended](https://kubernetes.github.io/ingress-nginx/#i-have-only-one-instance-of-the-ingresss-nginx-controller-in-my-cluster-what-should-i-do) though, to specify the default IngressClass

https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class

**Comment by mrgoonie** [comment]
Hmm... 2 years and this issue is still left open? 😅

**Comment by lbruun** [comment]
Further:

I believe that since [this commit](https://github.com/canonical/microk8s-core-addons/commit/577684eae2282243fb11114ab42dd11870a7f921) the addon now installs 2 ingress classes:  `public` AND `nginx`. So you have both. The one named `public` is marked as default.

**Comment by mrgoonie** [comment]
Thanks @neoaggelos @lbruun
