### ISSUE TITLE
Node keep stucked on "Booting worker with pid:"

### ISSUE THREAD

**Issue by kerenskybr** [canonical/microk8s#2043]
Hi. I trying to join a node to use with kubeflow (parallel training), but can't make a node join to the master. This is the log (`sudo journalctl -u snap.microk8s.daemon-cluster-agent -f`) for the node:

`fev 23 17:52:13 ubuntu-pt microk8s.daemon-cluster-agent[581421]: [2021-02-23 17:52:13 +0000] [581421] [INFO] Booting worker with pid: 581421`

And this for master:
`Feb 23 17:50:00 ubuntu-pt-2 microk8s.daemon-cluster-agent[26216]: Waiting for access to cluster.`

Left for an hour on this state until the node machine freezes and needed a restart.

Things i tried:
- reinstall microk8s after a remove --purge
- allow on firewall
- swapping machines (master have two gpus and node one)
- refresh certs
- and every single solution i could find here/online

Also running `sudo snap logs -f microk8s` show those logs all the time (in both)
```
2021-02-23T18:04:45Z microk8s.daemon-containerd[1230]: time="2021-02-23T18:04:45.263326275Z" level=info msg="Exec process \"8beb670179d2d895355b6c68fd18e346a0855520fde15b3ccdfae6d56590a0af\" exits with exit code 0 and error <nil>"
2021-02-23T18:04:45Z microk8s.daemon-containerd[1230]: time="2021-02-23T18:04:45.264060785Z" level=info msg="ExecSync for \"bdbd634c64ae019f37e46b29a664bb93ea72385ca4f6064f579885692bcd5f8a\" returns with exit code 0"
```
Tarballs:
[master-inspection-report-20210223_175553.tar.gz](https://github.com/ubuntu/microk8s/files/6030948/master-inspection-report-20210223_175553.tar.gz)
[node-inspection-report-20210223_175642.tar.gz](https://github.com/ubuntu/microk8s/files/6030949/node-inspection-report-20210223_175642.tar.gz)

**Comment by balchua** [comment]
The apiserver isn't healthy.  It kept exiting with `context deadline exceeded`.  
I can also see that you already have workloads running on the control plane.  Just for testing, will be possible to join empty nodes?  Meaning without any workload?
Thanks.

**Comment by kerenskybr** [comment]
Hi, thanks for your reply. I tried that, without success

After several reinstall/restarts and switching machines (machine with one gpu as master), i was able to join the other node machine.

But, would be cool to know what happened/prevent this to work to solve in the future...

Now i can't use the gpu from the node, but it's a question for another post lol

Thanks

**Comment by balchua** [comment]
Thanks @kerenskybr for the response.  Yes it will be great to know what happened / is happening.
If i repeat what you have tried.

* allow necessary ports on firewall.
* create 1 fresh MicroK8s node (without any workload)
* create the second fresh MicroK8s node, no workload.
* execute `microk8s add-node` on node 1.
* Execute `microk8s join ...` on node 2.
* Execute `microk8s kubectl get node` on node 1.
It doesn't show `node2` in the list.

I've tried doing this several times, i couldn't reproduce it like you do.  
One stupid question, are the nodes separated by low latency network? Like 100ms+ latency?

**Comment by kerenskybr** [comment]
Nodes are in same room, but I'm doing everything from another country. Could a remote configuration be affecting?

**Comment by balchua** [comment]
I don't think so... Since you are doing it from the nodes themselves.
