### ISSUE TITLE
Document that `etcd` is no longer used

### ISSUE THREAD

**Issue by akingscote** [canonical/microk8s#2051]
On the [configuring services](https://microk8s.io/docs/configuring-services) page it mentions `snap.microk8s.daemon-etcd`.
On newer installations of MicroK8s the service just exits instantly. After doing a bit of digging, it seems that `etcd` has been replaced with `dqlite`.

I wanted to use `etcdctl` with MicroK8s and lost a lot of time before i realised MicroK8s has moved away from it.

Please update the documentation to make it clearer.
For what its worth, i was able to downgrade to version `1.15/stable` and use `etcdctl` eventually. Thanks

**Comment by balchua** [comment]
Hi, you can still use etcd when you disable `ha-cluster`

After installing the snap, you can do `microk8s disable ha-cluster`.  It will use etcd and flannel.

Please remember that data will be gone.

**Comment by akingscote** [comment]
Ahh thanks that worked. 

```
$ sudo snap install microk8s --classic --channel=1.19
$ microk8s disable ha-cluster
Reverting to a non-HA setup
Generating new cluster certificates.
Waiting for node to start.  
Enabling flanneld and etcd
```

Perhaps that can be added to the documentation still?

**Comment by balchua** [comment]
@akingscote thanks for pointing it out.

@evilnick @ktsakalozos is this something that can be added in the documentation?

Thanks
