### ISSUE TITLE
Is it possible to install microk8s on ubuntu core?

### ISSUE THREAD

**Issue by lejsekt** [canonical/microk8s#2053]
Hi,
is it possible to install microk8s on rabsperry pi 4 with ubuntu core 20 for arm64?

sudo snap install microk8s --classic
error: snap "microk8s" requires classic confinement which is only available on classic systems

Thank you

**Comment by balchua** [comment]
I think **Ubuntu Core** supports only strict confinement.

**Comment by lejsekt** [comment]
And is it planned to support Ubuntu Core in the future?

**Comment by ktsakalozos** [comment]
Indeed Ubuntu Core needs strict confinement. There is a branch where we got most of MicroK8s strictly confined [1]. @joedborg has worked on this.

@lejsekt what would you need a strictly confined MicroK8s for? We would like your input to make a case to work on it. Thanks.

[1] https://github.com/ubuntu/microk8s/tree/feature/jdb%2Fstrict

**Comment by dylancourt** [comment]
+1 for this! I work at a smart building company and we're looking to replace yocto os while also having a pathway to kubernetes on embedded devices at Edge sites

**Comment by balchua** [comment]
@ktsakalozos im adding this to the wishlist. 😊

**Comment by usrbinkat** [comment]
microk8s on top of ubuntu core would simply solve the hardest challenges that I face with deployment and lifecycle of assembly plant robots and low power edge compute at 5G tower installations. I could enumerate the layers of features that enhance the end to end lifecycle if needed but both together would be the compelling story that I'm really looking for.

Please let me know if I can help get visibility to the importance of this work.

**Comment by ncpe20012003** [comment]
Any progress? I have a need to run microk8s on UC 20.

**Comment by robert-schmuck** [comment]
Hi,
I am also very interested in running mickrok8s on ubuntu core 20, is there plan when to implement this?

**Comment by ncpe20012003** [comment]
Checking in, any word on MicroK8s in UC 20?

**Comment by balchua** [comment]
@ncpe20012003 i know there's been plenty of work being put on this. @ktsakalozos maybe able to share more on this.

**Comment by ktsakalozos** [comment]
We are actively working on getting a strictly confined snap. There is a branch where you could follow our progress https://github.com/ubuntu/microk8s/tree/feature/jdb%2Fstrict . The build for now go in the latest/edge/strict channel. You could give it a try with:
```
sudo snap install mcirok8s --channel=latest/edge/strict --devmode
```

**Comment by Christoph02** [comment]
Also waiting on microk8s for  ubuntu core. Tried on proxmox and ran in same issue.
Would be great to have this very cool snap on ubuntu core, too. 
currently not working with --channel=latest/edge/strict even not in devmode.

Kind regards,
Christoph

**Comment by Ch4s3r** [comment]
@ktsakalozos There was a typo in your command in `mcirok8s`.
Works awesome otherwise on ubuntu core :)
```shell
sudo snap install microk8s --channel=latest/edge/strict --devmode
```

**Comment by ktsakalozos** [comment]
We would appreciate if you could run in non-devmode (without the `--devmode`) and provide us with some feedback on what may be broken. An inspection report should be enough (`microk8s inspect`) . Thank you.

**Comment by Ch4s3r** [comment]
There was an error on my side, I only tested it on a VM and expected it to also work on a PI.
So it's currently not working on the Pi 4 directly (with or without devmode).

But anyway here are the two reports if they still help:
devmode: [inspection-report-20211004_213459.tar.gz](https://github.com/ubuntu/microk8s/files/7281436/inspection-report-20211004_213459.tar.gz)
non-devmode: [inspection-report-20211004_205641.tar.gz](https://github.com/ubuntu/microk8s/files/7281430/inspection-report-20211004_205641.tar.gz)

Both setup on a fresh ubuntu core 20 arm64 distro on a Pi 4.

**Comment by ktsakalozos** [comment]
@Ch4s3r in the logs I see this error:
```
Oct 04 21:34:40 ubuntu microk8s.daemon-kubelite[7068]: E1004 21:34:40.630574    7068 kubelet.go:1423] "Failed to start ContainerManager" err="system validation failed - Following Cgroup subsystem not mounted: [memory]"
```
Have you enabled cgroups as described in https://microk8s.io/docs/install-alternatives#heading--arm ?

**Comment by Ch4s3r** [comment]
I did but maybe in the wrong place.
Because I could not find the firmware folder but there was another cmdline.txt  somewhere in /writable/.../system-data/...
Will have to recheck this in the evening.

**Comment by Ch4s3r** [comment]
Tried but could not append the kernel command line arguments on Ubuntu Core 20.
There is no `/boot/firmware` folder to write them to and there is no possibility to create this folder as the system is read-only.
Any suggestions how to do this?

**Comment by Christoph02** [comment]
Thank you Konstantinos (https://github.com/ktsakalozos)
## [MicroK8s v1.25 released!](https://github.com/canonical/microk8s/releases/tag/v1.25)

This is a real milestone: 
Strict confinement goes into general availability

It worked for me with Ubuntu Core on Raspberry 4.
```
snap install microk8s --channel=1.25-strict/stable
microk8s (1.25-strict/stable) v1.25.0 from Canonical✓ installed
```

The IoT experience with Ubuntu Core and MicroK8s can continue, now ...

Thanks a lot and best regards,
Christoph

**Comment by usrbinkat** [comment]
This is exciting!

**Comment by joedborg** [comment]
So happy to see this go GA!  Well done everyone.

**Comment by edocalia** [comment]
Thanks everyone, this is one major step beyond!

**Comment by Duc** [comment]
Hi, I ran successfully installed and run MicroK8s v1.26.0 revision 4393 on Ubuntu Core 22. I'm in a dead now regarding NFS volume, It's seems that Ubuntu Core is not able to mount NFS share. Am I right ?

**Comment by ktsakalozos** [comment]
@Duc I asked over at https://forum.snapcraft.io/t/mount-nfs-share-on-ubuntu-core/33332 as this might be a topic for snaps on core in general.
