### ISSUE TITLE
Cluster very unstable, sluggish. daemon-controller-manager and daemon-scheduler not running; constantly restarting  and spewing go-routine dumps

### ISSUE THREAD

**Issue by kquinsland** [canonical/microk8s#2077]
Sometime over night, a few pods died;  I looked  into it this afternoon and found a single node to be unresponsive.
cordoned off the node and restarted it. Did a rolling `apt update; reboot` on all nodes in the cluster as well as `/var/run/reboot-required` was present.

All nodes come back, seem to be sluggish and cluster as a whole seems slow to respond but all pods come back up but a few seem broken (one pod can't connect to database in another pod... database pod seems to be fine, though. Some messages in  kube-dashboard related  to calico errors of all things. I was out of time to diagnose and leave to run a few errands.   I come back about an hour later and 4 of 7 nodes are 'Unknown' in dashboard and 7/7  have PEGGED cpu.

All are responsive, though, as I managed to get a SSH connection in.

I run `inspect` and the process takes _significantly_ longer than usual (hundreds of seconds versus maybe 15 seconds, usually) and all come back with  similar results:

```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
 FAIL:  Service snap.microk8s.daemon-scheduler is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-scheduler
 FAIL:  Service snap.microk8s.daemon-controller-manager is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-controller-manager
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2035/inspection-report-20210306_001241.tar.gz
```

I checked  logs for `snap.microk8s.daemon-controller-manager` and see some _massive_ golang crash dumps:

```
<...>
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: goroutine 2541 [sync.Cond.Wait]:
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: runtime.goparkunlock(...)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/runtime/proc.go:312
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: sync.runtime_notifyListWait(0xc0009e7fd0, 0xc000000000)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/runtime/sema.go:513 +0xf8
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: sync.(*Cond).Wait(0xc0009e7fc0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/sync/cond.go:56 +0x9d
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*Type).Get(0xc0009bf620, 0x0, 0x0, 0xc0014e0f00)
Mar 06 00:05:44 node01 systemd[1]: snap.microk8s.daemon-controller-manager.service: Main process exited, code=exited, status=255/EXCEPTION
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit snap.microk8s.daemon-controller-manager.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 255.
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:145 +0x89
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).claimWorker.func1(0xc00139a900)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_base.go:470 +0x6e
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).claimWorker(0xc0007248c0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_base.go:516 +0x4b
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0031c1680)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0031c1680, 0x4db4120, 0xc0031ef350, 0xc000decf01, 0xc000e41ce0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0031c1680, 0x3b9aca00, 0x0, 0x10000c000c54001, 0xc000e41ce0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0031c1680, 0x3b9aca00, 0xc000e41ce0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
Mar 06 00:05:44 node01 systemd[1]: snap.microk8s.daemon-controller-manager.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit snap.microk8s.daemon-controller-manager.service has entered the 'failed' state with result 'exit-code'.
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: created by k8s.io/kubernetes/pkg/controller/volume/persistentvolume.(*PersistentVolumeController).Run
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_base.go:318 +0x3a5
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: goroutine 2540 [sync.Cond.Wait]:
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: runtime.goparkunlock(...)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/runtime/proc.go:312
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: sync.runtime_notifyListWait(0xc000ed20d0, 0xc000000000)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/runtime/sema.go:513 +0xf8
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: sync.(*Cond).Wait(0xc000ed20c0)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /snap/go/7013/src/sync/cond.go:56 +0x9d
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]: k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*Type).Get(0xc0009bf6e0, 0x0, 0x0, 0xc001bd3500)
Mar 06 00:05:44 node01 microk8s.daemon-controller-manager[349451]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:145 +0x89
<...>
```

After collecting the `inspect` results, i `microk8s stop`ed all nodes. Then brought back 4 of the 7 nodes (7, 2,3,4).

When i attempt to `get nodes`, the output is either 7 of 7 nodes up or a failure:

```shell
root@node04:/var/snap/microk8s/2035# microk8s kubectl get no
NAME     STATUS   ROLES    AGE    VERSION
node06   Ready    <none>   75d    v1.20.2-34+350770ed07a558
node05   Ready    <none>   16d    v1.20.2-34+350770ed07a558
node03   Ready    <none>   50d    v1.20.2-34+350770ed07a558
node02   Ready    <none>   52d    v1.20.2-34+350770ed07a558
node01   Ready    <none>   113d   v1.20.2-34+350770ed07a558
node04   Ready    <none>   113d   v1.20.2-34+350770ed07a558
node07   Ready    <none>   50d    v1.20.2-34+350770ed07a558
root@node04:/var/snap/microk8s/2035# microk8s kubectl get no
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?

(I can  keep running the get nodes command and I always get back 7/7 or failure)
```

But 7 of 7 cab't be the case because...

```
root@node05:/var/snap/microk8s/2035# microk8s status
microk8s is not running, try microk8s start
```

Attached are the inspection reports from all 7 nodes. 

[node01.gz](https://github.com/ubuntu/microk8s/files/6094324/node01.gz)
[node02.gz](https://github.com/ubuntu/microk8s/files/6094326/node02.gz)
[node03.gz](https://github.com/ubuntu/microk8s/files/6094328/node03.gz)
[node04.gz](https://github.com/ubuntu/microk8s/files/6094329/node04.gz)
[node05.gz](https://github.com/ubuntu/microk8s/files/6094330/node05.gz)
[node06.gz](https://github.com/ubuntu/microk8s/files/6094331/node06.gz)
[node07.gz](https://github.com/ubuntu/microk8s/files/6094333/node07.gz)

**Comment by ktsakalozos** [comment]
Hi @kquinsland 

I like your setup. It seems you are trying to make good use of already available hardware? Here are some thoughts on increasing the cluster's stability.

In your cluster there are three nodes that maintain the datadabe kubernetes uses, these nodes are termed voters. The voters are reported at the top of  `microk8s.status`. If any of the voters goes down the cluster will first wait for the node to recover and if it does not a new voter will be elected. If two voters go down at the same time the cluster will become unavailable. What are your current voters? I understand you have not all nodes started, are the started nodes the voters? Could you share the result of ` cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml` ?

I see your nodes run with swap. This is a problem because kubernetes is not able to asses the node resources correctly and will over-commit resources. The result will be that the nodes will become unresponsive as they are swapping heavily. I would not be surprised If during a reboot all scheduled containers try to reserve memory and the process you see pegging the CPU is kswap. BTW how does a `top` look like in a pegged machine.

There is CPU overheating and throttling on your nodes, see for example node07. Could you make sure your nodes have enough cooling? Look at `dmesg`.

In some of your nodes on `dmesg` these are erros like: `[16875.160391]  connection2:0: detected conn error (1020)`. Do you know what that might be?

On `/var/snap/microk8s/current/args/kubelet` on your nodes you will see the line `--eviction-hard="memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi"` that specifies when a pod should be evicted. In MicroK8s the eviction conditions are relaxed so we accommodate the local workstation case. Since you have a cluster you may want to comment out this line so that you go with the default eviction configuration of Kubernetes.

Thank you for reaching out. Looking forward to hear if any of the above made any difference.

**Comment by kquinsland** [comment]
Thanks for getting back to me!

>  It seems you are trying to make good use of already available hardware?

That i am :).  The cluster is 7 nodes of that were otherwise going to be thrown out / sent into the waste stream. The oldest machine is from the early intel i5 generation and the more 'modern' nodes are only a few years old. Certainly not what you'd want to run a _production_ load on, but fine for personal use / experimentation. 

- `nproc` returns `4` for all nodes.
- `node01` and `node06` are the only two with `4` gb ram. Once i've gotten back to a more stable cluster, I'll consider removing node06 (it's the oldest node, a  2012 chromebox!) and picking up some surplus RAM for `node01` to get all nodes to _at least_ 2GB per compute core
- `node07` is 32gig and all other nodes are 8.

> If any of the voters goes down the cluster will first wait for the node to recover and if it does not a new voter will be elected. 

How long do the two remaining nodes wait before a re-election? 

Does this mean that there are only 3 voters? Or 3 are 'elected' and the remaining nodes (4, in my case) are voters?  If one of the three primary nodes goes down, only the remaining 2 can promote a remaining node? Is there is no code path to support a multi-master failure where the remaining 4 nodes would then elect/promote new masters? 

That's fine if the case... it means that i'll need to adjust the time that I wait to rotate out a node to ensure that there is *plenty* of time for the remaining 2 or 6 nodes to promote a new leader before  re-introducing the newly updated node and selecting a new node for drain/update/reboot.

> What are your current voters? I understand you have not all nodes started, are the started nodes the voters? Could you share the result of cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml ?

After collecting the 7 reports, I shut the entire cluster off; no time for additional debugging and I wanted to wait for guidance here before digging in more. (`sudo microk8s stop; sudo shutdown`).

I powered up each node and pulled the  `cluster.yaml` from each node. I wrote a small script to group the data.

The key is the `Address` from the yaml. The value is a dict of the role values which points to a list of nodes that 'sees' the node at that role.

So for the payload below, `node02` and `node04` are the only two nodes that the cluster disagrees about.

- nodes 2,3,4,7 think that `node02` is `Role: 0` while nodes 1,5,6 think that `node02` is `Role: 1`
- nodes 2,3,4,7 think that `node04` is `Role: 1` while nodes 1,5,6 think that `node04` is `Role: 0`

```
{
    'node01': {2: [1, 2, 3, 4, 5, 6, 7]},
    'node02': {1: [1, 5, 6], 0: [2, 3, 4, 7]},
    'node03': {0: [1, 2, 3, 4, 5, 6, 7]},
    'node04': {0: [1, 5, 6], 1: [2, 3, 4, 7]},
    'node05': {1: [1, 2, 3, 4, 5, 6, 7]},
    'node06': {1: [1, 2, 3, 4, 5, 6, 7]},
    'node07': {0: [1, 2, 3, 4, 5, 6, 7]}
}
```

So `node04` and `node02` are the only nodes that do not have a consistent role across the cluster. I will not run` microk8s  start` on them and observe.  After collecting that data, i ran `swapoff -a; microk8s start` on all nodes _except_ `node02` and `node04`.

> I see your nodes run with swap. This is a problem because kubernetes is not able to asses the node resources correctly and will over-commit resources. 

Good observation! I had missed this during initial OS install. I will make adjustments to disable swap long term.


> I would not be surprised If during a reboot all scheduled containers try to reserve memory and the process you see pegging the CPU is kswap. BTW how does a top look like in a pegged machine.

I don't have screenshots handy, but `/snap/microk8s/2035/kube-apiserver` had _many_ entries in `htop` and they were all the biggest consumers of CPU. 

The cluster sans node02/04 seems to be operating about as expected (load average between .4 and 1.5 on  all nodes). I can try to re-introduce node02/4 to see if pegged comes back...

> There is CPU overheating and throttling on your nodes, see for example node07. Could you make sure your nodes have enough cooling? Look at dmesg.

Most of the nodes are [NUC](https://en.wikipedia.org/wiki/Next_Unit_of_Computing) or similar form factor PCs so throttling is, unfortunately, to be expected under sustained high load. Part of the reason for a 7 node cluster was to avoid more than a few pods on any one node to avoid thermal bottlenecks :)... That and I was tired of manually scheduling workloads across hosts and adjusting networking configuration as needed to suit! 

> [16875.160391] connection2:0: detected conn error (1020). Do you know what that might be?

That error appears to come from iSCSI:

https://access.redhat.com/solutions/423473
https://access.redhat.com/solutions/1423383
https://support.hpe.com/hpesc/public/docDisplay?docId=mmr_kc-0118122

This makes sense as I am using iSCSI to provide block level storage to a few pods that do not support file-level (mostly `postgres` containers; they do not support NFS). The *exact* cause of the error is unknown, but the only 'proposed' cause/solution that I see in the above links does not apply in my case  (no jumbo-frames in my LAN). I will keep an eye out for similar behavior, though.


> In MicroK8s the eviction conditions are relaxed so we accommodate the local workstation case. Since you have a cluster you may want to comment out this line so that you go with the default eviction configuration of Kubernetes.


Do you happen to know what those limits are? Going down to `100Mb` available RAM could be an acceptable trigger for eviction depending on if/how the host node recovers.

**Comment by kquinsland** [comment]
Spoke too soon.

I was  trying to  clean up  some of the pods that were  stuck in the `Unknown` state (this usually happens when a given node dies and must be `microk8s remove / add` back)

And nothing was working.
Went to check `microk8s status` and,  apparently, starting up  w/o `node02/node04` un-did HA:

```
root@node01:/home/karl# microk8s status
microk8s is running
high-availability: no
  datastore master nodes: none
  datastore standby nodes: none
```

same with node05 and 07....

**Comment by balchua** [comment]
If we remove node6 from the cluster permanently and then rejoin 2 and 4.  That is `microk8s remove-node` and then join them back.
Just tryin to see if the disk pressure on node 6 might be affecting the cluster state.
