### ISSUE TITLE
k8s.gcr.io/pause:3.1 gets deleted 

### ISSUE THREAD

**Issue by belsakn** [canonical/microk8s#2085]
Hey, 

I'm using microk8s in an offline environment and I import all needed images with `microk8s ctr images import image.tar`. 
After some time `k8s.gcr.io/pause:3.1` gets deleted automatically. If the machine restarts the pods won't be deployed because  `k8s.gcr.io/pause:3.1` can't be pulled.

Any solution to this problem? Can I prevent deleting the pause image somehow?

**Comment by balchua** [comment]
My guess is kubelet is doing some garbage collection.  Can you check if you have disk space pressure?
