### ISSUE TITLE
Connection Refused enabling helm3

### ISSUE THREAD

**Issue by mconner** [canonical/microk8s#2090]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by mconner** [comment]
[inspection-report-20210311_225213.tar.gz](https://github.com/ubuntu/microk8s/files/6126383/inspection-report-20210311_225213.tar.gz)

When trying to enable helm3 I get the following:

```
daruser@darqa:~$ microk8s enable helm3
Enabling Helm 3
Fetching helm version v3.0.2.
[sudo] password for daruser:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to get.helm.sh port 443: Connection refused

```

This is behind a proxy, and I believe this is happening because enable.helm.sh is doing run_with_sudo, which looses any  environment set up as defined by [Installing behind a proxy](https://microk8s.io/docs/install-proxy).  

A workaround (maybe the solution?)  is to set the HTTPS_PROXY in /env/environment, so it is there when the sudo is executed.

**Comment by balchua** [comment]
Thanks for reporting this.
@ktsakalozos do you think adding `preserve_env` when downloading the artifact will help?

**Comment by mconner** [comment]
> Thanks for reporting this.
> @ktsakalozos do you think adding `preserve_env` when downloading the artifact will help?

I don't know what context enable.helm.sh is running.  [Installing behind a proxy](https://microk8s.io/docs/install-proxy) is talking about the containerd environment.  I wouldn't think that applies to a script being run to install helm3.  Also preserve-env, without specifying anything would preserve all environment, which might be overly broad.

**Comment by balchua** [comment]
In that same document it also mentioned about `/etc/environment`. As you mentioned earlier would apply to root, since we are using sudo.

As far as i know the `enable.helm3.sh` is running on the current user context.  But i can be totally wrong here.
