### ISSUE TITLE
Ingresses not working, ingressClass doesn not point to deployed controller  - microk8s v1.20.4 #2074

### ISSUE THREAD

**Issue by sifotes** [canonical/microk8s#2112]
> Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20210321_153820.tar.gz](https://github.com/ubuntu/microk8s/files/6177777/inspection-report-20210321_153820.tar.gz)

3 node cluster.
Add ons enabled: metalLB, ingress, DNS.

I have a pod + service deployed, and an ingress rule for the service. Note the ingressClassName field on the ingress as per v1.18+ docs.  
When trying to reach the service in a browser, I get a nginx 404 error. The service is reachable if it's changed to a nodePort.

When describing the ingress class, it shows the controller as `k8s.io/ingress-nginx` , should this match the microk8s deployed controller called `nginx-ingress-microk8s-controller` ?

> # hello-kubernetes.yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: hello-ingress
> spec:
>   ingressClassName: "public"
>   rules:
>   - host: hello-mk8s.my.domain
>     http:
>       paths:
>       - pathType: Prefix
>         path: /
>         backend:
>           service:
>             name: hello-kubernetes
>             port:
>               number: 8080

`kubectl get ingressclasses.networking.k8s.io`

> NAME     CONTROLLER             PARAMETERS   AGE
> public   k8s.io/ingress-nginx   <none>       28m

`kubectl describe ingressclasses.networking.k8s.io public`

> Name:         public
> Labels:       <none>
> Annotations:  ingressclass.kubernetes.io/is-default-class: true
> Controller:   k8s.io/ingress-nginx
> Events:       <none>

`kubectl get pods -n ingress`

> NAME                                      READY   STATUS    RESTARTS   AGE
> nginx-ingress-microk8s-controller-46d4r   1/1     Running   0          29m
> nginx-ingress-microk8s-controller-dmghq   1/1     Running   0          29m
> nginx-ingress-microk8s-controller-fzw27   1/1     Running   0          29m

**Comment by balchua** [comment]
Hi. This is strange, we run an e2e test including ingress.

Can you try this manifest?
https://github.com/ubuntu/microk8s/blob/master/tests/templates/ingress.yaml
Just to see if it works.

**Comment by 2er0** [comment]
I'm running microk8s with Kubernetes v1.20.5-34+40f5951bd9888a, and I get the same error `404 Not Found`.

I tested with and without the ha-cluster, activated the DNS and ingress addons, and applied the `ingress.yaml` definition from the tests/templates directory. 

Any ideas to debug this? I tried to get useful information but did not found any usefull.

**Comment by balchua** [comment]
Hi @2er0 can you try the manifest i mentioned here? https://github.com/ubuntu/microk8s/issues/2112#issuecomment-804912819 coz that's what we use in the CI.

**Comment by 2er0** [comment]
Removing the `host: microbot.127.0.0.1.nip.io` and `host: microbot.127.0.0.1.xip.io` help in the case of the manifest: https://github.com/ubuntu/microk8s/blob/master/tests/templates/ingress.yaml

Also, my other problems with the Nginx-ingress are now magically gone.
