### ISSUE TITLE
Manually setting up Microk8s on Windows 10 using Multipass install

### ISSUE THREAD

**Issue by mconner** [canonical/microk8s#2120]
`microk8s inspect` tarball:
[inspection-report-20210322_165303.tar.gz](https://github.com/ubuntu/microk8s/files/6185509/inspection-report-20210322_165303.tar.gz)

I'm trying to install microk8s on Windows 10.  However, I want to be able to provide some additional configuration (e.g. [setting up static IPs](https://github.com/canonical/multipass/issues/567#issuecomment-702801046) ).  To do that, I would need to use the Multipass install.   However, I was hoping that I could:

1. Install Multipass
2. Install Microk8s, but _not_ configure a vm as part of the install
3. Create a vm following the multipass install instructions. e.g.:  `multipass launch --name microk8s-vm --mem 4G --disk 40G`

And then I would be able to use the microk8s commands both when shelled into microk8s-vm and from a Windows cmd shell (or maybe gitbash).   It works when shelled into microk8s-vm, but not from a Windows shell.  I just get:

C:>microk8s get pods microk8s-vm.mshome.net
sudo: microk8s.get: command not found
An error occurred when trying to execute 'sudo microk8s.get pods microk8s-vm.mshome.net' with 'multipass': returned exit code 1.

Actually, it just occurred to me to export the config:
`~$ microk8s config > ~/appdata/kubeconfig.yaml`
then scp it out to the windows host machine, and setting KUBECONFIG to that file

Preliminarily, this seems to work.  And based on that:
Am I right in assuming there's nothing special about the host name microk8s-vm?  That is, its just a known host from which the kubectl config has been exported to the windows microk8s cli, right?  I could call it "foo", if I wanted?

More Generally,  Is this the right way to do this?  If so, I would request augmenting the documentation under Alternative Installs to describe this, as it would allow (I think) for multiple nodes (assuming one has the memory and cpus).  (

**Comment by joedborg** [comment]
Hi there @mconner, thanks for raising this.  A few things as I read though. 

You need to do `microk8s kubectl get pods ...`, rather than just `microk8s get`.

If you're creating the Multipass VM manually (rather than via `microk8s install`), you'll also need to do the extra steps that does (https://github.com/ubuntu/microk8s/blob/6a6b6b72af5e0aff4c2ff9f0c0f276ef66f5191f/installer/vm_providers/_base_provider.py#L125-L126).  This effectively runs

```
sudo snap install microk8s --classic
sudo snap install microk8s-integrator-windows
```

inside the VM and then places the kubeconfig file, from MicroK8s, into the right place for the bundled kubectl on the host to see (https://github.com/ubuntu/microk8s/blob/6a6b6b72af5e0aff4c2ff9f0c0f276ef66f5191f/installer/common/file_utils.py#L83).

In terms of the VM name, it's not just kubectl that needs to reach the VM, all of the other MicroK8s subcommands are proxied into the VM via Multipass; it uses the static VM name to pass that.

I'm not entirely sure what you're trying to achieve by doing it manually, if it's only setting a static IP for the VM, I think we can add this as a feature of the installer, rather than promoting manual installs.  If you could clarify, I'd much appreciate it.

**Comment by mconner** [comment]
Well, I'd _swear_ I actually did try `microk8s kubectl get pods`, after I got the error, but I can't find that looking back at what I typed, so I'll assume I was just being boneheaded, and exporting the config _seemed_ to fix it.  

What I was hoping was to have the option to do is to create _multiple_ VMs, possibly to test clustering, but certainly to run different configurations.  It doesn't sound like the Windows install would support this, since it connects to just the one host, by name. I was thinking of something similar to what docker machine allows (allowed?) where the windows environment can be set to point at any of several vms, and the windows cli uses that environment to connect.  

Static IPs make it easier to diagnose issues and automate builds and such.  For example, I'd like to run helm from the windows side of things against the cluster in the vm.  To do that, I need to pull the kubeconfig and export it to my windows file system, then set the env variable KUBECONFIG.  The server is stored in the kubeconfig as an IP, not a name (see below).  If the ip is not static, then I have to remember to pull that any time I restart the vm, or when I reboot my machine.   And I believe we had some issues using host names rather than IP with kafka configuration.   Also, and a minor point, microk8s.mshome.net is a lot to type, when you need to. It would be nice to have some names like: uk8s1, uk8s2, that I could add to /etc/hosts.  

Aside: I've noticed a couple of things, which may be related to the way I installed microK8s (multipass + windows): 

First, after a restart of the vm, the IP given in my AppData\Local\MicroK8s\Config is incorrect:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  ... 
    server: https://192.168.204.244:16443
  name: microk8s-cluster
  ...
```
It appears not to have been updated with the new IP. Maybe that's because I did not snap microk8s-integrator-windows, and maybe it doesn't matter, since apparently, it uses the hostname.  

Second, when I do a microk8s stop --help, it shuts down the vm after providing the usage (See last line):
```
$ microk8s stop --help
Usage: /snap/microk8s/2074/microk8s-stop.wrapper [OPTIONS]

Stop Kubernetes services

Options:
 -h, --help          Show this help
Stopping microk8s-vm \
```
It should just show the usage. (Also, there's no way to only stop microK8s, not the vm, short of shelling in).  Further, if I then do a start, it errors:
```
$ microk8s start
exec failed: instance "microk8s-vm" is not running
An error occurred when trying to execute 'sudo microk8s.start' with 'multipass': returned exit code 2.

$ microk8s start
exec failed: instance "microk8s-vm" is not running
An error occurred when trying to execute 'sudo microk8s.start' with 'multipass': returned exit code 2.

```
I have to start it with multipass.
