### ISSUE TITLE
Can't get status, inspect stuck

### ISSUE THREAD

**Issue by kwonmha** [canonical/microk8s#2125]
`microk8s status` doesn't show anything.
It says, microk8s isn't running.
I stopped and started microk8s but it didn't work.
And, I can't run `microk8s inspect` either.
```
(base) user01@user-X299-WU8:/var/snap/microk8s/current/args$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
(base) user01@user-X299-WU8:/var/snap/microk8s/current/args$ microk8s stop
Stopped.
(base) user01@user-X299-WU8:/var/snap/microk8s/current/args$ microk8s start
Started.
(base) user01@user-X299-WU8:/var/snap/microk8s/current/args$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

(base) user01@user-X299-WU8:/var/snap/microk8s/current/args$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
```

It stucks more than 10 minutes.

**Comment by balchua** [comment]
@kwonmha just wanted to check if you are still facing this issue. Thanks

**Comment by kwonmha** [comment]
I can't reproduce this issue now.
I'll report later if this happens again.

**Comment by balchua** [comment]
Great to hear that. Thanks 👍

**Comment by Pezhvak** [comment]
something is off, my cluster is not working at all, tried re installing all the nodes but it keeps happening, here is my tarball:
[inspection-report-20210412_150020.tar.gz](https://github.com/ubuntu/microk8s/files/6299281/inspection-report-20210412_150020.tar.gz)

**Comment by balchua** [comment]
@Pezhvak can you tey to remove it with `sudo snap remove microk8s --purge`?  Then do `sudo snap install --classic --channel <the channel you want>`

**Comment by betsegaw** [comment]
I have run into something similar and I get inconsistent results...

Basically, a low powered (1 cpu 1 gb ram) Azure VM with ubuntu server 20 lts never returns a value for microk8s status or microk8s inspect... and instead hangs.

Is that behavior expected?

**Comment by balchua** [comment]
@betsegaw my guess is that the kernel is killing the apiserver due to memory pressure.  You may want to try enabling swap.  But that is highly discouraged by kubernetes.  Imho 1GB is too small for kubernetes.

**Comment by betsegaw** [comment]
@balchua - thank you for the reply and you are correct, increasing the memory of the VM fixed things. Sorry for the late confirmation but I had my github notifications off and didn't see someone had replied.

**Comment by RaghuMeda** [comment]
> I have run into something similar and I get inconsistent results...
> 
> Basically, a low powered (1 cpu 1 gb ram) Azure VM with ubuntu server 20 lts never returns a value for microk8s status or microk8s inspect... and instead hangs.
> 
> Is that behavior expected?

It's the same issue for me. I am using Raspberry Pi3 with 2 cpu and 1 GB ram and microk8s status and microk8s inspect always hangs out. Its pure luck when it works. I did replicate the same issue happens in AWS EC2 with 2 cpu and 1 GB ARM64 system. I beleieve Microk8s is not tested throughly yet for ARM64 systems with low power. Although it says it works for low power devices thats not true.

**Comment by fritzprix** [comment]
have same issue from 1.23/stable with Raspberry Pi3. Is there specific version that works with rpi3? or any plan to fix issue? 
or any walkaround for this?

**Comment by felipegouveiae** [comment]
I'm having the same issue after rebooting my Mac m1 over Multipass.

**Comment by xvilo** [comment]
I'm having similar issues on an RPi 5 8GB, after my internal network's ip changed. I'm in the process of trying to get it all working again but it just hangs:
```
$ microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
 FAIL:  Service snap.microk8s.daemon-apiserver-proxy is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver-proxy
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy asnycio usage and limits to the final report tarball
  Copy inotify max_user_instances and max_user_watches to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```

**Comment by Kavlings** [comment]
> have same issue from 1.23/stable with Raspberry Pi3. Is there specific version that works with rpi3? or any plan to fix issue? or any walkaround for this?
> 
> ```
> microk8s inspect
> Inspecting Certificates
> Inspecting services
>   Service snap.microk8s.daemon-cluster-agent is running
>   Service snap.microk8s.daemon-containerd is running
>   Service snap.microk8s.daemon-k8s-dqlite is running
>   Service snap.microk8s.daemon-kubelite is running
>   Service snap.microk8s.daemon-apiserver-kicker is running
>   Copy service arguments to the final report tarball
> Inspecting AppArmor configuration
> Gathering system information
>   Copy processes list to the final report tarball
>   Copy snap list to the final report tarball
>   Copy VM name (or none) to the final report tarball
>   Copy disk usage information to the final report tarball
>   Copy memory usage information to the final report tarball
>   Copy server uptime to the final report tarball
>   Copy current linux distribution to the final report tarball
>   Copy openSSL information to the final report tarball
>   Copy network configuration to the final report tarball
> Inspecting kubernetes cluster
>   Inspect kubernetes cluster
> HANGS HERE!!
> ```

Having the same issue here on an Pi3 as well, anyone found a fix yet?
