### ISSUE TITLE
help request - Ingress controller does not apply settings specified in deployment.yaml file

### ISSUE THREAD

**Issue by mitja-suncic** [canonical/microk8s#2128]
Report tarball:
[inspection-report-20210324_143124.tar.gz](https://github.com/ubuntu/microk8s/files/6197601/inspection-report-20210324_143124.tar.gz)

**Environment info**:
Microk8s version: `microk8s    v1.20.4   
2074    1.20/stable   canonical✓   classic`
OS version: `NAME="Ubuntu" VERSION="20.04.2 LTS (Focal Fossa)"`
Enabled services: DNS, Ingress
Disabled services: HA Cluster
Deployment type: single node

**Problem description**:
When we apply our application in Microk8s with a deployment YAML file, our Ingress configurations do not get applied.
Our Ingress configuration (attached in a file to preserve the indentation):
[ingress_setting_dummy_data.txt](https://github.com/ubuntu/microk8s/files/6198033/ingress_setting_dummy_data.txt)

After deploying the above configuration (kubectl apply -f deployment.yaml), we expect to see it applied in Ingress.
More specifically, we expect the /etc/nginx/nginx.conf file on the Ingress controller pod to have a new entry for our hostname.com server. That is not the case. In the logs of the Ingress controller we see that it skips applying the configuration and does not even pick up the specified values:
`I0324 12:58:09.045267  7 store.go:363] ignoring add for ingress ingress-service based on annotation kubernetes.io/ingress.class with value`

Removing the "kubernetes.io/ingress.class: nginx" annotation and replacing it with "ingressClassName", as seen below, does not solve the issue:
`apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
    ingressClassName: nginx`

We believe that there is something wrong with our deployment specification, but we cannot figure out what. What's more, we've had success with other apps when using Ingress that is configured almost identically. 
I've attached a full deployment file for the app below.

Kind regards,
Mitja

[app_deployment_dummy_data.txt](https://github.com/ubuntu/microk8s/files/6198059/app_deployment_dummy_data.txt)

**Comment by balchua** [comment]
Try using `public` as your `ingressClassName`
