### ISSUE TITLE
kubectl port-forward times out unless I disconnect the wifi (network manager)

### ISSUE THREAD

**Issue by spicysomtam** [canonical/microk8s#2130]
Also `microk8s inspect` also hangs on `Inspecting kubernetes cluster` until I disconnect the wifi connection (using Network Manager in the Mint gui).

```
$ microk8s kubectl port-forward pod/ng-nginx-546d8f98c9-4jbp7 8080:80 # wifi connected

error: error upgrading connection: error dialing backend: dial tcp 92.242.132.24:10250: i/o timeout

$ microk8s kubectl port-forward pod/ng-nginx-546d8f98c9-4jbp7 8080:80 # After disconnect wifi; reconnect still works.
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
```
Tried microk8s 1.18/stable and it was identical so must be my networking config (but what?).
Mint 20.1

[inspection-report-20210324_202754.tar.gz](https://github.com/ubuntu/microk8s/files/6200325/inspection-report-20210324_202754.tar.gz)

**Comment by balchua** [comment]
I can see that your interface is named `wlo` which i think calico will ignore.

Care to try this ?
https://github.com/ubuntu/microk8s/issues/1554#issuecomment-691426908

**Comment by spicysomtam** [comment]
Hi. Thanks for responding. I tried this and it did not work. Tried a reboot, stop/restart microk8s, etc. Issue is still the same.

**Comment by balchua** [comment]
Just clarifying here, you have 2 networks, one wifi and another one ethernet?

**Comment by spicysomtam** [comment]
Sorry for the late reply. Its a laptop with a wifi and a wired ethernet (not connected/no link).

**Comment by recursionbane** [comment]
I am seeing this command hang, too:

`sudo snap run microk8s kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443`

I think this might happen whenever the host exposes multiple IP addresses.

Is there any way to specify the primary IP address to expose in microk8s?

**Comment by balchua** [comment]
@recursionbane i think there is a way to specify `--advertise-address` pr `--bind-address` that in the `/var/snap/microk8s/current/args/kube-apiserver`. Make sure you restart MicroK8s

**Comment by recursionbane** [comment]
Thanks, @balchua, I tried the following with no luck:

```
> sudo snap remove microk8s ; sudo snap install microk8s --classic --channel=1.20/edge                                                                           
snap "microk8s" is not installed                                                                                    
microk8s (1.20/edge) v1.20.6 from Canonical✓ installed
```

```
> sudo snap run microk8s enable dns dashboard
```

Then I tried all combinations of `--advertise-address` and `--bind-address` in `/var/snap/microk8s/current/args/kube-apiserver` followed by `sudo snap restart microk8s`
```
--advertise-address=<IP>
--bind-address=<IP>
# Result of sudo snap restart microk8s; sudo snap run microk8s status: microk8s is not running.
```
```
# --advertise-address=<IP>
--bind-address=<IP>
# Result of sudo snap restart microk8s; sudo snap run microk8s status: microk8s is not running.
```
```
--advertise-address=<IP>
# --bind-address=<IP>
# Result of sudo snap restart microk8s; sudo snap run microk8s status: microk8s is running
# Result of port-forward: hangs
```

In the end, I patched the dashboard service with the correct IP as follows:

```
> sudo snap run microk8s kubectl patch -n kube-system service/kubernetes-dashboard -p '{"spec":{"externalIPs":["<IP>"]}}'
service/kubernetes-dashboard patched
```

I verified that `service/kubernetes-dashboard` now shows an `EXTERNAL-IP`, and I'm able to connect to it.

**Comment by balchua** [comment]
@recursionbane just clarifying it, 
You do port forwarding from tge microk8s machine, then you access the dashboard from the same microk8s machine, right?

**Comment by recursionbane** [comment]
No, I am trying to access the dashboard from another machine on the same network.

**Comment by balchua** [comment]
Oh i see, then you do the port-forward from that machine (not the MicroK8s machine), so you can access it locally.

**Comment by recursionbane** [comment]
Thanks, @balchua. The patching of the external IP works, as well.
