### ISSUE TITLE
rfe: please optimize ip-change detection for performance benefit and saving sdd life

### ISSUE THREAD

**Issue by devZer0** [canonical/microk8s#2154]
from what it looks like, ip change detection is based on re-creating certificate file every 3 seconds via apiservice-kicker.

why is certificate file constantly being re-created and then (apparently?) used for nothing but ip change detection ?

why doesn't microk8s detect ip change in ram (or in a less costly way) and takes action based in that,  instead of needlessly fireing up shell process chain and wasting precious disk iops and wearing out ssd  ?

root@microk8s:~# fatrace  -t |grep csr
11:39:12.561753 cp(3867136): O /var/snap/microk8s/2094/certs/csr.conf.template
11:39:12.561802 cp(3867136): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.561853 cp(3867136): R /var/snap/microk8s/2094/certs/csr.conf.template
11:39:12.561884 cp(3867136): CW /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.561884 cp(3867136): C /var/snap/microk8s/2094/certs/csr.conf.template
11:39:12.565796 sed(3867138): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.565873 sed(3867138): R /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.566248 sed(3867138): C /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.568778 cmp(3867139): RCO /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:12.568778 cmp(3867139): RCO /var/snap/microk8s/2094/certs/csr.conf
11:39:15.630921 cp(3867176): O /var/snap/microk8s/2094/certs/csr.conf.template
11:39:15.630966 cp(3867176): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.631100 cp(3867176): R /var/snap/microk8s/2094/certs/csr.conf.template
11:39:15.631100 cp(3867176): CW /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.631159 cp(3867176): C /var/snap/microk8s/2094/certs/csr.conf.template
11:39:15.634896 sed(3867178): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.634989 sed(3867178): R /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.635236 sed(3867178): C /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.637650 cmp(3867179): RO /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:15.637650 cmp(3867179): O /var/snap/microk8s/2094/certs/csr.conf
11:39:15.637725 cmp(3867179): RC /var/snap/microk8s/2094/certs/csr.conf
11:39:15.637725 cmp(3867179): C /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.701738 cp(3867201): O /var/snap/microk8s/2094/certs/csr.conf.template
11:39:18.701738 cp(3867201): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.701738 cp(3867201): R /var/snap/microk8s/2094/certs/csr.conf.template
11:39:18.701827 cp(3867201): CW /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.701911 cp(3867201): C /var/snap/microk8s/2094/certs/csr.conf.template
11:39:18.705661 sed(3867203): RO /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.705850 sed(3867203): C /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.708447 unknown(3867204): O /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.708447 unknown(3867204): O /var/snap/microk8s/2094/certs/csr.conf
11:39:18.708867 unknown(3867204): RC /var/snap/microk8s/2094/certs/csr.conf.rendered
11:39:18.708867 unknown(3867204): RC /var/snap/microk8s/2094/certs/csr.conf

also see https://github.com/ubuntu/microk8s/issues/2096

**Comment by devZer0** [comment]
as it seems, there's a lot of processes exec()'ed repeatedly for things which seldom/never change. 

why updating linux kernel iptables with the same data over and over again, for example ?

# cat execsnoop.log | cut -b 1-10,35- |sort|uniq -c|sort -rn
   1695 snapctl    0 /usr/bin/snapctl services microk8s.daemon-apiserver
   1695 sleep      0 /snap/microk8s/2094/bin/sleep 3
   1695 sed        0 /snap/microk8s/2094/bin/sed -i s/#MOREIPS/IP.3 = 172.16.31.207\nIP.4 = 10.1.38.0/g /var/snap/microk8s/2094/certs/csr.conf.rendered
   1695 openssl    0 /snap/microk8s/2094/usr/bin/openssl x509 -noout -issuer
   1695 ip         0 /snap/microk8s/2094/sbin/ip route
   1695 ip         0 /snap/microk8s/2094/sbin/ip -o -4 addr list vxlan.calico
   1695 ifconfig   0 /snap/microk8s/2094/sbin/ifconfig vxlan.calico
   1695 hostname   0 /snap/microk8s/2094/bin/hostname -I
   1695 head       0 /snap/microk8s/2094/usr/bin/head -1
   1695 grep       0 /snap/microk8s/2094/bin/grep default
   1695 grep       0 /snap/microk8s/2094/bin/grep active
   1695 grep       0 /snap/microk8s/2094/bin/grep -E (--advertise-address|--bind-address) /var/snap/microk8s/2094/args/kube-apiserver
   1695 gawk       0 /snap/microk8s/2094/usr/bin/gawk {print $4}
   1695 cut        0 /snap/microk8s/2094/usr/bin/cut -d/ -f1
   1695 cp         0 /snap/microk8s/2094/bin/cp /var/snap/microk8s/2094/certs/csr.conf.template /var/snap/microk8s/2094/certs/csr.conf.rendered
   1695 cmp        0 /snap/microk8s/2094/usr/bin/cmp -s /var/snap/microk8s/2094/certs/csr.conf.rendered /var/snap/microk8s/2094/certs/csr.conf
   1694 systemctl  0 /usr/bin/systemctl show --property=Id,ActiveState,UnitFileState,Type snap.microk8s.daemon-apiserver.service
   1029 iptables   0 /snap/microk8s/2094/sbin/iptables -t filter -C FORWARD -s 10.1.0.0/16 -j ACCEPT --wait
   1029 iptables   0 /snap/microk8s/2094/sbin/iptables -t filter -C FORWARD -d 10.1.0.0/16 -j ACCEPT --wait
   1027 iptables   0 /snap/microk8s/2094/sbin/iptables -t nat -C POSTROUTING -s 10.1.0.0/16 -d 10.1.0.0/16 -j RETURN --wait
   1027 iptables   0 /snap/microk8s/2094/sbin/iptables -t nat -C POSTROUTING -s 10.1.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --wait
   1027 iptables   0 /snap/microk8s/2094/sbin/iptables -t nat -C POSTROUTING ! -s 10.1.0.0/16 -d 10.1.38.0/24 -j RETURN --wait
   1027 iptables   0 /snap/microk8s/2094/sbin/iptables -t nat -C POSTROUTING ! -s 10.1.0.0/16 -d 10.1.0.0/16 -j MASQUERADE --wait
    501 getent     0 /usr/bin/getent group microk8s
    500 kubectl    0 /snap/microk8s/2094/kubectl --kubeconfig=/var/snap/microk8s/2094/credentials/client.config get nodes --all-namespaces
    500 kubectl    0 /snap/microk8s/2094/kubectl --kubeconfig=/var/snap/microk8s/2094/credentials/client.config get all --all-namespaces
    173 iptables   0 /snap/microk8s/2094/sbin/iptables -w 5 -W 100000 -S KUBE-PROXY-CANARY -t mangle
     86 iptables   0 /snap/microk8s/2094/sbin/iptables -w 5 -W 100000 -S KUBE-KUBELET-CANARY -t mangle
     26 sort       0 /usr/bin/sort

**Comment by balchua** [comment]
Hi, i think there is a way not to trigger the ip change, by adding to `/var/snap/microk8s/current/args/kube-apiserver` these argument.

```
--advertise-address
--bind-address
```
As an example `--bind-address=0.0.0.0`
Check if you still see those ip change detections.
Thanks

**Comment by devZer0** [comment]
activity

**Comment by neoaggelos** [comment]
Hi @devZer0 

Nope, the project is definitely not dead :) Some old issues have been moved to the wayside, especially ones without activity from the original reporter. Apologies for this, as I mentioned in the other issue, we are trying our best to improve on this.

Looking at the original issue, some of the commands that are listed are part of the apiservice-kicker, and others are part of the kubelite startup process routine. These have changed significantly in recent versions. Is the environment still active and somewhere you can try debugging? Having an introspection report would greatly help. From the looks of it, it appears that the kubelite process is constantly restarting. Any logs from journalctl (included in the introspection report) would be valuable information to see why this happens and how to approach a solution.

I would be interested to also see if this is the case when you install a recent version on a fresh instance `sudo snap install microk8s --classic`. If you are interested, can you try this out and get back to this issue with any possible issues?

Thank you, I'm keen on helping you resolve this.
