### ISSUE TITLE
feature request: update Istio

### ISSUE THREAD

**Issue by howardjohn** [canonical/microk8s#2163]
The Istio version used seems to be quite old: https://github.com/ubuntu/microk8s/blob/c9d10eaa89c014cd3a159f1829a65f5125ee754c/microk8s-resources/actions/enable.istio.sh#L12.

This version has been EOL for a while now (https://istio.io/latest/news/support/announcing-1.5-eol-final/) and as such has a number of critical bugs and security vulnerabilities unfixed.  I would encourage this to be updated to Istio 1.9.

Please let me know if you need any help with this, I am an Istio maintainer.

**Comment by balchua** [comment]
Hi @howardjohn thanks for spotting this one.   
And yes the addon needs an upgrade.  we have been looking for some help to upgrade the istio addon.

**Comment by tbertenshaw** [comment]
:( shame. Thought that the Envoy support was the blocker.

**Comment by Diablo2050** [comment]
Using microk8s with Istio and would love to use the latest version.
