### ISSUE TITLE
I/O timeout when attempting to retrieve pod logs

### ISSUE THREAD

**Issue by knkski** [canonical/microk8s#2169]
I have a CI process that has two runs from a single commit. The first one worked, and the second one failed:

https://github.com/canonical/mlmd-operator/actions/runs/743163722
https://github.com/canonical/mlmd-operator/actions/runs/743163708

When I try to get logs in the failing run, I get this error:

```
Run kubectl logs --tail 100 -nci-test -ljuju-app
Error from server: Get "https://fv-az167-675:10250/containerLogs/ci-test/mlmd-0/mlmd?tailLines=100": dial tcp 10.1.1.187:10250: i/o timeout
Error: Process completed with exit code 1.
```

Additionally, generating the `microk8s inspect` tarball takes a long time (~7.5m) as parts of it also encounter the same or similar errors. For example, the `cluster-info-dump` file just shows this error instead of pod logs:

```
==== START logs for container coredns of pod kube-system/coredns-86f78bb79c-2zxrl ====
Request log error: an error on the server ("unknown") has prevented the request from succeeding (get pods coredns-86f78bb79c-2zxrl)
```

Here are the working and failing inspection reports:
[inspection-working.zip](https://github.com/ubuntu/microk8s/files/6300962/inspection-report-2.zip)
[inspection-failing.zip](https://github.com/ubuntu/microk8s/files/6300964/inspection-report-3.zip)

**Comment by ktsakalozos** [comment]
Unfortunately in the logs of the API server I see a lot of timeouts coming from the datstore, eg
```
Apr 13 01:51:49 fv-az167-675 microk8s.daemon-apiserver[6499]: I0413 01:51:49.324722    6499 trace.go:205] Trace[1577669352]: "Get" url:/api/v1/namespaces/ci-test/pods/mlmd-0/log,user-agent:kubectl/v1.20.5 (linux/amd64) kubernetes/40f5951,client:127.0.0.1 (13-Apr-2021 01:51:19.320) (total time: 30004ms):
Apr 13 01:51:49 fv-az167-675 microk8s.daemon-apiserver[6499]: Trace[1577669352]: ---"Transformed response object" 30000ms (01:51:00.324)
Apr 13 01:51:49 fv-az167-675 microk8s.daemon-apiserver[6499]: Trace[1577669352]: [30.004140221s] [30.004140221s] END
Apr 13 01:52:11 fv-az167-675 microk8s.daemon-apiserver[6499]: E0413 01:52:11.148016    6499 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"error dialing backend: dial tcp 10.1.0.23:10250: i/o timeout"}
```

I do not have a fix for this at the moment I need to investigate more.

**Comment by knkski** [comment]
Looks like this is due to an issue with Github Actions: https://github.com/actions/virtual-environments/issues/3185
