### ISSUE TITLE
Microk8s - Kubeflow - Certificate Errors

### ISSUE THREAD

**Issue by vishalaj1** [canonical/microk8s#2172]
Hi,

I am trying Microk8s with kubeflow on local machine.

When i installed and use kubeflow it works fine.

But then i shutdown my laptop and open again. Next day a new ip address is assigned to VM and the Kubeflow services stop working with certificate and host error. Any idea how this can be fixed?

Regards,
Vishal

**Comment by ktsakalozos** [comment]
Hi @vishalaj1. Changing the IP of the kubernetes cluster results in the service account keys to be re-issued. As a result some pods may need to be deleted and recreated. The obvious approach is to have the VM get a static IP. @knkski may know of an alternative way to handle such IP changes.

**Comment by knkski** [comment]
@vishalaj1 Can you post the exact error you're seeing here?
