### ISSUE TITLE
Adding node to existing cluster with a shared subnet fails

### ISSUE THREAD

**Issue by khumps** [canonical/microk8s#2173]
A little overview of the structure of my cluster:
- Currently contains 3 nodes, each one of these nodes has an interface in both the subnets 192.168.2.0/24 and 172.16.1.0/28. The 172 subnet is a completely isolated 10G network existing between the existing 3 nodes (no connection to 4th node)
- These 3 nodes were joined together on the 172 subnet.
- In the output of `microk8s status` they are referred to by their IPs in the 172 subnet
- The 4th node does not have a 172 interface, only a 192 interface
- The 4th node is unable to connect using `microk8s join $IP_AND_TOKEN_OF_MASTER_NODE_192_ADDRESS`
[`microk8s inspect` tarball on failed 4th node](https://github.com/ubuntu/microk8s/files/6308057/inspection-report-after-purge.tar.gz)
I raised this issue in slack and @balchua says it appears that dqlite is trying to connect to the other nodes using their 172 interfaces which fails as that route doesn't exist

**Comment by ktsakalozos** [comment]
Hi @khumps this behavior is expected. When you do a `microk8s add-node` you are presented with a list of connection strings one for each network interface you have. At this point you have to connect your nodes on the network that is available to all nodes. So the three nodes on the 172 subnet should have been clustered using the 192 one so the fourth could also join.

Think about it this way, when the 4th node on the 192 subnet joins it contacts the node shown in the connection string `$IP_AND_TOKEN_OF_MASTER_NODE_192_ADDRESS` and requests a list of all the nodes already in the cluster. The already clustered nodes have registered with the 172 subnet. The joining node tries then to contact the leader of the cluster that has an 172 IP and fails.

**Comment by khumps** [comment]
@ktsakalozos  then that 192 output from add-node is misleading and should be removed. The cluster should detect that subnet is unusable for connecting and not return it as a viable connection endpoint as the cluster has already agreed on a subnet.

**Comment by balchua** [comment]
But if the node4 has 2 interfaces like the others, using the 192 subnet will still work right, coz it can still reach the 172 nodes thru the other network iface.

**Comment by khumps** [comment]
@balchua I mentioned in bullet 4 that the 4th node doesn't have a 172 interface

**Comment by balchua** [comment]
Sorry my response wasn't very clear.  What i mean is that if in the case that all nodes have access to each other's subnets, then one can use any of those join tokens printed.  But yes if a node like in your case do not belong to that subnet then it is a good option.

**Comment by khumps** [comment]
To sum up my conversation with @ktsakalozos, this is expected behavior as dqlite does not support inter-subnet communication within it's cluster. As a feature request based on that knowledge, `microk8s add-node` should not show any interfaces that it can not properly initiate a connection over (all interfaces work on a fresh install but as soon as a node is added, the interface is locked)
