### ISSUE TITLE
Signing the CLA and the new cla-check

### ISSUE THREAD

**Issue by tbertenshaw** [canonical/microk8s#2175]
I have already contributed and also signed the CLA using the same email.

I noticed after a recent update to a PR #2052 that the new `cla-check` github action, is failing for my build.

After some checking i installed the  `cla-check` snap and i could verify that Canonical believe that this email has signed the `CLA`.

![image](https://user-images.githubusercontent.com/2010002/114839641-eaea1d00-9dcd-11eb-85e1-08b5c56d9c16.png)

So am i missing a step regarding how i create my pr so that the action can verify the contributing email against the CLA?
Or does the [documentation](../blob/master/CONTRIBUTING.md) need updating?

**Comment by evilnick** [comment]
Hmm, that does look like something is going wrong with the action and we should check into it
