### ISSUE TITLE
Ingress is not working after restoring a snapshot

### ISSUE THREAD

**Issue by gcalvinos** [canonical/microk8s#2176]
Hello,

After restoring a snapshot I did with snap, when I started microk8s, ingress started to fail.

These are the steps I followed to get the error:

1.- I have one single node microk8s with the following services enabled:
```
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    metallb              # Loadbalancer for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    storage              # Storage class; allocates storage from host directory
```

2.- I have some workloads deployed on it

3.- I take a snapshot, for that first I stop microk8s:
```
  microk8s stop
  sudo snap save microk8s
```
4.- I start microk8s and delete one of the workloads (the aim of my tests was to check the backup&restore)
```
  microk8s start
```
5.- I stopped microk8s and restore the snapshot:
```
  microk8s stop
  sudo snap restore 1
```

Then all the pods were able to start (including the ones I deleted) with the exception of ingress:
```
  microk8s kubectl -n ingress get pods  
  NAME                                      READY   STATUS             RESTARTS   AGE 
  nginx-ingress-microk8s-controller-l52cs   0/1     CrashLoopBackOff   393        24h
```
Find the output of 'describe pod' command here:
[https://pastebin.canonical.com/p/ZbbWYH3F8v/](https://pastebin.canonical.com/p/ZbbWYH3F8v/)

And the output of the logs of the pod:
[https://pastebin.canonical.com/p/G32nCqN6VN/](https://pastebin.canonical.com/p/G32nCqN6VN/)

And finally the inspection report:

[inspection-report-20210412_101330.tar.gz](https://github.com/ubuntu/microk8s/files/6318959/inspection-report-20210412_101330.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @gcalvinos is it possible you did not attach the right inspection tarball? The logs on the attached tarball is fro the 12th of April when the API server was failing with:
```
Apr 12 10:11:33 microk8s microk8s.daemon-apiserver[17351]: Error: kine: building kine: failed to migrate DB from sqlite: COUNT(*)
```

On the pastebins I see this error:
```
2021/04/15 14:32:07 [emerg] 37#37: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```
that makes me wonder if the apparmor profiles containerd creates are part of the snapshot.

**Comment by gcalvinos** [comment]
You are right! Sorry about that. Here is the updated one:

[inspection-report-20210415_143617.tar.gz](https://github.com/ubuntu/microk8s/files/6323891/inspection-report-20210415_143617.tar.gz)

**Comment by gcalvinos** [comment]
Hello @ktsakalozos 
I added the right inspection tarball, just in case you didn't see it.
