### ISSUE TITLE
Error during automated microk8s restart while enabling DNS and metrics-server/RBAC

### ISSUE THREAD

**Issue by dlampa** [canonical/microk8s#2183]
While executing:

`sudo microk8s enable dns storage registry:size=20Gi metrics-server`

the following messages are displayed: 

```
    Enabling DNS..
    Applying manifest
    serviceaccount/coredns created
    configmap/coredns created
    deployment.apps/coredns created
    service/kube-dns created
    clusterrole.rbac.authorization.k8s.io/coredns created
    clusterrolebinding.rbac.authorization.k8s.io/coredns created
    Restarting kubelet
    error: error running snapctl: snap "microk8s" has "service-control" change in progress
    Enabling default storage class
    deployment.apps/hostpath-provisioner created
    storageclass.storage.k8s.io/microk8s-hostpath created
    serviceaccount/microk8s-hostpath created
    clusterrole.rbac.authorization.k8s.io/microk8s-hostpath created
    clusterrolebinding.rbac.authorization.k8s.io/microk8s-hostpath created
    Storage will be available soon
    Addon storage is already enabled.
    Enabling the private registry
    Applying registry manifest
    namespace/container-registry created
    persistentvolumeclaim/registry-claim created
    deployment.apps/registry created
    service/registry created
    configmap/local-registry-hosting configured
    The registry is enabled
    The size of the persistent volume is 20Gi
    Enabling Metrics-Server
    clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
    clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
    rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
    Warning: apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
    apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
    serviceaccount/metrics-server created
    deployment.apps/metrics-server created
    service/metrics-server created
    clusterrole.rbac.authorization.k8s.io/system:metrics-server created
    clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
    clusterrolebinding.rbac.authorization.k8s.io/microk8s-admin created
    error: error running snapctl: snap "microk8s" has "service-control" change in progress
```
There appears to be no adverse effect on functionality, and both DNS and the metrics-server run fine. 

It also appears that this is in some way related to the node microk8s is deployed on (e.g happens very often on low-spec VMs on GCP, or even "large" spec AWS instances).

Perhaps, introduce a check for change in progress and sleep until available prior to restarting microk8s?

**Comment by balchua** [comment]
Hi @dlampa just checking if you are still getting this issue after adding this apiserver args?
`--bind-address=0.0.0.0` or `--advertise-address=127.0.0.1` to the `/var/snap/microk8s/current/args/kube-apiserver`.
Thanks

**Comment by dlampa** [comment]
Hi @balchua - I've just done a few deployments with added `--advertise-address=127.0.0.1` arg. It appears to work fine now. Is this something that can be implemented upfront without needing the user to modify the args manually? 

Perhaps something to note which was not mentioned in the original post (but we did discuss on Slack) is that this issue only occurs with `ha-cluster` disabled.

**Comment by balchua** [comment]
Thanks for getting back to us on this topic.
I think in the future there maybe an option to stop the api service kicker from reacting to network changes and reissue certs.  https://github.com/ubuntu/microk8s/pull/2217
I haven't looked at it in detail, but its not something that comes as default i think.

**Comment by dlampa** [comment]
Sorry, please see my updated response above - it seems that there is now another issue as a result of the change.

**Comment by balchua** [comment]
Oops maybe the advertise-address value is wrong.  I don't remember if `0.0.0.0` will work.

**Comment by dlampa** [comment]
Yes, everything works correctly if `--bind-address=0.0.0.0` is used instead of `--advertise-address`.
