### ISSUE TITLE
add node on macOS not working 

### ISSUE THREAD

**Issue by Aaronlj2000** [canonical/microk8s#2190]
I am trying to create a cluster.  I issued the following microk8s command:
ubuntu@microk8s-ctl:~$ microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.64.8:25000/3bda567cd59fac17834586b40ed23425/d9af3875a8bc

If the node you are adding is not reachable through the default interface you can use one of the following:
 microk8s join 192.168.64.8:25000/3bda567cd59fac17834586b40ed23425/d9af3875a8bc

On the joining node I issued the command with the following results: 
ubuntu@microk8s-n1:~$ microk8s join 192.168.64.8:25000/3bda567cd59fac17834586b40ed23425/d9af3875a8bc
Contacting cluster at 192.168.64.8
Connection failed. (500).

The microk8s status is the following:
ubuntu@microk8s-ctl:~$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: none
  datastore standby nodes: none
addons:
  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    storage              # Storage class; allocates storage from host directory
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    gpu                  # Automatic enablement of Nvidia CUDA
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    istio                # Core Istio service mesh services
    jaeger               # Kubernetes Jaeger operator with its simple config
    keda                 # Kubernetes-based Event Driven Autoscaling
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    multus               # Multus CNI enables attaching multiple network interfaces to pods
    openebs              # OpenEBS is the open-source storage solution for Kubernetes
    openfaas             # openfaas serverless framework
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    traefik              # traefik Ingress controller for external access
[inspection-report-20210421_091642.tar.gz](https://github.com/ubuntu/microk8s/files/6351186/inspection-report-20210421_091642.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by Aaronlj2000** [comment]
My MAC version is 10.15.7

**Comment by ktsakalozos** [comment]
Hi @Aaronlj2000 how did you deploy MicroK8s? The installer starts a linux VM in which MicroK8s get installed. I guess you have two VMs, right? Are the two VMs on the same network? I think they are `192.168.64.9` and `192.168.64.8`. Are their hostnames resolvable?

**Comment by Aaronlj2000** [comment]
microk8s is deployed on the ubuntu VM on the macOS host machine.  I actually have four VMs, but for this example I am just using two to simplify the setup.  All of the VMs can communicate.  Do I need to make the hostnames resovable?

**Comment by Aaronlj2000** [comment]
Error still happening after adding hosts to /etc/hosts on both VMs

>> on microk8s-ctl
ubuntu@microk8s-ctl:~$ cat /etc/hosts
127.0.1.1 microk8s-ctl microk8s-ctl
127.0.0.1 localhost
192.168.64.9 microk8s-n1
192.168.64.8 microk8s-ctl

ubuntu@microk8s-ctl:~$ microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.64.8:25000/32131810acc72f9f1f271811ae0c2247/d9af3875a8bc

>> on microk8s-n1
ubuntu@microk8s-n1:~$ cat /etc/hosts
127.0.1.1 microk8s-n1 microk8s-n1
127.0.0.1 localhost
192.168.64.8 microk8s-ctl
192.168.64.9 microk8s-n1

ubuntu@microk8s-n1:~$ microk8s join 192.168.64.8:25000/32131810acc72f9f1f271811ae0c2247/d9af3875a8bc
Contacting cluster at 192.168.64.8
Connection failed. (500).

**Comment by alandtsang** [comment]
Same issue here.

I have two ubuntu 18.04 VMs on my macOS host, and network is bridge mode.
VM1, VM2 and host can ping each other.

After execute `microk8s join`,  I get `Connection failed. Invalid token (500).`

**Comment by alandtsang** [comment]
```
Jun 07 16:54:24 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 16:54:24 +0800] [1165] [CRITICAL] WORKER TIMEOUT (pid:1439)
Jun 07 16:54:24 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 16:54:24 +0800] [1439] [INFO] Worker exiting (pid: 1439)
Jun 07 16:54:24 ubuntu microk8s.daemon-cluster-agent[807]:  
Jun 07 16:54:24 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 16:54:24 +0800] [68066] [INFO] Booting worker with pid: 68066
Jun 07 17:00:03 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 17:00:03 +0800] [1165] [CRITICAL] WORKER TIMEOUT (pid:68066)
Jun 07 17:00:03 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 17:00:03 +0800] [68066] [INFO] Worker exiting (pid: 68066)
Jun 07 17:00:03 ubuntu microk8s.daemon-cluster-agent[807]: [2021-06-07 17:00:03 +0800] [69297] [INFO] Booting worker with pid: 69297
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]: Waiting for access to cluster. [2021-06-07 18:13:58,341] ERROR in app: Exception on /cluster/api/v2.0/join [POST]
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]: Traceback (most recent call last):
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     response = self.full_dispatch_request()
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     rv = self.handle_user_exception(e)
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     reraise(exc_type, exc_value, tb)
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     raise value
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     rv = self.dispatch_request()
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/scripts/cluster/agent.py", line 613, in join_node_dqlite
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     try_initialise_cni_autodetect_for_clustering(node_addr, apply_cni=True)
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/scripts/cluster/common/utils.py", line 241, in try_initialise_cni_autodetect_for_clustering
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     if cni_is_patched():
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:   File "/snap/microk8s/2210/scripts/cluster/common/utils.py", line 208, in cni_is_patched
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]:     with open(yaml) as f:
Jun 07 18:13:58 ubuntu microk8s.daemon-cluster-agent[807]: FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/2210/args/cni-network/cni.yaml'
```

when I use microk8s `1.18/stable` instead`1.21/stable`, `microk8s join` is OK.

**Comment by Aaronlj2000** [comment]
Hopefully having someone else with the issue will expedite the solution.


From: Alan ***@***.***>
Date: Monday, June 7, 2021 at 5:30 AM
To: ubuntu/microk8s ***@***.***>
Cc: Aaronlj2000 ***@***.***>, Mention ***@***.***>
Subject: Re: [ubuntu/microk8s] add node on macOS not working (#2190)

Same issue here.

I have two ubuntu 18.04 VMs on my macOS host, and network is bridge mode.
VM1, VM2 and host can ping each other.

After execute microk8s join, I get Connection failed. Invalid token (500).

**Comment by acierto** [comment]
I have this issue on mac.
I provides only 1 IP address, which is already occupied, what makes it impossible to join.
Not as it is described in documentation, which said about the list of options of IPs to join.

<img width="1169" alt="Screenshot 2022-09-08 at 17 51 26" src="https://user-images.githubusercontent.com/2265094/189168251-40e329f6-6d49-44f8-b04e-97ae1fa5a8e1.png">

**Comment by neoaggelos** [comment]
Hi @acierto 

The command you are running needs to run from a different VM. If still relevant, try the following:

```
multipass launch 20.04 --name second-node --cpus 4 --disk 20G
multipass shell second-node

# inside second-node
microk8s join 192.168.64.3:25000/XXXXXXXXXXXXXXXXX/YYYYYYYYYYYYYYYYYYY
```

**Comment by abunimeh** [comment]
`microk8s add-node` is returning an internal IP address. This IP address means nothing to another Mac sitting on the same network. The issue is that `microk8s add-node` does not listen on `0.0.0.0` or other external interfaces on macOS. It just listens in VM `192.168.64.8`
