### ISSUE TITLE
Microk8s node restart Service for unknown reasons

### ISSUE THREAD

**Issue by njleon007** [canonical/microk8s#2201]
Hello,

I use microk8s to set up my CI/CD cluster，but I face node service restart issue.

I don't know whether it's designed to restart when some situation happen.

I post two node inspection report.

Need your help to check the reason.

thanks

[inspection-report-20210425_064430.tar.gz](https://github.com/ubuntu/microk8s/files/6371766/inspection-report-20210425_064430.tar.gz)
[inspection-report-20210425_184930.tar.gz](https://github.com/ubuntu/microk8s/files/6371767/inspection-report-20210425_184930.tar.gz)

**Comment by balchua** [comment]
@njleon007 thanks for reporting the issue.  The 2 tarballs you posted are from a worker nodes.  I assume that when you say "node restart service", you are referring to the kubernetes apiserver.  Am i right?  Thanks.

**Comment by njleon007** [comment]
@balchua

Yes，tarball is inspected  from worker node. I get log from syslog, I find kubelet and containerd were stopped by systemd on worker nodes.

So，I think some resource lack or designed to restart kubelet/containerd to release resources. I got this:

**kubelet:**
kubelet.go:1322] Image garbage collection failed multiple times in a row: failed to garbage collect required amount of images. Wanted to free 268404460748 bytes, but freed 0 bytes
Stopping Service for snap application microk8s.daemon-kubelet...

**syslog:**
Apr 24 08:12:04 ubuntu21 systemd[1]: [/etc/systemd/system/snap-microk8s-2102.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:04 ubuntu21 systemd[1]: [/etc/systemd/system/snap-core-10958.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:04 ubuntu21 systemd[1]: [/etc/systemd/system/snap-core-10908.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-microk8s-2055.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: Started ACPI event daemon.
Apr 24 08:12:05 ubuntu21 systemd[1]: Reloading.

Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-microk8s-2102.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-core-10958.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-core-10908.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-microk8s-2055.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: [/etc/systemd/system/snap-microk8s-2140.mount:10] Unknown lvalue 'LazyUnmount' in section 'Mount'
Apr 24 08:12:05 ubuntu21 systemd[1]: Started ACPI event daemon.
Apr 24 08:12:05 ubuntu21 systemd[1]: Mounting Mount unit for microk8s, revision 2140...
Apr 24 08:12:05 ubuntu21 systemd[1]: Mounted Mount unit for microk8s, revision 2140.
Apr 24 08:12:06 ubuntu21 systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Apr 24 08:12:06 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-proxy.
Apr 24 08:12:06 ubuntu21 systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Apr 24 08:12:07 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
Apr 24 08:12:07 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-scheduler.
Apr 24 08:12:07 ubuntu21 systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
Apr 24 08:12:07 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelet.
Apr 24 08:12:08 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-etcd.
Apr 24 08:12:08 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver-kicker.
Apr 24 08:12:08 ubuntu21 systemd[1]: Stopping Service for snap application microk8s.daemon-cluster-agent...
Apr 24 08:12:20 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-cluster-agent.
Apr 24 08:12:20 ubuntu21 systemd[1]: Stopping Service for snap application microk8s.daemon-flanneld...
Apr 24 08:12:21 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-flanneld.
Apr 24 08:12:21 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
Apr 24 08:12:21 ubuntu21 systemd[1]: Stopped Service for snap application microk8s.daemon-controller-manager.

then every service start again. I attach my syslog, please help, thanks.

[syslog.2.zip](https://github.com/ubuntu/microk8s/files/6374863/syslog.2.zip)

**Comment by balchua** [comment]
I recall that this particular issue is a result of disk pressure.

```
kubelet.go:1322] Image garbage collection failed multiple times in a row: failed to garbage collect required amount of images. Wanted to free 268404460748 bytes, but freed 0 bytes
Stopping Service for snap application microk8s.daemon-kubelet...
```
Can you check if you have enough space on `/var`?
