### ISSUE TITLE
Microk8s potentially incompatible with glusterfs

### ISSUE THREAD

**Issue by khumps** [canonical/microk8s#2202]
I am unsure of the root cause but it appears that microk8s' dqlite and glusters network sockets step on each-others toes. 
For clarification, gluster is running as a separate process on nodes in the microk8s cluster. It is not a pod.
Occasionally, without warning I will lose all access to the microk8s control pane. The kubelite daemon always fails due to it failing to bind to port: https://pastebin.com/5RKxKdgy
Upon running `netstat` it appears the the glusterfs processes is stealing the dqlite socket. The only remedy I have found so far is to restart the offending node or sometimes the entire cluster.
[Inspect from a failed node](https://github.com/ubuntu/microk8s/files/6374085/inspection-report-20210419_040406.tar.gz)

```Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:24007           0.0.0.0:*               LISTEN      6297/glusterd
tcp        0      1 singularity004.fi:49147 singularity002.kh:24007 SYN_SENT    6297/glusterd
tcp        0      1 singularity004.fi:49148 singularity003.kh:24007 SYN_SENT    6297/glusterd
tcp        0      0 localhost:24007         localhost:49151         ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49130 ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49122 ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49123 ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49145 ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49150 ESTABLISHED 6297/glusterd
tcp        0      0 singularity004.fi:24007 singularity004.fi:49149 ESTABLISHED 6297/glusterd
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     473096   190298/glusterfs     @snap.microk8s.dqlite-4749344923551251393
unix  2      [ ACC ]     STREAM     LISTENING     61384    6297/glusterd        /var/run/glusterd.socket
unix  2      [ ]         DGRAM                    68083    6297/glusterd
unix  3      [ ]         STREAM     CONNECTED     68784    6297/glusterd
```

Logs from gluster:  https://pastebin.com/HfYTW8U9

**Comment by balchua** [comment]
Is there anything in glusterfs client logs that may give us some clue?

**Comment by khumps** [comment]
Not in any of the logs I have combed through. I will dump them all here once it happens again

**Comment by khumps** [comment]
@balchua the plot thickens. It appears to not be an issue specifically with gluster being on the node but with a pod in the cluster mouting the volume (using standard the kubernetes glusterfs mount options)

After stopping the glusterd process, all that was left was this one hung socket and pid.
```
kevin@singularity001:/var/snap/microk8s/current/var/lock$ sudo netstat -ap | grep -e dqlite -e glusterd -e Proto
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     244458   77899/glusterfs      @snap.microk8s.dqlite-8795547147414122509
```

looking into the pid I get:
```
kevin@singularity001:/var/snap/microk8s/current/var/lock$ ps aux | grep 77899
root       77899  0.0  0.0 685164 40980 ?        Ssl  01:25   0:01 /usr/sbin/glusterfs --log-level=ERROR --log-file=/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/glusterfs/config/transmission-749cf6b8b9-z2bfx-glusterfs.log --fuse-mountopts=auto_unmount --process-name fuse --volfile-server=192.168.2.31 --volfile-id=kub --fuse-mountopts=auto_unmount /var/snap/microk8s/common/var/lib/kubelet/pods/0674447f-8e44-421c-9bfa-b0297a4ef7f2/volumes/kubernetes.io~glusterfs/config
kevin     335867  0.0  0.0   6432   672 pts/0    S+   04:30   0:00 grep --color=auto 77899
```

I don't have a gluster server that is independent of my microk8s cluster to test on but it is possible that this issue exists in that case too which breaks a built in feature of k8s https://kubernetes.io/docs/concepts/storage/volumes/#glusterfs

**Comment by balchua** [comment]
Thanks @khumps for giving such info.
Is there a way to know which pod it is mounted to?  Curious to know if this happens only when the same pod is scheduled on MicroK8s.  From the looks of it, it doesn't seem like it is.

Another question, it happens as soon as the fuse mount happens that is a pod is scheduled? Or seemingly happen randomly even without doing anything to the cluster?
Sorry too many questions.

**Comment by khumps** [comment]
@balchua  I believe this time it was with a linuxserver/transmission pod, I can see if the next time it happens is on that pod as well. I have a pretty small set of pods and they all have worked so I don't think it happens directly on mount, I can try and check logs immediately after restarting the pod though

**Comment by khumps** [comment]
Update: The reboot process is no longer working. The nodes are entirely offline and 
[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/6401689/inspection-report.tar.gz) 
Multiple services are now failing to start after reboot:

kevin@singularity001:/var/snap/microk8s/current/var/kubernetes/backend$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
 FAIL:  Service snap.microk8s.daemon-proxy is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-proxy
 FAIL:  Service snap.microk8s.daemon-kubelet is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelet
 FAIL:  Service snap.microk8s.daemon-scheduler is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-scheduler
 FAIL:  Service snap.microk8s.daemon-controller-manager is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-controller-manager
 FAIL:  Service snap.microk8s.daemon-control-plane-kicker is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-control-plane-kicker

**Comment by balchua** [comment]
This is so strange, since you are in the `1.21` channel the apiserver and all must not be running.

I see these in the logs.
```
Apr 29 21:00:43 singularity001.khumps.dev microk8s.daemon-apiserver[1771]: + echo 'Service should not be running. This is a single binary snap'
```
This logs is printed when the `$SNAP_DATA/var/lock/lite lock` does not exist.
Here's the code.
https://github.com/ubuntu/microk8s/blob/932348f7b373f7d26d5f1dd06394aec55ee4eac4/microk8s-resources/wrappers/run-null-daemon#L8-L13

What could have happened to the `/var`?

**Comment by khumps** [comment]
@balchua ignore that message I deleted. I was doing some testing on my own and deleted that lock file and that was preventing the cluster from starting. We are back to just the gluster socket issue :)

**Comment by khumps** [comment]
@balchua, just got confirmation from another control pane failure. This time it was an entirely different pod using an entirely different image. For more context, this is what a fresh netstat looks like after reboot:
```
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     30418    890/glusterd         /var/run/glusterd.socket
unix  2      [ ACC ]     STREAM     LISTENING     21359    888/kubelite         @snap.microk8s.dqlite-8795547147414122509
unix  2      [ ]         DGRAM                    23274    890/glusterd
unix  3      [ ]         STREAM     CONNECTED     100083   888/kubelite         @snap.microk8s.dqlite-8795547147414122509
unix  3      [ ]         STREAM     CONNECTED     107482   888/kubelite         @snap.microk8s.dqlite-8795547147414122509
unix  3      [ ]         STREAM     CONNECTED     40266    890/glusterd
```
