### ISSUE TITLE
Server.crt files get deleted

### ISSUE THREAD

**Issue by maxlein** [canonical/microk8s#2216]
Yesterday K8 was working and today I can't reach the cluster anymore.  
After several restarts and hints from other threads like refreshing certs I have no clue what happened to the cluster.

I can't connect via dashboard or call any services.  

[inspection-report-20210429_081014.tar.gz](https://github.com/ubuntu/microk8s/files/6397164/inspection-report-20210429_081014.tar.gz)

**Comment by balchua** [comment]
I saw this in the logs.

```
Apr 29 08:10:02 maunakea microk8s.daemon-kubelite[82847]: I0429 08:10:02.544473   82847 server.go:199] Version: v1.21.0-3+121713cef81e03
Apr 29 08:10:03 maunakea microk8s.daemon-kubelite[82847]: Error: missing content for serving cert "serving-cert::/var/snap/microk8s/2128/certs/server.crt::/var/snap/microk8s/2128/certs/server.key"
```
Its a strange error.

**Comment by maxlein** [comment]
But how can this happen from one day to the other and how can I solve it? ;)

**Comment by balchua** [comment]
Does these files exist?
`/var/snap/microk8s/2128/certs/server.crt`
`/var/snap/microk8s/2128/certs/server.key`
If its missing then its weird.

**Comment by maxlein** [comment]
Yep, but crt is empty.

**Comment by balchua** [comment]
It could be caused by this error
```
Apr 28 17:38:33 maunakea microk8s.daemon-apiserver-kicker[1787338]: /snap/microk8s/2128/bin/sed: couldn't flush /var/snap/microk8s/2128/certs/sed96w4Qd: No space left on device
```

**Comment by maxlein** [comment]
Saw this error too, but when I checked disk, there were 8GB free.  
I solved it by copying the cert from /snap/microk8s/2094/certs.

**Comment by maxlein** [comment]
It's down again. This time certs folder looks different:  
`/var/snap/microk8s/2128/certs/csr.conf.template`  
`/var/snap/microk8s/2128/certs/csr-dqlite.conf.template`  
No certs anymore.  

[inspection-report-20210429_140422.tar.gz](https://github.com/ubuntu/microk8s/files/6399194/inspection-report-20210429_140422.tar.gz)

**Comment by balchua** [comment]
There's some strange logs that I don't understand.

```
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758465]: unable to load number from /var/snap/microk8s/2128/certs/ca.srl
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758465]: 139664888457024:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:../crypto/evp/p_lib.c:93:
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758465]: 139664888457024:error:0D066096:asn1 encoding routines:a2i_ASN1_INTEGER:short line:../crypto/asn1/f_int.c:140:
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758475]: Signature ok
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758475]: subject=CN = front-proxy-client
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[758475]: Getting CA Private Key
Apr 29 13:26:22 maunakea microk8s.daemon-apiserver-kicker[746587]: CSR change detected. Reconfiguring the kube-apiserver
Apr 29 13:50:45 maunakea microk8s.daemon-apiserver-kicker[804053]: chmod: cannot access '/var/snap/microk8s/2128/var/kubernetes/backend/.probe': No such file or directory
Apr 29 13:59:43 maunakea microk8s.daemon-apiserver-kicker[819702]: chmod: cannot access '/var/snap/microk8s/2128/var/kubernetes/backend/.probe': No such file or directory
```
So the apiservice kicker will try to detect network changes and when it does, it will recreate the certs.
I also noticed that when i look at the snap list, there is no channel associated with microk8s.
```
microk8s  v1.21.0    2128   -              canonical*    classic
snapd     2.49.2     11588  latest/stable  canonical*    snapd
```
I don't know if this is normal.

**Comment by maxlein** [comment]
If you say they were network changes, there weren't any.

Just a reboot, then I could connect again with the copied crt and after maybe half an hour, I couldn't connect anymore.

**Comment by balchua** [comment]
Can you add `--bind-address=0.0.0.0` to the file `/var/snap/microk8s/current/args/kube-apiserver`? I want to see if any of the stuffs inside the apiservice kicker is playing a role on this.
Thanks
