### ISSUE TITLE
OpenEBS doesn't work on Archlinux because of library version mismatch

### ISSUE THREAD

**Issue by mtb-xt** [canonical/microk8s#2218]
Hi everyone.

I'm encountering errors trying to use openebs and it's **jiva** storage class - 
pods that try to use the class are stuck in `initializing` indefinitely. Inspecting the logs on the node shows this:
```
Apr 29 22:19:39 thanatos microk8s.daemon-kubelite[680225]: I0429 22:19:39.267730  680225 operation_generator.go:575] MountVolume.WaitForAttach entering for volume "pvc-04297978-c7a4-4cb0-a978-65cbedb259ad" (UniqueName: "kubernetes.io/iscsi/10.152.183.112:3260:iqn.2016-09.com.openebs.jiva:pvc-04297978-c7a4-4cb0-a978-65cbedb259ad:0") pod "gitea-postgresql-0" (UID: "81bb6fa2-3998-4efb-8fb6-af84ba6b8812") DevicePath ""
Apr 29 22:19:39 thanatos microk8s.daemon-kubelite[680225]: E0429 22:19:39.269595  680225 iscsi_util.go:297] iscsi: could not read iface default error: iscsiadm: symbol lookup error: /snap/core18/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE
```
I'm using Archlinux on my machines, and `jiva` uses iscsi package to mount the volumes across the nodes. 
The version of **libpthread** inside the snap is libpthread-2.27.so, and in my host system its - libpthread-2.33.so

Is there any way around this?

[inspection-report-20210429_222735.tar.gz](https://github.com/ubuntu/microk8s/files/6397920/inspection-report-20210429_222735.tar.gz)

**Comment by balchua** [comment]
Its highly likely that this has something to do with the core18 base.  I think there's a fix to this but perhaps it is still in `1.21/edge` channel.

Here's the PR.  https://github.com/ubuntu/microk8s/issues/2181

Can you try `1.21/edge`?

**Comment by mtb-xt** [comment]
@balchua sorry, forgot to mention - I'm on `latest/edge` at the moment, otherwise microk8s doesn't want to work because of memory cgroups v2 enabled by default in archlinux.

So if I'm reading this correctly, I should already have this fix...
```
[root@thanatos hawara]# snap info microk8s
...
snap-id:      EaXqgt1lyCaxKaQCU349mlodBkDCXRcg
tracking:     latest/edge
refresh-date: today at 02:47 NZST
channels:
...
  latest/edge:      v1.21.0         2021-04-28 (2173) 191MB classic
...
installed:          v1.21.0                    (2173) 191MB classic
```

**Comment by balchua** [comment]
Yeah you should.

**Comment by mtb-xt** [comment]
@ktsakalozos sorry for direct mention, but I think this is also triggered by the move to **core18**

**Comment by mtb-xt** [comment]
Clarification - even if it's not an add-on installed by `microk8s`, it still won't work - anything that calls an external binary like `iscsiadm` or something else - will fail

**Comment by evaneaston** [comment]
@mtb-xt did you find a workaround?  All of my attempts to get replicated storage working on my arch-based microk8s cluster have failed because of this issue.

Since I don't know anything about how to customize a snap to use a different library than what the available channels offer (readonly overlay volumes), and I don't want to switch to ubuntu as the os,  I'm leaning toward rebuilding my cluster "the hard way" and have full control over dependencies.

**Comment by mtb-xt** [comment]
@evaneaston hey, I moved to using k3s -_- works much better on arch

**Comment by evaneaston** [comment]
Yeah.  Other having to configure the cluster nodes before starting them and removing traefik before setting up other 8ngress, it really easy to get k3s set up and running with openebs jiva volumes.
