### ISSUE TITLE
Exception on /cluster/api/v2.0/join (while joining a node)

### ISSUE THREAD

**Issue by aaron-trout** [canonical/microk8s#2233]
Hi, I'm seeing an issue when trying to join a second node to a cluster. The first node is an Intel NUC (Ubuntu 20.04.2 LTS) and has been running Microk8s for a while (since before the HA cluster stuff; I think probably 1.18 or maybe 1.19). Today I have upgraded the NUC from 1.20 to 1.21 (`sudo snap refresh microk8s --channel=1.21/stable`) and enabled HA mode (`microk8s enable ha-cluster`) after an initial join failure from my second node with a message about the cluster not being in HA mode.

The second node is a Raspberry Pi 4, and I get the following message when trying to join to the cluster with `sudo microk8s join 192.168.0.201:25000/<redacted>`:

```
Contacting cluster at 192.168.0.201
Connection failed. (500).
```

If I have a look on the NUC (master node) in the cluster-agent logs with `sudo journalctl -fu snap.microk8s.daemon-cluster-agent.service` while this is happening, I see the following output:

```
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]: Waiting for access to cluster. .. .. .. .. .. .. .. .. .. .. [2021-05-04 13:44:37,912] ERROR in app: Exception on /cluster/api/v2.0/join [POST]
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]: Traceback (most recent call last):
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     response = self.full_dispatch_request()
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     rv = self.handle_user_exception(e)
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     reraise(exc_type, exc_value, tb)
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     raise value
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     rv = self.dispatch_request()
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     return self.view_functions[rule.endpoint](**req.view_args)
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/scripts/cluster/agent.py", line 594, in join_node_dqlite
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     voters, non_voters = get_dqlite_nodes()
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:   File "/snap/microk8s/2128/scripts/cluster/agent.py", line 487, in get_dqlite_nodes
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]:     raise Exception("Could not get cluster info")
May 04 13:44:37 nuc microk8s.daemon-cluster-agent[1502]: Exception: Could not get cluster info
```

**Comment by balchua** [comment]
Hi do you happen to have a firewall blocking the port `19001`?
The command below can be executed on the main node to get the dqlite info.

```
/snap/microk8s/current/bin/dqlite -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -f json k8s ".cluster 192.168.0.201:19001"
```

**Comment by aaron-trout** [comment]
Sorry for the slow reply @balchua! I was away from home for a while and just started a new job so been quite busy!

Port 19001 does seem unreachable from the node I am trying to add to the cluster, however I don't have any special firewall config or anything, should just be whatever IPTables foo that Microk8s is doing (This is pretty much a plain Ubuntu install + Microk8s).

```bash
$ curl --connect-timeout 5 -v --insecure https://192.168.0.201:19001
*   Trying 192.168.0.201:19001...
* TCP_NODELAY set
* connect to 192.168.0.201 port 19001 failed: Connection refused
* Failed to connect to 192.168.0.201 port 19001: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.0.201 port 19001: Connection refused
```

I also tried the command you posted above, but it just seems to hang forever (tried with `sudo` as well just in case).

**Comment by aaron-trout** [comment]
Actually, furthermore nothing seems to be listing on 19001;  `sudo netstat -tunlp | grep 19001` returns nothing.

**Comment by aaron-trout** [comment]
Ok so I managed to get this working, however the process is not totally idea. Basically I think the process of upgrading the cluster from 1.18 --> 1.19 --> 1.20 --> 1.21 then enabling HA with `microk8s enable ha-cluster` something went wrong. I don't know what though...

What I did notice however is that in my `microk8s status` the datastore master node was "none" even though the ha addon was enabled:

```
microk8s is running
high-availability: no
  datastore master nodes: none
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
```

I spun up a fresh node in a VM and noticed that the fresh install on there showed `datastore master nodes: 127.0.0.1:19001` so I figured that was where my problem lied. I tried to reset the cluster with `microk8s reset --destroy-storage` but this didn't work. A full uninstall / reinstall of the microk8s snap did fix it however! Now I have joined the second node with no issues.

I'll leave it up to you guys to decide if you want to leave this ticket open or not / test the upgrade flow more, but feel free to close it if you like. I don't need any more help.

Thanks,
Aaron

**Comment by ericflo** [comment]
For what it's worth, I just ran into the same issue. dqlite appears to start fine on the worker nodes, but on the leader it won't start, with the same exception above "Could not get cluster info." I also upgraded from an existing non-HA cluster.
