### ISSUE TITLE
microk8s.juju is out of date

### ISSUE THREAD

**Issue by wallyworld** [canonical/microk8s#2234]
```
$ microk8s.juju version
2.8.6-hirsute-amd64
```

Can we update to juju 2.9.0?
We need a way to keep this up to date since even 2.8 is now 2.8.10

**Comment by joedborg** [comment]
Hey @wallyworld.  Yeah, we're looking, this cycle, at improving the way we do add ons in order to keep things like this up to date, without needing to cut a new release.

In the mean time, I'll look at bumping this and getting it on edge.

**Comment by joedborg** [comment]
https://github.com/ubuntu/microk8s/pull/2235/files

**Comment by ktsakalozos** [comment]
The only user of microk8s.juju at the moment is the kubeflow addon. The kubeflow team is updating juju based on the bundle they ship. @knkski @DomFleischmann please have a look at the PR. Thanks.

**Comment by wallyworld** [comment]
FWIW, we had a user run microk8s.juju because for whatever reason, their standalone Juju snap install had issues and microk8s.juju worked for them to be able to bootstrap a k8s model on microk8s.
