### ISSUE TITLE
Disabling openEBS from other than master node fails

### ISSUE THREAD

**Issue by jaxzon** [canonical/microk8s#2238]
I created three node cluster and enabled openEBS in masternode. Then i decided not to use it and tried to disable it on nodenr2. 

Here's the output:

`
user@nodenr2:~$ microk8s disable openEBS
Disabling OpenEBS
Information with regards to OpenEBS uninstallation (https://docs.openebs.io/docs/next/uninstall.html).
Have you deleted all the pods and PersistentVolumeClaims using OpenEBS PVC? (Y/N): Y
Deleting OpenEBS SPC in case of cStor
No resources found
Deleting OpenEBS BlockDevicePool
No resources found
Deleting OpenEBS cStor custom resources
No resources found
No resources found
/snap/microk8s/2128/scripts/wrappers/common/../../../actions/disable.openebs.sh: line 25: kubectl: command not found
Deleting OpenEBS block devices
No resources found
/snap/microk8s/2128/scripts/wrappers/common/../../../actions/disable.openebs.sh: line 35: /var/snap/microk8s/2128/bin/helm3: No such file or directory
`

**openEBS addon was not disabled when i checked microk8s status**. 

So i tried to disable it in the master node:
`user@masternode:/srv/project$ microk8s disable openebs
Disabling OpenEBS
Information with regards to OpenEBS uninstallation (https://docs.openebs.io/docs/next/uninstall.html).
Have you deleted all the pods and PersistentVolumeClaims using OpenEBS PVC? (Y/N): Y
Deleting OpenEBS SPC in case of cStor
No resources found
Deleting OpenEBS BlockDevicePool
No resources found
Deleting OpenEBS cStor custom resources
No resources found
No resources found
/snap/microk8s/2128/scripts/wrappers/common/../../../actions/disable.openebs.sh: line 25: kubectl: command not found
Deleting OpenEBS block devices
No resources found
release "openebs" uninstalled
Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "openebs-validation-webhook-cfg" not found
customresourcedefinition.apiextensions.k8s.io "castemplates.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorpools.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorpoolinstances.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorvolumeclaims.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorvolumereplicas.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorvolumepolicies.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorvolumes.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "runtasks.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "storagepoolclaims.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "storagepools.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "volumesnapshotdatas.volumesnapshot.external-storage.k8s.io" deleted
customresourcedefinition.apiextensions.k8s.io "volumesnapshots.volumesnapshot.external-storage.k8s.io" deleted
customresourcedefinition.apiextensions.k8s.io "blockdevices.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "blockdeviceclaims.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorbackups.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorrestores.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "cstorcompletedbackups.openebs.io" deleted
customresourcedefinition.apiextensions.k8s.io "upgradetasks.openebs.io" deleted
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorpoolclusters.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorpoolinstances.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorvolumeattachments.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorvolumeconfigs.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorvolumepolicies.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorvolumereplicas.cstor.openebs.io" not found
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "cstorvolumes.cstor.openebs.io" not found
namespace "openebs" deleted
OpenEBS disabled
Manually clean up the directory /var/snap/microk8s/common/var/openebs/
`
Seems like disabling was successful because addon is now disabled.

**Expectations**: disabling addons from all nodes works the same way.

Not putting microk8s inspect tarball here because of security reasons.
Details about environment:
OS:
"Ubuntu 20.04.2 LTS (Focal Fossa)"
Microk8s v1.21.0-3+121713cef81e03 on all three nodes. Installed with snap.

**Comment by balchua** [comment]
Currently this is one of the limitations of the enabling/disabling addons whereby it downloads the `helm` client and use it to install the charts.

Unfortunately disabling must be done on the same node where it was enabled.

**Comment by ktsakalozos** [comment]
@balchua, do you think we should detect the missing helm and fail gracefully, ie instruct the user to disable the addon on the node it was enabled from?

**Comment by balchua** [comment]
Yes thats something we can do.
