### ISSUE TITLE
Microk8s installer on windows 10 failing

### ISSUE THREAD

**Issue by josepholaide** [canonical/microk8s#2239]
After installing the microk8s installer on my windows.
I tried to configure it using --cpu 2, --mem 5G and --storage 60gb  but it returns:

`launch failed: The following errors occurred:                                   
microk8s-vm: timed out waiting for response
`

I also tried using multipass with hyper V enable but I got the same time out error.

OS: Windows 10
RAM: 8GB
ROM: 500GB
CORES: 4

**Comment by Josepholaidepetro** [comment]
With multipass, I found out the instance is created but the status shows "stopped".

**Comment by charlesa101** [comment]
+1 on this

**Comment by RFMVasconcelos** [comment]
@Josepholaidepetro you seem to be using 5G or 8G of RAM which is below the minimum to run the full Kubeflow bundle - The min recommended is 12G. You can try to `microk8s enable kubeflow --bundle=lite` or `microk8s enable kubeflow --bundle=edge` for lighter deployments. 

You can also start with something lighter and `microk8s juju add X` if you need an extra application in your bundle.

**Comment by RFMVasconcelos** [comment]
Alternatively, you can `juju bootstrap microk8s` and use `juju deploy kubeflow-lite` or `juju deploy kubeflow-edge` to deploy different bundles into your cluster.

More docs [here](https://charmed-kubeflow.io/docs/install).

**Comment by Josepholaidepetro** [comment]
@RFMVasconcelos thanks for your response.

Suggestion noted.

**Comment by ktsakalozos** [comment]
> With multipass, I found out the instance is created but the status shows "stopped".

@Josepholaidepetro you are not able to start any VM with multipass? Will a low spec VM created with `multipass launch` start?

**Comment by Josepholaidepetro** [comment]
@ktsakalozos yes, I wasn't able to create microk8s vm-instance with it./
When I tried `multipass list`, I found out the instance stopped without creating.
