### ISSUE TITLE
pods not listed entirely

### ISSUE THREAD

**Issue by itsyoshio** [canonical/microk8s#2240]
my HA-Enabled Cluster on 1.20/stable stops generating Pods for Deployments.

It's entering some kind of "no changes" State, where it
- doesn't want to delete Resources (they stay on terminating).
- won't try to spawn new Pods (they don't even appear in `kubectl get pods`, not even as Status unknown)

[inspection-report-20210505_200433.tar.gz](https://github.com/ubuntu/microk8s/files/6429587/inspection-report-20210505_200433.tar.gz)

It's bare Metal on Ubuntu 20.04.
3 Nodes with basically identical HW and Gigabit each.
Addons : dns, ha-cluster, helm (2), metallb, metrics-server, rbac

NFS-Client StorageClass deployed to the Cluster.
The NFS Master (Kernel Server) is also the first node [NODE1] / dev.

some things i've noticed / tried

1. daemon-scheduler seems to crash? every 30-120s
    <details>
      <summary>kubectl get events</summary>

      ```journalctl
      $ sudo systemctl status snap.microk8s.daemon-scheduler
      serving.go:331] Generated self-signed cert in-memory
      authentication.go:307] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
      authentication.go:331] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
      authorization.go:176] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
      authorization.go:47] Authorization is disabled
      authentication.go:40] Authentication is disabled
      deprecated_insecure_serving.go:51] Serving healthz insecurely on 127.0.0.1:10251
      secure_serving.go:197] Serving securely on [::]:10259
      tlsconfig.go:240] Starting DynamicServingCertificateController
      leaderelection.go:243] attempting to acquire leader lease kube-system/kube-scheduler...
      leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "kube-scheduler": the object has been modified; please apply your changes to the latest version and try again
      leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler?timeout=10s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
      leaderelection.go:253] successfully acquired lease kube-system/kube-scheduler
      leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler?timeout=10s": context deadline exceeded
      leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
      server.go:205] leaderelection lost
      > goroutine 1 [running]:
      ```

    </details>

    > It then goes on to write about 1500 Lines of what seems like a Stack Trace after loosing the Election (goroutine 1 [running]:)

2. Leader Election is happening very often.
    <details>
      <summary>systemctl status snap.microk8s.daemon-scheduler</summary>

      ```journalctl
        $ kubectl get events -n kube-system
        2m54s       Normal    LeaderElection           lease/kube-scheduler                             [NODE2]_629a6099-8138-461f-b1fe-22c7cfbc4f83 became leader
        2m22s       Normal    LeaderElection           lease/kube-scheduler                             [NODE1]_fc151b2b-7ce4-4c31-8ffa-eb8fd2daf07c became leader
        2m4s        Normal    LeaderElection           lease/kube-controller-manager                    [NODE2]_99375bb1-ae96-4416-a148-9f3a45420c44 became leader
        107s        Normal    LeaderElection           lease/kube-scheduler                             [NODE1]_dd62e010-4b7b-4a33-b8f1-27a37c803794 became leader
        92s         Normal    LeaderElection           lease/kube-controller-manager                    [NODE1]_651dfa7f-91e1-44a3-a392-e7fb16429bba became leader
        23s         Normal    LeaderElection           lease/kube-controller-manager                    [NODE1]_6ccbdd52-06a9-4f34-a33c-adacc877c761 became leader
        15s         Normal    LeaderElection           lease/kube-scheduler                             [NODE3]_09f79bd2-6706-4657-b9e3-a07fc6c37974 became leader
      ```
    </details>

3. Sporadic issues with API Server
    Sometimes Calico can't seem to interact with the ClusterIP
    > Warning  Unhealthy  pod/calico-kube-controllers-847c8c99d-njsbf Readiness probe failed: Error reaching apiserver: <nil> with http status code: 500

I was able to stop [NODE1] and start it again, and the basic Pods came up again. (kube-system)
[NODE1] also runs an Ingress, that seems to be working for the Workload that is on [NODE2] & [NODE3]
[NODE1] is running a Minio (not the Operator) where the Webinterface SHOULD be accessible via the same Ingress, but isn't.

Seems vaguely related to what's described [here](https://github.com/ubuntu/microk8s/issues/1840#issuecomment-748778137)

I had the same error pattern 2 days ago, couldn't figure out what it was and NUKED the Cluster, now it's there again.

[inspection-report-20210505_200433.tar.gz](https://github.com/ubuntu/microk8s/files/6429587/inspection-report-20210505_200433.tar.gz)

Would really appreciate some help.
Thanks!

**Comment by balchua** [comment]
Both the kube-controller and scheduler seems to be crash looping.

I also see this in the logs
```
May 05 19:58:48 dev.limegreen.it microk8s.daemon-apiserver[708193]: I0505 19:58:48.712297  708193 trace.go:205] Trace[1546571117]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager,user-agent:kube-controller-manager/v1.20.6 (linux/amd64) kubernetes/e4abae4/leader-election,client:127.0.0.1 (05-May-2021 19:58:39.680) (total time: 9031ms):
```

Care to try the steps shown here?
https://github.com/ubuntu/microk8s/issues/2205#issuecomment-827208050

**Comment by balchua** [comment]
Could be similar to this. 
https://github.com/ubuntu/microk8s/issues/2205

**Comment by balchua** [comment]
Hi @itsyoshio did it fix your issue? Thanks.

**Comment by itsyoshio** [comment]
I did nuke the Cluster to redo it after writing the Ticket.
I'm not yet sure. Last time it happend with Node Age around 44h.

My current Cluster is now at 34h. I'm assuming the same problem will occur again.
I'm already getting lots of 

`Error: rpc error: code = Unknown desc = exec (try: 500): database is locked` from Dqlite which might be somehow related?

Anyway, once the Issue is back, or if it doesn't ever come back in a short means while i be sure to come back here.

**Comment by balchua** [comment]
Hi @itsyoshio thanks for coming back.  The error `database is locked` is strange.

Do you mind taking an inspect tarball and upload it here?  Thanks.

**Comment by itsyoshio** [comment]
I can't really reproduce any of this right now.
The Issue doesn't seem to persist anymore. (Neither Pod Scheduling, nor database is locked)

It appears https://github.com/ubuntu/microk8s/issues/2205#issuecomment-827208050 is the best solution for the Issue at hand and i will be sure to try it (and report back here) if i ever encounter it again.

Since i had the Pod scheduling issue twice before reporting here, i had nuked my cluster and reinstalled it on 1.21.
It seems already fixed in that version?

As for the Database is Locked issue, i can't reproduce it currently. It seems to happen on large helm installs (e.g. Sentry) with some Gitlab Runners trying to helm install some software in parallel or rapid succession.

I will be sure to get back here, if i get any of these Issues again.

until then, thank you so much for your help @balchua !

**Comment by itsyoshio** [comment]
So `database is locked` came up again trying to install Sentry.
Although i feel that it happens with every install that apply's more than a few .yamls

```bash
$ helm install sentry -n sentry --wait sentry/sentry
[…]
W0516 00:18:48.147396 3095844 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0516 00:18:48.915199 3095844 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: rpc error: code = Unknown desc = exec (try: 500): database is locked
```

I got the issue a few times trying to delete Sentry via Helm (then deleting the Namespace and trying again).
I also once got this issue 
```bash
Error: Get "https://127.0.0.1:16443/api/v1/namespaces/sentry/services/sentry-rabbitmq": dial tcp 127.0.0.1:16443: connect: connection refused
```

and on my last try i got this
```bash
Error: rpc error: code = Unknown desc = query (try: 0): call query-sql (budget 59.95984354s): receive: header: EOF
```

Here is my Tarball.
[inspection-report-20210516_002606.tar.gz](https://github.com/ubuntu/microk8s/files/6488361/inspection-report-20210516_002606.tar.gz)

Thanks for the Help!

PS : I did not apply the fix for leaderelection in https://github.com/ubuntu/microk8s/issues/2205#issuecomment-827208050 because i'm waiting for it to happen again so i can investigate further.

**Comment by balchua** [comment]
hi @itsyoshio  thank you for reporting this.

@ktsakalozos i see this `database is locked` error several times in the logs.

```
May 14 10:14:02 dev.limegreen.it microk8s.daemon-kubelite[3189014]: time="2021-05-14T10:14:02+02:00" level=error msg="failed to delete revision 2096476: exec (try: 500): database is locked"
...
May 14 10:19:04 dev.limegreen.it microk8s.daemon-kubelite[3189014]: time="2021-05-14T10:19:04+02:00" level=error msg="failed to delete revision 2097438: exec (try: 500): database is locked"
...
May 14 10:24:00 dev.limegreen.it microk8s.daemon-kubelite[3189014]: time="2021-05-14T10:24:00+02:00" level=error msg="failed to record compact revision: exec (try: 500): database is locked"
...
May 14 10:29:01 dev.limegreen.it microk8s.daemon-kubelite[3189014]: time="2021-05-14T10:29:01+02:00" level=error msg="failed to record compact revision: exec (try: 500): database is locked"
...
```
The retry logic is here [1].  Looking at the workload of the cluster, it doesn't present something insanely loaded.  
Do you think it is worth while to have the same retry jitter as what lxd is currently setup to do [2]?

[1] https://github.com/canonical/kine/blob/2be85732177d1d17a4ffbdc6bbcf536a1d5a912e/pkg/drivers/generic/generic.go#L264
[2] https://github.com/lxc/lxd/blob/2cca15907320426a881f1030fc7f60b859ec936b/lxd/db/query/retry.go#L41

**Comment by itsyoshio** [comment]
I'm getting `database is locked` more frequently in Gitlab Runners if there are concurrent Jobs.

**Comment by balchua** [comment]
Does the gitlab runners deploy the applications?

**Comment by itsyoshio** [comment]
Sometimes.
In the case of sentry half of the yamls were applied,
( sometimes more, sometimes less) so the application was partially deployed.

I have 5 or 6 yamls that get applied and half of them are usually unchanged.

So if 50% gets applied it might or might not work.

**Comment by itsyoshio** [comment]
i'll go ahead and close this, since it's stale.\
for anyone seeing `database is locked` in the future : you might have overloaded you physical hardware for this to happen.
