### ISSUE TITLE
`microk8s enable helm3` doesn't enable anything

### ISSUE THREAD

**Issue by 205g0** [canonical/microk8s#2264]
Pretty much the title, after that command there's still no `microk8s helm` ,  `microk8s helm3` , `helm`, nor a `helm3` command available. Do I need still to install helm the traditional way?

**Comment by balchua** [comment]
If you run `microk8s helm3 version` what does the console show?

**Comment by jerryu** [comment]
The following sequence seems to work fine for me, on Ubuntu 20.04.2 LTS.
Could you please share specifics of your setup as well as output from your attempts, so people can help replicate or troubleshoot together with you?

1. sudo snap install microk8s --classic
2. sudo usermod -a -G microk8s me
3. newgrp - microk8s
4. microk8s start
5. export LC_ALL=C.UTF-8
6. export LANG=C.UTF-8
7. microk8s enable helm3
8. microk8s helm3 version

Below are output from step 7 & 8. Note that (p3env) is a typical python3 venv.
step 5 & 6 are prompted by 'enable helm3' command itself.
```
(p3env) /home/me$ microk8s enable helm3
Enabling Helm 3
Fetching helm version v3.0.2.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.5M  100 11.5M    0     0  17.8M      0 --:--:-- --:--:-- --:--:-- 17.8M
Helm 3 is enabled
(p3env) /home/me$ microk8s helm3 version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
(p3env) /home/me$ go version
go version go1.13.8 linux/amd64
(p3env) /home/me$ python --version
Python 3.8.5
```
