### ISSUE TITLE
Question: Setting Kernel Parameters When Using LXD

### ISSUE THREAD

**Issue by sstubbs** [canonical/microk8s#2266]
Hi,

I know this is a question involving quite a few different projects and I am sorry for asking it here but I'm trying to work out the best way to to do this. Some of the projects I'm using require prerequisites such as https://docs.pingcap.com/tidb-in-kubernetes/dev/prerequisites and https://docs.yugabyte.com/latest/deploy/manual-deployment/system-config/#ulimits but are more for kubeadm installs. Until now I have only adjusted ulimits in `/var/snap/microk8s/current/args/containerd-env` and I have not had any problems.

I am running microk8s in LXD and just want to double check.

1. should swap be disabled and if so must it be disabled on the server or within the lxd container with: 
```
swapoff -a
sed -i 's/^\(.*swap.*\)$/#\1/' /etc/fstab
```
or does microk8s disable this itself automatically? 

2. `systemctl enable irqbalance` should this be enabled on the host or within the lxd container?
3. `cpupower frequency-set --governor performance` should this be enabled on the host or within the lxd container?
4. Setting kernel parameters like the following:
```
modprobe br_netfilter

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
net.core.somaxconn = 32768
vm.swappiness = 0
net.ipv4.tcp_syncookies = 0
net.ipv4.ip_forward = 1
fs.file-max = 1000000
fs.inotify.max_user_watches = 1048576
fs.inotify.max_user_instances = 1024
net.ipv4.conf.all.rp_filter = 1
net.ipv4.neigh.default.gc_thresh1 = 80000
net.ipv4.neigh.default.gc_thresh2 = 90000
net.ipv4.neigh.default.gc_thresh3 = 100000
EOF

sysctl --system
```
should these be added to /var/snap/microk8s/current/args/containerd-env

**Comment by ktsakalozos** [comment]
Hi @sstubbs 



> 1. should swap be disabled and if so must it be disabled on the server or within the lxd container with:

Yes, swap should be disabled because it interferes with the k8s pod scheduling. I would disable swap in both host and lxc container. 

> 2. `systemctl enable irqbalance` should this be enabled on the host or within the lxd container?

I would expect this to be enabled on the host. You may want to ask over at the lxc if enabling in the container has the same effect. 

> 3. `cpupower frequency-set --governor performance` should this be enabled on the host or within the lxd container?

Same as above. Changing this on host makes more sense to me.

> 4. Setting kernel parameters like the following:

I would create a script run during boot and not place these into containerd-env. The containerd-env is applied when the containerd of MicroK8s starts. Some of the configuration options you have here seem system wide.

**Comment by balchua** [comment]
@sstubbs i use cloud-init which lxd happens to support. https://cloudinit.readthedocs.io/en/latest/index.html
I also use some bit of terraform to bootstrap MicroK8s on lxd.  If you're interested https://github.com/balchua/terraform-lxd-microk8s
Its not perfect, but it is so far serving me well.

**Comment by sstubbs** [comment]
Thank you both very much for the great information. This is very helpful.
