### ISSUE TITLE
I am unable to get nodes to joing microk8s cluster on raspberry pi 4

### ISSUE THREAD

**Issue by eddiechristian** [canonical/microk8s#2273]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

All rasps
Ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz   installed as image

root@ubuntu:/home/ubuntu# cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: d03114
Serial		: 1000000060b14ab3
Model		: Raspberry Pi 4 Model B Rev 1.4
root@ubuntu:/home/ubuntu#

master=============
root@ubuntu:/home/ubuntu# microk8s.kubectl get all --all-namespaces
NAMESPACE     NAME                                          READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-86f78bb79c-l5snv                  1/1     Running   1          2m16s
kube-system   pod/calico-kube-controllers-847c8c99d-vwv98   1/1     Running   0          9m55s
kube-system   pod/calico-node-6v54d                         1/1     Running   0          9m55s
kube-system   pod/hostpath-provisioner-976f6d665-j26m9      1/1     Running   0          96s
kube-system   pod/metrics-server-7b7db5984b-7jdxd           1/1     Running   0          90s
ingress       pod/nginx-ingress-microk8s-controller-jbzxh   1/1     Running   0          107s

NAMESPACE     NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes       ClusterIP   10.152.183.1    <none>        443/TCP                  10m
kube-system   service/kube-dns         ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   2m16s
kube-system   service/metrics-server   ClusterIP   10.152.183.7    <none>        443/TCP                  90s

NAMESPACE     NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node                         1         1         1       1            1           kubernetes.io/os=linux   9m59s
ingress       daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>                   117s

NAMESPACE     NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                   1/1     1            1           2m16s
kube-system   deployment.apps/calico-kube-controllers   1/1     1            1           9m59s
kube-system   deployment.apps/hostpath-provisioner      1/1     1            1           98s
kube-system   deployment.apps/metrics-server            1/1     1            1           90s

NAMESPACE     NAME                                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-86f78bb79c                  1         1         1       2m16s
kube-system   replicaset.apps/calico-kube-controllers-847c8c99d   1         1         1       9m55s
kube-system   replicaset.apps/hostpath-provisioner-976f6d665      1         1         1       98s
kube-system   replicaset.apps/metrics-server-7b7db5984b           1         1         1       90s
root@ubuntu:/home/ubuntu# microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.1.222:25000/d17ab5558429f412843c2e5ccd2dd9a4

If the node you are adding is not reachable through the default interface you can use one of the following:
 microk8s join 192.168.1.222:25000/d17ab5558429f412843c2e5ccd2dd9a4
 microk8s join 172.17.0.1:25000/d17ab5558429f412843c2e5ccd2dd9a4
root@ubuntu:/home/ubuntu#

Worker ==================
ubuntu@ubuntu:~$ sudo microk8s join 192.168.1.222:25000/d17ab5558429f412843c2e5ccd2dd9a4
Contacting cluster at 192.168.1.222
Traceback (most recent call last):
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 900, in join_dqlite
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 818, in update_dqlite
    with open("{}/info.yaml".format(cluster_backup_dir)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/2157/var/kubernetes/backend.backup/info.yaml'
ubuntu@ubuntu:~$

on this try i ran microk8s start on worker(i dont think this needs to be done, though)
[inspection-report-20210519_003531.tar.gz](https://github.com/ubuntu/microk8s/files/6505124/inspection-report-20210519_003531.tar.gz)

ubuntu@ubuntu:~$ sudo microk8s join 172.17.0.1:25000/d17ab5558429f412843c2e5ccd2dd9a4
Contacting cluster at 172.17.0.1
Failed to join cluster. Error code 500.
ubuntu@ubuntu:~$

[inspection-report-20210519_003531.tar.gz](https://github.com/ubuntu/microk8s/files/6505129/inspection-report-20210519_003531.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @eddiechristian 

In the first attempt that failed with `FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/2157/var/kubernetes/backend.backup/info.yaml'` the MicroK8s node probably did not start correctly. You would better do a `microk8s status --wait-ready`.

On the second attempt you used the IP 172.17.0.1, why? All rpi are on the same network right? Which network is this? Is it 172.17.0.X or 192.168.1.X?

Also please set the different hostname to each node. You do not want to get into the unpleasant situation where ubuntu is resolved to a different IP based on the node you are on.

**Comment by eddiechristian** [comment]
also  , do i need to do a `microk8s start` on each node?

**Comment by evilnick** [comment]
>also , do i need to do a microk8s start on each node?
MicroK8s needs to be running on each node, but its state should be persistent - i.e if you left it started, it should start again if you reboot etc

**Comment by eddiechristian** [comment]
i tried wait-ready
`ubuntu@ubuntu:~$ microk8s status --wait-ready
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
  disabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
ubuntu@ubuntu:~$ microk8s join 192.168.1.222:25000/8d999fd16c06c51144a8c80804d1c4d9
Contacting cluster at 192.168.1.222
Waiting for this node to finish joining the cluster. ..  
ubuntu@ubuntu:~$ k get no
k: command not found
ubuntu@ubuntu:~$ microk8s kubectl get no
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
ubuntu@ubuntu:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
ubuntu@ubuntu:~$
`
master hung after worker trys to join

`ubuntu@ubuntu:~$ sudo microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.1.222:25000/8d999fd16c06c51144a8c80804d1c4d9

If the node you are adding is not reachable through the default interface you can use one of the following:
 microk8s join 192.168.1.222:25000/8d999fd16c06c51144a8c80804d1c4d9
 microk8s join 172.17.0.1:25000/8d999fd16c06c51144a8c80804d1c4d9
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ k get no
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get nodes)
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ 
ubuntu@ubuntu:~$ k get no
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get nodes)
ubuntu@ubuntu:~$ sudo microk8s kubectl get no
^C
ubuntu@ubuntu:~$ ls /var/snap/
core/     core18/   lxd/      microk8s/ snapd/    
ubuntu@ubuntu:~$ ls /var/snap/microk8s/
2157/    common/  current/ 
ubuntu@ubuntu:~$ ls /var/snap/microk8s/2157/
.kube/                                    certs/                                    inspection-report-20210519_003531.tar.gz  opt/                                      
args/                                     credentials/                              juju/                                     tmp/                                      
bin/                                      inspection-report/                        juju-home/                                var/                                      
ubuntu@ubuntu:~$ ls /var/snap/microk8s/2157/credentials/
callback-token.txt         cluster-tokens.txt         controller.config          kubelet.config             scheduler.config           
client.config              cluster-tokens.txt.backup  known_tokens.csv           proxy.config               
ubuntu@ubuntu:~$ ls /var/snap/microk8s/2157/credentials/client.config 
/var/snap/microk8s/2157/credentials/client.config
ubuntu@ubuntu:~$ cat  /var/snap/microk8s/2157/credentials/client.config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUx5Rmx0NVA5dW5mTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1UQTFNVGd5TXpRM016TmFGdzB6TVRBMU1UWXlNelEzTXpOYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNaVNmRk9xMkhRMDFteUdwekxOWGxZb29FcG1Xd2h4ZWVuMUlnUHhrWjVlcHRhREwvM0sKMlVtVG5CSnQvSHpFdUszOWw4emloUHU2dGJnb0RrbEtVTTIwbGRvZ0tiR2piaFFqZGx6RHB5Y2pvZ1F6d3U5ZQpRdGVXOVR5Skh0dnhPbWF4cm1acXN3OVNTRUhaUnMrV044RnRPZHdWSUsxNm1tMHoyVHdzcFdBTnl4U1g3OFNOCit6aUgxY3NTQnFUekMrSk5IcEtacUlkVkx0QXBWWGhrRHgrOFZocmc5ekR1ZmI4MlNlS1BaR3Flbmh6MGgyZ0oKOVZQNWxRbFlBNXVtNVk3bEtFTmRRd0I0WFdoR3RVNHpWRTYvQzd1aSthS3lRRnlJZkRzUFdWVXYyTFlKQzVscAp3S3l1dXduRDFNUnRyREQ4TE9hUnBYVVJWZ2Jod3BCUk9mVUNBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGRDVXCm5VdVFUbm9mR0N2UThOU0kwMnMwRlErSU1COEdBMVVkSXdRWU1CYUFGRDVXblV1UVRub2ZHQ3ZROE5TSTAyczAKRlErSU1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdEWWY5TmpzUzB6K0p4SQpwQXRVRFBrdDllQjV2cEtKYzY2cjUvcDM0VTM3K0FtVjVqTThhQ29YQmM2TzJpTHo1UGtzbzlSb1NocHp3UUc2CjJaeUk2bEJ4bkxqWTYvS2Nta09qUkZSVUsvM0lnNitqZElUenF1di80OUVVeUVqZGk5WlU4R2l0RW1uZGx6cUoKSHIxOFdyS1BYTEF2MzEvZkM4SzZrc2pYVDR6TytxbHJiSTEvY3lsSHN3TVFNdG1JaDg5WVA4Y1J3bGV6ZlRnVwpBa1lOcFc1c0lRTGZXYWJhaDY5YlJGNHUyWTY0NE8ycDRZdXJvTHhDcHJJZ1JIblI2Z2hJZTYyUE5rbHJnUXBICnJFU2RNZkJpQml6aTFvZ1B1RW5zcGNTbkRMZStaZExFMGpudGdsNmNSQ0JhZG00MG51NGJoUGVJVmtiU3UzcUIKS3hZNjFvYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: UWR2RW9aSHpBMGk5YnYwa3NjaTZBbUl4SzFPYTRBSyt4bHo2eEl2RGxMQT0Kubuntu@ubuntu:~$ sudo bash
root@ubuntu:/home/ubuntu# cat ~/.kube/cache/
discovery/ http/      
root@ubuntu:/home/ubuntu# cat ~/.kube/cache/
discovery/ http/      
root@ubuntu:/home/ubuntu# microk8s statu
`

**Comment by ktsakalozos** [comment]
Could you please set a different hostname to each node.

**Comment by eddiechristian** [comment]
The master is hung, so i cant get that report(it hangs in inspect) 
[inspection-report-20210519_194451.tar.gz](https://github.com/ubuntu/microk8s/files/6511242/inspection-report-20210519_194451.tar.gz)

**Comment by eddiechristian** [comment]
now iam trying ubuntu21.04 and getting `root@new-hostname:/home/ubuntu# microk8s join 192.168.1.222:25000/48220197b6c261522543ec20ab11615e
Contacting cluster at 192.168.1.222
Waiting for this node to finish joining the cluster. ..  
Traceback (most recent call last):
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 900, in join_dqlite
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 856, in update_dqlite
    restart_all_services()
  File "/snap/microk8s/2157/scripts/cluster/join.py", line 784, in restart_all_services
    stderr=subprocess.DEVNULL,
  File "/snap/microk8s/2157/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/2157/microk8s-stop.wrapper']' returned non-zero exit status 1
root@new-hostname:/home/ubuntu# microk8s join 172.17.0.1:25000/48220197b6c261522543ec20ab11615e`

hopefully my network config is not affecting it? `root@new-hostname:/home/ubuntu# cat /etc/netplan/50-cloud-init.yaml 
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    wifis:
        wlan0:
            access-points:
                Fios-G2NCh:
                    password: sou35pea63unhand
            dhcp4: true
            optional: true
root@new-hostname:/home/ubuntu#`

**Comment by ktsakalozos** [comment]
As soon as a multi node cluster is formed the IPs of the nodes should not change.

**Comment by eddiechristian** [comment]
they are not changing..... why do you think they are changing?

**Comment by eddiechristian** [comment]
Can you give me some more direction? I dont think the rasp pi rebooted, but i will do what it says above and re-try the join? My colleagues and i work with k8s everyday(kubeadm to join) and 3 of us have struggled to get microk8s up... it should not be that hard , especially for those who have used k8s on a daily basis.

**Comment by bambinounos** [comment]
Hi guys, I am trying to add nodes in ARM64 Ampere, buy it doesn't work as well.
Unfortunately [https://microk8s.io/docs/install-alternatives#heading--arm] has no information, because it seems to be different to add cgroup for example.
