### ISSUE TITLE
flanneld stopped because of expired certificate after a year

### ISSUE THREAD

**Issue by andersrye** [canonical/microk8s#2297]
I'm running a cluster using the 1.18/stable channel (v1.18.18), that has been running for more than a year now (hence the problem)

flanneld exited with
```
microk8s.daemon-flanneld[30911]: E0528 14:27:35.940567   30911 main.go:416] Error renewing lease (trying again in 1 min): client: etcd cluster is unavailable or misconfigured; error #0: remote error: tls: bad certificate
microk8s.daemon-flanneld[30911]: E0528 14:28:33.641454   30911 main.go:432] Lease has been revoked. Shutting down daemon.
```
and would not start up again until i used `microk8s leave` and `microk8s join` to rejoin the cluster

From a quick search through the source it seems the certificate used to authenticate with etcd ("server.remote.crt") is only generated when joining a cluster and it has a hard-coded duration of 365 days. Is there any method to regenerate this certificate manually, or is the only solution to leave and rejoin on each node? 

Thanks for any help!

**Comment by ktsakalozos** [comment]
Hi @andersrye, please have a look at this comment https://github.com/ubuntu/microk8s/issues/2297 on how you can refresh the used certificates.

**Comment by andersrye** [comment]
Hi, thanks for the response, but I think you linked the wrong message?
