### ISSUE TITLE
Microk8s with cilium 1.10

### ISSUE THREAD

**Issue by ghazalrana** [canonical/microk8s#2301]
Hi ,
I want to use cilium 1.10 on microk8s. I came across this ;

https://docs.cilium.io/en/v1.10/gettingstarted/microk8s/#gs-microk8s

It is also giving cilium 1.8 instead of 1.10 (microk8s 1.21).

Is there any way for cilium 1.10 ?

**Comment by ktsakalozos** [comment]
Hi @ghazalrana , there is no easy way to switch to cilium 1.10. You can explore the following options:

- `microk8s enable cilium` and then upgrade to 1.10 following the instructions describe in the cilium project, or
- replay the steps in the cilium enable script [1] for the 1.10 release 

Maybe @joestringer knows of an easier way to get 1.10.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.cilium.sh

**Comment by joestringer** [comment]
Hi @ghazalrana , I believe that once you have installed via `microk8s enable cilium`, you should be able to use the new Cilium cluster CLI from github.com/cilium/cilium-cli to install a newer version of Cilium over the top. For Cilium v1.10, you may need to specify `cilium install --version v1.10.0` for now to get the newer release.

I have recently been working on updating microk8s to leverage this new CLI but the changes are not yet ready. This will bring Cilium v1.10 along with ARM64 support as well.
