### ISSUE TITLE
Microk8s is not running 

### ISSUE THREAD

**Issue by devcose** [canonical/microk8s#2302]
fresh install on ubuntu 20.04
using https://microk8s.io/

After running 
`microk8s enable dashboard dns registry istio `
and running `microk8s kubectl get all --all-namespaces` present's me with  and all other pods that are created remain pending 

NAMESPACE     NAME                                             READY   STATUS    RESTARTS   AGE
kube-system   pod/calico-node-cdtjb                            0/1     Pending   0          36m
kube-system   pod/calico-kube-controllers-847c8c99d-c2k7v      0/1     Pending   0          36m
kube-system   pod/metrics-server-8bbfb4bdb-gxtd8               0/1     Pending   0          30m
kube-system   pod/kubernetes-dashboard-7ffd448895-prlth        0/1     Pending   0          29m
kube-system   pod/dashboard-metrics-scraper-6c4568dc68-cb924   0/1     Pending   0          29m

NAMESPACE     NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
default       service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP    36m
kube-system   service/metrics-server              ClusterIP   10.152.183.171   <none>        443/TCP    30m
kube-system   service/kubernetes-dashboard        ClusterIP   10.152.183.202   <none>        443/TCP    29m
kube-system   service/dashboard-metrics-scraper   ClusterIP   10.152.183.234   <none>        8000/TCP   29m

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node   1         1         0       1            0           kubernetes.io/os=linux   36m

NAMESPACE     NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/calico-kube-controllers     0/1     1            0           36m
kube-system   deployment.apps/metrics-server              0/1     1            0           30m
kube-system   deployment.apps/kubernetes-dashboard        0/1     1            0           29m
kube-system   deployment.apps/dashboard-metrics-scraper   0/1     1            0           29m

NAMESPACE     NAME                                                   DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/calico-kube-controllers-847c8c99d      1         1         0       36m
kube-system   replicaset.apps/metrics-server-8bbfb4bdb               1         1         0       30m
kube-system   replicaset.apps/kubernetes-dashboard-7ffd448895        1         1         0       29m
kube-system   replicaset.apps/dashboard-metrics-scraper-6c4568dc68   1         1         0       29m

Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20210531_101233.tar.gz](https://github.com/ubuntu/microk8s/files/6568456/inspection-report-20210531_101233.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by balchua** [comment]
Are you using a btrfs file system or an ext4?

**Comment by locose-dev** [comment]
HP Desktop
`lspci`
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 05)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 05)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
00:14.0 USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (rev 31)
00:16.0 Communication controller: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] (rev 31)
00:1c.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #5 (rev f1)
00:1c.6 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #7 (rev f1)
00:1f.0 ISA bridge: Intel Corporation H110 Chipset LPC/eSPI Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller (rev 31)
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
00:1f.4 SMBus: Intel Corporation 100 Series/C230 Series Chipset Family SMBus (rev 31)
02:00.0 PCI bridge: Integrated Technology Express, Inc. IT8893E PCIe to PCI Bridge (rev 52)
04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

`uname -a`
Linux markbuntudt 5.12.0-8.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.12-7ubuntu1~focal (2021-05-28) x86_64 x86_64 x86_64 GNU/Linux

`lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

anything specific beyond this that you were looking for or that i can add?

**Comment by balchua** [comment]
Im wondering why that kubelet error shows up.  It looks like your cgroups isn't setup normally.
Is this instance a VM?

**Comment by locose-dev** [comment]
no just regular install on desktop.
