### ISSUE TITLE
Enabling Kubeflow stuck

### ISSUE THREAD

**Issue by Sadat-Remon** [canonical/microk8s#2320]
I am trying to enable kubeflow on Linux by the command:
**microk8s.enable kubeflow**

It shows:

Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...

But I get nothing after this. Please help

**Comment by ktsakalozos** [comment]
Could you please attach the tarball created by `microk8s inspect` ?

**Comment by Sadat-Remon** [comment]
@ktsakalozos I have attached the tarball.

[inspection-report-20210607_152008.tar.gz](https://github.com/ubuntu/microk8s/files/6606317/inspection-report-20210607_152008.tar.gz)
