### ISSUE TITLE
Kubelite keeps crashing and restarting

### ISSUE THREAD

**Issue by KiqoCode** [canonical/microk8s#2324]
[inspection-report-20210607_110536.tar.gz](https://github.com/ubuntu/microk8s/files/6608284/inspection-report-20210607_110536.tar.gz)

Could see from logs:
```
Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Scheduled restart job, restart counter is at 124.
Jun 07 04:55:05 k8s-1 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
Jun 07 04:55:05 k8s-1 systemd[1]: Started Service for snap application microk8s.daemon-kubelite.
```

```
ubuntu@k8s-1:~$ ls -lh /var/snap/microk8s/current/var/kubernetes/backend/
total 245M
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:47 0000000006217453-0000000006218055
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:48 0000000006218056-0000000006218574
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:49 0000000006218575-0000000006219095
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:51 0000000006219096-0000000006219487
-rw-rw---- 1 root microk8s 516K Jun  7 10:51 0000000006219488-0000000006219527
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:51 0000000006219528-0000000006220145
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:53 0000000006220146-0000000006220653
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:54 0000000006220654-0000000006221157
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:56 0000000006221158-0000000006221622
-rw-rw---- 1 root microk8s 5.9M Jun  7 10:56 0000000006221623-0000000006222022
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:57 0000000006222023-0000000006222552
-rw-rw---- 1 root microk8s 8.0M Jun  7 10:58 0000000006222553-0000000006223129
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:00 0000000006223130-0000000006223573
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:01 0000000006223574-0000000006224142
-rw-rw---- 1 root microk8s 2.1M Jun  7 11:01 0000000006224143-0000000006224304
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:03 0000000006224305-0000000006224859
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:04 0000000006224860-0000000006225410
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 0000000006225411-0000000006225914
-rw-rw---- 1 root microk8s 6.5M Jun  7 11:06 0000000006225915-0000000006226371
-rw-rw---- 1 root microk8s 1.9K May 28 13:08 cluster.crt
-rw-rw---- 1 root microk8s 3.2K May 28 13:08 cluster.key
-rw-rw---- 1 root microk8s    0 Jun  6 18:46 cluster.yaml
-rw-rw-r-- 1 root microk8s    2 Jun  7 11:06 failure-domain
-rw-rw---- 1 root microk8s   59 May 28 13:32 info.yaml
srw-rw---- 1 root microk8s    0 Jun  6 10:23 kine.sock
-rw-rw---- 1 root microk8s   65 Jun  6 10:23 localnode.yaml
-rw-rw---- 1 root microk8s   32 Jun  7 10:21 metadata1
-rw-rw---- 1 root microk8s   32 Jun  7 10:14 metadata2
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:07 open-1
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 open-2
-rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 open-3
-rw-rw---- 1 root microk8s  43M Jun  7 11:03 snapshot-28-6225094-2623398
-rw-rw---- 1 root microk8s  152 Jun  7 11:03 snapshot-28-6225094-2623398.meta
-rw-rw---- 1 root microk8s  43M Jun  7 11:06 snapshot-28-6226118-2825912
-rw-rw---- 1 root microk8s  152 Jun  7 11:06 snapshot-28-6226118-2825912.meta
```

**Comment by ktsakalozos** [comment]
@MathieuBordere any recommendations on how to approach this issue? 

On the kubelite logs I see:
```
Jun 07 10:56:46 k8s-1 microk8s.daemon-kubelite[18578]: + exec /snap/microk8s/2215/kubelite --scheduler-args-file=/var/snap/microk8s/2215/args/kube-scheduler --controller-manager-args-file=/var/snap/microk8s/2215/args/kube-controller-manager --proxy-args-file=/var/snap/microk8s/2215/args/kube-proxy --kubelet-args-file=/var/snap/microk8s/2215/args/kubelet --apiserver-args-file=/var/snap/microk8s/2215/args/kube-apiserver --kubeconfig-file=/var/snap/microk8s/2215/credentials/client.config --start-control-plane=true
Jun 07 10:56:47 k8s-1 microk8s.daemon-kubelite[18578]: Starting kubelite
Jun 07 10:56:47 k8s-1 microk8s.daemon-kubelite[18578]: I0607 10:56:47.226120   18578 daemon.go:73] Waiting for the API server
Jun 07 10:56:47 k8s-1 microk8s.daemon-kubelite[18578]: I0607 10:56:47.228110   18578 daemon.go:65] Starting API Server
Jun 07 10:56:47 k8s-1 microk8s.daemon-kubelite[18578]: Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
Jun 07 10:56:47 k8s-1 microk8s.daemon-kubelite[18578]: I0607 10:56:47.230109   18578 server.go:654] external host was not specified, using 10.10.50.10
Jun 07 11:01:51 k8s-1 microk8s.daemon-kubelite[18578]: Error: context deadline exceeded
Jun 07 11:01:51 k8s-1 microk8s.daemon-kubelite[18578]: F0607 11:01:51.291594   18578 daemon.go:67] API Server exited context deadline exceeded
```

This 5 minute timeout seems suspiciously familiar. https://github.com/ubuntu/microk8s/pull/2209

**Comment by MathieuBordere** [comment]
From the logs it looks to me like the node has trouble finding the leader of the cluster, based on lines like the following.
```
Jun 06 20:22:49 k8s-1 microk8s.daemon-kubelite[4073511]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/client.FindLeader(0x5e9f250, 0x40007c1ac0, 0x5e25d88, 0x40007c19c0, 0x400051cc80, 0x2, 0x2, 0x132a02af28b95, 0x4000e44cd0, 0x40009bfb00)
Jun 06 20:22:49 k8s-1 microk8s.daemon-kubelite[4073511]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/client/leader.go:26 +0x160
```

- How many nodes does your cluster count
- Do you have the inspection reports of your other nodes?
- I see you're running on a Raspberry Pi, have you already tried the suggestions based on this thread? https://github.com/ubuntu/microk8s/issues/2280

**Comment by KiqoCode** [comment]
I have 4 nodes, the other 3 has been healthy all along, this one only started acting up quite recently I noticed today..
[k8s-2.tar.gz](https://github.com/ubuntu/microk8s/files/6609120/k8s-2.tar.gz)
[k8s-3.tar.gz](https://github.com/ubuntu/microk8s/files/6609124/k8s-3.tar.gz)
[k8s-4.tar.gz](https://github.com/ubuntu/microk8s/files/6609125/k8s-4.tar.gz)

From that issue I can't see anything related to my issue really.. Not using any kind of USB storage and haven't noticed any kind of performance issues, even when running ElasticSearch + Fluentd..

**Comment by ktsakalozos** [comment]
Could you head on one of the functioning nodes and run:
```
sudo -E /snap/microk8s/current/bin/dqlite -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml k8s ".leader"
```

This should tell us who the leader is. Is it possible there is a network issue between the leader and the failing node?

**Comment by KiqoCode** [comment]
```
ubuntu@k8s-2:~$ sudo -E /snap/microk8s/current/bin/dqlite -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml k8s ".leader"
10.10.50.12:19001

ubuntu@k8s-1:~$ ping 10.10.50.12
PING 10.10.50.12 (10.10.50.12) 56(84) bytes of data.
64 bytes from 10.10.50.12: icmp_seq=1 ttl=64 time=15.5 ms
64 bytes from 10.10.50.12: icmp_seq=2 ttl=64 time=0.241 ms
64 bytes from 10.10.50.12: icmp_seq=3 ttl=64 time=0.188 ms

ubuntu@k8s-3:~$ ping 10.10.50.10
PING 10.10.50.10 (10.10.50.10) 56(84) bytes of data.
64 bytes from 10.10.50.10: icmp_seq=1 ttl=64 time=0.341 ms
64 bytes from 10.10.50.10: icmp_seq=2 ttl=64 time=0.253 ms
64 bytes from 10.10.50.10: icmp_seq=3 ttl=64 time=0.202 ms
```

Atleast ping works between them

**Comment by KiqoCode** [comment]
I manged to get the microk8s instance reset on the failing node after some tries.. And it's not in the kubectl of the working nodes.. However it is still there in dqlite:
```
dqlite> .cluster
2dc171858c3155be|10.10.50.10:19001|stand-by
c4313953f7dba417|10.10.50.11:19001|voter
d86e3131cdd0344a|10.10.50.12:19001|voter
a02c434d100a33e5|10.10.50.13:19001|voter
```
How can I delete 10.10.50.10 from dqlite to be able to rejoin?

**Comment by MathieuBordere** [comment]
There's this https://github.com/canonical/go-dqlite/blob/7071b960867314b04606a831ad8ffaa08d6b6c9d/client/client.go#L237 in go-dqlite , I'm not sure how it is wired up in microk8s, @ktsakalozos might have the answer to that.

**Comment by KiqoCode** [comment]
Managed to remove it from dqlite and rejoined. Now it's working fine again but will monitor for a little while.

**Comment by KiqoCode** [comment]
@MathieuBordere @ktsakalozos Now the exact same thing has happened to another node.

**Comment by MathieuBordere** [comment]
@KiqoCode Can you attach the inspection report for all 4 nodes please?

**Comment by KiqoCode** [comment]
[k8s-3.tar.gz](https://github.com/ubuntu/microk8s/files/6647443/k8s-3.tar.gz)
[k8s-4.tar.gz](https://github.com/ubuntu/microk8s/files/6647444/k8s-4.tar.gz)
[k8s-1.tar.gz](https://github.com/ubuntu/microk8s/files/6647445/k8s-1.tar.gz)
[k8s-2.tar.gz](https://github.com/ubuntu/microk8s/files/6647446/k8s-2.tar.gz)

It's node k8s-4 that got the problem now @MathieuBordere

**Comment by KiqoCode** [comment]
Any ideas? @MathieuBordere @ktsakalozos

**Comment by MathieuBordere** [comment]
@KiqoCode I would need a way to reproduce this to help you along, it's difficult to know what's going on right now.

**Comment by KiqoCode** [comment]
@MathieuBordere Can I provide any more information to make it anyway possible to investigate? 
Since this happened on one node before, fixed that one and then another one stopped working.. So I feel like it's just a very temporary fix to just delete that node, reset it and add it again..

**Comment by MathieuBordere** [comment]
> [inspection-report-20210607_110536.tar.gz](https://github.com/ubuntu/microk8s/files/6608284/inspection-report-20210607_110536.tar.gz)
> 
> Could see from logs:
> 
> ```
> Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=255/EXCEPTION
> Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
> Jun 07 04:55:05 k8s-1 systemd[1]: snap.microk8s.daemon-kubelite.service: Scheduled restart job, restart counter is at 124.
> Jun 07 04:55:05 k8s-1 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
> Jun 07 04:55:05 k8s-1 systemd[1]: Started Service for snap application microk8s.daemon-kubelite.
> ```
> 
> ```
> ubuntu@k8s-1:~$ ls -lh /var/snap/microk8s/current/var/kubernetes/backend/
> total 245M
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:47 0000000006217453-0000000006218055
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:48 0000000006218056-0000000006218574
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:49 0000000006218575-0000000006219095
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:51 0000000006219096-0000000006219487
> -rw-rw---- 1 root microk8s 516K Jun  7 10:51 0000000006219488-0000000006219527
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:51 0000000006219528-0000000006220145
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:53 0000000006220146-0000000006220653
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:54 0000000006220654-0000000006221157
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:56 0000000006221158-0000000006221622
> -rw-rw---- 1 root microk8s 5.9M Jun  7 10:56 0000000006221623-0000000006222022
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:57 0000000006222023-0000000006222552
> -rw-rw---- 1 root microk8s 8.0M Jun  7 10:58 0000000006222553-0000000006223129
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:00 0000000006223130-0000000006223573
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:01 0000000006223574-0000000006224142
> -rw-rw---- 1 root microk8s 2.1M Jun  7 11:01 0000000006224143-0000000006224304
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:03 0000000006224305-0000000006224859
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:04 0000000006224860-0000000006225410
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 0000000006225411-0000000006225914
> -rw-rw---- 1 root microk8s 6.5M Jun  7 11:06 0000000006225915-0000000006226371
> -rw-rw---- 1 root microk8s 1.9K May 28 13:08 cluster.crt
> -rw-rw---- 1 root microk8s 3.2K May 28 13:08 cluster.key
> -rw-rw---- 1 root microk8s    0 Jun  6 18:46 cluster.yaml
> -rw-rw-r-- 1 root microk8s    2 Jun  7 11:06 failure-domain
> -rw-rw---- 1 root microk8s   59 May 28 13:32 info.yaml
> srw-rw---- 1 root microk8s    0 Jun  6 10:23 kine.sock
> -rw-rw---- 1 root microk8s   65 Jun  6 10:23 localnode.yaml
> -rw-rw---- 1 root microk8s   32 Jun  7 10:21 metadata1
> -rw-rw---- 1 root microk8s   32 Jun  7 10:14 metadata2
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:07 open-1
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 open-2
> -rw-rw---- 1 root microk8s 8.0M Jun  7 11:06 open-3
> -rw-rw---- 1 root microk8s  43M Jun  7 11:03 snapshot-28-6225094-2623398
> -rw-rw---- 1 root microk8s  152 Jun  7 11:03 snapshot-28-6225094-2623398.meta
> -rw-rw---- 1 root microk8s  43M Jun  7 11:06 snapshot-28-6226118-2825912
> -rw-rw---- 1 root microk8s  152 Jun  7 11:06 snapshot-28-6226118-2825912.meta
> ```
I now notice `cluster.yaml` looks empty on the faulty node in 

Can you perform a `ls -lh /var/snap/microk8s/current/var/kubernetes/backend/` on the faulty and on the healthy node and also post the contents of `cluster.yaml` of both nodes please?

**Comment by KiqoCode** [comment]
k8s-4 10.10.50.13(Faulty Node)
```
ubuntu@k8s-4:~$ ls -lh /var/snap/microk8s/current/var/kubernetes/backend/
total 181M
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:47 0000000010905161-0000000010905657
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:49 0000000010905658-0000000010906192
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:50 0000000010906193-0000000010906723
-rw-rw---- 1 root microk8s 4.3M Jun 16 10:51 0000000010906724-0000000010907004
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:52 0000000010907005-0000000010907509
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:54 0000000010907510-0000000010908040
-rw-rw---- 1 root microk8s 7.9M Jun 16 10:56 0000000010908041-0000000010908480
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:57 0000000010908481-0000000010909002
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:58 0000000010909003-0000000010909596
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:59 0000000010909597-0000000010910135
-rw-rw---- 1 root microk8s 5.3M Jun 16 11:01 0000000010910136-0000000010910403
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:02 0000000010910404-0000000010910914
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:04 0000000010910915-0000000010911431
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:05 0000000010911432-0000000010912002
-rw-rw---- 1 root microk8s 6.9M Jun 16 11:06 0000000010912003-0000000010912439
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:07 0000000010912440-0000000010912963
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:09 0000000010912964-0000000010913488
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:10 0000000010913489-0000000010914028
-rw-rw---- 1 root microk8s 1.9K May 28 13:39 cluster.crt
-rw-rw---- 1 root microk8s 3.2K May 28 13:39 cluster.key
-rw-rw---- 1 root microk8s    0 Jun 13 02:01 cluster.yaml
-rw-rw-r-- 1 root microk8s    2 Jun 16 11:06 failure-domain
-rw-rw---- 1 root microk8s   60 May 28 13:39 info.yaml
srw-rw---- 1 root microk8s    0 Jun 12 18:29 kine.sock
-rw-rw---- 1 root microk8s   66 Jun 12 18:28 localnode.yaml
-rw-rw---- 1 root microk8s   32 Jun 16 09:35 metadata1
-rw-rw---- 1 root microk8s   32 Jun 16 09:35 metadata2
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:11 open-4
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:09 open-5
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:10 open-6
-rw-rw---- 1 root microk8s  11M Jun 16 11:07 snapshot-86-10912615-660258974
-rw-rw---- 1 root microk8s  152 Jun 16 11:07 snapshot-86-10912615-660258974.meta
-rw-rw---- 1 root microk8s  11M Jun 16 11:09 snapshot-86-10913639-660377206
-rw-rw---- 1 root microk8s  152 Jun 16 11:09 snapshot-86-10913639-660377206.meta

ubuntu@k8s-4:~$ cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
ubuntu@k8s-4:~$
```
k8s-1 10.10.50.10 (Healthy Node)
```
ubuntu@k8s-1:~$ ls -lh /var/snap/microk8s/current/var/kubernetes/backend/
total 181M
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:47 0000000010905115-0000000010905584
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:49 0000000010905585-0000000010906118
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:50 0000000010906119-0000000010906650
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:52 0000000010906651-0000000010907133
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:53 0000000010907134-0000000010907716
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:54 0000000010907717-0000000010908234
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:57 0000000010908235-0000000010908612
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:57 0000000010908613-0000000010909228
-rw-rw---- 1 root microk8s 8.0M Jun 16 10:59 0000000010909229-0000000010909765
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:00 0000000010909766-0000000010910299
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:02 0000000010910300-0000000010910735
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:04 0000000010910736-0000000010911259
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:04 0000000010911260-0000000010911870
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:06 0000000010911871-0000000010912390
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:07 0000000010912391-0000000010912883
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:09 0000000010912884-0000000010913407
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:10 0000000010913408-0000000010913949
-rw-rw---- 1 root microk8s 1.9K Jun  7 15:42 cluster.crt
-rw-rw---- 1 root microk8s 3.2K Jun  7 15:42 cluster.key
-rw-rw---- 1 root microk8s  264 Jun 16 11:11 cluster.yaml
-rw-rw-r-- 1 root microk8s    2 Jun 16 09:30 failure-domain
-rw-rw---- 1 root microk8s   60 Jun  7 15:42 info.yaml
srw-rw---- 1 root microk8s    0 Jun 16 09:30 kine.sock
-rw-rw---- 1 root microk8s   66 Jun 16 09:30 localnode.yaml
-rw-rw---- 1 root microk8s   32 Jun 16 09:35 metadata1
-rw-rw---- 1 root microk8s   32 Jun 16 09:35 metadata2
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:11 open-72
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:09 open-73
-rw-rw---- 1 root microk8s 8.0M Jun 16 11:10 open-74
-rw-rw---- 1 root microk8s  10M Jun 16 11:06 snapshot-86-10912443-660197993
-rw-rw---- 1 root microk8s  152 Jun 16 11:06 snapshot-86-10912443-660197993.meta
-rw-rw---- 1 root microk8s  11M Jun 16 11:09 snapshot-86-10913467-660358969
-rw-rw---- 1 root microk8s  152 Jun 16 11:09 snapshot-86-10913467-660358969.meta

ubuntu@k8s-1:~$ cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
- Address: 10.10.50.11:19001
  ID: 14137143738096133143
  Role: 0
- Address: 10.10.50.12:19001
  ID: 15595456649606739018
  Role: 0
- Address: 10.10.50.13:19001
  ID: 11541673943304385509
  Role: 1
- Address: 10.10.50.10:19001
  ID: 10948548379568619488
  Role: 0
```

So `cluster.yaml` is empty on faulty node, on a healthy node it says that k8s-4 (10.10.50.13) has `Role: 1`

**Comment by MathieuBordere** [comment]
Thanks, should not be too hard for us to figure out what could possibly go wrong now.

**Comment by KiqoCode** [comment]
@MathieuBordere it only seems to happen to the leader, since before it happened to k8s-1 when it was leader, now k8s-4 is the leader and it happened to that node.

**Comment by KiqoCode** [comment]
@MathieuBordere so I actually just took the /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml from a healthy node and put on the faulty node and it started working again.. Will probably fail again sometime though..

**Comment by MathieuBordere** [comment]
@KiqoCode Yes, I expected that to help. I might have a clue what's causing it, see linked issue.

**Comment by KiqoCode** [comment]
@MathieuBordere yes I saw that linked issue, so that's why I tried it :)
