### ISSUE TITLE
Enable Kubeflow gets stuck when RBAC is previously enabled

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/microk8s#2342]
When trying to install kubeflow through the addon on a microk8s which had RBAC previously enable the istio-ingressgateway charm stays in a waiting state with the following message: `Waiting for Istio Pilot information`

This can be avoided by executing the following command while the charms are spinning up:
```
microk8s kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
```
This command will probably have to be added somewhere in the script in the case of RBAC being enabled.

Steps to reproduce:
```
microk8s enable rbac
microk8s enable kubeflow-lite
```

**Comment by knkski** [comment]
It looks like we need to port over this section from `cli.py` that handles patching the istio-ingressgateway role:

https://github.com/canonical/bundle-kubeflow/blob/0563e6b/scripts/cli.py#L336-L357
