### ISSUE TITLE
Cannot pull image from private registor

### ISSUE THREAD

**Issue by leolnid** [canonical/microk8s#2354]
Good day!
During the development process, we encountered a problem, it is not possible to pull image from private harbor instance.

However, I can do
docker login harbor.domain.com --username=k8s --password=<PASSWORD>
docker pull harbor.domain.dev/gitlab/test-3:latest

I created a secret with this command
```kubectl create secret docker-registry regcred --docker-server=https://harbor.domain.dev --docker-username=k8s --docker-password=<PASSWORD>```

Also tryed: ```kubectl create secret docker-registry regcred --docker-server=harbor.domain.dev --docker-username=k8s --docker-password=<PASSWORD>```

My deploy file looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-domain-dev
spec:
  selector:
    matchLabels:
      run: test-domain-dev
  template:
    metadata:
      labels:
        run: test-domain-dev
    spec:
      containers:
        - name: test-domain-dev
          image: harbor.domain.dev/gitlab/test-3:latest
          imagePullPolicy: Always
          env:
            - name: HTTP_PORT
              value: "80"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
```

This returns error after apply. 
```
default               test-domain-dev-69466954d4-j2ddr                0/1     ImagePullBackOff   0          3m23s   10.1.219.213    development-1   <none>           <none>
```

```
 Normal   Scheduled  3m51s                  default-scheduler  Successfully assigned default/test-domain-dev-69466954d4-j2ddr to development-1
  Warning  Failed     2m28s (x6 over 3m50s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    2m17s (x4 over 3m50s)  kubelet            Pulling image "harbor.domain.dev/gitlab/test-3:latest"
  Warning  Failed     2m17s (x4 over 3m50s)  kubelet            Failed to pull image "harbor.domain.dev/gitlab/test-3:latest": rpc error: code = Unknown desc = failed to pull and unpack image "harbor.domain.dev/gitlab/test-3:latest": failed to resolve reference "harbor.domain.dev/gitlab/test-3:latest": failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
  Warning  Failed     2m17s (x4 over 3m50s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2m2s (x7 over 3m50s)   kubelet            Back-off pulling image "harbor.domain.dev/gitlab/test-3:latest"
```

Several times I have already recreated all this, several times deleted and reinstalled microk8s, completely reinstalled the virtual machine...

I tried to create a secret already from the docker config file, and change it ... I tried to push the login-password into /var/snap/microk8s/current/args/containerd-template.toml, but then microk8s generally crashes at the start

**Comment by leolnid** [comment]
In harbor I can select public type of project and then everything fine... But if you use private, the problem persists

**Comment by leolnid** [comment]
Also tryed to create /etc/containerd/config.toml with:
# explicitly use v2 config format
version = 2

# The registry host has to be a domain name or IP. Port number is also
# needed if the default HTTPS or HTTP port is not used.
[plugin."io.containerd.grpc.v1.cri".registry.configs."gcr.io".auth]
  username = k8s 
  password = "<Password>"
  auth = "base64_encode(k8s:<Password>)"
  identitytoken = ""
  
With the same result

**Comment by herberthobregon** [comment]
You need follow official instructions

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry

**Comment by ktsakalozos** [comment]
The containerd configuration is at `/var/snap/microk8s/current/args/containerd-template.toml`.

**Comment by GeorGeWzw** [comment]
@ktsakalozos Do I need to reload the configuration file after containerd is configured?

**Comment by addyess** [comment]
I also understand your plight @leolnid 

I went through the same issue today and seem to have come up with config changes to 
`/var/snap/microk8s/current/args/containerd-template.toml` which resolved the issue on my end using containerd version 1.5.2
```
$ /snap/microk8s/current/bin/containerd --version
containerd github.com/containerd/containerd v1.5.2 36cc874494a56a253cd181a1a685b44b58a2e34a
```


Firstly look in the key at: `[plugins."io.containerd.grpc.v1.cri".registry.mirrors]` for the hostname following the `https://`

for example)
```
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."my.domain"]
        endpoint = ["https://subdomain.my.domain", ]
```

If this is your case, the key to use on the configs should look like this:
```
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."subdomain.my.domain".auth]
          username = k8s 
          password = "<Password>"
          auth = "base64_encode(k8s:<Password>)"
```

after the change, `microk8s stop; microk8s start` should work.  

For testing my changes i found that using `crictl` was really nice to test the changes of containerd
```bash
sudo ./crictl --debug --runtime-endpoint unix:///var/snap/microk8s/common/run/containerd.sock pull my.domain/busybox:latest
```

Note: There's really no need to provide `username` and `password` as the encoded auth token should work just fine. 

Any close of this bug should result in a microk8s doc update to follow along with the may changes to the containerd upstream docs on this subject:

here: https://github.com/containerd/containerd/blob/main/docs/cri/registry.md
here: https://github.com/containerd/cri/blob/release/1.2/docs/registry.md

as upstream docs mention

**Comment by hiagodotme** [comment]
@leolnid has your problem been resolved? The same thing is happening to me.

@herberthobregon I followed all the steps described in https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ to try to pull my private registry with Gitlab.

On my local machine, Docker can pull normally, on K8s it cannot.

**Comment by herberthobregon** [comment]
@hiagodotme Are you using Mac OS or window to generate your docker Config file? Have you checked what that file contains? Windows and Mac save passwords in their password manager. Login to Linux and copy that file to k8s

**Comment by hiagodotme** [comment]
> @hiagodotme Are you using Mac OS or window to generate your docker Config file? Have you checked what that file contains? Windows and Mac save passwords in their password manager. Login to Linux and copy that file to k8s

Thanks for the answer, I use Ubuntu on Windows (wsl). It's very strange, to give you an idea I enter the name of a secret that doesn't exist (for testing) and the error is the same “403”.

**Comment by herberthobregon** [comment]
@hiagodotme OK you use a generic Linux, try generate this docker Config file with Linux vm and upload your yaml to k8s. Maybe you docker file Config is wrong because You generated it with wsl

**Comment by hiagodotme** [comment]
> @hiagodotme OK you use a generic Linux, try generate this docker Config file with Linux vm and upload your yaml to k8s. Maybe you docker file Config is wrong because You generated it with wsl

Using the instruction below I would not be loading my docker config. Do you believe that if I carry out this procedure there will be any changes?

I ask because my K8s does not have docker installed on the host.

```bash
kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
```
