### ISSUE TITLE
microk8s status shows not running but all services seem to be running properly

### ISSUE THREAD

**Issue by GuiMarthe** [canonical/microk8s#2360]
Hey folks, 
I'm attaching the tar file from `microk8s inspect`  after trying a few things. I've reinstalled (with and without `--purge`) and downgrading to `1.20/stable`. Everything worked fine yesterday, but I've run a few updates and the cluster seemed to not be up after that.

Also, `microk8s status --wait-ready` just hangs, and `microk8s status` gives me the following output:

`microk8s is not running. Use microk8s inspect for a deeper inspection.`

It would be awesome if you guys could help me around this. 

Inspect does show something with cgroups being wrong. But I'm not sure how to configure it under my distro or if that is an issue at all since it is something I've never altered the configs for.

```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

WARNING:  The memory cgroup is not enabled.
The cluster may not be functioning properly. Please ensure cgroups are enabled
See for example: https://microk8s.io/docs/install-alternatives#heading--arm
Building the report tarball
  Report tarball is at /var/snap/microk8s/2264/inspection-report-20210624_202344.tar.gz

```

[inspection-report-20210624_202344.tar.gz](https://github.com/ubuntu/microk8s/files/6712600/inspection-report-20210624_202344.tar.gz)

**Comment by GuiMarthe** [comment]
Was able to make things go back to normality by reinstalling snapd, and consequentially AppArmour again. So maybe here is a hint of what was going on, or where the problem was.

**Comment by skywalkerisnull** [comment]
@GuiMarthe 
I am having the same issue as you, today I did the usual apt updates and reboot. Normally it all comes back up fine. But have this same issues as what you seem to have had.

What steps did you take to reinstall snapd and AppArmour? i.e. did you remove all other snaps first? or some other command to reinstall snapd and AppArmour?

**Comment by GuiMarthe** [comment]
@skywalkerisnull, I haven't used `apt` in a while, so I don't know the exact arguments. But I think there is a `purge` option that deletes everything related to a package. But I also had to delete ` /var/lib/snapd` manually at some point. 
I don't use any other snaps other than microk8s, so I only removed it by the cli before removing snap.

AppArmour was listed as a dependency in pacman (the package manager in Manjaro, the distro I use), so I just used the option to remove orphan packages the package manager has. 

With `apt`  I would manually try to remove AppArmour as well, and then just install Snap, which should list AppArmour as a dependency.

**Comment by skywalkerisnull** [comment]
@GuiMarthe I did end up doing that with the following (in case I need to find this again in the future!):
```bash
systemctl stop apparmor
systemctl disable apparmor
systemctl disable apparmor
reboot
```

The frustrating part is I then had to do this on all the nodes and then re-create them all. But it is up and working again now.
