### ISSUE TITLE
MicroK8s 1.21 Unsupported in FIPS Environment 

### ISSUE THREAD

**Issue by drussellt** [canonical/microk8s#2361]
On RHEL using MicroK8s version 1.21 on a FIPS enabled offline system, the following error is encountered when enabling/disabling add-ons (e.g. microk8s kubectl enable dns) that call Python 3.6 scripts:

fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
/snap/microk8s/2210/actions/common/utils.sh: line 70: 26240 Aborted sudo -E LD_LIBRARY_PATH=”$GLOBAL_LD_LIBRARY_PATH” “$@”

When debugging the actual calls, the enabling/disabling of addons fail when exercising python3 like below:
utils.sh → run_with_sudo()
/snap/microk8s/2210/usr/bin/python3 /snap/microk8s/2210/scripts/cluster/distributed_op.py update_argument kubelet --authentication-token-webhook true

And the enables/disables will succeed when no python3 is called. This is due to the fact that there is no native functionality in Python 3.6 to enable the FIPS mode of the OpenSSL module. When tested in a non-FIPS environment, the issue is not present. 

This affects a number (but not all) of the addons in MicroK8s. A large concern is that this also prevents joining nodes into a cluster. 

The solution is to add in support for FIPS mode in the Python 3.6 bundled with MicroK8s. These two links below describe how to add in this functionality:
https://hussainaliakbar.github.io/add-support-for-fips-mode-and-fips-mode-set-in-python-3-6-0/
https://hussainaliakbar.github.io/build-python-3-6-0-from-source-with-fips-validated-openssl-on-ubuntu-16-04-lts/

This issue was not present in MicroK8s 1.19 which was using Python 3.5. We assume the Python 3.5 build shipped with 1.19 either had been manually updated to support FIPS, or was patched to a level that supported FIPS.

**Comment by drussellt** [comment]
https://discuss.kubernetes.io/t/microk8s-1-21-and-fips/16449

**Comment by drussellt** [comment]
Follow up to this ticket:

Debugging was performed on microk8s 1.19. It appears that the enabling/disabling of addons was not handled via Python 3.5 calls, and that this feature was introduced post 1.19 (to handle these operations with the distributed_op.py script using Python 3.6). This explains the lack of incompatibility with FIPS in 1.19 and why this issue has just appeared in subsequent versions.

If these operations going forward are desired to be handled via the Python 3.6 script(s), then Python 3.6 needs to be updated to support FIPS as described in the initial description. Alternatively, these operations could also be reverted to using their original calls (which don't use Python). 

**1.21 call enable/disable (using Python 3.6 scripts):**
/snap/microk8s/2210/usr/bin/python3 /snap/microk8s/2210/scripts/cluster/distributed_op.py update_argument kubelet --authentication-token-webhook true

**1.19 call enable/disable (not using Python 3.6 scripts):**
/snap/microk8s/1710/bin/sed -i s;^--authentication-token-webhook=.*; --authentication-token-webhook=true; /var/snap/microk8s/1710/args/kubelet

**Comment by evilnick** [comment]
@ktsakalozos are we planning on tackling this at any time? otherwise it may be better to add a note to the docs somewhere

**Comment by ktsakalozos** [comment]
We have this task in our todo list. We need to make some time to work on it.

Moving back to the bash based enable/disable scripts is not a good option. It seems we will need to build our own python with proper fips support. There is a past attempt [1] for building python but was never finished (in case anyone wants to lend a hand).

[1] https://github.com/ubuntu/microk8s/pull/1940

**Comment by DavidVadnais** [comment]
Has this issue been resolved or is it just stale as the bot implies? I was looking at the build-installer.yml and it seems like the install now uses python 3.8. 

It looks like python3.7+ [may now support](https://github.com/python/cpython/issues/84659) FIPS through [OpenSSL 3.0.0](https://www.openssl.org/blog/blog/2021/09/22/OpenSSL3-fips-submission/). Am I totally off base with this?

**Comment by DavidVadnais** [comment]
I am seeing in the [requirements.txt](https://github.com/canonical/microk8s/blob/master/installer/requirements.txt) a reference to Python 3.6 through pysha.
