### ISSUE TITLE
machine readable flag for "microk8s add node"?

### ISSUE THREAD

**Issue by dstathis** [canonical/microk8s#2395]
When you run "microk8s add node" you get output that looks like:

    From the node you wish to join to this cluster, run the following:
    microk8s join 10.220.113.121:25000/199cfabfeabc905c629ad98d93be964a/d86a2309e376
    
    If the node you are adding is not reachable through the default interface you can use one of the following:
     microk8s join 10.220.113.121:25000/199cfabfeabc905c629ad98d93be964a/d86a2309e376

It would be nice if there was a flag you could pass to get only the command to run so you could capture that and run it in a script.

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @dstathis.

We should have an output format flag similar to what we do for `microk8s status`.

**Comment by balchua** [comment]
@dstathis if you are after automating the `add-node` and `join-node`. There is an option to pass in the token when adding a node.  Then you can use the same token when joining a node.
Which we forgot to add in the documentation. 😊

**Comment by dstathis** [comment]
That makes sense and thanks for the suggestion. I think a --format option would still be nice though as googling for "set up microk8s cluster" doesn't find you info about setting the token.
