### ISSUE TITLE
Problem to execute microk8s CLI MacOs BigSur 11.4

### ISSUE THREAD

**Issue by olympien13** [canonical/microk8s#2396]
I have a Mac with BigSur v11.4 installed I followed the instructions to install MicroK8s on top of it.
https://microk8s.io/docs/install-alternatives#heading--macos

The installation went successfully without any errors. 
"microk8s install" installed perfectly too and I run it again I got that output:
**microk8s install**
MicroK8s is up and running. See the available commands with `microk8s --help`

However I can not execute any of others CLI commands"microk8s" commands such as "status", "stop", 
**microk8s status**
sudo: microk8s.status: command not found
An error occurred when trying to execute 'sudo microk8s.status' with 'multipass': returned exit code 1.

**microk8s stop**
sudo: microk8s.stop: command not found
An error occurred when trying to execute 'sudo microk8s.stop' with 'multipass': returned exit code 1.

Any Clue ? Any idea ? Any suggestions that could help me ?

**Comment by ktsakalozos** [comment]
On MacOs K8s runs in a VM that is driven by Multipass [1]. Could you check if Multipass is ok and that there is a MicroK8s VM running?


[1] https://multipass.run/

**Comment by olympien13** [comment]
Hi,

Multipass is also installed successfull and the VM is running fine as you can see:
multipass list
Name                    State             IPv4             Image
microk8s-vm             Running           192.168.64.9     Ubuntu 18.04 LTS

**Comment by ktsakalozos** [comment]
If you get into the VM with `multipass shell microk8s-vm` do the `microk8s` commands work? For example how does your `microk8s status` and `microk8s kubectl get all -A` look like? If they do not can you fetch a `microk8s.inspect` tarball (with the help of `multipass transfer`) and attach it to this issue?

**Comment by olympien13** [comment]
Hi, 
Here are the output of the two commands you asked me to enter into the multipass VM:
ubuntu@microk8s-vm:/$ microk8s status
microk8s: command not found
ubuntu@microk8s-vm:/$ microk8s kubectl get all -A
microk8s: command not found

Indeed as if it was not installed into the VM. 

Regarding the microk8s.inspect how I can invoke it ? 
Here is the output the "microk8s  inspect" on my mac:
microk8s inspect
sudo: microk8s.inspect: command not found
An error occurred when trying to execute 'sudo microk8s.inspect' with 'multipass': returned exit code 1.

Into the VM here is the output:
ubuntu@microk8s-vm:~$ microk8s inspect
microk8s: command not found

**Comment by ktsakalozos** [comment]
Could it be /snap is not in the PATH? How does `ls /snap` and `snap list` look like? It is strange that the VM got created but the snap is not installed. @joedborg have you seen this before?

**Comment by olympien13** [comment]
I was able to find out indeed that I had to execute manually the command into Multipass VM:
sudo snap install microk8s --classic --channel=1.18/stable

in order to make it work. 

Not sure this is normal I had to run it manually as it is not clearly stated according to me in the doc :
https://microk8s.io/docs/install-alternatives#heading--macos

**Comment by olympien13** [comment]
I still have a small issue. Indeed while executing the "microk8s kubectl" CLI commands into the Multipass VM it works fine. However when trying to invoke them from my Mac, I got:

microk8s kubectl get pods  --all-namespaces
error: stat /Users/Livigni/.microk8s/config: no such file or directory

microk8s kubectl get nodes
error: stat /Users/Livigni/.microk8s/config: no such file or directory

I guess one configuration step is also missing but don't know which ?

**Comment by ktsakalozos** [comment]
You can get the kubeconfig file by running microk8s config.

**Comment by olympien13** [comment]
Great. I had to create by hand the directory ".microk8s" and the content of the `microk8s config ` command within a file named config. 
Works now from my Mac as expected.
@ktsakalozos Thanks a lot for your help and support

**Comment by rkazak** [comment]
I just installed microk8s on my mbp

```
 % sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```
And still see that the directory `~/.microk8s` was not created automatically? The workaround above worked for me too.

1. Manually create the directory ( mkdir ~/.microk8s )
2. Grab the config from the VM environment directly ( multipass shell microk8s-vm, microk8s config )
3. create a file ~/.microk8s/config with the contents from point (2)

**Comment by gsuda2001** [comment]
> I was able to find out indeed that I had to execute manually the command into Multipass VM: sudo snap install microk8s --classic --channel=1.18/stable
> 
> in order to make it work.
> 
> Not sure this is normal I had to run it manually as it is not clearly stated according to me in the doc : https://microk8s.io/docs/install-alternatives#heading--macos

Same issue for me as well in my Macbook.Post this snap installation getting microk8s working.

**Comment by shitalm** [comment]
After Mac upgrade (Mac Monteray, 12.6.1), I got following error:
`microk8s start`

> start failed: The following errors occurred:                                    
> Instance stopped while starting
> An error occurred when trying to execute 'sudo microk8s.start' with 'multipass': returned exit code 2.

Somehow my VM failed to start and was stuck, executed `multipass list` to find the status of VM:
`multipass list`

> Name                    State             IPv4             Image
> microk8s-vm             Starting          --               Ubuntu 18.04 LTS

I then executed following command to recover:
```
multipass stop microk8s-vm
multipass delete microk8s-vm
multipass purge
```
and then finally reinstalled microk8s:
`microk8s install`

This finally fixed the issue.

**Comment by codeyash** [comment]
> `multipass shell microk8s-vm`

multipass shell microk8s-vm
shell failed: ssh connection failed: 'Failed to connect: No route to host'
