### ISSUE TITLE
Microk8s status is unaware of offline master-voter node

### ISSUE THREAD

**Issue by danrg** [canonical/microk8s#2400]
Hello,

Given a high-availability setup, what is the expected behavior when one of the master nodes (but not the leader) is powered off? For the underlying dqlite database, it means one of the voters is powered off.

The [official docs](https://microk8s.io/docs/high-availability) indicate that: 
- If the leader node gets “removed” ungracefully, e.g. it crashes and never comes back, it will take up to 5 seconds for the cluster to elect a new leader.
- Promoting a non-voter to a voter takes up to 30 seconds. This promotion takes place when a new node enters the cluster or when a voter crashes.

So, I expect that if a voter crashes or it's powered-off, then a non-voter is promoted to a voter in 30 seconds, or the cluster gets out of high-availability.

Here is my cluster. I turned off _bignode_, and then it appears as NotReady. However, it's still listed as a master node (voter, I assume) in the output of _microk8s status_, long after the 30 seconds and the status keeps reporting the cluster as high-available.

Is this normal? Can you reproduce it?

```
ubuntu@bluenode:~$ microk8s kubectl get nodes -o wide
NAME         STATUS     ROLES    AGE    VERSION                    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
bignode      NotReady   <none>   2d1h   v1.21.1-3+08fd9d63ea534e   192.168.100.30   <none>        Ubuntu 20.04.2 LTS   5.4.0-1038-raspi   containerd://1.4.4
masternode   Ready      <none>   2d1h   v1.21.1-3+08fd9d63ea534e   192.168.100.29   <none>        Ubuntu 20.04.2 LTS   5.4.0-1038-raspi   containerd://1.4.4
laptop       Ready      <none>   24h    v1.21.1-3+ba118484dd39df   192.168.100.26   <none>        Ubuntu 20.10         5.8.0-59-generic   containerd://1.4.4
bluenode     Ready      <none>   24h    v1.21.1-3+08fd9d63ea534e   192.168.100.31   <none>        Ubuntu 20.04.2 LTS   5.4.0-1028-raspi   containerd://1.4.4
```

```
ubuntu@bluenode:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.100.29:19001 192.168.100.30:19001 192.168.100.31:19001
  datastore standby nodes: 192.168.100.26:19001
addons:
  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
  disabled:
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
    traefik              # traefik Ingress controller for external access
```

Thank you,
Dan

**Comment by danrg** [comment]
I did some more testing and narrowed it to the following steps.
Given a cluster with 4 nodes, 3 nodes are master nodes and one is a standby node.
Run `microk8s stop` on the standby node and on master-voter node. The 2 nodes will appear as `NotReady`, but the cluster remains in high-availability node. The expected behavior is to turn off high-availability, since only 2 nodes are still working.

**Comment by ktsakalozos** [comment]
@danrg you are right that in the case were we are in a three node cluster and one of the nodes powers off we do not display a warning in the `microk8s status`. In this configuration (only two nodes running) you are expected to immediately add a third node so dqlite can form a quorum needed in its normal operation.

@MathieuBordere, I understand this is a case where dqlite assumes the powered off node will come back eventually. Is there a way to detect nodes falling behind so we can warn the user in an appropriate way?

**Comment by MathieuBordere** [comment]
@danrg Can you confirm it only happens when you power off both a master node and a standby node?
When there are 3 voters, 2 online voters is sufficient to have majority, but indeed it's not HA because it will break when one of those last 2 servers goes down.
If it also happens when only a master node is offline and the standby node is not promoted, it's probably a bug.

@ktsakalozos There's currently no way that dqlite reports that one of the nodes is down/falling behind. There would have to be some mechanism where the leader node tries to contact all the nodes and reports the last time it saw the nodes online or something similar. This does not necessarily mean those nodes are down, there might be a network issue e.g.
I'm not sure if this should be part of dqlite itself, I can image some monitoring system that detects that the node is down and then tries to remove it from the dqlite cluster (while it still has quorum) and afterwards adds a new healthy node.

**Comment by danrg** [comment]
@MathieuBordere Indeed, it only happened when powering off both a master and a standby node.
