### ISSUE TITLE
Openebs addon not working in multi-node cluster

### ISSUE THREAD

**Issue by kzay** [canonical/microk8s#2405]
Hi,

I have created a multi-node cluster on top of 3VPS, but i'm facing an issue using openebs.

I was working with the standard storage and everything was fine, after moving to openebs following the documentation i'm now facing on each node using a PVC an error like this:

`Unable to attach or mount volumes: unmounted volumes=[redis-data], unattached volumes=[config redis-tmp-conf tmp sentinel-tmp-conf redis-data kube-api-access-c85qn start-scripts health]: timed out waiting for the condition`

I've tried some investigation but without any result.

> ubuntu@vps-646c8993:~$ microk8s status
> microk8s is running
> high-availability: yes
>   datastore master nodes: 192.99.151.87:19001 144.217.80.200:19001 144.217.83.34:19001
>   datastore standby nodes: none
> addons:
>   enabled:
>     dns                  # CoreDNS
>     ha-cluster           # Configure high availability on the current node
>     helm3                # Helm 3 - Kubernetes package manager
>     ingress              # Ingress controller for external access
>     openebs              # OpenEBS is the open-source storage solution for Kubernetes
>     prometheus           # Prometheus operator for monitoring and logging
>     storage              # Storage class; allocates storage from host directory
>   disabled:
>     ambassador           # Ambassador API Gateway and Ingress
>     cilium               # SDN, fast with full network policy
>     dashboard            # The Kubernetes dashboard
>     fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
>     gpu                  # Automatic enablement of Nvidia CUDA
>     helm                 # Helm 2 - the package manager for Kubernetes
>     host-access          # Allow Pods connecting to Host services smoothly
>     istio                # Core Istio service mesh services
>     jaeger               # Kubernetes Jaeger operator with its simple config
>     keda                 # Kubernetes-based Event Driven Autoscaling
>     knative              # The Knative framework on Kubernetes.
>     kubeflow             # Kubeflow for easy ML deployments
>     linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
>     metallb              # Loadbalancer for your Kubernetes cluster
>     metrics-server       # K8s Metrics Server for API access to service metrics
>     multus               # Multus CNI enables attaching multiple network interfaces to pods
>     openfaas             # openfaas serverless framework
>     portainer            # Portainer UI for your Kubernetes cluster
>     rbac                 # Role-Based Access Control for authorisation
>     registry             # Private image registry exposed on localhost:32000
>     traefik              # traefik Ingress controller for external access

> iscsiadm -V
> iscsiadm version 2.1.3

> sudo iscsiadm -m node session
> iscsiadm: No records found

> systemctl status iscsid
> ● iscsid.service - iSCSI initiator daemon (iscsid)
>      Loaded: loaded (/lib/systemd/system/iscsid.service; enabled; vendor preset: enabled)
>      Active: active (running) since Mon 2021-07-05 02:47:25 UTC; 14min ago
> TriggeredBy: ● iscsid.socket
>        Docs: man:iscsid(8)
>     Process: 757 ExecStartPre=/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
>     Process: 854 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
>    Main PID: 870 (iscsid)
>       Tasks: 2 (limit: 18706)
>      Memory: 3.6M
>      CGroup: /system.slice/iscsid.service
>              ├─869 /sbin/iscsid
>              └─870 /sbin/iscsid
> 
> Jul 05 02:47:25 vps-646c8993 systemd[1]: Starting iSCSI initiator daemon (iscsid)...
> Jul 05 02:47:25 vps-646c8993 iscsid[854]: iSCSI logger with pid=869 started!
> Jul 05 02:47:25 vps-646c8993 systemd[1]: Started iSCSI initiator daemon (iscsid).
> Jul 05 02:47:26 vps-646c8993 iscsid[869]: iSCSI daemon with pid=870 started!
> 

> sudo iscsiadm -m discovery -t st -p *.*.*.*
> iscsiadm: cannot make connection to *.*.*.*: Connection refused
> iscsiadm: cannot make connection to *.*.*.*: Connection refused
> iscsiadm: cannot make connection to *.*.*.*: Connection refused
> iscsiadm: cannot make connection to *.*.*.*: Connection refused
> iscsiadm: cannot make connection to *.*.*.*0: Connection refused
> iscsiadm: cannot make connection to *.*.*.*: Connection refused
> iscsiadm: connection login retries (reopen_max) 5 exceeded
> iscsiadm: Could not perform SendTargets discovery: iSCSI PDU timed out

Please help debug or let me know if the add-on is not yet well supported. 
Thanks!

**Comment by balchua** [comment]
I think openebs didn't start properly.  You can see if the openebs-ndm on each node is started.
`kubectl -n openebs get pods -o wide`

Also check if coredns is running properly.

**Comment by kzay** [comment]
Thanks for your help,

Everythings seems to be runing, here are the results:

> microk8s kubectl -n openebs get pods -o wide
> NAME                                                              READY   STATUS    RESTARTS   AGE   IP               NODE           NOMINATED NODE   READINESS GATES
> openebs-ndm-d9sfv                                                 1/1     Running   1          17h   144.217.80.200   vps-77520b4d   <none>           <none>
> openebs-apiserver-79dc588cf4-tkwrz                                1/1     Running   2          17h   10.1.86.235      vps-77520b4d   <none>           <none>
> openebs-ndm-7kqzp                                                 1/1     Running   1          17h   144.217.83.34    vps-8ce42d42   <none>           <none>
> openebs-admission-server-66bf9476b4-62275                         1/1     Running   2          17h   10.1.89.244      vps-8ce42d42   <none>           <none>
> pvc-f3face35-3fbd-4e17-95d7-e28a65401ee6-ctrl-5464ddc4db-njgg4    2/2     Running   0          16h   10.1.89.248      vps-8ce42d42   <none>           <none>
> openebs-ndm-vfcpt                                                 1/1     Running   1          17h   192.99.151.87    vps-646c8993   <none>           <none>
> openebs-snapshot-operator-76b899b7c5-j4h52                        2/2     Running   4          17h   10.1.143.134     vps-646c8993   <none>           <none>
> pvc-f3face35-3fbd-4e17-95d7-e28a65401ee6-rep-1-69f7cddd46-6xklb   1/1     Running   2          16h   10.1.86.236      vps-77520b4d   <none>           <none>
> pvc-f3face35-3fbd-4e17-95d7-e28a65401ee6-rep-3-6f9cfd8999-2zzfg   1/1     Running   1          16h   10.1.143.178     vps-646c8993   <none>           <none>
> pvc-f3face35-3fbd-4e17-95d7-e28a65401ee6-rep-2-857778b545-rqpg8   1/1     Running   3          16h   10.1.89.239      vps-8ce42d42   <none>           <none>
> openebs-provisioner-855f4d7598-wz6kj                              1/1     Running   4          17h   10.1.143.182     vps-646c8993   <none>           <none>
> openebs-localpv-provisioner-696bb87896-98hlc                      1/1     Running   4          17h   10.1.143.151     vps-646c8993   <none>           <none>
> openebs-ndm-operator-7b6fc67b4b-rpg9d                             1/1     Running   2          17h   10.1.143.185     vps-646c8993   <none>           <none>

**Comment by balchua** [comment]
Ur right.  Openebs pods looks right to me.
Can you share your inspect tarball?
Thanks

**Comment by kzay** [comment]
Please find the microk8s inspect 

[inspection-report-20210705_213547.tar.gz](https://github.com/ubuntu/microk8s/files/6766254/inspection-report-20210705_213547.tar.gz)

**Comment by kzay** [comment]
I can also see that any blockdevice are created

> microk8s kubectl get blockdevice -n openebs
> No resources found in openebs namespace.

I'm using VPS and it have partition

> lsblk
> NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
> loop0     7:0    0  55.4M  1 loop /snap/core18/2066
> loop1     7:1    0  55.4M  1 loop /snap/core18/2074
> loop2     7:2    0  61.7M  1 loop /snap/core20/1026
> loop3     7:3    0  70.2M  1 loop /snap/lxd/20450
> loop4     7:4    0  66.4M  1 loop /snap/lxd/20840
> loop5     7:5    0 182.8M  1 loop /snap/microk8s/2262
> loop6     7:6    0  32.1M  1 loop /snap/snapd/11841
> loop7     7:7    0  32.3M  1 loop /snap/snapd/12398
> sda       8:0    0   160G  0 disk
> ├─sda1    8:1    0 159.9G  0 part /
> ├─sda14   8:14   0     4M  0 part
> └─sda15   8:15   0   106M  0 part /boot/efi

from openebs i can see this information

> From lsblk output check if the blockdevice you want to use is an LVM/software raid/ partition/LUKS filesystem. NDM currently does not support these types.

Maybe it can be the root cause? How i'm suppose to create them manualy

**Comment by balchua** [comment]
Im not an openebs expert, but the jiva store which you are using is not going to create a block device.

**Comment by kzay** [comment]
Its seems that the openebs NDM DaemonSet should create all the blockdevices.
But it seems to be excluded 

> osdiskexcludefilter.go:131] applying os-filter regex ^/dev/sda[0-9]*$ on /dev/sda1

**Comment by kzay** [comment]
> Im not an openebs expert, but the jiva store which you are using is not going to create a block device.

Maybe i'm going wrong in my investigation, i dont know how openebs and the kiva store should work. :,(

**Comment by balchua** [comment]
I couldn't find what is wrong.
Looking at the pv it looks like it is bound.

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS           REASON   AGE
pvc-f3face35-3fbd-4e17-95d7-e28a65401ee6   8Gi        RWO            Delete           Bound    spr/redis-data-redis-node-0   openebs-jiva-default            19h
```

**Comment by kzay** [comment]
Thanks @balchua , i havent change the iptable setup, its a fresh cluster installation. 

I will try to use iptables legacy and give you a feedback.

But if i look the changelogs the [1.21](https://microk8s.io/docs/release-notes) should support iptables-nft

**Comment by balchua** [comment]
Aaaa you are right.  Maybe its just the inspect is still using the legacy that's why it doesn't look like the usual content.

**Comment by kzay** [comment]
I saw this type of message on the node : Warning: iptables-legacy tables present, use iptables-legacy to see them, maybe its related to your comment

**Comment by BjoernPetersen** [comment]
I also tried to use the openebs addon on a cluster consisting of 3 VPS nodes. I encountered the exact same problem.

**Comment by faireai-fmonorchio** [comment]
Same problem here. Do you have info about how to resolve? thanks. any helm chart that use pvc do not start.

**Comment by NewMountain** [comment]
I'm in a similar situation. I have three nodes set up. Seems to be going reasonably well. Running MetalLB, works well. Cluster identifies as HA. 

All three nodes are set up in the same way. If I run lsblk on one of my nodes, I get:

```
nvme0n1     259:0    0   1.8T  0 disk 
├─nvme0n1p1 259:1    0   512M  0 part /boot/efi
├─nvme0n1p2 259:2    0 465.7G  0 part /
└─nvme0n1p3 259:3    0   1.4T  0 part 
```
so I have a block on each node ready to go.

When I use the command `k8 enable openebs`, 

I get the result:

```
Successfully installed OpenEBS.

Check the status by running: kubectl get pods -n openebs

The default values will install NDM and enable OpenEBS hostpath and device
storage engines along with their default StorageClasses. Use `kubectl get sc`
to see the list of installed OpenEBS StorageClasses.

**Note**: If you are upgrading from the older helm chart that was using cStor
and Jiva (non-csi) volumes, you will have to run the following command to include
the older provisioners:

helm upgrade openebs openebs/openebs \
	--namespace openebs \
	--set legacy.enabled=true \
	--reuse-values

For other engines, you will need to perform a few more additional steps to
enable the engine, configure the engines (e.g. creating pools) and create 
StorageClasses. 

For example, cStor can be enabled using commands like:

helm upgrade openebs openebs/openebs \
	--namespace openebs \
	--set cstor.enabled=true \
	--reuse-values

For more information, 
- view the online documentation at https://openebs.io/ or
- connect with an active community on Kubernetes slack #openebs channel.
OpenEBS is installed


-----------------------

When using OpenEBS with a single node MicroK8s, it is recommended to use the openebs-hostpath StorageClass
An example of creating a PersistentVolumeClaim utilizing the openebs-hostpath StorageClass


kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: local-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G



-----------------------

If you are planning to use OpenEBS with multi nodes, you can use the openebs-jiva-csi-default StorageClass.
An example of creating a PersistentVolumeClaim utilizing the openebs-jiva-csi-default StorageClass


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-volume-claim
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
```

I don't mean to criticize, but as a user, this is super confusing. Starting from the [OpenEBS Addon docs](https://microk8s.io/docs/addon-openebs), the only example shows 

```
The openebs-hostpath is recommended when using on a laptop or a single node cluster. Use openebs-jiva-default StorageClass for multi-node cluster.

Note: Using openebs-jiva-default requires to have 3 replicas.

Using OpenEBS is as easy as creating a PersistentVolumeClaim.

As an example:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
```

So according to openEBS docs, I should prefer `openebs-jiva-csi-default`. Based on various microk8s blog posts I found in researching this, I read I should strongly prefer cstor, so I followed the instruction provided in the above provided message to run: 

```
helm upgrade openebs openebs/openebs \
	--namespace openebs \
	--set cstor.enabled=true \
	--reuse-values
```

Trouble is, the helm ecosystem is basically non-functional at this point. I spent a solid hour trying to set up tiller only to eventually realize it was a dead end.

I can open up other tickets and am happy to help and debug. I suppose my questions are:

1. Would it be possible to show a working example of multi-node openebs in [the docs themselves](https://microk8s.io/docs/addon-openebs)
2. Is cstor possible to use? If so, can the output from `microk8s enable openebs` be updated to not advise folks to set up helm?

**Comment by keskival** [comment]
I made a report of the same issue here with more details of the root cause: https://github.com/canonical/microk8s/issues/3639
