### ISSUE TITLE
Can't access Kubeflow dashboard

### ISSUE THREAD

**Issue by ghost** [canonical/microk8s#2411]
Followed the instructions from here: https://charmed-kubeflow.io/docs/dashboard to open a new dashboard but keep getting "no address associated with hostname". I tried to restart and use .xip instead of .nip but it only gave me "temporary failure in name resolution". Thanks for the help!

[inspection-report-20210707_132431 (1).tar.gz](https://github.com/ubuntu/microk8s/files/6779426/inspection-report-20210707_132431.1.tar.gz)

**Comment by joedborg** [comment]
This might be better off raised over at https://github.com/canonical/bundle-kubeflow
