### ISSUE TITLE
microk8s leaking "containerd-shim <defunct>" processes

### ISSUE THREAD

**Issue by krichter722** [canonical/microk8s#2419]
I'm using microk8s on a slightly overwhelmed single-node setup for testing purposes. I'm observing an increase in tasks in `htop` which take up to 20GB RAM over 24h. I see around 5000 processes `containerd-shim <defunct>` after 24h and restarting microk8s with `microk8s.stop` and `microk8s.start` cleans everything up. I see

```
$ ps -A  | grep 'containerd-shim <defunct>' | wc --lines
5278
```
after 24h after a fresh install following `snap remove --purge microk8s` and installing different charts with around 60 pods in different namespaces. I'm very certain that they come from microk8s.

I installed software to make the cluster IPv6 ready with Calico following https://discuss.kubernetes.io/t/microk8s-ipv6-dualstack-how-to/14507.

I had some issues with very high probe failure counts similar to https://github.com/kubernetes/kubernetes/issues/89898 which I reduced by increasing failureThreshold and periodSecond of most probes. That seems to reduce the rate tasks are leaking. Still, I think the task leak shouldn't occur no matter what.

I'm experiencing this for weeks now with 1.21/stable (2262) and 1.21/edge (2296). I have to make some technical improvements to my setup and maybe even get some bug fixes to third party software released in order to make it work with Kubernetes 1.22, so please let me know if you deem it necessary to verify this issue with microk8s bleeding edge 1.22 - I understand, of course, if you do.

[inspection-report-20210711_151125.tar.gz](https://github.com/ubuntu/microk8s/files/6796969/inspection-report-20210711_151125.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @krichter722, 

Sorry for the late response.

Can you help me reproduce this issue? What steps do you follow to produce one such defunct process?

I see you have done some research on the issue as it is reported on docker/containerd too. On latest/edge we have upgraded containerd to v1.5.2, I would be grateful if you could try to reproduce this issue there as well.

Many thanks

**Comment by krichter722** [comment]
Hi @ktsakalozos, the issue no longer occurs with v1.21.3 (2337) from channel latest/edge. Thanks for the hint. I attached an inspection tarball of the running cluster after the upgrade with `snap refresh` in case you want to investigate further. `ps -A  | grep 'containerd-shim <defunct>' | wc --lines` shows `0` and it usually started showing >0 right after restarting `microk8s`.

The IPv6 setup and the high probe failure count outlined in the description are the only odd things on the cluster. A lot of pod are in CrashLoopBackoff with 100s of restarts over the past week. It's a mess. It's simply a too small server for a too high load. I don't do anything particular, just start the cluster, access the web frontend, make some REST calls to backend service. The processes just start piling up. The probe failure count remains high in 1.21.3 (2337), it's probably causes by an `overwhelmed sytemd-resolved` in conjunction with the DNS timeout issue linked in the description, but that's speculation as is the fact that the probe failures have anything to do with the defunct processes.

That being said, the setup worked fine with microk8s < 1.20 despite the lack of resources. I'm using 1.21 due to the possibility of IPv6 setup due to the insanely bad hardware from my ISP. I don't need to mention that I'm using microk8s is a non-professional hobbyist demo project.
