### ISSUE TITLE
microk8s high availability cluster on VPS hosting

### ISSUE THREAD

**Issue by jvalters** [canonical/microk8s#2453]
Hello, I know this will sound a bit fullish, but I would like to know is it possible and how to set up a high availability cluster on VPS hosting where externally each VPS has its own IP address if, for example, I use some load balancer or on one VPS NS1 and on Second VPS NS2 records or add 2 A records with different IP will it work?

Thanks.

**Comment by ktsakalozos** [comment]
A loadbalancer infront of the VPS would be preferable. you may however be able to use nodeport services [1] assuming your servers are reliable.


[1] https://kubernetes.io/docs/concepts/services-networking/service/
