### ISSUE TITLE
Juypter Server inaccessible

### ISSUE THREAD

**Issue by Dandevslack** [canonical/microk8s#2455]
The following steps were run to install kubeflow:
1. sudo snap install microk8s --classic (also tried with --classic --edge)
2. microk8s enable kubeflow --bundle=cs:kubeflow
3. added 3 additional nodes to the cluster
This step completed successfully. After receiving the login credentials and setting socks proxy, I was able to access the kubeflow dashboard.  All components appear to be working successfully with the exception of the notebook server.  When attempting to access the jupyter server, the following error is reported:
```{
  "log": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", 
  "status": 404, 
  "success": false, 
  "user": "admin"
}
```
All cluster nodes are running Ubuntu 20.04.  Inspection log is attached.  Thx :)
[inspection-report-20210721_110446.tar.gz](https://github.com/ubuntu/microk8s/files/6855110/inspection-report-20210721_110446.tar.gz)

**Comment by DomFleischmann** [comment]
Hey @Dandevslack we are aware of this issue and there is a discussion around it [here](https://github.com/canonical/bundle-kubeflow/issues/381)
