### ISSUE TITLE
Restarting a vm with microk8s erases data

### ISSUE THREAD

**Issue by tudor33sud** [canonical/microk8s#2472]
I have a question about the lifecycle of microk8s data. I use microk8s with kubeflow enabled, and I tried to upload a bunch of files in Minio and also add some kubeflow experiments.

I am able to consistently replicate that a vm reboot erases minio / kubeflow experiments data. Is this by design, or I messed something up at configuration level?

I would kindly request some assistance into how I could make minio / kubeflow data persistent, since my only input was microk8s enable kubeflow to get all of these.

![image](https://user-images.githubusercontent.com/8641630/126947917-ed3b2a32-5c0c-4b67-ac22-e5e12c546efc.png)
Attaching persistent volumes screenshot.

It seems like the dynamically created persistent volumes contain delete reclaim policy. I would like to know the best practice for keeping data intact, and also if there's any chance to configure persistent volumes size while enabling kubeflow, since I guess they use some defaults.

**Comment by polyedre** [comment]
As you detected it, the default microk8s storageclass `microk8s-hostpath`  has a reclaim policy set to `Delete`. I think that you can either [patch the storageclass](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/) or edit file  `/snap/microk8s/current/actions/storage.yaml` before enabling `kubeflow`.

**Comment by tudor33sud** [comment]
is there any example of how to do that? @polyedre  thanks for your response!

**Comment by polyedre** [comment]
Maybe the easiest way to do so in your case could be to modify the applied yaml file before enabling the plugin. For example with a `sed` ?

An alternative could be to add an argument to the plugin (as it is done with built-in registry: `microk8s enable registry:size=40Gi`).

Something like:

```
microk8s enable storage:reclaim_policy=persistent
```

**Comment by tudor33sud** [comment]
Thanks, we changed reclaim policy and everything was fine afterwards.
