### ISSUE TITLE
Pods fail to communicate with Apiserver on RHEL 8.4

### ISSUE THREAD

**Issue by polyedre** [canonical/microk8s#2473]
I tested Microk8s on multiples OS successfully (debian, centos7, centos8, RHEL7). When testing Microk8s with RHEL 8, the pods cannot communicate with the ApiServer.

Just after the installation, the pod `calico-kube-controllers` is in the state `CrashLoopBackOff`:

```
2021-07-26 09:28:34.764 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2021-07-26 09:28:44.765 [ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2021-07-26 09:28:44.765 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
```

To be sure that the error is not related to Calico, I disabled `ha-cluster`:

```sh
microk8s disable ha-cluster --force
```
Then I started CoreDNS:

```sh
microk8s enable dns
```
But the pod could not access the ApiServer:

```
E0726 10:03:40.941050       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I0726 10:03:40.941074       1 trace.go:205] Trace[939984059]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (26-Jul-2021 10:03:10.940) (total time: 30000ms):
Trace[939984059]: [30.000295724s] [30.000295724s] END
E0726 10:03:40.941098       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I0726 10:03:40.941205       1 trace.go:205] Trace[1474941318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (26-Jul-2021 10:03:10.940) (total time: 30000ms):
Trace[1474941318]: [30.000258176s] [30.000258176s] END
E0726 10:03:40.941217       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
```

I checked:
1. Advise from https://microk8s.io/docs/troubleshooting (especially "My pods can't reach the internet or each other (but my MicroK8s host machine can)...").
2. Firewalld is disabled.
3. When monitoring packets on the network interface of the CoreDNS pod, I can see periodically 3 packets from the pod to 10.152.183.1, but no response (this explains the "timeout").
4. When inspecting iptables rules, I managed to log the packets before they are DNATed, but after I was not able to distinguish them from other packets (between apiserver and controller, scheduler, etc...).

With microk8s v1.20, I was able to switch proxy mode to "userspace" and get a working cluster.

The problem seems linked with iptables but when comparing the rules with a working cluster (ubuntu 20.04), I could not see any difference.

Could you please advise me what to verify ?

Here is my inspection tarball:

[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/6877432/inspection-report.tar.gz)

**Comment by rpulijala** [comment]
In my case for a similar issue in RHEL 8.4 with `firewalld` enabled, I had to add these rules

```
        sudo firewall-cmd --permanent --add-port={16443,10250,10255,25000,12379,10257,10259,32000}/tcp
        sudo firewall-cmd --permanent --add-port=19001/udp
        sudo firewall-cmd --add-masquerade --permanent
        sudo firewall-cmd --reload
        sudo systemctl restart firewalld
```

got the ports from https://microk8s.io/docs/services-and-ports

**Comment by polyedre** [comment]
Thank you for responding. As mentioned before, I checked that Firewalld was disabled. When testing on Centos, it seemed to me that the only rule needed is the masquerade rule.

I will try to enable firewalld and use the rules you suggested.

**Comment by polyedre** [comment]
I tried it without any result.

**Comment by romeroyonatan** [comment]
Hey, I am facing the same issue. Please check if this work :slightly_smiling_face: 


https://github.com/canonical/microk8s/issues/3085#issuecomment-1110915801
