### ISSUE TITLE
Registry on ha-cluster and OpenEBS

### ISSUE THREAD

**Issue by turowicz** [canonical/microk8s#2481]
If I turn on ha-cluster and openebs, how can I tell the registry addon to use the `jiva` storage class?

**Comment by balasu** [comment]
Hi
I assume you are using microk8s1.21 build-in registry with microk8s enable registry. I am afraid builtin registry doesn't have the feasibility to use specific storage class. however it will use default storage class, pl confirm if the  default  storageclass is openebs-jiva-default .
microk8s kubectl get sc will return value like openebs-jiva-default (default)  . 
pl describe openebs jiva pod and check for this annotation on all nodes
"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}

**Comment by turowicz** [comment]
Seems like hostpath is the default @balasu 

![image](https://user-images.githubusercontent.com/1055391/127451286-578f336a-fe50-4f61-868a-38f714875c01.png)

**Comment by turowicz** [comment]
So I should be able to modify the annotations to make this work?

**Comment by balchua** [comment]
Yes, but you need to delete the container-registry after patching the default storage.
