### ISSUE TITLE
Logs of pods with "high bursts" of logs don't get processed properly

### ISSUE THREAD

**Issue by tsipo** [canonical/microk8s#2482]
Hi there,

We noticed that pods with "high bursts" of logs don't get their logs processed properly by microk8s whereas pods with "normal" throughput of logs do get their log processed.
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+860b3c46169b29", GitCommit:"860b3c46169b29e636f5b81a763dd097eb8a3fc3", GitTreeState:"clean", BuildDate:"2021-07-23T14:59:16Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-3+860b3c46169b29", GitCommit:"860b3c46169b29e636f5b81a763dd097eb8a3fc3", GitTreeState:"clean", BuildDate:"2021-07-23T14:56:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
Our use-case is as follows: we have some non-k8s components which generate logs. We have Splunk deployed to scrape all pods logs, so to cater for the non-k8s logs we have added a deployment of a new pod. This pod uses a volume, to which the log files are being uploaded (in zip files which include multiple logs each). The pod has a simple alpine-based image with unzip package installed and a shell script which loops over all log files in the uploaded zip, runs them through a _sed_ script and pipe the output to **/proc/1/fd/1**. After processing, the zip file is moved to another folder, to prevent re-processing.
Something like:
```
while true; do
  for file in $LOG_UPLOAD_FOLDER/*.zip; do
      if [ -f "$file" ]; then
          echo "----- START - extract of $file -----" >>/proc/1/fd/1
          logFiles=$(unzip -Z1 "$file" '*pattern*.log')
          for logF in $logFiles; do
              # translate backslashes to slashes in case zip was generated on Windows
              logFile=$(echo "$logF" | sed 's<\\</<g')
	      echo "Start $logFile... - $file" >>/proc/1/fd/1
	      unzip -j -p "$logFile" | sed "${SED_SCRIPT}" >>/proc/1/fd/1
	      echo "End $logFile... - $file" >>/proc/1/fd/1
          done
          filename=$(basename "$file" .zip)
          newfilename="$filename-"$(date +"%Y%m%d%H%M%S").zip
          mv "$file" "$PROCESSED_LOG_FOLDER/$newfilename" 2>/dev/null
          echo "Moved - $file to $PROCESSED_LOG_FOLDER/$newfilename" >>/proc/1/fd/1
          echo "----- END - extract of $file -----" >>/proc/1/fd/1
      fi
  done
  sleep 300
done
```
We have tested this pod on the following k8s distros:
1. AWS EKS clusters
2. Native k8s installed on Linux Mint
3. Docker for Windows k8s
4. microk8s v1.21.3-3+860b3c46169b29 on Ubuntu 20.04

On distros 1)-3) we could obtain the logs using simple `kubectl logs -n <namespace> <pod>` - no problem.
On microk8s we noticed the following:
a) If the zip file contains rather small log files (e.g. 1 log file of ~20KB, ~200 lines) - no problem. `microk8s.kubectl logs` shows the logs.
b) However, the zip file typically includes multiple files of around 10MB each. In this case, `microk8s.kubectl` logs did not show ANYTHING.

Investigating the log files under `/var/log/pods/<namespace>_<pod>_.../<container_name>` showed the following:
a) In the case of a zip file containing a small log file (~20KB), we see the file 0.log (which is used by `kubectl logs`) like one normally sees:
```
-rw-r----- 1 root root 33130 Jul 28 13:38 0.log
```
b1) In the case of a zip file containing ONE 10MB log file, after processing we see this:
```
-rw-r----- 1 root root        0 Jul 28 10:47 0.log
-rw-r----- 1 root root 12656352 Jul 28 10:46 0.log.20210728-104601
```
the log is written by microk8s to `0.log.yyyMMdd-HHmmss`, not to 0.log. It is therefore not shown by `kubectl logs`. Even waiting 15 minutes doesn't help.

b2) Then we dropped the same zip file of ONE 10MB log file again. After it was processed we see this:
```
-rw-r----- 1 root root        0 Jul 28 10:56 0.log
-rw-r--r-- 1 root root   842313 Jul 28 10:56 0.log.20210728-104601.gz
-rw-r----- 1 root root 12656352 Jul 28 10:55 0.log.20210728-105601
```
--> Previous file is gzipped, new file is created with its own 0.log.yyyMMdd-HHmmss.

b3) Again we dropped the same zip file of ONE 10MB log file again. After it was processed we see the same results:
```
-rw-r----- 1 root root        0 Jul 28 11:16 0.log
-rw-r--r-- 1 root root   842313 Jul 28 10:56 0.log.20210728-104601.gz
-rw-r--r-- 1 root root   842763 Jul 28 11:16 0.log.20210728-105601.gz
-rw-r----- 1 root root 12656340 Jul 28 11:15 0.log.20210728-111602
```
All this time, 0.log is not updated and `kubectl logs` doesn't show anything. Shelling into the pod and running
``` 
echo Hello World >>/proc/1/fd/1
```
does end up in 0.log (and `kubectl logs`).

Again, this behaviour is observed ONLY with microk8s and only with high log bursts. Please advise.

**Comment by balchua** [comment]
You can try tweaking the file `/var/snap/microk8s/args/kubelet` and add these

```
--container-log-max-size
```
This one defaults to 10MB according to kubelet docs.
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

Maybe this can help.  Let us know.  I have tried this personally

**Comment by tsipo** [comment]
Thanks @balchua it was indeed the container max log size. Bumping it up to 100MB or so "resolved" it. But this raises another question: isn't **kubectl logs** supposed to go over also the log-rotated gz files? We have here a strange situation, where the container emits (in a rather short period of time) logs which go over the 10MB, get rotated immediately and never show in a **kubectl logs** command. Also, is bumping up this setting up not only "deferring an execution" - i.e. what will happen when we go over the 100MB limit - wouldn't that be the same? Thanks!

**Comment by balchua** [comment]
Don't have a good answer to that but as far as i know it tries to keep only that size defined by that args and not the entire logs.  

Maybe using those `kubectl logs` args like `--since` will allow it to go thru the `gz` files.
