### ISSUE TITLE
MIcrok8s Error "Node NotReady"

### ISSUE THREAD

**Issue by falgifaisal** [canonical/microk8s#2487]
Hi,

I have an issue. Microk8s shows an error "Node NotReady" today.
A couple days ago, i also face the same problem, so i decided to reinstall microk8s.
But why today the error is happening again ?

I run microk8s v1.20.9 with single node.

Here is the result of microk8s inspect

[inspection-report-20210802_084856.tar.gz](https://github.com/ubuntu/microk8s/files/6913931/inspection-report-20210802_084856.tar.gz)

**Comment by balchua** [comment]
Thanks @falgifaisal for logging this issue.
Just checking, you have your `/var/snap/microk8s/` directory on a fast storage right?

@ktsakalozos @mathieubordere
Any idea how this can happen?

```
Aug 02 08:17:25 soetomodb2 microk8s.daemon-apiserver[15684]: kube-apiserver: src/unix/poll.c:109: uv_poll_stop: Assertion `!uv__is_closing(handle)' failed.
Aug 02 08:17:26 soetomodb2 systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=6/ABRT
```

**Comment by MathieuBordere** [comment]
Looks like the `libuv` API is misused somehow, let me check how that can happen.

**Comment by falgifaisal** [comment]
> Thanks @falgifaisal for logging this issue.
> Just checking, you have your `/var/snap/microk8s/` directory on a fast storage right?

Yes, it's on a fast storage. Is the error related with the storage ?

> 
> @ktsakalozos @MathieuBordere
> Any idea how this can happen?
> 
> ```
> Aug 02 08:17:25 soetomodb2 microk8s.daemon-apiserver[15684]: kube-apiserver: src/unix/poll.c:109: uv_poll_stop: Assertion `!uv__is_closing(handle)' failed.
> Aug 02 08:17:26 soetomodb2 systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=6/ABRT
> ```

**Comment by balchua** [comment]
@falgifaisal don't know if it is related to storage.  I was just asking, hoping it may ahed some light on why the error occurred.

**Comment by falgifaisal** [comment]
> @falgifaisal don't know if it is related to storage. I was just asking, hoping it may ahed some light on why the error occurred.

Okay, thank you. I also still wonder for the cause and how to prevent it

**Comment by ktsakalozos** [comment]
@falgifaisal did the node recover after some minutes or is it still "Not Ready"?

**Comment by falgifaisal** [comment]
> @falgifaisal did the node recover after some minutes or is it still "Not Ready"?

No, it still "Not Ready"
But if i restart microk8s, sometimes it will fix the problem but sometimes i need to reinstall it to fix the problem.
But even though it's been reinstalled, the error will still appear in the future.
