### ISSUE TITLE
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

### ISSUE THREAD

**Issue by a1exus** [canonical/microk8s#249]
Hello,

Trying to [quick-start](https://microk8s.io/#quick-start) microk8s, yet running into following error:

```
toor@suey:~$ sudo snap install microk8s --classic
[sudo] password for toor: 
microk8s v1.13.0 from Canonical✓ installed
toor@suey:~$ sudo microk8s.start
sudo: microk8s.start: command not found
toor@suey:~$ microk8s.kubectl get all --all-namespaces
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
toor@suey:~$ sudo snap refresh --channel=latest/beta microk8s
microk8s (beta) v1.13.1 from Canonical✓ refreshed
Channel latest/beta for microk8s is closed; temporarily forwarding to beta.
toor@suey:~$ microk8s.kubectl get all --all-namespaces
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
toor@suey:~$ microk8s.inspect
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
toor@suey:~$ sudo microk8s.kubectl get all --all-namespaces
sudo: microk8s.kubectl: command not found
toor@suey:~$ 
```

Please advise.

**Comment by ktsakalozos** [comment]
Hi @a1exus ,

This error seems to be related to snapd. What distribution are you using? Looking at this https://forum.snapcraft.io/t/snap-confine-has-elevated-permissions-error/2391/3 , Is it possible you are not running the default kernel?

Thanks

**Comment by a1exus** [comment]
@ktsakalozos thank you for your response, I'm running default kernel that came with distro:

```
toor@suey:~$ cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
toor@suey:~$ 
toor@suey:~$ uname -a
Linux suey.nknwn.local 4.18.0-kali3-amd64 #1 SMP Debian 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux
toor@suey:~$ 
```

**Comment by xOrMalware** [comment]
I am experiencing the same problem. But I would like to give a little bit more information. I am using trying to use Bitwarden.

If I install snapd. reboot, start snap service, reboot, install bit warden. I can get bitwarden to run. However, if I reboot, then try to run bitwarden, I get the error snap-confine has elevated permissions.

So I am not convinced this is as simple as a kernel issue, as I am surprised, I was able to get the app to run at all.

but uname -a

Linux Kernel 4.19.0-kali4-amd64 …..

**Comment by ktsakalozos** [comment]
Hi,

This has to be reported to the snapcraft team possibly at
https://forum.snapcraft.io/t/snap-confine-has-elevated-permissions-error/2391
or
on a new topic. This is out of my hands. I am sorry.

**Comment by byionline** [comment]
1. Check if snap core is not broken
`$ snap list`
2. Update the following package
A. apparmor 
`$ sudo apt-get install apparmor`

Now heroku will work.
`$ heroku`

Also restart the snapd.service after reboot if heroku gives following error:

internal error, please report: running "heroku" failed: timeout waiting for snap system profiles to get updated

`$ sudo systemctl restart snapd.service`

**Comment by RealJTG** [comment]
The same error occurs if apparmor service stopped or disabled.

**Comment by ktsakalozos** [comment]
Please report this issue to `https://forum.snapcraft.io`. Thank you.

**Comment by dxas90** [comment]
@a1exus 
you can also fix it with
```bash
sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
```

**Comment by SukiCZ** [comment]
```
sudo systemctl enable --now apparmor.service
```
fixed the issue for me. Asked for password once :tongue:

**Comment by Maidomax** [comment]
> @a1exus
> you can also fix it with
> 
> ```shell
> sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> ```

This works for me, but I have to do it after every reboot

**Comment by ahmedmahershaaban** [comment]
> According to the conversation in [[Ubuntu Forum](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1803476)], [this](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1803476/comments/16) particular answer, fixed my problem.
> 
> So, just install `apparmor` if don't have it already, and then enable it by:
> `systemctl enable --now apparmor.service`
> 
> **Note:** For some reasons, it asks for password multiple times. In my case, 5 times!! Don't give up! :)

fixed my problem thanks  ^_^

**Comment by HassanAmed** [comment]
> @a1exus
> you can also fix it with
> 
> ```shell
> sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> ```

@dxas90  after running this I got
 ```cannot change profile for the next exec call: No such file or directory```
trying to up docker containers.

**Comment by krupalraj** [comment]
> @a1exus
> you can also fix it with
> 
> ```shell
> sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> ```

this worked for me ..thanks !!

**Comment by NickWilde263** [comment]
> The same error occurs if apparmor service stopped or disabled.

true

**Comment by tarzq306** [comment]
> @a1exus
> you can also fix it with
> 
> ```shell
> sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> ```

This is work great for me. Thanks

**Comment by NickWilde263** [comment]
i do `sudo systemctl start apparmor`
try that before you do the `sudo apparmor_parser` commands

**Comment by rajdip-b** [comment]
Also check if your snapd service is running or not.

**Comment by blessedjasonmwanza** [comment]
**This worked for my Kali Linux destro (Debian). It might work for you as well. Remember default snap that comes with the OS has this issue in most destros**
> First, try uninstalling _snap_ and _snapd_ and then, resinstalling them back
>This should fix it;
```shell
sudo apt remove snap && sudo apt remove snapd
# or
sudo apt remove snap
# and when its done, run
sudo apt remove snapd
```

**Comment by NickWilde263** [comment]
> **This worked for my Kali Linux destro (Debian). It might work for you as well. Remember default snap that comes with the OS has this issue in most destros**
> 
> > First, try uninstalling _snap_ and _snapd_ and then, resinstalling them back
> > This should fix it;
> 
> ```shell
> sudo apt remove snap && sudo apt remove snapd
> # or
> sudo apt remove snap
> # and when its done, run
> sudo apt remove snapd
> ```

```sh
# Much simpler this way
# Apt have reinstall command
sudo apt reinstall snap snapd
```

**Comment by c4tom** [comment]
> ```shell
> sudo apt reinstall snap snapd
> ```

I've already done this, but when I restart linux, the problem comes back.

```
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma
```

**Comment by gcngov** [comment]
> @a1exus
> you can also fix it with
> 
> ```shell
> sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> ```

It work on kali linux. Thank you @a1exus

**Comment by NickWilde263** [comment]
> > ```shell
> > sudo apt reinstall snap snapd
> > ```
> 
> I've already done this, but when I restart linux, the problem comes back.
> 
> ```
> LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
> Distributor ID:	Linuxmint
> Description:	Linux Mint 20.2
> Release:	20.2
> Codename:	uma
> ```

do other solution works?

**Comment by sv-atoslav** [comment]
> > `sudo apt reinstall snap snapd`
> I've already done this, but when I restart linux, the problem comes back.

I write a script, that run after login. Hope it can be useful for someone else:

```
# fix snap
apt purge snap snapd
apt install snap snapd
systemctl restart snapd.service
# systemctl enable snapd.service # I delete snap again after every login
# install apps
declare -a SnapList=(
	"pycharm-community --classic"
	"telegram-desktop"
	"bitwarden"
	...
	# enumerate YOUR snaps here
)
for package in "${SnapList[@]}";do
	snap install $package
done
```
and add to `~/.bashrc` this line
`export PATH="$PATH:/snap/bin/"`

I run whole script with `sudo` permissions.

**Comment by serigne-moustapha-sy-ndoye** [comment]
Thanks all for help !

**Comment by alexis-evelyn** [comment]
> kali

![Screenshot_20211202_220828](https://user-images.githubusercontent.com/6305346/144538585-9327bc7b-d555-4918-9e2c-ddd19f6bc726.png)

The minimum number of files needed to have their definitions replaced (at least on Kali) is:

```zsh
# Generic
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-update-ns.*
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.*
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine.snapd.14066

# Example For Discord
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-update-ns.discord
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap.discord.discord
sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine.snapd.14066
```

The real question is, how do I get it to stay fixed across reboots and how do I do this without requiring root privileges?

**Comment by alexis-evelyn** [comment]
I'm digging more into apparmor. It appears at least for Kali, the profiles are not loaded at all. When running the replace command, the profiles will be added in enforce mode. I'll have to update if I figure out how to get the profiles to be loaded on boot (and without pulling sudo shenanigans with .zshrc or anything.

**Comment by alexis-evelyn** [comment]
This file might have some promise on getting snapd profiles to load on boot.

![Screenshot_20211203_001846](https://user-images.githubusercontent.com/6305346/144549656-ffb2b72e-ac43-4165-a60d-
bf2c513216df.png)

**Comment by alexis-evelyn** [comment]
Yep, that did it. Open `/lib/apparmor/rc.apparmor.functions` and look for the line `ADDITIONAL_PROFILE_DIR=` and paste your snapd profile directory into that line. For me, the profile directory was `/var/lib/snapd/apparmor/profiles/`.

![Screenshot_20211203_002311](https://user-images.githubusercontent.com/6305346/144550082-cd0b798c-a2be-4b1e-8a12-d6fcbea6b5b8.png)

**Comment by shdennlin** [comment]
@alexis-evelyn Tanks, I also use kali linux and have the same error, and your answer solves my problem.

**Comment by rangersmyth74** [comment]
Thank you all for all the different answers, and after doing many of the above tasks I was able to get pyradio working. For today anyway I am able to run Cointop without any error! This is great as I had to reinstall it every time to get it to work.

**Comment by wexterhack** [comment]
> > @a1exus
> > you can also fix it with
> > ```shell
> > sudo apparmor_parser -r /etc/apparmor.d/*snap-confine*
> > sudo apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine*
> > ```
> 
> @dxas90 after running this I got `cannot change profile for the next exec call: No such file or directory` trying to up docker containers.

```shell
> > sudo apt install apparmor-utils apparmor-profiles
> > sudo apparmor_parser --add /var/lib/snapd/apparmor/profiles/snap.mirok8s.*
```

**Comment by Foorack** [comment]
Having a reoccurance of this issue now. Running the two "apparmor"-commands fixes it temporarily, but the issue comes back after reboot. Several machines impacted simultaniously.

**Comment by davidshare** [comment]
I have tried almost everything here, but I am stuck with the error:

```
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
Please make sure that the snapd.apparmor service is enabled and started.
```
