### ISSUE TITLE
Microk8s install - fails if 'stealth mode' enabled in Firewall

### ISSUE THREAD

**Issue by planetf1** [canonical/microk8s#2509]
when following the installation process for MacOS, the following command fails:
```
$ microk8s install                                                                                                                  [15:59:25]
Launched: microk8s-vm
ping: snapcraft.io: Temporary failure in name resolution
An error occurred when trying to execute 'sudo ping -c 1 snapcraft.io' with 'multipass': returned exit code 2.
```
This happened on two separate installs of macOS (one was corporate managed Big Sur 11.5.1, the other a standalone unmanaged install of Monterey beta)

After some investigation it appears the cause is 'Stealth mode' in the MacOS firewall.

The fix to this is Before installing, go into System Preferences->Security & Privacy. Click the lock to get into Admin mode. Then ensure Firewall Options->Enable Stealth Mode is NOT enabled (no tick).

The install will then work (I did a microk8s uninstall beforehand to keep things clean)

Since the docs at https://microk8s.io try and make it easy to get k8s up and running, I think there needs to be some handling of this condition, or a clear reference in the docs. Perhaps the install could do a check for the failing condition locally on macOS before starting the install, or the error could provide a link with PD information. Also there may be more fine grained approaches other than simply turning off stealth mode.

**Comment by balchua** [comment]
Cc @joedborg

**Comment by denispolish** [comment]
I'm having the same issue on my mac (Sonoma  v. 14.3.1 (23D60)) with microk8s  version 2.3.4
