### ISSUE TITLE
Microk8s breaks routing on specific node when joining cluster

### ISSUE THREAD

**Issue by dza89** [canonical/microk8s#2510]
Running ubuntu 20.04 with microk8s 1.22 (also tried 1.21) on an RPI4. Running a cluster on two other x86 nodes.
I'm using a local dns server at 192.168.178.3 which is a loadbalancer provided by metallb.

Microk8s running everything is fine as a single instance.
Whenever i perform a join of the other two nodes, the following happens:
```
nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   google.com
Address: 142.250.184.238
Name:   google.com
Address: 2a00:1450:4001:82f::200e
```

A few moments later it's unable to reach the loadbalancer:
```
nslookup google.com 
;; connection timed out; no servers could be reached
```

When i do a dig and a tcpdump at the same time:
```
tcpdump -n -i eth0  host 192.168.178.3 -v
dig @192.168.178.3 google.com
```
I do not see any output under tcpdump; no traffic is actually leaving the machine.
Pinging the machine works and generates output at tcpdump.

Further:
- I can't generate a tarball on that machine because it hangs on `Inspect kubernetes cluster`, probably because it can't reach something online. (?)
- I can access any other machine using curl in and outside of my network from my RPI.
- I can access my dns server using any other machine inside my network.
- When I use `microk8s leave` dns works again.

**Comment by ktsakalozos** [comment]
@dza89 the nodes are on the same subnet as the dns service (`192.168.178.x`) ?

**Comment by dza89** [comment]
@ktsakalozos yes, all on the same subnet.
