### ISSUE TITLE
How to add worker node in microk8s

### ISSUE THREAD

**Issue by falgifaisal** [canonical/microk8s#2512]
Hi,

From this link https://microk8s.io/docs/high-availability, what i understand is about create multi master node (please correct me if i wrong)
So, how to add worker node in microk8s cluster ?

**Comment by balchua** [comment]
@falgifaisal currently there is no "worker" node option in microk8s.   I wrote some instructions on how to achieve this.  But its brutally manual.
https://discuss.kubernetes.io/t/adding-a-worker-node-only-with-microk8s/14801
I also know here is ongoing discussion on this too.
@ktsakalozos

**Comment by falgifaisal** [comment]
> @falgifaisal currently there is no "worker" node option in microk8s. I wrote some instructions on how to achieve this. But its brutally manual.
> https://discuss.kubernetes.io/t/adding-a-worker-node-only-with-microk8s/14801

Thank you for the answer, i will check it.

> I also know here is ongoing discussion on this too.
> @ktsakalozos
