### ISSUE TITLE
Microk8s snapctl error access denied

### ISSUE THREAD

**Issue by poropeked** [canonical/microk8s#2513]
When enabling the plugin microk8s.enable rbac, an error occurs:

Enabling RBAC
Reconfiguring apiserver
error: access denied
Failed to enable rbac

it is related to old snapd deb 2.21 and snapctl utility
This error was reported in the bug tracker https://bugs.launchpad.net/snapd/+bug/1933392

dpkg -l | grep snapd
ii  snapd                                 2.21-2+b1

snap list
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.51.1  11316  -              canonical✓  core
microk8s  v1.19.11   2263   -              canonical✓  classic
snapd     2.51.3     12704  latest/stable  canonical✓  snapd

[inspection-report-20210803_181747.tar.gz](https://github.com/ubuntu/microk8s/files/6962222/inspection-report-20210803_181747.tar.gz)

**Comment by poropeked** [comment]
snap list
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.51.1  11316  -              canonical✓  core
microk8s  v1.19.11   2263   -              canonical✓  classic
snapd     2.51.3     12704  latest/stable  canonical✓  snapd

**Comment by ktsakalozos** [comment]
Thank you for reporting this @poropeked while we figure out what to do for the snapd issue, let me try to offer a workaround.

The enable rbac script [1] just adds an argument in the apiserver and then restarts it. I think the restart is failing due to the bug you reported. Can you make sure `/var/snap/microk8s/current/args/kube-apiserver` has the argument `--authorization-mode RBAC,Node` and then do a `microk8s stop; microk8s start;` ?

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.rbac.sh

**Comment by poropeked** [comment]
> Thank you for reporting this @poropeked while we figure out what to do for the snapd issue, let me try to offer a workaround.
> 
> The enable rbac script [1] just adds an argument in the apiserver and then restarts it. I think the restart is failing due to the bug you reported. Can you make sure `/var/snap/microk8s/current/args/kube-apiserver` has the argument `--authorization-mode RBAC,Node` and then do a `microk8s stop; microk8s start;` ?
> 
> [1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.rbac.sh

**Comment by poropeked** [comment]
As a temporary solution, after restarting this service, the addon will turn on!
systemctl restart snap.microk8s.daemon-apiserver-kicker.service

**Comment by ktsakalozos** [comment]
Here is a cleaner workaround that would not require restarts.

We know the snapctl that comes with the deb package is outdated and we should be using the one from the core snap so first install the core snap, remove the old snapctl and create a symlink to the new snapctl.
```
sudo snap install core
sudo mv /usr/bin/snapctl /usr/bin/snapctl.old
sudo ln -s  /snap/core/current/usr/bin/snapctl /usr/bin/snapctl
```

**Comment by poropeked** [comment]
> Вот более чистый обходной путь, который не потребует перезапуска.
> 
> Мы знаем, что snapctl, поставляемый с пакетом deb, устарел, и мы должны использовать тот, который находится в основной оснастке, поэтому сначала установите базовую привязку, удалите старый snapctl и создайте символическую ссылку на новый snapctl.
> 
> ```
> sudo snap install core
> sudo mv /usr/bin/snapctl /usr/bin/snapctl.old
> sudo ln -s  /snap/core/current/usr/bin/snapctl /usr/bin/snapctl
> ```

Thanks, this solution suits me better!
