### ISSUE TITLE
HA Production "ready"

### ISSUE THREAD

**Issue by lfdominguez** [canonical/microk8s#2515]
Hi, i have used microk8s 1.19 and 1.20 with 3 and 10 hosts, i don't do any exceptional thing to use it but if i read on the microk8s site, microk8s is a production-grade and supports HA with dqlite, but (this things are experiences using it):

*  One of my nodes has network intermittent issues and the cluster break, i tried to force delete the node but the cluster never get stable again, i was waiting that dqlite supports this, but at the end the cluster get inconsistent, for example, if i list the daemonset, calico are showing that 3 pods are running and ready, but when list the pods, it's never appear, so the information on database was completely inconsistent, that's why i say about dqlite.

* One of the HA things that i expect is that if a node lost the connection, the theory is that dqlite select another master and all come to stable again, my experience with this was bad, lost a node and all the cluster get inconsistent like the first point.

The thing is that never i get a real HA recover from a issue, so how is tested this HA things of microk8s??? Sorry now i moved to rke2 with embedded etcd and tested the network issues, the lost of a node and everything works, the cluster come to stable again....

**Comment by ktsakalozos** [comment]
Hi @lfdominguez, I am sorry to see you leave and I appreciate letting us know the reasons.

The case you describe should be handled. Can you extend on two points that would help me reproduce the issue?

 * How can I simulate a node is lost? You perform a forced power off not leaving any time for the cluster to do a graceful shutdown? 
 * What workloads do you have? Anything special I should be aware of?

Thank you.

**Comment by lfdominguez** [comment]
Thanks for response, really i liked microk8s (the snap autorefresh is insane but i worked with the `download` and `install --dangerous` jeje). The simulation is removing completly a node (are VMs), but this was for rke2, for microk8s was in production, on hetznet cloud, their lost the connection to one of the DC and then i lost the network with one of the nodes and the cluster get inconsistent.
The real thing is that the cluster get running, but, the information showed by kubectl was wrong, like i say, for example, if you show the deployments or daemonsets, they show the RUNNING and READY columns as the pods was running, but if you get the pods, where is not there because i need to delete because lost, is like the information get from dqlite was wrong or something else. A real example, i found an screenshoot that i take:
![image](https://user-images.githubusercontent.com/5604131/129036148-3e2295c2-e87e-49f7-a0a3-5b65cb3e6cdf.png)
you can see there how the ingress ds is with 1 and there 3 pods "running" (really there is nothing running when i use `ctr` to show containers running in containerd), and the calico ds show 3 running, but there is not calico pods. How one can solve this in this situation? if we can solve or known how to solve this i can go back, really i like the microk8s.

**Comment by lfdominguez** [comment]
Because that behavior is that if you remove for example, all the ingress, is never redeploy because the deployment or ds show has is deployed.
