### ISSUE TITLE
CIS compliance

### ISSUE THREAD

**Issue by JesperBerggren** [canonical/microk8s#2517]
Hello,

**Summary of issue:**
Microk8s is pretty far from CIS compliant although claiming to be production ready. Many/most issues should be fixed in the default installation. The rest are of course for us to configure as required.

**Current situation:**
We're getting close to production date with our new Kubernetes clusters, which are based on Microk8s.

Currently we're working on protecting/hardening the installations according to the CIS benchmark: https://github.com/aquasecurity/kube-bench/

Microk8s claims to be a production ready Kubernetes cluster but looking at the scoring in the benchmark we're currently quite concerned if it can be sufficiently protected to actually work in a serious production environment.

This repository shows the all the security issues quite well: https://github.com/didier-durand/microk8s-kube-bench
> == Summary total ==
> 33 checks PASS
> 36 checks FAIL
> 46 checks WARN
> 0 checks INFO

On our clusters the summaries are even worse with more failures, which is perhaps because we're running the benchmark tool from command line:

As stated we're trying to mitigate all these issues but many/most of them really should just be fixed by the default installation.

**Question 1**: Is there any work in progress to be more CIS compliant?
If not, this should be a major concern for anyone using this for production.

**Question 2:** What will happen when snap updates the installation with a new version. 
Will all the manual changes in configuration files under: /var/snap/microk8s/current/args/ be merged with the new version or will they be lost?

Best regards
Jesper Berggren

**Comment by ktsakalozos** [comment]
Hi @JesperBerggren 

Thank you for bringing this up. We are always interested in hardening MicroK8s.

Any change you do under `/var/snap/microk8s/current/args` will not be affected by any future snap refreshes. In a production environment, you may also want to schedule the time when refreshes will reach you [1] and/or use a snapstore proxy [2] to test filter snap revisions. You could also consider proposing changes on the default arguments so you get them out of the box in upcoming releases. The default arguments we ship with are in [3].

A number of the CIS recommendations can be handled via cluster configuration. Would you be interested in discussing any specific configuration?

Thanks

[1] https://snapcraft.io/docs/keeping-snaps-up-to-date?&_ga=2.239360900.645980766.1628842290-826334627.1586932956#heading--controlling-updates
[2] https://docs.ubuntu.com/snap-store-proxy/en/
[3] https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/default-args

**Comment by JesperBerggren** [comment]
Hi again and sorry for the long delay in answering - I've been hung up on other issues.

I'm definitely interested in discussing specific configurations. At the very least all the configuration that will not be retained across snap updates.

I'm running the CIS benchmark and slowly hardening as required, so for now my list of suggested updates is not complete! More will follow :-)

Initially I think the following tests should be addressed:
```
[INFO] 1 Master Node Security Configuration
[INFO] 1.1 Master Node Configuration Files
[FAIL] 1.1.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.2 Ensure that the API server pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.4 Ensure that the controller manager pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.6 Ensure that the scheduler pod specification file ownership is set to root:root (Automated)
[FAIL] 1.1.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.8 Ensure that the etcd pod specification file ownership is set to root:root (Automated)
[WARN] 1.1.9 Ensure that the Container Network Interface file permissions are set to 644 or more restrictive (Manual)
[WARN] 1.1.10 Ensure that the Container Network Interface file ownership is set to root:root (Manual)
[FAIL] 1.1.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Automated)
[FAIL] 1.1.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Automated)
[FAIL] 1.1.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.14 Ensure that the admin.conf file ownership is set to root:root (Automated)
[FAIL] 1.1.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.16 Ensure that the scheduler.conf file ownership is set to root:root (Automated)
[FAIL] 1.1.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Automated)
[FAIL] 1.1.18 Ensure that the controller-manager.conf file ownership is set to root:root (Automated)
[FAIL] 1.1.19 Ensure that the Kubernetes PKI directory and file ownership is set to root:root (Automated)
[WARN] 1.1.20 Ensure that the Kubernetes PKI certificate file permissions are set to 644 or more restrictive (Manual)
[WARN] 1.1.21 Ensure that the Kubernetes PKI key file permissions are set to 600 (Manual)

...

== Remediations master ==
1.1.1 Run the below command (based on the file location on your system) on the
master node.
For example, chmod 644 /var/snap/microk8s/current/args/kube-apiserver

1.1.2 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/args/kube-apiserver

1.1.3 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /var/snap/microk8s/current/args/kube-controller-manager

1.1.4 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/args/kube-controller-manager

1.1.5 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /var/snap/microk8s/current/args/kube-scheduler

1.1.6 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/args/kube-scheduler

1.1.7 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /var/snap/microk8s/current/args/etcd

1.1.8 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/args/etcd

1.1.9 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 <path/to/cni/files>

1.1.10 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root <path/to/cni/files>

1.1.11 On the etcd server node, get the etcd data directory, passed as an argument --data-dir,
from the below command:
ps -ef | grep etcd
Run the below command (based on the etcd data directory found above). For example,
chmod 700 /var/lib/etcd

1.1.12 On the etcd server node, get the etcd data directory, passed as an argument --data-dir,
from the below command:
ps -ef | grep etcd
Run the below command (based on the etcd data directory found above).
For example, chown etcd:etcd /var/lib/etcd

1.1.13 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /etc/kubernetes/admin.conf

1.1.14 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /etc/kubernetes/admin.conf

1.1.15 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /var/snap/microk8s/current/credentials/scheduler.config

1.1.16 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/credentials/scheduler.config

1.1.17 Run the below command (based on the file location on your system) on the master node.
For example,
chmod 644 /var/snap/microk8s/current/credentials/controller.config

1.1.18 Run the below command (based on the file location on your system) on the master node.
For example,
chown root:root /var/snap/microk8s/current/credentials/controller.config

1.1.19 Run the below command (based on the file location on your system) on the master node.
For example,
chown -R root:root /var/snap/microk8s/current/certs

1.1.20 Run the below command (based on the file location on your system) on the master node.
For example,
chmod -R 644 /var/snap/microk8s/current/certs/*.crt

1.1.21 Run the below command (based on the file location on your system) on the master node.
For example,
chmod -R 600 /var/snap/microk8s/current/certs/*.key
```

Those tests are related to file permissions in the installation rather than arguments to e.g. kube-apiserver.
NB: Where suggested to make chmod 644 I would suggest a 640 instead (currently you've set it to 660).

The tests clashes a bit with your implementation of a microk8s group. If that group has been implemented to make things easier to test k8s then perhaps an optional flag like --production-mode or --cis-compliance during installation could be considered. On the other hand, I would think everybody would like a hardened installation to work on - both for testing and production.

BTW: The implementation of the CIS benchmark in https://github.com/aquasecurity/kube-bench/ has a lot of false negatives/positives because it's currently not perfectly adapted for Microk8s implementation (with e.g. kubelite). I've created another issue in their repo to have it fixed: https://github.com/aquasecurity/kube-bench/issues/959

Finally, thanks for the links regarding snap updates. And yes, now that you state it, I can see that the argument files under ../args are retained during updates.

Thanks and best regards
Jesper Berggren

**Comment by JesperBerggren** [comment]
Ok, now we're well in the hardening process from the CIS benchmark.

There are a few issues that we really think should be fixed in the default installation and arguments:

**File permissions and ownership (important since any changes done manually will be undone when updating Microk8s via  snap):**
- File permissions and ownership as described in my comment above.
- Besides my comment above the following needs to be corrected as well (for a node):
```
[INFO] 4 Worker Node Security Configuration
[INFO] 4.1 Worker Node Configuration Files
...
[FAIL] 4.1.5 Ensure that the --kubeconfig kubelet.conf file permissions are set to 644 or more restrictive (Automated)
[WARN] 4.1.6 Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root (Manual)
[WARN] 4.1.7 Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Manual)
[WARN] 4.1.8 Ensure that the client certificate authorities file ownership is set to root:root (Manual)
[FAIL] 4.1.9 Ensure that the kubelet --config configuration file has permissions set to 644 or more restrictive (Automated)
[FAIL] 4.1.10 Ensure that the kubelet --config configuration file ownership is set to root:root (Automated)
...
4.1.5 Run the below command (based on the file location on your system) on the each worker node.
For example,
chmod 644 /var/snap/microk8s/current/credentials/kubelet.config

4.1.6 Run the below command (based on the file location on your system) on the each worker node.
For example,
chown root:root /var/snap/microk8s/current/credentials/kubelet.config

4.1.7 Run the following command to modify the file permissions of the
--client-ca-file chmod 644 <filename>

4.1.8 Run the following command to modify the ownership of the --client-ca-file.
chown root:root <filename>

4.1.9 Run the following command (using the config file location identified in the Audit step)
chmod 644 /var/snap/microk8s/current/args/kubelet

4.1.10 Run the following command (using the config file location identified in the Audit step)
chown root:root /var/snap/microk8s/current/args/kubelet
...
```

**Certificates instead of tokens:**
- Use certificates instead of tokens for authentication. Basic auth and tokens are no longer recommended and really shouldn't be enabled by default.
  - Remove the kube-apiserver argument _--token-auth-file=${SNAP_DATA}/credentials/known_tokens.csv_
  - Remove the file _${SNAP_DATA}/credentials/known_tokens.csv_ and reconfigure the users to certificates instead.
 ```
[FAIL] 1.2.3 Ensure that the --token-auth-file parameter is not set (Automated)
...
== Remediations master ==
...
1.2.3 Follow the documentation and configure alternate mechanisms for authentication. Then,
edit the API server pod specification file /var/snap/microk8s/current/args/kube-apiserver
on the master node and remove the --token-auth-file=<filename> parameter.
```

**Use certificates to authenticate kubelet:**
- Set _--tls-cert-file_ and _--tls-private-key-file_ arguments for kubelet to ensure authentication of kubelet and prevent man-in-the-middle attacks.
- Set --kubelet-certificate-authority for kube-apiserver.
```
[FAIL] 1.2.6 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Automated)
...
== Remediations master ==
...
1.2.6 Follow the Kubernetes documentation and setup the TLS connection between
the apiserver and kubelets. Then, edit the API server pod specification file
/var/snap/microk8s/current/args/kube-apiserver on the master node and set the
--kubelet-certificate-authority parameter to the path to the cert file for the certificate authority.
--kubelet-certificate-authority=<ca-string>
...
[WARN] 4.2.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Manual)
...
== Remediations node ==
...
4.2.10 If using a Kubelet config file, edit the file to set tlsCertFile to the location
of the certificate file to use to identify this Kubelet, and tlsPrivateKeyFile
to the location of the corresponding private key file.
If using command line arguments, edit the kubelet service file
/etc/systemd/system/snap.microk8s.daemon-kubelet.service on each worker node and
set the below parameters in KUBELET_CERTIFICATE_ARGS variable.
--tls-cert-file=<path/to/tls-certificate-file>
--tls-private-key-file=<path/to/tls-key-file>
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
...
```

I guess that's it for now.

Best regards
Jesper Berggren

**Comment by JesperBerggren** [comment]
Hello again,

Does anyone has interest in at least fixing the file permissions/ownership?
The current setup compromises the installation and if manually fixed all changes will be lost across updates.

If the files have the current permissions/ownership to make things easy when "just playing around", could an optional flag like --production-mode or --cis-compliance be considered?

Best regards
Jesper Berggren

**Comment by ktsakalozos** [comment]
Let me first say that yes we are interested in making MicroK8s CIS compliant and deliver a secure out of the box installation.

Regarding the file permissions, as you may have seen when you `snap install microk8s` a new user group called `microk8s` is created. The rational is that both the root user and users in the `microk8s` group would be able to be the administrators of MicroK8s. The kubernetes installation/configuration files are owned by `root:microk8s` and the permissions we give them is 660. Out of the box the microk8s user group has no users so the permissions of 660 in a `root:microk8s` file are more strict than the recommended 640 in a root:root file. I wonder if this should be taken into account by kubebench or if MicroK8s should be giving you an option to disable the microk8s user group and use the root group.

**Comment by JesperBerggren** [comment]
Hi @ktsakalozos 

Thanks for your reply!

Yes, I can see your rationale and in theory I agree that it's more strict than the suggested 640 in a root:root file.
On the other hand we have an almost almighty security department with very deep concerns. They are indeed not interested in an extra microk8s group that doesn't fall under the same strict rules/management processes as the root user (at least not out of the box).

Therefore we strongly request an option to disable the microk8s group and use the root group instead. I guess we can't be the only ones when we're talking about a serious and potential large(r) scale production environment.

Best regards
Jesper Berggren

**Comment by nmav** [comment]
> Hi @ktsakalozos
> 
> Thanks for your reply!
> 
> Yes, I can see your rationale and in theory I agree that it's more strict than the suggested 640 in a root:root file.
> On the other hand we have an almost almighty security department with very deep concerns. They are indeed not interested in an extra microk8s group that doesn't fall under the same strict rules/management processes as the root user (at least not out of the box).

Could you elaborate on these concerns? They are not apparent from what you describe, and using a separate group for a service is what is expected for service isolation.

**Comment by JesperBerggren** [comment]
Hi @nmav 

I should probably get our security department to formulate the right answer, but here's my humble try.

Generally we try to minimize administrative privileges and only use administrative accounts when they are required. 
We have auditing on all use of administrative privileges but that is not focused on a group like microk8s, which more or less gives root access to the cluster. 
Separate groups might generally be expected for service isolation but in my opinion a Kubernetes cluster is not just another service. It more or less enables a full infrastructure and thus should be administered with utmost care and only the highest administrative privileges.

It might (and might not) be overcautious but failing multiple CIS tests and explaining it with the auto-creation of a group that doesn't need be used is hard to sell.

Best regards
Jesper Berggren

**Comment by fwininger** [comment]
Any progress on this issue ?

**Comment by neoaggelos** [comment]
Hi @fwininger 

CIS compliance is in the team plans for the future, but no one is currently assigned to working on it. Some things that are discussed above are also kind of blockers. For example, to avoid breaking UX changes in newer versions, MicroK8s might not come with CIS compliance out of the box, but it would be possible to produce a guide or a process (or an addon!) that would make the CIS compliance benchmarks happy.

If you (or anyone else reading) are interested in this, please upvote the issue or comment to raise awareness, and we can prioritize accordingly. Thank you!

**Comment by josemiguelcasado** [comment]
Hi there!
we have been considering to use microk8s as well, but not having CIS compliance is almost a no-go seen from our cybersecurity experts.

**Comment by merinogeospatial** [comment]
Hello! +1 for interest in CIS compliance for MicroK8s

**Comment by yalton-ruiz** [comment]
Hello,  As neoaggelos mentioned CIS is part of MicroK8s plans for the future. Currently, we are working on other features that we have already committed. However, if there is interest from the community or concrete customer use cases that require CIS, we can evaluate the CIS work.

Our next community hours is Friday this week, please feel free to approach and we can have a discussion around it.
----Join us in our community sync meeting on Friday 20th Jan, 1:30pm GMT. 
Video call link: https://lnkd.in/dVKKB4rc

Thanks, Yalton.

**Comment by josemiguelcasado** [comment]
I won't be able to join the meeting today, but I can give a hint on a use case where hardening is mandatory, critical infrastructures.
If the meeting is recorded, please share the link :-)

**Comment by ironicx** [comment]
Another one interested in CIS compliance for microk8s :)

**Comment by neoaggelos** [comment]
Looks like we skipped to update this issue. For CIS compliance in MicroK8s, have a look at the docs at https://microk8s.io/docs/cis-compliance

Thanks a lot folks for voicing the request!
