### ISSUE TITLE
Encrypting Secret Data at Rest is compromised with dqlite (that keeps unencrypted secrets)

### ISSUE THREAD

**Issue by JesperBerggren** [canonical/microk8s#2532]
Hello everybody!

### Summary of issue:
After configuration of _Encryption at Rest_ the official k8s documentation states that existing secrets should be encrypted with this command:
`kubectl get secrets --all-namespaces -o json | kubectl replace -f -`
Unfortunately looking in the dqlite database after running this command, the secret is encrypted **but** the old, unencrypted values still resides in the database and thus is still available in plaintext if compromised/accessed.

### Current situation:
After a long project we're finally getting close to production date with our new Kubernetes clusters, which are based on Microk8s.
Currently we're working on hardening our clusters and one of the steps is configuring _Encryption af Rest_ to have secrets encrypted.
We're configuring according to the documentation/tutorials in:
https://www.devshell.io/kubernetes-secrets-in-microk8s/
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

### Detailed explanation:
After installation of a Microk8s cluster all secrets are (as expected) unencrypted in the newly'ish introduced dqlite database.
This is easily verified by choosing any existing secret, e.g. _deployment-controller-token-79gmh_

**See unencrypted values:**
```
$ kubectl get secrets --all-namespaces
NAMESPACE         NAME                                               TYPE                                  DATA   AGE
...
kube-system       deployment-controller-token-79gmh                  kubernetes.io/service-account-token   3      6d2h
...

$ dbdir="/var/snap/microk8s/current/var/kubernetes/backend"

$ sudo /snap/microk8s/current/bin/dqlite -c ${dbdir}/cluster.crt -k ${dbdir}/cluster.key -s localhost:19001 k8s

dqlite> select name from kine where name like "%deployment-controller-token-79gmh%";
/registry/secrets/kube-system/deployment-controller-token-79gmh

dqlite> select * from kine where name = "/registry/secrets/kube-system/deployment-controller-token-79gmh";
/registry/secrets/kube-system/deployment-controller-token-79gmh|[107 56 ...<retained>... 34 0]

$ value="107 56 ...<retained>... 34 0"

$ echo "$value" | awk '{
  for(i=1; i<=NF; i++)
    if ($i > 31 && $i < 127 || $i == 10)
      printf("%c", $i);
    else
      printf(" ", $i);
  print "";
}'
<unencrypted value>
```

**New configuration of encryption at rest**
```
$ cd /var/snap/microk8s/current/args/

$ cat kube-apiserver | grep encryption
--encryption-provider-config=${SNAP_DATA}/args/encryption/encryptionconfiguration.yaml

$ cat encryption/encryptionconfiguration.yaml 
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: encryption-at-rest
          secret: <retained>
    - identity: {}
```

**Replace all secrets in cluster and verification that data has in fact been encrypted in the dqlite database:**
```
$ kubectl get secrets --all-namespaces -o json | kubectl replace -f -
...
secret/deployment-controller-token-79gmh replaced
...

$ sudo /snap/microk8s/current/bin/dqlite -c ${dbdir}/cluster.crt -k ${dbdir}/cluster.key -s localhost:19001 k8s

dqlite> select name from kine where name like "%deployment-controller-token-79gmh%";
/registry/secrets/kube-system/deployment-controller-token-79gmh
/registry/secrets/kube-system/deployment-controller-token-79gmh
```
Notice that there are two entries now!
I would have expected only one - with an updated value containing the encrypted secret.

**Deeper look at the data in the database:**
```
dqlite> select * from sqlite_master;
table|kine|kine|2|CREATE TABLE kine
			(
				id INTEGER primary key autoincrement,
				name INTEGER,
				created INTEGER,
				deleted INTEGER,
				create_revision INTEGER,
				prev_revision INTEGER,
				lease INTEGER,
				value BLOB,
				old_value BLOB
			)
...

dqlite> select * from kine where name like "%deployment-controller-token-79gmh%";
248|/registry/secrets/kube-system/deployment-controller-token-79gmh|1|0|0|0|0|[107 56 ...<retained>... 34 0]|[]
236728|/registry/secrets/kube-system/deployment-controller-token-79gmh|0|0|248|248|0|[107 56 ..<retained>... 92 120]|[107 56 ...<retained>... 34 0]
```
The row with id 248 is the secret from before the encryption with the unencrypted value - and it is still unencrypted.
The row with id 236728 is the new, replaced secret with an encrypted value in field _value_ but it still has the unencrypted value in the field _old_value_. Thus the unencrypted value resides in two rows after replacing secrets with encrypted values.

I'm thinking that the functionality with preserving old values probably helps in a lot of scenarios but when replacing (encrypting) secrets it more or less makes _Encryption at Rest_ worthless for existing secrets.

I hope someone can help with either fixing the issue or providing an alternative (which hopefully doesn't include deleting all secrets and recreating them).

Best regards
Jesper Berggren

**Comment by balchua** [comment]
Thanks @JesperBerggren for  pointing this out 
My understanding is that the old record will not be immediately removed, it is marked as deleted.
After sometime, the kine compaction will kick in, and delete old revisions.
This is purely a guess on kine's behavior simulating etcd.

**Comment by JesperBerggren** [comment]
Hi @balchua and thanks for your answer.

I can't seem to find which version of Kine Microk8s is using. I wonder if compaction doesn't work properly or is disabled somehow!?
A day later and a couple of microk8s.stop/starts there're still two rows. I don't think the compaction is actually running.

I just tried running (again):
`kubectl get secrets --all-namespaces -o json | kubectl replace -f -`
There are no changes to the database (which I find strange and unexpected). No new row, no new id's, and _old_value_ still has the unencrypted data.

Otherwise it was a good suggestion. Run the replace twice and wait for compaction. That would be fix the problem albeit a bit cumbersome and easy to forget.

Do you think it's a Kine issue or Microk8s?

Best regards
Jesper Berggren

**Comment by balchua** [comment]
> I can't seem to find which version of Kine Microk8s is using. I wonder if compaction doesn't work properly or is disabled somehow!?

The kine microk8s is using is here.
https://github.com/canonical/kine/tree/master/pkg
The compaction logic in kine is something i couldn't quite grasp.  Microk8s is currently using the master branch.

> I just tried running (again):
> `kubectl get secrets --all-namespaces -o json | kubectl replace -f -`
> There are no changes to the database (which I find strange and unexpected). No new row, no new id's, and _old_value_ still has the unencrypted data.

Hmmmm i would forcing the replace with the `--force`. Which issues a `DELETE` instead of `PUT`.

https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_replace/

is it fine to give that a try?

**Comment by JesperBerggren** [comment]
Hi @balchua 

Running this command:
`$ kubectl get secrets --all-namespaces -o json | kubectl replace --force -f -`
would seem like a good idea since it should delete before replacing but it makes the kine table look even more strange:
```
dqlite> select id,name,created,deleted,create_revision,prev_revision,lease from kine where name like "%deployment-controller-token-79gmh%";
248|/registry/secrets/kube-system/deployment-controller-token-79gmh|1|0|0|0|0
236728|/registry/secrets/kube-system/deployment-controller-token-79gmh|0|0|248|248|0
260792|/registry/secrets/kube-system/deployment-controller-token-79gmh|0|1|248|236728|0
260863|/registry/secrets/kube-system/deployment-controller-token-79gmh|1|0|0|260792|0
```
First of all, using _--force_ does make changes to the database AND both _value_ and _old_value_ now has encrypted values for the newest row (id).
But(!) there are a few things to notice:
- There are now two rows more than before (why two and not just one more?).
- The deleted flag seems to have been removed from id 248 (I think it still should be marked for deletion).
  - Actually only  id 260792 has the deleted flag - shouldn't it be 248, 236728 and 260792?
 
Do you think setting _--etcd-compaction-interval duration=5m_ could help?

Best regards
Jesper Berggren

**Comment by balchua** [comment]
@JesperBerggren that argument `etcd-compaction-interval` doesn't make any difference.
Kine runs its own compaction interval which is 5 mins.

We have to see how kine runs the compaction.  My best guess is why 2 new records is because the `force` calls 2 distinct events.  Which is delete then create.

**Comment by JesperBerggren** [comment]
@balchua, do you think the missing compaction is a general problem in Microk8s or simply just my in my installation?

Looking at the Kine repo it seems like they have a lot of focus on compaction so it would surprise me if it doesn't work at all!?

Btw, I think you're right about the two new records are caused by to distinct events.

**Comment by balchua** [comment]
> @balchua, do you think the missing compaction is a general problem in Microk8s or simply just my in my installation?

Unfortunately I don't have a good answer to this right now. ☹️. It can be the kine version that MicroK8s packaged.  We may not have seen this, since the cluster continues to function unless we check the records in dqlite like you did.

> Looking at the Kine repo it seems like they have a lot of focus on compaction so it would surprise me if it doesn't work at all!?

The kine that MicroK8s is a version known to work.  

Cc @ktsakalozos

**Comment by balchua** [comment]
@JesperBerggren its probably possible to delete the records related to the old secrets if compaction fails for that.
