### ISSUE TITLE
Cannot add Windows 10 node to existing cluster

### ISSUE THREAD

**Issue by Gabyx92** [canonical/microk8s#2547]
I'm trying to add a Windows 10 machine to my existing Microk8s server (ubuntu) by following these instructions: https://microk8s.io/docs/add-a-windows-worker-node-to-microk8s 

I'm able to install all the components and technically everything is running, however, I can't see the node listed when I run "microk8s kubectl get nodes". I can't see any issues in the logs either, can anyone confirm if my OS is actually supported please?

**Comment by ktsakalozos** [comment]
@Gabyx92, from what you describe kubelet running on the windows node is not registering with the API server running the control plane (on the Linux node). Do you see anything on on the logs of kubelet and the apiserver?

**Comment by anthopark** [comment]
@Gabyx92 Did you make sure your windows worker node's OS is Windows Server 2019?
