### ISSUE TITLE
microk8s fresh install inside LXD unable to get it running

### ISSUE THREAD

**Issue by typoworx-de** [canonical/microk8s#2549]
I've tried to setup microk8s inside LXD container using fresh installation of both (LXD + snap microk8s). Everything looks fine, until trying to start "microk8s start".

```
# microk8s start
# microk8s status
microk8s is not running.
```

official Setup instructions used:
https://microk8s.io/docs/lxd

**Comment by typoworx-de** [comment]
microk8s inspectio report attached
[inspection-report-20210902_143018.tar.gz](https://github.com/ubuntu/microk8s/files/7099728/inspection-report-20210902_143018.tar.gz)

**Comment by typoworx-de** [comment]
By the way I decided to use storage-backend 'btrfs'. I decided to use microk8s profile 'ext4' as there is only zfs optionally - but none for BTRFS. It's mentioned here: https://microk8s.io/docs/lxd

May be this is the problem?

**Comment by balchua** [comment]
Hi @typoworx-de 

It may well be that case.  Check this comment from another issue.
https://github.com/ubuntu/microk8s/issues/2304#issuecomment-854983653
See if it helps.

**Comment by typoworx-de** [comment]
> It may well be that case. Check this comment from another issue.
> [#2304 (comment)](https://github.com/ubuntu/microk8s/issues/2304#issuecomment-854983653)
> See if it helps.

Thanks, I'll try with ZFS Storage. Would be great if the lxd-init would point that out! Or there should be provided a BTRFS profile.

**Comment by typoworx-de** [comment]
I've tested with LVM-Storage (as ZFS was not available and seems to also have some issues with LXD).

The result with fresh setup of LXD + LVM-Pool is the same result as before:
```
root@microk8s:~# microk8s.start
Started.
root@microk8s:~# microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

Just for intereset the microk8s API seems to be accessible while microk8s status claims to be "not running"!
```
# sudo lsof -i TCP:16443
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
kubelite 6728 root   28u  IPv6 305876      0t0  TCP *:16443 (LISTEN)
kubelite 6728 root   34u  IPv4 306738      0t0  TCP localhost:43430->localhost:16443 (ESTABLISHED)
```

**Comment by typoworx-de** [comment]
Tried to get microk8s running despite of the fakt, that the microk8s.status states "not working". For some reason partly it looks like the k8s is working.

But trying to deploy dns ingress and dashboard showed me it is NOT working. Neither with LVM nor BTRFS backend.

I'll give it now a last try using dir-storage. Running the microk8s directly on host-system (development desktop workstation) is no option for me, as microk8s seems to screw too much in system and the fact, that it will kollidate with my existing development-stack already using 127.0.0.1 and port 80/443 (which obviously cannot be avoided!!! --> #2546).

It's really sad, that microk8s doesn't give users the ability to change the default ip-address being used!

**Comment by typoworx-de** [comment]
lxd+microk8s giving me the already known problems using dir-storage. So the issues found have not directly to do with LVM or BTRFS!

After deploying using instructions on https://microk8s.io/docs/lxd,

```
# microk8s.start      ---> seems to work, API is present
#microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.

# microk8s.enable dns ingress
microk8s.enable dns ingress
Enabling DNS
Applying manifest
error when creating "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Post "https://127.0.0.1:16443/api/v1/namespaces/kube-system/serviceaccounts?fieldManager=kubectl-client-side-apply": unexpected EOF
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "coredns", Namespace: "kube-system"
from server for: "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/api/v1/namespaces/kube-system/configmaps/coredns": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "coredns", Namespace: "kube-system"
from server for: "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/apis/apps/v1/namespaces/kube-system/deployments/coredns": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "kube-dns", Namespace: "kube-system"
from server for: "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole"
Name: "coredns", Namespace: ""
from server for: "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/coredns": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterrolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding"
Name: "coredns", Namespace: ""
from server for: "/root/snap/microk8s/2346/tmp/temp.coredns.yaml": Get "https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/coredns": dial tcp 127.0.0.1:16443: connect: connection refused
```
There seem to be mandatory problems with LXD <> microk8s!

**Comment by balchua** [comment]
@typoworx-de 
Can you try uploading the inspect tarball?

**Comment by typoworx-de** [comment]
> @typoworx-de
> Can you try uploading the inspect tarball?

There already is one for the given problem:
see post above --> https://github.com/ubuntu/microk8s/issues/2549#issuecomment-911753146

**Comment by dontlaugh** [comment]
I was unable to get microk8s running with 1) "dir" as my default storage pool running on 2) ext4 as my host filesystem (where that dir sits).

**Comment by ktsakalozos** [comment]
Hi @dontlaugh, did you follow the LXC installation instructions found in [1]? Could you share a `microk8s inspect` tarball?

[1] https://microk8s.io/docs/lxd

**Comment by dontlaugh** [comment]
I just ran through those instructions again to export the microk8s inspect tarball.
[inspection-report-20220215_235757.tar.gz](https://github.com/ubuntu/microk8s/files/8075555/inspection-report-20220215_235757.tar.gz)
