### ISSUE TITLE
Graceful Node Shutdown

### ISSUE THREAD

**Issue by turowicz** [canonical/microk8s#2551]
How to turn this feature on and configure it with microk8s?

https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

cc @balchua

**Comment by turowicz** [comment]
cc @ktsakalozos

**Comment by balchua** [comment]
This configuration seems to be only available with the yaml config.

**Comment by turowicz** [comment]
@balchua so if I add --config to the kubelet args and set it up there it will work?

**Comment by balchua** [comment]
I am not sure if adding the config yaml with the graceful node shutdown alone will work.
You may have to complete the entire yaml.  This simply speculation as I've not tried it at all.

**Comment by aarononeal** [comment]
I tried adding `--feature-gates="...,GracefulNodeShutdown=true"` to `kubelet` args, then restarted microk8s.

It does not work.

```
# systemd-inhibit --list
No inhibitors.
```

Any recommendations?

**Comment by DaviGia** [comment]
I have configured my microk8s instance just like @aarononeal, but I don't see kubelet item in inhibitor list.

To enable it I have:

1. removed `--feature-gates` parameter in `/var/snap/microk8s/current/args/kubelet` (to avoid redeclaration of the same variable, that will result in the cli parameter to [overwrite the same parameter specified in the config file](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file))
2. created a new file in `/var/snap/microk8s/current/args/kubelet-config.yaml`

  ``` yaml
  kind: KubeletConfiguration
  apiVersion: kubelet.config.k8s.io/v1beta1
  featureGates:
    DevicePlugins: true
    GracefulNodeShutdown: true
  shutdownGracePeriod: 300s
  shutdownGracePeriodCriticalPods: 60s
  ```

3. added `--config=kubelet-config.yaml` parameter in `/var/snap/microk8s/current/args/kubelet` (i've tried both relative and absolute path)
4. set microk8s group permission to `kubelet-config.yaml` file with `sudo chgrp microk8s kubelet-config.yaml`
5. rebooted the kubelet service with `sudo systemctl restart snap.microk8s.daemon-kubelet.service`

After all that, if I execute `systemd-inhibit --list` I don't see the kubelet inhibitor listed. What am I missing?

I'm currently using _microk8s 1.22/stable_ on _Ubuntu server 20.04 LTS_.

**Comment by aarononeal** [comment]
@DaviGia, on one of my clusters, I discovered an additional step I had to take.

Looking at the `kubelet` logs I saw it complaining that `InhibitDelayMaxSec` was set less than the grace period even though Kubernetes was writing that `logind` config.

You can check the current value with `gdbus introspect --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1`.

That led me to discover `/usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf` setting it to `30s`.

To workaround, I added my own higher priority config to `/etc/systemd/logind.conf.d/zz-kubelet.conf`.

The other thing to check is if the YAML parsing is finicky. I tried the `featureGate` format you had there first before switching to the other. I know it shouldn't make a difference, but if the above doesn't help, as a last resort try changing the formatting.

**Comment by DaviGia** [comment]
@aarononeal, thank you I'll try and let you know. Can you please tell me how you check the kubelet log? I tried systemctl and journalctl but I cannot see much.

**Comment by DaviGia** [comment]
@aarononeal, I checked the kubelite log and I don't see it complaining about `InhibitDelayMaxSec`. That said, inspecting `/org/freedesktop/login1` I see that the configured value is incorrect:
```
$ gdbus introspect --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1
interface org.freedesktop.login1.Manager {
  properties:
      @org.freedesktop.DBus.Property.EmitsChangedSignal("const")
      readonly t InhibitDelayMaxUSec = 30000000;
```

The value appears to be 30s while I've specified 300s in the kubelet configuration file. Looking at all logind possible configuration path I too discovered that there was a `/usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf` that declared `InhibitDelayMaxSec=30s` (as you have said). I've then proceed in deleting the file, rebooting kubelet, kubelite and systemd-logind services and listing again the inhibitors. Finally I can now see the kubelet entry:

```
$ systemd-inhibit --list
WHO                          UID USER PID   COMM            WHAT                                                     WHY                                                       MODE
ModemManager                 0   root 997   ModemManager    sleep                                                    ModemManager needs to reset devices                       delay
UPower                       0   root 1370  upowerd         sleep                                                    Pause device polling                                      delay
Unattended Upgrades Shutdown 0   root 983   unattended-upgr shutdown                                                 Stop ongoing upgrades or perform upgrades before shutdown delay
kubelet                      0   root 38790 kubelite        shutdown                                                 Kubelet needs time to handle node shutdown                delay
```

Thank you so much for the support @aarononeal !!

**Comment by aarononeal** [comment]
You're welcome. So glad to hear that helped!
