### ISSUE TITLE
Default IP bind to microk8s should NOT be 127.0.0.1 to avoid conflict with other services!

### ISSUE THREAD

**Issue by typoworx-de** [canonical/microk8s#2552]
I tried to change the IP to avoid conflicts with microk8s vs. an exisiting http-development-stack on my development workstation. This seems to be impossible!

Trying to workaround using LXD container for microk8s also doesn't work, as microk8s stack doesn't work correctly.

microk8s should either expose a configuration to change the default-ip bindings (at least for port 80/443) or it should use another local IP like 127.107.56.115 (127.{k}.{8}.{s} <-- ascii ordinary codes = 107,56,115).

It's much easier to "proxy" 127.0.0.1 and 80/443 on another IP then even trying to reconfigure microk8s in it's current state to work on another IP without wasting a lot of hours and giving up on that, as it seems to be impossible.

There is a bunch of related issues to LXD and address binding!

**Comment by typoworx-de** [comment]
I resignated as I need microk8s for one of my current customers to work on my workstation. I've tried to re-assign my local httpd to 127.0.10.1 IP. Never the less for any reason ANY IP on 127.0.0.0-127.0.0.254 seems to be routed to microk8s ingress! :-1: 

How can this be avoided? Not everybody wants nor need this! microk8s is skrewing too much on workstation systems.

**Comment by balchua** [comment]
The ingress addon is based on the upstream ingress.
https://kubernetes.github.io/ingress-nginx/
I even use this ingress and deploy it to microk8s.
https://github.com/poseidon/typhoon/tree/master/addons/nginx-ingress

Since its kubernetes, you are free to use and tweak it according to your needs.

As an example, i dont use the `microk8s kubectl` wrapper but instead i have `kubectl` client directly.

**Comment by typoworx-de** [comment]
I tried to figure out what's happening and noticed after starting microk8s + ingress EVERY ip in 127.0.0.0/8 is routed to ingress! It's not a problem of single-ip binding (127.0.0.1), but some kind of routing/nat/masquerade being applied!

Can anyone confirm this? How can this behaviour being changed?
- bind only single ip
- bind custom cidr (like 127.107.56.0/8 instead of 127.0.0.0/8)

This is totally frustrating. For a real k8s server running on a single node this may be totally okay, but for a development-workstation already running some services on 127.0.0.x this will absolutly destroy anything!

**Comment by typoworx-de** [comment]
Okay, I think masquerade is the culprit which NATs EVERYTHING to microk8s except:
CIDR  excluded by:
--non-masquerade-cidr=[IP CIDR]
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

So far I've tested only ONE IP-CIDR can be excluded! And there's no option to explicitly allow masquerade only on given CIDRs (instead on everything except non-masquerade-cidr).

**Comment by typoworx-de** [comment]
Is it somehow possible to make microk8s bind to only ONE given network-interface (f.e. network-bridge only) instead of hooking on 127.0.0.0/8?

**Comment by typoworx-de** [comment]
> Sometimes i use this ingress and deploy it to microk8s.
Thanks I'll have a look on that.
