### ISSUE TITLE
Getting  connection refused when I tried to push a local image to microk8s registry

### ISSUE THREAD

**Issue by michaelmok2021** [canonical/microk8s#2554]
I am  getting  error when I tried to push a local image to microk8s registry

Get "http://localhost:32000/v2/": dial tcp 127.0.0.1:32000: connect: connection refused

My setup

Ubuntu 20.04
Rootless docker
Microk8s (via snap)

I have no problem doing a curl -s -m 2 localhost:32000/v2 which return {}

Any advice?

See attached inspection report. Thanks. 
[inspection-report-20210904_221411.tar.gz](https://github.com/ubuntu/microk8s/files/7109873/inspection-report-20210904_221411.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @michaelmok2021 are you pushing the image with `docker push`? I trust you have gone through this document https://microk8s.io/docs/registry-built-in .
