### ISSUE TITLE
Local registry images not found every time snap updates

### ISSUE THREAD

**Issue by dmartin** [canonical/microk8s#2563]
I'm using the local registry addon and running several deployments referencing images from the registry.

Every time the microk8s snap automatically updates, all pods referencing `localhost:32000` images go into `ImagePullBackOff` status indefinitely and break these deployments.

They do not work again until some combination of restarting microk8s, disabling and re-enabling the registry addon, restarting the Docker daemon, or rebuilding the images is performed (I've never been able to figure out exactly what combination fixes it, and it seems random.)

I can confirm that the referenced images still exist via `curl localhost:32000/v2/_catalog` or `docker image ls`.
[inspection-report-20210907_190357.tar.gz](https://github.com/ubuntu/microk8s/files/7123838/inspection-report-20210907_190357.tar.gz)

**Comment by balchua** [comment]
My best guess is when the snap updates, we need to restart calico pods.  @ktsakalozos can this be the reason?

**Comment by balchua** [comment]
This happens to me when i set `imagePullPolicy: Always`

After restarting microk8s, i have to delete the pods.
