### ISSUE TITLE
MicroK8S host-system loosing outbound/internet connectivity due to iptables problems? :thinking: 

### ISSUE THREAD

**Issue by typoworx-de** [canonical/microk8s#2566]
I'm trying to run microk8s now inside VMware ESXi VM with fresh setup on top of Ubuntu 20.04 minimal. At first everything looks good, but for some reason the host system is loosing outbound/internet connectivity after at least 1 hour uptime.

Inbound connections from my workstation using f.e. SSH still work! But inside the microk8s-VM I can not even reach Google-DNS IP 8.8.8.8.

Trying to flush iptables does not work! After reboot everything works fine -- at first, but after some time running it's getting stuck again. There are no other services running than microk8s. UFW Firewall is disabled!

I had the same problems before that on my workstation trying to setup microk8s there locally, but abonded that idea after these Problems and some other network-conflicts due to 127.0.0.0/8 Masquerading.

[inspection-report-20210908_161627.tar.gz](https://github.com/ubuntu/microk8s/files/7129522/inspection-report-20210908_161627.tar.gz)

**Comment by typoworx-de** [comment]
Alsmost saw this very similar ticket and comment https://github.com/ubuntu/microk8s/issues/2180#issuecomment-896706519

But the mentioned change did not resolve the problem at all.

**Comment by ktsakalozos** [comment]
Hi @typoworx-de


> Trying to flush iptables does not work!

You mean that flushing the IPtable rules fail or that flushing the IPtable rules has no effect. Note that this flush will destroy MicroK8s because all routing rules will be dropped.

The attached tarball is at the point where the network connection is lost? When exactly did you take this inspection report?

**Comment by typoworx-de** [comment]
@ktsakalozos thanks for trying to help. After doing ```microk8s start``` the system works well for a while. But I noticed after a while the host-system is loosing network connectivity for any outgoing connection (f.e. curl/ping etc.). Inbound still does work (f.e. SSH to the microk8s host system running in the VM).

In the meanwhile I was not doing any change on the system or any iptables changes. Trying to flush iptables was only trial for error trying to get back connectivity after the issue is present, to prevent system reboot.
