### ISSUE TITLE
Kubeflow dashboard returns 403 Forbidden

### ISSUE THREAD

**Issue by IoanaEmma** [canonical/microk8s#2571]
I have a problem with Kubeflow Dashboard. Until now I could connect to the dashboard without problems, but after a restart of the PC it gives me forbidden when I try to connect from my browser to http://10.64.140.43.nip.io (this is the url received after kubeflow was enabled).

I'm working on Ubuntu 20.04.2 LTS machine where I installed microk8s 1.20.10 following the steps from this link: https://microk8s.io/docs and then enabled kubeflow(v1.2) addon. When I check kubeflow pods I can see that dex-auth pod sometimes is crashing with the following error:
"failed to list custom resource authcodes.dex.coreos.com, attempting to create: Get "https://[10.152.183.1]:443/apis/dex.coreos.com/v1/namespaces/kubeflow/authcodes": dial tcp 10.152.183.1:443: connect: connection refused"

After a few restarts of dex-auth deployment the pod is successfully Running, but still the dashborad is not working. It's not the first time I encounter this issue and the only solution I could find was to reinstall microk8s again.

I also installed: Knative v0.24, Istio for Knative v0.24, KFServing v0.5 for model prediction and from what I can see, after the restart the kubeflow dashboard can be accesed from this url: http://10.64.140.44.nip.io, but it shows me only the main page, when I try to navigate to experiments, runs or pipelines pages this message appears: no healthy upstream.

I am new to kubernetes and kubeflow so any help or any suggestion as to what I might do to solve this problem is welcome. Thanks.

[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/7153035/inspection-report.tar.gz)

![image](https://user-images.githubusercontent.com/31507685/133061216-55ebc744-18bc-45b3-86e3-971c4c5a1be9.png)

![image](https://user-images.githubusercontent.com/31507685/134663144-e2cc8764-165c-47b6-935f-a5221143c53f.png)

**Comment by ca-scribner** [comment]
Sorry for the slow response, I didn't notice this until reading #2665.  We are right now in the process of updating our charms to provide Kubeflow v1.4 (released this month) which might help with some of these issues.  We will probably have to see if they persist after that update.  Are you still encountering the issues listed here?  If not, any solutions you found along the way would be helpful

**Comment by ca-scribner** [comment]
Reading #2665 more I think yes you still see the issue.  I have a few vague guesses but nothing firm yet.  Wondering if maybe after a few days a pod restarts or something and the IP used for the dashboard gets messed up (and would require a new `juju config dex-auth ...` to set it)?  Does canonical/dex-auth-operator#17 sound like what you're experiencing?

If you have a deployment up with this issue, for the apps involved (maybe dashboard, profile, dex-auth, and oidc-gatekeeper, and any others you think relevant) could you please post their:
* `juju debug-log -i APPLICATION --replay`  (this is also in the inspect tarball, but if we export each app separately we get more history)
* `juju show-status-log` for the same applications

**Comment by IoanaEmma** [comment]
I managed to reproduce the issue, here are the logs from dex-auth and oidc-gatekeeper.

[dex-auth.txt](https://github.com/ubuntu/microk8s/files/7381518/dex-auth.txt)
[oidc-gatekeeper.txt](https://github.com/ubuntu/microk8s/files/7381520/oidc-gatekeeper.txt)
