### ISSUE TITLE
Addon upgrade support

### ISSUE THREAD

**Issue by mashbrno** [canonical/microk8s#2572]
Feature request

I'm using pretty standard addons: *coredns, ingress, rbac, storage* and a few others. With the upgrade to the *1.22/stable* channel the ingress controller stopped working due to [known changes in Kubernetes](https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/). Currently the [best approach](https://microk8s.io/docs/upgrading) is to disable addon and install again.

I'm missing some of these features:
* pre-flight check that some addons are not supported (or just simply not tested) with version being installed
* information that there is a new version of an addon
* smooth upgrade script

What I am very concerned about is that disabling some of the core addons will not just make the whole cluster dysfunct temporarily, but irreversibly harm deployments or their data (eg. storage addon).

**Comment by mashbrno** [comment]
As most of the addons are just YAML script files it should be quite simple to compare the applied and the most current version, even to display the *diff*. With [tains](https://kubernetes.io/docs/reference/labels-annotations-taints/) in place it should be possible to limit supported versions too.

**Comment by ktsakalozos** [comment]
Hi @mashbrno, you are right that refreshing to a channel may cause workloads to fail, including the workloads started by addons. At this point the release announcement of Kubernetes and MicroK8s is the best place to surface the any potentially braking changes and new addon version. You are also right that for a few core addons we should try to smooth the transition as much as possible.

We plan to draft a proposal for an addons framework that would allow for better addon lifecycle management. However, I am afraid we will never be able to completely rule out the case where an addon does not transparently migrates to a new k8s version.

**Comment by taintedkernel** [comment]
I was curious about this as well, after hitting this in #2595.  An enhancement for addon lifecycle management would be great.

I think the other aspect of the problem is the automatic background upgrades done by snap; it seems like there is somewhat recent feature of snap refresh awareness but it's experimental and not on by default.
