### ISSUE TITLE
Microk8s 1.21 - Kubeflow Enable issue

### ISSUE THREAD

**Issue by cheungtsl** [canonical/microk8s#2573]
Hi there,

I'm having issue when trying to enable Kubeflow under Microk8s 1.21 and I've attached my inspection report with this ticket.
 
Addon setup complete. Checking connectivity...
Couldn't contact api.jujucharms.com
Please check your network connectivity before enabling Kubeflow.
 
I spin up a ubuntu pod under Microk8s and installed python3 in the pod.... and I ran the following in the python shell under the pod .. I got the following ... 

>>> urlopen("https://api.jujucharms.com/charmstore/v5/istio-pilot-5/icon.svg")
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1421, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

If I install curl inside the pod.... the above command will work..
 apt-get install curl -y

root@7ab4302803be:/# python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> import os
>>> import random
>>> import string
>>> import subprocess
>>> import sys
>>> import tempfile
>>> import textwrap
>>> import time
>>> from distutils.util import strtobool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.util'
>>> from itertools import count
>>> from pathlib import Path
>>> from urllib.error import URLError
>>> from urllib.parse import ParseResult, urlparse
>>> from urllib.request import urlopen
>>>
>>> urlopen("https://api.jujucharms.com/charmstore/v5/istio-pilot-5/icon.svg")
<http.client.HTTPResponse object at 0x7fe879e771c0>
>>>

It seems we are missing ca certificate when we spin up the pod to check connectivity with kubeflow 

Do you have any suggestions to resolve this issue?

[inspection-report-20210913_135322.tar.gz](https://github.com/ubuntu/microk8s/files/7157402/inspection-report-20210913_135322.tar.gz)

**Comment by nitesh31mishra** [comment]
Hey, you can try the solutions mentioned in this https://github.com/ubuntu/microk8s/issues/1439  
you can try the following as well..
`sudo iptables -P FORWARD ACCEPT`

**Comment by yingding** [comment]
The same issue with MicroK8s v1.21.5 stable on Ubuntu VM 20.04.3 LTS with a fresh installation. I already tried `microk8s reset` and `sudo iptables -P FORWARD ACCEPT` on k8s node, both don't work. 

With 
```console
curl -v https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-88/icon.svg
```
on the k8s node works

With 
```console
microk8s.kubectl run --rm -it --restart=Never --image=ubuntu connectivity-check -- bash -c "apt update && apt install -y curl && curl https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-88/icon.svg"
```
 got the following error

```console
If you don't see a command prompt, try pressing enter.

Err:1 http://archive.ubuntu.com/ubuntu focal InRelease                   
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease         
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease           
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done        
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package curl
pod "connectivity-check" deleted
pod default/connectivity-check terminated (Error)
```

**Comment by Magister89** [comment]
@yingding Same console outputs, on Ubuntu 20.04 and microk8s 1.21/stable. Rules on iptables and disabling firewall didn't solve the problem...

**Comment by yingding** [comment]
@Magister89 My issue was really that my local microk8s 1.21.6 stable did't reach the google dns service `8.8.8.8` and `8.8.8.4` . For more detials please refer to https://github.com/ubuntu/microk8s/issues/2725 

Can you run
```
microk8s.kubectl run --rm -it --restart=Never --image=ubuntu connectivity-check -- bash -c "apt update && apt install -y curl && curl https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-88/icon.svg"
```
and see if the apt-get returns error such as `name not resolved`, then it is also the case, your egress port 53 must also be open. Otherwise just switch to your local DNS service.

And also be aware, you will need to enable dns addon first `microk8s dns storage` and DO NOT enable RBAC `microk8s disable rbac`. KubeFlow doesn't go well with RBAC addon. After that you might encounter some issue with juju and dex while login, and all these are solvable while googling :)

**Comment by Magister89** [comment]
@yingding My console output  for:

`microk8s.kubectl run --rm -it --restart=Never --image=ubuntu connectivity-check -- bash -c "apt update && apt install -y curl && curl https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-88/icon.svg"`

`Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Could not connect to security.ubuntu.com:80 (127.0.0.1). - connect (111: Connection refused)
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Could not connect to archive.ubuntu.com:80 (127.0.0.1). - connect (111: Connection refused)
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Unable to connect to archive.ubuntu.com:http:
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Unable to connect to archive.ubuntu.com:http:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Could not connect to archive.ubuntu.com:80 (127.0.0.1). - connect (111: Connection refused)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Unable to connect to archive.ubuntu.com:http:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Unable to connect to archive.ubuntu.com:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Could not connect to security.ubuntu.com:80 (127.0.0.1). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package curl
pod "connectivity-check" deleted
pod default/connectivity-check terminated (Error)
`
