### ISSUE TITLE
MicroK8s stuck at microk8s status --wait-ready

### ISSUE THREAD

**Issue by agriardyan** [canonical/microk8s#2574]
Hi. Thank you for this wonderful project.

I installed into one of my machines and it works wonders. 

However, recently I tried to install microk8s into one of our virtual server. The virtual server itself is provisioned with Proxmox, which I believe uses lxc.

Since I ran issue in installing it, I followed this gist https://gist.github.com/acj/3cb5674670e6145fa4f355b3239165c7. The installation via snap eventually successful. I added my user into microk8s group and everything seems ok at this point.

Only after executed `microk8s status --wait-ready`, I realized this command hangs forever. 

I've read these issue and none of those solve my problem.
https://github.com/ubuntu/microk8s/issues/1246
https://github.com/ubuntu/microk8s/issues/884

Any ideas?

Attached generated tarball from `microk8s inspect`
[inspection-report-20210914_091807.tar.gz](https://github.com/ubuntu/microk8s/files/7160650/inspection-report-20210914_091807.tar.gz)

**Comment by agriardyan** [comment]
Also, a bit out off topic: for Linux, any chance microk8s distributed via anything beside snap in the near future? Us, the proxmox users, often encounter problems with snap.

**Comment by ktsakalozos** [comment]
Hi @agriardyan, have you looked at the instructions for installing on lxc [1]?

There are no plans to distribute MicroK8s in anything other than a snap.

[1] https://microk8s.io/docs/lxd

**Comment by agriardyan** [comment]
Hi @ktsakalozos , thanks for your prompt response. 

As I said before, this is a case of microk8s in the virtual machine. Is adding the MicroK8s LXD profile and load apparmor profile done in the host machine?

If that's the case, then it's impossible to do right now. I simply don't have permission/privilege (in the context of organization) to alter anything in the host.

**Comment by balchua** [comment]
I can see from the logs that kube-proxy is failing to start.

```
Sep 14 09:17:56 SENAKEL-11 microk8s.daemon-kubelite[3297]: F0914 09:17:56.649722    3297 server.go:489] write /sys/module/nf_conntrack/parameters/hashsize: operation not supported
```
Another thing, you seem to have an all capital letter hostname.  Kubelet actually normalizes it to all small letters.  When you enable rbac later, you might find it not working.  Suggest to change the hostname to all small.

@ktsakalozos  you seem to have that fix sometime back. Here's the PR.
https://github.com/ubuntu/microk8s/pull/120
Here's the issue 
https://github.com/ubuntu/microk8s/issues/119

Is this something we missed when we move to kubelite?

@agriardyan can you try the fix in the said PR just to see if microk8s startsup?

**Comment by ktsakalozos** [comment]
The profile has to be created on the host where the the lxc containers are created. Also, the creation of the containers must be with the new profile.

**Comment by ktsakalozos** [comment]
@agriardyan, is LXC used to spawn lxc containers or VMs?

@balchua, I believe the `nf_conntrack/parameters/hashsize` issue is taken care by line [1] in the lxc profile.

[1] https://github.com/ubuntu/microk8s/blob/master/tests/lxc/microk8s.profile#L15

**Comment by agriardyan** [comment]
Sorry I mixed the terminology. I mean container. Will edit my previous posts.

**Comment by fenem** [comment]
@Balchua....

I think I spoke too soon.

Still having significant issues with bootstrapping microk8s on LXD.

Two nodes work fine; two nodes are being stubborn.  Followed the same
procedure for both.

My goal is to utilize lxd/microk8s/docker to stand-up a development
environment without polluting underlying OS.
Is this an appropriate use case for LXD/Microk8s?

Thx again for your consideration.

Kind Regards,

Michael Fene'

**Comment by balchua** [comment]
@fenem yes this is also the same use case at the same time emulate a multi node setup for dev.
I have been able to standup and join microk8s nodes running on lxd by just following the docs.

All lxd are running on the same host.  My file system is using ext (i think).

Are you trying to setup a multi node microk8s cluster? Or simply single nodes?
