### ISSUE TITLE
kubelet logs [pod name] command return Error from server: Get "https://ubuntu:10250/XX": EOF

### ISSUE THREAD

**Issue by nuc-uriel** [canonical/microk8s#2592]
I can't view any logs:
```shell
kubectl logs echo-cron-27207998-qgbfz
Error from server: Get "https://ubuntu:10250/containerLogs/default/echo-cron-27207998-qgbfz/echo-cron": EOF
```
But logs exist:
```shell
sudo cat /var/log/pods/default_echo-cron-27207998-qgbfz_373f215f-0c28-43b6-be7d-4576cb3b926b/echo-cron/0.log
2021-09-24T18:38:10.702348795+08:00 stdout F Fri Sep 24 10:38:10 UTC 2021
```

```shell
sudo microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2347/inspection-report-20210924_184002.tar.gz
```

I use Raspberry Pi，Ubuntu20.04，microk8s v1.21.3

**Comment by balchua** [comment]
Is this multiple nodes?  You can add your host name `ubuntu` to your `/etc/hosts`

**Comment by nuc-uriel** [comment]
> Is this multiple nodes? You can add your host name `ubuntu` to your `/etc/hosts`

`/etc/hosts` has hostname `ubuntu`,`tenlnet` command is success.

**Comment by balchua** [comment]
Thanks.  Does it happen on any pod?

**Comment by nuc-uriel** [comment]
> Thanks. Does it happen on any pod?
> 
> Can you also check if kubelite is restarting?
yes，any pods. i try to reboot system,but it still failed

**Comment by balchua** [comment]
If kubelite is crashing then thats probably the reason why you get EOF.
We need to see why kubelite is crashing if that is the case.  May i know what rpi you are using?

If you are not using HA, you can disable it.  But you will lose your data.

**Comment by nuc-uriel** [comment]
> If kubelite is crashing then thats probably the reason why you get EOF.
> We need to see why kubelite is crashing if that is the case. May i know what rpi you are using?
> 
> If you are not using HA, you can disable it. But you will lose your data.


I use Raspberry Pi 4b 8g，
If kubelite is crashing，other command is normal，only logs command is failed

**Comment by balchua** [comment]
Is it ok to upload the inspect tarball?

**Comment by balchua** [comment]
I couldn't find any lead to this issue.  The cluster is up. And like what is mentioned getting the logs throws the EOF error.
The cluster dump logs also reveal the same error.

**Comment by YangNianYi** [comment]
I got same issue on win10 wsl2 Ubuntu 22.04

sudo microk8s kubectl logs -f console-5cbc7f5744-48s7k -n minio-operator
Error from server: Get "https://nucwsl2:10250/containerLogs/minio-operator/console-5cbc7f5744-48s7k/console?follow=true": EOF
