### ISSUE TITLE
“Microk8s is not running” after Installing it fresh

### ISSUE THREAD

**Issue by asifansari80** [canonical/microk8s#2593]
The system was running fine. I reinstalled microk8s and since then its not coming up.

[root@asif-ansari-micro-k8-1 ~]# microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.

[root@asif-ansari-micro-k8-1 ~]# ps -ef | grep kubelet
root      2047     1  1 15:24 ?        00:00:21 /snap/microk8s/2409/kubelet --kubeconfig=/var/snap/microk8s/2409/credentials/kubelet.config --cert-dir=/var/snap/microk8s/2409/certs --client-ca-file=/var/sna2409/certs/ca.crt --anonymous-auth=false --network-plugin=cni --root-dir=/var/snap/microk8s/common/var/lib/kubelet --fail-swap-on=false --cni-conf-dir=/var/snap/microk8s/2409/args/cni-network/ --cni-bin-dirmicrok8s/2409/opt/cni/bin/ --feature-gates=DevicePlugins=true --eviction-hard=memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi --container-runtime=remote --container-runtime-endpoint=/var/ss/common/run/containerd.sock --containerd=/var/snap/microk8s/common/run/containerd.sock --node-labels=microk8s.io/cluster=true --authentication-token-webhook=true --cluster-domain=cluster.local --cluster-dn3.10
root      2070     1  7 15:24 ?        00:01:50 /snap/microk8s/2409/kube-apiserver --cert-dir=/var/snap/microk8s/2409/certs --service-cluster-ip-range=10.152.183.0/24 --authorization-mode=RBAC,Node --servicey-file=/var/snap/microk8s/2409/certs/serviceaccount.key --client-ca-file=/var/snap/microk8s/2409/certs/ca.crt --tls-cert-file=/var/snap/microk8s/2409/certs/server.crt --tls-private-key-file=/var/snap/microrts/server.key --kubelet-client-certificate=/var/snap/microk8s/2409/certs/server.crt --kubelet-client-key=/var/snap/microk8s/2409/certs/server.key --secure-port=16443 --token-auth-file=/var/snap/microk8s/24als/known_tokens.csv --insecure-port=0 --storage-backend=dqlite --storage-dir=/var/snap/microk8s/2409/var/kubernetes/backend/ --allow-privileged=true --service-account-issuer=https://kubernetes.default.svc ccount-signing-key-file=/var/snap/microk8s/2409/certs/serviceaccount.key --feature-gates=RemoveSelfLink=false --requestheader-client-ca-file=/var/snap/microk8s/2409/certs/front-proxy-ca.crt --requestheader-es=front-proxy-client --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --proxy-client-cert-file=/var/snap/micrerts/front-proxy-client.crt --proxy-client-key-file=/var/snap/microk8s/2409/certs/front-proxy-client.key
root     31199 20543  0 15:48 pts/1    00:00:00 grep --color=auto kubelet

[inspection-report-20210924_154344.tar.gz](https://github.com/ubuntu/microk8s/files/7226959/inspection-report-20210924_154344.tar.gz)

Inspect report attached.

Further I can see:
[root@asif-ansari-micro-k8-1 ~]# kubectl get pods -A
NAMESPACE            NAME                                         READY   STATUS     RESTARTS   AGE
kube-system          calico-node-s5xj9                            0/1     Init:0/3   0          34m
kube-system          calico-kube-controllers-847c8c99d-ssw4m      0/1     Pending    0          34m
kube-system          coredns-86f78bb79c-kjqqp                     0/1     Pending    0          21m
kube-system          hostpath-provisioner-5c65fbdb4f-dg95s        0/1     Pending    0          20m
kube-system          metrics-server-8bbfb4bdb-pwrj5               0/1     Pending    0          18m
kube-system          kubernetes-dashboard-7ffd448895-qqdkl        0/1     Pending    0          17m
kube-system          dashboard-metrics-scraper-6c4568dc68-tnw2f   0/1     Pending    0          17m
container-registry   registry-9b57d9df8-j9g8m                     0/1     Pending    0          16m

[root@asif-ansari-micro-k8-1 ~]# 
[root@asif-ansari-micro-k8-1 ~]# kubectl describe po/dashboard-metrics-scraper-6c4568dc68-tnw2f -n kube-system
Name:           dashboard-metrics-scraper-6c4568dc68-tnw2f
..

Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  9m (x12 over 17m)      default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Warning  FailedScheduling  4m28s (x3 over 6m58s)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Warning  FailedScheduling  79s (x2 over 2m49s)    default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
[

**Comment by nitesh31mishra** [comment]
Can you start the microk8s using `microk8s start` once... if it is not working you can remove microk8s again using --purge command  and reinstall it

**Comment by ktsakalozos** [comment]
Hi @asifansari80 , I see in the logs that containerd cannot pull images:
```
Sep 24 15:42:45 asif-ansari-micro-k8-1 microk8s.daemon-containerd[2076]: time="2021-09-24T15:42:45.017836619Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-node-s5xj9,Uid:e5ba95f2-bb9f-4401-be01-38fc94009b61,Namespace:kube-system,Attempt:0,} failed, error" error="failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": proxyconnect tcp: read tcp 100.69.112.106:49892->87.254.212.120:8080: read: connection reset by peer"
```
Are you behind a proxy or firewall? You may want to have alook at https://microk8s.io/docs/install-proxy

**Comment by asifansari80** [comment]
> Can you start the microk8s using `microk8s start` once... if it is not working you can remove microk8s again using --purge command and reinstall it

Hi
Thanks Nitesh for the response... the one that you pointed -- i did multiple times without success.

**Comment by asifansari80** [comment]
> Hi @asifansari80 , I see in the logs that containerd cannot pull images:
> 
> ```
> Sep 24 15:42:45 asif-ansari-micro-k8-1 microk8s.daemon-containerd[2076]: time="2021-09-24T15:42:45.017836619Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-node-s5xj9,Uid:e5ba95f2-bb9f-4401-be01-38fc94009b61,Namespace:kube-system,Attempt:0,} failed, error" error="failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": proxyconnect tcp: read tcp 100.69.112.106:49892->87.254.212.120:8080: read: connection reset by peer"
> ```
> 
> Are you behind a proxy or firewall? You may want to have alook at https://microk8s.io/docs/install-proxy

Thanks Tsakalozos ..  yes the setup is behind a Proxy.
Let me try the post shared by you...

**Comment by asifansari80** [comment]
Now .. i have the following:
Events:
  Type     Reason                  Age                     From     Message
  ----     ------                  ----                    ----     -------
  Warning  FailedCreatePodSandBox  12m (x5223 over 2d14h)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp 172.217.194.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  31s (x7 over 4m49s)     kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to resolve reference "k8s.gcr.io/pause:3.1": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.1": dial tcp 172.217.194.82:443: i/o timeout
[root@asif-ansari-micro-k8-1 ~]# ping k8s.gcr.io
PING k8s.gcr.io (172.217.194.82) 56(84) bytes of data.

Are these images pulled from docker repo ?
As i have another issue with docker:

[root@asif-ansari-micro-k8-1 ~]# docker run hello-world
Unable to find image 'hello-world:latest' locally
\docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
See 'docker run --help'.

**Comment by ktsakalozos** [comment]
MicroK8s pulls images from many public registries. The exact registry depends on where the upstream project puts its images. k8s.gcr.io/pause comes from k8s.gcr.io, other images may be fetched from dockerhub.

**Comment by asifansari80** [comment]
ok.. in that case i have to wait till my pull count is reset :(.
