### ISSUE TITLE
Ingress will not start on Windows 2019 worker nodes

### ISSUE THREAD

**Issue by wtfacoconut** [canonical/microk8s#2597]
I'm currently running MicroK8s version 2.1.0  on Windows 10 Enterprise (ver: 21H1, Build: 19043.1237).
I have a Windows Server 2019 (Ver: 1809. Build: 17763.1577) VM connected as a worker.
When trying to run either `microk8s.exe enable ingress` or `microk8s.exe enable traefik`, the ingress pod is able to start on the Linux worker node, but is **unable** to start on the Windows worker. In the case of both addons `ingress` and `traefik` the issue was because no windows container image was able to be retrieved.

After playing a bit, I was able to get the traefik ingress controller to work, but I had to perform the following steps to get it to work:

- (on windows worker): docker network create -d nat host
- (on windows worker): docker pull traefik:v2.3.0-windowsservercore-1809
- (on windows worker): docker tag 9fddb6b884a3 traefik:2.3
- (on host machine): microk8s.exe enable traefik

I feel that my workaround is not the correct way to have gotten the Traefik ingress controller to work. And as of now, I have not been able to get the addon called `ingress` to work at all.

Can I ask for some guidance on what I'm doing wrong here?

[inspection-report-20210926_205618.tar.gz](https://github.com/ubuntu/microk8s/files/7231294/inspection-report-20210926_205618.tar.gz)

**Comment by ktsakalozos** [comment]
The issue we have is that the manifests used to deploy the ingress daemonsets are not multi-arch. We usually expect the image references to support multiple architectures [1]. For example, the traefik 2.5.3 image [2] if for amd64, arm64 and arm but not for windows.

I am not sure what the right path forward is in this case. @balasu, @balchua @joedborg any ideas?

[1] https://kubernetes.io/docs/concepts/containers/images/#multi-architecture-images-with-image-indexes
[2] https://hub.docker.com/_/traefik?tab=tags&page=1&ordering=last_updated

**Comment by mkazmierczyk** [comment]
Hi, 

Did you manage to find any solution for described problem ? It exists for ingress addon and openebs addon. 

I have mixed cluster with Linux nodes and Windows workers. By default MicroK8s tries to create ingress controller on every worker but on Windows it failes. The same is for Openebs that as addon doesn't have node affinity and k9s tries to start its conteiners on Windows workers what results they fail.

**Comment by neoaggelos** [comment]
For future on-lookers, one way of preventing pods from being scheduled to windows nodes (if that is acceptable), is to configure the relevant daemonsets and deployments (e.g. `microk8s kubectl edit -n ingress daemonset nginx-ingress-microk8s-controller` with the following nodeSelector:

```
...
spec:
   ...
   template:
     ...
     spec:
       ...
       nodeSelector:
         kubernetes.io/os: linux
```

This will prevent the daemonset controller from spawning pods on the Windows workers.
