### ISSUE TITLE
Sometimes the pod for Portainer addon will try to start on a Windows worker node if one is available

### ISSUE THREAD

**Issue by wtfacoconut** [canonical/microk8s#2598]
I'm currently running MicroK8s version 2.1.0 on Windows 10 Enterprise (ver: 21H1, Build: 19043.1237).
I have a Windows Server 2019 (Ver: 1809. Build: 17763.1577) VM connected as a worker.
I had a situation where after adding my Windows worker node, then enabling the Portainer addon with `microk8s.exe enable portainer`, and then restarting all of microk8s/kubernetes/VMs, I would encounter an issue where sometimes the pod for Portainer would try to start on the Windows worker node.

This is an issue because the pod/deployment is configured to use a Linux container image. Because of this, when the pod tries to start, if will ultimately fail.

As a workaround, I edited the Portainer deployment by adding the following setting so that it would only start on Linux nodes:
```
nodeSelector:
  beta.kubernetes.io/os: linux
```

Can I ask for some guidance? Is this a bug or did I perhaps setup something incorrectly?

[inspection-report-20210926_205618.tar.gz](https://github.com/ubuntu/microk8s/files/7231418/inspection-report-20210926_205618.tar.gz)

**Comment by ktsakalozos** [comment]
Setting a node selector sound reasonable.

@balasu what are your thoughts about this? Should the Portainer manifests have this node selector by default?

**Comment by wtfacoconut** [comment]
@ktsakalozos  and @balasu, I also wanted to mention that this issue also happens with pods that get deployed as a result of enabling other MicroK8s Add-ons. Recently had to do this with coredns as well. There are probably other manifests that you'll want to add the node selector to.

**Comment by zimbres** [comment]
> @ktsakalozos and @balasu, I also wanted to mention that this issue also happens with pods that get deployed as a result of enabling other MicroK8s Add-ons. Recently had to do this with coredns as well. There are probably other manifests that you'll want to add the node selector to.

Hi!

How did you get the coredns replicaset not trying to be deployed at Windows host?

**Comment by zimbres** [comment]
@wtfacoconut 

How did you get the coredns replicaset not trying to be deployed at Windows host?

Tks...
