### ISSUE TITLE
microk8s-vm IP changes sometimes after full restart and breaks cluster

### ISSUE THREAD

**Issue by wtfacoconut** [canonical/microk8s#2599]
I'm currently running MicroK8s version 2.1.0 on Windows 10 Enterprise (ver: 21H1, Build: 19043.1237).
I have a Windows Server 2019 (Ver: 1809. Build: 17763.1577) VM connected as a worker.

There is an issue that I have encountered a few times where after restarting my physical machine, the internal IP address of the Linux VM that MicroK8s created, called `microk8s-vm` will have changed. When this happens, the cluster breaks as I have also added a Windows worker node. When MicroK8s for Windows creates `microk8s-vm`, is that VM intended to have a dynamic IP address?

Would it be safe for me to modify that VM to have a static IP address to try and prevent this issue from occurring again in the future?

Just in case if there's anyone who has encountered this issue, I was able to get my microk8s/kubernetes cluster running again by performing the following steps:
- [On Host] Using multipass, I opened a shell to the vm labeled "microk8s-vm" and retrieved the latest kubernetes config using the following command:
	`sudo microk8s config`
- [On Host] I updated the kuberketes config file (using the new config from the previous step) in the following two locations:
	`~\.kube\config`
	`~\AppData\Local\MicroK8s\config`
- [On Host] I ran the following command for all worker nodes to stop all currently running pods:
	`kubectl drain <node_name> --ignore-daemonsets`
- [On Win Workers] I then updated the config file below with the new one we got from the first step:
	`c:\k\config`
- [On Win Workers] Then I ran the following commands from powershell:
```
Stop-Service kubelet
Stop-Service kube-proxy
Stop-Service CalicoFelix
Stop-Service CalicoNode
C:\install-calico-windows.ps1 -DownloadOnly yes -KubeVersion 1.21.3
C:\CalicoWindows\install-calico.ps1
C:\CalicoWindows\kubernetes\install-kube-services.ps1
```
- [On Host] From here, things should be okay again. I ran the following command to verify that the nodes are back up:
	`kubectl get node -o wide`
- [On Host] After verifying that the worker node(s) are back up, I ran the following command so that kuberneter will start scheduling pods on the worker nodes again:
	`kubectl uncordon <NODE_NAME>`
- [On Host] Finally, I'm unsure if MicroK8s assigned any roles to any of the nodes. This was not something I paid attention to until I got to this step. Because I didn't see any roles when running `kubectl.exe get nodes -o wide`, I ran the following commands to assign roles to my nodes:
  - For any "worker" nodes: `kubectl label node <NODE_NAME> node-role.kubernetes.io/worker=worker`
  - For any "master" nodes: `kubectl label node microk8s-vm node-role.kubernetes.io/master=master`

[inspection-report-20210926_205618.tar.gz](https://github.com/ubuntu/microk8s/files/7231443/inspection-report-20210926_205618.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @wtfacoconut,

In a single-node cluster MicroK8s will detect host IP changes and will react to them by re-configuring its own services.

On a multi-node cluster MicroK8s expects that host IPs will not change. Re-configuring services in a multinode setup is not so straight forward. It is hard to know if a node changed IP or it just went offline. I cannot confirm that the manual steps you describe above will keep working without side effects. You would better look into setting a static IP for the VMs used.

Really appreciate the time and effort you spent in diving into the issue. Thank you.
