### ISSUE TITLE
Missing namespace in Portainer add-on

### ISSUE THREAD

**Issue by natalytvinova** [canonical/microk8s#2614]
When enabling Portainer on Microk8s hitting this warning:
`Warning: resource namespaces/portainer is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.`

Microk8s 1.22/edge, Ubuntu 20.04.3 ARM 64

**Comment by balasu** [comment]
Hi
 could you share microk8s kubectl get ns output

**Comment by natalytvinova** [comment]
Hi, here is an output, but I'm pretty sure it was patched automatically. So portainer itself works:
`$ microk8s kubectl get ns
NAME              STATUS   AGE
kube-system       Active   23h
kube-public       Active   23h
kube-node-lease   Active   23h
default           Active   23h
portainer         Active   23h`

**Comment by balasu** [comment]
Hi 
Yes its the add-on script which does it, if the namespace isnt exist will create 1 and deploy the portainer deployment. Its ignorable
