### ISSUE TITLE
TLS bootstrapping is broken after snap updates

### ISSUE THREAD

**Issue by JesperBerggren** [canonical/microk8s#2620]
Hello,

### Summary of issue:
TLS bootstrapping is broken after snap updates.
This is because TLS bootstrapping uses symbolic links to the actual certificates that are rotated and thus renamed when necessary.
Certificates and the symbolic links are preserved in the certs folder, but the symbolic link now points to the old microk8s folder under /var/snap/microk8s/xxxx/certs/ which is only retained a configurable number of updates.

### Detailed explanation:
We have successfully activated TLS bootstrapping as described in: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/
After configuring and activating the boostrap we had the following new files in _/var/snap/microk8s/2407/certs/_:

```
$ pwd
/var/snap/microk8s/2407/certs
$ ls -l
total 156
drwxrwx---  2 root microk8s 4096 Oct  1 12:18 ./
drwxr-xr-x 11 root root     4096 Oct  1 11:34 ../
-rw-rw----  1 root microk8s 1025 Sep  7 16:18 admin.crt
-rw-rw----  1 root microk8s  920 Sep  7 16:17 admin.csr
-rw-rw----  1 root microk8s 1679 Sep  7 16:17 admin.key
-rw-rw----  1 root microk8s 1123 Sep  7 14:29 ca.crt
-rw-rw----  1 root microk8s 1679 Sep  7 14:29 ca.key
-rw-rw----  1 root microk8s   41 Sep 16 10:59 ca.srl
-rw-rw----  1 root microk8s  675 Sep  7 14:29 csr.conf
-rw-rw----  1 root microk8s  675 Oct  1 12:18 csr.conf.rendered
-rw-rw----  1 root microk8s  665 Sep  7 14:29 csr.conf.template
-rw-rw----  1 root microk8s 1127 Sep  7 14:29 front-proxy-ca.crt
-rw-rw----  1 root microk8s 1679 Sep  7 14:29 front-proxy-ca.key
-rw-rw----  1 root microk8s   41 Sep  7 14:29 front-proxy-ca.srl
-rw-rw----  1 root microk8s 1432 Sep  7 14:29 front-proxy-client.crt
-rw-rw----  1 root microk8s 1147 Sep  7 14:29 front-proxy-client.csr
-rw-rw----  1 root microk8s 1679 Sep  7 14:29 front-proxy-client.key
-rw-rw----  1 root microk8s 1058 Sep 16 10:59 kube-apiserver-kubelet-client.crt
-rw-rw----  1 root microk8s  952 Sep 16 10:59 kube-apiserver-kubelet-client.csr
-rw-rw----  1 root microk8s 1679 Sep 16 10:59 kube-apiserver-kubelet-client.key
-rw-rw----  1 root microk8s 1025 Sep  7 16:17 kube-controller-manager.crt
-rw-rw----  1 root microk8s  920 Sep  7 16:17 kube-controller-manager.csr
-rw-rw----  1 root microk8s 1679 Sep  7 16:17 kube-controller-manager.key
-rw-rw----  1 root microk8s 1126 Sep  7 18:51 kubelet-client-2021-09-07-18-51-46.pem
lrwxrwxrwx  1 root microk8s   68 Sep  7 18:51 kubelet-client-current.pem -> /var/snap/microk8s/2407/certs/kubelet-client-2021-09-07-18-51-46.pem
-rw-rw----  1 root microk8s 2319 Sep  7 14:30 kubelet.crt
-rw-rw----  1 root microk8s 1679 Sep  7 14:30 kubelet.key
-rw-rw----  1 root microk8s 1179 Sep  7 18:54 kubelet-server-2021-09-07-18-54-21.pem
lrwxrwxrwx  1 root microk8s   68 Sep  7 18:54 kubelet-server-current.pem -> /var/snap/microk8s/2407/certs/kubelet-server-2021-09-07-18-54-21.pem
-rw-rw----  1 root microk8s 1005 Sep  7 16:17 kube-proxy.crt
-rw-rw----  1 root microk8s  903 Sep  7 16:16 kube-proxy.csr
-rw-rw----  1 root microk8s 1679 Sep  7 16:16 kube-proxy.key
-rw-rw----  1 root microk8s 1013 Sep  7 16:16 kube-scheduler.crt
-rw-rw----  1 root microk8s  907 Sep  7 16:16 kube-scheduler.csr
-rw-rw----  1 root microk8s 1679 Sep  7 16:15 kube-scheduler.key
-rw-rw----  1 root microk8s 1541 Sep  7 14:29 server.crt
-rw-rw----  1 root microk8s 1261 Sep  7 14:29 server.csr
-rw-rw----  1 root microk8s 1675 Sep  7 14:29 server.key
-rw-rw----  1 root microk8s 1679 Sep  7 14:29 serviceaccount.key
```

Notice _kubelet-client-current.pem_ and _kubelet-server-current.pem_
They both point to /var/snap/microk8s/2407/certs/...

This has worked until the last update (2546) where the folder _/var/snap/microk8s/2407/_ has been automatically deleted by snapd.

Throughout the updates after 2407 the symbolic links has not been updated, which was ok'ish because the old revision folder still existed and had the certificates, BUT after the last update the symbolic links points to certificates in a folder that no longer exists. This of cource breaks the link and thus communication between kube-apiserver and kubelet.

### What was expected:
The certs folder is copied to the new snap revision folder but that is not sufficient.
Symbolic links that resides in the certs folder and that points to files in a specific revision folder should be updated to match the new revision folder. Otherwise snap updates will eventually break the cluster if using TLS bootstrapping.

### Version details:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-16T02:43:21Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-3+83e2bb7ee39726", GitCommit:"83e2bb7ee3972654beca02a12a94777da22d6669", GitTreeState:"clean", BuildDate:"2021-09-28T15:36:44Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Best regards
Jesper Berggren

**Comment by ktsakalozos** [comment]
Hi @JesperBerggren 

When a new snap revision is released the  `/var/snap/microk8s/<new_revision_number>` directory is created and the link `/var/snap/microk8s/current` is updated to point to it. Would it be possible to use the `/var/snap/microk8s/current` to point to the `certs` directory?

**Comment by JesperBerggren** [comment]
Hi @ktsakalozos 

Thanks for your answer. Yes, I generally get update functionality with the new directory and a symbolic link called _current_ that just points to the folder with the current revision number.

To be honest I'm not really sure how exactly the TLS bootstrapping and certificate rotation works behind the scenes.

Is there an argument to provide a base-folder for issued certificates. Does it use _--cert-dir_ in kube-apiserver? If so, it's per default set to: _--cert-dir=${SNAP_DATA}/certs_

Actually I thought it was kube-controller-manager that issued the certificates and if so, I would think it only uses its own arguments. In that case it could be that it uses the base-folder for either _--root-ca-file_ or _--cluster-signing-cert-file_

In any case, all arguments related to certificates in the files under /var/snap/microk8s/current/args/ are given with the {SNAP_DATA} environment variable. And that resolves to the specific revision number - e.g. _SNAP_DATA=/var/snap/microk8s/2546_

If I knew the specific variable(s) that needs to be updated from: 
_{SNAP_DATA}/certs_
to:
_/var/snap/microk8s/current/certs_
then I could just update that or those arguments. Alternatively I could just replace all instances of _{SNAP_DATA}_ with _/var/snap/microk8s/current/args/_ !?

The issue is for both:
- TLS bootstrapping of the _kubelet-client-current.pem_
- Certificate Rotation of the _kubelet-server-current.pem_

Any insight would be greatly appriciated.

Thanks in advance!

Best regards
Jesper Berggren
