### ISSUE TITLE
Local registry fails with localhost:32000 works with 127.0.0.1

### ISSUE THREAD

**Issue by robotrapta** [canonical/microk8s#2625]
Trying to use microk8s with a local registry on ubuntu 18.04.  Saw this with microk8s 1.21 and 1.22.  Following a run book to set up a system that has worked fine in the past, today it wasn't working.  The system uses images named `localhost:32000/roboside:latest` and kept getting the error message 

```
Failed to pull image "localhost:32000/roboside:latest": rpc error: code = NotFound desc = failed to pull and unpack image "localhost:32000/roboside:latest": failed to resolve reference "localhost:32000/roboside:latest": localhost:32000/roboside:latest: not found
```

When I changed the image names to `127.0.0.1:32000/roboside:latest` and pushed images with that tag, it worked.

Huh?

(Not attaching the inspection report because it includes logs with some sensitive details in them, as my jobs have actually started running.  Happy to provide any parts you're interested in though.)

**Comment by balchua** [comment]
Very dumb question, is localhost in your etc/hosts?

**Comment by robotrapta** [comment]
Totally not a dumb question.  I did check, it the `etc/hosts` is unmodified:

```
127.0.0.1	localhost
127.0.1.1	ros2dev
```

and then a bunch of ipv6 noise.

**Comment by balchua** [comment]
How about doing a curl to `http://localhost:32000/v2/_catalog`
From your host?  Is localhost also linked to some ipv6 in etc/host file?

**Comment by balchua** [comment]
Thanks.  Just confirming this is a single node right.

**Comment by robotrapta** [comment]
Correct, single node.  It's an ARM aarch64 machine FWIW.  

```
$ uname -a
Linux ros2devel 4.9.253-rt168-tegra #1 SMP PREEMPT RT Mon Jul 26 12:10:58 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

$ k get nodes
NAME        STATUS   ROLES    AGE   VERSION
ros2devel   Ready    <none>   42h   v1.22.2-3+08d70d9ea9965a
```
