### ISSUE TITLE
Support for `KubeletConfiguration` kind

### ISSUE THREAD

**Issue by junjie-landing** [canonical/microk8s#2642]
```
error: unable to recognize "xxx/kubeconfig.yml": no matches for kind "KubeletConfiguration" in version "kubelet.config.k8s.io/v1beta1"
```

Curious how do I know which version kubelet microk8s is according to the main stream k8s?

We appreciate your feedback. Thank you for using microk8s.

**Comment by balchua** [comment]
MicroK8s channel correspond to the kubernetes version.

`snap info microk8s` will show u the microk8s version installed.

We are also working towards using yaml configuration of the kubernetes components instead of the arguments.  But it is currently not implemented.
