### ISSUE TITLE
Kubeflow add on failing

### ISSUE THREAD

**Issue by Djdraper12** [canonical/microk8s#2661]
To get K8s running having andd start the kubeflow add on in 1.21/Stable I having to run the following commands:
sudo sed -re "s/(value: \"first-found\")/value: \"interface=wlo.*\"/" -i /var/snap/microk8s/current/args/cni-network/cni.yaml
microk8s kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml

sudo chgrp -R microk8s /var/snap/microk8s/current/juju/
sudo chmod -R 775 /var/snap/microk8s/current/juju/

Also have to delete the lockfile from /tmp to start kubeflow due to permissions. 

The pods are starting up and now get this final error any ideas? 
Waited 450s for operator pods to come up, 6 remaining.
Waited 465s for operator pods to come up, 5 remaining.
Kubeflow could not be enabled:
ERROR starting proxy for api connection: Get "https://192.168.0.33:16443/api/v1/namespaces/controller-uk8s/services/controller-service": dial tcp 192.168.0.33:16443: connect: connection refused

![image](https://user-images.githubusercontent.com/32175818/137579196-922fbca6-3e57-4d9e-9f4e-3a64aa6e3891.png)

**Comment by ktsakalozos** [comment]
Hi @Djdraper12 could you try the `edge` channel, eg `snap refresh microk8s --channel=1.21/edge`?

**Comment by Djdraper12** [comment]
> Hi @Djdraper12 could you try the `edge` channel, eg `snap refresh microk8s --channel=1.21/edge`?

@ktsakalozos Still had the same issue but a different IP and different api connection
ERROR starting proxy for api connection: forwarding ports: error upgrading connection: error dialing backend: dial tcp 127.0.1.1:10250: connect: connection refused
