### ISSUE TITLE
Can't curl service in another node

### ISSUE THREAD

**Issue by falgifaisal** [canonical/microk8s#2666]
Hi,

I have joined node in via microk8s add-node and success

But, when i expose deployment, i can't create curl request for the pod in the master node (Ex : curl loclahost:30679).
But, when i create curl request in the joined, success (Ex : curl localhost:30679)

Master node : test1
Joined node : test2

This is result from microk8s kubectl get pod

nginx-6799fc88d8-mqma3                        1/1     Running   1 (40m ago)   56m   10.1.71.123    test2   <none>           <none>
nginx-6799fc88d8-q7pv3                        1/1     Running   1 (40m ago)   56m   10.1.71.124    test2   <none>           <none>
nginx-6799fc88d8-hmgn5                        1/1     Running   1 (40m ago)   56m   10.1.71.125    test2 <none>           <none>
nginx-6799fc88d8-67w73                        1/1     Running   1 (40m ago)   56m   10.1.71.126    test2 <none>           <none>

**Comment by balchua** [comment]
Based on your issue are you trying to curl using `NodePort`?

**Comment by falgifaisal** [comment]
> Based on your issue are you trying to curl using `NodePort`?

Yes. how to solve this ?

**Comment by balchua** [comment]
Can you show me the output of `microk8s get svc -A  -o wide`?

**Comment by falgifaisal** [comment]
> microk8s get svc -A -o wide

This is the result

default              nginx                          NodePort       10.152.183.150   <none>        80:30679/TCP             25h   app=nginx

**Comment by balchua** [comment]
Thats strange. Every node should open that port.

**Comment by fluxens** [comment]
same issue here. running `kubectl expose deployment nginx --type=NodePort`. Getting the nodeport with `kubectl get svc`. Nodeport is only open on master node communicating with kubectl. 

running `nmap localhost -p-` on each node shows that the exposed ports are not exposed on the other nodes.
