### ISSUE TITLE
Calico fails on 21.10 when running on raspberry pi

### ISSUE THREAD

**Issue by CharlesGillanders** [canonical/microk8s#2680]
I believe this may be the root cause of issue https://github.com/ubuntu/microk8s/issues/2663#issue-1029040908 Calico is not starting correctly - there is no calico.vxlan interface created and attempting to deploy any pod results in an error Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox 

Here's an inspection report from 21.10 on raspberry PI 4
[inspection-report-20211022_230749.tar.gz](https://github.com/ubuntu/microk8s/files/7401762/inspection-report-20211022_230749.tar.gz)

I first identified the issue from an upgrade of a working microk8s cluster on 21.04 to 21.10 on raspberry pi 4 - so I tested again with a clean install of 21.10 on raspberry pi 4 and got the same errors.

I've tested a clean install of microk8s on a  clean install of 21.10 on Intel and it works correctly - similarly a clean install of micro8ks on 21.04 on raspberry pi 4 also works correctly.    

I'm happy to produce more logging if someone can tell me what's needed to find out what is happening with calico on raspberry pi 4?

**Comment by slyons** [comment]
Seconded, same setup and same issue.

**Comment by AdriRRP** [comment]
One more that joins the problem. My kubernetes cluster was working until I decided to upgrade from 21.04 to 21.10. Does anyone have any news?

**Comment by igorabiola** [comment]
just tested this from #2712 and  it worked!
---
I have been chasing down this issue on my 7 node stack. Not sure if you got the same problem but i never got any containers up. Found out that in Ubuntu 21.10 i had to install `sudo apt install linux-modules-extra-raspi` after stop and start it came up and working! :)

_Originally posted by @jonizen in https://github.com/ubuntu/microk8s/issues/2712#issuecomment-963239054_

**Comment by CharlesGillanders** [comment]
The additional package install mentioned by @igorabiola has fixed my deployment.

**Comment by afassio** [comment]
Also for me Thanks Igor a lot

**Comment by jonizen** [comment]
> 
> 
> One more that joins the problem. My kubernetes cluster was working until I decided to upgrade from 21.04 to 21.10. Does anyone have any news?

Have a look at https://github.com/ubuntu/microk8s/issues/2712#issuecomment-963976614

and see if it is the same issue :)

**Comment by h3mmy** [comment]
This fixed my issue as well

**Comment by brianjgrier** [comment]
Upgrade my cluster yesterday only to have it die.
Found this at 3:00 today and life is good again.

How do we get the installation instructions for the Raspberry Pi updated?

**Comment by jonizen** [comment]
> Upgrade my cluster yesterday only to have it die.
> 
> Found this at 3:00 today and life is good again.
> 
> 
> 
> How do we get the installation instructions for the Raspberry Pi updated?

I think docs are already updated :)

https://github.com/ubuntu/microk8s/issues/2712#issuecomment-963858657

**Comment by AdriRRP** [comment]
[#2712](https://github.com/ubuntu/microk8s/issues/2712) Works perfectly for me!
Than you very much @igorabiola !

**Comment by stepanselyuk** [comment]
I link a related issue https://github.com/projectcalico/calico/issues/5410

**Comment by anil-sezer** [comment]
@igorabiola 's solution worked for me too. Thanks!

**Comment by Natrinicle** [comment]
The solution in https://github.com/canonical/microk8s/issues/2680#issuecomment-963581204 worked for me as well with Ubuntu 23.10 running Kubernetes 1.28.5 with Calico dumping the error

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "XXXXX": plugin type="calico" failed (add): failed to create host netlink handle: protocol not supported
```

Adding this comment in hopes that others searching for that log line might stumble across this issue faster as it wasn't easy for me to find

**Comment by krishna007-cloud** [comment]
Thanks, this worked like a dream "just tested this from https://github.com/canonical/microk8s/issues/2712 and it worked!
I have been chasing down this issue on my 7 node stack. Not sure if you got the same problem but i never got any containers up. Found out that in Ubuntu 21.10 i had to install sudo apt install linux-modules-extra-raspi after stop and start it came up and working! :)

Originally posted by @jonizen in https://github.com/canonical/microk8s/issues/2712#issuecomment-963239054"
