### ISSUE TITLE
Kubeflow fails behind a proxy 

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/microk8s#2690]
I'm trying to deploy Kubeflow behind a proxy and I'm having some issues with the `admission-webhook` and then with `kubeflow-profiles`.

I've followed the [steps](https://microk8s.io/docs/install-proxy) in the documentation and used the flag `--no-proxy=$no_proxy` to enable kubeflow. It stops deploying new pods with 27 remaining and checking the events in the namespace `kubeflow` it's possible to see this kind of events:

```
Internal error occurred: failed calling webhook "admission-webhook.kubeflow.org": Post "https://admission-webhook.kubeflow.svc:443/apply-poddefault?timeout=30s": Service Unavailable
```
My next step was trying to delete the `admission-webhook` with the command:

```
microk8s kubectl delete -n kubeflow mutatingwebhookconfiguration.admissionregistration.k8s.io/kubeflow-admission-webhook
```
After deleting the webhook, the pods restart to deploy, but it stops with approximately 6 remaining and is possible to see this error in juju-logs:

```
application-kubeflow-profiles: 20:23:07 ERROR unit.kubeflow-profiles/0.juju-log kubeflow-profiles:17: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/var/lib/juju/agents/unit-kubeflow-profiles-0/charm/venv/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f45f3eb80a0>: Failed to establish a new connection: [Errno 110] Connection timed out
```
I've already tried to install/remove microk8s and juju and I'm hitting this constantly. In a environment without proxy it deploys without problems.

[inspection-report-20211028_205507.tar.gz](https://github.com/ubuntu/microk8s/files/7437531/inspection-report-20211028_205507.tar.gz)

**Comment by ca-scribner** [comment]
There's probably a few things at play here.  I have some notes in google docs I will send to you outside this that might help - if they do please note what made the difference here :)  

These do look like the proxy is getting in the way.  In general I hit lots of problems with making sure things like `jujud` could talk to what they need to talk to.  Also, with the admission-webhook, it is a real pain when it breaks as it basically blocks everything.  If pods aren't scheduling, it is almost always because of that (and sometimes a leftover `mutatingwebhookconfiguration` means that problem persists even after the `remove-application`)

**Comment by gabrielcocenza** [comment]
Adding `admission-webhook.kubeflow.svc` into `no_proxy` variables solved the problem with the admission-webhook, but the kubeflow-profiles it's giving the same problem. Adding `raw.githubusercontent.com` in the `no_proxy` variables didn't solve the issue
