### ISSUE TITLE
[kubeflow add-on] microk8s status does not show kubeflow as enabled

### ISSUE THREAD

**Issue by DnPlas** [canonical/microk8s#2695]
The `kubeflow` add-on is not listed under the "enabled" section when running `microk8s status`. All Kubernetes resources are created, and Kubeflow seems to be working properly, it is just the output of the command that seems off.

#### Steps to reproduce
```bash
$ sudo snap install microk8s --classic --channel=1.21/stable
$ microk8s status --wait-ready
$ microk8s enable kubeflow
$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    istio                # Core Istio service mesh services
    metallb              # Loadbalancer for your Kubernetes cluster
    storage              # Storage class; allocates storage from host directory
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    dashboard            # The Kubernetes dashboard
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    gpu                  # Automatic enablement of Nvidia CUDA
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    jaeger               # Kubernetes Jaeger operator with its simple config
    keda                 # Kubernetes-based Event Driven Autoscaling
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
```
#### Possible cause
The add-on status is checked by [`status.py`](https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/status.py#L153) which relies on the value of `check_status` in [`addons-lists.yaml`](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml#L150). For kubeflow, it points to `pod/ambassador-operator-0`, an application that is not listed in [`bundle.yaml`](https://github.com/canonical/bundle-kubeflow/blob/master/bundle.yaml) and thus not deployed.

#### Possible solution
Point `check_status` to something else included in both [`bundle.yaml`](https://github.com/canonical/bundle-kubeflow/blob/master/bundle.yaml) and [`bundle-lite.yaml`](https://github.com/canonical/bundle-kubeflow/blob/master/bundle-lite.yaml). I propose `istio-ingressgateway-operator-0`

#### My setup
microk8s v1.21.5
Ubuntu 20.04 LTS
#### microk8s inspect
[inspection-report-20211031_210105.tar.gz](https://github.com/ubuntu/microk8s/files/7450527/inspection-report-20211031_210105.tar.gz)

**Comment by ktsakalozos** [comment]
The `microk8s status` needs to do a very quick test (as it checks all addons) to find out if kubeflow is running. @knkski @DomFleischmann @ca-scribner should we change the pod we are checking to some other one?

**Comment by DnPlas** [comment]
@ktsakalozos that pod we are currently checking is not created by the kubeflow bundle, as far as I understand. If that pod/ambassador-* doesn't exist, the status will always show as disable. That's why I was suggesting something that is actually specified in Kubeflow's `bundle.yaml`. I don't think the check will change its execution time, in the end all it is checking is the existence of a pod, unless I am missing something.

**Comment by DnPlas** [comment]
Hey @ktsakalozos, I received some suggestions from @ca-scribner and @knkski, we could either check for `kfp-api` or create a lock file, similar to what Kata is doing [here](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml#L226). I'd like your input here to know the preferred method so I can update #2696.
