### ISSUE TITLE
Set `--advertise-address 0.0.0.0` option by default

### ISSUE THREAD

**Issue by davigar15** [canonical/microk8s#2707]
Hello @ktsakalozos,

We already have conversations regarding this, but I think it is worth creating an issue explaining it.

**Description of the issue**
When MicroK8s is installed with some pods deployed, any change to the networking of the host machine will cause a restart of all the pods, where they will go to Unknown state, and after a couple of minutes they will restart successfully.

The problem of this, is that every time you connect/disconnect from a VPN, switch Wifi networks, or install/remove any software that touches the networking (like docker, lxd, microstack, ...) you'll face the same issue, which is a bit annoying and decreases the overall user experience.

**Proposed solution:**
To workaround this solution, what I have done so far is to add the `--advertise-address 0.0.0.0` option to `/var/snap/microk8s/current/args/kube-apiserver`. As you've explained to me before, this option will expose microk8s to all the interfaces existing at the time of installing microk8s.

What I propose is to have this option by default when installing microk8s. Then, we could add a command like `microk8s.refresh-networks` to restart the kubeapi server to expose microk8s in any of the potential new interfaces.

**Comment by balchua** [comment]
My 2 cents, instead of playing with this apiserver arg, maybe we should allow something like `microk8s enable/disable network-refresh`
