### ISSUE TITLE
Microk8s and Ubuntu 21.10 release with Rpi4 8G

### ISSUE THREAD

**Issue by afassio** [canonical/microk8s#2712]
Last version 1.22 does not work with Ubuntu 21.10 release with RPi 4 8Gb but very well with LTS 20.04.
Microk8s goes in endless loop with calico-kube-controllers in ContainerCreating state

**Comment by jonizen** [comment]
I have been chasing down this issue on my 7 node stack. Not sure if you got the same problem but i never got any containers up. Found out that in Ubuntu 21.10 i had to install `sudo apt install linux-modules-extra-raspi` after stop and start it came up and working! :)

**Comment by igorabiola** [comment]
> I have been chasing down this issue on my 7 node stack. Not sure if you got the same problem but i never got any containers up. Found out that in Ubuntu 21.10 i had to install `sudo apt install linux-modules-extra-raspi` after stop and start it came up and working! :)

just tested this on my cluster and it worked, thanks!

**Comment by jonizen** [comment]
After spending some time on the issue, I took out two nodes and did a fresh install on these. Picked up both 20.04 LTS AND 20.10. Both having trouble with iptables pointing to /modules for older rpi headers that does not exist. 

Tried a upgrade from 20.04 ==> 20.10 but it failed. I could see upgrading that generating headers failed too. 

It probably works if you got an older ubuntu version that you upgraded for a while. 

Can drop logs and output from inspect tomorrow 😊

**Comment by CharlesGillanders** [comment]
That's extremely helpful!  Thank you @jonizen - that was the answer for me.  All working correctly now on 21.10

**Comment by ktsakalozos** [comment]
Thank you for troubleshooting this issue @jonizen . The RPi installation instructions [1] and the troubleshooting section [2] in our docs have now references to this fix.

Maybe we could have the inspection script to detect this situation and propose a solution [3].

Many thanks.

[1] https://microk8s.io/docs/install-alternatives#heading--arm
[2] https://microk8s.io/docs/troubleshooting#heading--common-issues
[3] https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh#L125

**Comment by jonizen** [comment]
Glad to hear that it works. It is a bit strange, i ripped out another node to start over on 4 equal Raspberry pi 4s to have the same state and installed all on 20.04 LTS. One works as ussual and 2 does not.... 😀 

So let me start over again and see if it is possible to reproduce on all three. 

I have now flashed 3 of my ssd that are connected with USB to SATA connector. All flashed with Ubuntu 20.04 LTS and added ssh file to it.

![image](https://user-images.githubusercontent.com/1162489/140889004-8d8b1bee-1cdb-42b6-91e4-3e5034d35ea3.png)

Then running:
`sudo apt update
sudo apt full-upgrade`

looking into the apt full-upgrade log, i can see this:

`update-initramfs: Generating /boot/initrd.img-5.4.0-1045-raspi
W: missing /lib/modules/5.4.0-1045-raspi
W: Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/5.4.0-1045-raspi: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
cat: /var/tmp/mkinitramfs_Q9XvDZ/lib/modules/5.4.0-1045-raspi/modules.builtin: No such file or directory
depmod: WARNING: could not open modules.order at /var/tmp/mkinitramfs_Q9XvDZ/lib/modules/5.4.0-1045-raspi: No such file or directory
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_Q9XvDZ/lib/modules/5.4.0-1045-raspi: No such file or directory
Using DTB: bcm2711-rpi-4-b.dtb
Installing /lib/firmware/5.4.0-1045-raspi/device-tree/broadcom/bcm2711-rpi-4-b.dtb into /boot/dtbs/5.4.0-1045-raspi/./bcm2711-rpi-4-b.dtb
Taking backup of bcm2711-rpi-4-b.dtb.
Installing new bcm2711-rpi-4-b.dtb.
Installing /lib/firmware/5.4.0-1045-raspi/device-tree/broadcom/bcm2711-rpi-4-b.dtb into /boot/dtbs/5.4.0-1045-raspi/./bcm2711-rpi-4-b.dtb
Taking backup of bcm2711-rpi-4-b.dtb.
Installing new bcm2711-rpi-4-b.dtb.
flash-kernel: deferring update (trigger activated)
update-initramfs: Generating /boot/initrd.img-5.4.0-1042-raspi
W: missing /lib/modules/5.4.0-1042-raspi
W: Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/5.4.0-1042-raspi: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
cat: /var/tmp/mkinitramfs_aiAPA2/lib/modules/5.4.0-1042-raspi/modules.builtin: No such file or directory
depmod: WARNING: could not open modules.order at /var/tmp/mkinitramfs_aiAPA2/lib/modules/5.4.0-1042-raspi: No such file or directory
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_aiAPA2/lib/modules/5.4.0-1042-raspi: No such file or directory
Using DTB: bcm2711-rpi-4-b.dtb
Installing /lib/firmware/5.4.0-1042-raspi/device-tree/broadcom/bcm2711-rpi-4-b.dtb into /boot/dtbs/5.4.0-1042-raspi/./bcm2711-rpi-4-b.dtb
Installing new bcm2711-rpi-4-b.dtb.
Ignoring old or unknown version 5.4.0-1042-raspi (latest is 5.4.0-1045-raspi)
Setting up python3-problem-report (2.20.11-0ubuntu27.21) ...`

but it finish and everything seems alright...


![image](https://user-images.githubusercontent.com/1162489/140890801-b67e01ac-240e-4185-a131-411e64e671af.png)

going into `sudo vi /boot/firmware/cmdline.txt` and change 
`net.ifnames=1 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc` 

to ==> 
`cgroup_enable=memory cgroup_memory=1 net.ifnames=1 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc` and then reboot.


Running `sudo snap install microk8s --classic --channel=1.22`
![image](https://user-images.githubusercontent.com/1162489/140892644-8ae93814-7197-4599-a24f-c4d97da8e6ca.png)

running 
`sudo usermod -a -G microk8s ubuntu
sudo chown -f -R ubuntu ~/.kube
sudo reboot
` 
running `microk8s status --wait-ready` but nothing happens, waiting for 5-10 mins then abort.
trying to get pod or status fails.

![image](https://user-images.githubusercontent.com/1162489/140895830-7b160279-d79d-43b7-b470-3293b41cc3e2.png)


looking into `journalctl -u snap.microk8s.daemon-kubelite.service` shows:


`Nov 09 08:48:03 ubuntu microk8s.daemon-kubelite[4320]: ERROR: problem running iptables: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.13.0-1008-raspi
Nov 09 08:48:03 ubuntu microk8s.daemon-kubelite[4320]: iptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Nov 09 08:48:03 ubuntu microk8s.daemon-kubelite[4320]: Perhaps iptables or your kernel needs to be upgraded.
Nov 09 08:48:03 ubuntu microk8s.daemon-kubelite[4097]: + ufw=
Nov 09 08:48:03 ubuntu systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=1/FAILURE
Nov 09 08:48:03 ubuntu systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
Nov 09 08:48:03 ubuntu systemd[1]: snap.microk8s.daemon-kubelite.service: Scheduled restart job, restart counter is at 1.` 


if i try running iptables it fails:

`sudo iptables -L
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.13.0-1008-raspi
iptables v1.8.4 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`

guess that this is the problem. On my working node that is in my stack (none of the nodes i took out.) i can see that it runs on ubuntu 20.10 - `Welcome to Ubuntu 21.10 (GNU/Linux 5.13.0-1009-raspi aarch64`

Maybe som help in pin this down? 😄 

Attach inspection files t
[inspection-report-20211109_092323.tar.gz](https://github.com/ubuntu/microk8s/files/7503536/inspection-report-20211109_092323.tar.gz)
o!

**Comment by jonizen** [comment]
As i suspected, on my working nodes I can see:

![image](https://user-images.githubusercontent.com/1162489/140899496-e30fd36a-b28c-4f79-ab35-8807295c072a.png)

probably why it works on some nodes but on new ones it doesn't...

![image](https://user-images.githubusercontent.com/1162489/140899910-866dd970-e193-4988-8034-b74dedef6866.png)
this is what it should be i guess.

**Comment by Theoi-Meteoroi** [comment]
I found one other kernel setting was needed with 21.10 to get the 1.21.6 channel to work.  I haven't tried 1.22 because it breaks many CRDs that have not been updated to V1.
 [See here](https://github.com/ubuntu/microk8s/issues/1691#issuecomment-977543458)
