### ISSUE TITLE
Microk8s on mac keep failing?

### ISSUE THREAD

**Issue by leeadh** [canonical/microk8s#2717]
As shown

microk8s status --wait-ready
sudo: microk8s.status: command not found
An error occurred when trying to execute 'sudo microk8s.status --wait-ready' with 'multipass': returned exit code 1.

Why is this happening?

**Comment by ktsakalozos** [comment]
Hi @leeadh,

Is the Multipass VM running? Can you get a shell in the VM (with `multipass shell microk8svm`) and see if MicroK8s is running there?
