### ISSUE TITLE
Storage folder with read only access

### ISSUE THREAD

**Issue by cfonseca-elsevier** [canonical/microk8s#2719]
I'm running a Microk8s cluster with two nodes running Ubuntu 20.04.3 LTS.
On the cluster I have enabled local storage using microk8s.enable storage.
Everything seem to work well except all the pods that try to use storage on node1 have access permissions problems.
what I realized is that when the directory are crested on /var/snap/microk8s/common/default-storage/ on node1 they have different permissions then on node 2 .
for example Node 1:
` drwxr-xr-x 2 root root 4096 Nov  9 12:06 default-data-rabbitmq-0-pvc-5a75436c-1e41-43eb-80d5-358c0771a77c`
Node 2:
`drwxrwxrwx 2 root root 4096 Nov  9 09:56 default-data-rabbitmq-0-pvc-5a75436c-1e41-43eb-80d5-358c0771a77c`

So the pod on Node 1 fails because of access rights, and only starts when I go to node 1 and manually do: 
`sudo chmod +777 /var/snap/microk8s/common/default-storage/default-data-rabbitmq-0-pvc-5a75436c-1e41-43eb-80d5-358c0771a77c`

this happens every single time node1 get assigned a pod that needs a volume.

Any ideas?

[inspection-report-20211109_123605.tar.gz](https://github.com/ubuntu/microk8s/files/7504727/inspection-report-20211109_123605.tar.gz)
.

**Comment by balchua** [comment]
Hi @cfonseca-elsevier i am going to guess, the `hostpath-provisoner` is running on node2.
The chmod 777 done by the provisioner only works where the provisioner is running.

Hostpath is only usable for single nodes.  If you want the pods to access the local storage, i normally use this https://github.com/rancher/local-path-provisioner

Or use OpenEBS addon and use its local path provisioner.

**Comment by cfonseca-elsevier** [comment]
Hello Balchua.  Yes that is my guess also.  there should be a big caveat on using local storage as it is on multi node, and for sure not to use it when the cluster is using different architectures in the nodes... i have a mix of arm and x86_64, and the pod used for  hostpath-provisoner used a container based of the node where we enable the storage, so after a restart for example local storage stopped working because it tried to start an arm pod in an xb86_84 node... 

Thanks for the link I will give it a go.

**Comment by doggy8088** [comment]
I have the same issue. Reproduce steps here: https://gist.github.com/doggy8088/ce56e10152accee429425a36ef0ac909

The storage class creating a PVC and create PV on each nodes. The hostPath folder only apply `777` permission on `microk8s-vm` (master node).  All worker nodes are `755` permission, so that the Redis cause `Can't open the append-only file: Permission denied` and unable to started correctly.

Is it a bug on `storage` add-on?
