### ISSUE TITLE
Microk8s not starting - Offline

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [canonical/microk8s#2727]
Hi Microk8s team,

We are trying to setup Microk8s in an offline environment, and we are facing few issues with starting microk8s.

We have downloaded the snaps manually and installed without internet, and for cni images concern we are loading the below images into ctr for microk8s to run since there are reqd. for Microk8s to start. 

```bash
REPOSITORY                                 TAG              IMAGE ID       CREATED         SIZE
k8s.gcr.io/ingress-nginx/controller        v1.0.0-alpha.2   2b2a6487f032   4 months ago    287MB
k8s.gcr.io/metrics-server/metrics-server   v0.5.0           1c655933b9c5   5 months ago    63.5MB
quay.io/calico/node                        v3.19.1          c4d75af7e098   5 months ago    168MB
quay.io/calico/kube-controllers            v3.17.3          8a89fcd7b1c0   8 months ago    52.1MB
calico/pod2daemon-flexvol                  v3.13.2          77a3fabf99a5   19 months ago   111MB
calico/cni                                 v3.13.2          a89faaa1676a   19 months ago   224MB
cdkbot/hostpath-provisioner-amd64          1.0.0            dc1b767a6407   3 years ago     41.7MB
k8s.gcr.io/pause                           3.1              da86e6ba6ca1   3 years ago     742kB
```
We could see microk8s status is loading for a very long time and even microk8s.inspect returns below services are running

```bash
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
```
When checked kubelite service i found this in loop

```bash
+ '[' -e /var/snap/microk8s/2407/var/lock/stopped.lock ']'
microk8s.daemon-kubelite[17257]: + n=0
microk8s.daemon-kubelite[17257]: + '[' 0 -ge 20 ']'
microk8s.daemon-kubelite[17257]: + ip route
microk8s.daemon-kubelite[17257]: + grep default
microk8s.daemon-kubelite[17257]: + ip -6 route
microk8s.daemon-kubelite[17257]: + grep default
microk8s.daemon-kubelite[17257]: + echo 'Waiting for default route to appear. (attempt 0)'
microk8s.daemon-kubelite[17257]: Waiting for default route to appear. (attempt 0)
```
Surprising thing is, the moment we connect internet, the cluster is starting, and when we tried to remove everything and start again, it's not starting. Any help would be very much appreciated. 

[inspection-report-20211115_205559.tar.gz](https://github.com/ubuntu/microk8s/files/7539704/inspection-report-20211115_205559.tar.gz)

**Comment by Sam-Sundar-Apty** [comment]
`UPDATE`

Looks like the issue is with NIC, so we tried to run microk8s in a server which is on private N/W without access to internet and this error seems to be gone. Is there any other things we might have to look into apart from downloading below images for add-ons ?

For helm, i just download helm binary from `helm.sh` and then ran below command for helm to get `.kube/config`file.

`microk8s.kubectl config view --raw > $HOME/.kube/config`
 
 Hey @balchua,
 
 Please let us know if these are only images we reqd. since we enable these add-ons `dashboard dns ha-cluster helm3 ingress metrics-server registry storage`
 ```yaml
k8s.gcr.io/ingress-nginx/controller:v1.0.0-alpha.2
k8s.gcr.io/metrics-server/metrics-server:v0.5.0        
quay.io/calico/node:v3.19.1       
quay.io/calico/kube-controllers:v3.17.3       
calico/pod2daemon-flexvol:v3.13.2       
calico/cni:v3.13.2       
cdkbot/hostpath-provisioner-amd64:1.0.0         
k8s.gcr.io/pause:3.1        
coredns/coredns:1.8.0   
```

**Comment by balchua** [comment]
@Sam-Sundar-Apty 
Yes these are the images that should be there.

Are you planning to run a single node microk8s or a multi node?
If you plan to run a multi node cluster, then the `storage` addon and registry isn't going to work just like that.  You need to pin it to a specific node. 

I suggest if you have a private registry, you can load these images into your private registry and serve it from there.
At the minimum you need to change the following files.
To address the `pause` container image, you need to replace the file `/var/snap/microk8s/current/args/containerd-template.toml` and replace the location of the pause container.

To address the cni calico images.  Go to the file `/var/snap/microk8s/current/args/cni-network/cni.yaml` and change the registry path of `calico-node` and `calico-controller`.  Then do `kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml`

While for the dns, its easier to do `microk8s enable dns` then do a `kubectl -n kube-system deployment coredns`

Air gapped install is laboriously hard. ☹️

**Comment by Sam-Sundar-Apty** [comment]
Hey @balchua,


As of now just a single cluster, but will scale up in future, so yeah will follow your instructions.

You guys are AWESOME !!

**Comment by Sam-Sundar-Apty** [comment]
Hey @balchua,

We are facing a small hiccup in enabling `helm3` in offline mode, in `actions/enable.helm3.sh` it's checking `helm3` binary in `"${SNAP_DATA}/bin/helm3"` and if not present,  we see it's downloading helm binary and placing in the same path.

Can you please help us with exact path so that we can manually download helm3 binary and place the same in `"${SNAP_DATA}/bin` path.

Or can we just download helm binary from helm.sh and then run below command for helm to get .kube/configfile.

microk8s.kubectl config view --raw > $HOME/.kube/config

**Comment by balchua** [comment]
The addon scripts are located here.

https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/

With regards to the helm3, you can find it here.
https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.helm3.sh

I think it maybe better to simple download the helm separately and use it independently from Microk8s.  If you go this direction, you will have to export the kubeconfig using `microk8s config`

**Comment by Sam-Sundar-Apty** [comment]
Hey @balchua,

Sure i will better use helm by downloading helm binary from helm.sh and then running below command for helm to get .kube/configfile.

`microk8s.kubectl config view --raw > $HOME/.kube/config`
