### ISSUE TITLE
Create Grafana Agent Operator Add-on

### ISSUE THREAD

**Issue by rlankfo** [canonical/microk8s#2743]
The [Grafana Agent ](https://github.com/grafana/agent/) is a telemetry collector for sending metrics, logs, and trace data to the opinionated Grafana observability stack.

The [Agent operator](https://github.com/grafana/agent/tree/main/pkg/operator) is modeled after the prometheus operator but is optimized for remote write.

I propose adding the Grafana Agent Operator as an Add-on in microk8s, similar to the prometheus operator which is already included.

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @rlankfo. I passed your request to our LMA team.

**Comment by rlankfo** [comment]
I should have originally linked out to the docs, this should be helpful: https://grafana.com/docs/agent/latest/operator/getting-started/
