### ISSUE TITLE
Node is in not ready state during Microk8s deployment

### ISSUE THREAD

**Issue by kisakthi** [canonical/microk8s#2748]
Microk8s version - 1.21/stable
OS - Ubuntu 20.04
Container Runtime - CRIO
No errors reported in microk8s inspect

Installation Steps:
1. snap install --channel=1.21/stable microk8s --classic
2. microk8s status --wait-ready
3. microk8s.stop
4. microk8s.start
5. microk8s.enable dns rbac

~#microk8s.kubectl get nodes
NAME                                   STATUS     ROLES    AGE   VERSION
ubuntu                                 NotReady   <none>   66m   v1.21.3-3+90fd5f3d2aea0a

~# microk8s.kubectl get pods -n kube-system
NAME                                      READY   STATUS     RESTARTS   AGE
calico-kube-controllers-f7868dd95-n7hwh   0/1     Pending    0          74m
calico-node-rpsjs                         0/1     Init:0/3   0          74m

Error: 
FailedScheduling 40m default-scheduler 0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.

~# snap services microk8s
Service Startup Current Notes
microk8s.daemon-apiserver enabled inactive -
microk8s.daemon-apiserver-kicker enabled active -
microk8s.daemon-cluster-agent enabled active -
microk8s.daemon-containerd enabled active -
microk8s.daemon-control-plane-kicker enabled inactive -
microk8s.daemon-controller-manager enabled inactive -
microk8s.daemon-etcd enabled inactive -
microk8s.daemon-flanneld enabled inactive -
microk8s.daemon-kubelet enabled inactive -
microk8s.daemon-kubelite enabled active -
microk8s.daemon-proxy enabled inactive -
microk8s.daemon-scheduler enabled inactive -

**Comment by balchua** [comment]
This log you pointed out
```
Error:
FailedScheduling 40m default-scheduler 0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.
```
Is suggesting that your node maybe low on disk storage.  Im going to guess your `/var` is full.

**Comment by kisakthi** [comment]
@balchua I verified disk storage. Around 70% is free. So it's not related to storage.
