### ISSUE TITLE
enabling metallb occasionally fails with "connection refused"

### ISSUE THREAD

**Issue by sed-i** [canonical/microk8s#2770]
## Intro
I use terraform to provision machines for load testing.

## Environment
GCP instance from a ready-made custom image with microk8s and juju preinstalled ([full details](https://github.com/canonical/lma-light-bundle/pull/15)).

| Tool | Version |
|------|---------|
| OS | Ubuntu 21.04, Linux 5.11.0-1021-gcp|
| juju     | 2.9.19-ubuntu-amd64        |
| microk8s | 1.22.4 |

```
$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

# Warning: iptables-legacy tables present, use iptables-legacy to see them
Building the report tarball
  Report tarball is at /var/snap/microk8s/2695/inspection-report-20211130_152124.tar.gz
```
[inspect.tar.gz](https://github.com/ubuntu/microk8s/files/7626865/inspect.tar.gz)

## Steps to reproduce
```shell
systemctl disable systemd-tmpfiles-clean.timer --now
microk8s status --wait-ready
microk8s.enable storage dns ingress

IPADDR=$(ip -4 -j route | jq -r '.[] | select(.dst | contains("default")) | .perfsrc')
microk8s.enable metallb:$IPADDR-$IPADDR
```

## Expected result
Enabling metallb after `microk8s status --wait-ready` should work without error every time.

## Actual result
Occasionally, enabling metallb will fail with the following error:
`The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?`

Currently I use a workaround:
`until microk8s.enable metallb:$IPADDR-$IPADDR; do sleep 5; done`

**Comment by ktsakalozos** [comment]
Hi @sed-i,

The connection refused error you are seeing is because K8s restarts. The reason is most probably because when enabling DNS new arguments are added to k8s services and they need to be loaded via services restart. The way to handle this is to place the enable dns command first and in a separate line and wait for the DNS deployment to complete with something like `kubectl rollout status -w`.

**Comment by sed-i** [comment]
I suspect I encountered another race condition:
When I enable `metric-server` at the same time as `ingress`, followed by
`microk8s.kubectl rollout status daemonsets/nginx-ingress-microk8s-controller -n ingress -w --timeout=600s`
I get
`Error from server (NotFound): namespaces "ingress" not found`
