### ISSUE TITLE
Micork8s not running, stop/start does not fix, inspection report attached.

### ISSUE THREAD

**Issue by zhaminglei** [canonical/microk8s#2774]
Hey,
We are a team developing a software that can be hosted by customer, recently one of them suddenly run into issues that the microk8s stopped working and then everything else stopped working.
Attached is the result of microk8s.inspection, can you please help take a look and help us understand:
- Why did the issue happen?
- How can we fix it?

More context, we got hundreds of customers for the software in couple of months and looking forward to getting thousands in the coming year, it will be super helpful for us to find out the root cause.

Let us know if anything else is needed.

[inspection-report-20211201_005255.tar.gz](https://github.com/ubuntu/microk8s/files/7636006/inspection-report-20211201_005255.tar.gz)

**Comment by MathieuBordere** [comment]
Hi @zhaminglei,

Can you perform `ls -al /var/snap/microk8s/current/var/kubernetes/backend` and paste the contents here?
Will need to investigate how this can happen.

**Comment by ktsakalozos** [comment]
@zhaminglei in the logs I see a lot of entries like this one:
```
Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.547333  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list cert-manager.io/v1alpha2, Kind=Certificate: conversion webhook for cert-manager.io/v1, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.567782  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list acme.cert-manager.io/v1beta1, Kind=Order: conversion webhook for acme.cert-manager.io/v1, Kind=Order failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.568581  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list cert-manager.io/v1beta1, Kind=Certificate: conversion webhook for cert-manager.io/v1, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
```
Is this something expected?

The disk performance is also not great. We regularly see write requests taking longer than 0.5secs reaching up to a couple of seconds. For example:
```
Nov 05 06:19:36 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: Trace[1488074176]: ---"Transaction committed" 2617ms (06:19:00.438)
Nov 05 06:19:36 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: Trace[1488074176]: [2.625206753s] [2.625206753s] END
```

Is this a multi-node cluster?

**Comment by benlinyb** [comment]
@MathieuBordere  
Here you ago. 
-rw-rw---- 1 root microk8s  8379032 Nov  5 06:10 0000000006684859-0000000006685125
-rw-rw---- 1 root microk8s  8360384 Nov  5 06:11 0000000006685126-0000000006685418
-rw-rw---- 1 root microk8s  8370248 Nov  5 06:12 0000000006685419-0000000006685677
-rw-rw---- 1 root microk8s  6772784 Nov  5 06:13 0000000006685678-0000000006686150
-rw-rw---- 1 root microk8s  8384832 Nov  5 06:14 0000000006686151-0000000006686441
-rw-rw---- 1 root microk8s  4819520 Nov  5 06:15 0000000006686442-0000000006686575
-rw-rw---- 1 root microk8s  8363808 Nov  5 06:17 0000000006686576-0000000006686859
-rw-rw---- 1 root microk8s   222200 Nov  5 06:18 0000000006686860-0000000006686867
-rw-rw---- 1 root microk8s  8355024 Nov  5 06:19 0000000006686868-0000000006687143
-rw-rw---- 1 root microk8s  8360024 Nov  5 06:20 0000000006687144-0000000006687374
-rw-rw---- 1 root microk8s  8386664 Nov  5 06:21 0000000006687375-0000000006687633
-rw-rw---- 1 root microk8s  8374856 Nov  5 06:23 0000000006687634-0000000006687899
-rw-rw---- 1 root microk8s  8379320 Nov  5 06:23 0000000006687900-0000000006688455
-rw-rw---- 1 root microk8s  8362256 Nov  5 06:23 0000000006688456-0000000006689059
-rw-rw---- 1 root microk8s  8380256 Nov  5 06:23 0000000006689060-0000000006689628
-rw-rw---- 1 root microk8s  8387024 Nov  5 06:23 0000000006689629-0000000006690234
-rw-rw---- 1 root microk8s  8386808 Nov  5 06:23 0000000006690235-0000000006690837
-rw-rw---- 1 root microk8s  8381264 Nov  5 06:23 0000000006690838-0000000006691420
-rw-rw---- 1 root microk8s  8387600 Nov  5 06:23 0000000006691421-0000000006691977
-rw-rw---- 1 root microk8s  8387456 Nov  5 06:23 0000000006691978-0000000006692532
-rw-rw---- 1 root microk8s  3103472 Nov  5 06:25 0000000006692533-0000000006692715
-rw-rw---- 1 root microk8s  3203232 Nov  5 06:27 0000000006692716-0000000006692859
-rw-rw---- 1 root microk8s  5179344 Nov  5 06:29 0000000006692860-0000000006693032
-rw-rw---- 1 root microk8s  6892992 Nov  5 06:32 0000000006693033-0000000006693294
-rw-rw---- 1 root microk8s  8373384 Nov  5 06:35 0000000006693295-0000000006693597
-rw-rw---- 1 root microk8s  5544488 Nov  5 06:35 0000000006693598-0000000006693768
-rw-rw---- 1 root microk8s     1874 Oct 29 04:19 cluster.crt
-rw-rw---- 1 root microk8s     3272 Oct 29 04:19 cluster.key
-rw-rw---- 1 root microk8s       63 Nov  5 06:36 cluster.yaml
-rw-rw-r-- 1 root microk8s        2 Nov 30 23:43 failure-domain
-rw-rw---- 1 root microk8s       57 Oct 29 04:20 info.yaml
srw-rw---- 1 root microk8s        0 Nov  5 06:32 kine.sock
-rw-rw---- 1 root microk8s       63 Nov  5 06:32 localnode.yaml
-rw-rw---- 1 root microk8s       32 Oct 29 04:20 metadata1
-rw-rw---- 1 root microk8s  8388608 Nov  5 06:36 open-3
-rw-rw---- 1 root microk8s  8388608 Nov  5 06:35 open-4
-rw-rw---- 1 root microk8s  8388608 Nov  5 06:35 open-5
-rw-rw---- 1 root microk8s 10757891 Nov  5 06:23 snapshot-1-6691864-274966167
-rw-rw---- 1 root microk8s       72 Nov  5 06:23 snapshot-1-6691864-274966167.meta
-rw-rw---- 1 root microk8s 10954465 Nov  5 06:27 snapshot-1-6692888-275205515
-rw-rw---- 1 root microk8s       72 Nov  5 06:27 snapshot-1-6692888-275205515.meta

**Comment by zhaminglei** [comment]
> @zhaminglei in the logs I see a lot of entries like this one:
> 
> ```
> Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.547333  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list cert-manager.io/v1alpha2, Kind=Certificate: conversion webhook for cert-manager.io/v1, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
> Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.567782  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list acme.cert-manager.io/v1beta1, Kind=Order: conversion webhook for acme.cert-manager.io/v1, Kind=Order failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
> Nov 05 06:19:27 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: E1105 06:19:27.568581  517731 cacher.go:419] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list cert-manager.io/v1beta1, Kind=Certificate: conversion webhook for cert-manager.io/v1, Kind=Certificate failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found; reinitializing...
> ```
> 
> Is this something expected?
> 
> The disk performance is also not great. We regularly see write requests taking longer than 0.5secs reaching up to a couple of seconds. For example:
> 
> ```
> Nov 05 06:19:36 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: Trace[1488074176]: ---"Transaction committed" 2617ms (06:19:00.438)
> Nov 05 06:19:36 ip-172-31-34-53 microk8s.daemon-kubelite[517731]: Trace[1488074176]: [2.625206753s] [2.625206753s] END
> ```
> 
> Is this a multi-node cluster?

Thanks a lot, 
For your questions:
We had cert-manager running fine on top of microk8s before it stopped working. I don't think Cert-manager is the issue because we have hundreds of other customers running the system pretty well. Is there anything we can check now to confirm any guess you have?
For disk performance, we are using AWS t3.large with EBS storage, same situation that it works fine for other customers as well.
And it is not multi-node cluster.

Thanks a lot again, let us know if any other info we can provide!

**Comment by MathieuBordere** [comment]
Thanks @benlinyb 

Can you:
- stop microk8s, make sure it's not running
- make a backup of `/var/snap/microk8s/current/var/kubernetes/backend`
- delete `open-3`, `open-4`, `open-5` and `0000000006693598-0000000006693768`
- try to start again.
