### ISSUE TITLE
after OS upgrade (Ubuntu 20.04.3 LTS aarch64) microk8s goes crazy 

### ISSUE THREAD

**Issue by golgotow** [canonical/microk8s#2779]
Hello,

After OS update microk8s goes crazy , we tried to investigate it but there was some stuck, scheduler do not starting pods like calico on all nodes , cluster dropping connection on port 16443.

3 nodes ( raspberry pi 4b 8G )
during inspect all services are running.

Can you advice if this is some software bug or how to look for advice ?

root@rpi8g-1:~# microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Building the report tarball
  Report tarball is at /var/snap/microk8s/2628/inspection-report-20211204_155249.tar.gz
root@rpi8g-1:~# 

root@rpi8g-1:~# kubectl get nodes
NAME      STATUS   ROLES    AGE    VERSION
rpi8g-3   Ready    <none>   47d    v1.22.3-3+64e63223b19811
rpi8g-2   Ready    <none>   47d    v1.22.3-3+64e63223b19811
rpi8g-1   Ready    <none>   269d   v1.22.3-3+64e63223b19811

[inspection-report-20211204_155228.tar.gz](https://github.com/ubuntu/microk8s/files/7654117/inspection-report-20211204_155228.tar.gz)
[inspection-report-20211204_155249.tar.gz](https://github.com/ubuntu/microk8s/files/7654118/inspection-report-20211204_155249.tar.gz)
[inspection-report-20211204_155303.tar.gz](https://github.com/ubuntu/microk8s/files/7654119/inspection-report-20211204_155303.tar.gz)

Best regards,

**Comment by ktsakalozos** [comment]
Hi @golgotow,

In the logs (`journalctl -fu snap.microk8s.daemon-kubelite`) I see that there are significant delays in writing to the disk causing the k8s services to misbehave, eg:
```
Dec 04 15:49:31 rpi8g-1 microk8s.daemon-kubelite[57458]: Trace[1455414866]: ---"About to write a response" 11101ms (15:49:31.231)
```

This might be caused by either heavy load that the disks need to serve or problems in storage stack itself. Could you look at the "Raspberry Pi and systems with low disk performance" of the "Common issues" in our docs [1] ? Could you also measure the block I/O latency as described in [2] ?


[1] https://microk8s.io/docs/troubleshooting#heading--common-issues
[2] https://github.com/ubuntu/microk8s/issues/2285#issuecomment-847688045

**Comment by golgotow** [comment]
@ktsakalozos  thanks for tip. Will try to investigate deeper.

quick check shows me that disk usage is consumed only by microk8s and load on rpi also only cause microk8s processes ( pvc and others use nfs or ceph not local storage). This rpi do not use micro sd card at all ( or to boot only), all is based on ssd disk connected via usb with not so bad results .

`root@rpi8g-1:~# hdparm -t /dev/sda

/dev/sda:
 Timing buffered disk reads: 594 MB in  3.00 seconds = 197.89 MB/sec
root@rpi8g-1:~# fio --name=job1 --rw=read --size=1g  --directory=/ --direct=1
job1: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.16
Starting 1 process
job1: Laying out IO file (1 file / 1024MiB)
Jobs: 1 (f=1): [R(1)][100.0%][r=19.0MiB/s][r=5113 IOPS][eta 00m:00s]
job1: (groupid=0, jobs=1): err= 0: pid=1118132: Sun Dec  5 11:27:05 2021
  read: IOPS=5169, BW=20.2MiB/s (21.2MB/s)(1024MiB/50708msec)
    clat (usec): min=137, max=19110, avg=189.43, stdev=233.04
     lat (usec): min=137, max=19111, avg=189.87, stdev=233.08
    clat percentiles (usec):
     |  1.00th=[  143],  5.00th=[  145], 10.00th=[  147], 20.00th=[  153],
     | 30.00th=[  159], 40.00th=[  165], 50.00th=[  169], 60.00th=[  174],
     | 70.00th=[  180], 80.00th=[  186], 90.00th=[  208], 95.00th=[  241],
     | 99.00th=[  465], 99.50th=[  857], 99.90th=[ 4817], 99.95th=[ 5866],
     | 99.99th=[ 7439]
   bw (  KiB/s): min=17232, max=23480, per=99.90%, avg=20657.93, stdev=1366.45, samples=101
   iops        : min= 4308, max= 5870, avg=5164.46, stdev=341.58, samples=101
  lat (usec)   : 250=95.67%, 500=3.42%, 750=0.34%, 1000=0.16%
  lat (msec)   : 2=0.20%, 4=0.09%, 10=0.12%, 20=0.01%
  cpu          : usr=4.12%, sys=20.80%, ctx=263070, majf=0, minf=24
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=262144,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=20.2MiB/s (21.2MB/s), 20.2MiB/s-20.2MiB/s (21.2MB/s-21.2MB/s), io=1024MiB (1074MB), run=50708-50708msec

Disk stats (read/write):
  sda: ios=262130/714, merge=1/985, ticks=42110/1226, in_queue=1892, util=99.75%
`

**Comment by golgotow** [comment]
I did check I/O as described, results not so bad, Im not sure this can be real problem in this scenario where that cluster goes crazy, for me this looks like some microk8s issue ( I have similar hardware setups for k3s and k8s clusters without similar problems at all ) , but Im not able to find proper evidences that this is not my fault somewhere 

root@rpi8g-1:~# hdparm -Tt /dev/sda ; dd if=/dev/zero of=/tmp/test1.img bs=1G count=1

/dev/sda:
 Timing cached reads:   1376 MB in  2.00 seconds = 688.87 MB/sec
 Timing buffered disk reads: 564 MB in  3.00 seconds = 187.71 MB/sec
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 7.43739 s, 144 MB/s

root@rpi8g-2:~# hdparm -Tt /dev/sda ; dd if=/dev/zero of=/tmp/test1.img bs=1G count=1

/dev/sda:
 Timing cached reads:   1404 MB in  2.00 seconds = 702.90 MB/sec
 Timing buffered disk reads: 100 MB in  3.03 seconds =  33.00 MB/sec
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 38.9475 s, 27.6 MB/s

root@rpi8g-3:~# hdparm -Tt /dev/sda ; dd if=/dev/zero of=/tmp/test1.img bs=1G count=1

/dev/sda:
 Timing cached reads:   1450 MB in  2.00 seconds = 725.23 MB/sec
 Timing buffered disk reads: 558 MB in  3.00 seconds = 185.74 MB/sec
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 6.99692 s, 153 MB/s

**Comment by ktsakalozos** [comment]
What about the block I/O latency https://github.com/ubuntu/microk8s/issues/2285#issuecomment-847688045 ?

**Comment by golgotow** [comment]
@ktsakalozos tested during dd

root@rpi8g-1:~# bcc.biolatency
Tracing block device I/O... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 0        |                                        |
       128 -> 255        : 6        |**************                          |
       256 -> 511        : 7        |****************                        |
       512 -> 1023       : 1        |**                                      |
      1024 -> 2047       : 0        |                                        |
      2048 -> 4095       : 17       |****************************************|

**Comment by ktsakalozos** [comment]
This is not conclusive @golgotow the I/O operations run on the background were too few. Could you let the dd on the background run for a longer time?

**Comment by golgotow** [comment]
done during dd

root@rpi8g-1:~# dd if=/dev/zero of=/mnt/test.file bs=1M
^C21327+0 records in
21327+0 records out
22362980352 bytes (22 GB, 21 GiB) copied, 177.199 s, 126 MB/s




root@rpi8g-1:~# bcc.biolatency
Tracing block device I/O... Hit Ctrl-C to end.
^C
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 25       |                                        |
        32 -> 63         : 397      |                                        |
        64 -> 127        : 4046     |**                                      |
       128 -> 255        : 11750    |*******                                 |
       256 -> 511        : 6088     |****                                    |
       512 -> 1023       : 17080    |***********                             |
      1024 -> 2047       : 59840    |****************************************|
      2048 -> 4095       : 10973    |*******                                 |
      4096 -> 8191       : 3509     |**                                      |
      8192 -> 16383      : 2042     |*                                       |
     16384 -> 32767      : 1032     |                                        |
     32768 -> 65535      : 378      |                                        |
     65536 -> 131071     : 89       |                                        |
root@rpi8g-1:~#
