### ISSUE TITLE
microk8s chugging up the CPU

### ISSUE THREAD

**Issue by strgalt-t** [canonical/microk8s#2785]
Hello!

on my Fedora workstation I usually have microk8s idling in the background. 
Today I've noticed that it starts chugging up all my CPU resource.

Excerpt from journalctl -fu snap.microk8s.daemon-kubelite:

>Dez 07 14:59:47 p50 microk8s.daemon-kubelite[1951605]: I1207 14:59:47.023168 1951605 scope.go:110] "RemoveContainer" containerID="7966a221fcf158cc06857deb406239d176c89a6eba22a568bf07334f9dd546d1"
>Dez 07 14:59:47 p50 microk8s.daemon-kubelite[1951605]: E1207 14:59:47.023438 1951605 pod_workers.go:836] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"calico-kube-controllers\" with CrashLoopBackOff: \"back-off 40s restarting failed container=calico-kube-controllers pod=calico-kube-controllers-5d56697478-pslhh_kube-system(ae61d0f3-1490-4e1d-9097-0342d846f0c7)\"" pod="kube-system/calico-kube-controllers-5d56697478-pslhh" podUID=ae61d0f3-1490-4e1d-9097-0342d846f0c7
>Dez 07 14:59:57 p50 microk8s.daemon-kubelite[1951605]: I1207 14:59:57.888656 1951605 scope.go:110] "RemoveContainer" containerID="7966a221fcf158cc06857deb406239d176c89a6eba22a568bf07334f9dd546d1"
>Dez 07 14:59:57 p50 microk8s.daemon-kubelite[1951605]: E1207 14:59:57.888997 1951605 pod_workers.go:836] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"calico-kube-controllers\" with CrashLoopBackOff: \"back-off 40s restarting failed container=calico-kube-controllers pod=calico-kube-controllers-
[inspection-report-20211207_150029.tar.gz](https://github.com/ubuntu/microk8s/files/7668837/inspection-report-20211207_150029.tar.gz)
5d56697478-pslhh_kube-system(ae61d0f3-1490-4e1d-9097-0342d846f0c7)\"" pod="kube-system/calico-kube-controllers-5d56697478-pslhh" podUID=ae61d0f3-1490-4e1d-9097-0342d846f0c7

Restarting microk8s does not fix the problem.
Attached is my microk8s inspect report.

**Comment by ktsakalozos** [comment]
Hi @strgalt-t I see in the logs (`journalctl -fu snap.microk8s.daemon-kubelite`) that kubelet is failing to start with 
```
"Failed to start cAdvisor" err="inotify_init: too many open files"
```
Could this be related to some other workload running on the machine?

**Comment by strgalt-t** [comment]
Hey @ktsakalozos, sorry for the late reply.

I can't think of a particular workload that might have caused this as for work I usually only run my webbrowser and a terminal.
