### ISSUE TITLE
Microk8s high-availability not working

### ISSUE THREAD

**Issue by bkonicek** [canonical/microk8s#2796]
I created a microk8s cluster and added 2 nodes to it, following the instructions in the high-availability documentation.

```
NAME       STATUS   ROLES    AGE   VERSION
master02   Ready    <none>   25h   v1.21.7-3+7700880a5c71e2
master03   Ready    <none>   22h   v1.21.7-3+7700880a5c71e2
master01   Ready    <none>   92d   v1.21.7-3+7700880a5c71e2
```

The `ha-cluster` addon was enabled by default
```
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
```

but `microk8s status` is still showing `high-availability: no`
```
high-availability: no
  datastore master nodes: 192.168.30.10:19001
  datastore standby nodes: none
```

I tried setting the fault-domain on each node but it didn't seem to make a difference.

Here are the inspect tarballs
[master01.tar.gz](https://github.com/ubuntu/microk8s/files/7707475/master01.tar.gz)
[master02.tar.gz](https://github.com/ubuntu/microk8s/files/7707476/master02.tar.gz)
[master03.tar.gz](https://github.com/ubuntu/microk8s/files/7707477/master03.tar.gz)

**Comment by balchua** [comment]
Looking at the logs, it looks like dqlite formed the cluster.

Can you try running this on all the three nodes and paste it here?

```shell
sudo -E /snap/microk8s/current/bin/dqlite -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml k8s ".cluster"
```

**Comment by bkonicek** [comment]
On all three the output is 
```
2dc171858c3155be|192.168.30.10:19001|voter
b26793c27bc8e282|192.168.30.21:19001|spare
```

`master02` is the node whose IP is not listed in the output

**Comment by bkonicek** [comment]
I left/removed the node from the cluster, did a `microk8s reset` and then joined back and now HA is enabled and showing all 3 nodes as datastore masters, thanks for the help!

**Comment by adubkov** [comment]
Same thing happen to me. @bkonicek  Which node did you remove and reset to get it fixed? The one `spare` one or the `voter`?

**Comment by bkonicek** [comment]
Neither of them - I removed the node that's IP was not listed in that output.

**Comment by adubkov** [comment]
Got it. Actually in my case I have just 2 nodes and base don source code minimum of 3 nodes are required for HA to work.

**Comment by XtremeOwnageDotCom** [comment]
``` yaml
root@kube04:/var/snap/microk8s/current/var/kubernetes/backend# sudo -E /snap/microk8s/current/bin/dqlite -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml k8s ".cluster"
3512b267276f9e10|10.100.5.104:19001|voter
9d882e0fe91f400e|10.100.5.100:19001|spare
a75b3778b41ff791|10.100.5.105:19001|spare
```

```
root@kube04:/var/snap/microk8s/current/var/kubernetes/backend# microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 10.100.5.104:19001
  datastore standby nodes: none
```

MicroK8s doesn't like me tonight.

**Comment by XtremeOwnageDotCom** [comment]
And this, is why I switched to rancher/k3s.
