### ISSUE TITLE
Version 1.22/stable for ppc64el?

### ISSUE THREAD

**Issue by ArneSodal** [canonical/microk8s#2810]
Hi.

How do I install microk8s 1.22/stable for Ubuntu 20.04.3 LTS running on POWER9 architecture?

If I run the following:
root@myserver:~# snap info microk8s
name:      microk8s
summary:   Kubernetes for workstations and appliances
publisher: Canonical✓
store-url: https://snapcraft.io/microk8s
contact:   https://github.com/ubuntu/microk8s
license:   Apache-2.0
description: |
  MicroK8s is a small, fast, secure, single node Kubernetes that installs on
  just about any Linux box. Use it for offline development, prototyping,
  testing, or use it on a VM as a small, cheap, reliable k8s for CI/CD. It's
  also a great k8s for appliances - develop your IoT apps for k8s and deploy
  them to MicroK8s on your boxes.
snap-id: EaXqgt1lyCaxKaQCU349mlodBkDCXRcg
channels:
  latest/stable:    v1.11.1 2019-03-28 (136) 162MB classic
  latest/candidate: v1.11.1 2019-03-28 (136) 162MB classic
  latest/beta:      v1.11.1 2019-03-28 (136) 162MB classic
  latest/edge:      v1.11.1 2019-02-11 (136) 162MB classic
  1.10/stable:      –
  1.10/candidate:   –
  1.10/beta:        –
  1.10/edge:        v1.11.1 2018-07-24 (136) 162MB classic

...it is telling me that v1.11 is the latest. But I need version 1.20. 

How do I install version 1.20/stable?

Thanks in advance.

/ Arne

**Comment by ktsakalozos** [comment]
Hi @ArneSodal,

MicroK8s is not supported on ppc64el and it is not in our immediate plans to work on this task.

I am going to forward your request to the product management. Are you interested in collaborating in this effort?

Thanks

**Comment by neoaggelos** [comment]
Update: We are working on getting MicroK8s to build on ppc64le architectures, and it will be supported (starting with version 1.25 in August 2022)
