### ISSUE TITLE
Error Unable to connect to the server ... after reboot.

### ISSUE THREAD

**Issue by p770820** [canonical/microk8s#2821]
I create microk8s and node1.

windows 10 hyper-v
![image](https://user-images.githubusercontent.com/9010279/148286581-f6b73623-2023-421f-8d48-3f2e8041a10d.png)

I use powershell ,my step :
1. `microk8s install`
2. `microk8s config > ~/.kube/config`
3. `multipass launch --name node1`
4. `multipass exec node1 -- sudo snap install microk8s --classic`
5. `multipass exec node1 -- sudo usermod -a -G microk8s ubuntu`
6. `multipass exec node1 -- sudo chown -f -R ubuntu ~/.kube`
7. `microk8s add-node`
8. `multipass exec node1 -- sudo microk8s join xxx.xxx.xxx.xxx:port/d008396d18bf5c02916190063a90a055/d2b3c4a95057`

I use `microk8s kubectl get nodes` work.
but  use `microk8s kubectl get nodes`  and it's not work  after I reboot.
I get this error:
```
Unable to connect to the server: dial tcp 172.17.90.120:16443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

![image](https://user-images.githubusercontent.com/9010279/148285729-58146009-0051-4302-9df1-d87c80bf4c78.png)

I use "microk8s inspect". **FAIL:  Service snap.microk8s.daemon-kubelite is not running**

```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
 FAIL:  Service snap.microk8s.daemon-kubelite is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelite
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2695/inspection-report-20220106_040606.tar.gz
An error occurred when trying to execute 'sudo microk8s.inspect' with 'multipass': returned exit code 1.
```

reinstall is ok, but I can't reinstall every time when I get this problem.
can help? thanks.

**Comment by ktsakalozos** [comment]
Hi @p770820, thank you for reaching out.

The problem is probably because the node/VM got a different IP after the reboot. Nodes are not supposed to change IPs in multi-node clusters. Have a look at this issue [1] on how to set a static IP in multipass.

[1] https://github.com/canonical/multipass/issues/567

**Comment by p770820** [comment]
Hi @ktsakalozos 

first, thank you.
I saw your link "[canonical/multipass#567](https://github.com/canonical/multipass/issues/567)" but I don't know how to set it right?

my 50-cloud-init.yaml
I set dhcp4 to false, because it is true and will create new ip.
I add addresses and set my ip 172.30.200.22/20
```
network:
    ethernets:
        eth0:
            dhcp4: false
            match:
                macaddress: 52:54:00:ee:96:8f
            set-name: eth0
            addresses:
            - 172.30.200.22/20
    version: 2
```

sudo netplan try
sudo netplan apple
it's ok.

and then I key 'ip a' , I see the word "forever" I think it maybe tells me it's static ip.
![image](https://user-images.githubusercontent.com/9010279/149134843-43e2de64-97dd-4b56-ae3b-8b413f20cf59.png)

but I microk8s stop and microk8s start , broken. so sad!
![image](https://user-images.githubusercontent.com/9010279/149135210-a2ac3fa9-6bf1-4019-ac30-a375f7fa725a.png)

I use "microk8s inspect"
```
Inspecting Certificates
Inspecting services
 FAIL:  Service snap.microk8s.daemon-cluster-agent is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-cluster-agent
 FAIL:  Service snap.microk8s.daemon-containerd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-containerd
 FAIL:  Service snap.microk8s.daemon-apiserver-kicker is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver-kicker
 FAIL:  Service snap.microk8s.daemon-kubelite is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelite
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2695/inspection-report-20220112_193821.tar.gz
```

**Comment by p770820** [comment]
I google "how to set static ip hyper-v ubuntu vm."
https://www.youtube.com/watch?v=UwY282FAPCM

so sad. I can't connect microk8s-vm.
```
shell failed: ssh connection failed: 'Timeout connecting to microk8s-vm.mshome.net'
```
![image](https://user-images.githubusercontent.com/9010279/149306615-9da6d9e0-5916-479d-ae23-fca7db52cdab.png)

**Comment by p770820** [comment]
[canonical/multipass#567](https://github.com/canonical/multipass/issues/567) ,
I don't understand how to use "*.mshome.net" in Win 10 for setting same ip.

**Comment by doggy8088** [comment]
@p770820 Check this out: https://ithelp.ithome.com.tw/articles/10283724

**Comment by p770820** [comment]
@doggy8088 I know the post. this author is your employee, John Hsu.
