### ISSUE TITLE
Removing microk8s snap doesn't kill calico-node

### ISSUE THREAD

**Issue by MrMYHuang** [canonical/microk8s#2824]
microk8s version: microk8s (1.22/stable) v1.22.4

Steps to reproduce the bug:
```
sudo snap install microk8s --classic
microk8s kubectl get pod -A --watch
```
Then, wait until calico-node is ready.

Then, run `sudo snap remove microk8s`. You will find calico-node still run by `ps aux|grep calico-node`.
```
myh@alston-ubuntu:~$ ps aux|grep calico-node
root     1212222  5.1  0.1 1953788 58432 ?       Sl   14:07   0:14 calico-node -felix
```
It continues generating iptables-legacy rules (even if do flush rules and delete chains) and breaks cilium L7 policy functions (see https://github.com/cilium/cilium/issues/18350#issuecomment-1008565309).

A workaround is killing calico-node manually.

**Comment by sbe-arg** [comment]
This issue is very annoying...
