### ISSUE TITLE
round-robin doesn't work with metallb

### ISSUE THREAD

**Issue by fogost** [canonical/microk8s#2825]
Hello, i'm trying to setup simple round-robin load balancing example.

Cluster setup:
`microk8s enable dns`
`microk8s enable metallb`

Application setup:
`microk8s kubectl create deployment microbot --image=dontrebootme/microbot:v1`
`microk8s kubectl scale deployment microbot --replicas=4`
`kubectl expose deployment microbot --port=80 --target-port=80 --name=microbot-service --type=LoadBalancer`

And after this i can see my service, but when i press f5 i always see the same pod `microbot-5f5499d479-qs5l6`. But I expected that I would see **different pod ids**. So how i can setup round-robin load balancing with microk8s and metallb?
![image](https://user-images.githubusercontent.com/5126657/148750929-3cad32ad-c575-4f90-bdd5-267dff535bb0.png)

[inspection-report-20220110_101936.tar.gz](https://github.com/ubuntu/microk8s/files/7838184/inspection-report-20220110_101936.tar.gz)

**Comment by Luke-Tang** [comment]
Please see [kubernetes in action](https://www.manning.com/books/kubernetes-in-action)，section 5.3.2.
