### ISSUE TITLE
Hotfix for log4j issue not released in 1.22 snap package

### ISSUE THREAD

**Issue by watzo** [canonical/microk8s#2830]
Steps to reproduce:

Look at output from snap build
(https://github.com/ubuntu/microk8s/actions/runs/1664501450)

Expected outcome: a published snap package for 1.22 (1.22.5) on the stable channel

Actual outcome: a failed build

**Comment by ktsakalozos** [comment]
Hi @watzo, indeed at the time the log4j fix was merged the build of 1.22 was failing and that was addressed in a more recent commit. See https://github.com/ubuntu/microk8s/commits/1.22

**Comment by ktsakalozos** [comment]
Hi @watzo we are working on releasing the fixes to the beta, candidate and stable.

**Comment by watzo** [comment]
That is great news. Thanks again!
