### ISSUE TITLE
cluster broken after adding a kvm guest 

### ISSUE THREAD

**Issue by AVSuni** [canonical/microk8s#2841]
I have a 3 (physical) node cluster where I recently added one KVM guest as a fourth node. Within 24h the KVM host node has almost all of its pods in "unknown" state. I have tried to drain the node, but I get 

```
error when evicting pods/"argocd-applicationset-controller-76fc4dc766-7phr6" -n "argocd": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"gpu-operator-7db468cfdf-mgx29" -n "default": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"postgres-546d9d68b-gtxrq" -n "argo": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"cert-manager-cainjector-748dc889c5-v6gfc" -n "cert-manager": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"argocd-redis-5b6967fdfc-m5g48" -n "argocd": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"argocd-server-6b488d4c7-zjbff" -n "argocd": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"argocd-dex-server-6dcf645b6b-s2n8g" -n "argocd": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"minio-79566d86cb-2knm5" -n "argo": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"redpanda-system-redpanda-operator-84957c79b5-dr4zz" -n "redpanda-system": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"workflow-controller-558db44f7-ngnq7" -n "argo": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"cert-manager-webhook-5b679f47d6-cn72p" -n "cert-manager": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"argo-server-5d58f6585d-dmjtf" -n "argo": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"argocd-repo-server-7598bf5999-8lx6b" -n "argocd": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"cert-manager-74f46787b6-xpzpx" -n "cert-manager": Timeout: request did not complete within requested timeout - context deadline exceeded
error when evicting pods/"istio-egressgateway-5547fcc8fc-8vlgm" -n "istio-system": Post "https://127.0.0.1:16443/api/v1/namespaces/istio-system/pods/istio-egressgateway-5547fcc8fc-8vlgm/eviction": unexpected EOF
error when evicting pods/"istio-ingressgateway-8f568d595-rtkxq" -n "istio-system": Post "https://127.0.0.1:16443/api/v1/namespaces/istio-system/pods/istio-ingressgateway-8f568d595-rtkxq/eviction": dial tcp 127.0.0.1:16443: connect: connection refused
```  

When I try to force delete one of these pods e.g. `kubectl delete pods argocd-applicationset-controller-76fc4dc766-7phr6 --grace-period=0 --force`

I get `Error from server (NotFound): pods "argocd-applicationset-controller-76fc4dc766-7phr6" not found`

The pods that cannot be deleted nor drained are all pods with local storage or daemonset-managed

If I force delete the node, other nodes still claim that there are pods in "unknown" state in the deleted node. `kubectl get no` says that the node no longer exists. What are the lessons here? The underlying deployments and statefulsets for databases are all down. What is the best way to save them? 

According to the official documentation
```
A Pod is not deleted automatically when a node is unreachable. The Pods running on an unreachable Node enter the 'Terminating' or 'Unknown' state after a timeout. Pods may also enter these states when the user attempts graceful deletion of a Pod on an unreachable Node. The only ways in which a Pod in such a state can be removed from the apiserver are as follows:

The Node object is deleted (either by you, or by the Node Controller).

The kubelet on the unresponsive Node starts responding, kills the Pod and removes the entry from the apiserver.

Force deletion of the Pod by the user.

The recommended best practice is to use the first or second approach. If a Node is confirmed to be dead (e.g. permanently disconnected from the network, powered down, etc), then delete the Node object. If the Node is suffering from a network partition, then try to resolve this or wait for it to resolve. When the partition heals, the kubelet will complete the deletion of the Pod and free up its name in the apiserver

```

So option 1 seems to have no effect on the pods. They still show up as status "unknown" under the deleted node.

Option 2 is ruled out. The node didn't start responding. 

Option 3 has no effect.

Is option 4 deleting the whole cluster?

**Comment by balchua** [comment]
Are you using 1.23?  I will probably try to join as `--worker` only node.

**Comment by AVSuni** [comment]
Thanks @balchua . It's 1.22.5. And pods in "unknown" status are now on every node, so the failing node poisoned the whole cluster

**Comment by balchua** [comment]
If u can upload the inspect tarball of the nodes here, may be able to see what's happening.

**Comment by AVSuni** [comment]
There isn't much there. Every call to kubectl on all nodes now gives `The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?`
[inspection-report-20220117_100409.tar.gz](https://github.com/ubuntu/microk8s/files/7880262/inspection-report-20220117_100409.tar.gz)

**Comment by AVSuni** [comment]
Thanks @ktsakalozos . I'm pretty sure assigning a fixed IP was the first thing I did before anything else. 

I don't have that directory anymore since I'm already reinstalling everything. At the moment, I'm speculating on two possible causes.

1) If the KVM host (not the guest) was the first node to fail, is it possible that the failure has something to do with how Microk8s sees available resources? The KVM host obviously shows all resources on the machine, including those assigned to the KVM guest. In any case, I don't feel confident in mixing KVM hosts and guests as K8s nodes in the future.  
2) I don't really know how to diagnose network partition, but I guess it's possible that there was some glitch in the switch, one of the NICs or even the router.  If so, it's alarming to see this breaking the whole cluster.
