### ISSUE TITLE
Failed to install version 1.21/stable/strict on Ubuntu Core

### ISSUE THREAD

**Issue by chengyu0905** [canonical/microk8s#2862]
Hi,
How do I install version 1.21/stable/strict on Ubuntu Core?

If i run this command:
`sudo snap install microk8s --channel=1.21/stable/strict`

I got an error:
`error: requested a non-existing branch on 1.21/stable for snap "microk8s": strict`

I refer to the document: [https://ubuntu.com/tutorials/getting-started-with-microk8s-on-ubuntu-core?_ga=2.244429253.1131353067.1642742815-1486448945.1642742815#3-install-microk8s-on-ubuntu-core](url)

Thanks in advance.

**Comment by ktsakalozos** [comment]
Hi @chengyu0905 

The strict snap is in the latest/edge/strict. Please try to install it with `snap install microk8s --channel=latest/edge/strict`. Thank you.
