### ISSUE TITLE
Setting DefaultTolerationSeconds or --pod-eviction-timeout does not work.

### ISSUE THREAD

**Issue by DevOpsTKH** [canonical/microk8s#2876]
MicroK8s v1.22.5-3+b58e143d1dbf57

I am struggling to decrease timeout after one of nodes is down to recreate pods. By default it's set to 5 mins. Regarding K8s documentation there are two places to make adjustments:
- kube-apiserver - here you set --default-not-ready-toleration-seconds and --default-unreachable-toleration-seconds (default 5m)
- kube-controller-manager - here you set --pod-eviction-timeout (default 5m)
I have found configuration files in /var/snap/microk8s/current/args/kube-apiserver and /var/snap/microk8s/current/args/kube-controller-manager and added mentioned parameters. Unfortunately it does not make any effect after microk8s restart.

**Comment by balchua** [comment]
I think you will have to redeploy the pods to take effect.  IIRC the tolerations are added to the scope of the pod upon deployment.

**Comment by DevOpsTKH** [comment]
I think I made this to work. I additionally added --enable-admission-plugins="DefaultTolerationSeconds" to kube-apiserver and indeed I had to delete whole deployment not only pods. After deleting and redeploy deployment new pods got new default toleration values.

Unfortunatelly option with kube-controller-manager (--pod-eviction-timeout) still doesn't work.

**Comment by DevOpsTKH** [comment]
I made some additional tests and it looks like that the same settings must me applied to all nodes in the cluster before you redeploy the deployment to get current values to work.
