### ISSUE TITLE
Error: failed to create containerd container V 1.23

### ISSUE THREAD

**Issue by laczkaS** [canonical/microk8s#2893]
Hi,
On version 1.23-stable i got an error when i try to run a pod (deployment) 
I received the following message (kubectl describe po):
 "Error: failed to create containerd container: create container failed validation: containers.Labels: label key and value greater than maximum size (4096 bytes), key: io.buildpa: invalid argument"

Docker image created by springboot (mvn spring-boot:build-image)
I tried many other spring image even ran those error.

On version 1.22 those images working perfectly

[inspection-report-20220129_162854.tar.gz](https://github.com/ubuntu/microk8s/files/7964007/inspection-report-20220129_162854.tar.gz)

**Comment by neoaggelos** [comment]
Hi @laczkaS,

Thank you for reporting the issue. This is an [issue with containerd 1.5.7](https://github.com/containerd/containerd/issues/6123), which prevents containers from starting when they have huge labels. This has changed in newer containerd versions (1.5.8 and later), and [we are looking to upgrade containerd](https://github.com/ubuntu/microk8s/pull/2899).
