### ISSUE TITLE
Options for Disabling TLS v1.0 and v1.1

### ISSUE THREAD

**Issue by bbrougher-cerium** [canonical/microk8s#2896]
Our company is in the process of phasing out TLS v1.0 and v1.1. Due to the way snaps work, I can't edit the OpenSSL config file and therefore the agent running on port 25000 shows as vulerable to attack in our security auditing software. Is there some way I can override this or can a flag/config option be added to allow and disallow certain TLS versions?

**Comment by ktsakalozos** [comment]
Hi @bbrougher-cerium at this point you cannot edit the OpenSSL config. It would make sense for us to make it configurable.

The cluster agent service listening on port 25000 is served by gunicorn3 v19.7.1 [1]. You could be able to set the TLS versions you want by tuning the `--ssl-version` and `--cipher` arguments, for example `--ssl-version=2` and `--ciphers ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256`. These arguments need to be in `/var/snap/microk8s/current/args/cluster-agent` and a restart of MicroK8s is needed (`microk8s stop; microk8s start`). Note that in the future we may move away from gunicorn so this approach may not work in the future.


[1] https://docs.gunicorn.org/en/19.x/settings.html

**Comment by neoaggelos** [comment]
Hi @boekhold, starting from MicroK8s 1.25, the cluster-agent is no longer served with `gunicorn`.

The following flag can be used instead: `--min-tls-version=tls12`
