### ISSUE TITLE
DNS Add-on: The Service "kube-dns" is invalid: spec.clusterIPs: Invalid value: []string{"10.152.183.10"}: failed to allocate IP 10.152.183.10: provided IP is already allocated

### ISSUE THREAD

**Issue by nlnjnj** [canonical/microk8s#2909]
I occurred the following issue when executing `microk8s enable dns`

![dns](https://user-images.githubusercontent.com/5831940/153108801-7d18b46d-ed7c-4145-af25-321159f79c4e.png)

Then I found that the dashboard service: dashboard-metrics-scraper occupied the IP: `10.152.183.10`

![svc](https://user-images.githubusercontent.com/5831940/153109185-d74afc47-a156-4eea-9ec4-0aeed9e0c5f1.png)

So here is my question: If we specify the IP `10.152.183.10` for dns purpose, we should also avoid other service got this IP;

And when I reexecuting the cmd `microk8s enable dns`  I shouldn't this confused message: `Addon dns is already enabled.`

![cmd](https://user-images.githubusercontent.com/5831940/153110169-88c9876e-da3a-4ade-93f4-4c4d40d5244e.png)

**Comment by balchua** [comment]
This is one of the things that we find need work.  I think this was brought up before, the remediation as of now is to enable dns prior to the rest of the workloads, otherwise it can end ip like your situation.

**Comment by tsc-buddy** [comment]
Hey! I am experiencing this exact issue today as well. microk8s v1.24 - 4. Has there been any update remediation for this? 

Host OS - Windows 11.
