### ISSUE TITLE
Snap Removing/Purging MicroK8s does not clear helm3 previous configurations

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [canonical/microk8s#2913]
What i did:

`sudo snap remove --purge microk8s`
`sudo snap install microk8s --classic --channel=1.23/stable``
`microk8s.helm3 repo update`

And got the following response:

```
> helm repo update
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2948/credentials/client.config
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "gitlab" chart repository
Update Complete. ⎈Happy Helming!⎈
```

These were from previous installations, is this normal?

**Comment by balchua** [comment]
I would say its normal, from what i understand on linux, helm uses the XDG base directory or user's home dir to keep the repos.  

Do you think it is better to keep the HELM caches and config location inside snap dirs?

**Comment by RafaelMoreira1180778** [comment]
I did not know the location where helm saves the configs and caches, my bad i should have researched.

In that case no it's better to leave it as it is, but perhaps writing something about resetting microk8s and helm? Just so the user knows that helm will not be "totally" reset. Just a thought.
