### ISSUE TITLE
unable to recover after invalid amount of memory set on microk8s vm

### ISSUE THREAD

**Issue by avoidik** [canonical/microk8s#2915]
hello,

I'm using microk8s with virtualbox on windows 10 home, after I accidentally set memory in megabytes to invalid value I'm not able neither to create new microk8s vm, nor delete existing to start over (even if I set proper parameter afterward)

steps I followed to recover

1. run microk8s with invalid memory size
    ```batch
    microk8s install --cpu 2 --mem 3072 --disk 5 -y
    ```
    wait few seconds for it to fail with
    ```
    error: Invalid RAM size: 3145728 MB (must be in range [4, 2097152] MB)
    ```
2. run microk8s with valid memory size, this now also fails
    ```batch
    microk8s install --cpu 2 --mem 3 --disk 5 -y
    ```
    with
    ```
    [microk8s-vm] Could not unregister VM: VBoxManage.exe: error: Cannot unregister the machine 'microk8s-vm' while it is locked
    launch failed: Could not start VM: Waiting for VM "microk8s-vm" to power on...
    ```
3. try to uninstall, this looks like it worked
    ```batch
    microk8s uninstall
    ```
    with
    ```
    Thank you for using MicroK8s!
    ```
    but in fact it doesn't
4. run microk8s with valid memory size, same issue as in step 2. above
    ```batch
    microk8s install --cpu 2 --mem 3 --disk 5 -y
    ```
5. open virtualbox with system elevated privileges and delete microk8s vm with the error
    ```
    Could not delete the medium storage unit 'C:\Windows\system32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\microk8s-vm\ubuntu-18.04-server-cloudimg-amd64.vdi'.
    VD: error VERR_PATH_NOT_FOUND opening image file 'C:\Windows\system32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\microk8s-vm\ubuntu-18.04-server-cloudimg-amd64.vdi' (VERR_PATH_NOT_FOUND).
    ```
6. run microk8s with valid memory size, same issue as in step 2. above
    ```batch
    microk8s install --cpu 2 --mem 3 --disk 5 -y
    ```
7. run cmd with system elevated privileges and delete entire `C:\Windows\System32\config\systemprofile\VirtualBox VMs\microk8s-vm` folder manually
8. now I can run microk8s vm with proper parameters

I find this entire process is a little bit overwhelming, I'm now wondering is this expected experience?

multipass 1.8.0+win
multipassd 1.8.0+win
microk8s 2.2.1
virtualbox 6.1.32 r149290

**Comment by ktsakalozos** [comment]
Thank you for reporting this @avoidik 

This is not a good experience. Maybe we should guard against this case by adding some validations in the install script [1, 2].

[1] https://github.com/ubuntu/microk8s/blob/master/installer/cli/microk8s.py#L126
[2] https://github.com/ubuntu/microk8s/blob/master/installer/windows/microk8s.nsi#L147

**Comment by lferran** [comment]
Any advise on where to find the min and max values for memory, cpus and disk, respectively?

**Comment by ktsakalozos** [comment]
@lferran, lets go with:
 - min RAM: 2GB
 - min cpu: 2
 - min disk: 10GB
