### ISSUE TITLE
WSL2: Prometheus Daemon Set "node-exporter" failed to run

### ISSUE THREAD

**Issue by anthopark** [canonical/microk8s#2933]
Hi

I'm running `1.23.3` on a WSL2 Ubuntu 20.04 (Windows build: 19042).

When I enabled the Prometheus add-on, I noticed the pod for node-exporter is not starting. (`CreateContainerError`)

The container image is `quay.io/prometheus/node-exporter:v1.1.2`

I see the message on the dashboard

```
failed to generate container "<random pod name>" spec: failed to generate spec: path "/sys" is mounted on "/sys" but it is not a shared or slave mount
```

Because node exporter not working, I'm getting the Bad Gateway error on Grafana as well.

How should I fix this?

Thank you

**Comment by ktsakalozos** [comment]
Hi @anthopark 

Could you try this https://github.com/prometheus-community/helm-charts/issues/467#issuecomment-957091174 ?

**Comment by anthopark** [comment]
Hi @ktsakalozos,

I was able to get it working by removing the `mountPropagation` under the volume mount `sys` while editing the daemon set (`microk8s kubectl edit ds node-exporter -n monitoring`).

But I'm not sure what effect this solution will have. and I still don't get any metrics from Grafana. Even the node/cluster is not detected on Grafana.

I didn't have this issue when running with Multipass, but I encounter this in WSL2.

Lastly, [The literal command from the thread you shared](https://github.com/prometheus-community/helm-charts/issues/467#issuecomment-957091174) does not work because the index for the volume mount is different for the Microk8s version of ds/node-exporter, which has only 2 volume mounts (hence 0, 1).

**Comment by billyors** [comment]
Issue persists. I was able to use the workaround from @anthopark but still experiencing the Bad Gateway error with the grafana datasource (prometheus).

**Comment by kumarsen26** [comment]
I am still having the issue

![image](https://github.com/user-attachments/assets/daca8352-fdfb-443b-8d4e-8017a95eedd8)
