### ISSUE TITLE
Microk8s ignore private registry auth configuration

### ISSUE THREAD

**Issue by istvano** [canonical/microk8s#2948]
Hi Everyone,

I have been trying to figure this out and I think something is wrong with my microk8s (1.22)

I would like to pull private images from docker.io.

I have the following config ->

sudo crictl --debug --runtime-endpoint unix:///var/snap/microk8s/common/run/containerd.sock info

```json
"registry": {
      "configPath": "",
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://registry-1.docker.io"
          ]
        },
        "localhost:32000": {
          "endpoint": [
            "http://localhost:32000"
          ]
        }
      },

configs": {
        "docker.io": {
          "auth": {
            "username": "",
            "password": "",
            "auth": "$(mytoken_from_docker_config_json)",
            "identitytoken": ""
          },
          "tls": null
        },
        "registry-1.docker.io": {
          "auth": {
            "username": "",
            "password": "",
            "auth": "$(mytoken_from_docker_config_json)",
            "identitytoken": ""
          },
          "tls": null
        }
      },
```

microk8s.ctr -debug image pull docker.io/$(myimg) --skip-verify

```
INFO[0000] trying next host                              error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
```

Although if I pass in a -u $(mytoken_from_docker_config_json) 
like this

microk8s.ctr -debug image pull docker.io/$(myimg) --skip-verify -u $(mytoken_from_docker_config_json)

The pull works

```
fetch response received                       host=registry-1.docker.io response.header.content-length=2193 response.header.content-type=application/vnd.docker.distribution.manifest.v2+json response.header.date="Fri, 25 Feb 2022 14:12:05 GMT" response.header.docker-content-digest="sha256:8017fdc8c6aaaf0425ea38c97a3119a06a8c1df80983554d20c8bcb0333249f6" r
```

is it possuble that microk8s somehow ignores my auth config?

are there any logs anywhere that I could use to see the outgoing request to docker.io?

**Comment by neoaggelos** [comment]
Stale bot closed this, but if you are having issues, see the documentation page https://microk8s.io/docs/dockerhub-limits#option-1-configure-containerd-2 on how credentials should be configured
