### ISSUE TITLE
Node NotReady after reboot on ubuntu 20.04

### ISSUE THREAD

**Issue by boeyeb** [canonical/microk8s#2951]
Please run `microk8s inspect` and attach the generated tarball to this issue.
$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/2948/inspection-report-20220301_002436.tar.gz

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20220301_002436.tar.gz](https://github.com/canonical/microk8s/files/8157833/inspection-report-20220301_002436.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @boeyeb, looking at the logs of kubelite (`journalctl -fu snap.microk8s.daemon-kubelite`) I see the hostname registered with Kubernetes as a worker node is unreachable:
```
Mar 01 00:24:27 ip-172-31-34-126 microk8s.daemon-kubelite[620]: E0301 00:24:27.969344     620 kubelet.go:2422] "Error getting node" err="node \"ip-172-31-34-126\" not found"
```

It seems the machine you have changed IP at some point 28th of February:
```
Feb 28 23:19:47 ip-172-31-44-130 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
-- Reboot --
Feb 28 23:35:19 ip-172-31-34-126 systemd[1]: Started Service for snap application microk8s.daemon-kubelite.
``` 

This is not allowed in a Kubernetes cluster. Nodes changing IPs appear as new unregistered ones.

**Comment by boeyeb** [comment]
thanks

**Comment by boeyeb** [comment]
Hi ktsakalozos,
Whats is the correct way to handle reboot that changes ip address of the node?
Can Kubernetes cluster use hostname instead of ip address?

Thanks
Rajeev

**Comment by neoaggelos** [comment]
Hi @boeyeb 

There are a number of ways to deal with this. Typically, cluster nodes should be configured to have a static IP.

**Comment by boeyeb** [comment]
Thanks neoaggelos.  Can you suggest some ways? On single node system draining or cordoning before reboot which leads to IP address does not help.
