### ISSUE TITLE
Ambassador add-on not working on a new single node cluster

### ISSUE THREAD

**Issue by onlinejudge95** [canonical/microk8s#2955]
I installed microk8s on my `Ubuntu 20.04.4 LTS`. This is a single node cluster and I have enabled the following addons only
- dns
- registry
- storage
When I try to enable the **ambassador** add-on, I get the following error.
```
$ microk8s enable ambassador
Enabling Ambassador
Addon dns is already enabled.
error: unable to recognize "https://github.com/datawire/ambassador-operator/releases/latest/download/ambassador-operator-crds.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```
[inspection-report-20220302_171141.tar.gz](https://github.com/canonical/microk8s/files/8169374/inspection-report-20220302_171141.tar.gz)

**Comment by balchua** [comment]
Its looking like this one is abandoned.
https://github.com/datawire/ambassador-operator/issues/74
There hasn't been any movement since july last year.  1.23 deprecated many versions.
Or perhaps had been renamed...

@ktsakalozos i think we may have to retire ambassador addon.
