### ISSUE TITLE
Potential addons to add to microk8s 

### ISSUE THREAD

**Issue by Pflegusch** [canonical/microk8s#2956]
@ktsakalozos I'm currently using multiple microk8s clusters and found the below tools quite useful and think that they could be a great addition to the list of add-ons. 
Brief description of potential add-ons:
- [Loki](https://github.com/grafana/loki): Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by [Prometheus](https://prometheus.io/). It is designed to be very cost effective and easy to operate. It does not index the contents of the logs, but rather a set of labels for each log stream.
- [Cert Manager](https://github.com/cert-manager/cert-manager): cert-manager is a Kubernetes add-on to automate the management and issuance of TLS certificates from various issuing sources. It will ensure certificates are valid and up to date periodically, and attempt to renew certificates at an appropriate time before expiry.
- [Kubernetes-CSI](https://github.com/kubernetes-csi/csi-driver-smb): This driver allows Kubernetes to access SMB Server on both Linux and Windows nodes. 
- [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets#installation): A way of encrypting sensitive secrets and therefore making it possible to save them in repositories etc. 

Automatic configuration at installation could be a problem, as one needs to configure some stuff to make the cert-manager or csi driver workable, but I would give it a try and see what I can come up with. Let me know if you are interesting in having any of those :)

**Comment by ktsakalozos** [comment]
Hi @Pflegusch, this is a very nice set of addons that I am sure will find good use in several deployments.

With 1.24 release we are preparing a couple of changes on the addons framework to make them configurable and extendable. First you will be able to setup your own repositories with addons and load them on a MIcroK8s deployment. In [1] you will find a template repository that you can clone and later install in MicroK8s with:
```
microk8s addons repo add myawesomerepo https://github.com/myawesomeorg/myawesomerepo
```
Have a look at the [HACKING.md](https://github.com/canonical/microk8s-addons-repo-template/blob/main/HACKING.md) for instructions on how addons are authored.

By default we will keep shipping the same addons we ship now. These addons will be split to core addons [2] that we (Canonical) will provide support for and community addons [3] that will be maintained by community members.

With v1.24 you will be able to edit the addons in place. All addons will be placed under `/var/snap/microk8s/common/addons/` and you will be able to tune them to your liking. In your case this approach will help speedup the development process.

You can see how the above changes are shaping up in you `snap install microk8s --classic --channel=latest/edge`.

To sum-up your options are to create a public addons repo and/or put PRs for these addons to the community addons repo [3] so they are shipped with MIcroK8s by default.

We appreciate any effort you put into this and we will be here to help out. For realtime comunication you can find us in #microk8s on the kubernetes slack. Thank you.

[1] https://github.com/canonical/microk8s-addons-repo-template
[2] https://github.com/canonical/microk8s-core-addons
[3] https://github.com/canonical/microk8s-addons

**Comment by sxsmg** [comment]
hey? can I take this up?

**Comment by neoaggelos** [comment]
Hi @sxsmg

Contributions are always welcome. The repository for community-contributed addons is https://github.com/canonical/microk8s-community-addons. Please ensure that you include proper tests for any new addons. Thank you!
