### ISSUE TITLE
Making addons persistent when using the storage addon 

### ISSUE THREAD

**Issue by Pflegusch** [canonical/microk8s#2957]
Currently addons such as ``prometheus`` will deploy several deployments, such as Grafana for example. However, the deployments are not persistent as the important volume mounts don't have a underlying persistent volume and use ``emptyDirs`` for example. When the pod is restarted, the data is gone. 

As an enhancement, I would suggest that when the addon is enabled with the ``microk8s enable`` command, one checks if there is a possibility to create and mount persistent volumes and uses them. Otherwise, one can fallback to the classical solution with ``emptyDirs``. As an quick idea, I would simply check in the script if the ``hostpath-provisioner`` deployment is up and running and then deploy a persistent volume claim with a deployment that uses that claim, aka use a slightly modified deployment for the grafana example for instance.
Problems that one could be facing are inproper write/read permissions when creating the persistent volume, however, we could add some troubleshooting hints for users that would face such issues. 

Alternatively, we could also make a seperate addon called ``prometheus-persistent`` for example, and deploy the hostpath-provisoner with the modified deployment files there. 

I would give this a try if there is interest in having it in a future release :)

**Comment by ktsakalozos** [comment]
Hi @Pflegusch this is a great suggestion. My recommendation is to extend the Prometheus addon [1] (possibly rewrite it in python) and extend it with a `--storage-class` argument that you could tell prometheus how/if to persist its data. Of course this would require some editing in the manifests before applying them. I believe the default behavior ("emptyDis") should stay as is so we do not surprise users. What do you think?

[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons/prometheus/enable
