### ISSUE TITLE
Haproxy ingress and microk8s?

### ISSUE THREAD

**Issue by agonzalezm** [canonical/microk8s#2958]
It is possible to use haproxy ingress with microk8s? There is no addon for haproxy ingress, will installing manually from haproxytech repo work? I need a local k8s that can support haproxy ingress for dev and testing.

Is there any plan to release addon for this?

**Comment by PRNDA** [comment]
> It is possible to use haproxy ingress with microk8s? There is no addon for haproxy ingress, will installing manually from haproxytech repo work? I need a local k8s that can support haproxy ingress for dev and testing.
> 
> Is there any plan to release addon for this?

Yes it is, just install haproxy operator and create ingress with `ingressClassName: haproxy` and you are good to go.

I have a working cluster with both ingress-nginx and haproxy ingress installed, both works.

**Comment by maksonlee** [comment]
> > It is possible to use haproxy ingress with microk8s? There is no addon for haproxy ingress, will installing manually from haproxytech repo work? I need a local k8s that can support haproxy ingress for dev and testing.
> > Is there any plan to release addon for this?
> 
> Yes it is, just install haproxy operator and create ingress with `ingressClassName: haproxy` and you are good to go.
> 
> I have a working cluster with both ingress-nginx and haproxy ingress installed, both works.

can you explain more on how to install haproxy operator?

**Comment by PRNDA** [comment]
> can you explain more on how to install haproxy operator?

It's quite simple, just run `helm install ha-ingress -n ha-ingress --create-namespace`, of cause, you will have to add haproxy repo first.
