### ISSUE TITLE
After running with snap refresh, microk8s upgrade to 1.23, then everything stops to work

### ISSUE THREAD

**Issue by fzhan** [canonical/microk8s#2959]
Would there be a way to safely downgrade the version back to 1.20?

**Comment by ktsakalozos** [comment]
Hi @fzhan, have you looked into `snap revert` [1]

[1] https://snapcraft.io/docs/getting-started#heading--revert

**Comment by fzhan** [comment]
@ktsakalozos thanks, sorry forget to mention, I'm running snap in a air-gaped environment, all snap were previously downloaded from offline then ack before install locally, what's the command for snap revert with a local snap file?

**Comment by fzhan** [comment]
I've tried to offline reinstall snap with local snap file, kubelite failed on the following log:

`Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: + exec /snap/microk8s/2946/kubelite --scheduler-args-file=/var/snap/microk8s/2946/args/kube-scheduler --controller-manager-args-file=/var/snap/microk8s/2946/args/kube-controller-manager --proxy-args-file=/var/snap/microk8s/2946/args/kube-proxy --kubelet-args-file=/var/snap/microk8s/2946/args/kubelet --apiserver-args-file=/var/snap/microk8s/2946/args/kube-apiserver --kubeconfig-file=/var/snap/microk8s/2946/credentials/client.config --start-control-plane=true
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: Starting kubelite
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.347246  383564 daemon.go:73] Waiting for the API server
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.348566  383564 daemon.go:65] Starting API Server
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.350000  383564 server.go:654] external host was not specified, using 10.173.59.22
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:44.350032  383564 authentication.go:507] AnonymousAuth is not allowed with the AlwaysAllow authorizer. Resetting AnonymousAuth to false. You should use a different authorizer
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.350504  383564 server.go:199] Version: v1.21.9-3+5bfa682137fad9
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.729305  383564 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.729329  383564 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.730200  383564 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.730214  383564 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.732183  383564 client.go:360] parsed scheme: "endpoint"
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:44.732210  383564 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}]
Mar 03 17:00:44 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:44.732350  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:45 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:45.729139  383564 client.go:360] parsed scheme: "endpoint"
Mar 03 17:00:45 node13.local microk8s.daemon-kubelite[383564]: I0303 17:00:45.729265  383564 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}]
Mar 03 17:00:45 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:45.729492  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:45 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:45.733393  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:46 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:46.730557  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:47 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:47.605248  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:48 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:48.577783  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:50 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:50.465547  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:51 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:51.255570  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:53 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:53.916086  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
Mar 03 17:00:55 node13.local microk8s.daemon-kubelite[383564]: W0303 17:00:55.172213  383564 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2946/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
`

**Comment by fzhan** [comment]
> What version and revision of MicroK8s were you running before?

it was 1.20, then got upgraded to 1.23 (auto refresh by snap due to our firewall upgrade).

**Comment by ktsakalozos** [comment]
The error you showed me says that the datastore was not started. The datastore service is `snap.microk8s.daemon-k8s-dqlite`. Could you share the logs of that service too? Or a `microk8s inspect` tarball.

Have you tried to download the snap from the 1.20 track and install that one. As a general note upgrading should be done one step at a tile (1.20 -> 1.21 -> 1.22 etc).

**Comment by fzhan** [comment]
@ktsakalozos I've realized this was the cause of it. Too bad couldn't turn back in time to stop the snap from auto refresh.
1.20 just won't start, strangely 1.23 worked, but our kubeSystem running kubeSphere didn't support the 1.23 API. I guess we are down to two options: lose everything, or wait for kubeSphere to launch a support on 1.23. T_T

**Comment by ktsakalozos** [comment]
If you download the microk8s from 1.20 track it should not upgrade to 1.23. Have you specified the `--channel=1.20/stable` when downloading the snap?

All service arguments are under `/var/snap/microk8s/current/args/` so if a service does not start it is probably because of some argument missing.

**Comment by fzhan** [comment]
Yes but that was last year, when 1.20.6 was still stable. Not sure why snap auto refreshed microk8s two versions up.

I will give it last try.

**Comment by fzhan** [comment]
@ktsakalozos what'd be a manual way to recover the dqlite, manually runs datastore?

**Comment by fzhan** [comment]
I'm keeping it under 1.20.6 for the moment, it won't refresh to 1.23, i've added api.snapcraft.io to fw.
dqlite log seeing mostly these:
`
level=error msg="error while range on /registry/leases/kube-system/kube-scheduler : query (try: 0): context canceled"
`

**Comment by fzhan** [comment]
> The error you showed me says that the datastore was not started. The datastore service is `snap.microk8s.daemon-k8s-dqlite`. Could you share the logs of that service too? Or a `microk8s inspect` tarball.
> 
> Have you tried to download the snap from the 1.20 track and install that one. As a general note upgrading should be done one step at a tile (1.20 -> 1.21 -> 1.22 etc).

I could not find this service for 1.20, was this service introduced after 1.21?

**Comment by ktsakalozos** [comment]
On 1.20 dqlite was embeded into kubelet.

**Comment by fzhan** [comment]
> On 1.20 dqlite was embeded into kubelet.

I can see all the data files under /var/snap/microk8s/2143/var/kubernetes/backend, is there anyways to manually recover them?

**Comment by fzhan** [comment]
I've tried to follow the instruction on https://discuss.kubernetes.io/t/recovery-of-ha-microk8s-clusters/12931, however it seems that every node had different sets of dqlite files and snapshots.

**Comment by ktsakalozos** [comment]
What are the logs of `snap.microk8s.daemon-k8s-dqlite` service? Or if you are on 1.20 could you share the logs of `snap.microk8s.daemon-kubelite`, the last 3000 lines should be enough to show how the service crashloops. Could you also share the `/var/snap/microk8s/current/args/` directory? I would like to know what arguments each service is started with. Thanks.

**Comment by fzhan** [comment]
on 1.20, args attached
[args.zip](https://github.com/canonical/microk8s/files/8210928/args.zip)

kubelet logs attached
[snap.microk8s.daemon-kubelet-part.zip](https://github.com/canonical/microk8s/files/8210940/snap.microk8s.daemon-kubelet-part.zip)

Thanks a million!
> What are the logs of `snap.microk8s.daemon-k8s-dqlite` service? Or if you are on 1.20 could you share the logs of `snap.microk8s.daemon-kubelite`, the last 3000 lines should be enough to show how the service crashloops. Could you also share the `/var/snap/microk8s/current/args/` directory? I would like to know what arguments each service is started with. Thanks.

**Comment by fzhan** [comment]
Here's the other node in the cluster, this cluster only has two nodes for the moment.

[snap.microk8s.daemon-kubelet-part.zip](https://github.com/canonical/microk8s/files/8212356/snap.microk8s.daemon-kubelet-part.zip)

**Comment by ponderMuse** [comment]
Hi,

I have just done an upgrade from microk8s 1.19 stable straight to 1.23 stable and the cluster is up and running but `microk8s inspect` shows: **FAIL:  Service snap.microk8s.daemon-k8s-dqlite is not running**.

But if I do `sudo journalctl -u snap.microk8s.daemon-k8s-dqlite` it shows dqlite service succeeded with no errors. Last line: **systemd[1]: snap.microk8s.daemon-k8s-dqlite.service: Succeeded.**

Any idea what the mismatch might be? Maybe upgrading from 1.19 straight to 1.23 was not a good idea and don't know if I should uninstall microk8s completely and reinstall from scratch :o/
