### ISSUE TITLE
Request: Helm3 Add-on Version Upgrade to 3.8.0

### ISSUE THREAD

**Issue by anthopark** [canonical/microk8s#2961]
Hello,

Could we get the latest version of the Helm3 client (`3.8.0`) so that we can work with private registries that accept OCI artifacts?

Thank you!

**Comment by ktsakalozos** [comment]
Hi @anthopark the next release (v1.24) will come with helm v3.2.0. This work has already been merged. You can give it a try in the latest/edge channel.
