### ISSUE TITLE
How to upgrade kubernetes version under Windows?

### ISSUE THREAD

**Issue by BaerSy** [canonical/microk8s#2962]
I installed Microk8s for Windows. When I tried to deploy application with helm3 , I found error with k8s version not compatible. How can I upgrade k8s within microk8s under windows. I can't find snap refresh in microk8s for windows.

Thanks

**Comment by ktsakalozos** [comment]
Hi @BaerSy MicroK8s on windows runs in a Linux VM. You can use `multipass shell` [1] from a CMD to get a shell in the VM and from there you can call the `snap refresh` command.

[1] https://multipass.run/docs/shell-command

**Comment by BaerSy** [comment]
Thanks. Very helpful!!!
