### ISSUE TITLE
Redundant command in certs generation scripT

### ISSUE THREAD

**Issue by cg-cri-gl** [canonical/microk8s#2963]
Hi,

following line 
https://github.com/canonical/microk8s/blob/9536527e31d0d4d9c59f529d247c152625e68af5/build-scripts/build-certs.sh#L9
is redundant, and was introduced in https://github.com/canonical/microk8s/commit/f77eb17d7227dec5534e838375527fad60979eb3

**Comment by ktsakalozos** [comment]
Thank you for bringing this to our attention @cg-cri-gl . We will take care of it. Thanks.
