### ISSUE TITLE
Public DNS is not working by default in Pods

### ISSUE THREAD

**Issue by jpc** [canonical/microk8s#2976]
At least on macOS (arm64) and Ubuntu (x86_64) with the default installation of `microk8s` the Pods do not have a working DNS resolver configuration. I encountered the issue when trying to install some packages inside a Pod running a vanilla `alpine` image.

One way to reproduce: 

```shell
microk8s kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: internet-access-example
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - ping -c2 8.8.8.8; ping -c2 google.pl; tail -f /dev/null
    image: alpine
    name: internet-access-example
EOF
```

If I look at the logs `microk8s kubectl logs -f internet-access-example` I get:
```
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=115 time=17.545 ms
64 bytes from 8.8.8.8: seq=1 ttl=115 time=16.907 ms

--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 16.907/17.226/17.545 ms
ping: bad address 'google.pl'
```

So the internet access is working but the publicly visible DNS names fail to resolve.

The problem goes away if I use `microk8s enable dns` but this is a separate, seemingly optional step. The [Getting started](https://microk8s.io/docs/getting-started) document only mentions that "To start it is recommended to add DNS management to facilitate communication between services." which suggests it is for the internal DNS between the services but it does not say a word about basic public DNS access. The [macOS installation instructions](https://microk8s.io/docs/install-alternatives#heading--macos) do not really mention any recommended add-ons at all.

Is this intentional? Wouldn't it be better to enable `dns` by default to avoid strange issues like this? `microk8s` is probably a tool used by a lot of newcomers to K8s and it may be quite difficult to figure out the problems. Alternatively we could improve the documentation to make it clear `dns` is needed for "Internet access" or modify the Pod configuration to use the DNS resolver from the host if CoreDNS is not enabled.

Please run `microk8s inspect` and attach the generated tarball to this issue: [inspection-report-20220311_122804.tar.gz](https://github.com/canonical/microk8s/files/8231645/inspection-report-20220311_122804.tar.gz)

**Comment by neoaggelos** [comment]
Hi @jpc, thank you for reporting this issue.

Indeed, this would not be an issue if coredns was installed by default on MicroK8s deployments, and this is something that we are actively considering.

As is, a "workaround" to resolve public DNS names without coredns installed in the cluster would be to use `{spec: {hostNetwork: true}}`, but this is probably not what you want.

I also see how the documentation can be misleading to newcomers, thank you for raising this and we will make sure to address it. Feel free to share any suggestions that you might have :)

**Comment by DenisBessa** [comment]
I have the same problem.
After almost going nuts, I can tell it's limited to Alpine-based containers.
It looks like K3S has the same problem: https://github.com/ho-ansible/k3s/issues/6

**Comment by akzov** [comment]
The first thing I did after install was `microk8s enable dns` but I still don't have DNS
