### ISSUE TITLE
How to install a legacy minor version such as 1.20.2 ?

### ISSUE THREAD

**Issue by alexzhc** [canonical/microk8s#2985]
Hi, dev team, 

I have a compatibility test that requires a specific kubelet version of 1.20.2, but the snap channel offers only 1.20.13.  Is there any way to install the older revison of 1.20.2?

Thanks

**Comment by ktsakalozos** [comment]
Hi @alexzhc, there is no way to get an old build revision in a track (1.20 in this case). Your best option is to build the snap with the kubernetes version you desire.

Start by `git clone` the microk8s repository and `git checkout` the 1.20 branch.  Then edit the KUBE_VERSION in [1] to match the tag in the upstream Kubernetes [2] you want to target. This tag should make its way to the k8s binaries build script [3]. Building the microk8s snap will require you to `snap install multipass` and `snapcraft`. For deploying the output snap requires the `--dangerous` flag. Have a loog at [4] for a bit more information of how the snap is build.


[1] https://github.com/canonical/microk8s/blob/master/build-scripts/set-env-variables.sh#L29
[2] https://github.com/kubernetes/kubernetes/tags
[3] https://github.com/canonical/microk8s/blob/master/build-scripts/build-k8s-binaries.sh
[4] https://github.com/canonical/microk8s/blob/master/docs/build.md#building-the-snap-from-source

**Comment by alexzhc** [comment]
@ktsakalozos, thanks, I've figured it out.
