### ISSUE TITLE
LXD Sample profile causes my Gnome session to crash, reset and log off

### ISSUE THREAD

**Issue by johnbendi** [canonical/microk8s#3000]
The sample profile here: https://raw.githubusercontent.com/canonical/microk8s/master/tests/lxc/microk8s.profile is causing my desktop session to crash and log me out. When I log back in my session is lost. In other cases it just hangs on a black screen and prints 
```
BUG: scheduling while atomic: swappper/7/0/0x00000100
bad: scheduling fron the idle thread!
```
I have other instance which uses default profile and this does not happen when stopping and restarting it. Also after logging back in the problematic instance shows that it is running and I'm able to shell into it without problems

**Comment by johnbendi** [comment]
Hello @ktsakalozos, my graphics card and driver info on the host are below:
```
$ sudo lshw -c video
-display                 
       description: VGA compatible controller
       product: TU116M [GeForce GTX 1660 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:150 memory:a4000000-a4ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:4000(size=128) memory:a5000000-a507ffff
  *-display
       description: VGA compatible controller
       product: UHD Graphics 630 (Mobile)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:137 memory:a3000000-a3ffffff memory:80000000-8fffffff ioport:5000(size=64) memory:c0000-dffff

$ lspci -nn | grep -E 'VGA|Display'
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 630 (Mobile) [8086:3e9b]
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1)
```

The crash happens with any container using the profile before having microk8s installed on it. Though it runs fine when it's started and when booting up and I can shell into it and run commands without issue though I haven't moved forward to put microk8s on the container yet.

**Comment by tomponline** [comment]
This has also been discussed over at https://discuss.linuxcontainers.org/t/ubuntu-session-restarts-on-lxd-start/13634

**Comment by johnbendi** [comment]
And FWIW, the image booting the container is an ubuntu:20.04 running on ubuntu 20.04 host
