### ISSUE TITLE
DNS Host Ignored

### ISSUE THREAD

**Issue by cawoodm** [canonical/microk8s#3003]
When I run `microk8s enable dns:172.x.y.z` specifying our company's DNS server it is apparently ignored as is shown by `microk8s kubectl -n kube-system edit configmap/coredns`:
```
...
forward . 8.8.8.8 8.8.4.4
...
```
Nowhere in the config is our 172.x.y.z IP and none of the pods can do any DNS resolution of our LAN hosts
[inspection-report-20220325_141813.tar.gz](https://github.com/canonical/microk8s/files/8350828/inspection-report-20220325_141813.tar.gz)
.

**Comment by neoaggelos** [comment]
Hi @cawoodm.

I'm unable to reproduce this, can you share some stems to reproduce your issue?

Trying this on a fresh instance works:

```
sudo snap install microk8s --classic
sudo microk8s enable dns:10.0.0.1
```

Thanks!

**Comment by cawoodm** [comment]
Hello,
Are you saying you see the dns `10.0.0.1` in your `configmap/coredns`?

I am using a fresh, basic install of microk8s on CentOS 7.

```bash
yum install -y epel-release snapd
systemctl enable --now snapd.socket
ln -s /var/lib/snapd/snap /snap
systemctl restart snapd
snap install microk8s --classic --channel=1.19/stable
microk8s enable dns:172.x.y.z
```

When I check the `configmap/coredns` it doesn't contain this `172...` ip address.

One thing is that I did `microk8s enable dns` first, then later `microk8s disable dns` (configmap was deleted) then  `microk8s enable dns:172...`.

**Comment by cawoodm** [comment]
Doh! This is what happens when I copy-paste from the internet. I now intend to upgrade to 1.22 - or is 1.23 considered stable?

**Comment by neoaggelos** [comment]
MicroK8s versions follow upstream Kubernetes, and we support the current and the previous two minor versions.

At the moment, these are 1.23 (upstream), 1.22 and 1.21. All three versions are actively maintained and considered stable.

**Comment by cawoodm** [comment]
@neoaggelos could I suggest an improvement to microk8s due to this issue?

I've worked with k3s and this kind of manual DNS configuration was not necessary - it would be great if microk8s "just worked" out of the box.
