### ISSUE TITLE
DNS doesn't work on a fresh installation

### ISSUE THREAD

**Issue by cawoodm** [canonical/microk8s#3004]
Similarly to #332 we have no working DNS inside pods in a fresh installation on CentOS 7 (AMD 64) - on prem.  The pods are unable to resolve hostnames in our LAN. They seem to be configured to use an unknown DNS IP `10.152.183.10`.

During installation we did `microk8s enable dns:172.x.y.z` to define our corporate DNS but, as we reported #3003, this did not make it into `configmap/coredns` so we added our corporate DNS `172.x.y.z` manually to `configmap/coredns`:
```
forward . 172.x.y.z 8.8.8.8 8.8.4.4
```

When we look at `/var/snap/microk8s/current/args/kubelet` we see:
```
--cluster-dns=10.152.183.10
```
In all pods we see `/etc/resolv.conf` has
```
nameserver 10.152.183.10
```

The problem is `10.152.183.10` is an unknown IP - neither inside nor outside the cluster does this IP exist. The coredns pod has `10.1.139.225` but I guess this can change.

If we add our corporate DNS IP to `/var/snap/microk8s/current/args/kubelet` and restart microk8s we suddenly have the ability to resolve corporate/LAN hostnames but no cluster hostnames/services. If we add our corporate DNS AND the cordns pod IP to resolv.conf and ping an internal service it fails - only the corporate DNS is used.

[inspection-report-20220325_155510.tar.gz](https://github.com/canonical/microk8s/files/8351599/inspection-report-20220325_155510.tar.gz)

**Comment by cawoodm** [comment]
UPDATE: I now see the `kube-dns` service does indeed have the IP `10.152.183.10`. I was confused because it did not answer a ping.

So the issue remains that with `10.152.183.10` as a DNS server I am unable to resolve LAN names. I can only resolve cluster names (like `myservice`) and public names (like `google.com`). I cannot resolve other servers in the same network as my nodes.

**Comment by neoaggelos** [comment]
Hi @cawoodm. Thanks for reporting the issue.

Can you try changing your configuration line to this instead (i.e. all DNS requests are forwarded to your corporate DNS)

```
forward . 172.x.y.z
```

In order to apply the changes, make sure to restart the CoreDNS pod with:

```
microk8s.kubectl rollout restart -n kube-system deploy/coredns
```

**Comment by cawoodm** [comment]
Hello @neoaggelos,

Thanks so much for helping here!

Indeed your setting `forward . 172.25.8.100` instead of mine `forward . 172.25.8.100 8.8.8.8 8.8.4.4` has made all the difference! I can now curl/ping my cluster services as well as my LAN hosts!

You have saved my day!

**Comment by ktsakalozos** [comment]
For the future traveler, you may want to look at the respective docs page https://microk8s.io/docs/addon-dns
