### ISSUE TITLE
Cannot install microk8s offline - failed with timeout

### ISSUE THREAD

**Issue by nimi13** [canonical/microk8s#3017]
Followed the instruction from https://microk8s.io/docs/install-alternatives#heading--offline, with the virtual network interface. on Ubuntu 20.04

Running the install command including --classic `sudo snap install microk8s_3021.snap --classic`

Getting an error

>     error: cannot perform the following tasks:
> 
>         Start snap "microk8s" (3021) services (systemctl command [start snap.microk8s.daemon-containerd.service] failed with exit status 1: Job for snap.microk8s.daemon-containerd.service failed because a timeout was exceeded. See "systemctl status snap.microk8s.daemon-containerd.service" and "journalctl -xe" for details.

Getting command not found when running snap.microk8s.daemon-containerd.service

Do not see any error of the microk8s using the journalctl -xe command

Any idea how to install microk8s in an offline environment?

I cannot run `microk8s inspect` as microk8s is not installed.

**Comment by nimi13** [comment]
Hi @neoaggelos, thank you for the replay.

Offline means no connectivity to the internet, no proxy that can access the internet, 
I am trying to install it now on a test machine, it ip route is 

> 10.0.0.0/24 dev ens160 proto kernel scope link src 10.0.0.111 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1

**Comment by neoaggelos** [comment]
Thanks for the quick reply. Indeed, there are some issues when there is no configured default gateway, since the default route is used in 1 or 2 places to infer which host interface should be used.

This needs to be looked at, thank you for raising the issue.

In the meantime, a temporary hack could be to add a dummy gateway (it does not have to be functional), e.g.

```
ip route add default via 10.0.0.255
```

Make sure to pick a dummy address.

If truly offline, you will also need to load images with `microk8s ctr import`, but I suppose you might already be aware of that.

I want to note that we want to target offline and airgapped environments, so please share any issues and/or findings here.

Thank you!

**Comment by nimi13** [comment]
my bad, I imported the images using `microk8s ctr image import`, look like it running, will test it

**Comment by nimi13** [comment]
Hi, in a new offline environment created for a test before production installation.
It looked like the pod in pending statue even though there were all imported.

Any help will be much appreciate.

Attached is the inspection report after running microk8s inspect
[inspection-report-20220406_133238.tar.gz](https://github.com/canonical/microk8s/files/8427755/inspection-report-20220406_133238.tar.gz)
  
ip route output 
```
default via 172.17.211.1 dev ens192 proto static 
172.17.211.0/24 dev ens192 proto kernel scope link src 172.17.211.119 
172.18.0.0/16 dev docker0 proto kernel scope link src 172.18.0.1 linkdown
```
microk8s ctr images list

> docker.io/calico/cni:v3.19.1                                            application/vnd.docker.distribution.manifest.v2+json sha256:2cf071b3cd758112e84139470ee503cf588f0bbdd3b63d20dc3043bb26f29ebd 139.1 MiB linux/amd64 io.cri-containerd.image=managed 
> docker.io/calico/kube-controllers:v3.17.3                               application/vnd.docker.distribution.manifest.v2+json sha256:2c4fd2756236c6603a0663152131b556896249d5ec56ed273fa50064f572d5df 49.7 MiB  linux/amd64 io.cri-containerd.image=managed 
> docker.io/calico/node:v3.19.1                                           application/vnd.docker.distribution.manifest.v2+json sha256:b8db0eecc2929dcb050dc46e026dd5a9037034090dbfbce5e0d86b941e066832 162.9 MiB linux/amd64 io.cri-containerd.image=managed 
> docker.io/calico/pod2daemon-flexvol:v3.19.1                             application/vnd.docker.distribution.manifest.v2+json sha256:b493e68f0b9b80538e41f5d52aef1ce5e7ca3cf5d1ab8891a55a1ade1721e3d6 20.8 MiB  linux/amd64 io.cri-containerd.image=managed 
> docker.io/cdkbot/hostpath-provisioner:1.1.0                             application/vnd.docker.distribution.manifest.v2+json sha256:0be01cf89339234149847be843ed9f769730805c9e3254ad2a03a34653e2b73a 33.7 MiB  linux/amd64 io.cri-containerd.image=managed 
> docker.io/coredns/coredns:1.8.0                                         application/vnd.docker.distribution.manifest.v2+json sha256:f6e98aa3db70e7a1b369ca8628e786debb5c5d1cf2378b959c83a306f5fb320c 40.6 MiB  linux/amd64 io.cri-containerd.image=managed 
> docker.io/library/registry:2.7.1                                        application/vnd.docker.distribution.manifest.v2+json sha256:f1d8c00df884638c9c6c61a3f066e636cc4d1ac0ed219d0429167455e9719252 25.6 MiB  linux/amd64 io.cri-containerd.image=managed 
> k8s.gcr.io/pause:3.1                                                    application/vnd.docker.distribution.manifest.v2+json sha256:dbd83f9b94c312efd98b95b09ced85479fbba3c3b2d05a5c3e09c9cfa4421ff6 729.0 KiB linux/amd64 io.cri-containerd.image=managed 
> sha256:296a6d5035e2d6919249e02709a488d680ddca91357602bd65e605eac967b899 application/vnd.docker.distribution.manifest.v2+json sha256:0754aa364f7d9a42fdaa4eeae975e1186a090057552817f1d8e2e0b71c386dd8 40.6 MiB  linux/amd64 io.cri-containerd.image=managed 
> sha256:448b418034bdd808dd3e985c1e96fe614e4360f8d2de4c92c561c86e1ccd40d3 application/vnd.docker.distribution.manifest.v2+json sha256:dd38239503d303b8715020809a4a7885e43c744362c9331661645c543ef3daa1 33.7 MiB  linux/amd64 io.cri-containerd.image=managed 
> sha256:5660150975fb82f006d013fdb583b628d3d340ff64775ca3111ca28f523e32df application/vnd.docker.distribution.manifest.v2+json sha256:11c445e2e0a82a58f0fd9eb25f885fb32bdf2882475b09d51bb8ab76fd7701b1 20.8 MiB  linux/amd64 io.cri-containerd.image=managed 
> sha256:5749e8b276f9b5aea2683d8a0d59afd05a2be478f5092fbaadc4715f4db76e5a application/vnd.docker.distribution.manifest.v2+json sha256:32377433c377f554e3bfeb894789415ae0ddab406ef7713d26c19278ec3e9b02 139.1 MiB linux/amd64 io.cri-containerd.image=managed 
> sha256:8a89fcd7b1c018416025e4f7215957accf967679e07c5167a4a0c183414c324f application/vnd.docker.distribution.manifest.v2+json sha256:b91713e68f7fefe6ee40bec548203b937d027452d6b919c7f46a10a3adb64845 49.7 MiB  linux/amd64 io.cri-containerd.image=managed 
> sha256:b8604a3fe8543c9e6afc29550de05b36cd162a97aa9b2833864ea8a5be11f3e2 application/vnd.docker.distribution.manifest.v2+json sha256:49bd6b1420deba16b51bd073977ea6ae4000b816a356b12e805a699c4e5d3dba 25.6 MiB  linux/amd64 io.cri-containerd.image=managed 
> sha256:c4d75af7e098eef5142c65b8fab5b3ff0e5c614ce72e91b8c44ba20249b596ef application/vnd.docker.distribution.manifest.v2+json sha256:d1376ba6805fc71c7dae38b2cdd89e4b890619f6fe2076f2373f4b2036587ab5 162.9 MiB linux/amd64 io.cri-containerd.image=managed 
> sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e application/vnd.docker.distribution.manifest.v2+json sha256:0968e31df05b727234888883ba43ccaa4ec75566113c75065af5a6124b62d93c 729.0 KiB linux/amd64 io.cri-containerd.image=managed

**Comment by neoaggelos** [comment]
Just to make sure before I dive into the logs, have you tried

```
sudo snap restart microk8s
```

after importing the images, so that containerd is not still trying to fetch them from the registry?

**Comment by nimi13** [comment]
Did `sudo snap restart microk8s` and even restarted the server

**Comment by nimi13** [comment]
Try to reinstall the microk8s but it didn't helped
When running `journalctl -xe` I am getting 
```
Apr 07 08:21:31 offline-test microk8s.daemon-apiserver-kicker[8192]: Setting up the CNI
Apr 07 08:21:33 offline-test microk8s.daemon-kubelite[8384]: E0407 08:21:33.719313    8384 kubelet.go:2347] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```

**Comment by nimi13** [comment]
Didn't manage to solve it, 
System does not work offline/air gap.
Any help will be much appreciated.

**Comment by neoaggelos** [comment]
Hi @nimi13, sorry for taking long to reply.

How are you side-loading the images to the airgap instance?

I found that using `docker image save` can be tricky and leads to some issues, can you try using the following? Basically, export the images from a working MicroK8s installation with internet access, then move them and import them into the airgap instance.

```bash

# export images
arch=$(microk8s.kubectl describe node `hostname` | grep Architecture | tail -1 | awk '{print $2}')
microk8s.ctr image list                             \
    | tail -n '+2'                                  \
    | awk '{ print $3 " " $1 }'                     \
    | sort                                          \
    | uniq --check-chars=71                         \
    | while read hash image; do
        microk8s.ctr image export --platform "$arch" "microk8s-${hash}.tar" "${image}"
    done

# create a single bundle
tar cvzf images.tar.gz microk8s-*.tar

##########################
# scp images.tar.gz my-remote-host:images.tar.gz
##########################


# extract bundle
tar xvzf images.tar.gz

# import images
for image in microk8s-*.tar; do
    microk8s.ctr image import $image
done
```

**Comment by nimi13** [comment]
Regard your question I used microk8s.ctr image export to export the images from an online system.
The online system has been installed using:
```
snap download microk8s
sudo snap ack microk8s_3052.assert
sudo snap install microk8s_3052.snap --classic
```
The offline system is installed using the same files and commands.

Followed your commands
microk8s status return "microk8s is not running. Use microk8s inspect for a deeper inspection"
The inspection-report is attach
[inspection-report-20220424_082404.tar.gz](https://github.com/canonical/microk8s/files/8549291/inspection-report-20220424_082404.tar.gz)

Looked for error using "journalctl -xe" and getting the same error 
```
Apr 24 08:42:22 offline-test microk8s.daemon-apiserver-kicker[917]: Setting up the CNI
Apr 24 08:42:23 offline-test microk8s.daemon-kubelite[927]: E0424 08:42:23.674485     927 kubelet.go:2347] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```

**Comment by neoaggelos** [comment]
Can you check what the output is for `microk8s.ctr image list` on the online and the offline nodes? Are there any differences?

Further, it looks like Calico is removed from the cluster. Can you try

```
microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml
```

and see if the CNI then comes up?

**Comment by nimi13** [comment]
There are few images on the online installation only (this is with the same installation process)

```
docker.io/calico/cni:v3.19.1                                                                                application/vnd.docker.distribution.manifest.list.v2+json sha256:f301171be0add870152483fcce71b28cafb8e910f61ff003032e9b1053b062c4 46.1 MiB  linux/amd64,linux/arm64,linux/ppc64le                       io.cri-containerd.image=managed 
docker.io/calico/kube-controllers:v3.17.3                                                                   application/vnd.docker.distribution.manifest.list.v2+json sha256:072e5f661f9c1af9ab49d127743fdbfe5d8ba16bac7c2616b92e64dd304ec3c4 21.0 MiB  linux/amd64,linux/arm64,linux/ppc64le                       io.cri-containerd.image=managed 
docker.io/calico/node:v3.19.1                                                                               application/vnd.docker.distribution.manifest.list.v2+json sha256:bc4a631d553b38fdc169ea4cb8027fa894a656e80d68d513359a4b9d46836b55 56.0 MiB  linux/amd64,linux/arm64,linux/ppc64le                       io.cri-containerd.image=managed 
docker.io/calico/pod2daemon-flexvol:v3.19.1                                                                 application/vnd.docker.distribution.manifest.list.v2+json sha256:bcac7dc4f1301b062d91a177a52d13716907636975c44131fb8350e7f851c944 8.9 MiB   linux/amd64,linux/arm64,linux/ppc64le                       io.cri-containerd.image=managed 
k8s.gcr.io/pause@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea                    application/vnd.docker.distribution.manifest.list.v2+json sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea 309.7 KiB linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x io.cri-containerd.image=managed 
```
Running _microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml_
```
configmap/calico-config created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/calico-kube-controllers created
```
microk8s status didn't work 

I exported the missing images from the online installation and imported them on the offline installation, 
It looked like it is working, 
Will enable registry and dns, export and import the needed image and then load our system.

Hope it will work

**Comment by nimi13** [comment]
No luck,

It look like the system is looking for recurses not only from the local images

journalctl -xe return 


```
-- The unit UNIT has successfully entered the 'dead' state.
Apr 28 08:53:12 offline-test systemd[1]: run-netns-cni\x2d918a6a9b\x2d65dc\x2daaed\x2de52b\x2db5b76111ccb3.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit run-netns-cni\x2d918a6a9b\x2d65dc\x2daaed\x2de52b\x2db5b76111ccb3.mount has successfully entered the 'dead' state.
Apr 28 08:53:14 offline-test microk8s.daemon-apiserver-kicker[4068703]: Setting up the CNI
Apr 28 08:53:16 offline-test microk8s.daemon-kubelite[4073355]: I0428 08:53:16.870952 4073355 event.go:294] "Event occurred" object="container-registry/registry-claim" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ExternalProvisioning" message="waiting for a volume to be created, either by external provisioner \"microk8s.io/hostpath\" or manually created by system administrator"
Apr 28 08:53:18 offline-test microk8s.daemon-containerd[4068771]: time="2022-04-28T08:53:18.883886209Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:calico-kube-controllers-6966456d6b-sl9bz,Uid:1bbb3bef-37ce-4791-9b03-b9cceb493d07,Namespace:kube-system,Attempt:0,}"
Apr 28 08:53:19 offline-test microk8s.daemon-containerd[4068771]: time="2022-04-28T08:53:19.150245853Z" level=error msg="Failed to destroy network for sandbox \"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\"" error="error getting ClusterInformation: Get \"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused"
Apr 28 08:53:19 offline-test microk8s.daemon-containerd[4068771]: time="2022-04-28T08:53:19.151160601Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-kube-controllers-6966456d6b-sl9bz,Uid:1bbb3bef-37ce-4791-9b03-b9cceb493d07,Namespace:kube-system,Attempt:0,} failed, error" error="failed to setup network for sandbox \"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\": error getting ClusterInformation: Get \"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused"
Apr 28 08:53:19 offline-test microk8s.daemon-kubelite[4073355]: E0428 08:53:19.151571 4073355 remote_runtime.go:209] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\": error getting ClusterInformation: Get \"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused"
Apr 28 08:53:19 offline-test microk8s.daemon-kubelite[4073355]: E0428 08:53:19.151737 4073355 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\": error getting ClusterInformation: Get \"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused" pod="kube-system/calico-kube-controllers-6966456d6b-sl9bz"
Apr 28 08:53:19 offline-test microk8s.daemon-kubelite[4073355]: E0428 08:53:19.151798 4073355 kuberuntime_manager.go:833] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\": error getting ClusterInformation: Get \"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused" pod="kube-system/calico-kube-controllers-6966456d6b-sl9bz"
Apr 28 08:53:19 offline-test microk8s.daemon-kubelite[4073355]: E0428 08:53:19.151936 4073355 pod_workers.go:949] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"calico-kube-controllers-6966456d6b-sl9bz_kube-system(1bbb3bef-37ce-4791-9b03-b9cceb493d07)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"calico-kube-controllers-6966456d6b-sl9bz_kube-system(1bbb3bef-37ce-4791-9b03-b9cceb493d07)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"d98f61db029a01349ee8065e0bbc4d4dde22daa9c877922c148b20379e893213\\\": error getting ClusterInformation: Get \\\"https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\\\": proxyconnect tcp: dial tcp 172.17.211.1:3128: connect: connection refused\"" pod="kube-system/calico-kube-controllers-6966456d6b-sl9bz" podUID=1bbb3bef-37ce-4791-9b03-b9cceb493d07
Apr 28 08:53:19 offline-test systemd[2096343]: run-netns-cni\x2d1d782de5\x2d2536\x2d1bc4\x2d61c5\x2d88c03f149bde.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
Apr 28 08:53:19 offline-test systemd[1]: run-netns-cni\x2d1d782de5\x2d2536\x2d1bc4\x2d61c5\x2d88c03f149bde.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit run-netns-cni\x2d1d782de5\x2d2536\x2d1bc4\x2d61c5\x2d88c03f149bde.mount has successfully entered the 'dead' state.
Apr 28 08:53:19 offline-test microk8s.daemon-apiserver-kicker[4068703]: Setting up the CNI
```

**Comment by nimi13** [comment]
@neoaggelos 
It seems like the offline installation is working.
Thank you very much for your support!
