### ISSUE TITLE
Microk8s HA bug joining node microk8s service crashes after join

### ISSUE THREAD

**Issue by directsahan** [canonical/microk8s#3018]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

I have checked with several microk8s versions (1.22,1.21) and when I do a join from the joining node the microk8s services get crashed in the joining nodes. Then after sometime the microk8s services in the master node also crashes. Reboot wont fix the problem. I have seen some git hub bugs related to this as well. Can some one support me on this? Thanks.

**Comment by ktsakalozos** [comment]
Hi @directsahan could you please share a `microk8s inspect` tarball from both nodes so as to see what is failing?

**Comment by directsahan** [comment]
Hi @ktsakalozos : Thank you very much for responding. I will share the inspect output soon.

**Comment by directsahan** [comment]
Hi @ktsakalozos  : Suddenly the cluster got working. seems I was trying it so quickly. By the way can I get some help on HA form you. I have a project with microk8s vs HA. When we have clusters 3 nodes with control plans and when we do "microk8s config" I assume all the 3 nodes to display one ip:port in the output in the server section. But in my case the command displays each servers ip add and the port while HA availability is "yes".

**Comment by directsahan** [comment]
Hi @ktsakalozos : I'm facing the crashing issue again. I will check and upload the tar balls.
