### ISSUE TITLE
Pod cannot reach other pod on other node 

### ISSUE THREAD

**Issue by maximehyh** [canonical/microk8s#3043]
Hello, 

I am trying to build a cluster of two nodes where a MQTT broker is located on one node (exposing a service for a TCP connection on port 1883) and another pod on another node that is supposed to connect to this broker. 

Everything is working fine when the 2 pods are on the same node but I cannot manage to make the TCP connection when the 2 pods are on 2 different nodes (see screenshots below).

So far I have only enable registry, ingress and  dns. 

I wonder If there is not some Calico specific configuration to be made?

Thanks.

[microk8s-inspect.tar.gz.gz](https://github.com/canonical/microk8s/files/8448571/microk8s-inspect.tar.gz.gz)

**Comment by maximehyh** [comment]
After digging a bit more I realized that the pod in question was not even able to access internet. After a few test with pods set on 3 different nodes I discovered that pods where able to connect to internet only when the pod was on the same node as the CoreDNS pod. 

I am fairly new to microk8s and Kubernetes, is that expected? Does this mean that I should find a way to set one CoreDNS pod per node (i.e replicaset). 

Thanks

**Comment by ktsakalozos** [comment]
Hi @maximehyh, could you try a few things:
 - change the hostname of the nodes to something that does not have capital letters
 - make sure the both hostnames are resolvable on both nodes, maybe add them to `/etc/hosts` for that
 - remove and reinstall MicroK8s on both nodes
 - `microk8s enable dns` before you deploy any other workload
 - make sure the two nodes have a static IP

**Comment by maximehyh** [comment]
Hi @ktsakalozos, 

Thank you for getting back to me. I realized that I made a mistake when saying that the pod did not have access to internet. It actually can but it cannot resolve hostnames as it cannot reach the DNS pod that is located on the other node. 

I did pretty much all the things that you listed and I think my issue is somehow related to Calico. For example if I `shell exec` inside pod-74b4db7697-4znf5 (on node rnd03 - 10.99.111.103)  I can: 
- PING the host (10.99.111.103)
- PING the other node (10.99.111.104)
- PING another pod on the same node

```bash
│ container-registry             registry-5f697bb7df-s76r4                                ●             1/1                                  1 Running              10.1.72.74                 reamtlrnd04              37m                 ││ kube-system                    calico-kube-controllers-7959b65c6-4c8jc                  ●             1/1                                  1 Running              10.1.72.76                 reamtlrnd04              18m                 ││ kube-system                    calico-node-qnlcg                                        ●             1/1                                  1 Running              10.99.111.103              reamtlrnd03              18m                 ││ kube-system                    calico-node-x2kwn                                        ●             1/1                                  1 Running              10.99.111.104              reamtlrnd04              18m                 ││ kube-system                    coredns-64c6478b6c-swqmx                                 ●             1/1                                  0 Running              10.1.72.78                 rnd04              6m36s               ││ kube-system                    hostpath-provisioner-7764447d7c-p6tn4                    ●             1/1                                  2 Running              10.1.72.77                 reamtlrnd04              37m                 ││ production                     pod-controller-68fcbbfff-qxsdc             ●             1/1                                  1 Running              10.1.72.75                 rnd04              26m                 ││ production                     pod-74b4db7697-4znf5                 ●             1/1                                  1 Running              10.1.78.197                rnd03              26m  
```

So the issue is that one pod on one node cannot connect to a pod on another node. 

I started fiving in Calico's documentation and I tried to run `calicoctl node status`, which gives me: 
```bash
Calico process is running.                                                                                                                                                                                                                                                                                                                                                                                                                                                                The BGP backend process (BIRD) is not running.   
```

So there is indeed an issue. According to the doc I checked that I could make TCP connection on port 179 using `iperf` and configured `NetworkManager` but the BGP backend process is still not running. 

I also tried to specify the network interface using `IP_AUTODETECTION_METHOD=eno1`. But still no luck. 

```bash
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 30:9c:23:8b:9b:1f brd ff:ff:ff:ff:ff:ff
    inet 10.99.111.104/24 brd 10.99.111.255 scope global dynamic eno1
       valid_lft 3496sec preferred_lft 3496sec
    inet6 fe80::6d0c:9f1:320f:8764/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: enp3s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9000 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:1b:21:a9:f0:14 brd ff:ff:ff:ff:ff:ff
4: enp3s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:1b:21:a9:f0:15 brd ff:ff:ff:ff:ff:ff
5: docker_gwbridge: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:3d:c8:19:13 brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.1/16 brd 172.20.255.255 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:41:de:3e:ed brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
7: br-a97c54a911e3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:94:de:47:12 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-a97c54a911e3
       valid_lft forever preferred_lft forever
8: calib9339b5aa93@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-15d04f54-d345-0266-616d-3258b0bac74f
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
9: cali08d8c825d8d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-8a05cbdd-328b-58e0-9c88-3880924d2969
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
12: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default
    link/ether 66:b0:55:47:02:ae brd ff:ff:ff:ff:ff:ff
    inet 10.1.72.64/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::64b0:55ff:fe47:2ae/64 scope link
       valid_lft forever preferred_lft forever
13: cali837999d87fc@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-9eae2745-2ca9-4009-0911-8778fb56764b
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
14: cali223ed954663@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-92010649-d54b-62fd-c170-61d64638cc43
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
15: cali151a8c6b2f2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-613ce4de-93e7-91e0-4efc-168a1deaabf2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by maximehyh** [comment]
https://github.com/projectcalico/calico/issues/5884

**Comment by ktsakalozos** [comment]
Hi @maximehyh, we use vxlan [1] this is why you get the `The BGP backend process (BIRD) is not running.` message. Before diving deeper into calico networking I would strongly recommend to update the hostname to lowercase based on so it complies with [2, 3].

[1] https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options#switching-from-ip-in-ip-to-vxlan 
[2] https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
[3] https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by maximehyh** [comment]
Hi @ktsakalozos after (permanently) changing the hostname, reset the iptables and a few reboots I finally managed to make it work. Thanks a lot. 

I am still having another issue though. 

One of the pod I am deploying needs access to the host's network as it connects to a GigE camera over TCP and some random UDP ports. I am allowing this to happen thanks to Multus and a MacVLAN but the same pod also needs to be able to send MQTT messages over TCP to another pod, potentially on another node. 

It seems like the connection the connection to the other node is unstable in this configuration. I get something like 50 to 80% packet loss when pinging the IP of the MQTT broker. 

Do you know if the Multus network interface could clash with the (Calico?) existing one? So far I have overcame this issue by forcing the pod to be an the same node as the broker's pod using Taint and Tolerations.
