### ISSUE TITLE
Microk8s claims that it is started, but does not run when it started

### ISSUE THREAD

**Issue by oheckmann** [canonical/microk8s#3056]
Using a Raspberry Pi 3, with the latest stable 64 bit Raspbian and a microSD card with 128 Gigabytes of memory
Installed microk8s via snap with this argument: sudo snap install microk8s --classic --channel=1.21
When I use the command microk8s start, or microk8s.start, it says that it is started,
But when I run microk8s status, or microk8s.status, it says that it is not running

microk8s inspect yields this:
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

# Warning: iptables-legacy tables present, use iptables-legacy to see them
 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT 
The change can be made persistent with: sudo apt-get install iptables-persistent
WARNING:  Docker is installed. 
File "/etc/docker/daemon.json" does not exist. 
You should create it and add the following lines: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
WARNING:  The memory cgroup is not enabled. 
The cluster may not be functioning properly. Please ensure cgroups are enabled 
See for example: https://microk8s.io/docs/install-alternatives#heading--arm 
Building the report tarball
  Report tarball is at /var/snap/microk8s/3061/inspection-report-20220410_001923.tar.gz

Attached is the report Tarball: 
[inspection-report-20220410_001923.tar.gz](https://github.com/canonical/microk8s/files/8465067/inspection-report-20220410_001923.tar.gz)

Thank you for your assistance

**Comment by ktsakalozos** [comment]
Hi @oheckmann

In the logs of kubelite service (`journalctl -f -u snap.microk8s.daemon-kubelite`) I see the services would not start because they cannot find the default interface.
```
Error: Unable to find suitable network address.error='unable to select an IP from default routes.'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
Apr 10 00:18:18 raspberrypi microk8s.daemon-kubelite[17529]: F0410 00:18:18.809725   17529 daemon.go:67] API Server exited Unable to find suitable network address.error='unable to select an IP from default routes.'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
```
Have a look at [1] on setting a default network interface.

The experience you will have with k8s on a 1GB rpi3 will not be great. I would recommend at least to add some more swap so processes do not get randomly killed.

[1] https://linuxhint.com/change-the-default-interface-in-linux/
