### ISSUE TITLE
Adding another IP addresses to csr.conf.template is conflicting with local ip address

### ISSUE THREAD

**Issue by err404r** [canonical/microk8s#3059]
To access mikrok8s deployd behind NAT by ip address additional address must be added to /var/snap/microk8s/current/certs/csr.conf.template the file looks like that:
```
[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
#MOREIPS
IP.3 = 10.245.162.247
```
After updating certs, csr.conf looks like that
```
[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
IP.3 = 10.5.3.112
IP.3 = 10.245.162.247
```
As a result 10.5.3.112 is excluded from the server certificate.

[inspection-report-20220412_140801.tar.gz](https://github.com/canonical/microk8s/files/8473668/inspection-report-20220412_140801.tar.gz)

**Comment by err404r** [comment]
[inspection-report-20220412_140801.tar.gz](https://github.com/canonical/microk8s/files/8473660/inspection-report-20220412_140801.tar.gz)
And inspection report

**Comment by balchua** [comment]
I always start with `IP.999` or `DNS.999` amd work backwards to overcome this issue.

**Comment by err404r** [comment]
I just check the resulting conf and used next number from it, but anyway this PR should fix it
