### ISSUE TITLE
Add `microk8s --version` flag

### ISSUE THREAD

**Issue by lferran** [canonical/microk8s#3065]
## Goal
The purpose of this ticket is to add the `--version` flag to the main `microk8s` entrypoint.

## Motivation
As of now, we are using `snap info microk8s` and `microk8s.kubectl version` to know which versions of the snap and upstream k8s are installed, correspondingly. However, we are missing a convenient way to check, not only that, but also the versions for all microk8s components (cluster agent, kind, dqlite, etc)

We want to show the version for the following components:
- [x] MicroK8s snap
- [x] Upstream k8s
- [x] cni

## Example output
 ```bash
 $ microk8s --version      
MicroK8s v1.21.11 revision: 3058
  - K8s: 1.21-3
  - CNI: 4.3-beta
 ```

**Comment by lferran** [comment]
@ktsakalozos @neoaggelos since one could build a custom microk8s version tuning env variables like `KUBE_VERSION` and so on, I wonder if we should write all env variable values at built time onto a file, and then `microk8s --version` would just display it.
WDYT?

**Comment by ktsakalozos** [comment]
I am not convinced we should print the versions of all internal components. Does the end user care what is the version of etcd, flannel, traefik that typically are not used? The cluster-agent is something internal to us no one else outside the microk8s devs team know what this component is.

Lets print only what the user cares about: k8s version, CNI version and the snap revision. With the snap revision we can find what is the exact version of each component.

**Comment by ktsakalozos** [comment]
> write all env variable values at built time onto a file

I like this approach because that would mean we would not need to query external services.

**Comment by lferran** [comment]
> > write all env variable values at built time onto a file
> 
> I like this approach because that would mean we would not need to query external services.

What would be an appropriate path to store the versions file? `${SNAP_DATA}/var/versions.json` for instance?

**Comment by lferran** [comment]
Also, could you guide me on how can I obtain the snap version and revision at built time?
