### ISSUE TITLE
The certificate refresh with shell script at crontab.

### ISSUE THREAD

**Issue by minhwan9600** [canonical/microk8s#3066]
I want to renew the certificate with specific user on microk8s.
case1. It's well done with command ( $ microk8s refresh-certs)
case2. I was specific user not root . The shell script didn't work at crontab.
case3. When I was root user, It's well done.

Why didn't the shell script work at crontab when specific user?
for example)

vi certificate.sh
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
microk8s refresh-certs

crontabe -e
* * * * * /home/test/certificate.sh

**Comment by ktsakalozos** [comment]
The `microk8s refresh-certs` command needs to (among others) restart systemd services. This operation is limited to users with elevated privileges.

**Comment by minhwan9600** [comment]
Thank you for your answering.

I understand what you say.

You said "This operation is limited to users with elevated privileges."
I understood the users with elevated privileges has sudo command.
The users can does a microk8s refresh-certs command on the console.

Are there differences for the users to execute a microk8s refresh-certs command between the console and crontab ?
