### ISSUE TITLE
HA Node crashes and do not register after microk8s join

### ISSUE THREAD

**Issue by maximehyh** [canonical/microk8s#3068]
Hello, 

I am currently experiencing issues while trying to join a node to another microk8s node. Joining a node has always been fairly straightforward but I had to do some re work on my network and it now became impossible to rebuild the cluster. 

The main change is that I have added a new network interface on both machines. I have seen several threads mentioning that it could be an issue and tried all the potential solution without success. 

Here are the steps is am doing to ensure a fresh install (**note that `ufw` is disabled on all machines**): 

```bash
sudo snap remove  microk8s --purge
sudo iptables -P FORWARD ACCEPT
sudo snap install  microk8s --classic --channel=1.23
```

Before trying to make one node join another I first tried to change Calico's `IP_AUTODETECTION_METHOD` (https://github.com/canonical/microk8s/issues/1511) variable with the following, without success:
```bash
- name: IP_AUTODETECTION_METHOD
              value: "can-reach=8.8.8.8" # Here I tried with 8.8.8.8, as I know that my interface in 10.99.111.04 can reach the internet,, the gateway at 10.99.111.1, and even the other node at 10.99.111.103
```

I also tried to add `--advertise-address=10.99.111.104` (the IP corresponding to the interface I want the node to advertise) in `kube-api-server` based on https://github.com/canonical/microk8s/issues/2123 without more luck. 

Trying to join the node silently fails with the following console output: 
```bash
sudo microk8s join 10.99.111.104:25000/e72f92fbc1a51982626294e73f443001/eefd6862d1cf
Contacting cluster at 10.99.111.104
Waiting for this node to finish joining the cluster. .. .. ..



```

Then I try to get the nodes on the `master` but the node does not appear, even though it appears in `/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`:

```bash
# Does not appear
NAME         STATUS   ROLES    AGE   VERSION
twmtlrnd04   Ready    <none>   36m   v1.23.5-2+c812603a312d2b

# Does appear
sudo cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
- Address: 10.99.111.104:19001
  ID: 3297041220608546238
  Role: 0
- Address: 10.99.111.103:19001
  ID: 10648468664857155610
  Role: 2
```

And last but not least the node that tried to join suddenly stops working and gives 
```bash
sudo microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

I have generated a tarball on both nodes before and after trying to join (`node` being the machine that tries to join the `master`). 

Would you have an idea on how I could troubleshoot the issue?

FYI other things that I tried: 
- made sure the both hostnames are resolvable and in /etc/hosts
- made sure that the two nodes have a static IP

[node-pre-join.tar.gz](https://github.com/canonical/microk8s/files/8493574/node-pre-join.tar.gz)
[node-post-join.tar.gz](https://github.com/canonical/microk8s/files/8493583/node-post-join.tar.gz)
[master-pre-join.tar.gz](https://github.com/canonical/microk8s/files/8493597/master-pre-join.tar.gz)
[master-post-join.tar.gz](https://github.com/canonical/microk8s/files/8493603/master-post-join.tar.gz)

**Comment by maximehyh** [comment]
FYI I am currently making some tests with k3s and the node registration is working out of the box.

**Comment by maximehyh** [comment]
Looking at the logs on the machine that is crashing and trying to join I see that this error on all the logs linked to K8s: 

```bash
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.152.183.1")
```

I tried to rename `/var/snap/microk8s/current/var/lock/no-cert-reissue` as explained in https://microk8s.io/docs/troubleshooting but without luck.

**Comment by alphayax** [comment]
I still have the same issue with the latest version of k8s :( Any updates ?
