### ISSUE TITLE
keda addons not present in list on microk8s 1.23 stable

### ISSUE THREAD

**Issue by GitMax89** [canonical/microk8s#3069]
Please run `[inspection-report-20220415_101837.tar.gz](https://github.com/canonical/microk8s/files/8494859/inspection-report-20220415_101837.tar.gz)` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

Hello,

i am using microk8s on ubuntu 20.04 virtualized on parallels in my macbook pro M1 Pro.

Why is the Keda addon not present and activated?

Thanks

**Comment by ktsakalozos** [comment]
Hi @GitMax89, the Keda addon is for amd64 but M1 should be an arm64 processor.

**Comment by GitMax89** [comment]
I thank you for the answer. Is it therefore not possible to install keda in any way?

**Comment by ktsakalozos** [comment]
I see Keda has added arm64 support recently so you could be able to follow the upstream instructions [1] and get is deployed.

[1] https://keda.sh/docs/2.6/deploy/#install-3

**Comment by balchua** [comment]
The `arm64` build will be in keda v2.7.  the keda team is working on it.

https://github.com/kedacore/keda/issues/779#issuecomment-1063133713
