### ISSUE TITLE
prometheus ingress controller

### ISSUE THREAD

**Issue by KennethDhoe** [canonical/microk8s#3081]
i want to collect data of the ingress controller provided by the microk8s enable ingress controller. however when i look in prometheus there is no service discovery for the ingress controller. Could this be implemented or could someone help me on the way to get this working?

**Comment by ktsakalozos** [comment]
Hi @KennethDhoe, I haven't tried that. Have you looked at https://github.com/canonical/microk8s/issues/3081 ?

**Comment by KennethDhoe** [comment]
Hello, @ktsakalozos , Yes i have looked into this documentation however that did not resolve the issue. The issue lays in the ingress controller not exposing its metrics outside the pod. it is only reachable by localhost. thus prometheus cannot get the metrics needed for monitoring. Is that something that can be looked into for the ingress addon? thanks!

**Comment by fabioscaccabarozzi** [comment]
Hi @ktsakalozos , I noticed the same issue: we wanted to scrape the ingress metrics, but by default they are not annotated for Prometheus to scrape.
I added to the deployment's [spec.template.metadata](https://github.com/canonical/microk8s-core-addons/blob/main/addons/ingress/ingress.yaml#L172) the following:
```
...
    metadata:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
...
```
With this snippet, the metrics of nginx ingress pods are automatically picked up by Prometheus without further configuration.

**Comment by yunusefendi52** [comment]
just to add, I also added this to make sure nginx metrics is found, add to ports under this https://github.com/canonical/microk8s-core-addons/blob/69d8f85de732d09a669f9cf2dd946342d4bac7d1/addons/ingress/ingress.yaml#L249
```yaml
        - name: prometheus
          containerPort: 10254
          hostPort: 10255
```
