### ISSUE TITLE
Basic new install ... pods in CrashLoopbackOff

### ISSUE THREAD

**Issue by SamD** [canonical/microk8s#3082]
This seems related to Calico specifically calico-kube-controllers and as a result nothing works, ingress, dns, dashboard the whole install is in an unstable state
I did a purge and installed with the latest stable i.e `sudo snap install microk8s --classic --channel=latest/stable` same result

There are numerous errors in the logs related to Calico as you will see in the report but for example
```
13817 pod_workers.go:949] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"calico-kube-controllers\" with CrashLoopBackOff: \"back-off 10s restarting failed container=calico-kube-controllers pod=calico-kube-controllers-58698c8568-xkbq4_kube-system(805ff11b-d8af-4626-8d24-70edbe3e88f3)\"" pod="kube-system/calico-kube-controllers-58698c8568-xkbq4" podUID=805ff11b-d8af-4626-8d24-70edbe3e88f3
```

I disabled my firewall and vpn and still see the same
I read a post that suggested disabling ha `microk8s disable ha-cluster` which didn't fix the issue
I upped the timeout on the calico set for live and ready probes same errors

Please run `[inspection-report-20220420_175832.tar.gz]([inspection-report-20220420_175832.tar.gz](https://github.com/canonical/microk8s/files/8526463/inspection-report-20220420_175832.tar.gz)` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by SamD** [comment]
One more thing, purging microk8s still leaves the calico virtual interfaces and after several restarts attempting to fix the problem I noticed it just kept creating new ones and not cleaning up or reusing the old so it became quite polluted

**Comment by ktsakalozos** [comment]
Hi @SamD, there are lots of things happening in the 3 minutes included in the inspection report. Would it be possible to let the cluster settle for 10 minutes and attach a new inspection report? Thank you.

**Comment by SamD** [comment]
Sorry for late response , I tried again today with 1.24 candidate still the same issue , disabled firewall , flushed iptables, deleted old virtual interfaces (they aren't cleaned up on stop or removal) fresh install same thing, attaching report

[inspection-report-20220427_130604.tar.gz](https://github.com/canonical/microk8s/files/8577489/inspection-report-20220427_130604.tar.gz)

**Comment by ktsakalozos** [comment]
Thank you for the tarball. Could you please try this fix: https://github.com/canonical/microk8s/issues/3085#issuecomment-1110915801 ?

**Comment by SamD** [comment]
@ktsakalozos Yep that did it, thanks ! :partying_face:
