### ISSUE TITLE
Add global docker image prefix to microk8s, since many people cannot access k8s.gcr.io

### ISSUE THREAD

**Issue by fzyzcjy** [canonical/microk8s#3089]
Hi thanks for the library! I hope to add global docker image prefix to microk8s. In other words, if microk8s originally wants to pull from `k8s.gcr.io/image-name`, now with a global setting (say `globalPrefix: my.registry.com`), it is automatically renamed into `my.registry.com/k8s.gcr.io/image-name`.

This is because in many people, including China with 1.4 billion people, cannot access k8s.gcr.io since it is banned.

Related but not the same (proposed solution different): https://github.com/canonical/microk8s/issues/472

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @fzyzcjy. This is definitely something we need to address. Maybe a solution like [1] would be best.

[1] https://github.com/FairwindsOps/saffire

**Comment by neoaggelos** [comment]
We have added documentation for this in https://microk8s.io/docs/registry-private#configure-registry-mirrors-7
