### ISSUE TITLE
failure in name resolution

### ISSUE THREAD

**Issue by ID2343242** [canonical/microk8s#3090]
Please run `microk8s inspect` and attach the generated tarball to this issue.

[inspection-report-20220425_101949.tar.gz](https://github.com/canonical/microk8s/files/8553686/inspection-report-20220425_101949.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

I have a local 3 node k8s cluster. On my development PC I have a config file that Len's uses to access the cluster.  In the file it allows me to list out the ip address of one node per cluster to access it. 

- cluster:
    certificate-authority-data: XXXXX
    server: https://192.168.1.84:16443/ 
  name: microk8s-cluster

When I want to view the logs from a pod in Len's it works as long as the pod is on the node listed here otherwise it throws this error 

Failed to load logs: Get "https://sys0017:10250/containerLogs/mongodb/equinox-mongodb-1/mongodb?tailLines=502&timestamps=true": dial tcp: lookup sys0017: Temporary failure in name resolution
Reason: undefined (500)

I can update the server ip address in the config file on my development PC that Len's uses and whichever node of the cluster I change it to that one starts giving me the logs for it.

I can also fix this issue by editing the /etc/hosts file on each of the node PC's and adding entries for each of the relevant PC's 

127.0.1.1 sys0009

192.168.5.84    sys0001
192.168.5.91    sys0017

However I'm confused as the node's must be communicating with each other without the need to edit the nodes PC's /etc/hosts as otherwise they wouldn't be able to coordinate and do work. So why are they using the IP's of the node's sometimes and using the node's hostnames which they can't resolve othertimes?

**Comment by ktsakalozos** [comment]
Hi @ID2343242, not having resolvable hostnames will run into problems as the one you described. Editing the /etc/hosts is one solution to the problem but it makes adding and removing machines from the cluster a tedious task. In future releases we will be checking hostname resolution during the cluster node joining operation.   

> So why are they using the IP's of the node's sometimes and using the node's hostnames which they can't resolve othertimes?

My understanding is that these are different mechanisms within k8s. The nodes can register with their IP but when looking at the logs or exec in a pod will try to resolve the node name. There might be a configuration for this that I am not aware of.

**Comment by ID2343242** [comment]
Great thanks.
