### ISSUE TITLE
microk8s.daemon-kubelite Failed to start ContainerManager invalid kernel flags vm/overcommit_memory and kernel/panic

### ISSUE THREAD

**Issue by cccscdev** [canonical/microk8s#3091]
MicroK8s version: 1.22/stable
OS: CentOS Linux release 7.9.2009 (Core) - guest VM hosted under VMware
Linux 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Issue:**

kubelite service is stuck in a never-ending crash/restart loop.

The logs show the following error:

microk8s.daemon-kubelite: E0424 03:43:38.826373    8825 kubelet.go:1423] "Failed to start ContainerManager" err="[invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0, invalid kernel flag: kernel/panic, expected value: 10, actual value: 0]"
systemd: snap.microk8s.daemon-kubelite.service: main process exited, code=exited, status=1/FAILURE

I can fix this by setting the following in /etc/sysctl.conf :
vm.overcommit_memory = 1
kernel.panic = 10

After this, the error is resolved and the kubelite service becomes stable in running state.

However, I am confused as to why I had to manually configure these parameters.  As far as I understand, the values that kubelite complains about are the default Linux values.  I have checked the MicroK8s documentation and I'm unable to find any mention of requiring these parameters to be set as a pre-requisite to installing MicroK8s.  Therefore, (given the Linux defaults) I would have expected to see other users encounter this error when they install - but this doesn't seem to be the case based on my searches.  I have also deployed MicroK8s previously and haven't encountered this error before.

Is anyone able to help me understand why I have encountered this issue?

**Comment by balchua** [comment]
Can you check if you have the `--protect-kernel-defaults=true` in the file `/var/snap/microk8s/current/args/kubelet`.  I think this setting will force one to set the `vm.overcommit` to `1`.

**Comment by cccscdev** [comment]
Thanks for your help balchua.  Yes, this is set:

# grep protect-kernel-defaults /var/snap/microk8s/current/args/kubelet
--protect-kernel-defaults=true

I had a look at this setting - "Default kubelet behaviour for kernel tuning. If set, kubelet errors if any of kernel tunables is different than kubelet defaults."

So this explains why the error is occurring.  If my understanding is correct, the default settings for these kernel parameters in Linux is 0.  Therefore, would it not follow that anyone deploying MicroK8s onto Linux will face this same problem with kubelite crash looping with the above error?  It would be unavoidable until the kernel parameters were changed by the user.  Yet, I don't see others raising this issue.  Nor do I see it mentioned in the Kubernetes/MicroK8s documentation.

**Comment by cccscdev** [comment]
Further to the above I have identified some post-deployment local customisation my org is making to MicroK8s, to specifically add the --protect-kernel-defaults=true option to kubelet.  This has now clarified the situation, and explains the behaviour.

Thanks for the help.

**Comment by cccscdev** [comment]
Further info - fyi - the CIS Kubernetes and Google Kubernetes Engine (GKE) Benchmarks best practise is to configure --protect-kernel-defaults=true.  So, if people are hardening their implementation to meet this standard they will see the kubelite error as mentioned above.

To fix this (assuming you want to keep this setting), the kernel parameters would need to be changed in /etc/sysctl.conf :

vm.overcommit_memory = 1
kernel.panic = 10

There may be implications from changing vm.overcommit_memory if your host is running other workloads besides microk8s, that may be impacted.
