### ISSUE TITLE
microk8s hung on microk8s status --wait-ready 

### ISSUE THREAD

**Issue by ekhc** [canonical/microk8s#3094]
I'm installing on CentOS Linux release 7.9.2009 (Core) on a virtual server

[irteamsu@dev-flyte-test01-ncl ~]$ microk8s start
Started.
[irteamsu@dev-flyte-test01-ncl ~]$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

[inspection-report-20220426_214316.tar.gz](https://github.com/canonical/microk8s/files/8563269/inspection-report-20220426_214316.tar.gz)

I've looked through quite a few issues and tried some of the suggestions like snap removing microk8s and installing 1.22 and restarting microk8s.

Would really appreciate some help

**Comment by balchua** [comment]
I see this in the logs.
```
26 21:37:27 dev-flyte-test01-ncl microk8s.daemon-containerd[38209]: time="2022-04-26T21:37:27.318206963+09:00" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="failed to create CRI service: failed to find snapshotter \"overlayfs\""
```
What kind of filesystem is the host using?

Do you this may work https://github.com/canonical/microk8s/issues/1568#issuecomment-693362404?
