### ISSUE TITLE
Microk8s cluster on juju (on openstack) won't start

### ISSUE THREAD

**Issue by Basdbruijne** [canonical/microk8s#3095]
I have a microk8s (1.23) cluster on juju, running on a openstack cloud:

```
Model     Controller            Cloud/Region               Version  SLA          Timestamp
microk8s  foundation-openstack  openstack_cloud/RegionOne  2.9.28   unsupported  14:01:01Z

App       Version  Status  Scale  Charm     Channel  Rev  Exposed  Message
microk8s           active      3  microk8s  stable    13  yes

Unit         Workload  Agent  Machine  Public address  Ports                     Message
microk8s/0   active    idle   0        10.246.180.146  80/tcp,443/tcp,16443/tcp
microk8s/1*  active    idle   1        10.246.180.44   80/tcp,443/tcp,16443/tcp
microk8s/2   active    idle   2        10.246.180.107  80/tcp,443/tcp,16443/tcp

Machine  State    DNS             Inst id                               Series  AZ    Message
0        started  10.246.180.146  4c22a0b2-ed38-4b14-a135-af0087a8538a  focal   nova  ACTIVE
1        started  10.246.180.44   dd159032-fdbf-4035-94d8-8e17411e834d  focal   nova  ACTIVE
2        started  10.246.180.107  6691f375-4d65-4289-bd97-abbc6d0fdbc2  focal   nova  ACTIVE
```

I'm trying to run `juju add-k8s` to bootstrap on the microk8s cluster, but I am running into:
```
$ juju add-k8s microk8s_cloud --controller foundation-openstack
ERROR making juju admin credentials in cluster: ensuring cluster role "juju-credential-675cbee2" in namespace "kube-system": Get "https://10.246.180.44:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-675cbee2": dial tcp 10.246.180.44:16443: i/o timeout
```

Interestingly, juju only picked up the right IP after I ran the `kubeconfig` action. Before that it tried to connect to `172.16.0.70`.
This indicates that microk8s is not running, so I ran:
```
$ juju run-action microk8s/leader start --wait
unit-microk8s-1:
  UnitId: microk8s/1
  id: "6"
  results:
    Stdout: |
      Started.
  status: completed
  timing:
    completed: 2022-04-26 13:50:04 +0000 UTC
    enqueued: 2022-04-26 13:48:54 +0000 UTC
    started: 2022-04-26 13:48:55 +0000 UTC
```

But then verifying that it worked:
```
$ juju run-action microk8s/leader status --wait
unit-microk8s-1:
  UnitId: microk8s/1
  id: "10"
  results:
    Stdout: |
      microk8s is not running. Use microk8s inspect for a deeper inspection.
  status: completed
  timing:
    completed: 2022-04-26 13:56:22 +0000 UTC
    enqueued: 2022-04-26 13:56:19 +0000 UTC
    started: 2022-04-26 13:56:20 +0000 UTC
```

Following the guide on [deploying microk8s with juju](https://discuss.kubernetes.io/t/deploy-microk8s-clusters-using-juju/18355) gave similar results:
```
$ kubectl get node
Unable to connect to the server: dial tcp 10.246.180.44:16443: i/o timeout
```

We used a very similar configuration on a AWS cloud, which did work.
Do you know if there could be some openstack setting that I am missing?

[inspection-report.tar.gz](https://github.com/canonical/microk8s/files/8563917/inspection-report-20220426_135649.tar.gz)
[juju-crashdump-microk8s](https://github.com/canonical/microk8s/files/8563989/juju-crashdump-microk8s-2022-04-26-14.09.26.tar.gz)

**Comment by Basdbruijne** [comment]
Thanks for the quick answer, @neoaggelos 

I added some rules in the security groups in openstack and now the microk8s cluster does start. This is actually on a different deployment using 1.24/edge, so I'm not 100% that that is what solved the problem. The `juju add-k8s` commands are still not working. 

k8s.gcr.io is not accessible from the cluster (I assume k8s.gcr.io is an address, not some kind of service). We do set the juju proxy so I'm not sure why this happens.

**Comment by Basdbruijne** [comment]
I'm trying a deployment on a Maas cloud in parallel. Those nodes also can't reach k8s.gcr.io, but the `juju add-k8s` works fine there.

**Comment by neoaggelos** [comment]
@Basdbruijne I did some testing as well. So your issue with the Kubernetes control plane being unreachable by default is valid, you need to run the following after deploying the charm

```
juju expose microk8s
```

Alternatively, [this page](https://discourse.charmhub.io/t/how-to-specify-application-expose-parameters-within-a-bundle/5697) has useful information for including this in the bundle.

Thanks for catching this, I will go ahead and update the documentation accordingly
