### ISSUE TITLE
Strange Error When Trying out Kubeflow via juju in Microk8s

### ISSUE THREAD

**Issue by joesan** [canonical/microk8s#3099]
I'm facing a strange issue when trying out Microk8s.

As I was running the following command:

```
oesan@joesan-InfinityBook-S-14-v5:~$ juju add-model kubeflow
ERROR opening API connection: starting proxy for api connection: connecting k8s proxy: Get "https://192.168.0.35:16443/api/v1/namespaces/controller-microk8s-localhost/services/controller-service": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.152.183.1")
```

As you can see that it fails and I’m clueless on how to get past this. The documentation does not mention anything about this. I’m sure that I’m missing something very simple. Could anyone please help me point out what this error could be and how to get past this?

**Comment by joesan** [comment]
I kind of managed to fix it, but is this a bug that needs to be fixed appropriately?

https://stackoverflow.com/questions/72014796/microk8s-error-when-trying-to-install-kubeflow

**Comment by luisgrisolia** [comment]
In my case it was a bootstrapping problem not reported, the process staled. Moving the directory name (a backup just in case) and restarting the bootstrap process solved the issue.

**Comment by jaffe-fly** [comment]
> 

how to restart  bootstrap process

**Comment by jaffe-fly** [comment]
> In my case it was a bootstrapping problem not reported, the process staled. Moving the directory name (a backup just in case) and restarting the bootstrap process solved the issue.

how to restart bootstrap process?

**Comment by neoaggelos** [comment]
> how to restart bootstrap process?

@jaffe-fly For the most part, simply running `juju bootstrap microk8s my-controller` should be sufficient.

I am not sure if this would qualify as an issue with MicroK8s or perhaps Juju.

**Comment by neoaggelos** [comment]
Is this still an issue? Is this OK to close this one if not?
