### ISSUE TITLE
calico-node-xxxx “Hit error connecting to datastore” in a newly setup worker node

### ISSUE THREAD

**Issue by usersina** [canonical/microk8s#3101]
I want to create a multi-node cluster with two machines on the same private network. So I followed the [documentation](https://microk8s.io/docs/clustering). Exeuting `kubectl get nodes` shows that the newly created worker node is indeed `Ready`.

However I can see the following error in an automatically created pod by the new worker
> Hit error connecting to datastore - retry error=Get “[https://10.152.183.1:443/api/v1/nodes/foo](https://10.152.183.1/api/v1/nodes/foo)”: dial tcp 10.152.183.1:44 ││ 3: i/o timeout`

![2022-04-27_123724](https://user-images.githubusercontent.com/44204957/165517837-889ea3d9-df6f-46e6-99bc-d1ab3287837e.JPG)
![2022-04-27_123745](https://user-images.githubusercontent.com/44204957/165517847-0c2bf779-284a-4e75-bde9-55fc7c5db149.JPG)

I describe this is [more details here](https://discuss.kubernetes.io/t/calico-node-xxxx-hit-error-connecting-to-datastore-in-a-newly-setup-worker-node/19795).

Output of `microk8s inspect`
[inspection-report-20220427_122038.tar.gz](https://github.com/canonical/microk8s/files/8571961/inspection-report-20220427_122038.tar.gz)

**Comment by usersina** [comment]
I tried monitoring more closely. Looks like calico does find it at first but then it fails to start. From there it's in an endless `Hit error` loop as shown before.

![2022-04-29_095519](https://user-images.githubusercontent.com/44204957/165914581-5c274f40-daaa-46f1-aecf-cecf644143a6.JPG)

**Comment by ktsakalozos** [comment]
Hi @usersina, there might be some iptable rules blocking the pod to pod communication. I see you can docker running, could we test if this plays any role? Could you stop the docker service make sure it does not start at boot time and reboot? Just as a test to see if there are any iptable rules clashing.

**Comment by usersina** [comment]
I've disabled docker from running on startup, rebooted then disabled ipv6. I've also did a `microk8s reset` on both the controller and node machines for good measure before re-joining. I also made sure both machines are ping-able from each other over LAN (but not over WAN) but I still have the same issue.

A couple of points I've noticed that might somehow be related:
* I've tried linking two VMs on **separate networks** and calico works without timing out! I also deployed Pods to test just in case and they do indeed work. However logs will not be streamed to the controller which is a bit weird. I had to adjust the firewall rules appropriately for WAN communication but that doesn't scale very well and I don't suppose I should use that for production. Especially since the logs fail to stream over WAN for some reason.
* If I happen to enable/disable the dns `microk8s enable dns` after I do the join process, then configuring the node timeouts since it's using the external ip and not the LAN ip used during the join operation.

> Configuring node 82.xxx.xxx.xxx
Failed to reach node.
HTTPSConnectionPool(host='82.xxx.xxx.xxx', port=25000): Max retries exceeded with url: /cluster/api/v1.0/configure (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb904012d68>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by usersina** [comment]
Here's the network setup I currently have. `ens224` is the private network and `ens192` is the external ip.

![2022-04-29_215801](https://user-images.githubusercontent.com/44204957/166068789-9dc425b9-1286-478f-91e1-263a32375819.JPG)

**Comment by usersina** [comment]
I finally managed to get it working! Running `microk8s kubectl get nodes -o wide` shows that the Internal IP being used is always the WAN ip and not the LAN one. Therefore I tried looking for a way to change the IP addresses of the nodes and workers and stumbled upon [this issue](https://github.com/canonical/microk8s/issues/2402#issuecomment-950884240).

At the end, I had to do this for all nodes
```bash
microk8s stop
# or for workers: sudo snap stop microk8s

sudo vim.tiny /var/snap/microk8s/current/args/kubelet
# Add this to bottom: --node-ip=<this-specific-node-lan-ip>

sudo vim.tiny /var/snap/microk8s/current/args/kube-apiserver
# Add this to bottom: --advertise-address=<this-specific-node-lan-ip>

microk8s start
# or for workers: sudo snap start microk8s
```

That said, being able to specify both `--node-ip` and `--advertise-address` through runtime envs is definitely helpful.

**Comment by ktsakalozos** [comment]
Could you make sure the hostnames of the VMs are resolvable on all nodes? An easy way to do that is by editing `/etc/hosts`.

**Comment by usersina** [comment]
> Could you make sure the hostnames of the VMs are resolvable on all nodes? An easy way to do that is by editing `/etc/hosts`.

This is from the `kube-worker-test-1` node. They are also resolved in `kube-controller` without issues.
![2022-04-30_131933](https://user-images.githubusercontent.com/44204957/166105290-953f128c-2a44-472f-8e83-af78846771fd.JPG)

**Comment by usersina** [comment]
I was reading a [blog about setting up microk8s](https://fabianlee.org/2021/07/25/kubernetes-microk8s-cluster-on-ubuntu-using-ansible/) which got me to [something about setting up a bridged network](https://fabianlee.org/2019/04/01/kvm-creating-a-bridged-network-with-netplan-on-ubuntu-bionic/) since I was curious and looks like the private network created by my cloud provider is still using **/etc/network/interfaces** and not **/etc/netplan**

`cat /etc/network/interfaces`
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo ens192
iface lo inet loopback

# The primary network interface
allow-hotplug ens192
iface ens192 inet dhcp
iface ens192 inet6 manual
      pre-up sleep 5
      up dhclient -6 -nw -v ens192
      down dhclient -6 -r -v ens192
```

Maybe since the default interface is `ens192` (wan interface), it gets picked up during the join process? I tried changing the default interface but that breaks my ssh session so I can't confirm.

**Comment by usersina** [comment]
This is the network information in the worker once I changed `--node-ip` and `--advertise-address`. This setup seems to work without issues so far. I assume once the join commands executes, linking the worker to the cluster uses the default gateway that's why it didn't work without those settings changed. I will try a clean setup again to validate.

![2022-05-03_130126](https://user-images.githubusercontent.com/44204957/166449368-27518631-f777-4873-9868-00ba1c412053.JPG)

**Comment by usersina** [comment]
Closing the issue since [this here is a direct fix for it](https://github.com/canonical/microk8s/pull/3216).
