### ISSUE TITLE
external-ip pending for services

### ISSUE THREAD

**Issue by mandres18** [canonical/microk8s#3106]
hi, tried installing metallb and creating config but still im having a pending result on my external ip for may loadbalancer.

![image](https://user-images.githubusercontent.com/87108765/165703616-69f0b474-a8e9-4cbd-9fb3-cfb6ea314d3b.png)

![image](https://user-images.githubusercontent.com/87108765/165703862-af7b0c27-7547-48e0-829b-6f6fe8063953.png)

**Comment by ktsakalozos** [comment]
Hi @mandres18, could you describe how you enabled metallb? The metallb addon is the script [1] paired with the maifest at [2].

[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/enable
[2] https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/metallb.yaml
