### ISSUE TITLE
Unable to connect to internal registry 

### ISSUE THREAD

**Issue by SamD** [canonical/microk8s#3112]
I followed the instructions here https://microk8s.io/docs/registry-built-in and different variations I found including 0.0.0.0 but in each case there is nothing listening / exposed on 32000 

When trying to debug the previous issue I reported https://github.com/canonical/microk8s/issues/3082 I noticed the calico vxlan nic gave access to the cluster so tried tagging the image to be that so <vxlan.calico.ip>:32000/my-image and with that I was able to push successfully to the microk8s registry; however, when attempting to deploy a chart it results in an Image Pull error

Is there a recommended previous stable version of microk8s where everything is working because the latest stable version unfortunately doesn't seem to be all that stable or perhaps the latest documentation is not in sync with the release 
[inspection-report-20220429_173027.tar.gz](https://github.com/canonical/microk8s/files/8595364/inspection-report-20220429_173027.tar.gz)

Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by balchua** [comment]
Hi @SamD i mostly use `localhost:32000` as long as I am on the node where MicroK8s is running.
As an example:

``` shell

$ docker pull k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
$ docker tag k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3 localhost:32000/e2e-test-images/jessie-dnsutils:1.3

# push the image to local registry
$ docker push localhost:32000/e2e-test-images/jessie-dnsutils:1.3

# deploy a pod using the newly tagged image
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: localhost:32000/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
EOF

# check if the pod is running
$ kubectl get po
NAME       READY   STATUS    RESTARTS   AGE
dnsutils   1/1     Running   0          6m33s

# check the local registry if it has the image
$ curl http://localhost:32000/v2/e2e-test-images/jessie-dnsutils/tags/list
{"name":"e2e-test-images/jessie-dnsutils","tags":["1.3"]}
```
I also sometimes use my node's ip, for example: `192.168.4.92:32000`

I was checking your logs, i dont seem to see any `ErrPullImage`

**Comment by SamD** [comment]
You are not seeing any error messages since I uninstalled microk8s and went back to minikube but in order to create this issue I reinstalled it. I tried localhost, the direct ip , what I provided from the calico vxlan entry. As mentioned I was able to successfully push but only using that ip address (vxlan nic) localhost did not work. I had disabled fw for sake of testing as well. Nothing worked

**Comment by thebpmgroup** [comment]
Is there anything more that needs to be done other than microk8s enable registry?
I cannot push from my laptop (host) to microk8s registry.
I tagged the container as described in the documentation. e.g. docker build . -t localhost:32000/mycontainer:registry
Then try docker push localhost:32000/mycontainer - connection refused.
Tried the ip address of the cluster. Same.
Tried the ip address of the node port. Same.
Tried adding an ingress. Same.

Help!?!?!?

**Comment by balchua** [comment]
@SamD @thebpmgroup are you both runnin microk8s on VMs?

The one i showed above is im running directly without vm.

**Comment by thebpmgroup** [comment]
I cannot speak for our friend @SamD but I am running microk8s on windows which is running an ubuntu vm.

**Comment by thebpmgroup** [comment]
I cannot see anything listening on 127.0.0.1 (port 32000 or 5000) so I think maybe because this is running in a VM we need an ingress solution?

I added metallb but the external ip goes to <pending> forever. Maybe I also need to install a local DHCP server on the host? This is getting to be a real pita really quick. :-(

**Comment by thebpmgroup** [comment]
I uninstalled an reinstalled the whole application. Now I get microk8s: command not found when I open a shell from the multipass systray menu. This software is not in a good way at present and some more attention from canonical would be appreciated.

**Comment by SamD** [comment]
> @SamD @thebpmgroup are you both runnin microk8s on VMs?
> 
> The one i showed above is im running directly without vm.

Yes I'm running snap from now Ubuntu 22.04, I haven't tried again since my last update here , I don't have a lot of time to try to dig into the root cause although if I find some time over the weekend I might try again since I upgraded my distro.

**Comment by SamD** [comment]
@balchua An update on this, I decided to look at this again and it appears related to running docker in `rootless` mode : https://docs.docker.com/engine/security/rootless/

I switched back to standard docker engine install for Ubuntu https://docs.docker.com/engine/install/ubuntu/ and it worked fine. I'm not sure what the specifics are with the rootless setup that result in the failures, there are limitations listed on the page, but figured I would provide the update here as a heads up
