### ISSUE TITLE
Is running on SLES and openSUSE officlially supported?

### ISSUE THREAD

**Issue by yc185050** [canonical/microk8s#3113]
Found this on snapcraft website, https://snapcraft.io/install/microk8s/opensuse

Is running on openSUSE officially supported? 

What about SLES?

**Comment by ktsakalozos** [comment]
Official support for MicroK8s is available via Ubuntu Advantage [1]. There is no official support for openSUSE and SLES.


[1] https://ubuntu.com/advantage
