### ISSUE TITLE
[Documentation] addons - add repository 

### ISSUE THREAD

**Issue by AlexsJones** [canonical/microk8s#3116]
It would be beneficial to our users if we had a few lines for 1.24 that explain how they can add an addon repository.

e.g.

```
It is possible to add an external addon repo with X, Y, Z
```

We also need to confirm that adding from a branch works, I have not seen this operational yet ( e.g. `https://github.com/canonical/microk8s-core-addons/.git#feat/kube-ovn`)

**Comment by ktsakalozos** [comment]
Is this covered in https://microk8s.io/docs/addons ?

**Comment by evilnick** [comment]
@ktsakalozos it is

- the addons page could probably use a specific branch example though

**Comment by evilnick** [comment]
This was linked from the addons page as well as the covered in the edit/create addon page
