### ISSUE TITLE
Comparison with minikube: 2GB vs 540MB

### ISSUE THREAD

**Issue by guettli** [canonical/microk8s#3118]
https://microk8s.io/compare

Accoding to above page minikube uses 2GB and microk8s 540MB.

Could you please elaborate how you get to these numbers?

Minikube can be used with VM-virtualization or with docker. Please be fair and compare minikube+docker and microk8s.

Other wise you compare the VM-virtualization with container-virtualization.

**Comment by ktsakalozos** [comment]
Hi @guettli. The 540MB is the amount of memory used by the k8s services. Thank you for bringing this page in our attention.  You are right that this page needs to be revised as the 2GB memory usage for minikube is not the only inaccuracy I see there. We will take have news on this issue soon.

**Comment by AlexsJones** [comment]
We are updating this page shortly, thank you so much for bringing it to our attention.

**Comment by guettli** [comment]
the page has changed: https://microk8s.io/compare Memory is now almost equal. Closing this issue.
