### ISSUE TITLE
microk8s helm3 commands on MacOS don't pass the full path to multipass for relative files

### ISSUE THREAD

**Issue by tobybellwood** [canonical/microk8s#3130]
When running microk8s helm3 commands on MacOS, any command that references a file (such as passing a values.yaml), requires the full path (or a variable) to be specified in the microk8s helm3 command (i.e. `microk8s helm3 upgrade --install --create-namespace --namespace ingress-nginx --wait --timeout 30m --version 3.40.0 ingress-nginx ingress-nginx/ingress-nginx -f ${PWD}/helmvalues/ingress-nginx.yaml` Omitting the ${PWD} or just specifying `./` does not pass the full folder path across - the vm assumes a path of `/root/ubuntu`

The microk8s/multipass shim seems to work by mounting the initiating folder into the multipass vm at the exact same mount point - is there a way to either pass across the correct folder location, change the root in the vm for commands to the mounted host, or set the kubeconfig correctly on the host for helm3? I note that `microk8s kubectl` works fine with relative local files.

This is running k8s 1.21 on microk8s 2.2.0 using multipass 1.9.0
```
toby ~ % brew info microk8s
ubuntu/microk8s/microk8s: stable 2.2.0
Small, fast, single-package Kubernetes for developers, IoT and edge
https://microk8s.io/
/opt/homebrew/Cellar/microk8s/2.2.0 (1,913 files, 20MB) *
  Built from source on 2022-05-04 at 05:53:15
From: https://github.com/ubuntu/homebrew-microk8s/blob/HEAD/Formula/microk8s.rb
==> Dependencies
Required: python ✔, kubernetes-cli ✔
==> Requirements
Required: macOS >= 10.12 ✔
==> Caveats
Run `microk8s install` to start with MicroK8s
toby ~ % multipass version
multipass   1.9.0+mac
multipassd  1.9.0+mac
toby ~ % microk8s kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
microk8s-vm   Ready    <none>   19h   v1.21.11-3+68355092a9b768
toby~ % multipass info microk8s-vm

Name:           microk8s-vm
State:          Running
IPv4:           192.168.64.2
                10.1.254.64
Release:        Ubuntu 18.04.6 LTS
Image hash:     f86a544fe791 (Ubuntu 18.04 LTS)
Load:           0.78 1.21 1.22
Disk usage:     4.1G out of 48.3G
Memory usage:   1.1G out of 3.9G
Mounts:         /Users/toby/sites/test-helm => /Users/toby/sites/test-helm
                    UID map: 502:default
                    GID map: 20:default
```
[inspection-report-20220504_232307.tar.gz](https://github.com/canonical/microk8s/files/8627934/inspection-report-20220504_232307.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @tobybellwood ,

This is a limitation of running MicroK8s in a VM. Two options you have is to
- deploy your own set of utilities (eg kubectl, helm) on the host and use the kubeconfig file available with `microk8s config` to reach the cluster.
- use `multipass mount` [1] to mount your working directory in the right place inside the microk8s-vm

[1] https://multipass.run/docs/mount-command

**Comment by tobybellwood** [comment]
Thanks, I got there in the end. It's more of an issue that it's very undocumented that this is how it works, and although the pwd is mounted in the VM, relative paths do not work because the helm3 command presupposes /home/Ubuntu (which can't be mounted).

If helm3 is just a shim command, maybe the context can be passed through?
