### ISSUE TITLE
microk8s netscans external network (calico/iptables issue)

### ISSUE THREAD

**Issue by joaomlneto** [canonical/microk8s#3132]
### Description

I've recently set up microk8s on a dedicated server with just a few add-ons (dns, helm3, ingress, metallb, storage), and quickly started receiving abuse reports related to port scans on the external network:

```
# Netscan detected from host 95.21X.XX.XXX #
##########################################################################

time protocol src_ip src_port dest_ip dest_port
---------------------------------------------------------------------------
Wed May 4 19:50:54 2022 TCP 95.21X.XX.XXX 49488 => 10.152.183.2 5443 
Wed May 4 19:50:54 2022 TCP 95.21X.XX.XXX 49494 => 10.152.183.2 5443 
Wed May 4 19:50:54 2022 TCP 95.21X.XX.XXX 49490 => 10.152.183.2 5443 
```

I've received quite a few, and they always target the same `10.152.183.0/24` subnet and port `5443`.
This subnet matches the pod network, and I guess port `5443` suggests is maybe attempting to reach the API server? Couldn't verify this suspicion yet.

Shouldn't this entry be generated automatically on `iptables`?

### Steps to reproduce
1. Install Ubuntu 20.04.3
1. `apt update && apt upgrade -y`
1. `snap install microk8s --classic`
1. `microk8s status --wait-ready`
1. `microk8s enable dns helm3 ingress storage`
1. `microk8s enable metallb` (when prompted, specifying <IP>:<IP> as the range — e.g. 95.211.11.111-95.211.11.111, where IP is the public IP of the machine)
1. Monitor external traffic
1. After some time, witness some traffic destined to the `10.152.183.0/24` subnet *leaks* through the physical interface (e.g. `eth0`/`enp25s0`/ …)

I also verified that `iptables -L` does not seem to have any rules regarding that subnet, but I might be wrong.

I've already teared down the server (sorry!), but I can attempt to reproduce it and attach the output of `microk8s inspect` if you're unable to do so.

### Versions
- microk8s: `1.23`, `1.24`
- Ubuntu: `20.04.3`/`20.04.4`

**Comment by ktsakalozos** [comment]
Hi @joaomlneto 

The `10.152.183.0/24` is the k8s services subnet, calico is doing the routing.

In [1] of particular interest is the "IP autodetection methods" section. By default the IP autodetection method is "first-found" but you can change that by editing the cni manifest `/var/snap/microk8s/current/args/cni-network/cni.yaml` and kubectl applying it. Maybe you could use an internal interface with "interface=INTERFACE-REGEX" as described in [1].

[1] https://projectcalico.docs.tigera.io/reference/node/configuration

**Comment by joaomlneto** [comment]
Sorry I left this issue open for a while — the problem has been fixed.

The machine was connected to a single network interface (public IP), and no private network interfaces.
The packets were all being routed through that public interface (as it was the only option).

Adding a second interface (with a private subnet; bogus or not) routes the messages through it, and makes the network team happy.
