### ISSUE TITLE
Service of type `ClusterIP` timeouts on Ubuntu 22.04 using 1.23/stable

### ISSUE THREAD

**Issue by usersina** [canonical/microk8s#3149]
#### Summary
Services pointing to Pods deployed to a worker node running on **Ubuntu 22.04** always timeouts. **Ubuntu 20.04** works without issues. See the screenshots below.

#### What Should Happen Instead?
Services pointing to Pods deployed **Ubuntu 22.04** should resolve correctly.

#### Machines setup
I used 3 virtual machines on the same private network from a third party cloud provider for this setup, below is the hostname of each machine.

- `dev-kube-controller` running **Ubuntu 20.04**
- `dev-kube-worker-1` running **Ubuntu 20.04**
- `dev-kube-worker-2` running **Ubuntu 22.04**

#### Reproduction Steps
1. Install MicroK8s on each of the machines normally.
2. Run the add command from `dev-kube-controller`
```bash
microk8s add-node --token <my-32-length-string> --token-ttl 300
```
4. Execute the join command from `dev-kube-worker-1` and `dev-kube-worker-2`
```bash
microk8s join <ip-of-dev-kube-controller>:25000/<my-32-length-string> --worker
```
5. This is besides the point, but I always get [this issue](https://github.com/canonical/microk8s/issues/3101) at this step no matter which version of Ubuntu I have, so I apply [this fix](https://github.com/canonical/microk8s/issues/3101#issuecomment-1113796609) for every node separately.
6. Apply the [following manifests](https://git.incedo.com/usersina/kubernetes-manifests-examples/-/tree/main/fruits) (minus the ingress).

#### Introspection Report
[inspection-report-20220513_114105.tar.gz](https://github.com/canonical/microk8s/files/8686766/inspection-report-20220513_114105.tar.gz)

#### Additional context
I tried using **Ubuntu 22.04** for all virtual machines. Running `microk8s inspect` this way shows a warning that I need to `sudo iptables -P FORWARD ACCEPT` which I did. I also did a `sudo apt-get install iptables-persistent` and a reboot for all virtual machines but the issue still persists. However, the warning doesn't show up anymore when running `microk8s inspect`.

#### Some screenshots
![dev-kube-controller](https://user-images.githubusercontent.com/44204957/168278041-e67c32b5-27e7-4f61-a230-37813f1d5d4a.JPG)
![dev-kube-worker-1](https://user-images.githubusercontent.com/44204957/168278047-c4bdd7a4-95f3-48d2-b7d2-1efc00ca2225.JPG)
![dev-kube-worker-2](https://user-images.githubusercontent.com/44204957/168278058-f261dc73-24e4-46ae-ba15-600d40aec17a.JPG)

Note that if I were to add a `dev-kube-worker-3` running **Ubuntu 20.04**, it works without any issues.

#### Are you interested in contributing with a fix?
Sure, if I can help in any way!

**Comment by RobinJespersen** [comment]
sounds familiar to me, maybe one of the suggested solutions here work for you: https://github.com/canonical/microk8s/issues/3133

**Comment by usersina** [comment]
Here are some more details about how the network interfaces are configured

`kube-worker-1` (the one that works)
![2022-05-17_102902](https://user-images.githubusercontent.com/44204957/168779096-bba69d31-940e-4045-b155-8517465c3810.JPG)
`kube-worker-2` (the one that doesn't work)
![2022-05-17_102849](https://user-images.githubusercontent.com/44204957/168779090-a10e0b63-80bc-4d21-80a3-b118e528375d.JPG)

**Comment by usersina** [comment]
Re-installing **Ubuntu 22.04** as well as  **MicroK8s 1.24** solves this issue apparently. I'm not sure but I tried the setup from scratch and it all works now.
