### ISSUE TITLE
`UnboundLocalError` when `microk8s status --format yaml`

### ISSUE THREAD

**Issue by semrekkers** [canonical/microk8s#3150]
#### Summary

Get an `UnboundLocalError` when running `microk8s status` with output format set to yaml.
```
$ microk8s status --format yaml
microk8s:
  running: True
high-availability:
  enabled: False
addons:
  - name: community
Traceback (most recent call last):
  File "/snap/microk8s/3272/scripts/wrappers/status.py", line 215, in <module>
    print_yaml(isReady, enabled, disabled)
  File "/snap/microk8s/3272/scripts/wrappers/status.py", line 130, in print_yaml
    print("{:>4}repository: {:<1}".format("", enabled["repository"]))
UnboundLocalError: local variable 'enabled' referenced before assignment
```

#### What Should Happen Instead?

Expecting the status output in yaml format without an exception raised.

#### Reproduction Steps

1. `snap install microk8s --classic --channel=latest/stable`
2. `microk8s disable ha-cluster --force` (I think this causes an edge case maybe)
3. `microk8s stop`
4. `microk8s start` (restarting inside a script, but I'm not touching microk8s further)
5. `microk8s status --format yaml`

#### Inspection Report

[inspection-report-20220515_161957.tar.gz](https://github.com/canonical/microk8s/files/8695388/inspection-report-20220515_161957.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @semrekkers I am not able to reproduce this. You said this comes from a run in a script, could you share this script?
