### ISSUE TITLE
Microk8s 1.24 Service Account Tokens Not Generated

### ISSUE THREAD

**Issue by SeanCaruthers** [canonical/microk8s#3154]
Hi everyone, I'll start by saying that this is a great project, thank you!

### Summary ###
In Microk8s v1.24/stable, service account token generation does not occur.   
![1 24](https://user-images.githubusercontent.com/20529369/168699228-9df671a1-c29a-46a6-906e-ab4e85251610.png)

### What Should Happen Instead? ###
In Microk8s v1.23/stable, service account tokens are generated automatically.   We did not see anything related to this in the release notes.  If this divergence is intended, could you point us towards materials that would help in recreating the previous functionality?
![1 23](https://user-images.githubusercontent.com/20529369/168699235-4d53879f-90bf-4ce0-8022-926038faf8a2.png)

### Reproduction Steps ###

Run on Windows 10 Pro with Hyper-V enabled

1. Quick Create an Ubuntu 20.04 VM in the Hyper-V manager on 
![Screen Shot 2022-05-16 at 4 35 26 PM (2)](https://user-images.githubusercontent.com/20529369/168699019-cbec736c-cad2-4635-bfca-adc0bf357f55.png)
2. Install microk8s v1.24/stable.  `sudo snap install microk8s --classic --channel=1.24/stable`
3. View service accounts without tokens `sudo microk8s kubectl get sa -A`

### Introspection Report ###

The following inspection reports are run on the same machine about 10 or so minutes apart.

#### 1.24/stable - no tokens generated ####
[inspection-v1.24.zip](https://github.com/canonical/microk8s/files/8704020/inspection-v1.24.zip)

#### 1.23/stable - tokens generated ####
[inspection-v1.23.zip](https://github.com/canonical/microk8s/files/8704025/inspection-v1.23.zip)

**Comment by balasu** [comment]
I think its related to this change in upstream k8s https://github.com/kubernetes/kubernetes/pull/108309
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade
https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets
