### ISSUE TITLE
Microk8s snap disappears from WSL2 ubuntu 20.04 when windows restarts

### ISSUE THREAD

**Issue by pgfaller** [canonical/microk8s#3159]
#### Summary

Microk8s snap installed using 'sudo snap install microk8s --classic'. Saw that pods were not running, so restarted Windows. Then tried 'microk8s status' and saw:
```
peter@NTT-4SH11X2:~$ microk8s status
internal error, please report: running "microk8s" failed: cannot find installed snap "microk8s" at revision 3272: missing file /snap/microk8s/3272/meta/snap.yaml
peter@NTT-4SH11X2:~$ microk8s inspect
internal error, please report: running "microk8s" failed: cannot find installed snap "microk8s" at revision 3272: missing file /snap/microk8s/3272/meta/snap.yaml
peter@NTT-4SH11X2:~$ ls /snap/microk8s/ -lR
/snap/microk8s/:
total 4.0K
drwxr-xr-x 2 root root 4.0K May 23 10:45 3272/
lrwxrwxrwx 1 root root    4 May 23 10:45 current -> 3272/

/snap/microk8s/3272:
total 0
```
#### What Should Happen Instead?

Microk8s should still be installed, and should be up and running as advertised.
#### Reproduction Steps

1. See above - plain installation
2. Restart Windows

#### Introspection Report

Not possible - see above

**Comment by ktsakalozos** [comment]
Hi @pgfaller. The issue you report sounds similar to the one reported in https://forum.snapcraft.io/t/wsl2-ubuntu20-04-all-snaps-broken-after-each-reboot-even-snapd/24819/3

**Comment by pgfaller** [comment]
Hi @ktsakalozos - thanks for the link. Adding the change suggested in https://github.com/DamionGans/ubuntu-wsl2-systemd-script/pull/49 looked as if it made it work; but unfortunately it (microk8s) only worked once after that. Subsequent restarts threw up new errors. I suspect that WSL and snaps were not made to work together, so I will rather try running microk8s on a real Ubuntu platform.
