### ISSUE TITLE
microk8s fails to install on kernel version >= 5.16

### ISSUE THREAD

**Issue by MFAshby** [canonical/microk8s#3161]
#### Summary

microk8s fails to install on linux kernel 5.16+

#### What Should Happen Instead?

microk8s should install and boot

#### Reproduction Steps

1. Run linux distribution with kernel > 5.16 (e.g. manjaro linux, use the kernel selector to choose)
2. Try to install microk8s with `sudo snap install microk8s --classic`
The snap fails to install because it fails to start the 'daemon-containerd' service. It recommends to look at the daemon log, which has an error like below:
```
May 23 22:14:10 martin-n1517rd microk8s.daemon-containerd[52691]: ++ cat /proc/self/attr/current
May 23 22:14:10 martin-n1517rd microk8s.daemon-containerd[52691]: cat: /proc/self/attr/current: Invalid argument
```

#### Introspection Report

unable to get an inspection report due to failed install

#### Can you suggest a fix?

It looks like the script 'run-containerd-with-args' is checking the file /proc/self/attr/current to determine the apparmor status of the host system. It seems in kernel 5.16+ this got moved to /proc/self/attr/apparmor/current. Probably the containerd boot script should check the new location first.

#### Are you interested in contributing with a fix?

maybe!

**Comment by ktsakalozos** [comment]
Hi @MFAshby, thank you for reporting this. I am not sure if this `/proc/self/attr/apparmor/current` is a kernel or distribution configuration. Here is what I got from a 5.16 deployment on ubuntu lts:
```
ubuntu@omnipotent-woodpecker:~$ uname -a
Linux omnipotent-woodpecker 5.16.0-051600-generic #202201092355 SMP PREEMPT Mon Jan 10 00:21:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@omnipotent-woodpecker:~$ cat /proc/self/attr/current
unconfined
```
But even so I have no objections in making this work better everywhere. Do you think you could provide a patch for [1] so as to address this issue?

[1] https://github.com/canonical/microk8s/blob/master/microk8s-resources/wrappers/run-containerd-with-args#L6

**Comment by MFAshby** [comment]
Interesting!  

I found some relevant discussion [1] [2] and the relevant documentation from the kernel

>  The files directly in /proc/.../attr remain as legacy interfaces for modules that provide subdirectories.

I don't know quite why those legacy interfaces would be failing on my kernel. It does seem like the script should be checking the correct file location for apparmor, and that seems relatively simple to change.

[1] https://bbs.archlinux.org/viewtopic.php?id=263579
[2] https://github.com/docker/for-linux/issues/1199#issuecomment-774811300
[3] https://www.kernel.org/doc/html/latest/admin-guide/LSM/index.html

**Comment by neoaggelos** [comment]
Hi @MFAshby,

I'm going over your changes in this PR, but I see the following:

```
[arch@arch ~]$ uname -r
5.18.2-arch1-1
[arch@arch ~]$ cat /proc/self/attr/current
cat: /proc/self/attr/current: Invalid argument
[arch@arch ~]$ cat /proc/self/attr/apparmor/current
cat: /proc/self/attr/apparmor/current: Invalid argument
```

Further, on this machine (clean archlinux install), MicroK8s installs properly:

```
[arch@arch snapd]$ sudo snap install microk8s --classic
microk8s (1.24/stable) v1.24.0 from Canonical✓ installed
```

And is usable:

```
[arch@arch ~]$ microk8s.kubectl get pod -o wide
NAME                    READY   STATUS    RESTARTS   AGE    IP           NODE   NOMINATED NODE   READINESS GATES
nginx-8f458dc5b-flk79   1/1     Running   0          2m6s   10.1.141.2   arch   <none>           <none>
nginx-8f458dc5b-cgbdk   1/1     Running   0          2m6s   10.1.141.3   arch   <none>           <none>
nginx-8f458dc5b-n4j92   1/1     Running   0          2m6s   10.1.141.4   arch   <none>           <none>
[arch@arch ~]$ curl 10.1.141.2 --silent | head -2 
<!DOCTYPE html>
<html>
```

Are you sure this is the issue that causes containerd to fail? Could there be anything else in the logs?

**Comment by MFAshby** [comment]
hi @neoaggelos , interesting! I wonder if this is down to kernel configuration. I will try to find the relevant settings. Here's the output of uname -a: 
```
[martin@martin-intelz370 ~]$ uname -a
Linux martin-intelz370 5.17.9-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:53 UTC 2022 x86_64 GNU/Linux
```
and the output of trying to read those files on my machine: 
```
[martin@martin-intelz370 ~]$ cat /proc/self/attr/current
cat: /proc/self/attr/current: Invalid argument
[martin@martin-intelz370 ~]$ cat /proc/self/attr/apparmor/current
unconfined
```
and the output of trying to install microk8s from snap:
```
[martin@martin-intelz370 ~]$ sudo snap install microk8s --classic
[sudo] password for martin:
error: cannot perform the following tasks:
- Start snap "microk8s" (3272) services (systemctl command [start snap.microk8s.daemon-containerd.service] failed with exit status 1: Job for snap.microk8s.daemon-containerd.service failed because a timeout was exceeded.
See "systemctl status snap.microk8s.daemon-containerd.service" and "journalctl -xeu snap.microk8s.daemon-containerd.service" for details.
)
```
and journalctl command yields this (the first part is repeated a lot, truncated here)
```
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[41153]: ++ cat /proc/self/attr/current
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[41153]: cat: /proc/self/attr/current: Invalid argument
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[40142]: + '[' '' '!=' unconfined ']'
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[40142]: + exec aa-exec -p unconfined -- /var/lib/snapd/snap/microk8s/3272/run-containerd-with-args
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[40142]: + '[' -d /sys/kernel/security/apparmor ']'
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[41155]: ++ cat /proc/self/attr/current
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[41155]: cat: /proc/self/attr/current: Invalid argument
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[40142]: + '[' '' '!=' unconfined ']'
Jun 10 08:59:36 martin-intelz370 microk8s.daemon-containerd[40142]: + exec aa-exec -p unconfined -- /var/lib/snapd/snap/microk8s/3272/run-containerd-with-args
Jun 10 08:59:36 martin-intelz370 systemd[1]: snap.microk8s.daemon-containerd.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ The unit snap.microk8s.daemon-containerd.service has successfully entered the 'dead' state.
Jun 10 08:59:36 martin-intelz370 systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
░░ Subject: A stop job for unit snap.microk8s.daemon-containerd.service has finished
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░
░░ A stop job for unit snap.microk8s.daemon-containerd.service has finished.
░░
░░ The job identifier is 4124 and the job result is done.
```

I think it is this issue causing the failed install, since without the change in https://github.com/canonical/microk8s/pull/3172 I cannot install microk8s, and with the change I can, and the only thing changed is that file location, I think. I can double check that the same branch without that commit fails.

**Comment by neoaggelos** [comment]
Okay, let me look into it a bit deeper as well. I don't doubt that the issue is there, and it's good to see that you have a solution already.

How do you enable apparmor on your machine?
