### ISSUE TITLE
MicroK8s is not starting

### ISSUE THREAD

**Issue by lglaz** [canonical/microk8s#3166]
#### Summary
I have just installed MicroK8s on my Ubuntu 22.04 box and it is not starting. I've tried 'microk8s inspect' and at the beginning there were two warnings (one about docker and the second about iptables) and after applying the presented instructions the warnings no longer appear. However 'microk8s status' still informs that "microk8s is not running"

#### What Should Happen Instead?
MicroK8s should start normally.

#### Introspection Report

[inspection-report-20220526_163108.tar.gz](https://github.com/canonical/microk8s/files/8779763/inspection-report-20220526_163108.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @lglaz,

`microk8s status` will report the cluster as running if the API server replies and there are is at least one node in "Ready" state [1]. In the inspection tarball I see both conditions are met. Is it possible you called `microk8s status` immediately after the snap installation? Could you call `microk8s status --wait-ready` instead?

[1] https://github.com/canonical/microk8s/blob/master/scripts/wrappers/common/utils.py#L62

**Comment by lglaz** [comment]
> Hi @lglaz,
> 
> `microk8s status` will report the cluster as running if the API server replies and there are is at least one node in "Ready" state [1]. In the inspection tarball I see both conditions are met. Is it possible you called `microk8s status` immediately after the snap installation? Could you call `microk8s status --wait-ready` instead?
> 
> [1] https://github.com/canonical/microk8s/blob/master/scripts/wrappers/common/utils.py#L62

I have tried it several times also after restarting my computer. It is still 'not running' after more than 12 hours. Running it with '--wait-ready' switch just waits indefinitely.

**Comment by dskay** [comment]
Hi @ktsakalozos,
Experiencing the same issue. Any updates on it?

**Comment by neoaggelos** [comment]
Hi @dskay,

Is it possible to share an inspection report from the cluster that is not starting? In that way, we can have a look and see what might be going wrong. Thanks a lot!

**Comment by dskay** [comment]
Hi @neoaggelos,
Sure: [inspection-report-20230214_140948.tar.gz](https://github.com/canonical/microk8s/files/10731822/inspection-report-20230214_140948.tar.gz)

**Comment by neoaggelos** [comment]
In the containerd logs, I see lots of instances of this:

```
фев 13 18:42:02 dennis-pc microk8s.daemon-containerd[7709]: time="2023-02-13T18:42:02.734725179+03:00" level=error msg="loading cgroup for 112313" error="cgroups: cgroup mountpoint does not exist"
```

Are cgroups loaded on the machine? What is the output of `mount | grep cgroup`?

**Comment by dskay** [comment]
The output of "mount | grep cgroup": 
`cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)`
