### ISSUE TITLE
pods cant resolve dns from external dns server

### ISSUE THREAD

**Issue by agonzalezm** [canonical/microk8s#3167]
Ubuntu Server 22.04
microk8s enable dns

pods can ping ips of the network but cant resolve dns names in the network.

from node host i can resolve external dns correctly.

```
-- inside pod---

(ping to external dns ip)
# ping 10.58.20.1
PING 10.58.20.1 (10.58.20.1) 56(84) bytes of data.
64 bytes from 10.58.20.1: icmp_seq=1 ttl=127 time=0.487 ms

(ping to external dns name)
# ping dc01
ping: dc01: Name or service not known

# ping dc01.lab.local
ping: dc01: Name or service not known

# cat /etc/resolv.conf
search app.svc.cluster.local svc.cluster.local cluster.local lab.local
nameserver 10.152.183.10
options ndots:5
root@app-api-6d7f865754-9zcdg:/opt/app/api#
```

**Comment by ktsakalozos** [comment]
Hi @agonzalezm, have you tried to set the forward dns to the dns of your lab? See: https://microk8s.io/docs/addon-dns

**Comment by agonzalezm** [comment]
yes i tried adding my dns to enable dns (microk8s enable dns:10.58.20.1 ) but the same result, this was working months ago in ubutu 20.04, now i installed new machine with 22.04 and dns is not working:

**Comment by agonzalezm** [comment]
the strange this is if i deploy a dnsutils pod it can resolve dns correctly but my pods cant.

**Comment by agonzalezm** [comment]
I tested this in Ubuntu Server 20.04.4 and no problem i can run apt-get update from my container and resolve correctly with my pods, looks like problem in 22.04 not mature enough

**Comment by manoj-bandara** [comment]
microk8s disable dns
export dnss=`cat /run/systemd/resolve/resolv.conf | grep nameserver | cut -d ' ' -f2`
microk8s enable dns:$dnss

**Comment by olamy** [comment]
> microk8s disable dns export dnss=`cat /run/systemd/resolve/resolv.conf | grep nameserver | cut -d ' ' -f2` microk8s enable dns:$dnss

I did that for sure.
But then:
```
microk8s kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # nslookup github.com
Server:		10.152.183.10
Address:	10.152.183.10:53

Non-authoritative answer:

*** Can't find github.com: No answer
```

But more interesting my dns server is 10.0.0.1.
```
/ # nslookup github.com 10.0.0.1
Server:		10.0.0.1
Address:	10.0.0.1:53

Non-authoritative answer:
Name:	github.com
Address: 140.82.114.3

*** Can't find github.com: No answer
```

**Comment by rodrigorodrigues** [comment]
> microk8s disable dns
> export dnss=`cat /run/systemd/resolve/resolv.conf | grep nameserver | cut -d ' ' -f2`
> microk8s enable dns:$dnss

This solution works perfectly for me I wasn't able to connect to external datasource from local k8s cluster with raspberry, after run those commands now it's working.

Thanks

**Comment by Azbesciak** [comment]
I suppose not `gpu` but `dns`.
I just updated our ubuntu 18 to 22, then it turned out that dns does not work at all.
I got info that `/etc/resolv.conf` was not found.. of course, there was some, the default one I suppose, but it was not picked up anyway.

**Comment by AugustBrenner** [comment]
I'm having the same issue on Ubuntu 22

**Comment by teoxrr** [comment]
Same problem here, Jammy

**Comment by neoaggelos** [comment]
Hi @AugustBrenner @teoxrr @Azbesciak , would you mind sharing an inspection tarball (`microk8s inspect`) so that we can look into the issue further? Thanks!

**Comment by timbo-r** [comment]
I've the same issue ...

For the moment I can get around this by defining my dns config in the deployment:
```yaml
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.xx.x
      containers:
```

I configured the dns addon like mentioned above:
`
microk8s enable dns:192.168.xx.x
`

Additionally the metallb addon is enabled.

`cat /etc/os-release`:
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
[...]
```
`snap info microk8s`:
```bash
[...]
installed:               v1.27.4             (5643) 177MB classic
```

**Comment by timbo-r** [comment]
After a weekend of reading, learning and debugging I was able to fix my issue and it was not related to microk8s:

I use a self hosted dns called adguard and configured a dns rewrite rule with a wildcard: e.g. *\*.home.net*. This domain is forwarded to my metallb-ip ...

For testing in a pod i used the dnsutils pod described in the [kubernetes docs](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/).

When executing a ping in this pod ...
`kubectl exec -i -t dnsutils -- ping google.de`
```bash
PING google.de.home.net (192.168.10.30) 56(84) bytes of data.
```

... *google.de* is suffixed with *home.net*

As I learned this is because the ping command will try every search domain listened in `/etc/resolv.conf`. 

`kubectl exec -i -t dnsutils -- cat /etc/resolv.conf`
```bash
search default.svc.cluster.local svc.cluster.local cluster.local home.net
nameserver 10.152.183.10
options ndots:5
```

Because I used a wildcard domain in my adguard the *home.net* search domain is the first one which responded ...
[This](https://github.com/k3s-io/k3s/issues/5045#issuecomment-1026736973) explanation was the key for me.

So the solution for me is to specify every domain, in my adguard, as a whole, like traefik.home.net or heimdall.home.net and not use the wildcard option in my dns rewrites.

Best regards

**Comment by mvarchdev** [comment]
This is what I am getting:
```
root@dnsutils:/# nslookup google.com
Server:         10.152.183.10
Address:        10.152.183.10#53

Non-authoritative answer:
Name:   google.com.sunray.sk
Address: 46.150.201.69
```
Any suggestions? Thanks in advance.

**Comment by mnbf9rca** [comment]
I increased the logging level for coredns. when i inspect the logs, i see it's only trying to resolve local addresses, which means it never resolves:
```
rob@k7:~$ kubectl logs -n kube-system -l k8s-app=kube-dns
[INFO] 10.1.170.77:48121 - 26887 "AAAA IN uksouth.obo.arc.azure.com.mydomain.net. udp 55 false 512" NOERROR qr,rd,ra 153 0.018593215s
[INFO] 10.1.170.77:48121 - 26735 "A IN uksouth.obo.arc.azure.com.mydomain.net. udp 55 false 512" NOERROR qr,rd,ra 153 0.033970645s
[INFO] 10.1.170.77:60249 - 40605 "AAAA IN mcr.microsoft.com.azure-arc-release.svc.cluster.local. udp 71 false 512" NXDOMAIN qr,aa,rd 164 0.000144352s
[INFO] 10.1.170.77:60249 - 40375 "A IN mcr.microsoft.com.azure-arc-release.svc.cluster.local. udp 71 false 512" NXDOMAIN qr,aa,rd 164 0.00014482s
[INFO] 10.1.170.77:53076 - 62574 "AAAA IN mcr.microsoft.com.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000080304s
[INFO] 10.1.170.77:53076 - 62296 "A IN mcr.microsoft.com.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000104837s
[INFO] 10.1.170.77:51504 - 118 "AAAA IN mcr.microsoft.com.cluster.local. udp 49 false 512" NXDOMAIN qr,aa,rd 142 0.000066976s
[INFO] 10.1.170.77:51504 - 65389 "A IN mcr.microsoft.com.cluster.local. udp 49 false 512" NXDOMAIN qr,aa,rd 142 0.000088796s
[INFO] 10.1.170.77:59900 - 11187 "AAAA IN mcr.microsoft.com.mydomain.net. udp 47 false 512" NOERROR qr,rd,ra 145 0.019024323s
[INFO] 10.1.170.77:59900 - 10958 "A IN mcr.microsoft.com.mydomain.net. udp 47 false 512" NOERROR qr,rd,ra 145 0.019595862s
```
