### ISSUE TITLE
Microk8s security patches - Kubernetes updated, but calico images are really old

### ISSUE THREAD

**Issue by gaelgatelement** [canonical/microk8s#3169]
#### Summary

It seems that microk8s images are not being updated with the latest security patches. For example, here is my local kubernetes 1.21 cluster : 

```
$ kubectl get nodes
NAME             STATUS   ROLES    AGE    VERSION
ip-xxx-xx-x-xx   Ready    <none>   120d   v1.21.12-3+6937f71915b56b
```

It shows, as expected, the latest kubernetes release. But when I take a look, for example, at the calico controller : 

```
$ kubectl describe -n kube-system deploy/calico-kube-controllers
Name:               calico-kube-controllers
Namespace:          kube-system
CreationTimestamp:  Wed, 26 Jan 2022 15:16:45 +0000
Labels:             k8s-app=calico-kube-controllers
Annotations:        deployment.kubernetes.io/revision: 1
Selector:           k8s-app=calico-kube-controllers
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           k8s-app=calico-kube-controllers
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod: 
  Service Account:  calico-kube-controllers
  Containers:
   calico-kube-controllers:
    Image:      calico/kube-controllers:v3.13.2
    Port:       <none>
    Host Port:  <none>
    Readiness:  exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:  node
      DATASTORE_TYPE:       kubernetes
    Mounts:                 <none>
  Volumes:                  <none>
  Priority Class Name:      system-cluster-critical
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   calico-kube-controllers-f7868dd95 (1/1 replicas created)
Events:          <none>
```

I'm surprised to see a [2 years old calico image](https://hub.docker.com/layers/kube-controllers/calico/kube-controllers/v3.13.2/images/sha256-bf58609ff39089533b80ff2a10fffd1302346f153c66e24d0572fb8b198daea1?context=explore).

#### What Should Happen Instead?
Calico v3.13 seems to be affected to only a short list of [CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&isCpeNameSearch=true&seach_type=all&query=cpe:2.3:a:projectcalico:calico:3.13.2:*:*:*:*:*:*:*). But that seems odd not to rebuild the images with latest system patches. 

#### Can you suggest a fix?

I'd like to understand the reasoning behind microk8s security updates. Should we expect to see old images on the microk8s system ?

**Comment by ktsakalozos** [comment]
Hi @gaelgatelement, this is an topic we would like to improve and is partially is in the hands of the cluster administration.

The upstream kubernetes project releases patches very frequently (every few weeks). The K8s patch releases are delivered in a timely manner and the cluster updates without the admin needing to do anything. Kubernetes releases go out of maintenance after about a year. Admins need to decide when to upgrade their clusters and trigger such upgrades. So for example admins of 1.21 clusters should update their clusters as soon as possible.

We do not update the workloads running in K8s. This is something the admins should take care. The reasoning behind this is that this may be a disruptive operation and we (MicroK8s) should not assume anything on the expected availability of the running applications.

There is a special subset of workloads that are considered "core" for the cluster and are deployed by default. The CNI is one of them. Currently, the CNI does not change on a running cluster. Probably the easiest way to update the CNI is to edit the cni.yaml manifest under `/var/snap/microk8s/current/args/cni-network/cni.yaml` and kubectl apply it. We have in our plans to, a) monitor upstream releases of "core" workloads, b) update the default manifests with the latest upstream releases and c) see if we can update core workloads in a running cluster without service disruptions.
