### ISSUE TITLE
Hitting Error: with microk8s enable dns storage ..... 127.0.0.1:16443: connect: connection refused

### ISSUE THREAD

**Issue by psakamoori** [canonical/microk8s#3178]
microk8s enable storage ingress metallb:10.64.140.43-10.64.140.49
Enabling default storage class
[sudo] password for psakamoori: 
deployment.apps/hostpath-provisioner unchanged
storageclass.storage.k8s.io/microk8s-hostpath unchanged
serviceaccount/microk8s-hostpath unchanged
clusterrole.rbac.authorization.k8s.io/microk8s-hostpath unchanged
clusterrolebinding.rbac.authorization.k8s.io/microk8s-hostpath unchanged
Storage will be available soon
Enabling Ingress
ingressclass.networking.k8s.io/public unchanged
namespace/ingress unchanged
serviceaccount/nginx-ingress-microk8s-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/nginx-ingress-microk8s-clusterrole unchanged
role.rbac.authorization.k8s.io/nginx-ingress-microk8s-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s created
configmap/nginx-load-balancer-microk8s-conf created
configmap/nginx-ingress-tcp-microk8s-conf created
configmap/nginx-ingress-udp-microk8s-conf created
daemonset.apps/nginx-ingress-microk8s-controller created
Ingress is enabled
Enabling MetalLB
Applying Metallb manifest
namespace/metallb-system created
secret/memberlist created
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
podsecuritypolicy.policy/controller created
podsecuritypolicy.policy/speaker created
serviceaccount/controller created
serviceaccount/speaker created
clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
role.rbac.authorization.k8s.io/config-watcher created
role.rbac.authorization.k8s.io/pod-lister created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
rolebinding.rbac.authorization.k8s.io/config-watcher created
error when creating "STDIN": Post "https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/namespaces/metallb-system/rolebindings?fieldManager=kubectl-client-side-apply": unexpected EOF
error when retrieving current configuration of:
Resource: "apps/v1, Resource=daemonsets", GroupVersionKind: "apps/v1, Kind=DaemonSet"
Name: "speaker", Namespace: "metallb-system"
from server for: "STDIN": Get "https://127.0.0.1:16443/apis/apps/v1/namespaces/metallb-system/daemonsets/speaker": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "controller", Namespace: "metallb-system"
from server for: "STDIN": Get "https://127.0.0.1:16443/apis/apps/v1/namespaces/metallb-system/deployments/controller": dial tcp 127.0.0.1:16443: connect: connection refused
error when retrieving current configuration of:
Resource: "/v1, Resource=configmaps", GroupVersionKind: "/v1, Kind=ConfigMap"
Name: "config", Namespace: "metallb-system"
from server for: "STDIN": Get "https://127.0.0.1:16443/api/v1/namespaces/metallb-system/configmaps/config": dial tcp 127.0.0.1:16443: connect: connection refused

Appreciate any help...  My kubernetes master node/api-server is hosted on 192.168.0.26

 $sudo microk8s enable dns storage ingress metallb:10.64.140.43-10.64.140.49
Enabling DNS
Applying manifest
**The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?**

**=== /etc/hosts file ===**
127.0.0.1       localhost
127.0.1.1       pvlab

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

====Tried below: But did not help:====

 sudo microk8s.refresh-certs --cert server.crt
Taking a backup of the current certificates under /var/snap/microk8s/3202/certs-backup/
Creating new certificates
Signature ok
subject=C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1
Getting CA Private Key
Restarting service kubelite.
Restarting service cluster-agent.

$ sudo microk8s.refresh-certs --cert ca.crt
Taking a backup of the current certificates under /var/snap/microk8s/3202/certs-backup/
Creating new certificates
Can't load /root/.rnd into RNG
140534406043072:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
Signature ok
subject=C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1
Getting CA Private Key
Signature ok
subject=CN = front-proxy-client
Getting CA Private Key
1
Creating new kubeconfig file
Run service command "stop" for services ["daemon-apiserver" "daemon-apiserver-kicker" "daemon-cluster-agent" "daemon-containerd" "daemon-control-plane-kicker" "daemon-controller-manager…
Stopped.
Started.

The CA certificates have been replaced. Kubernetes will restart the pods of your workloads.
Any worker nodes you may have in your cluster need to be removed and re-joined to become aware of the new CA.

==================
DNs Pods running good
==================

psakamoori@pvlab:~/.kube$ kubectl get pods --all-namespaces
NAMESPACE     NAME                            READY   STATUS    RESTARTS         AGE
kube-system   coredns-6d4b75cb6d-dm98k        1/1     Running   0                4h18m
kube-system   coredns-6d4b75cb6d-nq459        1/1     Running   0                4h18m
kube-system   etcd-pvlab                      1/1     Running   4                5d2h
kube-system   kube-apiserver-pvlab            1/1     Running   6                5d2h
kube-system   kube-controller-manager-pvlab   1/1     Running   5 (6m59s ago)    5d2h
kube-system   kube-flannel-ds-jjxx6           1/1     Running   0                3d21h
kube-system   kube-flannel-ds-mwzgv           1/1     Running   0                3d21h
kube-system   kube-proxy-27s2q                1/1     Running   0                3d21h
kube-system   kube-proxy-4rbng                1/1     Running   0                5d2h
kube-system   kube-scheduler-pvlab            1/1     Running   22 (6m59s ago)   5d2h

Appreciate any inputs on how to get this resolved...I am beginner in this space..

**Comment by psakamoori** [comment]
With mick8s inspect...I am seeing below error:

May 30 16:20:29 pvlab systemd[1]: snap.microk8s.daemon-apiserver-kicker.service: Succeeded.
May 30 16:20:29 pvlab systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver-kicker.
May 30 16:21:03 pvlab systemd[1]: Started Service for snap application microk8s.daemon-apiserver-kicker.
May 30 16:21:28 pvlab microk8s.daemon-apiserver-kicker[2413711]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-1': No such file or directory
May 30 16:22:36 pvlab microk8s.daemon-apiserver-kicker[2417496]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-3': No such file or directory
May 30 16:28:29 pvlab microk8s.daemon-apiserver-kicker[2431855]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-1': No such file or directory
May 30 16:32:05 pvlab microk8s.daemon-apiserver-kicker[2440983]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-3': No such file or directory
May 30 16:39:59 pvlab microk8s.daemon-apiserver-kicker[2460148]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-1': No such file or directory
May 30 16:48:55 pvlab microk8s.daemon-apiserver-kicker[2482172]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-1': No such file or directory
May 30 16:59:11 pvlab microk8s.daemon-apiserver-kicker[2507326]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/open-2': No such file or directory
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517451]: Signature ok
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517451]: subject=C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517451]: Getting CA Private Key
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517456]: Signature ok
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517456]: subject=CN = front-proxy-client
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2517456]: Getting CA Private Key
May 30 20:22:41 pvlab microk8s.daemon-apiserver-kicker[2412231]: CSR change detected. Reconfiguring the kube-apiserver
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517617]: Signature ok
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517617]: subject=C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517617]: Getting CA Private Key
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517622]: Signature ok
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517622]: subject=CN = front-proxy-client
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2517622]: Getting CA Private Key
May 30 20:22:49 pvlab microk8s.daemon-apiserver-kicker[2412231]: CSR change detected. Reconfiguring the kube-apiserver
May 30 20:23:36 pvlab microk8s.daemon-apiserver-kicker[2519596]: chgrp: changing group of '/var/snap/microk8s/3202/var/kubernetes/backend/open-2': No such file or directory
May 30 20:29:42 pvlab microk8s.daemon-apiserver-kicker[2534528]: chgrp: changing group of '/var/snap/microk8s/3202/var/kubernetes/backend/open-1': No such file or directory
May 30 20:29:54 pvlab microk8s.daemon-apiserver-kicker[2535007]: chmod: cannot access '/var/snap/microk8s/3202/var/kubernetes/backend/kine.sock': No such file or directory

**Comment by neoaggelos** [comment]
Hi @psakamoori, how did you install microk8s? i see the control plane components running as pods.

```
psakamoori@pvlab:~/.kube$ kubectl get pods --all-namespaces
NAMESPACE NAME READY STATUS RESTARTS AGE
kube-system coredns-6d4b75cb6d-dm98k 1/1 Running 0 4h18m
kube-system coredns-6d4b75cb6d-nq459 1/1 Running 0 4h18m
kube-system etcd-pvlab 1/1 Running 4 5d2h
kube-system kube-apiserver-pvlab 1/1 Running 6 5d2h
kube-system kube-controller-manager-pvlab 1/1 Running 5 (6m59s ago) 5d2h
kube-system kube-flannel-ds-jjxx6 1/1 Running 0 3d21h
kube-system kube-flannel-ds-mwzgv 1/1 Running 0 3d21h
kube-system kube-proxy-27s2q 1/1 Running 0 3d21h
kube-system kube-proxy-4rbng 1/1 Running 0 5d2h
kube-system kube-scheduler-pvlab 1/1 Running 22 (6m59s ago) 5d2h
```

**Comment by psakamoori** [comment]
Hi @neoaggelos , Below are the steps I followed

Step 1.  Created kubernetes cluster using kubeadm as given here "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/"

Step 2: As I want to try MLops pipeline using kubeflow - following instruction given here "https://charmed-kubeflow.io/docs/quickstart" at this step "microk8s enable dns storage ingress metallb:10.64.140.43-10.64.140.49" I am getting above error.

Thank you.

**Comment by psakamoori** [comment]
Got it. Thank you. Will try it out.

**Comment by psakamoori** [comment]
I see - I need to use  below command to get the nodes

psakamoori@pvlab:~/.kube$ microk8s kubectl get nodes
NAME    STATUS   ROLES    AGE   VERSION
pvlab   Ready    <none>   35m   v1.21.12-3+6937f71915b56b

Hope my understanding is correct here..

**Comment by psakamoori** [comment]
Able to resolve as steps explained above
