### ISSUE TITLE
Deployment pods status is CrashLoopBackOff if it have a service

### ISSUE THREAD

**Issue by mahmoodAtcom** [canonical/microk8s#3195]
#### Summary

Creating a service of type NodePort with more than 1000 UDP ports, then create a deployment with one pod that will be used by the Service, the pod won't start and is in CrashLoopBackOff status.

If i do not create the Service, the pod will work normally.

#### What Should Happen Instead?

Pod is expected to run normally.

#### Reproduction Steps

1. create NodePort service
2. create Deployment

#### Introspection Report

[inspection-report-20220602_101139.tar.gz](https://github.com/canonical/microk8s/files/8822830/inspection-report-20220602_101139.tar.gz)

**Comment by balchua** [comment]
@mahmoodAtcom have you tried creating a `Service` with only 1 `NodePort` instead of `1000`.

The only error i see in the logs of freeswitch is this.

```
ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
ERROR: Could not set nice level
2022-06-02 10:09:40.591786 0.00%
```
But then it continues. The `Error: 139` indicates that the process terminated with `SIGSEGV`, meaning freeswitch process crashed.

**Comment by mahmoodAtcom** [comment]
@balchua I've created a service with one port and the pod worked fine. the SCHED_FIFO error appears even in normal working scenarios as it is generated by the application but neglected and doesn't affect the application running state.
All of the below works fine:
1. Create deployment first, then create the service.
2. create deployment with the pod using hostNetwork= true.
3. create deployment without a service.
