### ISSUE TITLE
new microk8s addon to support gopaddle-lite

### ISSUE THREAD

**Issue by kishore-sampathkumar** [canonical/microk8s#3197]
#### Summary
gopaddle-lite is a community edition of gopaddle, a modernization and automation solution on kubernetes clusters.
gopaddle-lite is being made available as an 'addon' on microk8s.

#### Why is this important?
go-paddle Lite is a lifetime free zero-cost end-to-end modernization and automation solution on kubernetes clusters for use by  developers, startups, learners and evaluation and can be brought upon desktops, VMs and host m/cs.

To know more about gopaddle capabilities, you can please visit the official gopaddle website at: gopaddle.io

#### Are you interested in contributing to this feature?
Yes

**Comment by neoaggelos** [comment]
MicroK8s has a GoPaddle addon starting from 1.26, see the docs in https://microk8s.io/docs/addon-gopaddle-lite
