### ISSUE TITLE
enable gpu fails on 22.04 (jammy) - Failed to pull image "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04"

### ISSUE THREAD

**Issue by nobuto-m** [canonical/microk8s#3217]
#### Summary

`microk8s enable gpu` deploys the gpu operator, but it fails eventually on pulling an image for 22.04(jammy).

```
$ snap version
snap    2.55.3+22.04
snapd   2.55.3+22.04
series  16
ubuntu  22.04
kernel  5.15.0-1004-aws

$ snap list microk8s
Name      Version  Rev   Tracking     Publisher   Notes
microk8s  v1.24.0  3272  1.24/stable  canonical✓  classic

$ lspci | grep NVIDIA
00:1e.0 3D controller: NVIDIA Corporation GV100GL [Tesla V100 SXM2 16GB] (rev a1)
```

```
$ microk8s kubectl -n gpu-operator-resources describe all | grep image
  Normal  Pulling    2m35s  kubelet            Pulling image "nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.8.2"
  Normal  Pulled     2m18s  kubelet            Successfully pulled image "nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.8.2" in 16.960575255s
  Normal   Pulling    2m35s                kubelet            Pulling image "nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.1.0"
  Normal   Pulled     2m24s                kubelet            Successfully pulled image "nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.1.0" in 10.97652533s
  Normal   Pulling    48s (x4 over 2m18s)  kubelet            Pulling image "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04"
  Warning  Failed     47s (x4 over 2m17s)  kubelet            Failed to pull image "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04": failed to resolve reference "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04": nvcr.io/nvidia/driver:470.57.02-ubuntu22.04: not found
  Normal   BackOff    33s (x5 over 111s)   kubelet            Back-off pulling image "nvcr.io/nvidia/driver:470.57.02-ubuntu22.04"
```

#### What Should Happen Instead?

`microk8s kubectl -n gpu-operator-resources get all` gets active and available.
OR
Getting a clear message from microk8s that enabling GPU on the base OS is not supported yet.

#### Reproduction Steps

1. prepare Ubuntu 22.04 LTS installation with Nvidia GPU
2. install microk8s
3. microk8s enable gpu

#### Can you suggest a fix?

This may be a limitation in Nvidia upstream (container images and/or gpu operators).
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags
If that's the case, it would be nice to get a warning in the output of `microk8s enable gpu` or in the documentation that the system OS is too new to enable the gpu addon of microk8s.
https://microk8s.io/docs/addon-gpu

**Comment by neoaggelos** [comment]
Update: GPU operator 1.11.0 is released, with support for Ubuntu Jammy https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html

We will be updating the addon (and the documentation page) accordingly.

In the meantime, you can install version 1.11.0 with:

```bash
sudo microk8s enable gpu --version v1.11.0
```
