### ISSUE TITLE
microk8s v1.24 - refresh-certs doesn't seem to refresh certs 

### ISSUE THREAD

**Issue by anubisg1** [canonical/microk8s#3241]
#### Summary
i have microk8s 1.24 and i need to grant access to the cluster via FQDN ..
I edited csr.conf.template  and i refreshed the certificates as follow

```sudo microk8s refresh-certs --cert server.crt```
```sudo microk8s refresh-certs --cert front-proxy-client.crt```

i didn't refresh the ca.ctr  because apparently i would have to rebuild the cluster
" Warning: refreshing the root CA requires nodes to leave and re-join the cluster"
unfortunately it's not yet working... when i connect to the API server via the FQDN i get connection rejected

```
Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, not [xxxxx.com](http://xxxxx.com/)
```

i was only able to make it work, after @neoaggelos  suggested as workaround, to run ```sudo snap set microk8s dummy="$(date)"```

#### What Should Happen Instead?
refresh certs should work

#### Reproduction Steps

add a DNS entry to csr.conf.template and refresh certs

#### Introspection Report

[inspection-report-20220612_111958.tar.gz](https://github.com/canonical/microk8s/files/8885549/inspection-report-20220612_111958.tar.gz)

**Comment by rkrzewski** [comment]
https://microk8s.io/docs/services-and-ports document states that DNS entries for the server can be added to `/var/snap/microk8s/current/certs/csr.conf.template` and `microk8s refresh-certs` should be run afterwards.

However, `microk8s refresh-certs` now requires `--cert` argument and I concur @anubisg1 observation that it does not change the X509v3 Subject Alternative Name entries in API server certificate. `server.csr` and `server.ctr` files are modified but contain only the original `kubernetes...` SAN entries.

I've noticed that adding DNS.n entries `csr.conf` file directly and running `microk8s refresh-certs --cert server.crt` DOES update SAN entries in `server.crt`. Further, I've noticed that timestamp on `csr.conf.rendered` file does not change after running `microk8s refresh-certs`. So it seems that `csr.conf.template` is used only during cluster installation and not when `microk8s refresh-certs` is run.

**Comment by lukewis** [comment]
Seeing this issue also on v1.23

**Comment by lnhrdt** [comment]
> Seeing this issue also on v1.23

Same. I had to downgrade to v1.22 to get valid certs which reflect the entries in `/var/snap/microk8s/current/certs/csr.conf.template`.

**Comment by HazyFish** [comment]
Same on v1.25

**Comment by iamwillbar** [comment]
@neoaggelos is there a reasonable workaround for this? Without this it's not possible to have the microk8s control plane behind a load balancer.

**Comment by anubisg1** [comment]
> @neoaggelos is there a reasonable workaround for this? Without this it's not possible to have the microk8s control plane behind a load balancer.

The workaround is `sudo snap set microk8s dummy="$(date)" ` as described in my initial report

**Comment by iamwillbar** [comment]
Thanks @anubisg1, I missed that.

**Comment by darth-veitcher** [comment]
For others stumbling across this I needed to perform the following in order for MicroK8s nodes to work across my wireguard mesh.

**Before** setting up the cluster, on each node prep them as follows:

* edit `/var/snap/microk8s/current/args/kube-apiserver` and add `--advertise-address={{wireguard_ip}}`
* edit `/var/snap/microk8s/current/args/kubelet` and add `--node-ip={{wireguard_ip}}`
* edit `/var/snap/microk8s/current/certs/csr.conf.template` and add `IP.100 = {{wireguard_ip}}` just before the `#MOREIPS` comment
* refresh the certificates with `sudo microk8s refresh-certs --cert ca.crt --cert server.crt --cert front-proxy-client.crt`
* restart microk8s

Create the cluster...

**After** nodes have joined (and you get the x509 certificate error when trying to run `microk8s kubectl get nodes -o wide`). On each node apply the fix:

* `sudo snap set microk8s dummy="$(date)"`

Hopefully that helps someone else (or me in 6months time when I've forgotten...)
