### ISSUE TITLE
node join issues

### ISSUE THREAD

**Issue by sign-out** [canonical/microk8s#3242]
#### Summary

cant join nodes  cluster  ends in time out error every time despite nodes being able to communicate network wise (ping, smb, nfs ect)

Traceback (most recent call last):
  File "/snap/microk8s/3272/scripts/cluster/join.py", line 968, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/3272/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/3272/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/3272/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/3272/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/3272/scripts/cluster/join.py", line 961, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/3272/scripts/cluster/join.py", line 739, in join_dqlite
    worker=worker,
  File "/snap/microk8s/3272/scripts/cluster/join.py", line 152, in get_connection_info
    conn.connect()
  File "/snap/microk8s/3272/usr/lib/python3.6/http/client.py", line 1438, in connect
    super().connect()
  File "/snap/microk8s/3272/usr/lib/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/snap/microk8s/3272/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/snap/microk8s/3272/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

#### What Should Happen Instead?

the nodes would join as normal 

#### Reproduction Steps

1. ...
2. ...

#### Are you interested in contributing with a fix?

if i could i would but i do not think my skills are up to the task

**Comment by berkayoz** [comment]
Hi @sign-out

Thanks for reaching out. Sorry to hear that you have trouble joining nodes.
Could you please run `microk8s inspect` and attach the generated tarball for the nodes you are trying to join?

**Comment by sign-out** [comment]
[inspection-report-20220612_215030.tar.gz](https://github.com/canonical/microk8s/files/8903388/inspection-report-20220612_215030.tar.gz)
[node1inspection-report-20220612_175108.tar.gz](https://github.com/canonical/microk8s/files/8903389/node1inspection-report-20220612_175108.tar.gz)

**Comment by sign-out** [comment]
sorry i thought they had attached already

**Comment by neoaggelos** [comment]
Hi @sign-out!

Have you seen https://microk8s.io/docs/services-and-ports? From the inspection report, I see that the logs of the `cluster-agent` are empty, thus the join attempt failed to connect (consistent with the error logs you posted in the description).

What happens if you try to do `curl https://$NODEIP:25000/ -k -v` from one to the other?

**Comment by sign-out** [comment]
from node1 -> node0

curl https://node0:25000/ -k -v
*   Trying node0:25000...
* Connected to node0 (node0) port 25000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=GB; ST=Canonical; L=Canonical; O=Canonical; OU=Canonical; CN=127.0.0.1
*  start date: Jun 21 21:36:20 2022 GMT
*  expire date: Jun 21 21:36:20 2023 GMT
*  issuer: CN=10.152.183.1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET / HTTP/1.1
> Host: node0:25000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 NOT FOUND
< Server: gunicorn/19.7.1
< Date: Tue, 21 Jun 2022 21:41:47 GMT
< Connection: close
< Content-Type: text/html; charset=utf-8
< Content-Length: 232
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
* Closing connection 0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS alert, decode error (562):


from node0 -> node 1

 curl https://node1:25000/ -k -v
*   Trying node1:25000...
* connect to node1 port 25000 failed: Connection timed out
* Failed to connect to node1 port 25000: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to node1 port 25000: Connection timed out

**Comment by sign-out** [comment]
is there a way to make it not parse the text ?
