### ISSUE TITLE
CNI not starting with "resource mapping not found for name: "bgpconfigurations.crd.projectcalico.org"" error

### ISSUE THREAD

**Issue by petrastegaev** [canonical/microk8s#3250]
#### Summary
After fresh snap install from snap on debian 11 microk8s cluster is not starting
microk8s status output:
`microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.`

microk8s inspect output:
>Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Also I see following errors in journalctl -u snap.microk8s.daemon-apiserver-kicker
>июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: [resource mapping not found for name: "bgpconfigurations.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "CustomResourceDefinition" in ve>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "bgppeers.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "CustomRe>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "blockaffinities.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "C>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "caliconodestatuses.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "clusterinformations.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kin>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "felixconfigurations.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kin>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "globalnetworkpolicies.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for k>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "globalnetworksets.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind >
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "hostendpoints.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Cus>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "ipamblocks.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Custom>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "ipamconfigs.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Custo>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "ipamhandles.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Custo>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "ippools.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "CustomRes>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "ipreservations.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Cu>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "kubecontrollersconfigurations.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no match>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "networkpolicies.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "C>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "networksets.crd.projectcalico.org" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Custo>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-kube-controllers" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "ClusterRole" in>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-kube-controllers" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "ClusterRoleBind>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-node" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "ClusterRole" in version "rb>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-node" namespace: "" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "ClusterRoleBinding" in vers>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-node" namespace: "kube-system" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "DaemonSet" in ve>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-kube-controllers" namespace: "kube-system" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "Depl>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first, resource mapping not found for name: "calico-kube-controllers" namespace: "kube-system" from "/var/snap/microk8s/3272/args/cni-network/cni.yaml": no matches for kind "PodD>
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: ensure CRDs are installed first]
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: Error from server (Forbidden): error when creating "/var/snap/microk8s/3272/args/cni-network/cni.yaml": configmaps "calico-config" is forbidden: not yet ready to handle request
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: Error from server (Forbidden): error when creating "/var/snap/microk8s/3272/args/cni-network/cni.yaml": serviceaccounts "calico-node" is forbidden: not yet ready to handle request
июн 15 14:34:16 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1534910]: error when creating "/var/snap/microk8s/3272/args/cni-network/cni.yaml": Post "https://127.0.0.1:16443/api/v1/namespaces/kube-system/serviceaccounts?fieldManager=kubectl-client-side-apply&fieldValidation=>
июн 15 14:34:22 stronghold.petrastegaev.dns-cloud.net microk8s.daemon-apiserver-kicker[1529838]: Setting up the CNI

#### What Should Happen Instead?
Cluster should start

#### Reproduction Steps

1. install microk8s following https://microk8s.io/docs/getting-started
2. run 'microk8s start'

#### Are you interested in contributing with a fix?

[inspection-report-20220615_144105.tar.gz](https://github.com/canonical/microk8s/files/8909056/inspection-report-20220615_144105.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @petrastegaev I see in the logs of containerd that there is no default route. Could you add one [1]?

[1] https://www.cyberciti.biz/faq/linux-setup-default-gateway-with-route-command/

**Comment by petrastegaev** [comment]
Hi! I have default route set, still same behaviour:

/home/petr# /sbin/route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.15.10   0.0.0.0         UG    102    0        0 enp6s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.30.32.0     0.0.0.0         255.255.254.0   U     0      0        0 hassio
192.168.15.0    0.0.0.0         255.255.255.0   U     0      0        0 bond0
192.168.15.0    0.0.0.0         255.255.255.0   U     102    0        0 enp6s0

**Comment by ktsakalozos** [comment]
Could you please share a new inspection tarball?
