### ISSUE TITLE
Dashboard addon instructions no longer valid as no token is generated by default for service accounts on 1.24

### ISSUE THREAD

**Issue by fleshin** [canonical/microk8s#3254]
#### Summary
With version 1.24, tokens are no longer generated by default for service accounts. 
The instructions provided https://microk8s.io/docs/addon-dashboard need to include the steps to generate the token.

#### What Should Happen Instead?
Following the steps in the doc should provide working tokens

#### Reproduction Steps
Follow the steps in the doc to get a valid token to login to dashboard
1. token=$(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
2. microk8s kubectl -n kube-system describe secret $token

No valid token is provided
#### Solution
First run: kubectl create token default

**Comment by berkayoz** [comment]
Hey @fleshin 

We have merged this fix into `latest/edge` and stable releases will include it soon.
We will be updating the documentation as necessary as well, many thanks.

**Comment by neoaggelos** [comment]
Hi @fleshin, the documentation page has been updated accordingly, containing steps for MicroK8s 1.24 and newer versions. Thank you!
