### ISSUE TITLE
MacOS M1 multipass &  microk8s -  Refusing join / Failed to update cni configuration

### ISSUE THREAD

**Issue by JCzz** [canonical/microk8s#3258]
Unable to join nodes as described [here](https://microk8s.io/docs/high-availability). 

Update: tried adding `-m 2G` to multipass launch, with same result
Update: also followed this [tutorial](https://pancho.dev/posts/multipass-microk8s-cluster/) with same result.

I am using multipass to create test nodes.

Steps:
1. `multipass launch -n node01 # ..3`
2. `sudo snap install microk8s --classic --channel=1.24/stable`
3.  `sudo microk8s.start` # don't know if this is necessary for setting up, but tried with and without with same result.
4. `sudo microk8s add-node`

**First error**:
```
sudo microk8s join 192.168.64.41:25000/4dfb9ae95c1f0a8e58f273f45ec63c1b/1cf1b6dd4013
Contacting cluster at 192.168.64.41
Connection failed. The hostname (node02) of the joining node does not resolve to the IP "192.168.64.42". Refusing join (400).
```

Then I edited the `etc/host` on `node01` to include ip of `node02`, inspired from this [serverstack](https://serverfault.com/questions/1102223/error-when-create-a-microk8s-cluster-connection-failed-the-hostname-xx-of-t)

Next error then:
```
sudo microk8s join 192.168.64.41:25000/96004259204175a4f72184681d98c397/1cf1b6dd4013
Contacting cluster at 192.168.64.41
Connection failed. Failed to update cni configuration: failed to apply cni configuration: command [/snap/microk8s/3278/microk8s-kubectl.wrapper apply -f /var/snap/microk8s/3278/args/cni-network/cni.yaml] failed with exit code 1: exit status 1 (500).
```

**Comment by JCzz** [comment]
Well well, just open port 25000:
`sudo ufw allow 25000/tcp`

Should I open more, just in case?

Thanks

**Comment by ktsakalozos** [comment]
Hi @JCzz, you might find this page useful https://microk8s.io/docs/services-and-ports
