### ISSUE TITLE
--disk doesn't seem to resize disk

### ISSUE THREAD

**Issue by rogermartensson** [canonical/microk8s#3259]
#### Summary
Multipass: 1.9.1
Microk8s-installer: 2.2.1

Installing microk8s with --disk doesn't seem to resize the disk.

Disk is set to 2GB which is a tad small.

#### What Should Happen Instead?
Disk should be resized to the supplied size.

#### Reproduction Steps
This should create a disk with 10 GB but doesn't.
```
microk8s install --disk 10
```
#### Introspection Report
No report.

#### Can you suggest a fix?
Nope.

It works if I use multipass. (Example from Alternative installation from the documentation)
```
multipass launch --name microk8s-vm --mem 4G --disk 40G
```

#### Are you interested in contributing with a fix?
Wouldn't know where to begin.,,

**Comment by ktsakalozos** [comment]
Hi @rogermartensson, how do you measure the disk size?

If you go into the vm (open a shell) what is the output of `df -h`?

**Comment by rogermartensson** [comment]
I'm not at my computer at the moment so I can't give you an exact output but every time I tried is was a 2GB disk.
I'll return with the output later.

**Comment by neoaggelos** [comment]
Hi @rogermartensson,

Could this be `10` vs `10G`? Can you try with `microk8s install --size=10G`?

**Comment by rogermartensson** [comment]
```
PS C:\Users\Admin> microk8s install --size=10G
usage: microk8s install [-h] [--cpu CPU] [--mem MEM] [--disk DISK] [--channel CHANNEL] [-y]
microk8s install: error: unrecognized arguments: --size=10G
```
Doesn't look like Microk8s 2.2.1 has a --size parameter. Lets use --disk instead.

```
PS C:\Users\Admin> microk8s install --disk=10G
usage: microk8s install [-h] [--cpu CPU] [--mem MEM] [--disk DISK] [--channel CHANNEL] [-y]
microk8s install: error: argument --disk: invalid int value: '10G'
```
