### ISSUE TITLE
"dqlite" shell gets stuck in a multinode microk8s cluster

### ISSUE THREAD

**Issue by vikash686** [canonical/microk8s#3268]
#### Summary
Accessing dqlite shell to look at the secrets works fine in a single node of microk8s but the same gets stuck while working on a multinode. 

#### What Should Happen Instead?
I should be able query my created secret and then look at the content

#### Reproduction Steps
1. Created a 3 node cluster.
```
admin@node3:~$ kubectl get nodes

NAME    STATUS   ROLES           AGE   VERSION
node2   Ready    master,worker   30h   v1.24.0-2+59bbb3530b6769
node1   Ready    master,worker   30h   v1.24.0-2+59bbb3530b6769
node3   Ready    worker          30h   v1.24.0-2+59bbb3530b6769
```

2. Access dqlite shell

```
dbdir="/var/snap/microk8s/current/var/kubernetes/backend"
sudo /snap/microk8s/current/bin/dqlite \
    -c ${dbdir}/cluster.crt \
    -k ${dbdir}/cluster.key \
    -s localhost:19001 k8s
dqlite>

[1]+  Stopped                 sudo /snap/microk8s/current/bin/dqlite -c ${dbdir}/cluster.crt -k ${dbdir}/cluster.key -s localhost:19001 k8s
admin@node2:~$
```
NOTE : I have to forcefully come out of the shell since it is stuck by pressing "ctrl+z"

3. Press "enter" key or execute any command for ex. select name from sqlite_master where type = "table"  and hit "enter"
4. The shell is stuck.

#### Introspection Report
[inspection-report-20220622_125651.tar.gz](https://github.com/canonical/microk8s/files/8957741/inspection-report-20220622_125651.tar.gz)

**Comment by neoaggelos** [comment]
Hi @vikash686 

Dqlite initially listens on `localhost:19001`, but after joining a node it will switch to use the appropriate network interface. This is why your shell hangs (there is nothing listening on `localhost:19001` anymore).

Instead, you can connect to dqlite using the `cluster.yaml` file (which contains the addresses of all known nodes):

```
dbdir="/var/snap/microk8s/current/var/kubernetes/backend"
sudo /snap/microk8s/current/bin/dqlite \
    -c ${dbdir}/cluster.crt \
    -k ${dbdir}/cluster.key \
    -s ${dbdir}/cluster.yaml k8s
```

**Comment by vikash686** [comment]
Thanks for the quick response. Really appreciate it a lot.
However, connecting using cluster.yaml does not work either.

```
admin@node1:~$ dbdir="/var/snap/microk8s/current/var/kubernetes/backend"
sudo /snap/microk8s/current/bin/dqlite \
    -c ${dbdir}/cluster.crt \
    -k ${dbdir}/cluster.key \
    -s ${dbdir}/cluster.yaml k8s
dqlite>

```

**Comment by vikash686** [comment]
Awesome, this works like a charm. Thanks a lot.
