### ISSUE TITLE
Kubelite takes 1.5GB for a 16GB machine

### ISSUE THREAD

**Issue by fzyzcjy** [canonical/microk8s#3279]
#### Summary

I have a 16GB machine which installed microk8s. However, `kubelite` itself takes 1.5GB, which seems a lot considering the total memory is so limited.

Is it a bug with microk8s, or is microk8s just *this* memory-hungry? Thanks.

#### What Should Happen Instead?

less memory

#### Reproduction Steps

1. n/s

#### Introspection Report

[cannot post here for privacy, can you give an email so I will send it]

#### Can you suggest a fix?

willing to pr

#### Are you interested in contributing with a fix?

yes

**Comment by ktsakalozos** [comment]
Hi @fzyzcjy,

What version of Kubernetes are you using? What workloads are you running?

Kubelite runs all the Kubernetes services started from a single process. This includes the control plane unless you `microk8s join` the nodes with the `--worker` flag. In past MicroK8s versions Kubelite also packs the datastore used by K8s.

Here are some configuration options to reduce k8s memory footprint:

- If you are not interested in high availability call `microk8s disable ha-cluster` immediately after you snap installed MicroK8s.
- If you have a multinode cluster join the nodes as worker nodes via the `--worker` flag
- if you know you would not be using some parts of the API offered by the API server, use the `--runtime-config` argument [1] to not load the APIs you do not use. THis argument should be added in `/var/snap/microk8s/current/args/kube-apiserver`.



[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by fzyzcjy** [comment]
> What version of Kubernetes are you using?

1.21

> What workloads are you running?

MySQL, spring, es, kafka, nginx, redis, etc

> This includes the control plane unless you microk8s join the nodes with the --worker flag. In past MicroK8s versions Kubelite also packs the datastore used by K8s.

Yes I need the control plane - since it is the single node.

> If you are not interested in high availability call microk8s disable ha-cluster immediately after you snap installed MicroK8s.

Will this destroy my existing cluster? Thank you
And I have only one node. So will this be affected?

**Comment by ktsakalozos** [comment]
> 1.21

In 1.21 kubelite also includes the datastore.

> Will this destroy my existing cluster?

Yes it will destroy your cluster.

**Comment by fzyzcjy** [comment]
> In 1.21 kubelite also includes the datastore.

So which minimal version shall I upgrade to?

Thanks

**Comment by neoaggelos** [comment]
Hi @fzyzcjy. Note that we support n-2 minor versions from upstream Kubernetes releases.

The current Kubernetes upstream version is 1.24, so MicroK8s versions 1.22, 1.23 and 1.24 are supported.

Unless you have a specific version requirement for your workloads that need pinning to a specific Kubernetes version, it is highly recommended to use `1.24`.

**Comment by fzyzcjy** [comment]
Thank you!

(Btw I was on 1.21 because 1.22 has a lot of API changes...)
