### ISSUE TITLE
Error when trying to deploy a Juju controller to the Kubernetes set up with MicroK8s

### ISSUE THREAD

**Issue by dominikkubik** [canonical/microk8s#3289]
Hello
Ubuntu 22.04
Microk8s 1.21/1.20/1.18

On Linux machine with Ubuntu 22.04 installed on i follow the Quickstart guide to install Kubeflow - https://charmed-kubeflow.io/docs/quickstart
Everything until the step "$juju bootstrap microk8s" was done, but now i am getting still error:
**ERROR resolving microk8s credentials: ensuring cluster role "juju-credential-microk8s" in namespace "kube-system": Get "https://172.16.33.18:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-microk8s": Forbidden**

I tried different microk8s version ( 1.21, 1.20, 1.18) but still the same error from above.
I try to google, yahoo, duckduckgo but nothing which could help me.
Any idea what is wrong?

**Comment by lferran** [comment]
Hi @dominikkubik, thanks for taking the time to bring up this issue.

I have tried to reproduce the issue but it works fine for me. What version of juju are you using?

Also note that as of now, kubeflow is only compatible with microk8s 1.21, so there is no need for you to try with older versions.

**Comment by dominikkubik** [comment]
Hello. Thank you very much for your reply.
I follow up the official Charmed Kubeflow Quickstart guide, which i tried at least 3 times with default (1.21 microk8s and juju version as provided in installation instructions).
Only later on when I searched for errors i found some hints for different microk8s or juju version.

Is there a problem with Ubuntu version? I was able to succesfully finish the Charmed Kubeflow installation on different desktop computer with Ubuntu 20.04.
This last attempt was to install Kubeflow on Laptop with Nvidia GPU and Ubuntu 22.04 and as I described, it failed always on the step above.

**Comment by dominikkubik** [comment]
I also checked the microk8s inspect and there I see following issue with cgroups, but i dont understand why. As i searched, this issue was on Raspberry devices. I have the memory defined, so i am really confused.

WARNING:  The memory cgroup is not enabled.
The cluster may not be functioning properly. Please ensure cgroups are enabled
See for example: https://microk8s.io/docs/install-alternatives#heading--arm
Building the report tarball
  Report tarball is at /var/snap/microk8s/3202/inspection-report-20220706_164812.tar.gz
(base) aimaster@prediction-master-01:/boot$ cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  0       205     1
cpu     0       205     1
cpuacct 0       205     1
blkio   0       205     1
memory  0       205     1
devices 0       205     1
freezer 0       205     1
net_cls 0       205     1
perf_event      0       205     1
net_prio        0       205     1
hugetlb 0       205     1
pids    0       205     1
rdma    0       205     1
misc    0       205     1
(base) aimaster@prediction-master-01:/boot$ mount|grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

**Comment by dominikkubik** [comment]
aimaster@prediction-master-01:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

aimaster@prediction-master-01:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

**# Warning: iptables-legacy tables present, use iptables-legacy to see them
WARNING:  The memory cgroup is not enabled.
The cluster may not be functioning properly. Please ensure cgroups are enabled**
See for example: https://microk8s.io/docs/install-alternatives#heading--arm
Building the report tarball
  Report tarball is at /var/snap/microk8s/3202/inspection-report-20220706_165901.tar.gz

I followed and did all the instructions to fix iptables and cgroups issue, but all i found was useless and did not helped.
Any idea how to move on to run microk8s?

**Comment by lferran** [comment]
hi @dominikkubik, which architecture are you running on?
Could you upload the actual microk8s inspect tarball too?

**Comment by dominikkubik** [comment]
Hello @lferran 

Am running following setup:
Asus Zenbook Pro UX582LR, X86_64 Architecture, Ubuntu 22.04 LTS

and actual microk8s inspect tarball is:
[inspection-report-20220708_143116.tar.gz](https://github.com/canonical/microk8s/files/9072034/inspection-report-20220708_143116.tar.gz)

Thank you very much for any hint, advice or help on this issue
Kind regards

**Comment by qaler** [comment]
Exactly the same problem here, `microk8s` is not running after installing on an Ubuntu 22.04 machine, and `inspect` shows warnings about `iptables-legacy` and `memory group`.

[inspection-report-20220731_212907.tar.gz](https://github.com/canonical/microk8s/files/9230639/inspection-report-20220731_212907.tar.gz)
.

**Comment by neoaggelos** [comment]
Hi @qaler, I see the following errors in the kubelite logs:

```
7月 31 21:28:50 mri-sys-server microk8s.daemon-kubelite[29977]: E0731 21:28:50.389064   29977 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": dial tcp 142.250.157.82:443: i/o timeout" pod="kube-system/calico-node-4r2tz"
```

Can you verify that your system has access to all required registries? Further, https://microk8s.io/docs/registry-private#configure-registry-mirrors-7 might help you.

**Comment by qaler** [comment]
> Hi @qaler, I see the following errors in the kubelite logs:
> 
> ```
> 7月 31 21:28:50 mri-sys-server microk8s.daemon-kubelite[29977]: E0731 21:28:50.389064   29977 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": dial tcp 142.250.157.82:443: i/o timeout" pod="kube-system/calico-node-4r2tz"
> ```
> 
> Can you verify that your system has access to all required registries? Further, https://microk8s.io/docs/registry-private#configure-registry-mirrors-7 might help you.

You are right, the problem occurred because `gcr.io` is not accessible in my region, it would be nice if image pulling process logs could be directly printed in console.

Also, I was using microk8s 1.22 (for kubeflow), so the `Configure registry mirrors` doesn't work, I guess it is for microk8s version 1.23 or newer?

Anyway, thanks for your help!

**Comment by dominikkubik** [comment]
Hello

Trying again the installation as described in Quick start guide, but again getting stop at the step ' juju bootstrap microk8s'
where i get following:

aimaster@prediction-master-01:~$ juju bootstrap microk8s
ERROR required addons not enabled for microk8s, run 'microk8s enable dns storage'
aimaster@prediction-master-01:~$ microk8s enable dns storage
Addon dns is already enabled.
Addon storage is already enabled.
aimaster@prediction-master-01:~$ juju bootstrap microk8s
ERROR required addons not enabled for microk8s, run 'microk8s enable dns storage'

any idea what am i doing wrong? microk8s inspection shows me:

aimaster@prediction-master-01:~$ sudo microk8s inspect                                 
[sudo] password for aimaster:
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

**Comment by dominikkubik** [comment]
I reinstall the computer. The same Hw get the previous version of ubuntu, that is 20.04
Still the same issue, during the microk8s installation command '_microk8s status --wait-ready_' cause that this process gets to sleep mode.
Later on after command microk8s status I get reply that "microk8s is not running. Use microk8s inspect for a deeper inspection." even if i start it previously

I attached the inspection log, as I can not find the reason since i dont have so many experiences.

Any idea what am I doing wrong?
[inspection-report-20220929_132845.tar.gz](https://github.com/canonical/microk8s/files/9674200/inspection-report-20220929_132845.tar.gz)

**Comment by neoaggelos** [comment]
Hi @dominikkubik 

There is two things you can try. If possible, start with a fresh install of MicroK8s 1.23 or newer, then follow the docs to configure a registry mirror for k8s.gcr.io.

Alternatively, edit `/var/snap/microk8s/current/args/containerd-template.toml` and do the following:

```toml
# find the line with sandbox_image and change to:
  sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.1"

# add a new section with the following contents:
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
        endpoint = ["https://registry.aliyuncs.com/google_containers"]
```

Afterwards, try restarting containerd with `sudo snap restart microk8s`. Note that this configuration has been deprecated in containerd, so upgrading to a newer microk8s version should be preferred if it is an option for you.

**Comment by dominikkubik** [comment]
Thank you very much for your reply.
I tried it, with MicroK8s 1.23 and even with MicroK8s 1.25 but still the same.
Can't run the MicroK8s.
I will try to reinstall notebook with new clean Ubuntu Server OS.

**Comment by amandahla** [comment]
I found this issue because I got the same error. Are you behind a proxy/firewall?
Maybe this could help: https://microk8s.io/docs/install-proxy

**Comment by dominikkubik** [comment]
Hi @amandahla 

Yes I am behind a proxy but I already did the proxy settings. But not exactly as listed on souce from URL link you proposed.
So i will check it and try again.

Thank you very much.

**Comment by amandahla** [comment]
There is another thing that I did: changed the default DNS.
Instead of "microk8s enable dns", I found out which one I was using ( resolvectl status) and then used it "microk8s enable dns:1.2.3.4"
Reference: 
https://microk8s.io/docs/addon-dns

**Comment by dominikkubik** [comment]
I just tried it with our DNS based on info ( resolvectl status) but still the same issue.
I appreciate your help.
Thank you very much.

**Comment by dominikkubik** [comment]
I did not find the cause of this error. But i try to reinstall this notebook with Ubuntu Server 22.04 where during the installation process i choose to isntall microk8s and juju and it is working.
