### ISSUE TITLE
Documentation missing ` in command

### ISSUE THREAD

**Issue by j-gooding** [canonical/microk8s#3308]
#### Summary

The documentation for getting the SUBNET cidr the pods are using is missing a `` ` `` character from the given command. As a result the command is unable to complete and bash prompt leaves you with a `>` to finish the command.

#### What Should Happen Instead?

The expected behavior is for the command to give you the cidr subnet the pods are using.

#### Reproduction Steps

1. Navigate to https://microk8s.io/docs/troubleshooting
2. Click on "Pod communication problems when using firewall-cmd (Fedora etc)"
3. Copy the following command from the documentation``SUBNET=`cat /var/snap/microk8s/current/args/cni-network/cni.yaml | grep CALICO_IPV4POOL_CIDR -a1 | tail -n1 | grep -oP '[\d\./]+'``
4. Observe the command is unable to complete because of the missing `` ` `` at the end

#### Can you suggest a fix?

change the documentation to include the `` ` ``. The entire command should be:
```bash
# get the subnet cidr the pods are using
SUBNET=`cat /var/snap/microk8s/current/args/cni-network/cni.yaml | grep CALICO_IPV4POOL_CIDR -a1 | tail -n1 | grep -oP '[\d\./]+'` 
echo $SUBNET
```

#### Are you interested in contributing with a fix?

no

**Comment by neoaggelos** [comment]
Typo has been fixed, thank you!
