### ISSUE TITLE
addon hostpath-storage: Provisioning Volumes needs 1 cpu

### ISSUE THREAD

**Issue by markussiebert** [canonical/microk8s#3314]
#### Summary
Using the hostpath provisioner on small nodes is not possible, as the provisioning pod requests one cpu, even if it's only executing a small shell script.

#### What Should Happen Instead?
The provisioner should start without requesting 1 cpu

#### Reproduction Steps
Create a pv

#### Can you suggest a fix?
It should be configurable how much cpu the hostpath provisioner pod requests 

#### Are you interested in contributing with a fix?
yes, but I don't know where the repo of the provisioner is

**Comment by markussiebert** [comment]
I have build a fix fort this
https://github.com/canonical/hostpath-provisioner/pull/4

**Comment by ktsakalozos** [comment]
Thank you for this fix. We have reviewed the PR and will be merging it soon (this also includes image uploading and updating the respective manifest).
