### ISSUE TITLE
Addon fluentd also for `arm64` architecture

### ISSUE THREAD

**Issue by casabre** [canonical/microk8s#3317]
#### Summary
In order to run more extensive monitoring also on `arm64` architectures, e.g. Raspberry Pi cluster, the `fluentd` addon would be quite handy.

Since all Docker images are available as multi-arch images supporting at least `arm64v8` architecture, I believe the addon could be extended to these images.

## Supported architectures

| Image | `arm32v7` | `arm64v8` | `amd64` | How to pull |
| -------- | -------------- | -------------- | ----------- | ----- |
| [fluentd](https://hub.docker.com/_/fluentd) | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | `docker pull docker.io/fluentd` |
| Elasticsearch | :x: | :heavy_check_mark: > `7.8.0` | :heavy_check_mark:  | `docker pull docker.elastic.co/elasticsearch/elasticsearch:7.8.0` |
| Kibana | :x: | :heavy_check_mark: > `7.13.0` | :heavy_check_mark:  | `docker pull docker.elastic.co/kibana/kibana:7.13.4-arm64` |

#### Why is this important?
Having more extensive logging for the cluster.

#### Are you interested in contributing to this feature?
yes if I can support somehow and it fits my experience :smiley:

**Comment by ktsakalozos** [comment]
Hi @casabre thank you for looking into this. 

If all the images are already multi-arch enabling support for ARM64 may be trivial. Here is a quick test you can do to verify this. Start by installing `microk8s` from `--channel=1.24`. Enable the community addons via `microk8s enable community` then edit `/var/snap/microk8s/common/addons/community/addons.yaml` and in the section of fluentd add the arm64 architecture. This addon should now be visible. Give it a try.

The `addons.yaml` is in [1]. The enable and disable scripts that run when you enable and disable fluentd are in [2] and the manifests applied are in [3]. At runtime, the `https://github.com/canonical/microk8s-community-addons` repository is under `/var/snap/microk8s/common/addons/community/`.

Should you decide to become the maintainer of this addon (at least the arm64 side) you would need to place PRs against https://github.com/canonical/microk8s-community-addons. The doc at [4] may help you. We are pleased to have you onboard and we are more than happy to help you in any way we can.

Thank you.

[1] https://github.com/canonical/microk8s-community-addons/blob/main/addons.yaml#L32
[2] https://github.com/canonical/microk8s-community-addons/tree/main/addons/fluentd
[3] https://github.com/canonical/microk8s-community-addons/tree/main/addons/fluentd/fluentd
[4] https://github.com/canonical/microk8s-community-addons/blob/main/HACKING.md

**Comment by casabre** [comment]
@ktsakalozos thanks for the update. It seems that here custom-baked Docker images are utilized instead of these ones I mentioned. Before I can finally state it is doable, I have to check first on these Dockerfiles. If it seems doable, I am going to raise an issue at the [microk8s-community-addons](https://github.com/canonical/microk8s-community-addons).

Anyway, would be great to have builtin support :)
