### ISSUE TITLE
1.24 CSR rendered config not copied after node join

### ISSUE THREAD

**Issue by bc185174** [canonical/microk8s#3321]
#### Summary

I have a HA cluster consisting of three nodes that we are currently upgrading to 1.24:

```
kubectl get nodes
NAME         STATUS     ROLES    AGE   VERSION
node-00-01   Ready      <none>   62m   v1.24.2-2+b841ff9cb797c4
node-00-02   NotReady   <none>   62m   v1.24.2-2+b841ff9cb797c4
node-00-03   NotReady   <none>   63m   v1.24.2-2+b841ff9cb797c4
```

We found when the two additional nodes join to `node-00-01`, they reach the state `NotReady`, whereas the initial node is `Ready`. It turns out the server certificates on the joining nodes never get regenerated once the CA cert is copied over. The contents of `csr.conf` just contained `changeme`, whereas the `csr.conf.rendered` contained all of the information we expected.

I ran the following snippet from the method [`produce_certs()`](https://github.com/canonical/microk8s/blob/8856e6408cb69ec0b2ee02d939623d2755dcb854/microk8s-resources/actions/common/utils.sh#L423) which returns true, so I would suspect the certs should get regenerated:

```bash
#!/usr/bin/env bash

SNAP_DATA=/var/snap/microk8s/current
SNAP=/data/snap/microk8s/x1
produce_certs() {
    local force
    if ! "${SNAP}/usr/bin/cmp" -s "${SNAP_DATA}/certs/csr.conf.rendered" "${SNAP_DATA}/certs/csr.conf"; then
        force=true
        cp ${SNAP_DATA}/certs/csr.conf.rendered ${SNAP_DATA}/certs/csr.conf
    else
        force=false
    fi
    echo "$force"
}

produce_certs
``` 

In addition to this, we found that the `--node-ip` argument on `node-00-02` or `node-00-03` was reset to the ip of the node they were joining to `node-00-01`. This seemed to happen during the node join or after running `microk8s refresh-certs -e server.crt`.

#### What Should Happen Instead?

1. Certificates should regenerate on joining nodes. 
2. Kubelet args `--node-ip` and/or `--address` arguments should not be set to the ip of the node they are joining to. Ideally, these arguments should be configured by the end user so they can configure the networking themselves.

#### Reproduction Steps

1. Deploy three microk8s nodes using `v1.24`.
2. Configure the `--node-ip` argument the kubelet's config file to match the IP set in `/etc/hosts` (must resolve to the hostname of the node).
3. As per the microk8s documentation, join the additional nodes to the first node.

#### Introspection Report

Contains sensitive data.

#### Can you suggest a fix?

- Not too sure how to go about resolving the certs issue but manually copying the csr.conf and regenerating the server cert (followed by a restart) fixed it.
- Avoid setting the `--node-ip` or `--address` arguments in kubelets config.

#### Are you interested in contributing with a fix?

Yes, happy to work on providing a fix given some advice on the problem/direction.

**Comment by ktsakalozos** [comment]
Hi @bc185174 thank you for reporting this.

Would it be possible to share some inspection tarballs from the nodes? We recently did a fix around node-ip [1] that is about to be released on stable. Thank you.

[1] https://github.com/canonical/microk8s/pull/3216
