### ISSUE TITLE
Make --client-ca-file a different file for kube-apiserver

### ISSUE THREAD

**Issue by aduzsardi** [canonical/microk8s#3322]
#### Summary
It would be nice to have the `--client-ca-file` for the kube-apiserver separate from `${SNAP_DATA}/certs/ca.crt` which is also used by all the other processes in the cluster

#### Why is this important?
If you add a new CA cert in the `${SNAP_DATA}/certs/ca.crt` file for client authentication , **kubelet** becomes unstable and keeps crashing (continuous restarts)

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @aduzsardi. Indeed the ca.crt is used in a couple of cases. However, in the case you are describing  kubelet is expected not to be authorized.

**Comment by aduzsardi** [comment]
i. changed the arguments file manually,  and works, but will probably get overwritten if update microk8s

**Comment by neoaggelos** [comment]
Hi @aduzsardi 

An important note: Upgrading MicroK8s will not make any changes to the configuration files of the services themselves, except in extreme cases where deprecated flags are removed.
