### ISSUE TITLE
microk8s master node status NotReady when refresh-certs is executed

### ISSUE THREAD

**Issue by ortegarenzy** [canonical/microk8s#3329]
#### Summary

When running the command `sudo microk8s refresh-certs` on a master node, it gives me sed error and caused the master node to go to NotReady status

```
~$ sudo microk8s refresh-certs
Taking a backup of the current certificates under /var/snap/microk8s/2530/var/log/ca-backup/
Creating new certificates
Signature ok
subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
Getting CA Private Key
Signature ok
subject=/CN=front-proxy-client
Getting CA Private Key
1
Creating new kubeconfig file
/snap/microk8s/2530/bin/sed: -e expression #1, char 71: unterminated `s' command
Stopped.
Started.

The CA certificates have been replaced. Kubernetes will restart the pods of your workloads.
Any worker nodes you may have in your cluster need to be removed and re-joined to become aware of the new CA.
```

The error was due to having "kubelet-0" string found twice in known_hosts.csv as a result of the said command below
```
kubelet_token=`grep kubelet-0 ${SNAP_DATA}/credentials/known_tokens.csv | cut -d, -f1`
```

#### What Should Happen Instead?

Master node should be able to be on Ready state while successfully refreshing the certificates

#### Reproduction Steps

1. `sudo microk8s refresh-certs`

#### Can you suggest a fix?

Suggested fix is to make the grep command for kubelet-token to be more specific

#### Are you interested in contributing with a fix?

Yes.

**Comment by neoaggelos** [comment]
Hi @ortegarenzy, thank you for reporting the issue and the linked PR. I wonder how the second `kubelet-0` found its way into the `known_tokens.csv`.

My main concern is that this should never happen, and the suggested fix might not work in all cases. Which MicroK8s version is this?

**Comment by ortegarenzy** [comment]
@neoaggelos I am using microk8s version v1.19.5.

This is how my known_tokens.csv looks like when multiple kubelet-0 is found

```
worker-1:~$ cat /var/snap/microk8s/current/credentials/known_tokens.csv
VU1LZjNJWElvQzJseFk4Qm4yVzJYSHNUcDZHZEtBb0Q1YWhsWVJUREptcz0K,system:kube-proxy,kube-proxy
TVBkTmJCMW1UU0xWN1RTTVh0RzRjdkRpQ1kxS0tPWWlrQm9xU0R5YWNoZz0K,system:node:vet-prd-worker-1,kubelet-0,"system:nodes"
K05LMm91VnJqb0RGS3RmK21kbjNCK240Q3ZJZGJtNThCNFJRRTVqY0xpOD0K,system:kube-controller-manager,controller
ekhxdS9na1RVdHBkRjdjVjZMQytzenowMS9zNFh1bHR5cGFTbEVpZE1VVT0K,system:kube-scheduler,scheduler
Rmw5d1lEWTdNeGZkOUpvUnBlUlR1T1RPQ0dQWlR6ck04RGFnaFBVMFdwMD0K,admin,admin,"system:masters"
rHRoMFUcViiiDiQNiGvtAtwEaA7RyvoG,system:node:192.168.13.103,kubelet-02945547,"system:nodes"
ueJueDl9P76VqcYZD4yo4nqauB5Zti8v,system:node:192.168.13.102,kubelet-81420966,"system:nodes"
```

As you can see, `vet-prd-worker-1` has kubelet-0 and as well as the second to the last node(192.168.13.103)
