### ISSUE TITLE
After installing microk8s all of my lxc containers IPv4 addresses disappeared

### ISSUE THREAD

**Issue by casual-lemon** [canonical/microk8s#3334]
#### Summary
After installing microk8s all of my lxc containers IPv4 addresses disappeared. 

I listed my lxc containers with `lxc list` and noticed all of the IPv4 addresses were gone. 

#### What Should Happen Instead?
Ipv4 address tied to local lxc should not be removed

#### Reproduction Steps
1.  sudo snap install microk8s --classic
2.  microk8s status --wait-ready
3. # shows a ready status 
4. lxc list shows empty ipv4 addresses

#### Introspection Report

I can provide an inspect if there is a way to scrub PII.

**Comment by ktsakalozos** [comment]
Hi @casual-lemon, thank you for reporting this.

Could you please offer some more information on the system you are using to reproduce this? I would also be interested on what networks lxc uses, it might be there is some kind of conflict there.

**Comment by casual-lemon** [comment]
root@hypothetical-lemon:/home/heather# lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/instances/focal
- /1.0/instances/bionic
- /1.0/instances/etcdissue
- /1.0/instances/snapcraft-sts-chat-bot
- /1.0/instances/maas31?project=proj-maas
- /1.0/instances/maas28?project=proj-maas
- /1.0/instances/kdumpjammy?project=proj-maas
- /1.0/instances/focalkdump?project=proj-maas
- /1.0/instances/kdumpimpish?project=proj-maas
- /1.0/instances/kdumpbionic?project=proj-maas
- /1.0/instances/apache?project=proj-maas

9: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:69:99:42 brd ff:ff:ff:ff:ff:ff
    inet 10.x.x.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever

heather@hypothetical-lemon:~$ lxc list
```
+-------------+---------+------+------+-----------+-----------+
|    NAME     |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+-------------+---------+------+------+-----------+-----------+
| apache      | RUNNING |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| focalkdump  | STOPPED |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| kdumpbionic | RUNNING |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| kdumpimpish | STOPPED |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| kdumpjammy  | RUNNING |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| maas28      | STOPPED |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
| maas31      | STOPPED |      |      | CONTAINER | 0         |
+-------------+---------+------+------+-----------+-----------+
```

uname -a
Linux hypothetical-lemon 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

All lxc containers use lxdbr0 (bridge network). 
Running Focal with latest kernel.
