### ISSUE TITLE
containerd "state" dir should be in tmpfs instead of persistent folder, otherwise causing bugs

### ISSUE THREAD

**Issue by fzyzcjy** [canonical/microk8s#3336]
#### Summary

As mentioned here https://github.com/containerd/containerd/issues/7194#issuecomment-1190972202, containerd "state" dir should be in tmpfs instead of persistent folder, otherwise causing bugs.

#### What Should Happen Instead?

https://github.com/canonical/microk8s/blob/fed797cfcbacef86cacd8bddf45c74f11e5d0341/microk8s-resources/default-args/containerd#L3

maybe `--state ${SNAP_COMMON}/run/containerd` change to some tmpfs folder.

#### Reproduction Steps

see above

#### Introspection Report

n/a

#### Can you suggest a fix?

see above

#### Are you interested in contributing with a fix?

yes

**Comment by ktsakalozos** [comment]
Hi @fzyzcjy with tmpfs all the state of containerd is reset on a system reboot. As you mention containerd relies on this behavior.

In MicroK8s we detect the first boot of containerd and we make sure we cleanup the containerd state directory including the socket [1]. Is it possible something holds back the `rm` clean up of the containerd state directory? 

[1] https://github.com/canonical/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L700

**Comment by fzyzcjy** [comment]
> Is it possible something holds back the rm clean up of the containerd state directory?

I am not sure... But here is full diagnostics reports and full error description: https://github.com/canonical/microk8s/issues/3335
