### ISSUE TITLE
Can't submit CLA

### ISSUE THREAD

**Issue by csantanapr** [canonical/microk8s#3345]
#### Summary
The CLA form can't be submitted.

I'm currently working on a PR for the repository https://github.com/canonical/microk8s-community-addons, and I can't submit the CLA form. Is my understanding this form is the same for all microk8s contribution repositories.

#### What Should Happen Instead?
Any contributor doing a PR should be able to submit the CLA form.

#### Reproduction Steps
1. Read the [CONTRIBUTING.md](https://github.com/canonical/microk8s-community-addons/blob/main/CONTRIBUTING.md)
2. Click on the link [sign the CLA here](https://ubuntu.com/legal/contributors/agreement)
3. Select individual or corporate
4. On Launchpad id visit the link there [Don’t know your Launchpad id?](https://login.launchpad.net/)
5. The link takes you to the site https://login.launchpad.net/
6. Create a new account Ubuntu One and select username
7. Enter the username in the form input text box 'Launchpad id'
8. Finish entering all the form fields
9. Click the "I agree" green button 

Result:
There is an error popup that there is one problem with the form, but it doesn't indicate in the form which field.

I tried creating a second launchpad account, and the same problem.

#### Can you suggest a fix?
I looked at the chrome console in developer tools, and there is an error on launchpad id error 404.
Remove the need to specify a launchpad id.

Here is the picture of the error
![image](https://user-images.githubusercontent.com/1094878/180578575-03344eaa-1750-48ed-af85-b3544409b0d9.png)

Browser Error:
![image](https://user-images.githubusercontent.com/1094878/180578767-0a4a003a-2f10-453b-8818-54f321e61f5a.png)

**Comment by anthonydillon** [comment]
Hi @csantanapr thank you for taking the time to report this issue to us. A fix and been landed and deployed.

**Comment by csantanapr** [comment]
Thank you @anthonydillon I verified the fix.
