### ISSUE TITLE
Community addon - fluentd/fluent not showing or installable despite enabling community repo (as well as other addons)

### ISSUE THREAD

**Issue by jamescoll** [canonical/microk8s#3354]
#### Summary
When running 'microk8s enable community' it runs successfully and I can see the community repo enabled when I run 'microk8s status' however I cannot install or see listed the fluentd addon in the community repository. I was hoping to install fluentd but this plugin doesn't appear on the list. 

#### What Should Happen Instead?
Expected behaviour would be that after a successful enable of the microk8s community repo and after it is present and visible in 'microk8s status' that I would then be able to install plugins (e.g. fluentd - which is what I was trying to install). Instead I see 'Addon fluentd was not found in any repository' and additionally cannot see listed many other addons from the community repo.

https://microk8s.io/docs/addons - many of these are not present or available in the addons list despite enabling the community repo.

#### Reproduction Steps

1. on the master type 'microk8s enable community' - observe it running successfully
2. run 'microk8s status' - you'll notice the community addon is enabled but you will only see a very small number the community repositories listed.

#### Introspection Report
[inspection-report-20220730_135405.tar.gz](https://github.com/canonical/microk8s/files/9226618/inspection-report-20220730_135405.tar.gz)

#### Can you suggest a fix?
Not sure what the fix is - as I'm not sure what is causing some addons to be visible and others not.

#### Are you interested in contributing with a fix?
Happy to help if I can understand the issue better.

**Comment by balchua** [comment]
Hi @jamescoll not all addons are available for `ARCH=aarch64` architecture.  Speaking about `fluentd`. We are using [this image](https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags). Unfortunately, the inage we are using is rather old which doesn't support `arm64` architecture.  But version 4 does have multi arch support.

Are you interested in contributing this fix?
Thanks 🙏

**Comment by jamescoll** [comment]
Hi - I'll take a look and see if I can figure it out. I know elasticsearch  images themselves didn't support aarch64 for quite some time but have since one of the 7.x versions. Let me take a deeper look and see if I can fix this. Very useful to have this as an addon - as it's ELK stack in one move and ELK can be a bear to set up if you do it by individual components. Leave it with me and I'll report back.

**Comment by jamescoll** [comment]
I have forked the addons repo to see if bumping versions gets fluentd going - will be back in touch if I see progress.

**Comment by briantilburgs** [comment]
I noticed that the 'microk8s repo update community' gives an error, that might be the reason tat this doesn't work.
[ISSUE 3730](https://github.com/canonical/microk8s/issues/3730)

**Comment by guilhermocc** [comment]
Hey there, any updates on this? I'm willing to contribute to fixing this to support arm64 architecture... any tips for updating this addon?
