### ISSUE TITLE
节点采用sdwan组网，打通网络层通讯。安装microk8s想要指定虚拟网卡进行通讯。

### ISSUE THREAD

**Issue by laiqinghua** [canonical/microk8s#3360]
目前我的节点之间采用sdwan组网，打通网络通讯，采用虚拟网卡通讯节点之间相互可以ping通。网卡一共两张：
master:
物理网卡： eth0 ip:192.168.1.5/24
sdwan虚拟网卡： spje2xzwe ip:172.27.0.2/16 <----sdwan 生成的虚拟网卡

work1:
物理网卡： eth0 ip:10.0.1.2/24
sdwan虚拟网卡： spje2xzwe ip:172.27.0.3/16

work2:
物理网卡： eth0 ip:10.0.1.3/24
sdwan虚拟网卡： spje2xzwe ip:172.27.0.4/16

--------------------
节点之间可以通过 网卡：spje2xzwe 进行通讯可以 ping 通。
安装microk8s时会默认使用第一张网卡的地址，我必须要指定要虚拟网卡spje2xzwe上才能通讯。请问我应该如何做？

**Comment by ktsakalozos** [comment]
Hi @laiqinghua would it be possible to use English? Unfortunately we do not have anyone in the team speaking Chinese.

When joining the nodes, do you use the `microk8s join <endpoint>/<token>` that goes through the spje2xzwe?
