### ISSUE TITLE
how edit default endpoints  kubernetes ip 

### ISSUE THREAD

**Issue by laiqinghua** [canonical/microk8s#3363]
![image](https://user-images.githubusercontent.com/39586055/182278963-81969914-0810-455d-8b9f-5979f43a48e9.png)

Please tell me how to modify the network interface address of 192.168.1.5, I need to modify it to another network interface address

**Comment by neoaggelos** [comment]
Hi @laiqinghua.

You need to configure the following arguments for this (assuming the two node interfaces are 192.168.1.5 and 10.10.10.5):

In `/var/snap/microk8s/current/args/kube-apiserver`, set the following:

```
--advertise-address=10.10.10.5
```

Then, in `/var/snap/microk8s/current/args/kubelet`, set:

```
--node-ip=10.10.10.5
```

Make sure that you have setup the IP address as needed, then restart MicroK8s with:

```
sudo snap restart microk8s
```

**Comment by jtcressy** [comment]
Is there any way to automate setting this by maybe using something`--advertise-interface=ethX`? My nodes need to advertise on the interface that is _not_ the default route but the ip address cannot be known ahead of time.

(note the above argument probably doesn't exist, to my knowledge)
