### ISSUE TITLE
Rookie deployment question

### ISSUE THREAD

**Issue by MoO-Jams** [canonical/microk8s#3373]
Deploying on RHEL7 I noticed that microk8s is in the /etc/group file with a GID of under 1000. If I remember best practices a UID/GID under 1000 should be reserved for system accounts or services. Is there an alternate deployment method to specify a GID?  
We used LDAP to control our UIDs/GIDs. Is microk8s considered a system service?

**Comment by ktsakalozos** [comment]
Hi @MoO-Jams, the microk8s group is created in [1] as a system one. You should be able to remove the microk8s group and re-create it as a non-system one.

[1] https://github.com/canonical/microk8s/blob/master/snap/hooks/configure#L370
