### ISSUE TITLE
Unexpected SIGTERM when using microk8s cli on red hat 8.6

### ISSUE THREAD

**Issue by sean-caruthers** [canonical/microk8s#3386]
#### Summary
After installing snap and microk8s (channel 1.24) on red hat 8.6, microk8s cli commands run with sudo are terminated via SIGINT and exit with status code 143.  

#### What Should Happen Instead?
When running without sudo, commands cli work as expected

#### Reproduction Steps

1. Install Red hat 8.6 iso on Hyper V or Virtual Box
2. Follow instructions to install snap on red hat ([red hat installation of snapd](https://snapcraft.io/docs/installing-snap-on-red-hat))
3. install microk8s 
4. Run the following to view unexpected SIGTERM
```sudo microk8s stop && sudo microk8s start```

#### Introspection Report
[inspection-report.tar.gz](https://github.com/canonical/microk8s/files/9302328/inspection-report.tar.gz)

**Comment by sean-caruthers** [comment]
Not sure if anyone is looking into this, but it appears that the command will execute correctly if the sudo is run with the preserve environment flag. 

```sudo -E microk8s stop && sudo -E microk8s start```

I've so far been unable to determine which set of environment variables that determines the success or failure of the cli command.  

Any advice on identifying the determining factor here would be greatly appreciated.

**Comment by xbankov** [comment]
I have experienced the same issue on AlmaLinux.

Command for me were terminating only inside of the bash script, while running them one-by-one there was no problem. 

I confirm that adding sleep increases the chances of success.
