### ISSUE TITLE
Unable to run microk8s kubectl after host reboot (Hyper-V)

### ISSUE THREAD

**Issue by doggy8088** [canonical/microk8s#3388]
#### Summary

I have a fully functional MicroK8s running in my Hyper-V. After my host rebooted, I can't use `microk8s kubectl` anymore. I always get the following error:

```sh
microk8s kubectl get node -o wide
```

> Unable to connect to the server: dial tcp `172.31.119.125:16443`: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

As I know, the master node IP been changed. If I update the KUBECONFIG locally, I can connect to cluster without problem.

```
microk8s config > ~/.kube/config
```

But if I want to use `microk8s kubectl get node -o wide` to get node status, I always can't get it working. I'm still unable to connect to the server.

I tried to clear all possible cache by removing all `.kube/cache` folders. But still not working.

```
sudo rm -rf /.kube/cache /root/.kube/cache /home/ubuntu/.kube/cache /var/snap/microk8s/3582/.kube/cache
```

I stopped and started MicroK8s again. I'm still unable to connect to the server.

```ps1
microk8s stop
microk8s start
```

After MicroK8s restarted, I also tried to find out all files that contains `172.31.119.125` ip address. 

```sh
grep '172.31.119.125' -r /
```

Nothing useful found. Only `/var` contains some logs with `172.31.119.125`. That's so weird. Is there anything I can try? How to connect to MicroK8s using `microk8s kubectl`?

#### What Should Happen Instead?

I expected there a RIGHT way to use `microk8s kubectl`. Even I reboot the host.

#### Reproduction Steps

1. `microk8s install`
2. Reboot host
3. `microk8s kubectl get no -o wide`

#### Introspection Report

[inspection-report-20220814_104341.tar.gz](https://github.com/canonical/microk8s/files/9332643/inspection-report-20220814_104341.tar.gz)

#### Can you suggest a fix?

After 1 hours deep dive, I finally found that there is a `$env:LOCALAPPDATA\MicroK8s\config` file exist which the [doc](https://microk8s.io/docs/working-with-kubectl#heading--kubectl-windows) never said.

PowerShell

```ps1
microk8s config > $env:LOCALAPPDATA\MicroK8s\config
```

Command Prompt

```cmd
microk8s config > %LOCALAPPDATA%\MicroK8s\config
```

#### Are you interested in contributing with a fix?

I strongly recommend this information can add to the doc. Thanks.  Can I contribute docs?

**Comment by madalinignisca** [comment]
If I remember right, with Hyper-V you have to set static IPs, as each reboot will make your virtual machines get another ip.

**Comment by doggy8088** [comment]
@madalinignisca Yes, you are right.

**Comment by karolswdev** [comment]
would you be able to post how you set up the static IP, please?

**Comment by doggy8088** [comment]
@karolswdev I'm not setting up static IP address. It because `microk8s install` use `Default Switch` as the default network on Hyper-V on Windows which means the IP address will change after reboot.
