### ISSUE TITLE
calico-kube-controller stays in pending state

### ISSUE THREAD

**Issue by JoergSnn** [canonical/microk8s#3389]
#### Summary
After I updated Ubuntu 22.04.1 LTS on my raspberry pi 4 with the latest packages (apt update, apt upgrade) microk8s fails to start.

Especially, 
kube-system      calico-node-z9jk8                            0/1     Pending   0               46m
kube-system      calico-kube-controllers-865c95bc57-v4r4p     0/1     Pending   0               46m
kube-system      coredns-64c6478b6c-pwrh5                     0/1     Pending   0               17m

stay in Pending state forever.

Thus I suspect that something is wrong with the calico networking. I have no idea how to troubleshoot this one
I have applied the steps from #3085

[inspection-report-20220813_085924.tar.gz](https://github.com/canonical/microk8s/files/9333581/inspection-report-20220813_085924.tar.gz)

**Comment by ktsakalozos** [comment]
Did your node change hostname?
```
Jun 06 20:03:36 ubuntumitte systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
-- Boot b24a473d93464be284b0b128b56d2ec7 --
Aug 13 07:25:01 ubuntu2 microk8s.daemon-kubelite[885]: E0813 07:25:01.440127     885 kubelet.go:2466] "Error getting node" err="node \"ubuntu2\" not found"
```

I see that the node cannot register with the apiserver. Strangely I also see a third name "ubuntu-nuc".

**Comment by JoergSnn** [comment]
The hostname hasn't changed recently. Before a reset of microk8s it was called ubuntumitte. However, this was months ago.

ubuntu-nuc is a node that I have removed a couple of days ago. So it seems the removal was kind of incomplete.

**Comment by JoergSnn** [comment]
I set my system up from scratch.
