### ISSUE TITLE
VM disk size requested exceeds free space on host

### ISSUE THREAD

**Issue by doggy8088** [canonical/microk8s#3390]
#### Summary

`microk8s install` shows `VM disk size requested exceeds free space on host.` which should not display.

#### What Should Happen Instead?

The warning message should not display.

#### Reproduction Steps

I'm using Windows 10 with Hyper-V.

I have `C:\` and `G:\` which `G:\` only have 2GB RAM disk and `C:\` have enough disk space.

I'm at `G:\` and running the following command:

```sh
microk8s install
```

The screen shows:

```txt
VM disk size requested exceeds free space on host.
VM disk size requested exceeds free space on host.
Launched: microk8s-vm
```

I actually able to create VM without any problem. I think the `VM disk size requested exceeds free space on host.` might be misleading and it can be ignored.

Is it possible to change the checking logic a bit and not showing this message when my host do have enough disk space?

#### Introspection Report
N/A

#### Can you suggest a fix?
Check for Hyper-V default disk location to check disk space on that drive.

#### Are you interested in contributing with a fix?
no

**Comment by ktsakalozos** [comment]
Thank you for reporting this @doggy8088. This a bit more complicated as we use multipass to create the VMs. Regardless, this is a valid point.
