### ISSUE TITLE
calico-node-xxxxx "Hit error connecting to datastore: connection refused" in newly installed cluster

### ISSUE THREAD

**Issue by bobby-driver** [canonical/microk8s#3396]
I want to create a multi-node cluster, but I get this error setting up the first node.  Calico-node pods enter CrashLoopBackoff with the following logs:

`2022-08-18 18:38:06.172 [INFO][8] startup/startup.go 417: Hit error connecting to datastore - retry error=Get "https://10.152.183.1:443/api/v1/nodes/foo": dial tcp 10.152.183.1:443: connect: connection refused`

I do not recognize this IP or know where it's coming from.  I can curl kube-apiserver at the correct IP and receive a response.  

I've tried plugging the correct IP in to the kubelet and kube-apiserver args as described [here](https://github.com/canonical/microk8s/issues/3101#issuecomment-1113796609), but the pod continues to try 10.152.183 even after restarting.

I've also tried editing calico-kubeconfig but that file seems to get rewritten with 10.152.183.

I've also tried editing the IP environment variable in the calico-node daemonset to include the right IP, but this doesn't help.

Can anyone please advise?  I would like to post the inspection tarball here but that seems to include sensitive information.

It's worth mentioning that flannel was working fine, this problem is only with calico.  But I can't use flannel since I need HA.

**Comment by ktsakalozos** [comment]
Hi @bobby-driver, k8s service IP 10.152.183.1 of the API server. It is available for all services hosted in the cluster. Is it possible you are running in an environment with a proxy and you do not have the 10.152.183.x in the no_proxy settings?

**Comment by bobby-driver** [comment]
Hi @ktsakalozos.  Thank you for your response.

I edited my /etc/environment file to look like this:
`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
no_proxy=10.152.183.1/24
NO_PROXY=10.152.183.1/24`

Then I did `microk8s stop`, `microk8s start`, and deleted the calico-node-xxxxx pod, but the new pod that came up has the same error.

**Comment by ktsakalozos** [comment]
Maybe you need to restart the node for the /etc/environment to propagate everywhere.

Also make sure you have the pods CIDR in the no proxy list.

**Comment by bobby-driver** [comment]
Now I'm getting "no route to host"

`2022-08-19 15:04:19.458 [INFO][8] startup/startup.go 417: Hit error connecting to datastore - retry error=Get "https://10.152.183.1:443/api/v1/nodes/foo": dial tcp 10.152.183.1:443: connect: no route to host`

Here is the inspection report.  Thank you for your help

[inspection-report-20220819_150122.tar.gz](https://github.com/canonical/microk8s/files/9383188/inspection-report-20220819_150122.tar.gz)
