### ISSUE TITLE
microk8s not working on ARM64 Ubuntu 22.04 - microk8s status goes on infinitely

### ISSUE THREAD

**Issue by niksacdev** [canonical/microk8s#3412]
#### Summary
I am trying to install microk8s on a ARM64 Ubuntu 22.04 build. The snap installs without any errors but when I look at the microk8s services, it does not seem to be running. I ran the inspect command and it does not show any errors, can you please help

Report is attached.

~ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
~ microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/3712/inspection-report-20220829_131308.tar.gz

#### What Should Happen Instead?
microk8s status --wait-ready should return a running response

#### Reproduction Steps

1. install microk8s as described in the tutorial
2. run microk8s status --wait-ready - nothing happens and it keeps on waiting infinitely

#### Introspection Report
~ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
~ microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/3712/inspection-report-20220829_131308.tar.gz

**Comment by berkayoz** [comment]
Hey @niksacdev,

Sorry to hear that you are having trouble with your installation. Could you please attach the tarball generated by the `microk8s inspect` command? 

Thanks.

**Comment by benz0li** [comment]
I ran into this issue when I selected `microk8s` during installation of Ubuntu 22.04 LTS [Step: Featured Server Snaps].

Not selecting during Ubuntu installation but installing via `sudo snap install microk8s --classic --channel=1.25/stable` resolved it.
