### ISSUE TITLE
Portainer not working in microk8s  1.24 cluster on ubuntu 22.04

### ISSUE THREAD

**Issue by AllardKrings** [canonical/microk8s#3420]
#### Summary
I have enabled portainer on a three-node cluster. I can connect to portainer on the nodeport but when clicking on the cluster Portainer gives the error “unable to retrieve namespaces” . Clicking on menu-items like “Applications” does nothing.

#### What Should Happen Instead?
Portainer shoould show me the items in the cluster and let me manage them.

#### Reproduction Steps

I hav re-installed microk8s several times.
1: install microk8s on Ubuntu server 22.04 on three Rapberry Pi 4b with 8Gb
2: add nodes to form the cluster
3. enable dns, storage, etc.

I am 

[inspection-report-20220902_080607.tar.gz](https://github.com/canonical/microk8s/files/9479809/inspection-report-20220902_080607.tar.gz)

**Comment by ncresswell** [comment]
i replied on the Kubernetes forum.. 

Im unable to reproduce this.. please note that Portainer requires RBAC extension to be running in MicroK8s. 

See the steps i went through here: [https://discuss.kubernetes.io/t/portainer-namespace-issue/21153/5](https://discuss.kubernetes.io/t/portainer-namespace-issue/21153/5) if you can try to follow my steps and advise.
