### ISSUE TITLE
Unable to use multus with MicroK8s v1.25.0 revision 3834 - On ubuntu core

### ISSUE THREAD

**Issue by bhuvaneshne** [canonical/microk8s#3424]
#### Summary
Unable to enable multus - It asks to enable community even though community is already enabled

#### What Should Happen Instead?
Multus should have been enabled 

#### Reproduction Steps
Below steps were done on ubuntu core OS.
1. sudo snap install microk8s --channel=1.25-strict/stable --devmode
2. sudo microk8s enable community
3. sudo microk8s enable multus
^Last step will suggest to enable community even though community is already enabled in previous step

#### Introspection Report
[inspection-report-20220907_123713.tar.gz](https://github.com/canonical/microk8s/files/9506212/inspection-report-20220907_123713.tar.gz)

**Comment by bhuvaneshne** [comment]
```
administrator@ubuntu:~$ sudo microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    rbac                 # (core) Role-Based Access Control for authorisation
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated
  disabled:
    argocd               # (community) Argo CD is a declarative continuous deployment for Kubernetes.
    dashboard-ingress    # (community) Ingress definition for Kubernetes dashboard
    fluentd              # (community) Elasticsearch-Fluentd-Kibana logging and monitoring
    inaccel              # (community) Simplifying FPGA management in Kubernetes
    istio                # (community) Core Istio service mesh services
    jaeger               # (community) Kubernetes Jaeger operator with its simple config
    keda                 # (community) Kubernetes-based Event Driven Autoscaling
    knative              # (community) Knative Serverless and Event Driven Applications
    linkerd              # (community) Linkerd is a service mesh for Kubernetes and other frameworks
    openebs              # (community) OpenEBS is the open-source storage solution for Kubernetes
    openfaas             # (community) OpenFaaS serverless framework
    osm-edge             # (community) osm-edge is a lightweight SMI compatible service mesh for the edge-computing.
    portainer            # (community) Portainer UI for your Kubernetes cluster
    starboard            # (community) Kubernetes-native security toolkit
    traefik              # (community) traefik Ingress controller for external access
    cert-manager         # (core) Cloud native certificate management
    host-access          # (core) Allow Pods connecting to Host services smoothly
    ingress              # (core) Ingress controller for external access
    mayastor             # (core) OpenEBS MayaStor
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
administrator@ubuntu:~$ sudo microk8s version
MicroK8s v1.25.0 revision 3834
administrator@ubuntu:~$ sudo microk8s enable multus
Addon multus was not found in any repository
To use the community maintained flavor enable the respective repository:

    microk8s enable community

**Comment by bhuvaneshne** [comment]
Thanks @ktsakalozos.

I was successful in running microk8s + multus on ubuntu core using below installation commands (about couple of months ago). It needed exceptions in apparmor to get the workloads going though.

sudo snap install microk8s --channel=latest/edge/strict 

I was not able to reach to similar stage with more recent versions of latest/edge/strict.
Is there any repository where I can access the older latest/edge/strict snaps which were available in snap store?

Thanks,
Bhuvan

**Comment by bhuvaneshne** [comment]
Found old screenshot: This is the version that had worked for be earlier on ubuntu core - v1.23.4
![image](https://user-images.githubusercontent.com/97009526/188915585-c79c9a7e-f239-42fb-9792-e6bff74f4815.png)

**Comment by neoaggelos** [comment]
Hi @bhuvaneshne,

The breaking change was introduced in [#](https://github.com/canonical/microk8s-community-addons/pull/56/), see (https://github.com/canonical/microk8s-community-addons/pull/56/files#r896679074) for the relevant discussion.

The `mountPropagation: Bidirectional` is the problematic field there. While reviewing the change, I had success even with that setting removed, but I did not test it thoroughly to ensure there were not other regressions.

Can you help us test this? Please do the following on your `1.25-strict` installation:

```
sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
sudo microk8s enable multus
```

And let me know if you encounter any issues. If you don't, I would be happy to include this fix in the next bugfix release. For reference, here is the change: https://github.com/canonical/microk8s-community-addons/compare/main...feat/strict-fix-multus Thank you!

**Comment by bhuvaneshne** [comment]
> Hi @bhuvaneshne,
> 
> The breaking change was introduced in [#](https://github.com/canonical/microk8s-community-addons/pull/56/), see (https://github.com/canonical/microk8s-community-addons/pull/56/files#r896679074) for the relevant discussion.
> 
> The `mountPropagation: Bidirectional` is the problematic field there. While reviewing the change, I had success even with that setting removed, but I did not test it thoroughly to ensure there were not other regressions.
> 
> Can you help us test this? Please do the following on your `1.25-strict` installation:
> 
> ```
> sudo microk8s addons repo add community https://github.com/canonical/microk8s-community-addons --reference feat/strict-fix-multus
> sudo microk8s enable multus
> ```
> 
> And let me know if you encounter any issues. If you don't, I would be happy to include this fix in the next bugfix release. For reference, here is the change: [canonical/microk8s-community-addons@main...feat/strict-fix-multus](https://github.com/canonical/microk8s-community-addons/compare/main...feat/strict-fix-multus) Thank you!

Thanks @neoaggelos . Happy to test this. I will update shortly.

**Comment by bhuvaneshne** [comment]
Hi @neoaggelos : Confirming that your fix works. Tested on Ubuntu core OS.

<<Adding screenshot>>
![image](https://user-images.githubusercontent.com/97009526/189090158-cabf2912-dae6-41dc-aa14-8d63f6ba2464.png)

Thank you very much!

Regards,
Bhuvan

**Comment by nickbreen** [comment]
This is still necessary to apply as of microk8s      v1.32.4
