### ISSUE TITLE
Question: Can't login with grafana with Microk8s 1.25

### ISSUE THREAD

**Issue by morrowyn** [canonical/microk8s#3443]
Hi, 

I have enabled the following:   `microk8s.enable observability`

I have port forwarded the service:
`microk8s.kubectl port-forward -n observability service/kube-prom-stack-grafana --address 0.0.0.0 3000:80`

When I navigate to `http://localhost:3000`  and use username: `admin` and password: `admin` the website says: `invalid username or password.`

Any ideas what the default username/password could be?

Regards,

**Comment by morrowyn** [comment]
Nevermind: retrieved it using
`microk8s.kubectl get secrets/kube-prom-stack-grafana -n observability -o jsonpath="{.data.admin-password}" | base64 --decode;echo`

**Comment by ktsakalozos** [comment]
It should also be printed in the output on `microk8s enable prometheus`.
