### ISSUE TITLE
Fresh microk8s v1.24 installation have failing calico-kube-controller pod

### ISSUE THREAD

**Issue by tapanhalani** [canonical/microk8s#3447]
#### Summary
On a fresh microk8s-v1.24.4 installation on ubuntu-server-22.04, I see that calico-kube-controllers deployment's pod is failing from the start, causing it to be in "CrashloopBackOff" state. Here are the list of pods in the system:

```
NAMESPACE     NAME                                       READY   STATUS             RESTARTS        AGE
kube-system   calico-node-knlnn                          1/1     Running            2 (35m ago)     57m
ingress       nginx-ingress-microk8s-controller-clx2q    1/1     Running            0               27m
kube-system   calico-kube-controllers-64d4cb6ccb-26krj   0/1     CrashLoopBackOff   7 (4m38s ago)   15m
```

Here is the log-output from the calico-kube-controllers pod:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

#### What Should Happen Instead?
The calico, and all other kube-system pods should all be running properly

#### Reproduction Steps
1. Install Ubuntu-server 22.04 on VirtualBox Version 6.1.38 r153438 (Qt5.12.8)
2. While installing ubuntu-server, enable microk8s installation via cloudinit, and select stable/1.24 channel to install kubernetes v1.24.4
3. Once installed, login to the ubuntu server, and run `microk8s kubectl` commands to check k8s installation

#### Introspection Report

[inspection-report-20220914_112938.tar.gz](https://github.com/canonical/microk8s/files/9565888/inspection-report-20220914_112938.tar.gz)

**Comment by tapanhalani** [comment]
While reading calico + microk8s docs here https://projectcalico.docs.tigera.io/getting-started/kubernetes/microk8s, I can see that calico doesn't list ubuntu 22.04 as a supported/tested version for the installation.

This is in contrast with the documentation on the microk8s site: https://microk8s.io/docs/getting-started

Is this a potential issue?

**Comment by neoaggelos** [comment]
Hi @tapanhalani

> `standard_init_linux.go:228: exec user process caused: exec format error` 

This error message typically comes up when you are using binaries compiled for a different architecture. I presume this is an `amd64` machine? What kind of host is VirtualBox running on?

Also, can you try with other versions as well? e.g.

- `sudo snap remove microk8s --purge && sudo snap install microk8s --classic --channel 1.25`
- `sudo snap remove microk8s --purge && sudo snap install microk8s --classic --channel 1.23`
- `sudo snap remove microk8s --purge && sudo snap install microk8s --classic --channel 1.22`

What happens if you run other pods? e.g. `microk8s kubectl create deploy --image nginx --replicas 3`? Do the pods come up? Can you curl the nginx in the pods?

**Comment by neoaggelos** [comment]
I'm not able to reproduce this on a clean ubuntu 22.04 machine:

```
root@u1:~# snap list microk8s
Name      Version  Rev   Tracking  Publisher   Notes
microk8s  v1.24.4  3719  -         canonical✓  classic

root@u1:~# uname -a
Linux u1 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

root@u1:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@u1:~# k get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-node-c5pg5                          1/1     Running   0          7m34s
kube-system   calico-kube-controllers-5b688b5b84-4fqvr   1/1     Running   0          7m34s

root@u1:~# k get node
NAME   STATUS   ROLES    AGE     VERSION
u1     Ready    <none>   8m40s   v1.24.4-2+2f38f78fa07274

```

**Comment by dnewsholme** [comment]
I ran into this after upgraded to 22.04.1 LTS. My microk8s snap also upgraded to 1.25, when trying to rollback to 1.24 I got this issue because snap doesn't clear up the calico virtual network devices on removal.

**Comment by tapanhalani** [comment]
@neoaggelos Thank you very much for a very prompt reply :)

Here I show my virtualbox host setup:

```bash
tapan@microk8s-test-vm:~$ uname -a
Linux microk8s-test-vm 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

tapan@microk8s-test-vm:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
``` 
So the architecture is amd64 only. The only thing is, contrary to using snap command to install microk8s after the system setup, I installed it while setting up ubuntu OS on virtualbox using GUI (when you can configure what software snaps will be installed e.g. docker, powershell, microk8s etc).

I tried doing this: 

```
sudo snap remove microk8s --purge && sudo snap install microk8s --classic --channel 1.24
```

The new installation is working perfectly, including the creation of nginx deployment and pods:
```
tapan@microk8s-test-vm:~$ microk8s kubectl create deploy nginx --image nginx --replicas 3
deployment.apps/nginx created
tapan@microk8s-test-vm:~$ microk8s kubectl get pods -A -w
NAMESPACE     NAME                                       READY   STATUS              RESTARTS   AGE
kube-system   calico-node-7grc6                          1/1     Running             0          58m
kube-system   calico-kube-controllers-5fd8fd5f55-gc2dj   1/1     Running             0          58m
default       nginx-8f458dc5b-5gc2r                      0/1     ContainerCreating   0          15s
default       nginx-8f458dc5b-dscpd                      0/1     ContainerCreating   0          15s
default       nginx-8f458dc5b-nsbl6                      0/1     ContainerCreating   0          15s
default       nginx-8f458dc5b-5gc2r                      1/1     Running             0          22s
default       nginx-8f458dc5b-dscpd                      1/1     Running             0          25s
default       nginx-8f458dc5b-nsbl6                      1/1     Running             0          27s
```

**Comment by tapanhalani** [comment]
I have successfully tried installing microk8s multiple times with multiple fresh virtualbox machines. And i cannot reproduce this issue again.

Closing this issue now. Thank you @neoaggelos for attending to this.
