### ISSUE TITLE
GPU Support broken in 1.25

### ISSUE THREAD

**Issue by dkibble** [canonical/microk8s#3452]
#### Summary
NVidia gpu support is no longer working in microk8s 1.25 when using microk8s enable gpu. The gpu-operator has errors relating to the node.k8s.io/v1beta1 api and no further gpu related pods are launched. microK8s 1.24 works perfectly on the same machine.

#### What Should Happen Instead?
NVidia GPU support should function in the same way as microk8s 1.24

#### Reproduction Steps
1. Install microk8s 1.25
2. Enable GPU support with microk8s enable gpu
3. Observe the logs for the gpu-operator pod

#### Can you suggest a fix?
The node.k8s.io/v1beta1 api was removed in Kubernetes 1.25 see here:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#runtimeclass-v125
It should be replaced with node.k8s.io/v1 API

#### Are you interested in contributing with a fix?
Happy to test a fix

**Comment by ktsakalozos** [comment]
Hi @dkibble, thank you for pointing this out. The nvidia operator is not yet ready for k8s v1.25 because of the API issue you are reporting. The team maintaining the operator is aware and a patch is already ready available [1, 2]. The next release of the gpu operator should address the problem. As soon as the new gpu operator is released we will update the gpu addon to include it.

As k8s 1.25 is relatively new it is somewhat expected that parts of the ecosystem are not yet up to date. We appreciate your understanding.

[1] https://github.com/NVIDIA/gpu-operator/issues/401#issuecomment-1245932303
[2] https://github.com/NVIDIA/gpu-operator/commit/5e73a0b291c8063918a3de9ca918d629e42bd23e

**Comment by dkibble** [comment]
Hi Konstantinos

That's great to hear, I really look forward to the update.

Thanks to you and the team for such a great product and support.

Dave

On 17/09/2022 18:22, Konstantinos Tsakalozos wrote:

> Hi @dkibble [1], thank you for pointing this out. The nvidia operator 
> is not yet ready for k8s v1.25 because of the API issue you are 
> reporting. The team maintaining the operator is aware and a patch is 
> already ready available [1, 2]. The next release of the gpu operator 
> should address the problem. As soon as the new gpu operator is released 
> we will update the gpu addon to include it.
> 
> As k8s 1.25 is relatively new it is somewhat expected that parts of the 
> ecosystem are not yet up to date. We appreciate your understanding.
> 
> [1] NVIDIA/gpu-operator#401 (comment) [2]
> [2] ***@***.*** [3]
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/dkibble
[2] 
https://github.com/NVIDIA/gpu-operator/issues/401#issuecomment-1245932303
[3] 
https://github.com/NVIDIA/gpu-operator/commit/5e73a0b291c8063918a3de9ca918d629e42bd23e
[4] 
https://github.com/canonical/microk8s/issues/3452#issuecomment-1250109223
[5]

**Comment by neoaggelos** [comment]
Hi @dkibble

GPU operator just released [v22.9.0](https://github.com/NVIDIA/gpu-operator/releases/tag/v22.9.0) which fixes support for Kubernetes 1.25.

You can try it out already with

```
microk8s enable gpu --version v22.9.0
```

There is also a PR to install v22.9.0 by default when enabling the GPU addon https://github.com/canonical/microk8s-core-addons/pull/109, which will be released soon after CI passes.

**Comment by dkibble** [comment]
Hi AngelosThank you for letting me know. Will give this a go ASAP.DaveSent from my mobile, so please excuse typos 
-------- Original message --------From: Angelos Kolaitis ***@***.***> Date: 04/10/2022  07:29  (GMT+00:00) To: canonical/microk8s ***@***.***> Cc: dkibble ***@***.***>, Mention ***@***.***> Subject: Re: [canonical/microk8s] GPU Support broken in 1.25 (Issue #3452) 
Hi @dkibble
GPU operator just released v22.9.0 which fixes support for Kubernetes 1.25.
You can try it out already with
microk8s enable gpu --version v22.9.0

There is also a PR to install v22.9.0 by default when enabling the GPU addon canonical/microk8s-core-addons#109, which will be released soon after CI passes.
