### ISSUE TITLE
Control plane initializer node reports kubelet "stopped posting node status" and marked as not ready.

### ISSUE THREAD

**Issue by eddieparker** [canonical/microk8s#3459]
I have a set of VMs I've spun up to test out an ansible-playbook that generates a kubernetes cluster.  The main initializer control node always ends up NotReady complaining that kubelet stopped posting node status and I'm unsure how to debug.

Here's the output of microk8s.kubectl get node (k is an alias):

```
eddie@k8s-control-vm-01:~$ k get node
NAME                STATUS     ROLES    AGE   VERSION
k8s-control-vm-01   NotReady   <none>   74d   v1.23.6-2+2a84a218e3cd52
k8s-control-vm-02   Ready      <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-control-vm-03   Ready      <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-worker-vm-01    Ready      <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-worker-vm-02    Ready      <none>   74d   v1.23.10-2+b9088462d1df8c
```

k describe node k8s-control-vm-01 yields this excerpt:

```
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----                 ------    -----------------                 ------------------                ------              -------
  NetworkUnavailable   False     Tue, 12 Jul 2022 02:44:31 +0000   Tue, 12 Jul 2022 02:44:31 +0000   CalicoIsUp          Calico is running on this node
  MemoryPressure       Unknown   Tue, 12 Jul 2022 02:43:35 +0000   Tue, 12 Jul 2022 02:47:58 +0000   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure         Unknown   Tue, 12 Jul 2022 02:43:35 +0000   Tue, 12 Jul 2022 02:47:58 +0000   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure          Unknown   Tue, 12 Jul 2022 02:43:35 +0000   Tue, 12 Jul 2022 02:47:58 +0000   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready                Unknown   Tue, 12 Jul 2022 02:43:35 +0000   Tue, 12 Jul 2022 02:47:58 +0000   NodeStatusUnknown   Kubelet stopped posting node status.
```

I've attached the output of microk8s inspect.

[inspection-report-20220924_090230.tar.gz](https://github.com/canonical/microk8s/files/9638325/inspection-report-20220924_090230.tar.gz)

The stdout from the tool indicates that kubelite is running, but not kubelet.  I'm not sure what to do here - advice appreciated.

**Comment by neoaggelos** [comment]
Hi @eddieparker

I see that `k8s-control-vm-01` is running version 1.23.6, whereas the other nodes are at 1.23.10. In the logs of your node I see

```
Sep 24 08:51:58 k8s-control-vm-01 microk8s.daemon-kubelite[18309]: E0924 08:51:58.060033   18309 server.go:307] "Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
```

And, looking at 1.23 release notes for Kubernetes I see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#container-runtime-interface-cri-v1-is-default, which looks relevant and I would imagine could be playing a part in the issue you are seeing.

Is it possible to upgrade so that all your nodes are at the same version and see if the issue persists? Thank you

**Comment by eddieparker** [comment]
Thank you for the reply @neoaggelos!  Can't believe I didn't notice that discrepancy in the `get nodes` output.

I'll try to upgrade the node.  Right now I'm struggling because the only docs on upgrading say I should be able to do:
```
eddie@k8s-control-vm-01:~$ sudo snap refresh microk8s --channel=1.23/stable
snap "microk8s" has no updates available
```

But as you can see it says there are no updates. Going to keep digging to see if there's a way to upgrade - if you have any quick answers that'd be appreciated otherwise I'll reply when I sleuth it out.

**Comment by neoaggelos** [comment]
If you are feeling lucky, you could try `sudo snap refresh microk8s --channel=1.23/edge`

**Comment by eddieparker** [comment]
I did the following and it seems to have installed:

```
eddie@k8s-control-vm-01:~$ sudo snap revert microk8s
microk8s reverted to v1.23.9
eddie@k8s-control-vm-01:~$ sudo snap refresh microk8s --channel=1.23/stable
microk8s (1.23/stable) v1.23.10 from Canonical✓ refreshed
```

But get nodes still reports it at 1.23.6-2:

```
eddie@k8s-control-vm-01:/usr/local/bin$ k get nodes
NAME                STATUS                        ROLES    AGE   VERSION
k8s-control-vm-02   Ready                         <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-control-vm-03   Ready                         <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-control-vm-01   NotReady,SchedulingDisabled   <none>   74d   v1.23.6-2+2a84a218e3cd52
k8s-worker-vm-01    Ready                         <none>   74d   v1.23.10-2+b9088462d1df8c
k8s-worker-vm-02    Ready                         <none>   74d   v1.23.10-2+b9088462d1df8c
```

I'm going to reboot it and then give it an hour in case somehow it's percolating the changes...?  Thanks for your help so far.

**Comment by neoaggelos** [comment]
Hi @eddieparker any update on this? Was the issue resolved?

**Comment by eddieparker** [comment]
I couldn't get it working without destroying the vms and recreating it sadly.  Thereafter I had troubles getting kubelet to stop crashing, so I've switched to kubeadm and it seems to work now!
