### ISSUE TITLE
Microk8s stopped running with error kubelet nodes not sync and unable to register node

### ISSUE THREAD

**Issue by RamjiRaju** [canonical/microk8s#3460]
Hi Team,

we are using single node Microk8s, it started running and all of sudden it stopped.

The node went to Notready state

we tried to stop and start, even than we are unable to start the MicroK8s

we have taken inspect logs, there we see below errors

**API-Server log**

[inspection-report-20220923_112828.tar.gz](https://github.com/canonical/microk8s/files/9642848/inspection-report-20220923_112828.tar.gz)
 Sep 22 16:49:43 phdc2sanoramp1.fnzch.net microk8s.daemon-apiserver[674]: E0922 16:49:43.799165     674 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token

**Kubelet log**

Sep 23 01:03:15  microk8s.daemon-kubelet[684]: I0923 01:03:15.541975     684 kubelet.go:449] kubelet nodes not sync
Sep 23 01:03:15 microk8s.daemon-kubelet[684]: E0923 01:03:15.904279     684 controller.go:136] failed to ensure node lease exists, will retry in 7s, error: Unauthorized
Sep 23 01:03:17  microk8s.daemon-kubelet[684]: I0923 01:03:17.324510     684 kubelet_node_status.go:71] Attempting to register node xxxxxxxxxxxxxxxxx.xxx.net
Sep 23 01:03:17 microk8s.daemon-kubelet[684]: E0923 01:03:17.325518     684 kubelet_node_status.go:93] Unable to register node "xxxxxxxxxxxxxxxxx.xxx.net" with API server: Unauthorized

root@phdc2sanoramp1:/home/gateway-admin# snap list
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.49.1  10908  latest/stable  canonical✓  core
microk8s  v1.19.8    2060   1.19/stable    canonical✓  classic

root@phdc2sanoramp1:/home/gateway-admin#

root@phdc2sanoramp1:/home/gateway-admin# microk8s.kubectl get nodes
NAME                       STATUS     ROLES    AGE    VERSION
xxxxxxxxxxxxxxxxx.xxx.net   NotReady   <none>   150d   v1.19.8-34+811e9feeade1d3

Please find the attached inspect logs for reference.

Please let us know what is the reason for why Microk8s going into this state, Thanks in advance

**Comment by ktsakalozos** [comment]
Hi @RamjiRaju, how long have you been running this deployment for? Could you check the expiration date of the certificates with:
```
sudo openssl 'x509' '-enddate' '-noout', '-in' '/var/snap/microk8s/current/certs/ca.crt'
# and
sudo openssl 'x509' '-enddate' '-noout', '-in' '/var/snap/microk8s/current/certs/kubelet.crt'
``` 

The v1.19 has gone EOL, would you consider upgrading to a newer version (1.25 is the latest)?
