### ISSUE TITLE
Pods on one node cannot reach pods on other nodes.

### ISSUE THREAD

**Issue by LauJosefsen** [canonical/microk8s#3461]
Hi.

I am experiencing the same issue as https://github.com/canonical/microk8s/issues/3043 , however I believe my hostnames already comply with Kubernetes standards, thus the solution that worked for that issues does not work for us.

Our setup is a 3 node cluster. Two of the nodes work fine, where pods on these two nodes can reach eachother, however pods from the third node cannot reach pods on the first two nodes, and vice versa.

I have been trying different versions of microk8s, reinstalling multiple times, but nothing has worked so far. I don't see any error logs in calico pods.

Host OS is ubuntu 20.04.5

[inspection-report-20220926_073507.tar.gz](https://github.com/canonical/microk8s/files/9644845/inspection-report-20220926_073507.tar.gz)

**Comment by balchua** [comment]
I have some few questions
* Can a pod access the other pod using the IP address instead of the service name?
* do you setup proxy settings on the node?

**Comment by LauJosefsen** [comment]
No, the IP of the pods cannot be reached, a traceroute to the IP of the problematic pods, seems to go to the hosts default gateway before being dropped.

I do not use any proxy setup. 

I suspect that the calico-node pod on the problematic node is having trouble reaching calico-master, however it does not mention anything of this kind in the logs.

**Comment by LauJosefsen** [comment]
I have tried to follow the debugging mentioned here
https://projectcalico.docs.tigera.io/getting-started/kubernetes/hardway/test-networking
Again pods on node 1 and 2 can communicate fine, but communication between pod 1 and 3, 2 and 3 is not working.

By running ```ip route get <ip>``` i can see that both the working links and not working links all try to resolve the ip using a local address (10.1.38.72 via 169.254.1.1 dev eth0  src 10.1.177.131)

I assume the problematic node may have VXLAN issues, I just can't find any information anywhere in either microk8s or calico documentation on how to approach this problem, as there is no indication of any issues in calico node or manager logs. Any hints are appreciated. 

I have tried opening the firewall on my physical machines to allow all UDP (I believe VXLAN is UDP) and TCP on all ports to debug this problem, but did not help.

**Comment by balchua** [comment]
I was just looking at the logs you provided.  I see this in the calico config.

``` json
{
                                        "name": "IP_AUTODETECTION_METHOD",
                                        "value": "can-reach=130.225.39.94"
                                    },
```
It looks like it is attached to a different network interface?

**Comment by LauJosefsen** [comment]
That IP is indeed the IP another machine can be reached on.

However, as is not included in the tar ball, the `can-reach<external-ip>` is used on all the nodes, and node 1-2 communicate fine.

It sounds like you expect this value to be something else? I have not modified the YAMLs myself (i assume its the one located at /var/snap/microk8s/current/args/cni-network/cni.yaml )

Also I am not sure this setting is even used when BGP is disabled as per default in microk8s? But I could be wrong.

**Comment by balchua** [comment]
The default ip detection mode is `first-found`. So i was just wondering if this is set explicitly.
You also mentioned that the other 2 nodes also has that set and they are able to communicate.
I assume you also disabled the host firewall on that node 3.

**Comment by LauJosefsen** [comment]
First of all, thanks a lot for taking the time to look into what is properly a noob-mistake after all.

I remember going around each node and adding all the hostnames to `/etc/hosts`.

The 3-node cluster is actually only part of the story. Originally, we had 5 nodes, ais-pg-db-1 through ais-pg-db-5. They were all created at the same time, and everything worked on these. We then down the road found out we needed a compute heavy node, and thus the problems began. To debug the system is removed 2 of the original nodes to try to isolate what was wrong, which I couldn't figure out and then opened this issue.

I have since creating this issue gone back to the 5 original nodes but am still unable to connect the 6th node. We have tried with multiple different machines as well. I tried adding the hostnames to all machines as you suggested a while back, and restarted everything, but it did not help sadly. I can attach a new tarball if it helps?

**Comment by balchua** [comment]
Yes please if you have a new tarball.  I hope the new logs can reveal something.
Just to reconfirm, this new node is successfully joined to the cluster, but it is unable to establish pod to pod communication between this new node and the other nodes 
Thanks 🙏

**Comment by LauJosefsen** [comment]
Hi. Yes, the nodes seem to be communicating perfectly fine, besides pod->pod comms.

Currently our cluster looks like this
```NAME             STATUS   ROLES    AGE     VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
ais-pg-test      Ready    <none>   19h     v1.25.0   130.225.39.75    <none>        Ubuntu 20.04.5 LTS   5.4.0-126-generic   containerd://1.6.6
ais-etl-worker   Ready    <none>   23h     v1.25.0   130.225.39.16    <none>        Ubuntu 20.04.5 LTS   5.4.0-126-generic   containerd://1.6.6
ais-pg-db-5      Ready    <none>   2d19h   v1.25.0   130.225.39.249   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic    containerd://1.6.6
ais-pg-db-4      Ready    <none>   2d19h   v1.25.0   130.225.39.166   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic    containerd://1.6.6
ais-pg-db-3      Ready    <none>   2d19h   v1.25.0   130.225.39.242   <none>        Ubuntu 20.04.1 LTS   5.4.0-125-generic   containerd://1.6.6
ais-pg-db-2      Ready    <none>   2d19h   v1.25.0   130.225.39.121   <none>        Ubuntu 20.04.1 LTS   5.4.0-125-generic   containerd://1.6.6
ais-pg-db-1      Ready    <none>   2d20h   v1.25.0   130.225.39.200   <none>        Ubuntu 20.04.1 LTS   5.4.0-126-generic   containerd://1.6.6```

ais-pg-db-1 through ais-pg-db-5 can communicate between pods on different nodes, however pods places on ais-etl-worker and ais-etl-test cannot reach any pods outside their own node and vice versa.

I have attached a tar ball with an inspection from one of the working nodes, and one from one of the "not working" nodes.

Furthermore this is the entries in all nodes for /etc/hosts:
```
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

130.225.39.200 ais-pg-db-1
130.225.39.121 ais-pg-db-2
130.225.39.242 ais-pg-db-3
130.225.39.166 ais-pg-db-4
130.225.39.249 ais-pg-db-5
130.225.39.16 ais-etl-worker
130.225.39.75 ais-pg-test
```

[ais-pg-db-1.tar.gz](https://github.com/canonical/microk8s/files/9671842/ais-pg-db-1.tar.gz)
[ais-etl-worker.tar.gz](https://github.com/canonical/microk8s/files/9671841/ais-etl-worker.tar.gz)

You will find if you are looking for it, errors such as `dial tcp: lookup ais-pg-test on 127.0.0.53:53: server misbehaving` from yesterday before i updated the /etc/hosts entry. :)

**Comment by LauJosefsen** [comment]
After reconfirming my firewall settings on my cloud provider, I saw that the first 5 machines only allowed ingress from the first 5 machines..

It is still unclear to me what port VXLAN requires to be open for UDP trafic as per the [documentation](https://microk8s.io/docs/services-and-ports), but for now it has started working by opening all ports.

**Comment by balchua** [comment]
These are the ports required by calico.
https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements
Vxlan port is `4789`

**Comment by neoaggelos** [comment]
Hi @LauJosefsen, thanks for brining this up and glad the issue was resolved. I've updated the documentation to include the 4789/udp calico port. Thanks a lot!
