### ISSUE TITLE
microk8s service stop working on external devices on the same network

### ISSUE THREAD

**Issue by SpringFlutter** [canonical/microk8s#3462]
#### Summary

I have a microservice which works perfectly in my localhost. I'm able to access to it from my localhost and others external machines on the same network. However, after around 15 minutes it stopped working and I'm not able to access to the service from just external machines. (In local host it works fine, always can access to the service). Moreover, if i restart my localhost the service again is able to the external machines but just for 15 minutes.

#### What Should Happen Instead?

I should be able to access to the service from external devices always I need (as in my localhost that never stopped working) and not just for 15 minutes. 

#### Reproduction Steps

1. Install microk8s 1.24/stable
2. Enable dns and metrics-server
3. Access to the service through http:my_ip_localhost:port 
4. reboot 

#### Introspection Report

[inspection-report-20220926_110707.tar.gz](https://github.com/canonical/microk8s/files/9647928/inspection-report-20220926_110707.tar.gz)

**Comment by balchua** [comment]
How do you access the service from outside the cluster?  What are you using, ingress? Or port forwarding? Or node port?

**Comment by SpringFlutter** [comment]
I'm using Node Port to access the service. The connection is refused when try it with Postman; moreover I notice that I can not access to the localhost via ssh after that 15 minutes also.

**Comment by SpringFlutter** [comment]
Hi, thanks for your answer. Im running microk8s in a VM with CentOs. I suspect it is a network problem because today I notice that If I just restart the network I have the same problem.

**Comment by balchua** [comment]
Yeah i guess it has something to do with the host rather than microk8s.
