### ISSUE TITLE
cluster refuse to work after auto upgrade to v1.22.14-3+3b9af18c361d7b

### ISSUE THREAD

**Issue by golgotow** [canonical/microk8s#3483]
#### Summary
Cluster stop to respond properly ( looks like schedule not working ? ) after auto upgrade to v1.22.14-3+3b9af18c361d7b
 via snap ( we did not disable auto upgrade, this for now work ok as cluster was installed in early 1.22 version)

kubectl -n kube-system get pods
NAME                                       READY   STATUS        RESTARTS         AGE
calico-node-lzxjd                          0/1     Terminating   861 (123m ago)   7d2h
calico-kube-controllers-775d6c6d65-rm2vn   0/1     Terminating   8                7d2h
metrics-server-7b7db5984b-dp7t9            0/1     Terminating   0                35d
coredns-7f9c69c78c-bqkm2                   0/1     Terminating   1                35d

kubectl get nodes
NAME     STATUS   ROLES    AGE    VERSION
rpi8g1   Ready    <none>   147d   v1.22.14-3+3b9af18c361d7b
rpi8g2   Ready    <none>   147d   v1.22.14-3+3b9af18c361d7b
rpi8g3   Ready    <none>   147d   v1.22.14-3+3b9af18c361d7b

#### What Should Happen Instead?
cluster shall work normally

#### Reproduction Steps
auto upgrade enable in snap
upgrade was done from previous version of v1.22.14-3+3b9af18c361d7b
no idea how to reproduce it now

#### Introspection Report
[inspection-report-20221001_104459.tar.gz](https://github.com/canonical/microk8s/files/9689934/inspection-report-20221001_104459.tar.gz)

#### Can you suggest a fix?
no :( 

#### Are you interested in contributing with a fix?
yes , but not idea how

**Comment by balchua** [comment]
Can you check if your certs are still valid?

``` shell
sudo openssl 'x509' '-enddate' '-noout', '-in' '/var/snap/microk8s/current/certs/ca.crt'
# and
sudo openssl 'x509' '-enddate' '-noout', '-in' '/var/snap/microk8s/current/certs/kubelet.crt'
```

**Comment by golgotow** [comment]
Hi,

yes cert was still valid, anyway our team dropped microk8s and reinstalled it to another solutions so no more logs I have ...

Thank you for help

**Comment by ktsakalozos** [comment]
@golgotow in the logs you send us there are a number entries showing how long it takes for the k8s datastore to handle a transaction:
```
Oct 01 10:36:17 rpi8g1 microk8s.daemon-kubelite[144539]: Trace[1628345170]: ---"Transaction prepared" 9455ms (10:36:11.649)
Oct 01 10:36:17 rpi8g1 microk8s.daemon-kubelite[144539]: Trace[1628345170]: [14.966565878s] [14.966565878s] END
```

In this particular case it took 9.45 seconds. Anything more than 0.5 seconds is considered problematic and therefore k8s logs it.

Here is some suggestions you could consider:
- upgrade the hardware used (at least for the control plane nodes)
- do not host disk I/O intensive workloads on the same nodes as the k8s control plane
- use an external etcd
- upgrade to a newer k8s version
