### ISSUE TITLE
Hostpath-storage doesn't set permisssions correctly

### ISSUE THREAD

**Issue by psmit** [canonical/microk8s#3490]
#### Summary

On a single-node microk8s cluster, with a custom hostpath, the permissions for persistent volume claims are not set correctly, my pods are not having any rights to write in those folders.

#### What Should Happen Instead?

Creating a hostpath pvc should have the right permissions.

#### Reproduction Steps

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2022-09-28T19:25:54Z"
  name: hdd-hostpath
  resourceVersion: "52118"
  uid: 253b8fce-e76b-4851-8b04-0fc828ba3ad4
parameters:
  pvDir: /data/k8s-pvc
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

```

2. Create pod with PVC

3. No rights inside pod

#### Can you suggest a fix?

Unfortunately, I can't see how this is supposed to work, so I can't contribute a fix either.

**Comment by neoaggelos** [comment]
Hi @psmit, quick question, which MicroK8s version are you using? It would help with figuring out the problem. Thank you!

**Comment by neoaggelos** [comment]
Hi @psmit, we have released a fix that should resolve your issue, can you try updating the hostpath provisioner to 1.4.1?

```
microk8s kubectl set image deploy/hostpath-provisioner hostpath-provisioner=cdkbot/hostpath-provisioner:1.4.1 -n kube-system
```

Volumes should then be created with proper permissions

**Comment by psmit** [comment]
My apologies for omitting the version in the first place, I'm running 1.25.

Your fix works great!
