### ISSUE TITLE
Unable to import some Docker images to MicroK8s image cache via tar stream

### ISSUE THREAD

**Issue by ashenwgt** [canonical/microk8s#3493]
#### Summary

When trying to import a set of locally-built Docker images to the MicroK8s image cache, some images turn into `text/html` type, the size becomes too small (in KiB), and the platform becomes `-` in the output. The pods based on such erroneous images show an `ImagePullBackOff` error.

#### What Should Happen Instead?

If the image is healthy, its type should be something like `application/vnd.docker.distribution.manifest.v2+json`, the size should be almost similar to the original Docker image size, and the platform should be something like `linux/amd64`.

#### Reproduction Steps

IMPORTANT: Unfortunately, this happens **rarely** and the affected images are also changing **randomly**. When the issue is present, what happens is, some images stay healthy and a few go into this erroneous mode. 

1. Export Docker images to MicroK8s.
```
docker save $image > /tmp/$image.tar
microk8s ctr image rm "$image" || true
microk8s ctr image import /tmp/$image.tar
```

2. List MicroK8s image types & sizes.
```
microk8s ctr image list

// SAMPLE OUTPUT
REF                                                                                                         
TYPE                                                      
DIGEST                                                                  
SIZE      
PLATFORMS                                                                  
LABELS

// HEALTHY
docker.io/aaaaaa/xxxxxx:local                                                                
application/vnd.docker.distribution.manifest.v2+json      
sha256:xxxxxxxxxxxxxxxxxxxxx 
671.5 MiB 
linux/amd64                                                                
io.cri-containerd.image=managed

// ERRONEOUS
docker.io/aaaaaa/yyyyyy:local                                                                
text/html                                                 
sha256:yyyyyyyyyyyyyyyyyyyy 
229.9 KiB 
-                                                                          
io.cri-containerd.image=managed

...
```

#### Introspection Report

N/A

#### Can you suggest a fix?

N/A

#### Are you interested in contributing with a fix?

N/A

**Comment by neoaggelos** [comment]
We have seen that containerd sometimes has issues with importing images that come from `docker save`.

instead, what has been found to consistently work is:

```
microk8s ctr image pull docker.io/some/image:tag
microk8s ctr content fetch --all-platforms docker.io/some/image:tag
microk8s ctr image export file.tar docker.io/some/image:tag
```

and then import in a different instance with:

```
microk8s ctr image import file.tar
```

Can you see whether this solution solves your issue?

**Comment by ashenwgt** [comment]
Many thanks for your explanation @neoaggelos . 

Actually, all our environments have been working healthily for the past ~5 days - so I have no way to try this right now. However, if I come across this issue again in the future, I will apply the above approach and provide an update here.
