### ISSUE TITLE
microk8s disable - "is already disabled"

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [canonical/microk8s#3496]
#### Summary
When attempting to disable metallb, microk8s reports it as already being disabled. (It is not disabled, but, is enabled.)

#### What Should Happen Instead?
microk8s should properly detect that it is indeed, enabled, and disabled it.

##### Step 1. Setup environment.

- Remove any snapshots which may, or may not exist... This fixes another bug I found....
- tldr; even after microk8s reset, snap remove microk8s, snap add microk8s, I encountered an error where I could not join nodes to a cluster, because the node already existed. However, removing the snapshots from inside of this directory, did resolve that issue... and whatever data was not being cleaned up.
rm /var/lib/snapd/snapshots/*
snap install microk8s --classic
microk8s enable metallb:10.0.0.1/20

##### Delete the speaker role from metallb.

- Delete the "Speaker" from metallb. Since Microk8s uses calico by default, it doesn't play well with speaker.
- https://metallb.org/configuration/calico/
kubectl delete daemonset -n metallb-system speaker

##### Lastly- attempt to disable metal lb.

```bash
root@kube03:/var/lib# microk8s disable metallb
Infer repository core for addon metallb
Addon core/metallb is already disabled
root@kube03:/var/lib# microk8s enable metallb
Infer repository core for addon metallb
MetalLB already enabled.
root@kube03:/var/lib# microk8s disable metallb
Infer repository core for addon metallb
Addon core/metallb is already disabled
root@kube03:/var/lib# microk8s enable metallb
Infer repository core for addon metallb
MetalLB already enabled.
root@kube03:/var/lib#
```

Now- ponder the meaning of life.

#### Introspection Report
[inspection-report-20221007_174346.tar.gz](https://github.com/canonical/microk8s/files/9736071/inspection-report-20221007_174346.tar.gz)

#### Can you suggest a fix?

```
kubectl delete namespace metallb-system
microk8s enable metallb:10.0.0.1/20
```
is extremely effective at cleaning up metallb, and then properly installing metallb.

#### Are you interested in contributing with a fix?
I would love to, however, I am unaware of the inner workings. 

I will note, this is not a crucial issue. this is not an impacting issue. I am reporting this because this command obviously does not work as expected.... since it reports the addon as both installed, and disabled at the same time.

The best fix I could recommend based on my knowledge, is to make a schrodinger's cat reference.

**Comment by ktsakalozos** [comment]
@XtremeOwnageDotCom when you do a `microk8s status` or when you need to enable an addon we do a quick check to see if the addon is enabled or not. In the case of metallb this check is the existance of the speaker pod [1]. Disabling the addon is actually deleting the namespace you mention. It is however possible that while the speaker pods get removed the addon reports as enabled. A `microk8s kubectl get all -A` should be enough to collapse the addon's wave function ;) .

[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons.yaml#L113 
[2] https://github.com/canonical/microk8s-core-addons/blob/main/addons/metallb/disable#L13

**Comment by XtremeOwnageDotCom** [comment]
@ktsakalozos  that explanation would make perfect sense in this case. 

Might be better to update the check to look to determine if `deployment.apps/controller` exists, as the official metallb documentation even has directions to delete the speaker pods, when used in conjunction with calico.
