### ISSUE TITLE
[microk8s 1.25/1.26] Service snap.microk8s.daemon-apiserver-proxy is not running in cluster setup

### ISSUE THREAD

**Issue by adh8885** [canonical/microk8s#3497]
#### Summary
Service snap.microk8s.daemon-apiserver-proxy is not running in cluster setup, journalctl reported “Not a worker node, exiting”

#### What Should Happen Instead?
snap.microk8s.daemon-apiserver-proxy should be not included in first node setup. 

#### Reproduction Steps

1. sudo snap install microk8s --classic --channel=1.18/stable
2. sudo snap refresh microk8s --classic --channel=1.26/stable
3. microk8s start
4. microk8s status
5. microk8s inspect

#### Introspection Report
[]
[inspection-report-20221010_141814.tar.gz](https://github.com/canonical/microk8s/files/9743683/inspection-report-20221010_141814.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @adh8885 there are a couple of things we need to make clear.

As I understand you want to upgrade your 1.18 cluster, correct? Upgrading one such cluster should be done progressively going through each release track. This means you need to refresh from 1.18 to 1.19, then to 1.20, then to 1.21 etc. The last stable release is the 1.25 so you should stop there, for 1.26 we only have pre-stable releases from upstream so do not go there yet.

In recent releases all k8s services have been consolidated to a single service for efficiency reasons. So the logs of the kube-proxy service is now in the `snap.microk8s.daemon-kubelite` one.
