### ISSUE TITLE
Can't restart kubeflow pods after remote host restarted. 

### ISSUE THREAD

**Issue by Daard** [canonical/microk8s#3503]
#### Summary
After reboot all pods are in Unknown or Init:Unknown state. I tried get juju status / juju models / juju clouds, but all them are just hanging out and do not show anything. 

#### What Should Happen Instead?
I should get all kubeflow pods ready to use and be able to see juju status results. 

#### Reproduction Steps
I followed this guide to deploy Kubeflow : https://charmhub.io/topics/kubeflow/quickstart.
Everything worked fine until reboot. 

#### Introspection Report
[inspection-report-20200601_164808.tar.gz](https://github.com/canonical/microk8s/files/9765311/inspection-report-20200601_164808.tar.gz)

**Comment by ca-scribner** [comment]
Hey @Daard, sorry you're hitting trouble.

Is the inspection report for the right cluster?  I only looked quickly but didn't see anything kubeflow related.  I do see many things are in a bad state though like you mentioned.

**Comment by Daard** [comment]
Hi @ca-scribner. 

I have reseted microk8s, this have unfreezed juju from hanging out. I was trying to redeploy kubeflow using this [guide](https://charmhub.io/topics/kubeflow/quickstart), but I had stucked. Kube-system namespace is in _Init_ or _ContainerCreating_ status and admin namespace is in _Terminatting_. 

**New Introspection Report**

[inspection-report.tar.gz](https://github.com/canonical/microk8s/files/9800284/inspection-report.tar.gz)

What should I do with this?
