### ISSUE TITLE
CoreDNS doesn't work on Ubuntu 22.04, Debian 11

### ISSUE THREAD

**Issue by dzmitry-zimin** [canonical/microk8s#3504]
Hey,
I've set up a cluster on 2 nodes(server + worker) ubuntu 18.04, k8s v 1.22. All work well.
Some days ago I need to add an additional worker debian 11 and I faced with a problem - 'CoreDNS is unreachable from pods',
I've tried the solution:
```
sudo ufw allow in on vxlan.calico && sudo ufw allow out on vxlan.calico
sudo ufw allow in on cali+ && sudo ufw allow out on cali+
```
but the above it didn't help. I've tried it on ubuntu 22.04, then I've updated microk8s to 1.25 but I didn't have a success.
Then I set up new worker on base ubuntu 18.04 and all work. Thoughts?

**Comment by neoaggelos** [comment]
Hi @dzmitry-zimin

I am not sure if the issue is still relevant, but we have seen this be an issue in the past due to a vxlan bug that breaks checksum calculation on the hosts. Can you check to see whether this helps with your issue?

```
microk8s kubectl patch felixconfigurations default --patch '{"spec":{"featureDetectOverride":"ChecksumOffloadBroken=true"}}' --type=merge
```

Thanks!
