### ISSUE TITLE
nix package

### ISSUE THREAD

**Issue by ck3mp3r** [canonical/microk8s#3506]
#### Summary
It would be great to have microk8s deployable via Nix packages and not just homebrew and snap.

#### Why is this important?
This will allow for distribution to platforms using the nix package ecosystem for deterministic deployments.

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @ck3mp3r. It is not in our plans at the moment. I am not sure if this is even possible. Maybe some one from the community is willing to give this a try.

**Comment by ck3mp3r** [comment]
If it is possible to create a home-brew recipe it will be possible to do this for nix...
