### ISSUE TITLE
daemon-kubelite failed to start on nodes after update: tries to load them from the old version directory (3883) and not current

### ISSUE THREAD

**Issue by mielemilos** [canonical/microk8s#3523]
#### Summary

Child nodes were stuck in "unknown" state. After inspection it turned out the daemon-kubelite services on the nodes were down.
The logs (journalctl -u snap.microk8s.daemon-kubelite -f -n 100) showed that the certs were not found in /var/snap/microk8s/3883
The dir "3883" did not exists, only  4055 , 4094,  common and current.
A quick workaround was to 'ln currect 3883' 

#### What Should Happen Instead?

daemon-kubelite should get the certs from current

#### Reproduction Steps

1. install version 3883 on ubuntu 22.04 with 1 or more nodes
2. update over time
3. error occurs after 2 updates (when 3883 is no longer "previous")

#### Introspection Report

[inspection-report-20221023_084153.tar.gz](https://github.com/canonical/microk8s/files/9846166/inspection-report-20221023_084153.tar.gz)

#### Can you suggest a fix?

it seems the config should point to "current" and not the version it is running

#### Are you interested in contributing with a fix?

yes, but i needs some pointers as where to find the snap config ;)

**Comment by gsnsw-felixs** [comment]
I had this same issue, there were two config files which had 3883 configured as cert locations.

/var/snap/microk8s/4094/credentials/proxy.config
/var/snap/microk8s/4094//credentials/kubelet.config

I made a backup copy, changed to 4094 and then restarting microk8s worked.

**Comment by neoaggelos** [comment]
Apologies for missing this, this was tracked in a different issue and has been resolved for all supported MicroK8s tracks. If you keep having issues, please re-open, thanks!
