### ISSUE TITLE
microk8s nodes losing network connection

### ISSUE THREAD

**Issue by ThomasMinschart** [canonical/microk8s#3529]
#### Summary
It is regularly reported that there are network issues on our cluster. When we start looking, we indeed see that a lot of nodes end up in the "not ready" status. Commands like: "microk8s status" takes a super long time to finish...

If we look in the logs we see things like this:
![image](https://user-images.githubusercontent.com/116797557/198239441-854df9a2-5be7-495a-ab60-95aa72678e6b.png)

Because of this we have the feeling that there is something wrong with the APIserver or the microk8s backend.

We are currently applying the workaround below to fix this problem:
On cluster node --> kubectl drain <node-name>,
On broken node --> microk8s leave,
On cluster node --> microk8s remove-node <node>,
On cluster node --> microk8s add-node,
On broken node --> copy output of add-node command on cluster

Of course, we want to solve the problem at the root. Unfortunately, we don't find anything in the logs right away that clearly shows us what the problem is.

We expect the nodes to have no network loss. If they do, we would expect that we should be able to clearly find the reason in one of the logs.

microk8s inspect file:
[inspection-report-20221027_104957.tar.gz](https://github.com/canonical/microk8s/files/9877748/inspection-report-20221027_104957.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @ThomasMinschart,

In the logs there are a number of entries similar to:
```
Oct 27 10:45:15 lsp-k8s-lom04 microk8s.daemon-apiserver[415706]: Trace[517650125]: ---"Transaction committed" 852ms (10:45:00.725)
```
This indicates the disk the k8s datastore is using is under contentions. This is what probably causes the instability and the API server to restart and appear unavailable. Here is what you should try:

- Upgrade to a newer k8s release. 1.20 is too old.
- Have three control plane nodes and as many worker noders as you want (joined with the `--worker` flag).
- Ensure that (disk) intensive workloads are not scheduled in the control plane nodes.
