### ISSUE TITLE
`enable --help` asks for elevated permissions

### ISSUE THREAD

**Issue by barrettj12** [canonical/microk8s#3533]
#### Summary

When I try to get help for the `enable` command, I am told I need elevated permissions to do this.

```console
$ microk8s enable --help
Elevated permissions are needed for this command. Please use sudo.
```

#### What Should Happen Instead?

We shouldn't require root permissions to view the help text.
```console
$ microk8s enable --help
Usage: microk8s enable [OPTIONS] ADDONS...

  Enable a MicroK8s addon.

  For a list of available addons, run `microk8s status`.

  To see help for individual addons, run:

      microk8s enable ADDON -- --help

Options:
  -h, --help  Show this message and exit.
```

This is using the strictly confined snap v1.25.2 from channel `1.25-strict/stable`.

**Comment by ArshErgon** [comment]
Its actually weird inside https://github.com/ArshErgon/microk8s/blob/ded9d647072fab340b4205fcf121f8866428181d/installer/cli/microk8s.py#L207 it is mention that `--help` or `-h` can be start without `sudo`, but https://github.com/ArshErgon/microk8s/blob/ded9d647072fab340b4205fcf121f8866428181d/microk8s-resources/actions/common/utils.sh#L914 is forcing every command  to be run with `sudo`
