### ISSUE TITLE
microk8s suggests command hiding error info

### ISSUE THREAD

**Issue by barrettj12** [canonical/microk8s#3534]
#### Summary

When you try to run microk8s with insufficient permissions, you get an error and suggestion:

```console
$ microk8s status
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user runner to the 'snap_microk8s' group:

    sudo usermod -a -G snap_microk8s runner
    sudo chown -f -R runner ~/.kube

After this, reload the user groups either via a reboot or by running 'newgrp snap_microk8s'.
```

However, if you don't have a `~/.kube` file, the `chown` command will fail silently and suppress the error message. This can cause failures e.g. in GitHub runners / scripts with `set -e`, and the `-f` option will hide the error message. This makes it very hard to debug the failure as there are no log messages.

#### What Should Happen Instead?

Suggest to the user not to use the `-f` flag in `chown`. There is no reason to suppress the error message.
```console
$ microk8s status
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user runner to the 'snap_microk8s' group:

    sudo usermod -a -G snap_microk8s runner
    sudo chown -R runner ~/.kube

After this, reload the user groups either via a reboot or by running 'newgrp snap_microk8s'.
```

**Comment by neoaggelos** [comment]
Hi, seems like a simple fix, contributions are welcome!
