### ISSUE TITLE
AWS EKS context?

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#3537]
Does this work with AWS EKS? I `aws eks update-kubeconfig` but `microk8s kubectl config get-contexts` only shows local microk8s cluster.
#### Reproduction Steps

1. ...
2. ...

**Comment by berkayoz** [comment]
Hey @khteh,

`microk8s kubectl` uses the `kubectl` binary packaged with the snap which has a different `kubeconfig` path than `~/.kube/config`. I assume `aws eks update-kubeconfig` is updating the default config path, which `microk8s kubectl` does not use. I would suggest using a separate `kubectl` client to manage your clusters.

If you want to manage your MicroK8s cluster through the same client, you can use `microk8s config` to get the config and edit the `~/.kube/config` file to include the MicroK8s cluster as well.
