### ISSUE TITLE
ERROR resolving microk8s credentials: ensuring cluster role “juju-credential-microk8s” in namespace “kube-system”

### ISSUE THREAD

**Issue by dominikkubik** [canonical/microk8s#3538]
Please, any idea what Am i doing wrong to have it running as described in official quickstart guide on completely fresh Ubuntu installation?

#### Summary
I had to reinstall my NTB with Ubuntu 22.04 to have also GUI Desktop (from Ubuntu Server)
I try to reproduce quickstart guide for running Kubeflow on my Laptop exactly as mentioned here https://charmed-kubeflow.io/docs/quickstart. 
All steps was done correctly until the following one:

aimaster@aimaster001:~$ juju bootstrap microk8s
**ERROR resolving microk8s credentials: ensuring cluster role “juju-credential-microk8s” in namespace “kube-system”: Get https://172.16.32.232:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-microk8s": Forbidden**

#### What Should Happen Instead?

Instead it should deploy a Juju controller to the Kubernetes we set up with MicroK8s

#### Reproduction Steps

Any idea what am I doing wrong? Here is my setup: I am running following setup: Asus Zenbook Pro UX582LR, X86_64 Architecture, Ubuntu 22.04 LTS

Info:

juju 2.9.35
juju-bundle 0.4.0
juju-wait 2.8.4
kubectl 1.25.3
microk8s v1.24.6
aimaster@aimaster001:~$ microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
Service snap.microk8s.daemon-cluster-agent is running
Service snap.microk8s.daemon-containerd is running
Service snap.microk8s.daemon-kubelite is running
Service snap.microk8s.daemon-k8s-dqlite is running
Service snap.microk8s.daemon-apiserver-kicker is running
Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
Copy processes list to the final report tarball
Copy snap list to the final report tarball
Copy VM name (or none) to the final report tarball
Copy disk usage information to the final report tarball
Copy memory usage information to the final report tarball
Copy server uptime to the final report tarball
Copy current linux distribution to the final report tarball
Copy openSSL information to the final report tarball
Copy network configuration to the final report tarball
Inspecting kubernetes cluster
Inspect kubernetes cluster
Inspecting dqlite
Inspect dqlite

Building the report tarball
Report tarball is at /var/snap/microk8s/4023/inspection-report-
20221102_183658.tar.gz
aimaster@aimaster001:~$

aimaster@aimaster001:~$ microk8s status
microk8s is running
high-availability: no
datastore master nodes: 127.0.0.1:19001
datastore standby nodes: none
addons:
enabled: dashboard # (core) The Kubernetes dashboard
dns # (core) CoreDNS
ha-cluster # (core) Configure high availability on the current node
helm3 # (core) Helm 3 - Kubernetes package manager
hostpath-storage # (core) Storage class; allocates storage from host directory
ingress # (core) Ingress controller for external access
metallb # (core) Loadbalancer for your Kubernetes cluster
metrics-server # (core) K8s Metrics Server for API access to service metrics
storage # (core) Alias to hostpath-storage add-on, deprecated
disabled:
community # (core) The community addons repository
gpu # (core) Automatic enablement of Nvidia CUDA
helm # (core) Helm 2 - the package manager for Kubernetes
host-access # (core) Allow Pods connecting to Host services smoothly
mayastor # (core) OpenEBS MayaStor
prometheus # (core) Prometheus operator for monitoring and logging
rbac # (core) Role-Based Access Control for authorisation
registry # (core) Private image registry exposed on localhost:32000

#### Introspection Report
microk8s.inspect report
[inspection-report-20221103_130702.tar.gz](https://github.com/canonical/microk8s/files/9928180/inspection-report-20221103_130702.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @dominikkubik there seems to be a firewall running in your system. Is it possible you do a test run with it disabled so we can see if it standing in the way? If this is the case you should consider allowing traffic to the K8s services found in https://microk8s.io/docs/services-and-ports .

**Comment by dominikkubik** [comment]
Hello @ktsakalozos 
I tried what you suggested, but firewall seems not to be blocker in my case as you can see below.

_aimaster@aimaster001:~$ sudo ufw disable
Firewall stopped and disabled on system startup
aimaster@aimaster001:~$ sudo ufw status
Status: inactive
aimaster@aimaster001:~$ juju bootstrap microk8s
ERROR resolving microk8s credentials: ensuring cluster role "juju-credential-microk8s" in namespace "kube-system": Get "https://172.16.32.232:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-microk8s": Forbidden
aimaster@aimaster001:~$ sudo juju bootstrap microk8s
ERROR error reading current controller: cannot acquire lock file to get the current controller name: unable to open /tmp/juju-store-lock-3635383939333230: permission denied
aimaster@aimaster001:~$_

Thank you very much for your time and help.

**Comment by neoaggelos** [comment]
Hi @dominikkubik

We have seen this `Forbidden` error popping up when an http proxy is configured on the system. Is this the case for you? If not, can you do the same steps with:

```
juju bootstrap microk8s --debug
```

to get some more verbose output? Are you having any issues with using MicroK8s in general? E.g. do `microk8s kubectl get pod,node` etc work properly?

**Comment by dominikkubik** [comment]
Hello @neoaggelos 

Yes this is my case. My computer is part of network with proxy. I tried to set up  Charmed Kubeflow ax described in this tutorial - https://charmed-kubeflow.io/tutorials/deploy-kubeflow-on-microk8s-behind-a-web-proxy#4-install-microk8s

I tried 
`juju bootstrap microk8s --debug`

and get following

**Comment by neoaggelos** [comment]
Can you check whether 172.16.0.0/12 is included in the list of the no_proxy variable?

**Comment by neoaggelos** [comment]
Hi @dominikkubik, I seem to have missed this, apologies.

In general, you have to ensure that the API server traffic is excluded from the http proxy. You could use something like tcpdump to see whether the traffic goes to the API server directly or your proxy.

For the most part, error messages like `Get "https://172.16.32.232:16443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-microk8s": Forbidden` indicate that the traffic is in fact still going through the proxy.
