### ISSUE TITLE
i cant edit kubernetes-dashboard anymore after changing the type to nodeport

### ISSUE THREAD

**Issue by tgk-be** [canonical/microk8s#3540]
#### Summary
i changed the type of kubernetes-dashboard to nodeport but now everytime i try to use edit it opens the file but when i do :wq i get the error "error: services "kubernetes-dashboard" is invalid"

#### What Should Happen Instead?
it should just change what i want it to change

#### Reproduction Steps
do microk8s kubectl -n kube-system edit service kubernetes-dashboard and try to :wq

**Comment by neoaggelos** [comment]
Hi @tgk-be 

What is the output of `microk8s kubectl get service -n kube-system kubernetes-dashboard -o yaml`? What change are you trying to apply?

**Comment by tgk-be** [comment]
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kubernetes-dashboard"},"name":"kubernetes-dashboard","namespace":"kube-system"},"spec":{"ports":[{"port":443,"targetPort":8443}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
  creationTimestamp: "2022-11-01T21:33:49Z"
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
  resourceVersion: "84780"
  uid: 02f85e3e-e264-4cb2-bbb4-72e4608fc0e9
spec:
  clusterIP: 10.152.183.194
  clusterIPs:
  - 10.152.183.194
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32426
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

**Comment by tgk-be** [comment]
well when i use edit it shows me this and i edit the nodeport and then i get the error
"error: services "kubernetes-dashboard" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-3854180713.yaml""

**Comment by neoaggelos** [comment]
Are you trying to change the service type to something else from NodePort? I would suggest trying to remove the `nodePort: ` fields as well in this case. Also, apologies but the formatting from github does not help me read the yaml properly

**Comment by tgk-be** [comment]
i am trying to change the nodeport like the port its on. but the issue is
basically everytime i change anything it says that its not a valid
service even tho it shows me the yaml when i do edit.
also if you want i can mail it over to you so you have it normally

Op za 5 nov. 2022 om 13:05 schreef Angelos Kolaitis <
***@***.***>:

**Comment by tgk-be** [comment]
like i want nodeport:xxxxx to become nodeport:10443

Op za 5 nov. 2022 om 17:27 schreef Tommy Van Haute <
***@***.***>:

**Comment by neoaggelos** [comment]
Note that `nodeport:10443` is not valid yaml indeed, you need to make sure there is a space, i.e. change it to `nodePort: 32413`. Also note that by default the node port range is defined as `30000-32767`, and you need to change the API server argument `--service-node-port-range` to allow others.

See https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ and look for the `--service-node-port-range` flag

**Comment by tgk-be** [comment]
omg i'm just an idiot.
thanks for making i clear to me.

Op zo 6 nov. 2022 om 20:40 schreef Angelos Kolaitis <
***@***.***>:
