### ISSUE TITLE
how to make microk8s use host docker engine or containerd for container runtime or using different version of containerd inside microk8s?

### ISSUE THREAD

**Issue by javad87** [canonical/microk8s#3549]
#### Summary

 how to make microk8s use host docker engine or containerd for container runtime or using different version of containerd inside microk8s? Can I just change binary file in this path: /snap/microk8s/4094/bin/?
#### Why is this important?

I encountered an Error which is explained here:
https://github.com/canonical/microk8s/issues/3545
and now want to try another container runtime.
#### Are you interested in contributing to this feature?

yes

**Comment by neoaggelos** [comment]
Hi @javad87, the container runtime is a kubelet configuration flag, which can be set in `/var/snap/microk8s/current/args/kubelet`.

In particular, you should be able to set the flag like this, and change container-runtime and container-runtime-endpoint to whatever you wish to use. For more details, see the documentation for each flag in the [Kubernetes documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

```
--container-runtime=remote
--container-runtime-endpoint=${SNAP_COMMON}/run/containerd.sock
```

Note that such deployment scenarios are possible, but not tested or supported by the MicroK8s team.

**Comment by neoaggelos** [comment]
Hi @javad87

You should ensure that the host containerd is installed and configured properly.

As I mentioned, apologies but this is not something that we support at the moment, or have plans to support in the foreseeable future.

Instead, you can look into the configuration file for containerd (which is found in `/var/snap/microk8s/current/args/containerd-template.toml`. you can change any configuration option you might want, and apply it with

```
sudo snap restart microk8s.daemon-containerd
```

Hope this helps, thank you.

**Comment by javad87** [comment]
> Hi @javad87
> 
> You should ensure that the host containerd is installed and configured properly.
> 
> As I mentioned, apologies but this is not something that we support at the moment, or have plans to support in the foreseeable future.
> 
> Instead, you can look into the configuration file for containerd (which is found in `/var/snap/microk8s/current/args/containerd-template.toml`. you can change any configuration option you might want, and apply it with
> 
> ```
> sudo snap restart microk8s.daemon-containerd
> ```
> 
> Hope this helps, thank you.

tnx @neoaggelos I understand and appreciate your kind hint, exacalty I tried to use my host installed containerd for microk8s cotanier run time, and tweaking variables in /var/snap/microk8s/current/args/containerd-template.toml and restarting all microk8s daemon by microk8s stop, start ....any way could not figure it out, but as I explained at last comment here: https://github.com/canonical/microk8s/issues/3545
I tried to revert back to previous version of microk8s on my server that worked correctly, I did it through offline installation of microk8s and then reverting back....

lesson learned is that pls add in the user guide so that other also know that "snap auto refresh and update packages without notice" and they have to stop it.
