### ISSUE TITLE
microk8s docker image pull error

### ISSUE THREAD

**Issue by lramachandr** [canonical/microk8s#3566]
we are using microk8s on ubuntu 18.04 .

we have a private docker registry hosted on remote machine which is tls secured. 

all the images are going in imagepullBackoff as images are not getting pulled from the registry

Events:
  Type    Reason   Age                    From     Message
  ----    ------   ----                   ----     -------
  Normal  BackOff  2m22s (x344 over 80m)  kubelet  Back-off pulling image "docker-registry.com:5000/*******"

We have configured microk8s to take docker as a container runtime in below file location

--->/var/snap/microk8s/current/args/kubelet
Change --container-runtime=docker 

after exploring we have added below config as mentioned but still we are seeing imagePullBackOff issue.
 
/var/snap/microk8s/current/args/certs.d/****:5000/hosts.toml
server = "https://****:5000"

[host."https://****:5000"]
capabilities = ["pull", "resolve"]

Please let us know if we need to update any other configuration.

**Comment by neoaggelos** [comment]
Hi @lramachandr 

Is there any specific error message you are seeing in containerd? Is there anything in the output of `microk8s kubectl describe pod $yourpod` or `sudo journalctl -u snap.microk8s.daemon-containerd` that looks suspicious?

Is the registry perhaps using a self-signed certificate? Finally, can you try pulling an image directly like this:

```
microk8s ctr image pull --hosts-dir /var/snap/microk8s/current/args/certs.d $yourimage
```

Also, which microk8s version is this? Does the registry require credentials to work?

**Comment by lramachandr** [comment]
1)we have self signed certificate 

2) microk8s ctr image pull --hosts-dir /var/snap/microk8s/current/args/certs.d docker-registry.com:5000/nginx/nginx-ingress:1.10.1
INFO[0000] trying next host                              error="failed to do request: Head \"https://docker-registry.com:5000/v2/nginx/nginx-ingress/manifests/1.10.1\": x509: certificate relies on legacy Common Name field, use SANs instead" host="docker-registry.com:5000"
INFO[0000] trying next host                              error="failed to do request: Head \"https://docker-registry.com:5000/v2/nginx/nginx-ingress/manifests/1.10.1\": x509: certificate relies on legacy Common Name field, use SANs instead" host="docker-registry.com:5000"
ctr: failed to resolve reference "docker-registry.com:5000/nginx/nginx-ingress:1.10.1": failed to do request: Head "https://docker-registry.com:5000/v2/nginx/nginx-ingress/manifests/1.10.1": x509: certificate relies on legacy Common Name field, use SANs instead

**Comment by neoaggelos** [comment]
Looks like containerd is having issues with the self-signed CA then. Can you test if [the documentation for configuring the CA](https://microk8s.io/docs/registry-private#using-a-custom-ca-8) solves your issue?

**Comment by lramachandr** [comment]
yes i have followed the same steps but its not accepting CA

**Comment by neoaggelos** [comment]
OK, in the issue description I now saw (sorry, formatting is a bit confusing) that you have changed the `--container-runtime` to docker? If so, then any containerd configs you change would be irrelevant.

Further, which MicroK8s version are you using?

**Comment by lramachandr** [comment]
vmauser@ubuntu18:~$ microk8s version
MicroK8s v1.25.3 revision 4128
