### ISSUE TITLE
worker node fail to start because kubelet config is looked into a non existent folder 

### ISSUE THREAD

**Issue by anubisg1** [canonical/microk8s#3569]
#### Summary
Worker node is not ready becasue ` NodeStatusUnknown   Kubelet stopped posting node status.` 
further investigation shows that 

```
 Error: failed to run Kubelet: invalid kubeconfig: invalid configuration: [unable to read client-cert /var/snap/microk8s/4055/certs/kubelet.crt for kubelet due to open /var/snap/microk8s/4055/certs/kubelet.crt: no such file or directory, unable to read client-key /var/snap/microk8s/4055/certs/kubelet.key for kubelet due to open /var/snap/microk8s/4055/certs/kubelet.key: no such file or directory]
```

the folder /var/snap/microk8s/4055/ actully does not exist, instead only 40994 and 4128 exist (and of course the "current" symlink

looking at /var/snap/microk8s/current/args/kubelet i can see a lot of references to ${SNAP_DATA} which i think caused the problem.

this was likely addressed with https://github.com/canonical/microk8s/pull/3554 in some fashion

#### What Should Happen Instead?
kubelet should start

#### Can you suggest a fix?
always point to /var/snap/microk8s/current to ensure to have a working configration

**Comment by neoaggelos** [comment]
Hi @anubisg1, thank you for reporting this

Indeed, https://github.com/canonical/microk8s/pull/3554 should be fixing this, and the fix is also backported to 1.25 already with https://github.com/canonical/microk8s/pull/3563
