### ISSUE TITLE
snap refresh microk8s but calico not upgrade

### ISSUE THREAD

**Issue by logici** [canonical/microk8s#3574]
#### Summary

Firstly, I do not know whether it is a bug.  I do something below.
1. `sudo snap refresh microk8s --channel=1.24/stable` , upgrade from 1.19/stable to 1.24/stable.
2.  It is all done. But the calico is now be upgraded. Is this expected? And if I want to upgrade calico fitted microk8s1.24, what should I do?
#### Reproduction Steps

1. ...
3. ...

**Comment by logici** [comment]
Thanks for your reply @neoaggelos 
I see that it need to mount the all kinds of dir which include some calico plugins. So I also need to replace all mounted dir or files. Can there be a tool to help me?

**Comment by neoaggelos** [comment]
Hi @logici 

For the most part, there are two paths:

- If you have not done any changes to the `cni.yaml` file yourself, then simply copy-pasting the new one over it and reapply will work as you expect. Commands to get you started are above, (ignore the "transfer any manual changes" part).
- If you have done "extensive" changes, you can just bump the calico images in the existing file with something like:

```
sudo sed -i 's/v3.23.3/v3.23.5/' /var/snap/microk8s/current/args/cni-network/cni.yaml
```

In any case, we do not have any specific tools, as the amount of cases to handle would be too many. Hope this helps!

**Comment by logici** [comment]
Thanks! @neoaggelos 

The second one didn't work fine for me. Because I upgrade microk8s from v1.19 to v1.24 and some apiversion change from `v1beta1` to `v1`.

The first one and second one both need to modify the calico plugin `/var/snap/microk8s/current/opt/cni/bin` which will be mounted into calico pod.  It need to modify so many. 

And I feel that the folder `/var/snap/microk8s` is unreliable which it may reset to its original appearance. But actually, I am not sure.

So, in my opinion, microk8s should supply a tool to achieve the whole microk8s 1.24 status(in my case). Or when execute `sudo snap refresh microk8s --channel=1.24/stable` which can support some options to upgrade calico.

**Comment by neoaggelos** [comment]
> The first one and second one both need to modify the calico plugin /var/snap/microk8s/current/opt/cni/bin which will be mounted into calico pod. It need to modify so many.

Getting the Calico yaml from `/snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml` should come with all the important paths patched already. What kind of issue did you have?

> The second one didn't work fine for me. Because I upgrade microk8s from v1.19 to v1.24 and some apiversion change from v1beta1 to v1.

Yes, and this is part of the reason why we refrain from auto-updating cluster objects. Imagine for example the situation where a cluster administrator would want to revert a change. Changing things automagically would only serve as a source of confusion and frustration.

> And I feel that the folder /var/snap/microk8s is unreliable which it may reset to its original appearance. But actually, I am not sure. 

The contents of /var/snap/microk8s will not go away or be overwritten. `/var/snap/microk8s/common` is meant for files shared across all snap revisions, and `/var/snap/microk8s/current` is for things that might change on updates, and they are kept as-is to enable upgrade reverts in case things might go wrong.

Thanks!

**Comment by logici** [comment]
> Getting the Calico yaml from /snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml should come with all the important paths patched already. What kind of issue did you have?
I am so sorry. It is my fault. The calico.yaml is so long that I did not check carefully whether it can help me to upgrade calico plugins. 
Thanks so much for your reply! @neoaggelos

**Comment by djjudas21** [comment]
@neoaggelos can you explain how the Calico upgrade process works on a multi-node cluster? I have had a 3-node cluster since microk8s v1.15 or something, and I have upgraded to every version including v1.25. Do I have to do the steps from https://github.com/canonical/microk8s/issues/3574#issuecomment-1319891135 on just one node, or all of them? Thanks

**Comment by neoaggelos** [comment]
Hi @djjudas21, sorry for missing this.

The calico upgrade only need be done from a single node (it updates the daemonset and the deployment running in the cluster). In general, the process looks like this:

- Do a rolling upgrade of all MicroK8s nodes to the next minor version.
- Update calico and apply the new version (once).
