### ISSUE TITLE
knative addon on v1.26 RC is failing

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/microk8s#3597]
#### Summary
Enabling the knative addon on the 1.26-RC results in a setup that cannot be disabled. The K8s 1.26 release removes the  
`autoscaling/v2beta2` API version of `HorizontalPodAutoscaler`, the `autoscaling/v2` should be used instead. Enabling the knative addon (see repro steps below) results in  `microk8s.kubectl describe -n knative-serving knativeserving.operator.knative.dev` showing the following warning:
```
  Warning  InternalError  3m4s (x3 over 13m)  knativeserving-controller  failed to apply non rbac manifest: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
```
Looking at the release notes of knative v1.8.0 [2] this issue must have been addressed, but unfortunately I am still seeing it. 
Maybe I am missing something in the deployment process, @csantanapr could you offer some insight on what might be wrong?

[1] https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#removal-of-the-v2beta2-horizontalpodautoscaler-api
[2] https://github.com/knative/serving/releases/tag/knative-v1.8.0

#### What Should Happen Instead?
The addon should come up correctly.

#### Reproduction Steps
Install the 1.26 RC:
```
sudo snap install microk8s --classic --channel=1.26/candidate
```

Enable the community addons:
```
sudo microk8s enable community
```

Have the knative addon deploy the v1.8.1 release by editing `/var/snap/microk8s/common/addons/community/addons/knative/enable` and `/var/snap/microk8s/common/addons/community/addons/knative/disable`  to set  `KNATIVE_VERSION="1.8.1".

Enable the knative addon:
```
sudo microk8s enable knative
```

See the error:
```
sudo microk8s.kubectl describe -n knative-serving knativeserving.operator.knative.dev
```

See disable command hang:
```
sudo microk8s disable knative
```

**Comment by neoaggelos** [comment]
From some early investigation, perhaps there are still some dependencies using `autoscaling/v2beta2`?

I see https://github.com/knative/serving/blob/3d9c724d13c5ebe23317f4f77d996b373440b831/vendor/knative.dev/pkg/client/injection/kube/client/client.go have lots of references to it, and this is pulled as a depedency of knative serving. So perhaps there is still some usage of the v2beta2 APIs that has not been fixed?

Dependency on knative/pkg here https://github.com/knative/serving/blob/cd1cd1a612579f93cc6d94df07b20be3247159fb/go.mod#L40
