### ISSUE TITLE
Increasing disk space utilization on non-opereating cluster

### ISSUE THREAD

**Issue by Azbesciak** [canonical/microk8s#3604]
#### Summary
The disk space utilization goes up even when the cluster is not used (pods are running, but do not do anything)
![image](https://user-images.githubusercontent.com/17334466/204698972-6a8884cd-cae9-480a-b6f0-08afb81070c6.png)
![image](https://user-images.githubusercontent.com/17334466/204700097-e5cd50e3-7f1e-48c5-bb64-c2791c0499f4.png)
Both nodes have something similar - I have the master and the worker one (below)
![image](https://user-images.githubusercontent.com/17334466/204699937-d68b895e-7e83-4e25-b3dd-4c6af9663a7c.png)
![image](https://user-images.githubusercontent.com/17334466/204700140-6aae8374-93c3-422d-b0a3-1ba3e16030ab.png)

#### What Should Happen Instead?
The disk space should not grow up. The same deployment on docker-compose worked well for the recent 2 years without any surprise. I installed microk8s in parallel 2 months ago, and then some things started to happen. I have even cleared all cluster images [with this approach](https://stackoverflow.com/questions/72434877/how-to-make-microk8s-ctr-image-prune), and it helped a lot, but there is still something wrong. Please notice that both the attached log and chart above are from the newly created cluster on new VMs (same config, 2 nodes), which is not used, so there should be no reason for it to generate so much disk usage.

#### Introspection Report
[inspection-report-20221130_031420.tar.gz](https://github.com/canonical/microk8s/files/10119066/inspection-report-20221130_031420.tar.gz)

I haven't done anything special, so what makes the problem happen...?

**Comment by Azbesciak** [comment]
Update after 24h - +2 percent points (first machine, no usage). Any idea what is going on?
![image](https://user-images.githubusercontent.com/17334466/204990659-ac32dbd4-0cf1-41e5-b59c-a09a632b92ad.png)

**Comment by ktsakalozos** [comment]
Hi @Azbesciak, is it possible to spot what parts of the filesystem grows? In particular, MicroK8s places its files under `/var/snap/microk8s/current` and `/var/snap/microk8s/current`. Are these the ones that are growing? If yes could we drill into it a bit more?

**Comment by Azbesciak** [comment]
Hi, thank you for the response.
What do you exactly need? I am using the default grafana config from the `observability` plugin (so maybe which dashboard/chart?). 
below `micok8s inspect` from now from the main machine (same as before)
[inspection-report-20221201_080226.tar.gz](https://github.com/canonical/microk8s/files/10130419/inspection-report-20221201_080226.tar.gz)

**Comment by Azbesciak** [comment]
Another +300MB
[inspection-report-20221201_080226.tar.gz](https://github.com/canonical/microk8s/files/10137980/inspection-report-20221201_080226.tar.gz)

**Comment by Azbesciak** [comment]
for 3 days (2-5 Dec) `/var/snap/microk8s` increased from 8.3 to 8.4GB. It is much lower than the above... but anyway, expected and accepted? Most changes are in `common/var/lib/containered/`, but also `loki` volume increased by 30M.

I base on the `du . -h` results, below (reboot was between, but the disk usage did not change);

[du-2022-12-02.txt](https://github.com/canonical/microk8s/files/10150738/du-2022-12-02.txt)
[du-2022-12-05.txt](https://github.com/canonical/microk8s/files/10150736/du-2022-12-05.txt)

Below report from 03 and today (05) if you would need it
[inspection-report-20221203_043914.tar.gz](https://github.com/canonical/microk8s/files/10150744/inspection-report-20221203_043914.tar.gz)
[inspection-report-20221205_042710.tar.gz](https://github.com/canonical/microk8s/files/10150745/inspection-report-20221205_042710.tar.gz)

**Comment by Azbesciak** [comment]
Maybe this is connected with https://github.com/canonical/microk8s/issues/1465?
