### ISSUE TITLE
permanently dropping privs did not work: File exists

### ISSUE THREAD

**Issue by barrettj12** [canonical/microk8s#3607]
#### Summary

I get a strange error when trying to run the microk8s snap as a user outside the `microk8s` group:
```
permanently dropping privs did not work: File exists
```

#### What Should Happen Instead?

I would expect a useful error, e.g. "You don't have permission to access MicroK8s".

#### Reproduction Steps

```console
$ sudo snap install microk8s
$ sg adm 'microk8s status'
permanently dropping privs did not work: File exists
```

#### Introspection Report

Not sure how to attach a tarball.

**Comment by ktsakalozos** [comment]
Hi @barrettj12 could you offer some more details on what the host OS is so I could reproduce the issue? A `microk8s inspect` tarball would tell us a lot. Also I assume your installation was with `sudo snap install microk8s --classic`, right?

**Comment by barrettj12** [comment]
It was either inside a LXD container or on a GitHub runner (Ubuntu 22.04). Will try to reproduce tomorrow.

**Comment by barrettj12** [comment]
```console
$ lxc launch ubuntu: c
$ lxc exec c bash
root@c:~# snap install microk8s --classic
microk8s (1.25/stable) v1.25.4 from Canonical✓ installed
root@c:~# sg adm 'microk8s status'
permanently dropping privs did not work: File exists
```

**Comment by PyDataBlog** [comment]
Same issue here. The only solution is to do `sudo microk8s status`

**Comment by neoaggelos** [comment]
This error is not coming from MicroK8s. Maybe worth asking some folks from LXD?
