### ISSUE TITLE
Rolling update with pvc `ReadOnlyMany` and deployment: Unable to attach or mount volumes: unmounted volumes, unattached volumes timed out waiting for the condition

### ISSUE THREAD

**Issue by Azbesciak** [canonical/microk8s#3624]
#### Summary
Hello, I face a problem when I try to update the pods version on my deployments, which are using the same PVC with `ReadOnlyMany` access. The problem is that it hangs because of the error
`Unable to attach or mount volumes: unmounted volumes=[my-pvc], unattached volumes=[my-pvc, ...] timed out waiting for the condition`.

I suppose it should not cause problems? I have found different theories, but these were rather related to implementation errors on given platform, or that the one used `ReadOnlyOnce`, not `ReadOnlyMany`, like there https://www.reddit.com/r/kubernetes/comments/i9axle/how_to_do_rolling_update_for_deployment_with_pvc/

`ReadWriteMany` also did not work for me.

The biggest problem is that is not predictable - sometimes it works, sometimes not.
For example, now when I tried to replicate this after shutting down everything for the 3rd time for `microk8s inspect` purpose (the previous 2 times were reproducible) I could not replicate it...
#### What Should Happen Instead?
the deployment should pass

#### Introspection Report
[inspection-report-20221212_070005.tar.gz](https://github.com/canonical/microk8s/files/10205309/inspection-report-20221212_070005.tar.gz)

**Comment by neoaggelos** [comment]
Hi @Azbesciak, I think this is not a MicroK8s but rather a "working as intended" that has to do with pods being scheduled on different nodes. Note that Kubernetes sends `ReadWriteMany` and `ReadOnlyMany` to the underlying storage provider implementation, and it is up to it to provision things correctly.

Perhaps this is something that you could tackle by configuring correct PodAffinity rules https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity.

**Comment by Azbesciak** [comment]
Thank you for that advice and for checking that issue.
I also checked that, but that PV is a NFS, and right now it is working on the master node, whereas consumers are on the workers. There was no affinity specified for these containers (NFS has it indeed - it has to work on the master node).

Basically, I have 3 deployments that are using that PVC. For the purpose of the test I specified the affinity for 2 of them (a different node), and one left without but was scaled to 3 so effectively it was on all nodes, and on one it was duplicated.
And it is working now.

Am I getting you wrong?

**Comment by neoaggelos** [comment]
> And it is working now.

Good to know that at least it works. Can you verify with `microk8s kubectl get pod -A -o wide`? (no need to share the output)

In that case, I am not sure, maybe this is something to ask in upstream Kubernetes (https://github.com/kubernetes/kubernetes). MicroK8s itself is upstream Kubernetes, and you will most likely find someone there that is much more knowledgeable to discuss the issue and figure out whether it is a bug or not.

Hope this helps!

**Comment by Azbesciak** [comment]
> And it is working now.

But the problem there is that the configuration is exactly the same, I just needed to kill everything and set it up again. The previous one occurred when I bumped up image versions. Now I can do it without any problems, and It works for the last week, but now we are in a test environment; I want to introduce Kubernetes to production, but if during the update it will just hang... you know.

>  Can you verify with `microk8s kubectl get pod -A -o wide`

In general, I checked it via the Kubernetes dashboard, but that command also confirmed the same.

**Comment by Azbesciak** [comment]
I do not understand it. Now I changing the conf to be managed with Helm.
I have the same config right now, but when pod is on the second node, PVC cannot be attached (_Unable to attach or mount volumes: unmounted volumes_). PV is still NFS. When that pod is on the first node, it works fine.
