### ISSUE TITLE
update homebrew formula to newest microk8s version (1.26) - otherwise Mac Users can't use it.

### ISSUE THREAD

**Issue by turbopape** [canonical/microk8s#3628]
#### Summary
The latest present formula on homebrew dates back to v2.2, of September 2021. This makes it near to impossible for mac users to use it.

#### Why is this important?
 Lot has changed since that time. The instructions do not work in the present day, leading to newbies like myself wasting precious time, assuming the fault is theirs :)

#### Are you interested in contributing to this feature?
yep definitely.

**Comment by neoaggelos** [comment]
Hi @turbopape, thank you for raising this.

This is indeed in our team's radar now that the 1.26 release is out. The relevant files to look at are https://github.com/canonical/microk8s/blob/master/installer/common/definitions.py#L31. The MicroK8s team is on it (the installer has not been updated in a while, but we are looking to pick this up). That said, contributions are always welcome!

After the channel is updated, a member of the team can look to do a new release for https://github.com/ubuntu/homebrew-microk8s.

**Comment by neoaggelos** [comment]
This is resolved

**Comment by oviliz** [comment]
> This is resolved

Hi @neoaggelos , did this PR also fix https://github.com/canonical/microk8s/issues/3525#issue-1421082574 ?
