### ISSUE TITLE
microk8s not starting behind corporate proxy

### ISSUE THREAD

**Issue by SR4ven** [canonical/microk8s#3629]
#### Summary

I'm unable to start microk8s behind a corporate proxy on Ubuntu 22.04.
https://microk8s.io/docs/install-proxy was followed.

/etc/environment
```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
HTTP_PROXY=http://192.168.135.221:3128
http_proxy=http://192.168.135.221:3128
HTTPS_PROXY=http://192.168.135.221:3128
https_proxy=http://192.168.135.221:3128
NO_PROXY=localhost,127.0.0.0/8,::1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16
no_proxy=localhost,127.0.0.0/8,::1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/16
```
(no_proxy=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16 as suggested in the proxy guide didn't work either)

My guess is that it is somehow related to this error in the containerd log:
```
Dez 15 16:23:19 dev microk8s.daemon-containerd[19054]: time="2022-12-15T16:23:19.894977791+01:00" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /var/snap/microk8s/4390/args/cni-network: cni plugin not initialized: failed to load cni config"
```

I also tried to set the proxy variables in `/var/snap/microk8s/current/args/containerd-env` and other *-env files without success.

`microk8s.kubectl get all` somewhat works
```
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   54m
```

#### What Should Happen Instead?

`microk8s status` always reports `microk8s is not running.`

#### Reproduction Steps

1. Setup Ubuntu 22.04 inside of a proxy environment and configure /etc/environment
2. Install microk8s 1.26

#### Introspection Report

[inspection-report.zip](https://github.com/canonical/microk8s/files/10238601/inspection-report.zip)

**Comment by neoaggelos** [comment]
Hi @SR4ven, can you try including `127.0.0.1` in the no_proxy string directly and restart with `sudo snap restart microk8s`

**Comment by SR4ven** [comment]
Hi @neoaggelos, `127.0.0.1` was still included form my last test as mentioned here:

> (no_proxy=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16 as suggested in the proxy guide didn't work either)

However, `sudo snap restart microk8s` actually fixed it and `microk8s status` shows it running now. So many thanks!

Still I'd like to understand what's happening. Why is `microk8s stop; microk8s start` not showing the same effect? I even did several reboots during debugging and even purged and reinstalled the microk8s snap several times in different versions.
So what magic happens with `snap restart`?

**Comment by neoaggelos** [comment]
Apologies for taking long to reply. 

`microk8s stop; microk8s start` will only restart the Kubernetes services, not the container runtime. Hence `containerd` did not pick up any configuration changes.

**Comment by SR4ven** [comment]
Ok got it, thanks for the explanation.

Maybe it's worth mentioning `sudo snap restart microk8s` in the troubleshooting section of the docs or on the proxy setup guide https://microk8s.io/docs/install-proxy? Only `microk8s stop/start` are mentioned there.
