### ISSUE TITLE
Microk8s running but pods stuck in Unknown / ContainerCreating

### ISSUE THREAD

**Issue by pinahar** [canonical/microk8s#3630]
#### Summary
We have a single node microk8s cluster which uses OLM. We accidentally put in a cron job which refreshed server.crt and front-proxy-client.crt every hour which has put the cluster in an unresponsive state and pods were restarting frequently. Kubelite CPU usage is also pretty high.
We stopped the job and restarted microk8s in the hope of recovery but a lot of pods are now stuck in Unknown / ContainerCreating state.

microk8s kubectl commands take a long time to run as well.

#### What Should Happen Instead?
Pods should be ready

#### Reproduction Steps
1. Install our OLM based application on a fresh instance
2. Refresh server.crt and front-proxy-client.crt every hour
3. Pods go in a restart loop and kubelite CPU usage spikes

#### Introspection Report
[inspection-report-20221216_190832.tar.gz](https://github.com/canonical/microk8s/files/10248422/inspection-report-20221216_190832.tar.gz)

**Comment by neoaggelos** [comment]
Looking at the logs, I see the following quite a few times:

```
Dec 16 19:02:27 capig.localdomain microk8s.daemon-kubelite[2254036]: E1216 19:02:27.960697 2254036 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=15s": context deadline exceeded
Dec 16 19:02:27 capig.localdomain microk8s.daemon-kubelite[2254036]: I1216 19:02:27.960912 2254036 leaderelection.go:278] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
```

This is coming after a few trace logs showing that datastore requests are taking a very long time. Essentially, it looks like the datastore is not in a good state, which translates to API server requests taking a long time and the controller manager losing the leader election lock.

Further, I see that this is MicroK8s version 1.21. Keep in mind that due to the way containerd is configured in MicroK8s versions < 1.22, every time MicroK8s restarts, so do all the containers running on that node (similar to what you would see when you do a `systemctl restart docker`). Further, Kubernetes 1.21 is now considered EOL.

Effectively, this puts a huge pressure on the node causing it to stay in this limbo state of failing to come up, crashing on its own weight and starting over.

One way to move forward would be to consider using a newer Kubernetes version. Even starting with 1.22 will be very useful, since kubelite restarts would not kill the container workloads.

**Comment by pinahar** [comment]
We can consider upgrading the version once we can stabilize the current setup. Can you suggest something to alleviate the load on the datastore and get the cluster running?
Also, is there a way to upgrade a running cluster without data loss?

**Comment by neoaggelos** [comment]
> We can consider upgrading the version once we can stabilize the current setup. Can you suggest something to alleviate the load on the datastore and get the cluster running?

This would heavily depend on the workload itself, so not sure how much I could help you with this. One thing that be useful would be to start each service one by one and wait for each one to properly come up prior to continuing:

```bash
sudo snap stop microk8s
sudo snap start microk8s.daemon-k8s-dqlite   # and check `journactl -f` until the datastore comes up
sudo snap start microk8s           # start the rest of the services and wait until the stabilize
```

Can you also share the output of `ls -la /var/snap/microk8s/current/var/kubernetes/backend`? also cc @MathieuBordere, if you can provide any insight into this

---

As for the upgrade: from the inspection report I see it's a single node installation, to upgrade to `1.22` it would suffice to do:

```
sudo snap refresh microk8s --channel 1.22
```

This will upgrade your MicroK8s to 1.22, and preserve all the data in the process. See also the [Upgrading](https://microk8s.io/docs/upgrading) documentation page for more details.

If you observe failures after the upgrade, you can always revert with `sudo snap revert microk8s`.

**Comment by pinahar** [comment]
I get this error when I try to start dqlite ->
root@capig:~# sudo snap start microk8s.daemon-k8s-dqlite
error: snap "microk8s" has no service "daemon-k8s-dqlite"
Am I missing something?

Output for the command you requested ->
root@capig:~# ls -la /var/snap/microk8s/current/var/kubernetes/backend
total 1593048
drwxrwx--- 2 root microk8s     20480 Dec 17 10:26 .
drwxr-xr-x 3 root root          4096 Oct 28  2021 ..
-rw-rw---- 1 root microk8s   3991016 Dec 17 03:44 0000000410165567-0000000410165707
-rw-rw---- 1 root microk8s   2637344 Dec 17 03:49 0000000410165708-0000000410165800
-rw-rw---- 1 root microk8s   2164184 Dec 17 03:53 0000000410165801-0000000410165876
-rw-rw---- 1 root microk8s   2201672 Dec 17 03:58 0000000410165877-0000000410165960
-rw-rw---- 1 root microk8s   2587952 Dec 17 04:03 0000000410165961-0000000410166051
-rw-rw---- 1 root microk8s   2842856 Dec 17 04:07 0000000410166052-0000000410166148
-rw-rw---- 1 root microk8s   2312480 Dec 17 04:13 0000000410166149-0000000410166232
-rw-rw---- 1 root microk8s   2399048 Dec 17 04:18 0000000410166233-0000000410166321
-rw-rw---- 1 root microk8s   2987048 Dec 17 04:23 0000000410166322-0000000410166426
-rw-rw---- 1 root microk8s   2921672 Dec 17 04:27 0000000410166427-0000000410166535
-rw-rw---- 1 root microk8s   3234176 Dec 17 04:33 0000000410166536-0000000410166652
-rw-rw---- 1 root microk8s   3159920 Dec 17 04:37 0000000410166653-0000000410166764
-rw-rw---- 1 root microk8s   3538280 Dec 17 04:42 0000000410166765-0000000410166887
-rw-rw---- 1 root microk8s   3106568 Dec 17 04:47 0000000410166888-0000000410166999
-rw-rw---- 1 root microk8s   2332736 Dec 17 04:52 0000000410167000-0000000410167079
-rw-rw---- 1 root microk8s   2485424 Dec 17 04:57 0000000410167080-0000000410167171
-rw-rw---- 1 root microk8s   3028016 Dec 17 05:02 0000000410167172-0000000410167275
-rw-rw---- 1 root microk8s   3167504 Dec 17 05:08 0000000410167276-0000000410167378
-rw-rw---- 1 root microk8s   3007424 Dec 17 05:12 0000000410167379-0000000410167481
-rw-rw---- 1 root microk8s   3299816 Dec 17 05:17 0000000410167482-0000000410167598
-rw-rw---- 1 root microk8s   3731888 Dec 17 05:22 0000000410167599-0000000410167731
-rw-rw---- 1 root microk8s   3658160 Dec 17 05:27 0000000410167732-0000000410167866
-rw-rw---- 1 root microk8s   3772784 Dec 17 05:31 0000000410167867-0000000410167997
-rw-rw---- 1 root microk8s   3262472 Dec 17 05:37 0000000410167998-0000000410168108
-rw-rw---- 1 root microk8s   1876232 Dec 17 05:42 0000000410168109-0000000410168175
-rw-rw---- 1 root microk8s   2197520 Dec 17 05:47 0000000410168176-0000000410168258
-rw-rw---- 1 root microk8s   1950464 Dec 17 05:51 0000000410168259-0000000410168330
-rw-rw---- 1 root microk8s   1637720 Dec 17 05:56 0000000410168331-0000000410168390
-rw-rw---- 1 root microk8s   1810160 Dec 17 06:01 0000000410168391-0000000410168451
-rw-rw---- 1 root microk8s   2102672 Dec 17 06:06 0000000410168452-0000000410168528
-rw-rw---- 1 root microk8s   1732112 Dec 17 06:10 0000000410168529-0000000410168588
-rw-rw---- 1 root microk8s   2472824 Dec 17 06:15 0000000410168589-0000000410168676
-rw-rw---- 1 root microk8s   1962368 Dec 17 06:20 0000000410168677-0000000410168742
-rw-rw---- 1 root microk8s   2464832 Dec 17 06:25 0000000410168743-0000000410168833
-rw-rw---- 1 root microk8s   2904824 Dec 17 06:30 0000000410168834-0000000410168936
-rw-rw---- 1 root microk8s   2415248 Dec 17 06:35 0000000410168937-0000000410169022
-rw-rw---- 1 root microk8s   2662112 Dec 17 06:40 0000000410169023-0000000410169117
-rw-rw---- 1 root microk8s   2769104 Dec 17 06:45 0000000410169118-0000000410169216
-rw-rw---- 1 root microk8s   2756744 Dec 17 06:50 0000000410169217-0000000410169314
-rw-rw---- 1 root microk8s   2847296 Dec 17 06:55 0000000410169315-0000000410169416
-rw-rw---- 1 root microk8s   2555696 Dec 17 07:00 0000000410169417-0000000410169515
-rw-rw---- 1 root microk8s   2682944 Dec 17 07:05 0000000410169516-0000000410169614
-rw-rw---- 1 root microk8s   3361592 Dec 17 07:10 0000000410169615-0000000410169734
-rw-rw---- 1 root microk8s   2999360 Dec 17 07:15 0000000410169735-0000000410169839
-rw-rw---- 1 root microk8s   3900512 Dec 17 07:21 0000000410169840-0000000410169977
-rw-rw---- 1 root microk8s   4007072 Dec 17 07:25 0000000410169978-0000000410170113
-rw-rw---- 1 root microk8s   2903984 Dec 17 07:31 0000000410170114-0000000410170204
-rw-rw---- 1 root microk8s   2456408 Dec 17 07:36 0000000410170205-0000000410170292
-rw-rw---- 1 root microk8s   2942192 Dec 17 07:41 0000000410170293-0000000410170401
-rw-rw---- 1 root microk8s   2262824 Dec 17 07:46 0000000410170402-0000000410170479
-rw-rw---- 1 root microk8s   2842904 Dec 17 07:51 0000000410170480-0000000410170577
-rw-rw---- 1 root microk8s   3418976 Dec 17 07:56 0000000410170578-0000000410170696
-rw-rw---- 1 root microk8s   3592376 Dec 17 08:01 0000000410170697-0000000410170829
-rw-rw---- 1 root microk8s   3394712 Dec 17 08:06 0000000410170830-0000000410170953
-rw-rw---- 1 root microk8s   4283336 Dec 17 08:11 0000000410170954-0000000410171107
-rw-rw---- 1 root microk8s   3336824 Dec 17 08:16 0000000410171108-0000000410171225
-rw-rw---- 1 root microk8s   2645984 Dec 17 08:21 0000000410171226-0000000410171324
-rw-rw---- 1 root microk8s   2369600 Dec 17 08:25 0000000410171325-0000000410171403
-rw-rw---- 1 root microk8s   2583992 Dec 17 08:30 0000000410171404-0000000410171496
-rw-rw---- 1 root microk8s   2151728 Dec 17 08:35 0000000410171497-0000000410171570
-rw-rw---- 1 root microk8s   2229896 Dec 17 08:40 0000000410171571-0000000410171647
-rw-rw---- 1 root microk8s   2172536 Dec 17 08:45 0000000410171648-0000000410171725
-rw-rw---- 1 root microk8s   2946440 Dec 17 08:50 0000000410171726-0000000410171836
-rw-rw---- 1 root microk8s   2880056 Dec 17 08:55 0000000410171837-0000000410171937
-rw-rw---- 1 root microk8s   2748392 Dec 17 09:00 0000000410171938-0000000410172033
-rw-rw---- 1 root microk8s   2953640 Dec 17 09:05 0000000410172034-0000000410172130
-rw-rw---- 1 root microk8s   3192608 Dec 17 09:10 0000000410172131-0000000410172240
-rw-rw---- 1 root microk8s   2736632 Dec 17 09:15 0000000410172241-0000000410172344
-rw-rw---- 1 root microk8s   3509576 Dec 17 09:20 0000000410172345-0000000410172467
-rw-rw---- 1 root microk8s   2920808 Dec 17 09:26 0000000410172468-0000000410172564
-rw-rw---- 1 root microk8s   3398024 Dec 17 09:30 0000000410172565-0000000410172677
-rw-rw---- 1 root microk8s   2596304 Dec 17 09:35 0000000410172678-0000000410172770
-rw-rw---- 1 root microk8s   2686760 Dec 17 09:40 0000000410172771-0000000410172865
-rw-rw---- 1 root microk8s   3056888 Dec 17 09:45 0000000410172866-0000000410172971
-rw-rw---- 1 root microk8s   3040544 Dec 17 09:50 0000000410172972-0000000410173078
-rw-rw---- 1 root microk8s   3229712 Dec 17 09:55 0000000410173079-0000000410173190
-rw-rw---- 1 root microk8s   3246392 Dec 17 10:00 0000000410173191-0000000410173306
-rw-rw---- 1 root microk8s   3102752 Dec 17 10:05 0000000410173307-0000000410173422
-rw-rw---- 1 root microk8s   3974240 Dec 17 10:10 0000000410173423-0000000410173558
-rw-rw---- 1 root microk8s   3106088 Dec 17 10:15 0000000410173559-0000000410173663
-rw-rw---- 1 root microk8s   2978624 Dec 17 10:20 0000000410173664-0000000410173765
-rw-rw---- 1 root microk8s   2670464 Dec 17 10:25 0000000410173766-0000000410173862
-rw-rw---- 1 root microk8s      1879 Oct 28  2021 cluster.crt
-rw-rw---- 1 root microk8s      3272 Oct 28  2021 cluster.key
-rw------- 1 root root            63 Dec 17 10:26 cluster.yaml
-rw-rw-r-- 1 root microk8s         2 Dec 17 10:24 failure-domain
-rw-rw---- 1 root microk8s        57 Oct 28  2021 info.yaml
srw-rw---- 1 root microk8s         0 Dec 17 10:25 kine.sock
-rw-rw---- 1 root microk8s        63 Dec 17 10:25 localnode.yaml
-rw-rw---- 1 root microk8s        32 Oct 28  2021 metadata1
-rw-rw---- 1 root microk8s   8388608 Dec 17 10:26 open-1
-rw-rw---- 1 root microk8s   8388608 Dec 17 10:25 open-2
-rw-rw---- 1 root microk8s   8388608 Dec 17 10:25 open-3
-rw-rw---- 1 root microk8s 685464138 Dec 17 09:37 snapshot-1-410172794-477745577
-rw-rw---- 1 root microk8s        72 Dec 17 09:37 snapshot-1-410172794-477745577.meta
-rw-rw---- 1 root microk8s 685930377 Dec 17 10:23 snapshot-1-410173818-480515547
-rw-rw---- 1 root microk8s        72 Dec 17 10:23 snapshot-1-410173818-480515547.meta

**Comment by neoaggelos** [comment]
> I get this error when I try to start dqlite ->
> root@capig:~# sudo snap start microk8s.daemon-k8s-dqlite
> error: snap "microk8s" has no service "daemon-k8s-dqlite"
> Am I missing something?

In 1.21 the datastore is running along with the rest of the Kubernetes services. This was moved to a separate service in 1.22, so the above would only be possible in 1.22+. The change was made due to situations like yours, where the kubernetes services compete to start along with the datastore, and eventually fail to start at all. I would imagine the size of the datastore is directly related here, @MathieuBordere can you confirm?

**Comment by MathieuBordere** [comment]
@neoaggelos I don't see anything suspicious wrt dqlite on first inspection. Datastore size also looks manageable.

**Comment by pinahar** [comment]
Upgraded to 1.22 but still not seeing a recovery.
Also, still see the same error - error: snap "microk8s" has no service "daemon-k8s-dqlite".

**Comment by ktsakalozos** [comment]
A small correction, dqlite was split out of kubelite in the 1.23 release so `sudo snap start microk8s.daemon-k8s-dqlite` would require a 1.23+ installation. However, you would better do a full stop/start of all the MicroK8s services with a `microk8s stop` and `microk8s start` instead of trying to get each service running one by one.

**Comment by pinahar** [comment]
I'm not trying to start and stop services individually. I did a full restart but it didn't help either.
