### ISSUE TITLE
Unable to acces Linkerd viz dashboard on Windows 11 Pro

### ISSUE THREAD

**Issue by amartincolby** [canonical/microk8s#3644]
#### Summary
Running Windows 11 Pro, I install Microk8s, enable Linkerd, run `microk8s linkerd viz dashboard` and cannot connect to the provided end points, specifically localhost:50750.

#### What Should Happen Instead?
I should be able to connect to and see the Linkerd dashboard.

#### Reproduction Steps
1. Install a fresh Microk8s on Windows 11 Pro
2. Enable Linkerd
3. run `microk8s linkerd viz dashboard`
4. Go to the generated endpoint and see the browser fail to connect.

#### Introspection Report
[inspection-report-20221228_134135.tar.gz](https://github.com/canonical/microk8s/files/10315876/inspection-report-20221228_134135.tar.gz)

#### Are you interested in contributing with a fix?
I would but have no idea how.

**Comment by ktsakalozos** [comment]
Hi @amartincolby, on windows (and mac) MicroK8s runs on a VM so what probably happens is the "localhost" on the generated endpoint refers to the VM. Could you try to point your browser to `<VM_IP>:50750`? You could also try to expose the dashboard manually on a nodeport.

**Comment by amartincolby** [comment]
I thought similarly. I already tried pointing it to the VM's IP but still no luck. I will try again now just to make sure...

And nope. It still fails to connect. But, as expected, when I `curl http://localhost:50750` from within the VM, it works.

**Comment by ktsakalozos** [comment]
If the service is exposed with `kubectl port-forward` it may be blocking requests coming from external IPs. `kubectl port-forward` had a `--address` argument you can set to `0.0.0.0` to allow all request sources, see for example https://github.com/canonical/microk8s/blob/master/scripts/wrappers/dashboard_proxy.py#L93

**Comment by amartincolby** [comment]
It appears that it is indeed exposed with `port-forward`. The mystery is why this worked in the past but does not work now. This article: [http://thinkmicroservices.com/blog/2021/service-mesh/service-mesh-linkerd-kubernetes.html](http://thinkmicroservices.com/blog/2021/service-mesh/service-mesh-linkerd-kubernetes.html) shows the command working. There was a change in Linkerd's [portforward.go](https://github.com/linkerd/linkerd2/blob/main/pkg/k8s/portforward.go) file around that time, but it did not touch any of the pertinent code.

And dammit. There is likely where the break happened. [On January 13th, 2021](https://github.com/linkerd/linkerd2/commits/15d1809bd043192bb21cacbc96112cce35bf384f/viz/cmd/dashboard.go), one day after that article published, they completely refactored viz commands. Checking the history seems to indicate that `defaultHost` was always hard-coded to `localhost`, so again, I do not understand how this ever worked inside of Microk8s.

I think I'm going to have to expose it.
