### ISSUE TITLE
Solution for this error: Microk8s is not running. Use microk8s inspect for a deeper inspection.  - When working with LXD/LXC

### ISSUE THREAD

**Issue by yalton-ruiz** [canonical/microk8s#3646]
#### Summary
After installation of MicroK8s on LXD/LXC container, MicroK8s responds with "MicroK8s is not running message"

#### What Should Happen Instead?
MicroK8s commands should be working.

#### Reproduction Steps

root@m1:~# snap install microk8s --classic 
microk8s (1.25/stable) v1.25.4 from Canonical✓ installed 
root@m1:~# microk8s version 
MicroK8s v1.25.4 revision 4221 
root@m1:~# microk8s status 
**microk8s is not running. Use microk8s inspect for a deeper inspection.** 

Solution:
MicroK8s requires some specific settings to work within LXD. This settings are loaded via LXC profile as described on the link below,
https://microk8s.io/docs/install-lxd

**Comment by yalton-ruiz** [comment]
Configuration settings on the link added https://microk8s.io/docs/install-lxd

**Comment by ktsakalozos** [comment]
We could improve the `microk8s inspect` script to detect that MicroK8s is on an lxc containers with the proper profile missing.

**Comment by berkayoz** [comment]
Closed by #3790
