### ISSUE TITLE
My dns and dashboard pods are CrashLooping, ufw commands didn't fix

### ISSUE THREAD

**Issue by gretchenfrage** [canonical/microk8s#3649]
#### Summary
Watching `microk8s kubectl get all --all-namespaces` shows services including hostpath-provisioner, dashboard, and dns getting into CrashLoopBackOff states repeatedly. hostpath-provisioner usually seems like the first to fail. As per [the troubleshooting guide](https://microk8s.io/docs/troubleshooting) I have run these commands:

```
sudo ufw allow in on vxlan.calico && sudo ufw allow out on vxlan.calico
sudo ufw allow in on cali+ && sudo ufw allow out on cali+
```

And rebooted, but the issue does not go away.

#### What Should Happen Instead?

`microk8s kubectl get all --all-namespaces` should eventually show all pods in the "Running" status with "READY" being "1/1".

#### Reproduction Steps

1. Turn on my computer
2. `watch microk8s kubectl get all --all-namespaces`
3. Various system pods start erroring and getting into CrashLoopBackOff status

For additional context, I am just trying to set up microk8s for the first time on a home server with a fresh install of Ubuntu server 20.04 LTS. The one thing I think might be problem-causing is that I have the partition I'm running in formatted to only 15 GB.

#### Introspection Report

[inspection-report-20230105_063544.tar.gz](https://github.com/canonical/microk8s/files/10349884/inspection-report-20230105_063544.tar.gz)

#### Are you interested in contributing with a fix?

No. I don't know what's going on sorry.

**Comment by ktsakalozos** [comment]
Hi @gretchenfrage looking at the logs I suspect there is something wrong with the network Kubernetes is trying to setup. Kubernetes sets up tow main networks: one for the services (10.152.183.0/24) and one for the pods (10.1.0.0/16). Is there anything blocking traffic on these networks? It is strange i do not see the right IPtable rules created.

**Comment by gretchenfrage** [comment]
@ktsakalozos I'm not aware of anything that would be doing that. I haven't intentionally set up some sort of firewall. The only things I've done related to the network I can think of are:

- Configurated a static LAN IP address with these commands:
  ```sh
  sudo nmcli con add con-name "static-ip" ifname enp1s0 type ethernet ip4 192.168.1.115/24 gw4 192.168.1.254
  nmcli con mod "static-ip" ipv4.dns "8.8.8.8,4.4.4.4"
  nmcli con mod "static-ip" ipv4.method manual
  nmcli con up "static-ip" ifname enp1s0
  ```
- Enabled the microk8s istio extension, and had to enable community repositories to do that
- Ran the ufw commands mentioned in the OP

**Comment by sunmerry** [comment]
@gretchenfrage  Is this resolved? I got the same problem.
