### ISSUE TITLE
`microk8s inspect` return no errors, but microk8s doesn't start

### ISSUE THREAD

**Issue by byjg** [canonical/microk8s#3656]
#### Summary
I successfully installed microk8s on a Raspberry Pi 4B with 8GB RAM and OS is Ubuntu 22.04, however after one day, microk8s stopped to work and is not starting. 

The apt package `linux-modules-extra-raspi` is already installed, and I added to the file `/boot/firmware/cmdline.txt` the following: `systemd.unified_cgroup_hierarchy=0 cgroup_enable=memory cgroup_memory=1`

#### What Should Happen Instead?
MicroK8s should start normally

#### Reproduction Steps

```
$ microk8s version

MicroK8s v1.23-11 revision 4432

$ microk8s status

microk8s is not running. Use microk8s inspect for a deeper inspection.

$ microk8s inspect

Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/4432/inspection-report-20230109_205821.tar.gz
```

#### Introspection Report
[inspection-report-20230109_205821.tar.gz](https://github.com/canonical/microk8s/files/10376821/inspection-report-20230109_205821.tar.gz)

#### Can you suggest a fix?
I can't see any possible solution. 

#### Are you interested in contributing with a fix?
If I know what is the cause, definitely would help with a fix.

**Comment by berkayoz** [comment]
Glad to hear your issue is resolved. 
I believe you can re-enable the addon as I couldn't reproduce any issues through refreshes with it enabled. 

For your question, the main difference is that `*-eksd` tracks use the [EKS-D](https://distro.eks.amazonaws.com/) from Amazon which has extra patches for Kubernetes and some images used in the cluster. It also has some extended support, compared to the vanilla Kubernetes. MicroK8s also does some AWS specific things like shipping the addons and some configurations to run those addons easier. Please also note that most of these addons require the cluster to be running on EC2 machines, since they are specific to the AWS cloud.

**Comment by berkayoz** [comment]
That's a great catch, normally addons do ask for elevated permissions at the start if needed. Seems like it is missing for the IAM addon. And as you mentioned, we also need to make sure the directory is created the same way across control plane nodes. We'll get this bug into the backlog and fix it. For now you can get around by creating the directory on the nodes and the setting permissions manually. 

Thank you.
