### ISSUE TITLE
Custom add-on shows on master node but not on the worker nodes in the cluster

### ISSUE THREAD

**Issue by byjg** [canonical/microk8s#3659]
#### Summary
I created a custom add-on and installed it in a new folder on `/var/snap/microk8s/common/addons/` in the master node. 
I am able to enable and disabled it, and I can confirm that when is enabled, the addon is working as expected. 

When I run `microk8s status` on master node, I can see:

```
microk8s is running
high-availability: no
  datastore master nodes: 192.168.1.249:19001
  datastore standby nodes: none
addons:
  enabled:
    easyhaproxy          # (byjg) EasyHAProxy can detect and configure HAProxy automatically based on ingress labels
    parking              # (byjg) Static webserver to park a domain. Requires EasyHAProxy.
    ...
```

However, If I run `microk8s status` command in any other node, it doesn't show neither as enabled nor disabled even my addon is installed and working. 

#### What Should Happen Instead?
I'd expect to see the add-on listed in any node, and not only where I installed the addon source code. 

#### Reproduction Steps

1. SSH into the master node.
2. Run the command below to install the new addon repository:

```
git clone https://github.com/byjg/microk8s-addons.git /var/snap/microk8s/common/addons/byjg
```

3. enable the addon:

```
microk8s enable easyhaproxy
```

4. Check if the plugin is installed:

```
microk8s status
microk8s kubectl get all -n easyhaproxy
```

5. SSH into the other node
6. Try to check with `microk8s status` if we can see the plugin, but I can't. 

#### Introspection Report
It is not necessary to this issue. Microk8s version 1.23

#### Can you suggest a fix?
I noticed if I enable the community addon (`microk8s enable community`) I only can see the newly added addons on the node I enabled it. 

So, I don't know if that is, in fact, an issue, but a possible solution is to create a `core` addon to install other addons and replicate to the other nodes. 

Something like this:
```
microk8s enable repository <repo name> <http to tar.gz>
```

#### Are you interested in contributing with a fix?
Yes

**Comment by berkayoz** [comment]
Hey @byjg,
Great to see you working on addons.  

The addons and repositories listed are node specific, as there isn't a central hub for management. There are some addons which are enabled on node by node basis, and some that get deployed on the cluster. However this doesn't mean that the addon is not working, it is related to the cli being node specific instead of applying to the whole cluster. If there is an addon that makes changes on the host, it would need to be enabled on all nodes.
