### ISSUE TITLE
Kubectl permissions for Minio & MLFlow

### ISSUE THREAD

**Issue by andreeamun** [canonical/microk8s#3671]
#### Summary
Connection to the server localhost:8080 was refused after running ```kubectl apply -f permissions/allow-minio.yaml -n admin```

Error I get: The connection to the server localhost:8080 was refused - did you specify the right host or port?

I run on an AWS instance, where I deployed MicroK8s, Juju and Kubeflow.
#### What Should Happen Instead?

Instead, it would give access to Minio & MLFlow. 

#### Reproduction Steps

1. Yes

#### Introspection Report

![image](https://user-images.githubusercontent.com/77149394/212649860-fa4cd4ac-c960-4cd7-8781-3b1c22851f8e.png)

#### Can you suggest a fix?

No

**Comment by berkayoz** [comment]
Hey @andreeamun,

Could you try `sudo microk8s kubectl apply -f permissions/allow-minio.yaml -n admin`?

MicroK8s bundles the kubectl and the proper configurations as api server is running on a different port. You also won't need to use `sudo` if the user is in the `microk8s` group.

**Comment by andreeamun** [comment]
hello. 

Thank you for the help. I think the problem is with Minio actually. When running the command you suggested, I got ```error: the path "permissions/allow-minio.yaml" does not exist```

**Comment by berkayoz** [comment]
Seems like the file(`permissions/allow-minio.yaml`) that's trying to be applied is not there, could you make sure the working directory you are in is correct and contains this file?
