### ISSUE TITLE
Failed to create containerd container error

### ISSUE THREAD

**Issue by JJMoon** [canonical/microk8s#3687]
#### Summary
Failed to start deployment on AWS ubuntu EC2 instance, and Mac
I will test in k8s context and share the result.

#### What Should Happen Instead?
Pod should be ready.

#### Reproduction Steps
microk8s start
apply secret to pull image from ghcr.io
apply deployment => error

#### Introspection Report
 Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  21s               default-scheduler  Successfully assigned famdev/dashapi-84-4 to microk8s-vm
  Normal   Pulling    20s               kubelet            Pulling image "ghcr.io/nsinfranetiiot/dash-api@sha256:cfb0"
  Warning  Failed     17s               kubelet            Failed to pull image "ghcr.io/nsinfranetiiot/dash-api@sha256:cfb0": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/nsinfranetiiot/dash-api@sha256:cfb041a1": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown
  Warning  Failed     17s               kubelet            Error: ErrImagePull
  Normal   Pulled     6s (x2 over 17s)  kubelet            Container image "ghcr.io/nsinfranetiiot/dash-api@sha256:" already present on machine
  Warning  Failed     6s (x2 over 17s)  kubelet            Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:: failed to get stream processor for application/vnd.in-toto+json: no processor for media-type: unknown

#### Are you interested in contributing with a fix?
Yes

**Comment by sachinkumarsingh092** [comment]
Hi @JJMoon, looks like there is a conflict between the image and containerd. Can you provide additional logs from containerd?
```
journalctl -fu snap.microk8s.daemon-containerd
```
