### ISSUE TITLE
microk8s not starting on ubuntu22.04.1 on odroid sbc

### ISSUE THREAD

**Issue by AllardKrings** [canonical/microk8s#3693]
#### Summary
I have a brand new ODROID N2+ SBC (ARM64)
I installed UBUNTU on it.
I installed microk8s on it
microk8s refuses to run

#### What Should Happen Instead?
microk8s should run
#### Reproduction Steps

1. Install ubuntu 22.04.1
2. Install microk8s : sudo snap install microk8s --classic

#### Introspection Report
[inspection-report-20230125_094845.tar.gz](https://github.com/canonical/microk8s/files/10498139/inspection-report-20230125_094845.tar.gz)

#### Are you interested in contributing with a fix?
no

**Comment by neoaggelos** [comment]
Hi @AllardKrings

From the inspection report, I can see lots of message that look like this:

```
Jan 25 09:48:27 odroid microk8s.daemon-containerd[3432]: time="2023-01-25T09:48:27.166575670Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-node-ss4pg,Uid:0673a412-ebfd-4cd3-b7a3-f5f5c5870644,Namespace:kube-system,Attempt:1,} failed, error" error="failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: open /sys/fs/cgroup/kubepods/burstable/pod0673a412-ebfd-4cd3-b7a3-f5f5c5870644/96005811154644d4d9e30b42b1d1d914b344f7e617d2130aa94604e6d5f8f714/cpu.weight: no such file or directory: unknown"
```

Are cgroups enabled on the machine?

**Comment by AllardKrings** [comment]
I tried to do that, however the ubuntu version on odroid apparantly is
different from the one I use on raspberry pi.

I added the option but it seems the ubuntu kernel is too old (4.9)

I will switch now to another linux-brand until canonical has a decent
distribution for the odroid that supports microk8s :-(


Op wo 25 jan. 2023 om 15:54 schreef Angelos Kolaitis <
***@***.***>

**Comment by adubkov** [comment]
@neoaggelos 

Same thing happening with Orange Pi 5. I'm getting `cpu.weight: no such file or directory`. 
cgroups seem to be enabled:
```
$ findmnt -lo source,target,fstype,options -t cgroup,cgroup2
SOURCE  TARGET         FSTYPE  OPTIONS
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot
```

```
$ ls -1 /sys/fs/cgroup/
cgroup.controllers
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cpu.pressure
cpuset.cpus.effective
cpuset.mems.effective
cpu.stat
dev-hugepages.mount
dev-mqueue.mount
init.scope
io.pressure
io.stat
memory.pressure
memory.stat
proc-sys-fs-binfmt_misc.mount
sys-fs-fuse-connections.mount
sys-kernel-config.mount
sys-kernel-debug.mount
sys-kernel-tracing.mount
system.slice
user.slice
```

```
$ uname -a
Linux pi-03 5.10.110-orange-pi #1 SMP Sat Feb 25 03:45:09 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux
```

I was using this linux build: https://github.com/Joshua-Riek/ubuntu-orange-pi5

**Comment by neoaggelos** [comment]
Hi @adubkov

I'm not sure, I do not see a `cpu.weight` in the list. Could it be the particular cgroup implementation and/or systemd version and/or kernel version and/or architecture that does not support `cpu.weight`?

Can you refresh all system packages, reboot the OS and then test? I don't think there is much we can do from the MicroK8s side here.

**Comment by adubkov** [comment]
It was an issue with kernel parameters. Once I set to: 
```
cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"
```
it start working.
