### ISSUE TITLE
Connection failed. The joining node is already known to dqlite.

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [canonical/microk8s#3694]
#### Summary
If, joining a new node fails for any reason, the joining node gets added to .dqlite, and the cluster has to be fully shutdown to remediate.

#### What Should Happen Instead?
Either, `microk8s remove-node (broken ip)` should work, or there should be a less impactful way to remediate.

#### Reproduction Steps
Have not tried reproducing.

BUT, On a production cluster running 1.25, I provisioned a new server, added microk8s, and `microk8s add-node` followed by join.

I failed to specify the correct channel, so, the new node now running 1.26 failed to join the cluster. 

Not a problem, let me remove microk8s, and install the correct channel.

```
Contacting cluster at 10.100.5.100
Connection failed. The joining node (10.100.5.102) is already known to dqlite (504).
```

https://microk8s.io/docs/restore-quorum

Is supposedly the method needed to resolve this issue, however, this is highly impactful to workloads, as the entire cluster has to be shutdown.

#### Related Tickets

https://github.com/canonical/microk8s/issues/2212

#### A few more details

```
root@kube01:~/Kubernetes/namespaces/readymotorsports.net# cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
- Address: 10.100.5.105:19001
  ID: 3297041220608546238
  Role: 0
- Address: 10.100.5.100:19001
  ID: 6578832437747111275
  Role: 0
- Address: 10.100.5.106:19001
  ID: 16212301467739305109
  Role: 0
- Address: 10.100.5.102:19001
  ID: 17023170999447087085
  Role: 1
root@kube01:~/Kubernetes/namespaces/readymotorsports.net# microk8s remove-node 10.100.5.102
Error from server (NotFound): nodes "10.100.5.102" not found
Node 10.100.5.102 does not exist in Kubernetes.
root@kube01:~/Kubernetes/namespaces/readymotorsports.net# kubectl get node -o wide
NAME     STATUS   ROLES                  AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kube06   Ready    <none>                 83d    v1.25.5   10.100.5.106   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.8
kube01   Ready    control-plane,master   95d    v1.25.5   10.100.5.100   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.8
kube05   Ready    <none>                 108d   v1.25.5   10.100.5.105   <none>        Ubuntu 22.04.1 LTS   5.15.0-58-generic   containerd://1.6.8
```

**Comment by XtremeOwnageDotCom** [comment]
I will note,

Just changing the IP/hostname of the joining node, allows it to join.

```
root@kube04:~# microk8s join redacted
Contacting cluster at 10.100.5.100
Waiting for this node to finish joining the cluster. .. .. ..
root@kube04:~# kubectl get nodes
NAME     STATUS     ROLES                  AGE    VERSION
kube05   Ready      <none>                 108d   v1.25.5
kube06   Ready      <none>                 83d    v1.25.5
kube01   Ready      control-plane,master   95d    v1.25.5
kube04   NotReady   <none>                 6s     v1.25.6
root@kube04:~#
```

**Comment by adubkov** [comment]
I had similar problem. Simple `microk8s leave` and re-joining cluster did the trick for me.

**Comment by m-ocean-it** [comment]
same issue

**Comment by ktsakalozos** [comment]
You could also try to do a `microk8s remove-node <node-ip> --force` to make sure dqlite has removed this IP from the nodes it knows. We fail adding nodes with IPs dqlite already knows about so we do not risk corrupting the datastore.

**Comment by XtremeOwnageDotCom** [comment]
Guys-

I don't need a work-around. I have work-arounds!

This ticket, is so that hopefully somebody fixes the underlying issue causing this.

**Comment by sachinkumarsingh092** [comment]
Steps to reproduce after creating a 3 CP node cluster:
1. `microk8s leave` on one of the nodes.
2. `microk8s remove-node <IP>` on the same node (not the correct way to do remove-node)

After this, the node gets removed
```
# k get no
No resources found
```

But it still is not removed from `/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`. 
Doing a `microk8s remove-node <node-id> --force` from a different node resolves it.
