### ISSUE TITLE
DQLite goes crazy on 1.24

### ISSUE THREAD

**Issue by franco-martin** [canonical/microk8s#3706]
#### Summary

DQLite cluster is flooded with errors on my three node cluster backed by SSDs
`level=error msg="error while range on /registry/health : query (try: 0): context deadline exceeded"`

Servers are running in proxmox with 7GB of ram and 3 vcpus each, storage is backed by NVME storage on mk8s01 and mk8s02 and sata ssd on srv03

`/dev/mapper/dqlite--data-dqlite--data   20G  5.2G   14G  29% /var/snap/microk8s/4023/var/kubernetes/backend`

FIO output mk8s01

> iops-test-job: (groupid=0, jobs=4): err= 0: pid=38330: Sat Jan 28 00:54:16 2023
>   read: IOPS=36.6k, BW=143MiB/s (150MB/s)(16.8GiB/120124msec)
>     slat (usec): min=4, max=284526, avg=42.77, stdev=654.74
>     clat (usec): min=184, max=618809, avg=13795.91, stdev=26523.84
>      lat (usec): min=193, max=636590, avg=13839.12, stdev=26621.66
>     clat percentiles (msec):
>      |  1.00th=[    3],  5.00th=[    4], 10.00th=[    5], 20.00th=[    7],
>      | 30.00th=[    8], 40.00th=[    9], 50.00th=[   10], 60.00th=[   12],
>      | 70.00th=[   14], 80.00th=[   16], 90.00th=[   19], 95.00th=[   25],
>      | 99.00th=[  161], 99.50th=[  230], 99.90th=[  338], 99.95th=[  376],
>      | 99.99th=[  456]
>    bw (  KiB/s): min= 5016, max=278704, per=100.00%, avg=147245.53, stdev=20622.76, samples=956
>    iops        : min= 1254, max=69676, avg=36811.17, stdev=5155.67, samples=956
>   write: IOPS=36.6k, BW=143MiB/s (150MB/s)(16.8GiB/120124msec); 0 zone resets
>     slat (usec): min=4, max=295007, avg=43.17, stdev=667.05
>     clat (usec): min=117, max=651809, avg=14069.45, stdev=31310.45
>      lat (usec): min=127, max=651816, avg=14113.09, stdev=31404.22
>     clat percentiles (msec):
>      |  1.00th=[    3],  5.00th=[    4], 10.00th=[    5], 20.00th=[    6],
>      | 30.00th=[    7], 40.00th=[    8], 50.00th=[    9], 60.00th=[   11],
>      | 70.00th=[   13], 80.00th=[   15], 90.00th=[   18], 95.00th=[   24],
>      | 99.00th=[  203], 99.50th=[  275], 99.90th=[  380], 99.95th=[  422],
>      | 99.99th=[  506]
>    bw (  KiB/s): min= 5408, max=280792, per=100.00%, avg=147146.53, stdev=20610.83, samples=956
>    iops        : min= 1352, max=70198, avg=36786.42, stdev=5152.69, samples=956
>   lat (usec)   : 250=0.01%, 500=0.01%, 750=0.01%, 1000=0.01%
>   lat (msec)   : 2=0.38%, 4=5.97%, 10=48.18%, 20=38.03%, 50=5.60%
>   lat (msec)   : 100=0.32%, 250=0.99%, 500=0.51%, 750=0.01%
>   cpu          : usr=5.69%, sys=13.65%, ctx=1441400, majf=0, minf=74
>   IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
>      submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
>      complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
>      issued rwts: total=4401134,4398216,0,0 short=0,0,0,0 dropped=0,0,0,0
>      latency   : target=0, window=0, percentile=100.00%, depth=256
> 
> Run status group 0 (all jobs):
>    READ: bw=143MiB/s (150MB/s), 143MiB/s-143MiB/s (150MB/s-150MB/s), io=16.8GiB (18.0GB), run=120124-120124msec
>   WRITE: bw=143MiB/s (150MB/s), 143MiB/s-143MiB/s (150MB/s-150MB/s), io=16.8GiB (18.0GB), run=120124-120124msec
> 
> Disk stats (read/write):
>     dm-3: ios=4400986/4398167, merge=0/0, ticks=35734204/35072756, in_queue=70806960, util=99.88%, aggrios=4399537/4396742, aggrmerge=1597/1567, aggrticks=35721680/35076065, aggrin_queue=70798431, aggrutil=99.83%
>   sdc: ios=4399537/4396742, merge=1597/1567, ticks=35721680/35076065, in_queue=70798431, util=99.83%

FIO Output mk8s02

> iops-test-job: (groupid=0, jobs=4): err= 0: pid=36655: Sat Jan 28 00:59:39 2023
>   read: IOPS=48.4k, BW=189MiB/s (198MB/s)(22.2GiB/120007msec)
>     slat (usec): min=4, max=66737, avg=31.12, stdev=302.83
>     clat (usec): min=184, max=125774, avg=10489.78, stdev=6366.18
>      lat (usec): min=194, max=125781, avg=10521.50, stdev=6382.55
>     clat percentiles (usec):
>      |  1.00th=[ 2999],  5.00th=[ 3654], 10.00th=[ 4113], 20.00th=[ 5145],
>      | 30.00th=[ 6652], 40.00th=[ 8160], 50.00th=[ 9503], 60.00th=[10945],
>      | 70.00th=[12518], 80.00th=[14222], 90.00th=[16909], 95.00th=[20841],
>      | 99.00th=[34341], 99.50th=[40633], 99.90th=[56361], 99.95th=[65274],
>      | 99.99th=[91751]
>    bw (  KiB/s): min=102927, max=335650, per=100.00%, avg=193882.28, stdev=9564.55, samples=956
>    iops        : min=25731, max=83912, avg=48470.03, stdev=2391.15, samples=956
>   write: IOPS=48.4k, BW=189MiB/s (198MB/s)(22.2GiB/120007msec); 0 zone resets
>     slat (usec): min=4, max=68640, avg=32.27, stdev=310.03
>     clat (usec): min=174, max=125153, avg=10591.80, stdev=6511.99
>      lat (usec): min=185, max=125159, avg=10624.66, stdev=6528.54
>     clat percentiles (usec):
>      |  1.00th=[ 3130],  5.00th=[ 3687], 10.00th=[ 4178], 20.00th=[ 5080],
>      | 30.00th=[ 6718], 40.00th=[ 8225], 50.00th=[ 9503], 60.00th=[11076],
>      | 70.00th=[12649], 80.00th=[14353], 90.00th=[16909], 95.00th=[21103],
>      | 99.00th=[35390], 99.50th=[41681], 99.90th=[57410], 99.95th=[66847],
>      | 99.99th=[94897]
>    bw (  KiB/s): min=102005, max=331725, per=100.00%, avg=193763.91, stdev=9585.35, samples=956
>    iops        : min=25500, max=82931, avg=48440.44, stdev=2396.35, samples=956
>   lat (usec)   : 250=0.01%, 500=0.01%, 750=0.01%, 1000=0.01%
>   lat (msec)   : 2=0.02%, 4=8.37%, 10=44.95%, 20=40.89%, 50=5.55%
>   lat (msec)   : 100=0.20%, 250=0.01%
>   cpu          : usr=9.02%, sys=17.87%, ctx=1251068, majf=0, minf=71
>   IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
>      submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
>      complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
>      issued rwts: total=5811019,5807254,0,0 short=0,0,0,0 dropped=0,0,0,0
>      latency   : target=0, window=0, percentile=100.00%, depth=256
> 
> Run status group 0 (all jobs):
>    READ: bw=189MiB/s (198MB/s), 189MiB/s-189MiB/s (198MB/s-198MB/s), io=22.2GiB (23.8GB), run=120007-120007msec
>   WRITE: bw=189MiB/s (198MB/s), 189MiB/s-189MiB/s (198MB/s-198MB/s), io=22.2GiB (23.8GB), run=120007-120007msec
> 
> Disk stats (read/write):
>     dm-0: ios=5810608/5806913, merge=0/0, ticks=18874924/16434712, in_queue=35309636, util=100.00%, aggrios=5808620/5805038, aggrmerge=2399/2309, aggrticks=18862059/16406827, aggrin_queue=35269141, aggrutil=99.96%
>   sdb: ios=5808620/5805038, merge=2399/2309, ticks=18862059/16406827, in_queue=35269141, util=99.96%

#### What Should Happen Instead?

It should not be having issues

#### Introspection Report

[inspection-report-20230128_011330.tar.gz](https://github.com/canonical/microk8s/files/10524230/inspection-report-20230128_011330.tar.gz)
#### Are you interested in contributing with a fix?

No

**Comment by ktsakalozos** [comment]
Hi @franco-martin, I see that the disk I/O is too high and also that dqlite is failing to reply to a number of queries. I also see that we are hitting swap. I am not sure if this behavior is solely of dqlite. It would help if we had the inspection report of the other two nodes. Do you have prometheus running? Could we look at the requests per sec of the API server and the observed latency?

@MathieuBordere any ideas on this?

**Comment by franco-martin** [comment]
I can get you three new inspection reports in a couple of minutes, I dont have prometheus running. Swap is supposed to be disabled and memory is at 60%. Im gonna double check just in case

**Comment by franco-martin** [comment]
While I get the inspection reports, here is the memory usage:
mk8s01
```
Jan 30 20:22:45 mk8s01 microk8s.daemon-k8s-dqlite[931]: time="2023-01-30T20:22:45Z" level=error msg="error while range on /registry/health : query (try: 0): context deadline exceeded"
franco@mk8s01:~$ free -m
               total        used        free      shared  buff/cache   available
Mem:            6941        3430        1747           1        1764        3310
Swap:              0           0           0

```

mk8s02
```
nge on /registry/health : query (try: 0): context deadline exceeded"
Jan 30 20:22:39 mk8s02 microk8s.daemon-k8s-dqlite[988]: time="2023-01-30T20:22:39Z" level=error msg="error in txn: query (try: 0): context deadline exceeded"
franco@mk8s02:~$ free -m
               total        used        free      shared  buff/cache   available
Mem:            6941        2874        2101           1        1964        3835
Swap:              0           0           0
```

**Comment by franco-martin** [comment]
Here are fresh inspection reports.
[mk8s02.tar.gz](https://github.com/canonical/microk8s/files/10539824/mk8s02.tar.gz)
[mk8s01.tar.gz](https://github.com/canonical/microk8s/files/10539825/mk8s01.tar.gz)
[srv03.tar.gz](https://github.com/canonical/microk8s/files/10539826/srv03.tar.gz)
I also have the output of "iotop -Pao"
Looks like systemd-journald is writing a lot too, I assume because of the failures. Kubelite seems to be in trace mode, which causes a lot of IO.
```
    341 be/3 root          0.00 B     36.00 K  ?unavailable?  [jbd2/dm-1-8]
    413 be/3 root          0.00 B    712.00 K  ?unavailable?  systemd-journald
    721 be/3 root          0.00 B     32.00 K  ?unavailable?  [jbd2/dm-2-8]
    730 be/3 root          0.00 B     76.00 K  ?unavailable?  [jbd2/dm-0-8]
    906 be/4 syslog        0.00 B     32.00 K  ?unavailable?  rsyslogd -n -iNONE
    931 be/4 root          0.00 B    196.00 K  ?unavailable?  k8s-dqlite --storage-dir=/~es/backend/kine.sock:12379
   1001 be/4 root          0.00 B      8.00 K  ?unavailable?  glusterfs --process-name f~volfi

```
Here's the output of journalctl -fu snap.microk8s.daemon-kubelite
```
Jan 30 20:40:49 mk8s01 microk8s.daemon-kubelite[11325]: Trace[752451130]: ---"About to write a response" 663ms (20:40:49.133)
Jan 30 20:40:49 mk8s01 microk8s.daemon-kubelite[11325]: Trace[752451130]: [664.006295ms] [664.006295ms] END
Jan 30 20:40:49 mk8s01 microk8s.daemon-kubelite[11325]: I0130 20:40:49.649181   11325 trace.go:205] Trace[1876658121]: "Get" url:/apis/rbac.authorization.k8s.io/v1/clusterroles/system:service-account-issuer-discovery,user-agent:kubelite/v1.24.8 (linux/amd64) kubernetes/1dda18a,audit-id:b9a76a5f-d800-4b31-8f34-37cd19ed10ad,client:::1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (30-Jan-2023 20:40:49.135) (total time: 513ms):
Jan 30 20:40:49 mk8s01 microk8s.daemon-kubelite[11325]: Trace[1876658121]: ---"About to write a response" 513ms (20:40:49.649)
Jan 30 20:40:49 mk8s01 microk8s.daemon-kubelite[11325]: Trace[1876658121]: [513.726996ms] [513.726996ms] END
```

**Comment by franco-martin** [comment]
I managed to reduce disk io by moving journald to volatile storage according to https://github.com/canonical/microk8s/issues/2580
and the number of "context deadline exceeded" messages is reduced but still there

**Comment by franco-martin** [comment]
My workaround was to bring everything down, uninstall microk8s on all nodes, install it again and restore from backup. Fortunately I have daily backups.
Now I dont have any messages in the dqlite error logs nor in kubelite.

**Comment by franco-martin** [comment]
More metrics:
- APIServer has 2 requests per second now that the cluster is cordoned
- APIServer usually has 15-20 rps and response times are like 3s (not ms)

**Comment by franco-martin** [comment]
Other things im investigating:
- API Server randomly throwing some ` Failed to connect to 10.152.183.1 port 443 after 3053 ms: No route to host` error. Looks like the kubernetes' api endpoints show a host that should not be there. This brings me all kinds of errors for scheduling pods.
