### ISSUE TITLE
Joining a cluster as a worker node from certain distributions throws an error

### ISSUE THREAD

**Issue by amsal** [canonical/microk8s#3715]
#### Summary
Joining cluster as a worker node fails on some distros like Centos / Alma Linux / Oracle Linux due to invalid `openssl.cnf` path. This error occurs because when joining a node to cluster, MicroK8s looks for `openssl.cnf` from `/usr/lib/ssl/openssl.cnf` which does not exist on these distributions.

```
microk8s join 192.168.1.230:25000/92b2db237428470dc4fcfc4ebbd9dc81/2c0cb3284b05 --worker
```

```
Contacting cluster at 192.168.1.230
Traceback (most recent call last):
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 981, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/4390/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/4390/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/4390/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/4390/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 974, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 766, in join_dqlite
    join_dqlite_worker_node(info, master_ip, master_port, token)
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 834, in join_dqlite_worker_node
    update_cert_auth_kubeproxy(token, info["ca"], master_ip, master_port, hostname_override)
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 427, in update_cert_auth_kubeproxy
    cert = get_client_cert(master_ip, master_port, "kube-proxy", proxy_token, "system:kube-proxy")
  File "/snap/microk8s/4390/scripts/wrappers/join.py", line 281, in get_client_cert
    subprocess.check_call(cmd_cert.split(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/snap/microk8s/4390/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/4390/usr/bin/openssl', 'req', '-new', '-sha256', '-key', '/var/snap/microk8s/current/certs/kube-proxy.key', '-out', '/var/snap/microk8s/current/certs/kube-proxy.csr', '-subj', '/CN=system:kube-proxy']' returned non-zero exit status 1.
```

#### What Should Happen Instead?
Join python script should load the openssl.cnf file from `$SNAP/etc/ssl/openssl.cnf` and there should be no error when joining a node to cluster.

#### Reproduction Steps

1. Install microk8s (channel 1.26) on two machines/vms both running Oracle Linux / Alma Linux / Centos (k8node1, k8node2)
2. Enable dns addon on both nodes
3. Run `microk8s add-node` on k8node1 to get instructions
4. Join to k8node1 from k8node2 as a worker (with --worker flag)
5. Join script on k8node2 throws an error

#### Can you suggest a fix?

Set the correct `openssl.cnf` path by setting `OPENSSL_CONF` environment variable in https://github.com/canonical/microk8s/blob/5b8c4ef88f1c6281b548eefc1756a8472f9e26c9/microk8s-resources/wrappers/microk8s-join.wrapper

e.g. Add to L11 in `microk8s-resources/wrappers/microk8s-join.wrapper`

```bash
export OPENSSL_CONF="$SNAP/etc/ssl/openssl.cnf"
```

#### Are you interested in contributing with a fix?
yes

**Comment by neoaggelos** [comment]
Hi @amsal, thanks for bringing this up. I believe we have seen this in the past, can you see whether the suggestions in https://github.com/canonical/microk8s/issues/3611#issuecomment-1338891237 and the issue above solve your problems?

We should probably look into fixing this properly on the MicroK8s side.

**Comment by amsal** [comment]
Hello,

Thanks for the suggestion. I used an alternative method to resolve this issue on my side.

```
sudo mkdir -p /usr/lib/ssl/
sudo cp /snap/microk8s/current/etc/ssl/openssl.cnf /usr/lib/ssl/
``` 

Copying the openssl.cnf from MicroK8s path to the default openssl path allowed me to join node successfully.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @amsal and for offering a solution to it. Would you interested in adding the openssl configuration in the `microk8s-join.wrapper` very similar as we do in [1]? Let us know if you need any assistance on how to build the snap.

Thank you again.

[1] https://github.com/canonical/microk8s/blob/5b8c4ef88f1c6281b548eefc1756a8472f9e26c9/microk8s-resources/wrappers/microk8s-add-node.wrapper#L8

**Comment by amsal** [comment]
Hi, I have now created the pull request.

Thanks
