### ISSUE TITLE
microk8s  ha on centos9  issues with auto adding route - ClusterIP is not working as expected 

### ISSUE THREAD

**Issue by rahulrnair21** [canonical/microk8s#3718]
#### Summary

I did setup a microk8s ha setup on centos9(on Vmware Esxi ) using snap and the status show ha is available 

microk8s is running
high-availability: yes
  datastore master nodes: 192.168.5.103:19001 192.168.5.104:19001 192.168.5.105:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
  disabled:
    cert-manager         # (core) Cloud native certificate management
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    kube-ovn             # (core) An advanced network fabric for Kubernetes
    mayastor             # (core) OpenEBS MayaStor
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    minio                # (core) MinIO object storage
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
    rbac                 # (core) Role-Based Access Control for authorisation
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated

I did a simple deployment of nginx with a service as ClusterIP, to my surprise, noticed that the ClusterIP cannot  be accessed from all of my nodes .  

[root@k8sdev02 ~]# kubectl get no -o wide 
NAME           STATUS   ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION          CONTAINER-RUNTIME
k8sdev03  Ready    <none>   27h   v1.26.0   192.168.5.104   <none>        CentOS Stream 9   5.14.0-239.el9.x86_64   containerd://1.6.8
k8sdev02   Ready    <none>   27h   v1.26.0   192.168.5.103   <none>        CentOS Stream 9   5.14.0-239.el9.x86_64   containerd://1.6.8
k8sdev04   Ready    <none>   27h   v1.26.0   192.168.5.105   <none>        CentOS Stream 9   5.14.0-239.el9.x86_64   containerd://1.6.8

[root@k8sdev02 ~]# kubectl get all -o wide 
NAME                       READY   STATUS    RESTARTS   AGE     IP             NODE           NOMINATED NODE   READINESS GATES
pod/test-cbb664644-gtk8n   1/1     Running   0          4h22m   10.1.145.133   k8sdev02.way   <none>           <none>
pod/test-cbb664644-khvvn   1/1     Running   0          4h22m   10.1.99.198    k8sdev04.way   <none>           <none>
pod/test-cbb664644-qnfp5   1/1     Running   0          4h22m   10.1.105.135   k8sdev03.way   <none>           <none>

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE     SELECTOR
service/kubernetes   ClusterIP   10.152.183.1     <none>        443/TCP   27h     <none>
service/testsvc      ClusterIP   10.152.183.194   <none>        80/TCP    4h22m   app=test,type=service

NAME                   READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS   IMAGES         SELECTOR
deployment.apps/test   3/3     3            3           4h22m   test         nginx:latest   app=test,type=service

NAME                             DESIRED   CURRENT   READY   AGE     CONTAINERS   IMAGES         SELECTOR
replicaset.apps/test-cbb664644   3         3         3       4h22m   test         nginx:latest   app=test,pod-template-hash=cbb664644,type=service

[root@k8sdev02 ~]# kubectl describe svc testsvc 
Name:              testsvc
Namespace:         default
Labels:            app=testsvc
Annotations:       <none>
Selector:          app=test,type=service
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.152.183.194
IPs:               10.152.183.194
Port:              tcp-80-80  80/TCP
TargetPort:        80/TCP
Endpoints:         10.1.105.135:80,10.1.145.133:80,10.1.99.198:80
Session Affinity:  None
Events:            <none

So if i do a curl to clusterIp ie  10.152.183.194 in my case , it sometimes gives the nginx page  but  most of the time it timed out 

On further analysis noticed the pod  which is running on the same node  form which curl command is running is working file , while others will timed out 

For ex , i am running curl form k8sdev02

[root@k8sdev02 ~]# curl  10.1.145.133 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

While the below two timed out 

[root@k8sdev02 ~]# curl  10.1.105.135

[root@k8sdev02 ~]# curl 10.1.99.198 

PS - i don't have any firewall setup , each node can access each other on all ports 
#### What Should Happen Instead?

curl ClusterIP should give the nginx page which is expected 

#### Reproduction Steps

1. Install microk8s as ha on 3 centos 9  
2. Do a simple nginx deployment and try to access it using curl ClusterIP form all nodes , you will see that some times  i will work and some time it won't

**Comment by neoaggelos** [comment]
Hi @rahulrnair21, given that traffic from pods cannot reach other nodes, can you still check whether there are any iptables or firewall-cmd rules that might be blocking the traffic?

Secondly, can you check whether this is an issue with Calico dropping packets due to checksum calculations? Please try to run the command below, and see if it has any effect.

```
sudo microk8s kubectl patch felixconfigurations default --patch '{"spec":{"featureDetectOverride":"ChecksumOffloadBroken=true"}}' --type=merge
```

Thanks!

**Comment by rahulrnair21** [comment]
@neoaggelos  - There are not firewalls blocking in my case . I have disabled it at first before installing the mircok8s .

Looks like the issue seems to be with calico , what i did initially was downloading the calico.yml from their website and re run it on microk8s  which solved the issue 

curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml -O && kubectl apply -f calico.yml 

But up on restart some of the pods on kube-system went to unknown state . 

I edited the file on /var/snap/microk8s/current/args/cni-network/cni.yaml  and changed the following 

 image: docker.io/calico/cni:v3.25.0
image: docker.io/calico/node:v3.25.0
image: docker.io/calico/node:v3.25.0
image: docker.io/calico/kube-controllers:v3.25.0

and  applied the yaml file . Which seems to be working . 

Not sure if this is a right approach .

**Comment by rahulrnair21** [comment]
@neoaggelos  I have applied the patch you suggested and it working . Please see my snippet below, so it seems to be  Calico dropping packets due to checksum calculations

[root@k8sdev02 ~]# kubectl get all -o wide -A
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE     IP              NODE           NOMINATED NODE   READINESS GATES
kube-system   pod/calico-node-vq5ls                          1/1     Running   0          3m27s   192.168.5.104   k8sdev03.way   <none>           <none>
kube-system   pod/calico-node-w8zcc                          1/1     Running   0          4m22s   192.168.5.103   k8sdev02.way   <none>           <none>
kube-system   pod/coredns-6f5f9b5d74-s24jw                   1/1     Running   0          71s     10.1.99.193     k8sdev04.way   <none>           <none>
kube-system   pod/calico-node-gzs85                          1/1     Running   0          3m29s   192.168.5.105   k8sdev04.way   <none>           <none>
kube-system   pod/calico-kube-controllers-5c5cc98dfb-b7gch   1/1     Running   0          5m17s   10.1.145.129    k8sdev02.way   <none>           <none>

NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  5m23s   <none>
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   71s     k8s-app=kube-dns

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE     CONTAINERS    IMAGES                          SELECTOR
kube-system   daemonset.apps/calico-node   3         3         3       3            3           kubernetes.io/os=linux   5m23s   calico-node   docker.io/calico/node:v3.23.5   k8s-app=calico-node

NAMESPACE     NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS                IMAGES                                      SELECTOR
kube-system   deployment.apps/calico-kube-controllers   1/1     1            1           5m23s   calico-kube-controllers   docker.io/calico/kube-controllers:v3.23.5   k8s-app=calico-kube-controllers
kube-system   deployment.apps/coredns                   1/1     1            1           71s     coredns                   coredns/coredns:1.9.3                       k8s-app=kube-dns

NAMESPACE     NAME                                                 DESIRED   CURRENT   READY   AGE     CONTAINERS                IMAGES                                      SELECTOR
kube-system   replicaset.apps/calico-kube-controllers-79568db7f8   0         0         0       5m18s   calico-kube-controllers   docker.io/calico/kube-controllers:v3.23.5   k8s-app=calico-kube-controllers,pod-template-hash=79568db7f8
kube-system   replicaset.apps/calico-kube-controllers-5c5cc98dfb   1         1         1       5m17s   calico-kube-controllers   docker.io/calico/kube-controllers:v3.23.5   k8s-app=calico-kube-controllers,pod-template-hash=5c5cc98dfb
kube-system   replicaset.apps/coredns-6f5f9b5d74                   1         1         1       71s     coredns                   coredns/coredns:1.9.3                       k8s-app=kube-dns,pod-template-hash=6f5f9b5d74
[root@k8sdev02 ~]# kubectl apply -f test.yml 
anaconda-ks.cfg           .bash_profile             calico.yaml_bak           installmk8s.sh            purgemk8s.sh              .ssh/                     
.bash_history             .bashrc                   cni.yaml                  .kube/                    remove_termintaingpod.sh  .tcshrc                   
.bash_logout              calico.yaml               .cshrc                    .lesshst                  snap/                     test.yml                  
[root@k8sdev02 ~]# kubectl apply -f test.yml 
deployment.apps/test created
service/test created
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# kubectl get all -o wide 
NAME                       READY   STATUS    RESTARTS   AGE   IP             NODE           NOMINATED NODE   READINESS GATES
pod/test-cbb664644-vkl2q   1/1     Running   0          6s    10.1.145.130   k8sdev02.way   <none>           <none>
pod/test-cbb664644-slxmx   1/1     Running   0          6s    10.1.99.194    k8sdev04.way   <none>           <none>
pod/test-cbb664644-rw8j9   1/1     Running   0          6s    10.1.105.129   k8sdev03.way   <none>           <none>

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE     SELECTOR
service/kubernetes   ClusterIP   10.152.183.1     <none>        443/TCP   5m44s   <none>
service/test         ClusterIP   10.152.183.243   <none>        80/TCP    6s      app=test,type=service

NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
deployment.apps/test   3/3     3            3           6s    test         nginx:latest   app=test,type=service

NAME                             DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES         SELECTOR
replicaset.apps/test-cbb664644   3         3         3       6s    test         nginx:latest   app=test,pod-template-hash=cbb664644,type=service
[root@k8sdev02 ~]# curl 10.1.105.129 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@k8sdev02 ~]# curl 10.1.99.194 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@k8sdev02 ~]# curl 10.1.145.130 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@k8sdev02 ~]# curl 10.152.183.243 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# 
[root@k8sdev02 ~]# curl 10.152.183.243 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>



Thank you !!!

**Comment by neoaggelos** [comment]
Good to see that this was resolved. MicroK8s typically applies this by default, but we recently found a bug and #3705 fixes it on latest master.

We will proceed with backporting the fix to all stable releases. Thanks for reporting!

**Comment by neoaggelos** [comment]
came here by stale bot, #3705 is merged and the issue should be resolved.
