### ISSUE TITLE
microk8s >v1.24 fails to start on after install on Ubuntu 20.04 LTS with non-default MTU 

### ISSUE THREAD

**Issue by gheist** [canonical/microk8s#3729]
#### Summary
Micrkok8s >v1.24  fails to install on microk8s @ Ubuntu 20.04 LTS due to CNI initialization error
cni config load failed: no network config found in /var/snap/microk8s/4390/args/cni-network: cni plugin not initialized: failed to load cni config
The system is VM-based, uses 1450 MTU on eth0. microk8s v1.24 installs and initializes fine.
The installation is per documentation: 
# snap install microk8s --classic --channel=1.26

#### What Should Happen Instead?
1. microk8s status should show that microk8s is running 
2. microk8s kubectl get pods --all-namespaces should show properly initialized calico containers 
#### Reproduction Steps
Consistently reproduced in multiple VMs in same setup 

#### Introspection Report
[inspection-report-20230203_180819.tar.gz](https://github.com/canonical/microk8s/files/10581588/inspection-report-20230203_180819.tar.gz)

**Comment by neoaggelos** [comment]
Sorry for missing this issue, got here from stalebot, but this is probably resolved with #4142.

Please re-open if the issue still persists, thanks!
