### ISSUE TITLE
MicroK8S unable to deploy CoreDNS on a Raspberry Pi 4 (Raspbian)

### ISSUE THREAD

**Issue by GBT55** [canonical/microk8s#3734]
Hello,

After performing the steps in this thread https://github.com/canonical/microk8s/issues/2454 I finally got my MicroK8S stable. Now I want to deploy the dns addon ```microk8s enable dns`` but the CoreDNS pods are constantly crashing with the following error (image also to provide context):
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/kubepods/burstable/pod1287a9e5-81b5-4a75-89f1-f39a520e32a1/coredns/memory.max: no such file or directory: unknown
```
![image](https://user-images.githubusercontent.com/76950842/217006878-9a296b39-ae92-4798-a0f6-b87fffd0c56c.png)

I've tried the following:
- Restart MicroK8S
- Append ```cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1``` to _/boot/firmware/nobtcmd.txt_, _/boot/firmware/cmdline.txt_ and _/boot/cmdline.txt_

[inspection-report-20230206_161349.tar.gz](https://github.com/canonical/microk8s/files/10664492/inspection-report-20230206_161349.tar.gz)

**Comment by neoaggelos** [comment]
Hi @GBT55, I see this issue in the containerd logs (mirroring the error message you see with kubectl), which would hint that cgroupsv2 is not really available on the system in an unexpected way?

```
feb 06 12:09:27 raspberrypi microk8s.daemon-containerd[3037292]: time="2023-02-06T12:09:27.571558950+01:00" level=warning msg="error from *cgroupsv2.Manager.EventChan" error="failed to add inotify watch for \"/sys/fs/cgroup/kubepods/besteffort/podc1540cc4-a2d1-404b-b7b8-aab61ac9fccd/747b781200a9e79e5aa459a407c9d201374006e18cd46f74e869dd1e6a83cacf/memory.events\": no such file or directory"
```

Can you test whether using cgroupsv1 solves your issue? Please try:

```
# use cgroupsv1
sudo sed -i 's,${RUNTIME_TYPE},io.containerd.runc.v1,' /var/snap/microk8s/current/args/containerd-template.toml
sudo snap restart microk8s.daemon-containerd

# delete all pods to force recreate containers
sudo microk8s kubectl delete pod --all -A
```

Can you also share the output of the following command from your machine? Thanks a lot

```
mount | grep cgroup
```

**Comment by GBT55** [comment]
Hi @neoaggelos, thank you for the quick response.

I tried this one and the error still remains, in fact I dont think the sed command is doing anything.
> Can you test whether using cgroupsv1 solves your issue? Please try: 
> ```
> # use cgroupsv1
> sudo sed -i 's,${RUNTIME_TYPE},io.containerd.runc.v1,' /var/snap/microk8s/current/args/containerd-template.toml
> sudo snap restart microk8s.daemon-containerd
> 
> # delete all pods to force recreate containers
> sudo microk8s kubectl delete pod --all -A
> ```

There you go
```
root@raspberrypi:~# mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
root@raspberrypi:~#
```
> Can you also share the output of the following command from your machine? Thanks a lot
> 
> ```
> mount | grep cgroup
> ```

**Comment by neoaggelos** [comment]
Hi @GBT55

Can you check the contents of `/var/snap/microk8s/current/args/containerd-template.toml` for instances of `${RUNTIME_TYPE}` and `io.containerd.runc.v1`? Can you ensure that they are replaced with `io.containerd.runc.v2` instead and restart containerd? This is what the sed command above should have done (but configure containerd to use cgroupv1 instead).

After restarting, again ensure that you delete all pods so that containerd restarts the shims with v2:

```
sudo microk8s kubectl delete pod --all -A
```

**Comment by bhwarren** [comment]
I was facing what may be a related issue with coredns not starting. Raspberry pi 4, 64bit, OS completely up to date.

```
58s         Warning   Failed                   pod/coredns-64c6478b6c-47z7s          Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubepods/burstable/pod5cb3542a-4888-4094-942e-e13f7de62c81/coredns/memory.max: no such file or directory: unknown  
```

The sed command to use cgroups v1 didn't work, but when I followed @neoaggelos suggestion to replace the line with v2, restart containerd, and delete the offending pod, it stayed up!

Not sure if this detail has anything to do with it either, but I did add the following to /boot/cmdline.txt and rebooted prior to it starting to work.

``` cgroup_enable=memory swapaccount=1 cgroup_memory=1 cgroup_enable=cpuset```

**Comment by GBT55** [comment]
Hi, @neoaggelos 
I have replaced all instances of `io.containerd.runc.v1` with `io.containerd.runc.v2`.
By the way there are no lines containing `${RUNTIME_TYPE}` in my `/var/snap/microk8s/current/args/containerd-template.toml` file.

<br>

I then restarted and the problem persists, I also added that line to `/boot/cmdline.txt` as @bhwarren suggested, but unfortunately it didn't do the workaround as it did for you.
> Not sure if this detail has anything to do with it either, but I did add the following to /boot/cmdline.txt and rebooted prior to it starting to work.
> 
> ` cgroup_enable=memory swapaccount=1 cgroup_memory=1 cgroup_enable=cpuset`

**Comment by neoaggelos** [comment]
> By the way there are no lines containing ${RUNTIME_TYPE} in my /var/snap/microk8s/current/args/containerd-template.toml file.

Yup, this is because of the `sed` command you run previously. For some background, microk8s will attempt to pick cgroups2 (if available on the host) and otherwise fallback to v1.

How did you restart? Can you attempt a fresh install like this:

```
sudo snap remove microk8s --purge
sudo reboot
sudo snap install microk8s --classic
```

**Comment by GBT55** [comment]
Hi @neoaggelos, still no luck… I've tried reinstalling as you said, I've rebooted a few times, and I've tried with `io.containerd.runc.v2` and also with the `${RUNTIME_TYPE}` variable. None of them have been successful, it keeps showing the same error:
```bash
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: openat2 /sys/fs/cgroup/kubepods/burstable/pod847514fc-ae4c-4345-a538-cc7ea6445b4f/coredns/memory.max: no such file or directory: unknown
```

**Comment by neoaggelos** [comment]
Hi @GBT55 can you check whether setting any of the following on the cmdline.txt helps?

```
# disable cgroupv1 altogether
cgroup_no_v1=all

# use cgroupv2 for systemd
systemd.unified_cgroup_hierarchy=1

# disable hybrid cgroupv1
systemd.legacy_systemd_cgroup_controller=0

```

**Comment by GBT55** [comment]
Hi, I appreciate the help, but I'm sorry to say… no luck yet. Maybe it's something on my side, but I don't know what it is.

**Comment by neoaggelos** [comment]
Looking at similar issues in other projects, could it be that it is related to the kernel/systemd version you are running? Have you installed the latest system package updates?

**Comment by GBT55** [comment]
Hi @neoaggelos. I re-installed the O.S and it seems the issue has been fixed. From a clean install I was able to enable the cgroups and install microk8s, then it worked perfectly.

It was something on my side, you can close the issue.
