### ISSUE TITLE
microk8s enable rbac fails 

### ISSUE THREAD

**Issue by SchwingSK** [canonical/microk8s#3737]
I have a cluster of two Ubuntu 22 nodes & 2 Windows server 2022. 
When I try to enable rbac, I get the following output:

> Infer repository core for addon rbac
Enabling RBAC
Reconfiguring apiserver
Adding argument --authorization-mode to nodes.
Failed to reach node.
HTTPSConnectionPool(host='172.26.197.85', port=25000): Max retries exceeded with url: /cluster/api/v1.0/configure (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f54d5629668>: Failed to establish a new connection: [Errno 111] Connection refused',))

172.26.197.85 is the IP of one of the two Windows nodes.
[inspection-report-20230207_160135.tar.gz](https://github.com/canonical/microk8s/files/10676543/inspection-report-20230207_160135.tar.gz)

**Comment by neoaggelos** [comment]
Hi @SchwingSK, thank you for reporting this.

It seems like we should be more careful with how we select which K8s nodes the configuration should be applied at, we will have a look!

As a workaround, you can manually do the following on the two Ubuntu nodes:

```
echo '--authorization-mode=RBAC,Node' | sudo tee -a /var/snap/microk8s/current/args/kube-apiserver
sudo snap restart microk8s
```
