### ISSUE TITLE
microk8s don't work in wsl2

### ISSUE THREAD

**Issue by etoyz** [canonical/microk8s#3748]
#### Summary
microk8s don't work in wsl2(ubuntu18.04)

#### Reproduction Steps
1. [Enable systemd in wsl2](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/), which is disabled by default
2. sudo snap install microk8s --classic --channel=1.18/stable
3. sudo microk8s status
4. sudo microk8s inspect

#### Introspection Report

> Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
 FAIL:  Service snap.microk8s.daemon-containerd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-containerd
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
> 
> Building the report tarball
  Report tarball is at /var/snap/microk8s/2271/inspection-report-20230209_184027.tar.gz
[inspection-report-20230209_184027.tar.gz](https://github.com/canonical/microk8s/files/10696276/inspection-report-20230209_184027.tar.gz)

**Comment by sachinkumarsingh092** [comment]
Hey @etoyz, thanks for opening this.
I can see a lot of these deprecated flag errors in kubelet logs:
```
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: + exec /snap/microk8s/2271/kubelet --kubeconfig=/var/snap/microk8s/2271/credentials/kubelet.config --cert-dir=/var/snap/microk8s/2271/certs --client-ca-file=/var/snap/microk8s/2271/certs/ca.crt --anonymous-auth=false --network-plugin=cni --root-dir=/var/snap/microk8s/common/var/lib/kubelet --fail-swap-on=false --cni-conf-dir=/var/snap/microk8s/2271/args/cni-network/ --cni-bin-dir=/snap/microk8s/2271/opt/cni/bin/ --feature-gates=DevicePlugins=true '--eviction-hard=memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi' --container-runtime=remote --container-runtime-endpoint=/var/snap/microk8s/common/run/containerd.sock --containerd=/var/snap/microk8s/common/run/containerd.sock --node-labels=microk8s.io/cluster=true --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
Feb 09 17:54:24 ETOYZ microk8s.daemon-kubelet[5617]: Flag --kubelet-cgroups has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```
Can you also see this with the newer supported versions too? Also, is there any particular use case to use the unsupported 1.18/stable version?

**Comment by etoyz** [comment]
Hello, @sachinkumarsingh092 

####  When I install the latest version:
```
etoyz@ETOYZ:~$ sudo snap install microk8s --classic
error: cannot perform the following tasks:
- Start snap "microk8s" (4595) services (systemctl command [start snap.microk8s.daemon-containerd.service] failed with exit status 1: Job for snap.microk8s.daemon-containerd.service failed because the control process exited with error code.See "systemctl status snap.microk8s.daemon-containerd.service" and "journalctl -xe" for details.
)
etoyz@ETOYZ:~$ systemctl status snap.microk8s.daemon-containerd.service
Unit snap.microk8s.daemon-containerd.service could not be found.
etoyz@ETOYZ:~$ journalctl -xe >> a.txt
```
[a.txt](https://github.com/canonical/microk8s/files/10704993/a.txt)

**Comment by neoaggelos** [comment]
Hi @etoyz 

Looks like there is something listening in `127.0.0.1:1338` on your host, which is preventing containerd from starting. Is it possible to temporarily disable that, and retry the installation?

**Comment by etoyz** [comment]
> 

SOLVED! 
First, I use ‘netstat’ to check the listening ports, and find that no process is using port 1338. 
However, if I try to bind port 1338 by:
`python -m http.server 1338`
It show that port 1338 is in already use. 
Finally, I found that the port 1338 was designated as reserved by the Windows system, and I finally found a solution [here](https://stackoverflow.com/a/65234135/14783981).
