### ISSUE TITLE
microk8s.status shows "not running" while microk8s.inspect show "running"

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#375]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20190325_104142.tar.gz](https://github.com/ubuntu/microk8s/files/3001293/inspection-report-20190325_104142.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
```
$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-docker is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/437/inspection-report-20190325_104142.tar.gz
$ microk8s.status
microk8s is not running. Use microk8s.inspect for a deeper inspection.
```

**Comment by andrewcheny** [comment]
I have the same problem. Log file attached here.
[inspection-report-20190417_164310.tar.gz](https://github.com/ubuntu/microk8s/files/3091507/inspection-report-20190417_164310.tar.gz)

**Comment by msm-code** [comment]
I have the same problem:

```
$ microk8s.status
microk8s is not running. Use microk8s.inspect for a deeper inspection.
$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster
Unable to connect to the server: dial tcp 127.0.0.1:16443: i/o timeout
```

**Comment by ktsakalozos** [comment]
@msm-code could you please attach the `microk8s.inspect` tarball? I need to see what happens with the API server.

Immediately after starting MicroK8s there is a period when the systemd service of the API server says it is up but the API server is still booting so the endpoint is not ready. Could that be the case? `microk8s.status --wait-ready` will wait for the API server to be available.

**Comment by heckad** [comment]
I have the same problem.

**Comment by optimus-kart** [comment]
Facing the same issue even a reinstall did not solve the problem

**Comment by hadirsa** [comment]
I have the same issue.

**Comment by optimus-kart** [comment]
@hadirsa try rebooting the machine. Worked for me

**Comment by ktsakalozos** [comment]
Please remember to attach the tarball produced with `microk8s.inspect` so I can help.

**Comment by Spajderix** [comment]
[inspection-report-20191118_212722.tar.gz](https://github.com/ubuntu/microk8s/files/3860778/inspection-report-20191118_212722.tar.gz)
Same Here. Right after installing. I've done `microk8s.reset` but it did not help

**Comment by ktsakalozos** [comment]
@Spajderix I see this in the logs of containerd (`journalctl -u snap.microk8s.daemon-containerd`)
```
lis 18 13:07:46 microk8s microk8s.daemon-containerd[21587]: time="2019-11-18T13:07:46.779334737Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-test-6557497784-vbk4f,Uid:2bd15faf-4d6c-4949-8416-fa711bc3811b,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to resolve image "k8s.gcr.io/pause:3.1": no available registry endpoint: failed to do request: Head https://k8s.gcr.io/v2/pause/manifests/3.1: dial tcp 74.125.205.82:443: i/o timeout"
```
Are you behind a firewall, need a proxy to reach the web?

**Comment by Spajderix** [comment]
@ktsakalozos You're right. Had a typo in proxy url. Corrected, but still no luck. For reference: I've set it on `/var/snap/microk8s/current/args/containerd-env`, as follows:
`HTTP_PROXY=http://proxy.entity:3128
HTTPS_PROXY=http://proxy.entity:3128`
Hostname resolves correctly, and when set on bash shell, properly works with curl.

New report for reference: 
[inspection-report-20191118_215951.tar.gz](https://github.com/ubuntu/microk8s/files/3860921/inspection-report-20191118_215951.tar.gz)

**Comment by TimHarmon** [comment]
I seem to have the same problem  attached are my inspect logs
[node00_inspection-report-20200619_223517.tar.gz](https://github.com/ubuntu/microk8s/files/4806929/node00_inspection-report-20200619_223517.tar.gz)

**Comment by ktsakalozos** [comment]
@TimHarmon could you try `microk8s.status  --wait-ready`? There is a short delay between the services start and the time they are actually ready to use.

**Comment by TimHarmon** [comment]
I have done that and the command simply times out.

**Comment by evilfactory** [comment]
I have also the same problem

```
[inspection-report-20200723_191542.tar.gz](https://github.com/ubuntu/microk8s/files/4968297/inspection-report-20200723_191542.tar.gz)

> microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

> microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1515/inspection-report-20200723_191542.tar.gz

```

**Comment by ktsakalozos** [comment]
@evilfactory I believe you machine does not register as a node in Kubernetes because there are underscores in its hostname. Could you change to a hostname that does not include underscores and capital letters and retry?

**Comment by evilfactory** [comment]
> 
> 
> @evilfactory I believe you machine does not register as a node in Kubernetes because there are underscores in its hostname. Could you change to a hostname that does not include underscores and capital letters and retry?

thanks! it worked :D

**Comment by dmissud** [comment]
Hello,
I have the same problem. 
I try to build a cluster of raspberry pi 4. One is ok (the master) but I've the problem on the second one.
I use ubuntu 20.04.1 for raspberry.

I've got : 

`sudo microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

sudo microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1794/inspection-report-20201111_142236.tar.gz
`

[inspection-report-20201111_142236.tar.gz](https://github.com/ubuntu/microk8s/files/5524563/inspection-report-20201111_142236.tar.gz)

Thx for you're answer

**Comment by rchadgray** [comment]
I have the same issue on Raspberry Pi also.  I got two Pi's to cluster, but i cannot add this third Pi to the master.

`ubuntu@kube3:~$ sudo microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1794/inspection-report-20201117_165157.tar.gz
`

[inspection-report-20201117_165157.tar.gz](https://github.com/ubuntu/microk8s/files/5554914/inspection-report-20201117_165157.tar.gz)

**Comment by rchadgray** [comment]
I had to completely start my OS over.  One thing i did different is install Docker first.  Then microk8s.  Not sure if that helped, but i did get all three Raspberry Pi 4 to cluster and in HA.  I think because i got the hang of all the step to install i was much more familiar with the process and probably made less mistakes that may have corrupted the OS.

**Comment by ksully-execute** [comment]
I have the same issue, reboot does not help, removing and reinstalling does not help, I'll attached the inspect log
[inspection-report-20210210_162133.tar.gz](https://github.com/ubuntu/microk8s/files/5961621/inspection-report-20210210_162133.tar.gz)
Does anyone have a solve for this?

**Comment by rkh-hash** [comment]
same issue ... :(

**Comment by ksully-execute** [comment]
> I have the same issue, reboot does not help, removing and reinstalling does not help, I'll attached the inspect log
> [inspection-report-20210210_162133.tar.gz](https://github.com/ubuntu/microk8s/files/5961621/inspection-report-20210210_162133.tar.gz)
> Does anyone have a solve for this?

I found that although the instructions say to do the snap as 'sudo snap....', if I clean up and reinstall, and do that command as root, it works fine. No idea why

**Comment by balchua** [comment]
> I have the same issue, reboot does not help, removing and reinstalling does not help, I'll attached the inspect log
> [inspection-report-20210210_162133.tar.gz](https://github.com/ubuntu/microk8s/files/5961621/inspection-report-20210210_162133.tar.gz)
> Does anyone have a solve for this?

Its strange that i see this error.

```
error: stat /home/ksully/.kube/config: not a directory
```
Normally it uses the `kubectl.env` included in the snap.  For some reason it looks like it is being overridded.  Do you have an environment variable `KUBECONFIG` defined in your root profile?

Can you do `microk8s config > /home/ksully/.kube/config`
