### ISSUE TITLE
Second node fails to join cluster when given an IPv6 address

### ISSUE THREAD

**Issue by trendamplifier** [canonical/microk8s#3751]
#### Summary

When adding a second node via an IPv6 address, the join command fails to parse it.

#### What Should Happen Instead?

The second node should join the cluster.

#### Reproduction Steps

1. microk8s add-node
2. microk8s join 2a01:4f8: ... ::2:25000/7d5316b ... f83fc/e08c2 ... 650

The error message implies that "4f8" is taken to be a port number, not part of the address.

#### Introspection Report

Version 1.26.1

**Comment by trendamplifier** [comment]
This is a severe bug, because the add-node subcommand itself recommends a join subcommand that can't work.

**Comment by sachinkumarsingh092** [comment]
Hi @trendamplifier, thanks for opening this!
Where did you get the IPV6 address and join token from? Was it generated from the `add-node`?
I'd also be very helpful if you can give an introspection report for this.

**Comment by trendamplifier** [comment]
Yes, I copy and pasted the command from the `add-node` output.

**Comment by trendamplifier** [comment]
As for the introspection report, I don't want all this data about my system on the open forum. I could send it to you privately, if that is ok to you?

**Comment by sachinkumarsingh092** [comment]
Sure. My email is in my GH profile if you want to email me.

**Comment by trendamplifier** [comment]
Email is out. This is easy to reproduce, IMHO. Just setup the newest stable microk8s with snap and choose the join command that uses the IPv6 address line from the add-node output.

**Comment by sachinkumarsingh092** [comment]
Thanks! Looking into it.

**Comment by trendamplifier** [comment]
Any progress yet @sachinkumarsingh092 ? If this can't be fixed, I'll have to revert to IPv4 networking ☹️

**Comment by sachinkumarsingh092** [comment]
Hey @trendamplifier 
Sorry for the late reply but the problem is particularly with using IPV6 in general.
We might look deeper into IPV6 in the future. But for now, I'd suggest using IPV4 for now.

**Comment by trendamplifier** [comment]
Hi @sachinkumarsingh092
So I got it working with the IPv4 command now. Thanks for your effort!
