### ISSUE TITLE
Getting an error while setting up multi cluster(adding a node)

### ISSUE THREAD

**Issue by SuperAayush** [canonical/microk8s#3752]
#### Summary
When I try to add a node to set up multicluster in mac m1 it is throwing me a connection error.
Doc I am following - https://microk8s.io/docs/clustering

#### What Should Happen Instead?
It should add a node with a different port number.
#### Reproduction Steps

1. Setup microk8s in your system
2. Create and run a dashboard 
3. Try adding a node

#### Screenshot:
<img width="1426" alt="Screenshot 2023-02-12 at 4 12 40 PM" src="https://user-images.githubusercontent.com/78820926/218306263-80290854-916a-4758-b105-635c689e8b39.png">

**Please close the issue if found duplicate**

**Comment by SuperAayush** [comment]
Followed by this error:
<img width="1416" alt="Screenshot 2023-02-12 at 4 29 42 PM" src="https://user-images.githubusercontent.com/78820926/218307017-7e628fae-f8c3-4078-b2cc-2f7c611bc22c.png">

**Comment by trendamplifier** [comment]
Are you running add-node and join subcommands on the same host? Join has to be executed on a different host to join the one you ran add-node on...

**Comment by SuperAayush** [comment]
Currently, my localhost address is: 192.168.64.4:10443
And the one I am trying to add a node to is: 192.168.64.4:25000

It is showing an error if I change the host number or even IP.

**Comment by balchua** [comment]
@SuperAayush it microk8s is composed of several components, hence many other ports.  It is not possible to join nodes belonging to the same node.

**Comment by SuperAayush** [comment]
I am really sorry but since I am just a beginner with MicroK8s can you please tell me the command I should run to make this work?

**Comment by balchua** [comment]
@SuperAayush try this tutorial 
https://ubuntu.com/tutorials/getting-started-with-kubernetes-ha?&_ga=2.175375329.218996862.1676296581-1422638236.1668300180#1-overview

**Comment by SuperAayush** [comment]
I would like to troubleshoot along with you over a meet 🤔,  can you please help me out with it?
I respect your time and if cannot find time for a quick meeting that totally fine!! 

I might be a little confused here and I think that can be clearly understood over a meeting!!

<img width="1205" alt="Screenshot 2023-02-13 at 7 47 11 PM" src="https://user-images.githubusercontent.com/78820926/218482258-537d0edb-80f5-4073-a276-b4ddd80c79fa.png">


cc- @balchua

**Comment by sachinkumarsingh092** [comment]
Hey @SuperAayush, 

Joining in microk8s requires at least 2 nodes on the same network with microk8s installed on both of these to form a cluster. If there are 3 or more nodes, it reaches HA (high-availability).

The first screenshot seems like you're trying to make your local machine the master node. This is risky as your local node has lots of different processes running and hence most probably use/block the required ports required by your other node (I'm assuming a VM) to do a join. Also in your last ss, it seems the issue is with the DNS.

I suggest you make another VM and try to join these two VM nodes for your experiment. From any one on the VMs with a fresh microk8s installed do the following,
```
$ sudo microk8s.enable dns
$ sudo microk8s.add-node
```

On the second node do this:
```
$ sudo microk8s join <join_string>
```
This should get you a 2 node cluster. Similarly, you can add more nodes to your cluster to make it HA.
Do let me know if you're facing any more problems.

**Comment by SuperAayush** [comment]
No change: 
<img width="1162" alt="Screenshot 2023-02-14 at 12 39 42 AM" src="https://user-images.githubusercontent.com/78820926/218551449-f5957ca4-5743-40d8-947c-2c9bc4460f64.png">

**Comment by sachinkumarsingh092** [comment]
You need to make sure that your control plane node (192.168.64.17) can also resolve `check1` to 192.168.64.18
Add this under `/etc/hosts` of 192.168.64.17:
```
192.168.64.18 check1
```

**Comment by SuperAayush** [comment]
Again there is another error where I cannot change the permission of this folder to make it both read and write accessible.
Error: "hosts" E212: Can't open file for writing
Can we do a quick meet to solve it if you are fine at this hour of time?

cc-sachinkumarsingh092

**Comment by sachinkumarsingh092** [comment]
Do a good old `sudo` and see if it works.

```
$ sudo vi /etc/hosts
```

**Comment by SuperAayush** [comment]
Already tried various alternatives not working!!

**Comment by sachinkumarsingh092** [comment]
Can you show please show me what you did and what was the error you're receiving?

**Comment by SuperAayush** [comment]
This has been fixed now, closing the issue.
