### ISSUE TITLE
Unable to connect to the server: dial tcp <local IP>:16443: connect: no route to host

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#3778]
`microk8s kubectl get pod` shows the error.
 
#### Reproduction Steps

1. ...
2. ...

#### Introspection Report

[inspection-report-20230218_131408.tar.gz](https://github.com/canonical/microk8s/files/10773136/inspection-report-20230218_131408.tar.gz)

**Comment by sachinkumarsingh092** [comment]
Hi @khteh, Thanks for opening this.
I see these logs in your api-server:
```
Feb 03 09:01:47 khteh-p17-2i microk8s.daemon-apiserver-kicker[15722]: Unable to locate credentials. You can configure credentials by running "aws configure".
Feb 03 09:01:49 khteh-p17-2i microk8s.daemon-apiserver-kicker[15768]: Unable to locate credentials. You can configure credentials by running "aws configure".
Feb 03 09:01:49 khteh-p17-2i microk8s.daemon-apiserver-kicker[15676]: Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 253
```

Can you confirm you've set up your credentials properly?

**Comment by khteh** [comment]
Yes, I can connect to the EKS. Thus error happens on localhost cluster.
