### ISSUE TITLE
microk8s inspect return no errors, but microk8s doesn't start

### ISSUE THREAD

**Issue by janv67** [canonical/microk8s#3787]
#### Summary
After fresh installation, microk8s is not starting. It says nothing in the inspect. The installation was running earlier, but pods were not starting. I

#### What Should Happen Instead?
I want microk8s to run without errors in an empty installation so I can try running my docker image finally on a cluster locally in my network

#### Reproduction Steps
Just remove everything in my installation and reinstall

1. microk8s reset
2. sudo snap remove microk8s
3. sudo snap install microk8s --classic
4. microk8s status

#### Introspection Report
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

#### Can you suggest a fix?
Tried everything I found on the internet. I am out of solutions

#### Are you interested in contributing with a fix?
No, no skills to do so

[inspection-report-20230221_185610.tar.gz](https://github.com/canonical/microk8s/files/10796478/inspection-report-20230221_185610.tar.gz)

**Comment by ebebpl** [comment]
Try to install an older release like 1.24/stable:
$ snap remove microk8s
$ snap install microk8s --classic --channel=1.24/stable

**Comment by janv67** [comment]
Back in business. Thanks!
Any idea for the reason why an older release seems to work whereas the current did work but is no longer working?

**Comment by ebebpl** [comment]
Dependency hell I presume :). 1.25 and 1.26/stable seems to be having problems with glibc version on centos 7.9:
/usr/bin/pkttyagent: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /snap/microk8s/4595/lib/x86_64-linux-gnu/libexpat.so.1)

**Comment by sachinkumarsingh092** [comment]
Hi @janv67,
When you do `snap remove`, there is a snapshot of data that still remains present for future use. You can use the `--purge` flag to remove all the old data and then install any version of microK8s again.
