### ISSUE TITLE
How to bind microk8s to eth1 and avoid 127.0.0.1 on AWS instance

### ISSUE THREAD

**Issue by hpanneti** [canonical/microk8s#3795]
#### Summary
 Hi support from microk8s

I'm struggling with a microk8s installation on an AWS Workspaces instance (ubuntu 22.04).
Microk8s networking is failing on this kind of environment.

Hereafter is the response given by AWS support : 

   "Workspaces have 2 Network Adaptors, eth0 sitting in AWS's VPC and controlled and used by the Workspaces 
    to access internal addresses. The second interface [eth1] is the one which a customer can access and control.
    The Workspaces itself is already using the primary interface [eth0] for data streaming and access to 
    internal AWS infrastructure. 

    The 'localhost' [127.0.0.1] is tied to eth0.

    We can see that by default, the install starts to use localhost:
          $ sudo snap install microk8s --classic
          microk8s (1.26/stable) v1.26.0 from Canonical✓ installed
          $ sudo microk8s status
          microk8s is running
          high-availability: no
          datastore master nodes: 127.0.0.1:19001

    By default, it appears MicroK8s expects to use localhost, which directs traffic to/from eth0, 
    which is not recommended, as the Workspaces itself is using eth0." 

#### Introspection Report
To attempt to solve this issue:
- I checked that the "default" interface for microk8s is eth1 thanks to the default route. 
- I then attempted to modify the configuration as described in the documentation : https://microk8s.io/docs/configure-host-interfaces
  See hereafter what has been changed.

- However it appears that is not sufficient to have microk8s working.
- "ss -anlt" shows that 127.0.0.1 is still in use 
- "microk8s status" still shows that 127.0.0.1 is in use

- Did I miss something in the modification that should be done to bind microk8s to eth1 and avoid 127.0.0.1 ?
- see also attached the tarball generated via "microk8s inspect"

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current$ grep -rin "172.31.38.8" *
args/kubelet:18:--healthz-bind-address=172.31.38.8
args/kube-proxy:3:--healthz-bind-address=172.31.38.8
certs/csr.conf.rendered:28:IP.4 = 172.31.38.8
certs/csr.conf:28:IP.4 = 172.31.38.8
credentials/kubelet.config:5:    server: https://172.31.38.8:16443
credentials/scheduler.config:5:    server: https://172.31.38.8:16443
credentials/client.config:5:    server: https://172.31.38.8:16443
credentials/controller.config:5:    server: https://172.31.38.8:16443
credentials/proxy.config:5:    server: https://172.31.38.8:16443

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current$ ip route
default via 172.31.32.1 dev eth1 proto static onlink 
blackhole 10.1.198.0/26 proto 80 
10.1.198.1 dev calie2b338f2754 scope link 
10.1.198.2 dev cali22b1cd8bc88 scope link 
172.31.32.0/20 dev eth1 proto kernel scope link src 172.31.38.8 metric 100 
198.19.128.0/18 dev eth0 proto kernel scope link src 198.19.155.54 metric 100 

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current$ ss -anlt
State         Recv-Q        Send-Q                 Local Address:Port                  Peer Address:Port        Process        
LISTEN        0             50                           0.0.0.0:445                        0.0.0.0:*                          
LISTEN        0             4096                       127.0.0.1:45411                      0.0.0.0:*                          
LISTEN        0             4096                     172.31.38.8:10248                      0.0.0.0:*                          
LISTEN        0             4096                   198.19.155.54:8200                       0.0.0.0:*                          
LISTEN        0             4096                       127.0.0.1:10249                      0.0.0.0:*                          
LISTEN        0             4096                       127.0.0.1:9099                       0.0.0.0:*                          
LISTEN        0             50                           0.0.0.0:139                        0.0.0.0:*                          
LISTEN        0             1024                       127.0.0.1:9999                       0.0.0.0:*                          
LISTEN        0             4096                     172.31.38.8:10256                      0.0.0.0:*                          
LISTEN        0             128                        127.0.0.1:8240                       0.0.0.0:*                          
LISTEN        0             4096                   127.0.0.53%lo:53                         0.0.0.0:*                          
LISTEN        0             128                          0.0.0.0:22                         0.0.0.0:*                          
LISTEN        0             128                        127.0.0.1:631                        0.0.0.0:*                          
LISTEN        0             4096                       127.0.0.1:19001                      0.0.0.0:*                          
LISTEN        0             4096                       127.0.0.1:1338                       0.0.0.0:*                          
LISTEN        0             10                     198.19.155.54:8220                       0.0.0.0:*                          
LISTEN        0             50                              [::]:445                           [::]:*                          
LISTEN        0             4096                               *:25000                            *:*                          
LISTEN        0             4096                               *:10250                            *:*                          
LISTEN        0             50                              [::]:139                           [::]:*                          
LISTEN        0             4096                               *:10257                            *:*                          
LISTEN        0             4096                               *:10259                            *:*                          
LISTEN        0             128                             [::]:22                            [::]:*                          
LISTEN        0             128                            [::1]:631                           [::]:*                          
LISTEN        0             4096                               *:16443                            *:*               

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
  disabled:
    cert-manager         # (core) Cloud native certificate management

**Comment by hpanneti** [comment]
Sorry , I don't see how to attach the tarball inspection-report-20230223_161834.tar.gz

**Comment by ktsakalozos** [comment]
Hi @hpanneti it is a bit surprising to me that 127.0.0.1 is on eth0. Could you share the output of `ip a`?



> Sorry , I don't see how to attach the tarball inspection-report-20230223_161834.tar.gz

You can attach a inspection tarball by drag and drop it the reply text box.

**Comment by hpanneti** [comment]
Hi Konstantinos
Thank you for your help.
I'm also surprised by the answer that AWS gave me stating that eth0 and 127.0.0.1 are tied together for the workspace instances.
Hereafter is the output of "ip a"

pannetier@U-1AUT752MOFRY6:~/Documents$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:60:98:c8:fa:c9 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    inet 198.19.155.54/18 metric 100 brd 198.19.191.255 scope global dynamic eth0
       valid_lft 3453sec preferred_lft 3453sec
    inet6 fe80::860:98ff:fec8:fac9/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:57:d4:3c:a9:f9 brd ff:ff:ff:ff:ff:ff
    altname enp0s6
    inet 172.31.38.8/20 metric 100 brd 172.31.47.255 scope global dynamic eth1
       valid_lft 3453sec preferred_lft 3453sec
    inet6 fe80::857:d4ff:fe3c:a9f9/64 scope link 
       valid_lft forever preferred_lft forever
26: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8951 qdisc noqueue state UNKNOWN group default 
    link/ether 66:f8:e6:64:4b:bb brd ff:ff:ff:ff:ff:ff
    inet 10.1.198.0/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::64f8:e6ff:fe64:4bbb/64 scope link 
       valid_lft forever preferred_lft forever
27: calie2b338f2754@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-197efab7-ab70-23e7-4f53-13e6da11c61c
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
28: cali22b1cd8bc88@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-d932311a-cbb0-ac99-f956-b07aa56b856c
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by ktsakalozos** [comment]
In https://microk8s.io/docs/services-and-ports you will find all the services that K8s runs along with where they are listening (interface/port). There are a number of them that listen on localhost because they are not meant to be exposed. Under `/var/snap/microk8s/current/args/` you will find configuration files with the arguments passed to all services. What you could try to do is to work through one by one the services and set (if possible) the interface each service listens to. That would of course mean that you will have to point the clients that need to interact with services through localhost to use the designated interface. Overall this is not a good/easy path forward. It would be best to see if you limit the localhost traffic forwarded to eth0.

**Comment by hpanneti** [comment]
Hi Konstantinos,
Thank you for your reply.
I will review the link https://microk8s.io/docs/services-and-ports and attempt to apply  the necessary changes   to avoid using the localhost.
I'll let you know if I succeed to make it works.
Regards

**Comment by hpanneti** [comment]
Hello Konstantinos,

I followed the links you mentioned 
https://microk8s.io/docs/configure-host-interfaces
https://microk8s.io/docs/services-and-ports

And did the following changes to specify eth1 (172.31.38.8) as the listen address instead of 127.0.0.1

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current/args$ grep 172.31.38.8 *
containerd-template.toml:  address = "172.31.38.8:1338"
containerd-template.toml:  stream_server_address = "172.31.38.8"
etcd:--listen-client-urls=https://172.31.38.8:12379
flanneld:--etcd-endpoints=https://172.31.38.8:12379
kube-apiserver:--bind-address=172.31.38.8
kube-apiserver:--advertise-address=172.31.38.8
kube-controller-manager:--bind-address=172.31.38.8
kubelet:--address=172.31.38.8
kubelet:--node-ip=172.31.38.8
kubelet:--healthz-bind-address=172.31.38.8
kube-proxy:--healthz-bind-address=172.31.38.8
kube-proxy:--bind-address=172.31.38.8
kube-proxy:--nodeport-addresses=172.31.38.8
kube-scheduler:--bind-address=172.31.38.8

hpannetier@U-1AUT752MOFRY6:/var/snap/microk8s/current/credentials$ grep 172.31.38.8 *
client.config:    server: https://172.31.38.8:16443
controller.config:    server: https://172.31.38.8:16443
kubelet.config:    server: https://172.31.38.8:16443
proxy.config:    server: https://172.31.38.8:16443
scheduler.config:    server: https://172.31.38.8:16443

However this doesn't solve the issue so I get back to the standard configuration.
I'm wondering if AWS telling that "127.0.0.1 is tied to eth0" is the real issue 
on this deployment of microk8s over Amazon Workspace.

The 1st error observed is the pod coredns which keep restarting due to liveness/readiness probe failure.
This is maybe this issue that I need to dig through.

Hereafter are few traces about the coredns. Could you tell me what to check to progress on this issue?
Thanks a lot. 

hpannetier@U-1AUT752MOFRY6:~$ kubectl -n kube-system get pods
NAME                                       READY   STATUS    RESTARTS       AGE
calico-kube-controllers-786644b55b-m4f59   1/1     Running   6 (75s ago)    17h
coredns-6f5f9b5d74-snwl5                   0/1     Running   28 (75s ago)   71m
calico-node-66gg5                          1/1     Running   5 (75s ago)    17h

hpannetier@U-1AUT752MOFRY6:~$ kubectl -n kube-system get pods
NAME                                       READY   STATUS             RESTARTS         AGE
calico-kube-controllers-786644b55b-m4f59   1/1     Running            6 (55m ago)      17h
calico-node-66gg5                          1/1     Running            5 (55m ago)      17h
coredns-6f5f9b5d74-snwl5                   0/1     CrashLoopBackOff   41 (4m19s ago)   125m


hpannetier@U-1AUT752MOFRY6:~$ kubectl -n kube-system logs coredns-6f5f9b5d74-snwl5
.:53
.:53
[INFO] plugin/reload: Running configuration SHA512 = deb3871c00828b25727978460b261c74de0519acfb0c61c7813cc2cea8e445ddeb98d0e8f8c7bf945861f2a8b73a581c56067b8fe22b9acd076af72a94958de2
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] plugin/health: Going into lameduck mode for 5s
.:53: command not found



hpannetier@U-1AUT752MOFRY6:~$ kubectl -n kube-system get events -w


0s          Warning   Unhealthy        pod/coredns-6f5f9b5d74-snwl5                   Readiness probe failed: Get "http://10.1.198.34:8181/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
0s          Warning   Unhealthy        pod/coredns-6f5f9b5d74-snwl5                   Liveness probe failed: Get "http://10.1.198.34:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
108s        Warning   BackOff   pod/coredns-6f5f9b5d74-snwl5   Back-off restarting failed container coredns in pod coredns-6f5f9b5d74-snwl5_kube-system(0eebf88d-4e35-421a-808a-04c4ed8466a5)

hpannetier@U-1AUT752MOFRY6:~$ kubectl -n kube-system get all | grep dns
pod/coredns-6f5f9b5d74-snwl5                   0/1     Running   30 (111s ago)   76m
service/kube-dns   ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   76m
deployment.apps/coredns                   0/1     1            0           76m
replicaset.apps/coredns-6f5f9b5d74                   1         1         0       76m

hpannetier@U-1AUT752MOFRY6:~$ kubectl get endpoints --all-namespaces
NAMESPACE     NAME           ENDPOINTS                           AGE
default       kubernetes     172.31.38.8:16443                   17h
default       lbs-nodered    <none>                              17h
default       lbs-appli      <none>                              17h
default       lbs-mongo      10.1.198.32:27017                   17h
default       lbs-maria      10.1.198.31:3306                    17h
default       lbs-keycloak   10.1.198.33:8443,10.1.198.33:8080   17h
kube-system   kube-dns                                           77m
