### ISSUE TITLE
Microk8s in WSL2 22.04 with native Systemd support fails with internal error, please report: running "microk8s" failed

### ISSUE THREAD

**Issue by ooeygui** [canonical/microk8s#3810]
#### Summary
Installing Microk8s using [native systemd support in WSL2](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) fails with:

```
internal error, please report: running "microk8s" failed: cannot find installed snap "microk8s" at revision 4595: missing file /snap/microk8s/4595/meta/snap.yaml
```

#### What Should Happen Instead?
I expect microk8s to start and function normally.

#### Reproduction Steps
Using Windows 11 (verified on multiple machines with different 22h2+)

1. Install WSL2 from the Windows store
2. Install Ubuntu 22.04 using `wsl --install Ubuntu-22.04`
3. Create user account
4. Edit `/etc/wsl.conf` and add:
```toml
[boot]
systemd=true
```
5. wsl --shutdown
6. Open Ubuntu 22.04
7. run `sudo snap install microk8s`
8. Once complete, run `sudo microk8s start` or `sudo microk8s status`

#### Introspection Report
```bash
~$ sudo microk8s inspect
internal error, please report: running "microk8s" failed: cannot find installed snap "microk8s" at revision 4595: missing file /snap/microk8s/4595/meta/snap.yaml
```

#### Can you suggest a fix?
I'm not quite certain; happy to help diagnose it.

#### Are you interested in contributing with a fix?
Yes - with guidance

**Comment by ooeygui** [comment]
@neoaggelos thank you for the quick reply. Yes, I am following those. (I forgot to add --classic to the snap install command line).

Here's the output of snap list:
```bash
Name                      Version          Rev    Tracking         Publisher   Notes
bare                      1.0              5      latest/stable    canonical✓  base
core18                    20230207         2697   latest/stable    canonical✓  base
core20                    20230126         1822   latest/stable    canonical✓  base
gtk-common-themes         0.1-81-g442e511  1535   latest/stable/…  canonical✓  -
microk8s                  v1.26.1          4595   1.26/stable      canonical✓  classic
snapd                     2.58.2           18357  latest/stable    canonical✓  snapd
ubuntu-desktop-installer  0+git.50d8deaa   802    latest/edge      canonical✓  classic
```

**Comment by neoaggelos** [comment]
I have to admit that this "internal error" is not something I have encountered. I also assume that yoy have properly configured virtualization extensions from BIOS and enabled all WSL components since you have a VM up and running.

Can you see whether a restart of the computer solves the problem? Also, are there any more details in the outputsnof journalctl or dmesg?

**Comment by ooeygui** [comment]
On a whim, I tried using other snaps; it seems that this issue is in snap itself not microk8s:
```bash
 sudo snap install mosquitto
mosquitto.ctrl
internal error, please report: running "mosquitto.ctrl" failed: cannot find installed snap "mosquitto" at revision 776: missing file /snap/mosquitto/776/meta/snap.yaml
```

I wish the error indicated it was from snap itself instead of implying it was a microk8s issue. I'm going to close this and follow up on snap.

Thank you for the quick replies and turnaround!

**Comment by ooeygui** [comment]
Turns out this happens if you run terminal as administrator.
https://github.com/microsoft/WSL/issues/9097

Not sure why this would happen, but running it normally does not repo the behavior.
