### ISSUE TITLE
Control Center Config Fail 

### ISSUE THREAD

**Issue by Arnav2001** [canonical/microk8s#3818]
I have downloaded Control Center to run Ethereal Engine project and kept everything as it is in configuration option but in the end it said config fail
1. Main log(Non-UI logs)
[main.log](https://github.com/canonical/microk8s/files/10905827/main.log)
2. UI logs
[XRE-logs-2023-03-07T05-41-41.366Z.txt](https://github.com/canonical/microk8s/files/10905836/XRE-logs-2023-03-07T05-41-41.366Z.txt)

**Comment by berkayoz** [comment]
Hey @Arnav2001,
This is the GitHub repository for the MicroK8s project. 
I think you might be at the wrong place, please report your issue in the respective project's repository. Thanks!
