### ISSUE TITLE
Whrong IP Interface 

### ISSUE THREAD

**Issue by crebollobr** [canonical/microk8s#3825]
#### Summary
Whrong IP Interface 

#### What Should Happen Instead?
I Have a cluster with 3 nodes with 3 vlan network. All installation and world view of cluster is tag 70. Others tags are for storage.
I have a pod with postfix and another pod with web sending mail for this pod. 
The source IP of the connection points to storage interface. I guess this is wrong. 

the same problem with ssh server in pod
the sabe problem with node host connecting to mail pod 

#### Reproduction Steps
Install cluster
make deployment of postfix and nginx with mail script
make connection pod - pod using service ip 

#### Introspection Report
[_var_snap_microk8s_4595_inspection-report-20230309_150506.tar.gz](https://github.com/canonical/microk8s/files/10934759/_var_snap_microk8s_4595_inspection-report-20230309_150506.tar.gz)

#### Can you suggest a fix?
no
#### Are you interested in contributing with a fix?
yes

**Comment by neoaggelos** [comment]
Hi @crebollobr, can you describe what you mean by "source IP of the connection points"? Do you mean the externalIP assigned to the service by MetalLB?

From the inspection report, I see that kubernetes is using vlan 70 for all control plane traffic (see `kubectl get node -o wide`, it should show the ips from vlan70), as well as for calico.

The only thing that looks weird is the load balancer service IPs for two of your services (10.0.0.240 and 10.0.0.241). These are handed out by metallb, depending on the addresspools you have configured. Is this what you are refering to?

```

{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.131"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["10.0.0.241"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.130"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.135"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.172"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.136"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.134"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.138"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.132"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["10.0.0.240"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.174"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.171"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
{"caller":"main.go:344","event":"serviceAnnounced","ips":["143.106.42.137"],"level":"info","msg":"service has IP, announcing","pool":"default-addresspool","protocol":"layer2","ts":"2023-03-09T18:04:38Z"}
```

If this is what appears wrong on your side, can you check the output of `microk8s get ipaddresspoll -A -o yaml`? If not, can you explain a bit more what happens? Thank you!
