### ISSUE TITLE
Improve documentation on hints of how to change different settings (calico)

### ISSUE THREAD

**Issue by sjmudd** [canonical/microk8s#3837]
#### Summary

I have been playing with [microk8s](https://microk8s.io/) and find it's a very good and quick way to setup basic k8s. It requires little knowledge or effort to get going.  However, a lot of what it does and the specific configuration it provides seems to not be documented in much detail. If you do not want or need to change this that's fine.

However, I want to change a few things, partly as experimentation but also as I would like to use microk8s for home use across 3 machines and thus want to change some settings.  To do that I need to better understand the "default configuration" and if it differs from a 100% normal k8s setup to know what those differences are.

Specifically I want to do is:
- disable snat within calico, I see there's a setting to do this but am not sure how to trigger the change
- enable BGP so that the internal calico network can be exported to and routed to my internal network.  Again calico has some settings but there seem to be few examples to indicate how this should be done. I'll figure out the BGP configuration on my mikrotik routers on my own

I am not looking for specific documentation on my use case but more some pointers on:
- default configuration provided
- any things to be aware of or differences from the upstream feature implementation
- potential changes that users may want to apply to the default configuration and pointers on how to do them.  This would be true for multiple features provided within microk8s. Just pointing at the upstream feature documentation may not be enough if there are some differences to take into account.

#### Why is this important?

It is important to me because I can not figure out alone the exact changes which are needed to achieve my desired goal. I assume they should be simple but it's not clear. When I look specifically at the calico documentation I have noticed already there are some differences:
- calico seems to recommend the use of the [calico operator](https://github.com/tigera/operator) which is not present on microk8s
- I see the location of the calico resources appear to be in `kube-system` whereas the calico operator puts them into it's own namespace.  This seems to mean that I can not safely use the calico operator within microk8s at least without understanding the configuration differences this implies.

#### Are you interested in contributing to this feature?

I would love to do this but I've been struggling to put the things together to make this work so can not really help here.
Maybe for my case I could share in a blog post or similar the required steps that were needed so others looking to solve similar problems could benefit from that.

**Comment by neoaggelos** [comment]
Hi @sjmudd 

Thank you for raising this issue. We have recently started working on improving the documentation regarding the CNI configuration on MicroK8s in general. All of the things you raised are valid points, and there are also more that have been partly discussed in multiple issues over the years (e.g. how to upgrade Calico CNI, how to use an alternative CNI, etc).

For single-node, you will typically get far by editing `/var/snap/microk8s/current/args/cni-network/cni.yaml` and setting the calico settings you want, and then applying the changes with `microk8s kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml`. There are more considerations for multi-node, but the above should be enough to get started.

Once we have something, I will make sure to link it here to get your feedback. In the meantime, feel free to ask here for particular calico configurations that are you unsure how to apply on MicroK8s. Thanks again!

**Comment by cbcoutinho** [comment]
Hi, I'm also running into the same issue attempting to install the Calico Operator onto a multi-node Microk8s cluster that has calico installed via the `ha-cluster` addon. While attempting to install the Operator, I run into some of the same ownership issues raised by OP.

I'm specifically interested in using `GlobalNetworkPolicy` resources from `projectcalico.org/v3` API group which I understand requires the Calico Operator to be installed.

Any help would be appreciated on upgrading Calico or modifying it beyond the defaults to enable calico network policies 🙏
