### ISSUE TITLE
Retag on image import

### ISSUE THREAD

**Issue by jardon** [canonical/microk8s#3840]
#### Summary

When importing an image archive locally, I cannot retag the image afaik.  This requires me to use other tooling to unpack and repack the archive with a new tag in the image metadata.  It would be very helpful to be able to override the tags.

#### Why is this important?

When building rocks with rockcraft, the tooling uses the `version` field of the `rockcraft.yaml`  to populate the tag.  Instead of having to modify the artifact directly, would it be possible to pass a `--tag` option to `microk8s ctr image import`?  I cannot pass a tag to the basename at this time.

#### Are you interested in contributing to this feature?

Not at this time.

#### Relevant Information:
[Rockcraft Issue](https://github.com/canonical/rockcraft/issues/213)

**Comment by neoaggelos** [comment]
Hi @jardon 

Looks like this functionality is not supported by the `ctr` command, and there is nothing for us to do from the side of MicroK8s.

However, you might be able to do this in two separate steps:

```
microk8s ctr image import image.tar
microk8s ctr image convert $oldtag $newtag
```
