### ISSUE TITLE
When injecting Linkerd via files, kubectl apply fails

### ISSUE THREAD

**Issue by amartincolby** [canonical/microk8s#3842]
#### Summary

I am injecting Linkerd via a file instead of piping. This was working fine until I upgraded to the newest Microk8s. Now, when I try to apply the file generated by the Linkerd injection, I get this error `for: "./injected_config.yml": error when patching "./injected_config.yml": Operation cannot be fulfilled on deployments.apps "service_name": the object has been modified; please apply your changes to the latest version and try again`

#### What Should Happen Instead?

Linkerd should be injected, create a new manifest file, and this file should then be successfully applied to the cluster.

#### Reproduction Steps

1. Run Windows 11 Pro
2. Enable linkerd in mk8s 2.6
3. Retrieve a deployment and save it as a yaml file
4. Inject linkerd into that manifest file and save the output as another yaml
5. Try to apply that yaml to the cluster
6. See the error

#### Introspection Report

Probably no need for this yet.

#### Can you suggest a fix?

No idea.  By deleting the resourceVersion from the file I am attempting to apply, it works, but this was not necessary up until a few days ago. The only other change was an update to PowerShell. I do not know if this is being caused by Linkerd, kubectl, or what. The Linkerd community definitely thinks that Linkerd is not the problem and they simply told me to edit the manifest file, which actually kind of insulted me. I'm not going to write a script to sanitize a file that did not previously need sanitizing.

Further, the reason I am not using piping is because this script is running in Windows, and the scope of the pipe commands between the host and the VM is squiffy.

#### Are you interested in contributing with a fix?

Sure. But I have zero idea how. I am quite incompetent, which is why I am here asking questions.

**Comment by neoaggelos** [comment]
Hi @amartincolby 

Hmm, I see the issue. Indeed, it's due to the resourceVersion of the deployment. Can you share the deployment manifest before injecting linkerd, as well as the linkerd command you use?

Also, when you see this error, can you compare the latest version of the deployment `microk8s kubectl get deploy $deployment -o yaml` with the original manifest prior to the injection?

It could be a lot of different things, but it might also be that a Kubernetes controller is updating the Deployment in the meantime.  In any case, applying a manifest with a resourceVersion can be problematic due to the issue that you are seeing.

In any case, MicroK8s is not really doing anything to alter the resources, but happy to help you with debugging your issue.

**Comment by amartincolby** [comment]
I compared the three manifests: the originally retrieved one, the injected one, and a freshly retrieved manifest. Indeed, the resource version that is live when attempting to apply is different, so the failure makes sense. My confusion is why this suddenly started happening. I had been working with this flow for months with no problem. Now, if I try to revert back to an older Microk8s, I simply encounter _other_ errors, such as the inability to run `dashboard-proxy`. I have reverted to older versions of Linkerd to no avail.

OH HO! As I was writing this, I began doing really extensive Linkerd testing and have seen misalignment with the resourceVersion. I do not yet know what is causing it, but I at least have a clue.

**Comment by amartincolby** [comment]
I am seeing other problems actually. I am beginning to think that the problem is actually PowerShell. My scripts periodically just lock up. I'm going to try running them outside of Visual Studio Code, see if that helps.

**Comment by amartincolby** [comment]
My attentions have shifted to Multipass. Periodically, text will simply stop being generated and the terminal will lock. Trying to kill the terminal fails, but I can cause it to immediately unlock by killing the VM. It often freezes while in the middle of returning a message, such as when displaying what is returned from a `kubectl get` command. Further, after investigating every step in my scripts, it is the `kubectl apply` itself that seems to changing the `resourceVersion` value. I can open up the shell for the VM and it appears healthy. Is there any other way to analyze the connection?

**Comment by amartincolby** [comment]
Also, `microk8s linkerd check` will always fail because Linkerd cannot access the microk8s kubectl. I can fix it by going into the VM and installing kubectl and just using the Microk8s kubectl config, but am I missing something in the Linkerd setup?

**Comment by amartincolby** [comment]
I removed `--debug` from my `helm upgrade` command and it seems to have solved my problems. This is very strange indeed.

**Comment by amartincolby** [comment]
And that stopped terminal freezes but I am still encountering the apply issue randomly. I can run the script multiple times and it will sometimes succeed, sometimes fail.

**Comment by amartincolby** [comment]
I have ultimately used `Start-Sleep -Seconds 5` before injecting and applying Linkerd. That _seems_ to solve the problem.
