### ISSUE TITLE
Metallb installation broken - container images are no longer on docker.io

### ISSUE THREAD

**Issue by senyahnoj** [canonical/microk8s#3855]
#### Summary

Microk8s 1.24 with metallb add-on sources its container images from docker.io. The metallb project have removed these images and put them on quay.io instead.

As a result on new installations of microk8s enabling the metallb add-on, the pods inside the metallb-system namespace will get stuck in ImagePullBackOff as they cannot download the following images.

* docker.io/metallb/controller:v0.9.3
* docker.io/metallb/speaker:v0.9.3

We also believe that this affects other versions of Microk8s - certainly 1.23

#### What Should Happen Instead?

We would expect the container images to be available so that the metallb system operates as normal.

#### Reproduction Steps

1. snap install microk8s --channel=1.24/stable --classic
2. microk8s enable metallb:\<ip-address-pool\>

Run `watch microk8s.kubectl -n metallb-system get po` - you will see the pods getting stuck in ImagePullBackOff when the installation tries to pull in the containers

#### Can you suggest a fix?

We only have a workaround for the time being, which I share below:

```
microk8s.kubectl -n metallb-system patch deployment controller --type=json -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"quay.io/metallb/controller:v0.9.3"}]'
microk8s.kubectl -n metallb-system patch daemonset speaker --type=json -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"quay.io/metallb/speaker:v0.9.3"}]'
```
This replaces the existing image locations in docker.io with their quay.io hosted locations.

**Comment by neoaggelos** [comment]
Hi @senyahnoj

Thank you for raising this, as well as offering a quick workaround for affected people. Worth noting that this only affects MicroK8s versions 1.24 or older. Also discussed in https://github.com/canonical/microk8s/issues/3854 and https://github.com/canonical/microk8s/issues/3851.

The fix for this is already merged https://github.com/canonical/microk8s-core-addons/pull/172 and released in `1.24/edge`. It will soon be promoted to the `1.24/stable` branch as well.

**Comment by falk-atos** [comment]
@neoaggelos do we know when it will make it into 1.24/stable?

I checked the latest snap delivered today: (  1.24/stable: **v1.24.12** 2023-03-20 (4950) 225MB classic). But it was not included.

**Comment by neoaggelos** [comment]
Hi @falk-atos 

Did you refresh from a previous version, is this a new install? For the former, you should first do:

```
sudo microk8s kubectl addons repo update core
```

So that the latest changes are pulled in.

**Comment by melkamar** [comment]
The command should be 

```
$ sudo microk8s addons repo update core
```

It's a microk8s command, not a kubectl command. This does fix the problem though!

I couldn't find this command in the [upgrading documentation](https://microk8s.io/docs/upgrading) so thanks a lot for this thread.
