### ISSUE TITLE
microk8 snap installation with snap proxy configuration

### ISSUE THREAD

**Issue by canramesh** [canonical/microk8s#3858]
#### Summary
snap microk8s installation works fine if the proxy is set as per https://microk8s.io/docs/install-proxy

i.e if I set the proxy in /etc/environment it is able to download resources and install microk8s

However when I setup the proxy at the snap system level as below , it does not seem to use the proxy

$ sudo snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
$ sudo snap set system proxy.https="http://<proxy_addr>:<proxy_port>"

#### What Should Happen Instead?
I think the behaviour should be same if I use snap proxy.http and proxy.https as well.

#### Reproduction Steps
1.  Install microk8s snap with appropriate proxy with sudo snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
Microk8s does not get configured properly.(this is assuming /etc/environment proxy is not setup)

2. Install microk8s snap with system level proxy in /etc/environment then it all works fine.

**Comment by neoaggelos** [comment]
Hi @canramesh 

The `proxy.http` and `proxy.https` system options (https://snapcraft.io/docs/system-options#heading--proxy) are used by the snapd daemon for downloading snap packages from the snap store.

They are not meant to be used by the installed snaps (that is, MicroK8s, or any other snap). It is also not possible for a snap to retrieve this value from snapd.

The correct way to set the proxy for MicroK8s is the one described in the documentation page that you linked.
