### ISSUE TITLE
observability addon cannot be installed offline without intervention

### ISSUE THREAD

**Issue by jeff-hillman** [canonical/microk8s#3863]
#### Summary

For all other Canonical supplied addons for MicroK8s, using the sideload method allows the addon to be enabled.  However, the observability addon has a requirement to grab an external resource.

specifically, it tries to reach out to prometheus-community.github.io
#### What Should Happen Instead?

One would expect that this addon would behave like all others and be able to be installed fully from a sideload, or have the external helm chart built into the snap.
#### Reproduction Steps

1. Install microk8s on on online machine
2. enable the observability addon
3. run `microk8s images export-local > images.tar`
4. copy the microk8s images.tar to an offline machine
5. Install microk8s in an offline fashion (local snap)
6. load in the images `microk8s images import < images.tar`
7. microk8s enable observability

#### Introspection Report

cannot retrieve from this environment
#### Can you suggest a fix?

Include the helm chart within the snap
#### Are you interested in contributing with a fix?

no

**Comment by nrobinaubertin** [comment]
I'm having the same issue while trying to bootstrap a microk8s cluster while being completely offline on my laptop.

To do that, I download the snap (the classic 1.26/stable in my case), I spawn a cluster (with the dns, ingress and registry plugins) and let it download all the images it needs.
Then I'm exporting the images using `export-local` to create a tar file with all the images.

I create a VM to host the new cluster (the VM is created with multipass) and I'm adding a new virtual IP on its loopback to be used by microk8s when I'm going offline.
I shutdown my wifi, install the snap in the VM and then try to sideload the images.
That always fails.

But if I try to pull the name of the images one by one and sideload them one by one, then it works. I suspect the [export-local](https://github.com/canonical/microk8s/blob/master/scripts/wrappers/images.py#L46) script to be faulty.

### Commands used

On the host:
```shell
sudo snap install microk8s --channel=1.26/stable --classic
sudo microk8s.enable ingress dns hostpath-storage registry
# wait for everything to be up, and then:
microk8s images export-local > images-microk8s-only.tar
# if I want only one image:
microk8s ctr i export calico-node.tar docker.io/calico/node:v3.23.5
```

On the VM:
```
sudo snap install microk8s_5219.snap --classic
sudo microk8s ctr images import images-microk8s-only.tar
```
The second command gives me the output:
```
ctr: content digest sha256:19f468f7dde9dc85d1576e6eb244b190661764199e21fcb53d84378bef16e334: not found
```

But if I sideload only one image:
```
sudo microk8s ctr images import calico-node.tar
```
Then I have:
```
unpacking docker.io/calico/node:v3.23.5 (sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934)...done
```
And I can see on the `kubectl get pod -A` side that the container starts.

**Comment by neoaggelos** [comment]
Hi @nrobinaubertin 

Can you please elaborate with the list of images that are exported at `images-microk8s-only.tar`?

The command output from `microk8s ctr image ls` from that cluster should be a good starting point. That way we can investigate further, as we have seen a few issue with different images in the past. Thanks!

**Comment by nrobinaubertin** [comment]
[Here](https://paste.ubuntu.com/p/VpHYDPH2cN/) is the output of `microk8s ctr image ls`.

Output of `microk8s images export-local > images-microk8s-only.tar`:
```
Checking docker.io/calico/cni:v3.23.5
Checking docker.io/calico/cni@sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc
Checking docker.io/calico/kube-controllers:v3.23.5
Checking docker.io/calico/kube-controllers@sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb
Checking docker.io/calico/node:v3.23.5
Checking docker.io/calico/node@sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934
Checking docker.io/cdkbot/hostpath-provisioner:1.4.2
Checking docker.io/cdkbot/hostpath-provisioner@sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c
Checking docker.io/coredns/coredns:1.9.3
Checking docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a
Checking docker.io/library/busybox:1.28.4
Checking docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
Checking docker.io/library/registry:2.8.1
Checking docker.io/library/registry@sha256:8c51be2f669c82da8015017ff1eae5e5155fcf707ba914c5c7b798fbeb03b50c
Checking registry.k8s.io/ingress-nginx/controller:v1.5.1
Checking registry.k8s.io/ingress-nginx/controller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629
Checking registry.k8s.io/pause:3.7
Checking registry.k8s.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
```

Output of `microk8s version` (on the host, like the previous commands):
```
MicroK8s v1.26.4 revision 5219
```

**Comment by neoaggelos** [comment]
Hi @nrobinaubertin, sorry for taking long.

Can you check whether specifying the platform during import solves your problem?

```bash
microk8s ctr images import images.tar --platform amd64
```

I was able to resolve the issue:
```bash
root@u2:~# microk8s ctr i import images.tar
ctr: content digest sha256:19f468f7dde9dc85d1576e6eb244b190661764199e21fcb53d84378bef16e334: not found
root@u2:~# microk8s ctr images import --platform amd64 images.tar 
unpacking docker.io/calico/cni:v3.23.5 (sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc)...done
unpacking docker.io/calico/cni@sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc (sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc)...done
unpacking docker.io/calico/kube-controllers:v3.23.5 (sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb)...done
unpacking docker.io/calico/kube-controllers@sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb (sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb)...done
unpacking docker.io/calico/node:v3.23.5 (sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934)...done
unpacking docker.io/calico/node@sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934 (sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934)...done
unpacking docker.io/cdkbot/hostpath-provisioner:1.4.2 (sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c)...done
unpacking docker.io/cdkbot/hostpath-provisioner@sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c (sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c)...done
unpacking docker.io/coredns/coredns:1.9.3 (sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a)...done
unpacking docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a (sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a)...done
unpacking docker.io/library/busybox:1.28.4 (sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47)...done
unpacking docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47 (sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47)...done
unpacking docker.io/library/registry:2.8.1 (sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb)...done
unpacking docker.io/library/registry@sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb (sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb)...done
unpacking registry.k8s.io/ingress-nginx/controller:v1.5.1 (sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629)...done
unpacking registry.k8s.io/ingress-nginx/controller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629 (sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629)...done
unpacking registry.k8s.io/pause:3.7 (sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c)...done
unpacking registry.k8s.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c (sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c)...done
```

Thanks!

**Comment by nrobinaubertin** [comment]
This works indeed. Thanks for taking the time to find the issue !

**Comment by gentoo9ball** [comment]
> Hi @nrobinaubertin, sorry for taking long.
> 
> Can you check whether specifying the platform during import solves your problem?
> 
> ```shell
> microk8s ctr images import images.tar --platform amd64
> ```
> 
> I was able to resolve the issue:
> 
> ```shell
> root@u2:~# microk8s ctr i import images.tar
> ctr: content digest sha256:19f468f7dde9dc85d1576e6eb244b190661764199e21fcb53d84378bef16e334: not found
> root@u2:~# microk8s ctr images import --platform amd64 images.tar 
> unpacking docker.io/calico/cni:v3.23.5 (sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc)...done
> unpacking docker.io/calico/cni@sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc (sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc)...done
> unpacking docker.io/calico/kube-controllers:v3.23.5 (sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb)...done
> unpacking docker.io/calico/kube-controllers@sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb (sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb)...done
> unpacking docker.io/calico/node:v3.23.5 (sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934)...done
> unpacking docker.io/calico/node@sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934 (sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934)...done
> unpacking docker.io/cdkbot/hostpath-provisioner:1.4.2 (sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c)...done
> unpacking docker.io/cdkbot/hostpath-provisioner@sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c (sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c)...done
> unpacking docker.io/coredns/coredns:1.9.3 (sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a)...done
> unpacking docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a (sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a)...done
> unpacking docker.io/library/busybox:1.28.4 (sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47)...done
> unpacking docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47 (sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47)...done
> unpacking docker.io/library/registry:2.8.1 (sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb)...done
> unpacking docker.io/library/registry@sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb (sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb)...done
> unpacking registry.k8s.io/ingress-nginx/controller:v1.5.1 (sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629)...done
> unpacking registry.k8s.io/ingress-nginx/controller@sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629 (sha256:4ba73c697770664c1e00e9f968de14e08f606ff961c76e5d7033a4a9c593c629)...done
> unpacking registry.k8s.io/pause:3.7 (sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c)...done
> unpacking registry.k8s.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c (sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c)...done
> ```
> 
> Thanks!

@neoaggelos did you use the pull request when testing? I was unable to get a successful result using the platform command you used. When specifying platform amd64, import still fails to find a digest tied to the 386 busybox image.

**Comment by neoaggelos** [comment]
Hi @gentoo9ball, can you share the list of images `microk8s ctr image ls -q` this fails with? How are you exporting your images? Thank you!

**Comment by gentoo9ball** [comment]
@neoaggelos sure thing...

docker.io/bitnami/mariadb:10.6.8-debian-11-r9
docker.io/bitnami/mariadb@sha256:f9af41ce372cd4d26d720d0f7ee079713e54a05b43914aca696896c1325f2641
docker.io/bitnami/mongodb:6.0.4-debian-11-r10
docker.io/bitnami/mongodb@sha256:016dce036593c1e4e845d0d988a7aaeacbea31575d494f4ab40c339efb876c7a
docker.io/bitnami/postgres-exporter:0.8.0-debian-10-r99
docker.io/bitnami/postgres-exporter@sha256:d5a45468d8f586c8cd6e052c5d7840f53e61b528a64484b9f6b6a37ec590c156
docker.io/bitnami/postgresql:12.7.0
docker.io/bitnami/postgresql@sha256:004606c4f3ddc629f628d74fb53778a2f497ee0bf61f7b119e5efcc4f0ded67a
docker.io/bitnami/redis-exporter:1.12.1-debian-10-r11
docker.io/bitnami/redis-exporter@sha256:c7250bf30ecba208e28e234cd3baa46930e650239ebb2b780edd25ea352fdfa1
docker.io/bitnami/redis:6.0.9-debian-10-r0
docker.io/bitnami/redis@sha256:0617d340ee21c60f2ee3075dd0a014741f5b54b02e922a12d935c5454103e5f5
docker.io/calico/cni:v3.23.5
docker.io/calico/cni@sha256:7ca5c455cff6c0d661e33918d95a1133afb450411dbfb7e4369a9ecf5e0212dc
docker.io/calico/kube-controllers:v3.23.5
docker.io/calico/kube-controllers@sha256:58cc91c551e9e941a752e205eefed1c8da56f97a51e054b3d341b67bb7bf27eb
docker.io/calico/node:v3.23.5
docker.io/calico/node@sha256:b7f4f7a0ce463de5d294fdf2bb13f61035ec6e3e5ee05dd61dcc8e79bc29d934
docker.io/cdkbot/hostpath-provisioner:1.4.2
docker.io/cdkbot/hostpath-provisioner@sha256:b8e7be62e9c072adc52ca7e0ff4cffd3687cc39e98171b07884c456104e3fc5c
docker.io/collabora/code:21.11.3.6.1
docker.io/collabora/code@sha256:4774df73648187bfffc62ae742d4a1b03e3ea2a510f19be6072aa4ec7a70f682
docker.io/coredns/coredns:1.9.3
docker.io/coredns/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a
docker.io/jgraph/drawio:latest
docker.io/jgraph/drawio@sha256:a305230f1dbc1fb06d071d89ec333f4976051fbcaf721e1367f81e81eca5f2f0
docker.io/jupyterhub/configurable-http-proxy:4.5.3
docker.io/jupyterhub/configurable-http-proxy@sha256:9e2c0107c7a35410bb89b22dd037bd6be748eb23c838941ae6fb30254d53d2e6
docker.io/jupyterhub/k8s-hub:2.0.0
docker.io/jupyterhub/k8s-hub@sha256:cd0e191901292364fbf219a4b2fd64f5b98ba02e9d9145a920105fea6e49bf71
docker.io/kubernetesui/dashboard:v2.7.0
docker.io/kubernetesui/dashboard@sha256:2e500d29e9d5f4a086b908eb8dfe7ecac57d2ab09d65b24f588b1d449841ef93
docker.io/kubernetesui/metrics-scraper:v1.0.8
docker.io/kubernetesui/metrics-scraper@sha256:76049887f07a0476dc93efc2d3569b9529bf982b22d29f356092ce206e98765c
docker.io/library/busybox:latest
docker.io/library/busybox:stable
docker.io/library/busybox@sha256:05a79c7279f71f86a2a0d05eb72fcb56ea36139150f0a75cd87e80a4272e4e39
docker.io/library/busybox@sha256:9e2bbca079387d7965c3a9cee6d0c53f4f4e63ff7637877a83c4c05f2a666112
docker.io/library/nextcloud:25.0.4-apache
docker.io/library/nextcloud@sha256:0f452ad89a8b2312474eabf6c1b5ceda81128fa20f5c2ae8decf27f5f13e7c58
docker.io/library/postgres:9.6-alpine
docker.io/library/postgres@sha256:8342bcb43446694428ec6594e72e4299692854f0fc3aca090b0ab46f4c7f32a1
docker.io/library/registry:2.8.1
docker.io/library/registry@sha256:dbaa3e69f563fc146f3337eb9de422f74f6765bf0203c891ddfbd74a6f9b56eb
docker.io/mattermost/mattermost-team-edition@sha256:7a7acbc25c1948081eedb3c1f98f5a7ffb75f7bc84359ab8e457f94766d9a014
docker.io/minio/mc:RELEASE.2018-07-13T00-53-22Z
docker.io/minio/mc@sha256:88890e23ba30a056293bf4e83563d18ac51b4102e784c939db541bcca53c05ac
docker.io/minio/minio:RELEASE.2017-12-28T01-21-00Z
docker.io/minio/minio@sha256:3611f1644cf5447e2f3639b4212ade26155f6a0632bef155c4d6510811c1fe1d
docker.io/mpepping/cyberchef:latest
docker.io/mpepping/cyberchef@sha256:179b8249d15cb0a6b22634c0cd47547c98694dc47cdb543f3759cd6a1ba5d0a2
docker.io/openebs/node-disk-manager:2.0.0
docker.io/openebs/node-disk-manager@sha256:1a032535fc6c1cb070dcea54933da278fe294e58d542be8791fa12201213e4ad
docker.io/openebs/node-disk-operator:2.0.0
docker.io/openebs/node-disk-operator@sha256:60fdfea034ee6df8f3956b7fc09d0bbbd66849d98efc128557afdcbcde28e938
docker.io/openebs/provisioner-localpv:3.3.0
docker.io/openebs/provisioner-localpv@sha256:9944beedeb5ad33b1013d62da026c3ac31f29238b378335e40ded2dcfe2c56f4
docker.io/opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
docker.io/opensearchproject/logstash-oss-with-opensearch-output-plugin@sha256:88b87ecfff7a28f11b72c10e2e1e5bdbddcff3f2b00e69cef51401db83deee57
docker.io/opensearchproject/opensearch-dashboards:2.6.0
docker.io/opensearchproject/opensearch-dashboards@sha256:fc18bb5001caa43e1814d026a80a2175be0147c79410b5cbe15caca6260c7c6e
docker.io/opensearchproject/opensearch:2.6.0
docker.io/opensearchproject/opensearch@sha256:40f5bb40a543f7ea6458bc0ecffc7679c9df6f8836a9e3781a78829d587ef552
ghcr.io/linuxserver/bookstack:version-v21.12
ghcr.io/linuxserver/bookstack@sha256:f05447347ff102589c7db6f51ff07a2717c6a8cb2bd557a8b4ffa27ef1cefc7a
k8s.gcr.io/kube-scheduler:v1.23.10
k8s.gcr.io/kube-scheduler@sha256:07d72b53818163ad25b49693a0b9d35d5eb1d1aa2e6363f87fac8ab903164a0e
quay.io/jetstack/cert-manager-cainjector:v1.11.0
quay.io/jetstack/cert-manager-cainjector@sha256:5c3eb25b085443b83586a98a1ae07f8364461dfca700e950c30f585efb7474ba
quay.io/jetstack/cert-manager-controller:v1.11.0
quay.io/jetstack/cert-manager-controller@sha256:d429b6d696e0ef47cff1d15241c6ffaac351e38ac22664b82fafa771d615b89a
quay.io/jetstack/cert-manager-webhook:v1.11.0
quay.io/jetstack/cert-manager-webhook@sha256:6730d96fc382a57cde4f7519d2a32b40013e0d3bace2ea0579c7c051fbbd608d
quay.io/metallb/controller:v0.13.3
quay.io/metallb/controller@sha256:12fd9f57369003ea2cf503e4464baf70de08d00e689412277125ea605f7260e8
quay.io/metallb/speaker:v0.13.3
quay.io/metallb/speaker@sha256:839ca1f96149ec65b3af5aa20606096bf1bd7d43727611a5ae16de21e0c32fcd
quay.io/wekan/wekan:v6.79
quay.io/wekan/wekan@sha256:5bf7f52847bb7f66b050aae31d31f2f3dabbe9d5ee4e3678bfc2eb0707e09c6d
registry.gitlab.com/gitlab-org/build/cng/certificates:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/certificates@sha256:f7c6d4323a9c7ac8d59c9df5a5f297c58e630f1246d4380db2e655d67446fe5f
registry.gitlab.com/gitlab-org/build/cng/gitaly:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitaly@sha256:906d4076a80ba26b3c67de40f537e27f14dac19f125c5d32219a761ab4362a48
registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry:v3.69.0-gitlab
registry.gitlab.com/gitlab-org/build/cng/gitlab-container-registry@sha256:6997d13192cc3d2a9109a5d4fe0b54195e0db083c835764d46d0b8521f7975df
registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter:12.1.1
registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter@sha256:bb626970cfcdb99668fef26f60ccf2996c8457b9143b2f390b8050f797368f5c
registry.gitlab.com/gitlab-org/build/cng/gitlab-kas:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-kas@sha256:1abb7f5ef9799b083109564b86ec8c8cd9e5ab8b6145765e8bec9b15d5b58b78
registry.gitlab.com/gitlab-org/build/cng/gitlab-shell:v14.18.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-shell@sha256:8dbe472bb76c8b94b19e90a1668ed3508050082d54b5f0f298065476b73a1133
registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ee@sha256:395efe01851a26a65711a91e613544499e6d1281a92f5c9e207c4b17e019b9f2
registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee@sha256:a314a90b27b2e6af72cd6bb179bc8cdf90178601f87e24bee3ae23dbe50ad24a
registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ee@sha256:c6ce1ff7454aba7951df1d02b3c2fc18acd43ddc7a425648ea9c87c8b5764289
registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee:v15.10.0
registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ee@sha256:fab5790791868824b159904dadbff4a5f57e5b1c83a75129fc0251f6f6416813
registry.k8s.io/ingress-nginx/controller@sha256:15be4666c53052484dd2992efacf2f50ea77a78ae8aa21ccd91af6baaa7ea22f
registry.k8s.io/metrics-server/metrics-server:v0.5.2
registry.k8s.io/metrics-server/metrics-server@sha256:6385aec64bb97040a5e692947107b81e178555c7a5b71caa90d733e4130efc10
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.2
registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:a13bff2ed69af0cf4270f0cf47bdedf75a56c095cd95b91195ae6c713a9b1845
registry.k8s.io/sig-storage/csi-provisioner:v3.3.0
registry.k8s.io/sig-storage/csi-provisioner@sha256:ee3b525d5b89db99da3b8eb521d9cd90cb6e9ef0fbb651e98bb37be78d36b5b8
registry.k8s.io/sig-storage/livenessprobe:v2.8.0
registry.k8s.io/sig-storage/livenessprobe@sha256:cacee2b5c36dd59d4c7e8469c05c9e4ef53ecb2df9025fa8c10cdaf61bce62f0
registry.k8s.io/sig-storage/nfsplugin:v4.2.0
registry.k8s.io/sig-storage/nfsplugin@sha256:1d9f524c0fd5d714cf274a0ddf5dceebeb1848349de5687e530c33dd2675e4ba
sha256:053a6428019cd08d4c687d78353b996220ccff7722e146990f490a16b9cdf717
sha256:075b18d7ddcee9fbf88195905a1d9c303dcab593eb656b34988984c077336a24
sha256:07655ddf2eebe5d250f7a72c25f638b27126805d61779741b4e62e69ba080558
sha256:10bffc52595c39b5efbb95ee039ac3ab9050b0f7f97bfbd4febeac0c1da1d19d
sha256:115053965e86b2df4d78af78d7951b8644839d20a03820c6df59a261103315f7
sha256:1b597b32680dbf5125d35207f5418e97bc1860bc1787e671837252330da0f06c
sha256:1c979d623de9aef043cb4ff489da5636d61c39e30676224af0055240e1816382
sha256:322aa02bbb15409fdbd444e6f3de44013dbb33e7ea5196e8fd54c64cb0345af3
sha256:3359982f8b183f076ac374b5bc8f07d4aa5076f54f58f7fbc3bb02d0b17d3af5
sha256:3fca80a3830dd96fb4e311135d84df286b5909ba97de90c5693b225950ceff9c
sha256:438dce41a980d758258892a25ea6fd6e27f28197dee1726d5ba7e449f388b37f
sha256:45799057e19c0d1b38a810811095f7351ef8c456323c56cee6b5a21103b29ae9
sha256:459a1870d6dedf1a2dd4e6ba09101ee51ee21b467c568ddf61f02bd6d7d68f7a
sha256:4cbcabaa33be3767f6617de9fd569a028f42cc8be1bb0a7ed2dafc233670497a
sha256:5185b96f0becf59032b8e3646e99f84d9655dff3ac9e2605e0dc77f9c441ae4a
sha256:51da1a29b7bfa39fd7f71cacd70bbac80c2400a1663a0d52888a0343f31a4140
sha256:57c9b06c2af3045b124942d4073ee6b53f642c21cbe1e853b7c484edb07467d9
sha256:5e7af2c49d882a8ece68514bdb3521f2a0d3f65b8f15e0d1183ce76f388bd438
sha256:6454e421feabe7a9a0ad21d1c77046560b25a57f3d477695021d2a9030af2c74
sha256:68ba74862b3a66a53281051014a2206de30df0235848a956a9d196949e7a5433
sha256:739e82fed8b2ca886eb4e5cce90ad4b2518c084e845b56f79d03f45d81b8f6c3
sha256:75ed1f91b7955ea4c67980addbd905fea6da153a1d615a1b288ee3c95d06a297
sha256:7744eedd958ffb7011ea5dda4b9010de8e69a9f114ba3312c149bb7943ddbcd6
sha256:7a44beae07710c40adfc11d4d3c171d2abcbc8d53a32239b6e8b3783923982c6
sha256:8079c9849308d93e1b6517246bcc5ff21bca7fe243c319d69b0b383686f926ec
sha256:827365c7baf137228e94bcfc6c47938b4ffde26c68c32bf3d3a7762cd04056a5
sha256:896a3ee2cfa6e44d4224d34a2f7ca78146ab530f13df08003b1b5b42b0adcc50
sha256:89eae75066cb7e69d90bcaf06429e81fcf4a4868cf44491fc79822ca143b42a4
sha256:8cf453f32acfd0d1e8e60aac977dd3505ea77ca5c208e45021b7395cd23a1fb1
sha256:931dbfd16f87c10b33e6aa2f32ac2d1beef37111d14c94af014c2c76f9326992
sha256:95b26d2e8788073fc3ed6ccf026178f8e7aedbdbd3eb624892ad186b7edaae6e
sha256:9604d46e1ddae3640a4d7a3b157560f0da5ae2a23fdfea4706727d2fec9a1b11
sha256:97fabc1bd6c2671f5ab40f8347e6712487204b18f6f39f63e3481d0861b548e0
sha256:9d956e1ef1a61a4ddb3027663d6e304ec00dd5d457ab5cfe7810447b48b26312
sha256:a26ccff6c31b4f115cb9adbc705624768274f271d7629365b6896a385456a511
sha256:a4962689e3f62f6bfcfdfa3459c046a55d1879cf7f029b2c376b8090a860c0f8
sha256:ab76b5caf097cfca5f316f412b3a05f3371f987bcd195a467768f952806b21e7
sha256:af2c3e96bcf1a80da1d9b57ec0adc29f73f773a4a115344b7e06aec982157a33
sha256:b410b023b4c3ad365f110ee34fefcf521703b35f0f98bbc780d5a9c004d5de17
sha256:b6e6ee0788f2079219fecb418f573bbaad4c07f6f82b712ccc72684db8cc2deb
sha256:bc5bcad49545ba6e639dcba6df128f9a19006a5f70ceedfeb584c8ebfa5debc6
sha256:bd8b5f4d1eb10b4f198ba5a9fdd40563d9b8a300b33c5f61c85c26cc0c317f99
sha256:c3f1478f398eabc2c0e77fe95715886fd1e57b6049a12fe4b46eae0dcecded00
sha256:c5880357c5334ed1777c3333e7a873efb655586c53a911e10c4857b6434207fe
sha256:c670e98c71bb4688f9debbadceb3ccd625bc2ca9ea722adda965e19713971747
sha256:d5c0efb802d9530c3532a312c88498b4efba8a5218e1e36e6d70b6f6c176d708
sha256:d7205f2ca5ef7c796e9ce5a4822bbefdd3ad40ef455b57bb99564c68ff08a77a
sha256:e3d823194afdb27c1caed606b638ecf05473888d840362c63bb48f8c85380bcf
sha256:e899260153aedc3a54e6b11ee23f11d96a01236ccd556fbd0372a49d07a7bdb8
sha256:ea5536b1fa4a86e5ecf0803b7a1118d797f5ef51d2f452acf0b701d64dc6fcd9
sha256:ea6670b27349103b781dbb68f8d2a891ba0e17258c5eadf96661154dcda0ad5e
sha256:ee62869f5c8d54f8878adc9f77d9de1b8fdeae79eb5ce7501ad755454b5d6220
sha256:f0b6d6172e3e7165555b89727089f5693a0d7624baedbccbf3a0523f49d089f3
sha256:f5352b75f67e2e2df2bf2d96509248d1f618b8aa66d8b8c89d21e29111424881
sha256:f73640fb506199d02192ef1dc99404aeb1afec43a9f7dad5de96c09eda17cd71
sha256:feebbf30f81c1a63983c81e374e1a9021818e943cde1530381ae91f9dab777f9

**Comment by gentoo9ball** [comment]
I ended up deleting the image that referenced the image that wasn't exported, then repeating the process several times until all of those the images weren't in the export. Then I manually pulled the ones with problems and imported those individually. Not ideal for sure, but it did eventually work.
