### ISSUE TITLE
Hostpath PVCs don't get provisioned automatically on RHEL

### ISSUE THREAD

**Issue by arjen-s** [canonical/microk8s#3875]
#### Summary
I have 2 identical setups with a clean 1.26 microk8s, hostpath-storage and registry add ons.
One is running on Ubuntu and the other on RHEL8 (CIS L2 image).

On Ubuntu the creation of a PVC with storage class 'microk8s-hostpath' automatically triggers the creation of it's PV, but on RHEL the PVC remains unbound and the PV never gets created.
When I create the PV manually the PVC does bind to it and all seems to work correctly, but this behaviour is different from the Ubuntu behaviour.

Checking the provisioner pods logs on Ubuntu shows me this:
```
I0327 10:14:01.757094       1 hostpath-provisioner.go:96] Using busybox image: "busybox:1.28.4"
I0327 10:14:01.775852       1 leaderelection.go:248] attempting to acquire leader lease kube-system/microk8s.io-hostpath...
I0327 10:14:20.029273       1 leaderelection.go:258] successfully acquired lease kube-system/microk8s.io-hostpath
I0327 10:14:20.029512       1 controller.go:810] Starting provisioner controller microk8s.io/hostpath_hostpath-provisioner-78cb89d65b-snn9p_9ce1a44b-f709-42d4-be14-8a9349595d51!
I0327 10:14:20.089337       1 event.go:285] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"microk8s.io-hostpath", UID:"41af02bd-393b-48a3-89da-2a742ad9f78f", APIVersion:"v1", ResourceVersion:"1173000", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' hostpath-provisioner-78cb89d65b-snn9p_9ce1a44b-f709-42d4-be14-8a9349595d51 became leader
I0327 10:14:20.130685       1 controller.go:859] Started provisioner controller microk8s.io/hostpath_hostpath-provisioner-78cb89d65b-snn9p_9ce1a44b-f709-42d4-be14-8a9349595d51!
```

Whereas on RHEL it gives:
```
I0327 13:49:09.235985       1 hostpath-provisioner.go:97] Using busybox image: "busybox:1.28.4"
I0327 13:49:09.236348       1 leaderelection.go:248] attempting to acquire leader lease kube-system/microk8s.io-hostpath...
E0327 13:49:39.236889       1 leaderelection.go:330] error retrieving resource lock kube-system/microk8s.io-hostpath: Get "https://10.152.183.1:443/api/v1/namespaces/kube-system/endpoints/microk8s.io-hostpath": dial tcp 10.152.183.1:443: i/o timeout
```

Also note that I do not have the 'microk8s.io-hostpath' endpoint on RHEL whereas I do on Ubuntu.

#### What Should Happen Instead?
The behaviour should be consistent between the two OS'es and in both cases the PVC should be provisioned automatically.

#### Reproduction Steps
Install 1.26 microk8s onto RHEL (CIS L2 image) using snap
Enable hostpath-storage add on
Enable registry add on
Note the PVC never binding

#### Introspection Report
[inspection-report-20230327_124929.tar.gz](https://github.com/canonical/microk8s/files/11079350/inspection-report-20230327_124929.tar.gz)

#### Can you suggest a fix?
Temporary work around is to manually create a PV for each PVC, but this doesn't explain the inconsistent behaviour.

**Comment by neoaggelos** [comment]
Hi @arjen-s, thank you for raising the issue.

Could this be related to firewall dropping network traffic from pods? Can you check if the steps described in the "Pod communication problems when using firewall-cmd (Fedora etc)" section in https://microk8s.io/docs/troubleshooting help?

**Comment by arjen-s** [comment]
Thanks @neoaggelos I'll definitely have a look at that as well, but I'm starting to suspect it's more related to Traefik and its CNI. I'll do more testing and will update this ticket when i know more.

**Comment by arjen-s** [comment]
Thanks a lot for your assistance @neoaggelos, I believe you were right that the problem was with the firewall (iptables in my case) blocking the cni subnet traffic. I have not defined a new ruleset for it, but disabling iptables altogether seems to have resolved the communication issues and I'll figure the rest out myself later.
