### ISSUE TITLE
preserve  CALICO_IPV4POOL_CIDR configuration after refresh

### ISSUE THREAD

**Issue by miro-balaz** [canonical/microk8s#3876]
#### Summary

My cluster became unusable after automatically refreshed from 1.24.10 to 1.24.12, after unsuccesfully trying to restore quorum i found that CIDR configuration was 10.1.0.0 (in ds calico-node) inside the database which was probably the cause of problem and i had to revert snap (to use database files from older revision), after revert CIDR was configured  correctly and everything magically worked again. 

#### What Should Happen Instead?

CIDR setting from new cni.yaml is carried over to the new version or is NOT automatically applied. Another approach is to have this CIDR setting in args directory and carry it to joining node, because during refresh it is maybe not possible to query database and the actual cni.yaml on node might be left with default CIDR

#### Why is this important?

If CIDR is changed unexpectedly it causes problems.

#### Are you interested in contributing to this feature?

yes

**Comment by neoaggelos** [comment]
Hi @miro-balaz, thanks for raising this. Seems to be a defect from the calico upgrade hook https://github.com/canonical/microk8s/blob/1.24/scripts/calico/upgrade.py#L162, where we get the new Calico version but only patch the autodetection method.

We will see how we can deal with this scenario. Would an "opt out" mechanism be acceptable to you? As in, creating a lockfile like `/var/snap/microk8s/current/var/lock/no-manage-calico` that tells MicroK8s to simply leave Calico be?

I am still a bit worried though that it occured in 1.24.10 -> 1.24.12. It should not be, the calico upgrade should only run when upgrading from a previous minor version.

**Comment by miro-balaz** [comment]
In my opinion, another mistake with this process is an assumption that cni.yaml on host corresponds to cni.yaml that was deployed to cluster. It might happen that cluster runs on different version that happens to be on host joining the cluster/ refreshing. It should be documented or automated to copy cni.yaml to joining cluster. Or there should be one designated "master", that is only allowed to. Or it can be stored in kubernetes which node has applied its config and only allow to reapply that one. But it might make problem if that node is lost. Definitelly there is no easy solution to this. It should be at least documented that "before joining, copy(or better merge) all the configuration including cni.yaml"
