### ISSUE TITLE
Pre-installing Microk8s in VM image causes node not to be ready

### ISSUE THREAD

**Issue by arjen-s** [canonical/microk8s#3879]
#### Summary
When I pre-install a single-node instance of Microk8s (1.26) in a VM image in Azure (using Packer) and I create a new VM from this image the hostname and IP of the VM will be different from the hostname & IP when the image was created and Microk8s will list two nodes, one with the hostname of when the image was created and one named after the current hostname. Sometimes both nodes will be in a NotReady state and sometimes one may work, but I have yet to find a logic.

I also tried by setting a hard-coded hostname in the kubelet config, /var/snap/microk8s/current/args/kubelet, 
--hostname-override=my-node-1 and adding a record for my-node-1 (127.0.0.1) in the hosts file before creating the image.
Then, when creating a VM of the image, there's only one node as intended, my-node-1, but this is in a NotReady state.

I have also refreshed both the certificates and tokens after as suggested [here](https://github.com/canonical/microk8s/issues/3753), but that didn't make a difference.

Is there a way to refresh the node details or for the node to leave and re-join the cluster on first boot of the VM (or similar) so I can distribute a pre-configured Microk8s instance in the image?

#### What Should Happen Instead?
One node, my-node-1, should be listed and should be in a Ready state.

#### Introspection Report
[inspection-report-20230328_144443.tar.gz](https://github.com/canonical/microk8s/files/11090986/inspection-report-20230328_144443.tar.gz)

**Comment by neoaggelos** [comment]
Hi @arjen-s 

I believe running a `microk8s reset` on the first boot of the machine (but after reaching network.target) can get you quite far. As part of the reset, the "old" node should also not appear in the node list. Having said that, it's been some time since I attempted this so there might be issues, happy to discuss with you further.

I would recommend that you avoid hand-picking /etc/hosts entries for this.

**Comment by arjen-s** [comment]
@neoaggelos
This may be more of a snap issue then a Microk8s one, but when i run the `microk8s reset` command (discussed above) as part of a systemd service with selinux enabled the selinux policies will prevent it from executing files in /var (e.g. microk8s). You wouldn't happen to have a fix for this, do you?

I have been troubleshooting this for some time now but selinux is clearly not my strong point...

Thanks!
