### ISSUE TITLE
gpu addon cannot be installed offline using just image export/import

### ISSUE THREAD

**Issue by jeff-hillman** [canonical/microk8s#3881]
#### Summary

For all other Canonical supplied addons for MicroK8s, using the sideload method allows the addon to be enabled. However, the GPU addon has a requirement to grab an external resource.

specifically, it tries to reach out to nvidia to download drivers

#### What Should Happen Instead?

One would expect that this addon would behave like all others and be able to be installed fully from a sideload having at least a default set of drivers built into the snap

#### Reproduction Steps

1. Install microk8s on on online machine
2. enable the gpu addon
3. run microk8s images export-local > images.tar
4. copy the microk8s images.tar to an offline machine
5. Install microk8s in an offline fashion (local snap)
6. load in the images microk8s images import < images.tar
7. microk8s enable gpu
#### Introspection Report

cannot retrieve from a secure environment
#### Can you suggest a fix?

having drivers preloaded into the snap to make it no longer dependant upon internet access
#### Are you interested in contributing with a fix?

no

**Comment by ktsakalozos** [comment]
Hi @jeff-hillman thank you for reporting this. Indeed some addons may be reaching out to the internet making them inappropriate for offline deployments.

One workaround you could try is to install the nvidia drivers manually before enabling the gpu addon. The nvidia operator should be able to skip the driver installation in this case.
