### ISSUE TITLE
After disabling HA - inspect indicates Service snap.microk8s.daemon-flanneld is not running

### ISSUE THREAD

**Issue by maxshlain** [canonical/microk8s#3882]
#### Summary
**Sometimes**, after disabling HA microk8s becomes unresponsive:

/snap/bin/microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

/snap/bin/microk8s inspect
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
 FAIL:  Service snap.microk8s.daemon-flanneld is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-flanneld
 FAIL:  Service snap.microk8s.daemon-etcd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-etcd
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

The only known WA is to reinstall the microk8s

[inspection-report-20230328_171431.tar.gz](https://github.com/canonical/microk8s/files/11092855/inspection-report-20230328_171431.tar.gz)

**Comment by maxshlain** [comment]
[inspection-report-20230328_171431.tar.gz](https://github.com/canonical/microk8s/files/11092848/inspection-report-20230328_171431.tar.gz)

**Comment by berkayoz** [comment]
Hey @maxshlain ,
Thanks for reaching out. Once you are in HA mode (ie you have at least 3 control plane nodes) you cannot drop to a non-HA setup without having the cluster freeze. The reason is that the cluster loses quorum and the datastore locks up so it would not risk any form of corruption. To recover from this state (lost quorum) you should follow the instructions at https://microk8s.io/docs/restore-quorum
