### ISSUE TITLE
microk8s ctr i import myimage but not found

### ISSUE THREAD

**Issue by logici** [canonical/microk8s#3894]
#### Summary

When I use command `microk8s ctr i import`, it responses `unpacking xxx done` and I can query it by `microk8s ctr i ls`. However, when I want to use the image by `kubectl apply my.yaml`, it fail to find the image.

```
$ microk8s.ctr i import myimage.tar
unpacking docker.io/library/myimage:0.1 (sha256:xxxxxxxxxxxxxx)...done

$ microk8s.ctr i ls | grep myimage
docker.io/library/myimage:0.1                                                                                                 
application/vnd.docker.distribution.manifest.v2+json      
sha256:xxxxxxxxxxxxxxxx 35.5 MiB  linux/amd64                                                                                             
io.cri-containerd.image=managed

$ microk8s kubectl myimage.yaml
$ microk8s.ctr i ls | grep myimage
docker.io/library/myimage:0.1                                                                                                  
text/html                  
sha256:aaaaaaaaaaaaaaaaaa 241.3 KiB -                                         
io.cri-containerd.image=managed
```
When I check image again, it changes into `text/html` from `application/vnd.docker.distribution.manifest.v2+json` and `kubectl describe pod ` tell me that not found the image. My image is built by `docker build` and saved by `docker save`.

My environment is microk8s 1.24

**Comment by ktsakalozos** [comment]
Hi @logici could you please follow the instructions at https://microk8s.io/docs/registry-images and tell me if they fail at any point? I am trying to reproduce the issue.

**Comment by ktsakalozos** [comment]
Anything special in the `Dockerfile`? Could you share that, or at least a flavor of it?

**Comment by logici** [comment]
I am so sorry that I try again and it can not be reproduced. A new image I rebuild and the old one I built before are both failed to reproduce.  When I reproduce it steadily, I will update the issue. Btw, how to analyse this problem and what key words I can search in Google. Thanks for your reply.

**Comment by ktsakalozos** [comment]
I am closing this issue for now, please feel free to reopen it as soon as you have more information on it.
