### ISSUE TITLE
Simple one node cluster - bridge is DOWN but communication works

### ISSUE THREAD

**Issue by MaciekLeks** [canonical/microk8s#3896]
#### Summary
Can't sniff vxlan.calico and bridge traffic in standalone installation. I do not know if it's an error while it works but how? I do not know.

#### What Should Happen Instead?
I've configured my microk8s instance (one node). Works well. I've started digging in some linux network internals and I was dumbfounded looking at this:

$ ip -c -br link
```
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
enp0s3           UP             08:00:27:ad:36:a3 <BROADCAST,MULTICAST,UP,LOWER_UP> 
enp0s8           UP             08:00:27:86:35:40 <BROADCAST,MULTICAST,UP,LOWER_UP> 
enp0s9           UP             08:00:27:25:c8:6d <BROADCAST,MULTICAST,UP,LOWER_UP> 
br-e6dc1065d537  DOWN           02:42:92:65:b3:c3 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
vxlan.calico     UNKNOWN        66:57:ed:b9:9c:1c <BROADCAST,MULTICAST,UP,LOWER_UP> 
cali9e5a2199a75@if3 UP             ee:ee:ee:ee:ee:ee <BROADCAST,MULTICAST,UP,LOWER_UP> 
caliec07808c9ad@if3 UP             ee:ee:ee:ee:ee:ee <BROADCAST,MULTICAST,UP,LOWER_UP> 
calid39e8c9a8ec@if3 UP             ee:ee:ee:ee:ee:ee <BROADCAST,MULTICAST,UP,LOWER_UP> 
cali6a901a5bd4a@if3 UP             ee:ee:ee:ee:ee:ee <BROADCAST,MULTICAST,UP,LOWER_UP> 
```

$ brctl  show br-e6dc1065d537
```
bridge name	bridge id		STP enabled	interfaces
br-e6dc1065d537		8000.02429265b3c3	no
```

As you can see linux bridge is DOWN, and bridge does not have anything connected to it, e.g. calico veths. 

So I've started sniffing traffic on the `vxlan.calico` when I curl some workloads between each other (it works!). Nothing. No traffic found. As far as I know and I've tested to communicate veths you need bridge. To run vxlan over it you need vxlan be connected to the bridge,...But as you see nothing is here.

The only connection I see on the veths in root namesapce, but how can it be, that two seperated veths talks to each other?

#### Reproduction Steps
First I've installed docker and I've tried work with (-driver=none) but it does not fit my needs (it does not work at all ;)). Then 
I've simply install ubuntu 22.10 VM, and install micrk8s snap. Then I've add dns addin and that's all. 

#### Introspection Report
[inspection-report-20230403_112917.tar.gz](https://github.com/canonical/microk8s/files/11137777/inspection-report-20230403_112917.tar.gz)

#### Can you suggest a fix?
Simple explanation is enough.

#### Are you interested in contributing with a fix?
no

**Comment by ktsakalozos** [comment]
Hi @MaciekLeks I am not very familiar with how calico handles traffic. I would point you to [1] as a high level description of how things could/should be and [2] for a deep dive into calico configuration. I suspect in your case that the internal traffic (pod-to-pod within the same node) does not go through the bridge.

[1] https://www.altoros.com/blog/kubernetes-networking-writing-your-own-simple-cni-plug-in-with-bash/ 
[2] https://docs.tigera.io/calico/latest/networking/determine-best-networking

**Comment by MaciekLeks** [comment]
You are 100% right. I fixed myself to bridgend and forgot the simplest solution. `ip -br -c route` shows the whole true. Thanks a lot for recalling this great article I read some time ago ;)
