### ISSUE TITLE
When using strict confinement, `microk8s kubectl` cannot access `/tmp`

### ISSUE THREAD

**Issue by lieryan** [canonical/microk8s#3899]
#### Summary

`microk8s kubectl` cannot read files in temporary directory.

#### What Should Happen Instead?

kubectl can read manifests/kustomization from a temporary directory.

#### Reproduction Steps

When on strict confinement:

```
$ snap list microk8s
Name      Version  Rev   Tracking            Publisher   Notes
microk8s  v1.25.6  4504  1.25-strict/stable  canonical✓  -
```

and you try to run a `microk8s kubectl` command in a temporary directory, then `kubectl` somehow cannot read files there:

```
$ mkdir /tmp/testme
$ cd /tmp/testme
$ microk8s kubectl kustomize
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/var/lib/snapd/void'
$ microk8s kubectl apply -f foo.yaml
error: the path "foo.yaml" does not exist
```

#### Can you suggest a fix?

Maybe mount the host machine's temporary directory into the snap, or maybe at least make sure that the current working directory is always mounted in the snap. Ideally, `microk8s kubectl` should work just like unconfined `kubectl`, with the only restriction being that it is configured to only work on the installed microk8s.

**Comment by ktsakalozos** [comment]
Hi @lieryan, indeed strict confinement will restrict access to certain parts of the host filesystem. The `microk8s kubectl` command is subject to such restrictions. Here is something you could try. Install an external `kubectl` and use the kubeconfig file you get from `microk8s config` to access the cluster.

**Comment by lieryan** [comment]
My use case here for needing `microk8s kubectl` is running tests on a cookiecutter template project. So the template project would generate a sample project in /tmp and then some tests will run against the generated project to make sure the generated project behaves correctly.

For our use case, while it's possible to set up a standalone `kubectl`, it runs the risk of the plain `kubectl` running against the wrong kubernetes cluster depending on the active kubectl context, in particular, as the standalone `kubectl` may run against production k8s cluster instead of microk8s.

IMO, what would've been very useful is if there's a separate `snap install --legacy microk8s-kubectl` that's pre-configured such that it installs into `microk8s kubectl` (or `microk8s-kubectl`) and such that it always runs against the `microk8s` snap installed on the same system.

Nevertheless, I think I'm going to close this issue for now. My original use case for why I was trying to use microk8s with strict confinement is because I was having issues with installing microstack Sunbeam on microk8s with legacy confinement earlier. I just tried microstack Sunbeam again and I think it seemed to work just fine on microk8s with legacy confinement now, so I can now just use microk8s with legacy.

**Comment by neoaggelos** [comment]
Hi @lieryan, just to follow up, you should be able to do:

```
sudo snap install microk8s --channel 1.27-strict       # or any other version with strict

# install kubectl using your preferred way
sudo snap install kubectl --classic

# export the kubeconfig from microk8s into the standard location
sudo microk8s config > ~/.kube/config

# kubectl commands now work as expected, no confinement issues
kubectl get pod -A
```
