### ISSUE TITLE
Question: supported/recommended approach for installing via script/headless on Windows?

### ISSUE THREAD

**Issue by htxryan** [canonical/microk8s#3939]
Question: is there an supported/recommended approach for installing via script/headless on Windows?

We would like to include MicroK8s as part of a product service installation package, and need to install it without user input via scripts. Is this possible?

I can't find anything in the official documentation other than reference to the installer (which has no quiet/headless mode, from what I can tell).

**Comment by ktsakalozos** [comment]
Hi @htxryan MicroK8s on windows needs to run on a linux VM. That may be one from WSL, hyper-v/virtualbox.
