### ISSUE TITLE
"write init-p: broken pipe" on CentOS 7

### ISSUE THREAD

**Issue by LarsFromMars** [canonical/microk8s#3944]
#### Summary
microk8s status --wait-ready holds forever

#### What Should Happen Instead?
should say ready?

#### Reproduction Steps
cannot reproduce - works in AWS env
Vanilla build : CentOS Linux release 7.9.2009 (Core)
Non VM - Centos installed on laptop

`]# microk8s status --wait-ready

^CTraceback (most recent call last):
  File "/snap/microk8s/5016/scripts/wrappers/status.py", line 200, in <module>
    isReady = wait_for_ready(timeout)
  File "/var/lib/snapd/snap/microk8s/5016/scripts/wrappers/common/utils.py", line 166, in wait_for_ready`

#### Introspection Report
attached

#### Can you suggest a fix?
search various forums but cannot find specific fix

Sample output:

# journalctl -fu snap.microk8s.daemon-kubelite
-- Logs begin at Sat 2023-04-22 01:52:09 AEST. --
Apr 21 16:05:57 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:05:57.660961    3709 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Apr 21 16:05:57 esky-2023 microk8s.daemon-kubelite[3709]: W0421 16:05:57.686723    3709 manager.go:1174] Failed to process watch event {EventType:0 Name:/kubepods/burstable/pod24b7e01f-0df7-417b-a0e7-b6da8a9dc4fd/be6f77e00e3265bd9671f7252f1725a1c37c88aaa88f4a563d1bb9bcb2fbbac5 WatchSource:0}: container "be6f77e00e3265bd9671f7252f1725a1c37c88aaa88f4a563d1bb9bcb2fbbac5" in namespace "k8s.io": not found
Apr 21 16:06:02 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:06:02.663040    3709 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Apr 21 16:06:07 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:06:07.600991    3709 remote_runtime.go:222] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown"
Apr 21 16:06:07 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:06:07.601090    3709 kuberuntime_sandbox.go:71] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown" pod="kube-system/calico-node-ltgdl"
Apr 21 16:06:07 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:06:07.601169    3709 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown" pod="kube-system/calico-node-ltgdl"
Apr 21 16:06:07 esky-2023 microk8s.daemon-kubelite[3709]: E0421 16:06:07.601305    3709 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"calico-node-ltgdl_kube-system(24b7e01f-0df7-417b-a0e7-b6da8a9dc4fd)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"calico-node-ltgdl_kube-system(24b7e01f-0df7-417b-a0e7-b6da8a9dc4fd)\\\": rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown\"" pod="kube-system/calico-node-ltgdl" podUID=24b7e01f-0df7-417b-a0e7-b6da8a9dc4fd`

**Comment by LarsFromMars** [comment]
[inspection-report-20230421_161227.tar.gz](https://github.com/canonical/microk8s/files/11292857/inspection-report-20230421_161227.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @LarsFromMars,

I see that the containers do not come up with the error:
```
            "reason": "FailedCreatePodSandBox",
            "message": "Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't copy bootstrap data to pipe: write init-p: broken pipe: unknown",
```

Users reporting this error on CentOS 7 relate the issue with the rather old 3.10 kernel  (https://forums.docker.com/t/centos7-docker-hello-world-fails/68941/5) would it be possible to update your system with a newer kernel?

**Comment by ktsakalozos** [comment]
@LarsFromMars could you also try to use the 1.27 channel? We have introduced static builds in some components that may address the issue you are seeing:
```
sudo snap install microk8s --classic --channel=1.27
```

**Comment by LarsFromMars** [comment]
Upgrading the kernal and using the 1.27 channel seems to have worked ..

`[esky@esky-2023 ~]$ microk8s kubectl get pods -n sc4snmp
NAME                                                          READY   STATUS    RESTARTS      AGE
snmp-mibserver-6d7cf77cd6-sbcl6                               1/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-trap-8465648484-g9rw6            1/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-worker-poller-b4d45b958-krqkt    1/1     Running   1 (44s ago)   3d17h
snmp-splunk-connect-for-snmp-worker-sender-867dcd54f4-p8rzt   1/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-scheduler-fd8656765-g8vfb        1/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-worker-trap-5d77d474cd-bdnc8     1/1     Running   1 (44s ago)   3d18h
snmp-redis-master-0                                           0/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-worker-trap-5d77d474cd-q84xr     1/1     Running   1 (44s ago)   3d18h
snmp-splunk-connect-for-snmp-worker-poller-b4d45b958-nd48d    1/1     Running   1 (44s ago)   3d17h
snmp-splunk-connect-for-snmp-trap-8465648484-nv5xv            1/1     Running   1 (44s ago)   3d18h
snmp-mongodb-5875b58795-hjf5q                                 2/2     Running   2 (44s ago)   3d18h
[esky@esky-2023 ~]$
[esky@esky-2023 ~]$ uname -a
Linux esky-2023 6.2.12-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 20 07:54:20 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
[esky@esky-2023 ~]$`

**Comment by neoaggelos** [comment]
This should now be fixed with https://github.com/canonical/microk8s/pull/3839. Please re-open if you encounter on a different system, thanks!
