### ISSUE TITLE
CPU allocation failing

### ISSUE THREAD

**Issue by Dennisovan92** [canonical/microk8s#3948]
#### Summary

I'm trying to deploy microk8s with 10cpus and 16gb ram which normally works through multipass or different tools.
I have enough resources so it should work

#### What Should Happen Instead?

Getting an error that I don't have a sufficient number of CPUs
VM cpus requested exceed number of available cores on host.

#### Introspection Report

I can not because there is no running instalce of microk8s
#### Can you suggest a fix?

Maybe add an option where you can ignore this error ?

#### Are you interested in contributing with a fix?

no

**Comment by neoaggelos** [comment]
Hi @Dennisovan92

I assume this is using the MicroK8s installer? If you are trying to create a 10-core VM on a host with less CPUs than that, the installer will fail instead.

Can you please describe how you are trying to setup the VM, and what the host specs are?

Thanks!

**Comment by Dennisovan92** [comment]
> Hi @Dennisovan92
> 
> I assume this is using the MicroK8s installer? If you are trying to create a 10-core VM on a host with less CPUs than that, the installer will fail instead.
> 
> Can you please describe how you are trying to setup the VM, and what the host specs are?
> 
> Thanks!

HI @neoaggelos 

I have a 16core CPU and 32GB memory on MacBook Pro, at the time of installation resources are barely used by anything else, all installation steps are based on this https://microk8s.io/docs/install-macos however, I was able to establish microk8s manually through multipass with the same specifications 10cpu and 16 GB memory, and then I deployed Kubernetes cluster, so everything works and looking fine but I was wondering why I was not able to do so by just running microk8s install instead of login in to microk8s-vm and installing and configuring everything manually.

Thanks
