### ISSUE TITLE
How do I execute the kubectl command on a slave node

### ISSUE THREAD

**Issue by jepson66** [canonical/microk8s#3954]
What should I do if I want to execute the kubectl command on the slave node？

**Comment by neoaggelos** [comment]
Hi @jepson66 

By default, MicroK8s worker nodes do not get an admin kubeconfig file. Instead what you can do is grab one from any of the control plane nodes and run kubectl manually, e.g.:

Print a kubeconfig file for the admin user by running this command on any of the control plane nodes:

```
microk8s config > kubeconfig
```

Then manually move this to `~/.kube/config` on your worker node, and install kubectl, e.g. with `sudo snap install kubectl --classic`

```
cp /path/to/kubeconfig ~/.kube/config

# install kubectl, e.g. with snap
sudo snap install kubectl --classic
kubectl get pod
```

Hope this helps!

**Comment by jepson66** [comment]
OK, thank @neoaggelos, I'll try it.

**Comment by jepson66** [comment]
@neoaggelos，According to what you said, it is configured, but the slave node still cannot use the kubectl command
<img width="568" alt="image" src="https://user-images.githubusercontent.com/108441697/237007374-6a4c22bf-5f33-4ca6-b7ef-de6edafac6c1.png">

**Comment by ktsakalozos** [comment]
@jepson66 is it possible you have an alias of `microk8s.kuebctl` to `kubectl`? Could you try calling directly `/snap/bin/kubectl` and use the ` --kubeconfig <path_to_kubeconfig>` just to be sure we are not picking up any config we are not supposed to?
