### ISSUE TITLE
microk8s kubectl get nodes says node is down, when it isn't

### ISSUE THREAD

**Issue by reematcs** [canonical/microk8s#3957]
#### Summary

3 nodes running on virtualbox/using vagrant on Windows host.

- microk8s_a: control plane
- microk8s_b, microk8s_c: worker nodes.

Every time VMs microk8s_b or microk8s_c are restarted, they must be manually added to the cluster via:

`microk8s add-node
`
on microk8s_a, then joined to the cluster.

IPs are static.

#### What Should Happen Instead?

Should remain in the cluster.

#### Reproduction Steps

1. Follow this article for setup: https://jet.dev/blog/spin-up-local-kubernetes-cluster-agrant/
2. Make additional worker node `microk8s_c`
3. Change vm.network for each of b and c to static (see attached Vagrantfile.txt)
[Vagrantfile.txt](https://github.com/canonical/microk8s/files/11400237/Vagrantfile.txt)

4. Start VMs, join worker nodes b and c to cluster.
5. Restart one of the VMs.

#### Introspection Report

[inspection-report-20230504_180747.tar.gz](https://github.com/canonical/microk8s/files/11400224/inspection-report-20230504_180747.tar.gz)

#### Can you suggest a fix?
Not at this point in time, no.

#### Are you interested in contributing with a fix?

If I can, I am interested.

**Comment by nyukeit** [comment]
I had the same issue. I solved it by editing this file:
`/var/snap/microk8s/current/args/kube-apiserver`
Add
`--advertise-address=x.x.x.x`
The IP address is your VM IP. After doing this and restarting, my worker nodes are in 'Ready' status.

**Comment by reematcs** [comment]
Great, thank you so much @nyukeit. It worked!

So, to summarize:

Add --advertise-address=publicIP to master node manifest file /var/snap/microk8s/current/args/kube-apiserver
and attempt to restart worker nodes.
OR just do this from the Vagrantfile (attached).
[Vagrantfile.txt](https://github.com/canonical/microk8s/files/11412233/Vagrantfile.txt)

Rejoin the cluster (final time).

Restart worker node.

No need to rejoin cluster after this.
