### ISSUE TITLE
snap.microk8s.daemon-apiserver.service not found

### ISSUE THREAD

**Issue by gaow0007** [canonical/microk8s#3958]
#### Summary

Following the installation steps describe in [get started](https://microk8s.io/docs/getting-started), I cannot find `snap.microk8s.daemon-apiserver.service` on my machine. 
```
sudo systemctl start snap.microk8s.daemon-apiserver.service
Failed to start snap.microk8s.daemon-apiserver.service: Unit snap.microk8s.daemon-apiserver.service not found.
```

#### Reproduction Steps

Following the official installation step [get started](https://microk8s.io/docs/getting-started)

#### Introspection Report

[inspection-report-20230506_103303.tar.gz](https://github.com/canonical/microk8s/files/11412115/inspection-report-20230506_103303.tar.gz)
#### Are you interested in contributing with a fix?

No, I am not very familiar with microk8s.

**Comment by neoaggelos** [comment]
Hi @gaow0007 

Is there any reference to `snap.microk8s.daemon-apiserver.service` that we have missed in the getting started guide? This will not work, you should instead do:

```
sudo systemctl start/restart/stop snap.microk8s.daemon-kubelite.service
```

For some context, there used to be separate `snap.microk8s.daemon-apiserver`, `snap.microk8s.daemon-kubelet`, etc services in older MicroK8s versions, but they have been replaced by the `snap.microk8s.daemon-kubelite` service, which then takes care of starting all of the Kubernetes control plane services in the right order.

Hope this helps! What are you trying to accomplish?
