### ISSUE TITLE
Calico-node refuses to start with I/O timeout

### ISSUE THREAD

**Issue by philiphenriksen** [canonical/microk8s#3960]
#### Summary

My cluster refuses to start, with `calico-node` getting the following error:
```
startup.go 365: Hit error connecting to datastore - retry error=Get https://10.152.183.1:443/api/v1/nodes/foo: dial tcp 10.152.183.1:443: i/o timeout
```
This causes every node in the cluster to refuse to start, as they are unable to create pod sandbox.

#### What Should Happen Instead?

This pod should restart successfully.

#### Steps attempted to mitigate the issue
1. Deleted pod and let k8s restart it
2. Executed `microk8s reset` and let the process finish
3. Removed the snap and re-installed.

None of these steps helped,

#### Introspection Report

[inspection-report-20230510_091209.tar.gz](https://github.com/canonical/microk8s/files/11440234/inspection-report-20230510_091209.tar.gz)

**Comment by philiphenriksen** [comment]
It's worth noting that `kubectl` commands still work flawlessly, so the APIserver itself is not unavailable.

Other commands I've tried to explore the current state:

Heres other commands that I've executed to explore the state of the cluster:
```
$> kubectl logs calico-node-sx9rp -n kube-system -f
2023-05-10 09:48:16.863 [INFO][8] startup.go 290: Early log level set to info
2023-05-10 09:48:16.864 [INFO][8] startup.go 306: Using NODENAME environment for node name
2023-05-10 09:48:16.864 [INFO][8] startup.go 318: Determined node name: app311009
2023-05-10 09:48:16.867 [INFO][8] startup.go 350: Checking datastore connection
2023-05-10 09:48:46.869 [INFO][8] startup.go 365: Hit error connecting to datastore - retry error=Get https://10.152.183.1:443/api/v1/nodes/foo: dial tcp 10.152.183.1:443: i/o timeout
2023-05-10 09:49:17.869 [INFO][8] startup.go 365: Hit error connecting to datastore - retry error=Get https://10.152.183.1:443/api/v1/nodes/foo: dial tcp 10.152.183.1:443: i/o timeout
$> kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   41m
$> kubectl get endpoints
NAME         ENDPOINTS             AGE
kubernetes   192.168.30.34:16443   40m
$> curl https://192.168.30.34:16443/api/v1/nodes/foo -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
$> kubectl exec -it calico-node-sx9rp -n kube-system -- curl https://192.168.30.34:16443/api/v1/nodes/foo -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
$> kubectl exec -it calico-node-sx9rp -n kube-system -- curl https://10.152.183.1/api/v1/nodes/foo -k
-- does not respond before the pod is killed due to crashloop backoff (at least 20 seconds)
```

**Comment by neoaggelos** [comment]
Hi @philiphenriksen, thank you for raising the issue.

I see a `docker0` interface on the machine, is Docker installed as well on the same machine? We have had issues in the past due to Docker being a bit opinionated and messing with the system iptables rules.

Can you test whether doing the same on a host without Docker helps?

**Comment by philiphenriksen** [comment]
Docker was installed as a snap, so I've tried to remove it (with `--purge`) then reset microk8s again and rebooted the machine, just to be sure.

This seems to have worked!
```
$> kg pods -A
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-node-bqkcj                         1/1     Running   0          75s
kube-system   calico-kube-controllers-f7868dd95-24nj8   1/1     Running   0          75s
kube-system   coredns-7f9c69c78c-982nz                  1/1     Running   0          75s
ingress       nginx-ingress-microk8s-controller-r9qhg   1/1     Running   0          75s
```

**Comment by ktsakalozos** [comment]
Closing this, thank you both for reporting and solving this issue.
