### ISSUE TITLE
Microk8s problems changing static IP address and FQDN of the VM running microk8s

### ISSUE THREAD

**Issue by kamranmohammed** [canonical/microk8s#3966]
#### Summary
We have a VM running microk8s v1.25 with pods and services running and we would like to support IP and domain name changes at any point in the future. The host is on Ubuntu 18 and these are the following steps we do to make IP and domain change:
1. Hostname changes by:
`$sudo hostnamectl set-hostname $new_hostname`
Followed by changes to `/etc/hosts` file.

2. Followed by:
`
microk8s disable dns
          microk8s disable rbac
          sudo kubectl delete svc kube-dns -n kube-system
          microk8s.stop

          sudo sed -ie 's%state.*%state /data/run/containerd/%g' /var/snap/microk8s/current/args/containerd
          sudo sed -ie 's%root.*%root /data/var/lib/containerd/%g' /var/snap/microk8s/current/args/containerd

          #https://github.com/ubuntu/microk8s/issues/276
          cd /var/snap/microk8s/current/var/kubernetes/backend/
          grep -lr "${old_ip_address}" *.yaml | xargs sed -i "s/${old_ip_address}/${ip_address}/g"
          sudo /snap/microk8s/current/bin/dqlite -s 127.0.0.1:19001 -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key k8s ".reconfigure /var/snap/microk8s/current/var/kubernetes/backend/ /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml"
          cd -

          logprint "Updating kube-apiserver"

          cd /var/airwave/appliance/mk8s
          sudo sed -iE "s/--advertise-address=.*/--advertise-address=$ip_address/g" /var/snap/microk8s/current/args/kube-apiserver

   echo "network:
  version: 2
  renderer: networkd
  ethernets:
    $intf:
      dhcp4: no
      addresses:
        - $ip_address/$numbits
      gateway4: $gateway
      nameservers:
        addresses: 
          - $dns" | sudo tee "/etc/netplan/00-airwave.yaml"> /dev/null
   if [ ! -z $secdns ]; then
      echo "          - $secdns" | sudo tee -a "/etc/netplan/00-airwave.yaml" > /dev/null
   fi

   sudo rm -rf /etc/netplan/01-netcfg.yaml
   sudo ip route flush default || true
   sudo netplan apply  || { exit_action "Couldn't apply netplan config" "Please verify network configuration and retry airwave setup";

sudo ufw allow in on cni0 && sudo ufw allow out on cni0
            sudo ufw default allow routed
            #https://github.com/canonical/microk8s/issues/1401
            sudo iptables -I INPUT -p tcp -m multiport --dports 1338,2380,12379,16443,19001,25000,10248:10259 -j ACCEPT
            sudo microk8s enable dns:16.182.80.91,16.182.80.92
            microk8s status --wait-ready
            sudo microk8s enable rbac
            sudo microk8s start

            #https://microk8s.io/docs/change-cidr
            sudo microk8s kubectl delete -f /var/snap/microk8s/current/args/cni-network/cni.yaml
            #for --cluster-cidr=s
            #https://microk8s.io/docs/change-cidr
            sudo sed -ie 's|10.1.0.0/16|10.123.0.0/16|g' /var/snap/microk8s/current/args/kube-proxy
            sudo sed -ie 's|10.1.0.0/16|10.123.0.0/16|g' /var/snap/microk8s/current/args/cni-network/cni.yaml

            microk8s.stop
            microk8s.start
            #https://microk8s.io/docs/change-cidr
            sleep 5
            sudo kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml
            sleep 20
            microk8s.stop

            #https://github.com/ubuntu/microk8s/issues/276
            #-service-cluster-ip-range=10.152.183.0/24
            sudo sed -ie 's|10.152.183.0/24|10.129.0.0/23|g' /var/snap/microk8s/current/args/kube-apiserver
            sudo sed -ie 's|10.152.183.1|10.129.0.1|g' /var/snap/microk8s/current/certs/csr.conf.template

            microk8s.start
            sleep 5
            sudo microk8s kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml

            #--cluster-dns
            sudo sed -ie 's|10.152.183.10|10.129.0.10|g' /var/snap/microk8s/current/args/kubelet

            if [ -z "$K8S_125_HACK" ]; then
              K8S_125_HACK="false"
            fi

            if [[ $K8S_125_HACK == "true" ]]; then
              sudo cp "/snap/microk8s/${MICROK8S_SNAP_DIR}/addons/core/addons/dns/coredns.yaml" /tmp/
            else
              sudo cp /snap/microk8s/current/actions/coredns.yaml /tmp/
            fi

            sudo sed -ie 's|$ALLOWESCALATION|false|g' /tmp/coredns.yaml
            sudo sed -ie 's|$NAMESERVERS|16.182.80.91|g' /tmp/coredns.yaml
            sudo sed -ie 's|10.152.183.10|10.129.0.10|g' /tmp/coredns.yaml

            sudo kubectl apply -f /tmp/coredns.yaml
            microk8s.stop
            microk8s.start
            sudo rm /var/snap/microk8s/current/certs/*
            sleep 5
            sudo microk8s refresh-certs --cert ca.crt
            sudo microk8s refresh-certs --cert server.crt
            sudo microk8s refresh-certs --cert front-proxy-client.crt 
`

While the `microk8s status` says the cluster is running but the pods are in init state. I also checked calico and coredns pods and they seem to be running but I see the following errors:
`
Warning  MissingClusterDNS  6m3s (x51 over 8d)  kubelet  pod: "nginx-device-ingress-ds-dswm9_ingress-nginx(60b24ccf-0e21-45a3-9c73-02033110b727)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
`

#### What Should Happen Instead?
How should I safely make static IP and hostname changes without impacting pod network or anything?

#### Reproduction Steps
See summary.

#### Introspection Report
[inspection-report-after-change.tar.gz](https://github.com/canonical/microk8s/files/11455025/inspection-report-after-change.tar.gz)
[inspection-report-before-change.tar.gz](https://github.com/canonical/microk8s/files/11455027/inspection-report-before-change.tar.gz)
Old IP/Hostname details:
IP: 16.182.25.243
FQDN: xx-xxxxxx-75-vm02.mip.xxxxxxx.xxxxxxx.net (where x are masked characters)

IP: 16.182.24.45
FQDN: xx-xxxxxx-73-vm01.mip.xxxxxxx.xxxxxxx.net (where x are masked characters)

Please help!

**Comment by ktsakalozos** [comment]
Hi @kamranmohammed 

When the dns addon get enabled it adds two arguments [1] to the kubelet but in the inspection tarball attached I do not see those arguments. The two arguments that have to be added to `/var/snap/microk8s/current/args/kubelet`:
```
--cluster-domain=cluster.local
--cluster-dns=<service IP of DNS service>
```   
These arguments are used by kubelet to inject the DNS endpoint to the containers it creates. This way the containers can know where to find the DNS service.

You are probably missing the two arguments because the dns addon gets removed (so the arguments are removed from kubelet) and the follow up `sed` commands do not find the dns endpoints.
 
[1] https://github.com/canonical/microk8s-core-addons/blob/main/addons/dns/enable#L80

**Comment by kamranmohammed** [comment]
Thanks for looking into this. I fixed that problem. I feel now the problem is with the hostname change part. I tried to follow https://github.com/canonical/microk8s/issues/3753#issuecomment-1429286747 but now the kubelet throwing these errors:
```
May 03 07:48:50 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: }. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/5016/var/kubernet
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: W0503 07:48:52.019291   45134 logging.go:59] [core] [Channel #3 SubChannel #6] grpc: addrConn.createTransport f
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Addr": "unix:///var/snap/microk8s/5016/var/kubernetes/backend/kine.sock:12379",
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "ServerName": "kine.sock",
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Attributes": null,
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "BalancerAttributes": null,
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Type": 0,
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Metadata": null
May 03 07:48:52 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: }. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/5016/var/kubernet
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: W0503 07:48:54.145192   45134 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport f
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Addr": "unix:///var/snap/microk8s/5016/var/kubernetes/backend/kine.sock:12379",
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "ServerName": "kine.sock",
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Attributes": null,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "BalancerAttributes": null,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Type": 0,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Metadata": null
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: }. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/5016/var/kubernet
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: W0503 07:48:54.314229   45134 logging.go:59] [core] [Channel #4 SubChannel #5] grpc: addrConn.createTransport f
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Addr": "unix:///var/snap/microk8s/5016/var/kubernetes/backend/kine.sock:12379",
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "ServerName": "kine.sock",
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Attributes": null,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "BalancerAttributes": null,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Type": 0,
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Metadata": null
May 03 07:48:54 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: }. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/5016/var/kubernet
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]: W0503 07:48:55.839453   45134 logging.go:59] [core] [Channel #3 SubChannel #6] grpc: addrConn.createTransport f
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Addr": "unix:///var/snap/microk8s/5016/var/kubernetes/backend/kine.sock:12379",
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "ServerName": "kine.sock",
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net mic
[inspection-report-new.tar.gz](https://github.com/canonical/microk8s/files/11480860/inspection-report-new.tar.gz)
rok8s.daemon-kubelite[45134]:   "Attributes": null,
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "BalancerAttributes": null,
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Type": 0,
May 03 07:48:55 m2-dl380g10-73-vm01.mip.storage.hpecorp.net microk8s.daemon-kubelite[45134]:   "Metadata": null
```

I tried refreshing certs as well but nothing works. Attaching latest inspect tarball.

**Comment by viclevy** [comment]
It is unfortunate that this issue is now marked stale due to inactivity.
I'm surprised to find out that I'm among a few who's encountered a use case where hostname change is expected to occur post microk8s install. I was really hopping this matter would draw more attention and help drive adoption.
