### ISSUE TITLE
microk8s does not starting after host server reboot

### ISSUE THREAD

**Issue by javad87** [canonical/microk8s#3967]
#### Summary

After host rebooted, microk8s does not start on CentOs7
#### What Should Happen Instead?

micrk8s start should make kube running
#### Reproduction Steps

Not exactly I know after restart of host server it happened...
1. ...
2. ...

#### Introspection Report

[inspection-report-20230514_092437.tar.gz](https://github.com/canonical/microk8s/files/11471252/inspection-report-20230514_092437.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @javad87 

Would it be possible to use the latest 1.27 release? There have been a few updates for better support of CentOS in the latest release.

Also, could you please not name the nodes "localhost.localdomain".

Finally, I see there are some issues in pulling the images:
```
May 14 09:23:47 kousha.ifb.ir microk8s.daemon-containerd[1425]: time="2023-05-14T09:23:47.605612820+03:30" level=info msg="PullImage \"library/pyodbcsqlimage:1.0.0\""
May 14 09:23:55 kousha.ifb.ir microk8s.daemon-containerd[1425]: time="2023-05-14T09:23:55.101644621+03:30" level=info msg="trying next host" error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
```
Could you please check that the node kousha.ifb.ir can actually pull images?

**Comment by priyashpatil** [comment]
Facing the same issue, Might be related to #4597 #4449
