### ISSUE TITLE
Mismatch between changing the pods CIDR config and the automatic iptables rules

### ISSUE THREAD

**Issue by Dunge** [canonical/microk8s#3971]
#### Summary
Following [this guide](https://microk8s.io/docs/change-cidr) to change the pods CIDR instruct to modify two files `/args/kube-proxy` and `/args/cni-network/cni.yaml`. And it works fine.

But I also encountered the same issues as in #266 after rebooting my nodes. Somehow on only one node, the traffic from the cluster couldn't reach anything. iptables was reset to `-P FORWARD DROP`.

microk8s had added an automatic rule to allow forward traffic on the node. Using `iptables -S`:
```
-A FORWARD -s 10.1.0.0/16 -m comment --comment "generated for MicroK8s pods" -j ACCEPT
-A FORWARD -d 10.1.0.0/16 -m comment --comment "generated for MicroK8s pods" -j ACCEPT
```

Problem is, this is the default CIDR, and not the changed one.

Looking at the [code adding this rule here ](https://github.com/canonical/microk8s/blob/3ad1294c8c5f4ae8b08c9510d3975006358e8780/microk8s-resources/wrappers/run-kubelite-with-args#L91) it takes his cidr information from either `/args/kubelet` or `/args/flannel-network-mgr-config`, which is not the same as the files mentioned in the guide above. The flannel config file still have the old 10.1.0.0 value.

#### What Should Happen Instead?
No clash between the CIDR configuration location, so that following the guide to change CIDR also set the correct iptables rules.

**Comment by ktsakalozos** [comment]
Hi @Dunge 

Thank you for bring this issue to our attention. Indeed this seems to be a bug on our scripts. I believe we should be getting the CIDR from kube-proxy. Would you be interested in a PR to address this? If not we will provide a fix shortly. Many thanks.
