### ISSUE TITLE
"microk8s status" exits with zero return code when server is down

### ISSUE THREAD

**Issue by rsalinas** [canonical/microk8s#3974]
#### Summary
microk8s status returns 0 when the server is down. 

$ _microk8s status --yaml ; echo $?_
**microk8s is not running, try microk8s start**
0

#### What Should Happen Instead?
I would expect it to return non-zero, so that I don't need to search for text in the output.

This also complicates my life when trying to directly parse its output as yaml. 

#### Reproduction Steps

1. It happens always, both and without --yaml. Retval is always zero.

#### Introspection Report
Probably not relevant.

#### Can you suggest a fix?
Yes, simply return non-zero when the server is down.
Fix scripts/wrappers/common/utils.py:

```
def exit_if_stopped():
    stoppedLockFile = os.path.expandvars("${SNAP_DATA}/var/lock/stopped.lock")
    if os.path.isfile(stoppedLockFile):
        print("microk8s is not running, try microk8s start")
        **exit(0)**

```

#### Are you interested in contributing with a fix?
Yes, it's about changing that zero by a one. 
I can make a PR if you wish.

**Comment by sachinkumarsingh092** [comment]
Hey @rsalinas, thanks for opening the issue and the PR. I'll try to look into it soon.
