### ISSUE TITLE
Microk8s registry not started

### ISSUE THREAD

**Issue by hanzlamateen** [canonical/microk8s#3977]
#### Summary
After I install Microk8s, registry is not accessible after I install it for like 5 mins or so. `microk8s status` shows it to be enabled but when I push image it says `get "http://localhost:32000/v2/": dial tcp 127.0.0.1:32000: connect: connection refused`. It does not open in browser as well `http://localhost:32000/v2/_catalog`. After a while it starts working. I want to understand how can I found out why its not working.

#### What Should Happen Instead?
It should start or else if its initializing, then there should be some way to figure out if its loading.

#### Reproduction Steps

1. Run `snap install microk8s --classic --channel=1.26/stable` OR `snap install microk8s --classic --channel=1.27`
2. Run following commands to enable addons:
```
sudo microk8s enable dashboard
sudo microk8s enable dns
sudo microk8s enable registry
sudo microk8s enable host-access
sudo microk8s enable ingress
sudo microk8s enable rbac
sudo microk8s enable hostpath-storage
sudo microk8s enable helm3
```
3. Run `microk8s status`
4. Run `microk8s inspect`
5. Open `http://localhost:32000/v2/_catalog` in browser, nothing happens.
6. Push image tagged image, it says `get "http://localhost:32000/v2/": dial tcp 127.0.0.1:32000: connect: connection refused`
7. Docker's `daemon.json` already contains `localhost:32000` as insecure registry.

#### Introspection Report
This is the report when it was not working:
[inspection-report-20230518_083627.tar.gz](https://github.com/canonical/microk8s/files/11504158/inspection-report-20230518_083627.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @hanzlamateen 

In the attached tarball the problem is that the hostpath-provisioner is not coming up and therefore the registry is in pending state:
```
NAMESPACE            NAME                                            READY   STATUS              RESTARTS   AGE     IP           NODE        NOMINATED NODE   READINESS GATES
kube-system          pod/calico-node-8fc9m                           1/1     Running             0          5m5s    10.0.0.4     hanzla-pc   <none>           <none>
container-registry   pod/registry-77c7575667-fnk9n                   0/1     Pending             0          2m16s   <none>       <none>      <none>           <none>
default              pod/agones-controller-855485bffc-8d4cc          0/1     ContainerCreating   0          2m16s   <none>       hanzla-pc   <none>           <none>
default              pod/agones-allocator-7f87d5d884-578xg           0/1     ContainerCreating   0          2m16s   <none>       hanzla-pc   <none>           <none>
default              pod/agones-allocator-7f87d5d884-q8wj7           0/1     ContainerCreating   0          2m16s   <none>       hanzla-pc   <none>           <none>
kube-system          pod/calico-kube-controllers-79568db7f8-hz9rl    1/1     Running             0          5m5s    10.1.215.2   hanzla-pc   <none>           <none>
kube-system          pod/metrics-server-6f754f88d-4z2nr              1/1     Running             0          4m14s   10.1.215.1   hanzla-pc   <none>           <none>
default              pod/local-redis-master-0                        0/1     Pending             0          117s    <none>       <none>      <none>           <none>
default              pod/local-redis-replicas-0                      0/1     Pending             0          117s    <none>       <none>      <none>           <none>
kube-system          pod/coredns-6f5f9b5d74-xqdhf                    1/1     Running             0          2m16s   10.1.215.4   hanzla-pc   <none>           <none>
kube-system          pod/hostpath-provisioner-69cd9ff5b8-2hkrh       1/1     Running             0          2m16s   10.1.215.5   hanzla-pc   <none>           <none>
ingress              pod/nginx-ingress-microk8s-controller-kw65w     1/1     Running             0          2m17s   10.1.215.3   hanzla-pc   <none>           <none>
kube-system          pod/hostpath-provisioner-hanzla-pc-bfjph        0/1     ContainerCreating   0          67s     <none>       hanzla-pc   <none>           <none>
kube-system          pod/hostpath-provisioner-hanzla-pc-nftkc        0/1     ContainerCreating   0          66s     <none>       hanzla-pc   <none>           <none>
kube-system          pod/hostpath-provisioner-hanzla-pc-dtfmx        0/1     ContainerCreating   0          66s     <none>       hanzla-pc   <none>           <none>
kube-system          pod/kubernetes-dashboard-55c7cdd5bb-7wzbg       1/1     Running             0          2m16s   10.1.215.6   hanzla-pc   <none>           <none>
kube-system          pod/dashboard-metrics-scraper-7bc864c59-tzwwx   1/1     Running             0          2m16s   10.1.215.7   hanzla-pc   <none>           <none>
default              pod/agones-allocator-7f87d5d884-s7xgx           1/1     Running             0          2m16s   10.1.215.8   hanzla-pc   <none>           <none>
```
I could not find a good reason for why the hostpath-provisioner is not coming up. I also see other deployments that are not part of the issue description. Could we please simplify the deployment? Could you attach an inspection tarball from an installation that has only dns and the registry enabled (the registry will pull in the hostpath-provisioner).

**Comment by hanzlamateen** [comment]
So, it seems like I have to check in `container-registry` namespace to find out if its in pending or started state. Got it thanks.
