### ISSUE TITLE
HA cluster doesn't recover from network failover (removed LAN cable)/ abruptly shutdown

### ISSUE THREAD

**Issue by sanjaybharti-consort** [canonical/microk8s#3983]
#### Summary
I'm trying to achieve quick failover in a microk8s 3 node HA cluster. My 3 nodes are running on 3 separate machine having Ubuntu 20.04 & Microk8s 1.27.1/stable , I just stop one node at a time by  abruptly shutting it down or by removing that node from network,  after that multiple nodes come to  **not-ready** state & it  takes more time to recover from failover.  

I removed LAN cable from one node at May 20 09:24 (timestamp for reference inspection log) which thereafter resulted in all nodes coming in **not-ready** state. After 17 min node status changed  & two nodes came into ready state at May 20 09:24. After that all pods are rescheduled from that node to another node. Sometime it takes more than 40 mins for the other nodes to come into ready state.

#### What Should Happen Instead?
The node for which I have removed LAN cable only that node  should be in not-ready state & all the other nodes should be in running  state. After toleration period all pods which are running node should be rescheduled to another node.

#### Reproduction Steps
1. Make 3 node cluster 
2. Remove one node at a time from network or abruptly shutdown 
3. repeat these steps for all the nodes 

#### Introspection Report
Inspection report of 1st node
[inspection-report-20230520_094239.tar.gz](https://github.com/canonical/microk8s/files/11522250/inspection-report-20230520_094239.tar.gz)

Inspection report of 2nd node 
[inspection-report-20230520_094343.tar.gz](https://github.com/canonical/microk8s/files/11522254/inspection-report-20230520_094343.tar.gz)

Inspection report of 3rd node which is removed from network 
[inspection-report-20230520_102548.tar.gz](https://github.com/canonical/microk8s/files/11522257/inspection-report-20230520_102548.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @sanjaybharti-consort apologies for the late response.

I was not able to reproduce the issue you describe, for reference when a node is unreachable (I used something like  `sudo ip address del xxx.yyy.zzz.ccc/24 dev ens3`) it takes about 30 seconds for the node to be marked as not ready and as soon as it get back online it registers again with the API server. I have never noticed all nodes getting into a not ready state because of a single node leaving the cluster.

Looking at the logs you attached I see the nodes do not not come back online because the default rout is not set. For example, the logs on the 3rd node that got removed and re-added back shows that it is failing to start with:
```
May 20 09:30:04 bocc microk8s.daemon-kubelite[174740]: I0520 09:30:04.358880  174740 daemon.go:65] Starting API Server
May 20 09:30:04 bocc microk8s.daemon-kubelite[174740]: Error: Unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
May 20 09:30:04 bocc microk8s.daemon-kubelite[174740]: F0520 09:30:04.361579  174740 daemon.go:67] API Server exited Unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
May 20 09:30:04 bocc systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=255/EXCEPTION
May 20 09:30:04 bocc systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
```
See the logs with `journslctl -fu snap.microk8s.daemon-kubelite`.

The above goes on from the time the node got disconnected until `May 20 10:09:25`. During this time the datastore is very slow as indicated by log messages such as:
```
May 20 09:25:42 occ microk8s.daemon-kubelite[724307]: Trace[1311172744]: ---"Writing http response done" 3043ms (09:25:42.115)
May 20 09:25:42 occ microk8s.daemon-kubelite[724307]: Trace[1311172744]: [3.067019242s] [3.067019242s] END
May 20 09:25:45 occ microk8s.daemon-kubelite[724307]: E0520 09:25:45.187237  724307 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://bocc:10250/containerLogs/default/mysql-1/sidecar", Err:(*net.OpError)(0xc00e917900)}: Get "https://bocc:10250/containerLogs/default/mysql-1/sidecar": dial tcp 192.168.1.33:10250: connect: no route to host
```

Is it possible the disk on one of nodes is misbehaving or it is under stress by over processes/workloads running on your system?

**Comment by kcarson77** [comment]
was there a solution to this?
I'm seeing similar occasionally when I power off a node. I have 3 nodes hosted on VMs.

If I power off a node, one or both of the remaining will report "NotReady" with "unknown" conditiions.
It recovers in 20-25 mins.

**Comment by geocomm-cwillard** [comment]
I am experiencing the same issue. I have a 6-node cluster, with 3 nodes as the master and 3 as workers. I am using Ubuntu 22.04 and microk8s 1.29.4. When I bring down the master node that is the leader for the dqlite cluster, I notice that some of my other nodes show as not ready in the cluster status. This status persists for about 16 to 17 minutes, after which the cluster reports only one node as offline.

**Comment by kcarson77** [comment]
https://github.com/canonical/microk8s/issues/4596#issuecomment-2330734826
