### ISSUE TITLE
Non-HA single node, leaving node removes all pods

### ISSUE THREAD

**Issue by khandg** [canonical/microk8s#4006]
#### Summary
Iam running the microk8s in ubuntu in no high availability i.e. there is a single node onto the same machine where it is installed. I updated the certificates and then i issue following command:
`sudo microk8s leave`

It give following messages:

```
Generating new cluster certificates.
Waiting for node to start. 
```

and then i stopped microk8s and then started again, the node appeared  however all of my pods / namespaces are gone, how to recover?

#### What Should Happen Instead?
All the pods should retain

#### Reproduction Steps
Already described above

#### Can you suggest a fix?

[https://wetransfer.com/downloads/ee891f9d62bd9ffd7fdac2f9597e638f20230529135310/bf5d38484b8a54a7107a5447153c884820230529135327/7b32a3](url)

**Comment by berkayoz** [comment]
Hey @khandg,

Thanks for reporting this issue. `microk8s leave` command is supposed to remove the node from a cluster and return it to a clean state. Although it does not sound right that a node that is not in a cluster acts the same way. Sorry about the trouble, I'll mark it as a bug and add it to our backlog.

**Comment by khandg** [comment]
Thanks @berkayoz for noting this issue. Is there any possible way i can have it recovered?

**Comment by beingyash** [comment]
Do we not have any resolution for this scenario to recover the cluster? I am experiencing the same situation with v1.25.x and I can see that all the cluster data is still available on the disk.
