### ISSUE TITLE
Fresh install broken on Pi 3

### ISSUE THREAD

**Issue by 0anth** [canonical/microk8s#4009]
#### Summary
Microk8s is not fully starting on a fresh install of Ubuntu Server 22.04.2 arm64 on a CM3+ module with eMMC. I have already tried installing linux-modules-extra-raspi, but there was no change. I tried installing Ubuntu 22.04.2 fresh again, but it resulted in the same issue. Performing any microk8s commands takes a long time to execute. CPU is around 50% load and memory around 60% load at idle with micok8s installed and started, despite no pods added. Most microk8s commands hang and never complete. Journalctl constantly mentions that the network plugin is not ready:

`microk8s.daemon-kubelite[2095]: E0531 21:28:35.752093    2095 kubelet.go:2475] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"`

#### Reproduction Steps
1) Install a fresh copy of Ubuntu Server 22.04.2 arm64
2) Perform `apt update` and `apt upgrade`
3) Install extra modules with `sudo apt install linux-modules-extra-raspi`
4) Install microk8s with `sudo snap install microk8s --classic`

#### Introspection Report
[inspection-report-20230531_215943.tar.gz](https://github.com/canonical/microk8s/files/11615032/inspection-report-20230531_215943.tar.gz)

**Comment by berkayoz** [comment]
Hey @0anth ,

Thanks for reaching out. Have you updated the boot parameters to enable cgroup as described [here](https://microk8s.io/docs/install-raspberry-pi)?

**Comment by 0anth** [comment]
Hi, I have, but it also seemed to make no difference.

`turing@turing-master:~$ sudo cat /boot/firmware/cmdline.txt
cgroup_enable=memory cgroup_memory=1 console=serial0,115200 dwc_otg.lpm_enable=0 console=tty1 root=LABEL=writable rootfstype=ext4 rootwait fixrtc quiet splash`

**Comment by 0anth** [comment]
I previously ran K3s on the same CM3+, and although not the fastest, it did run ok. I have 7 modules available, so the individual load on each node shouldn't be too high once it actually gets going. This is a homelab environment and not production, so I'm willing to turn off HA and any other non-critical services if it will help the control plane.

**Comment by berkayoz** [comment]
After checking out the CM3+ resources, it should be enough to get a simple node up. We've usually observed this issue on Raspberry Pi's with slow storage, which leads to unstability with apiserver and the whole cluster. Do you have any information about your eMMC storage? 
I'd suggest checking out `Raspberry Pi and systems with low disk performance` under our [troubleshooting page](https://microk8s.io/docs/troubleshooting).

**Comment by 0anth** [comment]
I tested the disk and got the following results:
`Timing cached reads:   874 MB in  2.00 seconds = 437.79 MB/sec`
`Timing buffered disk reads:  64 MB in  3.02 seconds =  21.19 MB/sec`
`629145600 bytes (629 MB, 600 MiB) copied, 32.8676 s, 19.1 MB/s`

I tried configuring journald with `Storage=volatile` and rebooting, but microk8s is still not starting correctly.

**Comment by halfer** [comment]
Just a thought - if the control plane is the problem, could you add something juicier than a Pi for the leader node, and then join all the Pi modules as worker-only nodes? You can use `microk8s join --worker ...` for that.

Or if you don't have other servers, maybe you could get one Pi to run on a proper magnetic/SSD, and then use that as the leader. Then all the Pi modules can join, again as worker-only.
