### ISSUE TITLE
The one node couldn't re-join when it have a unexpected problem.

### ISSUE THREAD

**Issue by minhwan9600** [canonical/microk8s#4025]
Summary : 

When the one node re-join , the node couldn't join on cluster.
microk8s ver: 1.19.5 
This version can't upgrade. It should keep this version.

Problem:

The one node of three nodes have been a problem.
When I execute the kubectl get node, it was as not ready status.
I dont know what's going on.
I followed for resolving as follow proceduers

1. microk8s leave
2. microk8s remove-node  <node-name>
3.microk8s add-node 

I executed the output of microk8s add-node on the removed-node.
But, I coundn't join the removed-node.
When I exceute the kubectl command, The error messags was "do you specify the right api-server" ?

When I watch the cluster.yaml, It don't register  the new-cluster-id of removed node.
I watched previous cluster-id of the removed-node with new-cluster-id in cluster.yaml

do you know how to register one removed-node on cluster?

**Comment by halfer** [comment]
I won't be able to help, but could you perhaps run these two commands for readers, and capture the output in a code block in this thread?

* `microk8s kubectl get nodes`
* `microk8s status`

Thanks.

**Comment by ktsakalozos** [comment]
@minhwan9600, could you please share exactly the error massage you get when you try to join the node as well as the contents of `cluster.yaml`? Maybe the cluster agent service is not running in the node you are trying to contact to join the cluster?
