### ISSUE TITLE
Should the DNS addon be enabled by default?

### ISSUE THREAD

**Issue by halfer** [canonical/microk8s#4030]
I originally considered raising this as a feature request, but I bumped into a problem with the out-of-the-box MicroK8S configuration, so on balance I have marked this as a bug.

I am learning K8S using MicroK8S, and I am creating some workloads to understand how everything works. On my three-node cluster I ran this command:

    root@arran:/home/myuser# microk8s kubectl create deployment k8s-workload --image=k8s-workload

I was having a problem [per this question](https://serverfault.com/questions/1132843/how-to-fix-failed-to-unpack-image-on-snapshotter-overlayfs-unexpected-media-ty), which turned out to be caused by a corrupted image in containerd. While I was debugging that, I was getting this warning:

> kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.

See **Update 1** - I fixed this by enabling the `dns` addon. This did not resolve my overall problem, but it made the warning (in the pod description) go away. I assume that I could now disable the `dns` addon, which would cause the warning to return, but starting workloads would still be fine.

I wonder thus whether it would make for a cleaner developer experience for things to work flawlessly, with no warnings, when doing fairly normal operations? On that basis I wonder if this addon could be enabled by default in MicroK8S. Knowledgeable users who prefer a different DNS solution would know to disable it and enable something else.Conversely, beginners would tend to flounder.

(I am running a mix of v1.26.4 and v1.26.5 in my cluster).

**Comment by ktsakalozos** [comment]
Hi @halfer. Traditionally MicroK8s would give you the most minimal kubernetes cluster you could get, and that would not include dns. You would need to `microk8s enable dns` to get dns working. With the 1.27 release we revised our approach. DNS now gets enabled by default. That should match your needs and will address the issue you bring up.

**Comment by halfer** [comment]
Ah perfect @ktsakalozos - thanks!
