### ISSUE TITLE
Slow DNS resolution on Snap v1.27.2

### ISSUE THREAD

**Issue by kian99** [canonical/microk8s#4036]
#### Summary
DNS resolution is extremely slow in microk8s when installed from latest/stable, currently 
```
latest/stable:         v1.27.2  2023-06-05
```

#### What Should Happen Instead?
DNS resolution should be faster.

#### Reproduction Steps

1. sudo snap install microk8s --classic
2. Create test Ubuntu pod in default namespace
3. Exec into pod and run command like `curl -v https://google.com`
4. Observe lengthy delay before the request ever starts

Inspecting the coredns pod logs with `microk8s kubectl logs coredns-7745f9f87f-d9xdg -n kube-system -f` shows
```
[INFO] 10.1.5.132:35029 - 61557 "A IN google.com.20.10.in-addr.arpa. udp 47 false 512" NXDOMAIN qr,rd,ra 47 0.054326251s
[INFO] 10.1.5.132:57023 - 15493 "A IN google.com.0.24.10.in-addr.arpa. udp 49 false 512" NXDOMAIN qr,rd,ra 49 0.007542046s
[INFO] 10.1.5.132:57023 - 14215 "AAAA IN google.com.0.24.10.in-addr.arpa. udp 49 false 512" NXDOMAIN qr,rd,ra 49 0.056274168s
[INFO] 10.1.5.132:57884 - 20786 "A IN google.com.lxd. udp 32 false 512" NXDOMAIN qr,rd,ra 32 0.000180199s
[INFO] 10.1.5.132:57884 - 38960 "AAAA IN google.com.lxd. udp 32 false 512" NXDOMAIN qr,rd,ra 32 2.001486058s
```
which only starts several >20 seconds after the curl command was executed. Once the resolution starts occuring it is also slow, taking 5-8 seconds for the whole thing to complete. It's also confusing to me that lxd is mentioned.

#### Introspection Report 
[inspection-report-20230614_173052.tar.gz](https://github.com/canonical/microk8s/files/11747806/inspection-report-20230614_173052.tar.gz)

#### Are you interested in contributing with a fix?
Would love to, but unsure where to start.

**Comment by neoaggelos** [comment]
Hi @kian99, thank you for opening this issue. Could be a couple of things:

Can you check that CoreDNS has properly started before attempting to resolve hostnames from your pod? For example, try something like `microk8s kubectl wait --for=condition=ready deploy/coredns -n kube-system` before your kubectl run command, and see whether you get the same delay. If not, then this it just takes some time for coredns to start and begin serving requests.

Second, can you test whether the following results in faster resolution? (note the final dot `.` on the hostname). If it does, then it is some issue with the resolver.

```
curl https://google.com.
```

Also useful for debugging, could you share the contents of `/etc/resolv.conf` that is rendered inside the pod?

Finally, is anything else like LXD or Docker running on the same node?

**Comment by kian99** [comment]
Hi @neoaggelos 

So I've rebooted my laptop and went to check this again and without having changed anything, the issue is no longer present though I can report a few things.

I had trouble running the wait command you suggested,
```
$ microk8s kubectl wait --for=condition=ready deploy/coredns -n kube-system
error: timed out waiting for the condition on deployments/coredns
```
but the following indicate to me coredns is running 
```
$ microk8s kubectl get deploy -n kube-system
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
coredns                   1/1     1            1           123m
calico-kube-controllers   1/1     1            1           123m
```
and
```
$ microk8s kubectl rollout status deployments/coredns -n kube-system -w
deployment "coredns" successfully rolled out
```
Which were both in the same state when I had the issue. Also interestingly, the following command has a different output,
```
microk8s kubectl logs coredns-7745f9f87f-d9xdg -n kube-system -f
.:53
[INFO] plugin/reload: Running configuration SHA512 = deb3871c00828b25727978460b261c74de0519acfb0c61c7813cc2cea8e445ddeb98d0e8f8c7bf945861f2a8b73a581c56067b8fe22b9acd076af72a94958de2
CoreDNS-1.10.0
linux/amd64, go1.19.1, 596a9f9
```
I'm no longer seeing DNS resolution logs here as I was before. In fact this is a similar output to what I saw when I switched to microk8s v1.25 which worked fine.

Further, I do have Docker and LXD running on my host, but nothing like that running on the microk8s nodes.
From my host machine,
```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.1
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        6802122
 Built:             Fri May 19 18:06:21 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.1
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       463850e
  Built:            Fri May 19 18:06:21 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
lxd version
5.14
```

So just in summary,
- This morning started my laptop which already had microk8s v1.27 installed, attempted to `juju deploy <charm>` which failed due to network timeout errors and narrowed down the issue to DNS problems.
- Removed microk8s and reinstalled from channel 1.25, all was working and proceeded to do use microk8s just fine.
- Removed microk8s again and reinstalled from channel 1.27 to create this bug report and observed the same DNS slowness as before.
- Restarted laptop a few minutes ago and now the issue is gone. Just for a sanity check,
```
$ microk8s version
MicroK8s v1.27.2 revision 5372
```

**Comment by kian99** [comment]
Thanks for the help and understood, I'll keep that in mind for the future. I'll close this issue without any ability to reproduce it further.
