### ISSUE TITLE
1.25.10 Microk8s dqlite and kubelite services restarting continuously post refresh with revision 5392

### ISSUE THREAD

**Issue by DILLY64** [canonical/microk8s#4037]
Hi

Microk8s kubectl is not responding from 10 June onwards. upon further investigation, I found out there is a refresh happened due to auto-update in microk8s which installed revision 5392 for version 1.25.10. Post restart of service the dqlite and kubelite system services where restarting continuosly till date. The system logs show below errors for dqlite and kubelite. 

![image](https://github.com/canonical/microk8s/assets/61912793/2a556bd6-9060-41a9-922b-d8d5c6e74d0c)

![image](https://github.com/canonical/microk8s/assets/61912793/93a9fc90-090c-4a51-a0ff-fec2c01175fd)

This i am seeing in dqlite logs

Jun 14 14:48:46 kubenode01 microk8s.daemon-k8s-dqlite[4116737]: k8s-dqlite: src/vfs.c:1040: vfsDatabaseWrite: Assertion `page_size > 0' failed.
Jun 14 14:48:47 kubenode01 systemd[1]: snap.microk8s.daemon-k8s-dqlite.service: Main process exited, code=killed, status=6/ABRT
Jun 14 14:48:47 kubenode01 systemd[1]: snap.microk8s.daemon-k8s-dqlite.service: Failed with result 'signal'.
Jun 14 14:48:47 kubenode01 systemd[1]: snap.microk8s.daemon-k8s-dqlite.service: Scheduled restart job, restart counter is at 14590.

This is for kubelite

Jun 14 06:56:08 qekubenode1 microk8s.daemon-kubelite[1062710]: }. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/5392/var/kubernetes/backend/kine.sock:12379: connect: connection refused"
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]: W0614 06:56:10.227212 1062710 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "Addr": "unix:///var/snap/microk8s/5392/var/kubernetes/backend/kine.sock:12379",
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "ServerName": "kine.sock",
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "Attributes": null,
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "BalancerAttributes": null,
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "Type": 0,
Jun 14 06:56:10 qekubenode1 microk8s.daemon-kubelite[1062710]:   "Metadata": null

**Comment by ktsakalozos** [comment]
Hi @DILLY64 could you share a larger portion of the dqlite logs or a `microk8s inspect` tarball?

**Comment by DILLY64** [comment]
@ktsakalozos Please find logs in attachment 
[journal.log](https://github.com/canonical/microk8s/files/11752930/journal.log)
