### ISSUE TITLE
Hugepages corrupt java 

### ISSUE THREAD

**Issue by mrefky** [canonical/microk8s#4039]
#### Summary

Have a running container that run Java application on sles12sp3 and need to enable mayastor so I need to enable hugepages as follows:
sudo sysctl vm.nr_hugepages=1024
Once this is executed ; Java no longer runs.
#### What Should Happen Instead?

Java should run properly
#### Reproduction Steps

1. ...
2. ...

**Comment by ktsakalozos** [comment]
Hi @mrefky, when you say "java" will not run you mean that any java program will not run under hugepages or does this affect only containarized applications? Can you please offer a minimal reproducer?
