### ISSUE TITLE
Error trying to enable community on MicroK8s v1.27.2

### ISSUE THREAD

**Issue by jamest-portainer** [canonical/microk8s#4047]
#### Summary
Error trying to enable community on MicroK8s v1.27.2

I have some VMs on DigitalOcean, and I've installed MicroK8s v1.27.2 revision 5372.
When I try to run `microk8s enable community` I get an error:
`microk8s community ModuleNotFoundError: No module named 'importlib_resources'`

#### What Should Happen Instead?
The community addon should enable, so I can then use community addons.

#### Reproduction Steps
Consistently reproducible.

1. Set up 3 VMs on Digital Ocean
2. Install MicroK8s
3. Try to enable community: `microk8s enable community`

This is what shows:
```
Infer repository core for addon community
Traceback (most recent call last):
  File "/snap/microk8s/5372/scripts/wrappers/addons.py", line 11, in <module>
    import jsonschema
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema._format import (
  File "/usr/lib/python3/dist-packages/jsonschema/_format.py", line 10, in <module>
    from jsonschema.exceptions import FormatError
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 13, in <module>
    from jsonschema import _utils
  File "/usr/lib/python3/dist-packages/jsonschema/_utils.py", line 12, in <module>
    import importlib_resources as resources  # type: ignore
ModuleNotFoundError: No module named 'importlib_resources'
```

Note that, if I use MicroK8s 1.26, I don't have a problem - community enables fine.

#### Introspection Report
[inspection-report-20230622_113152.tar.gz](https://github.com/canonical/microk8s/files/11833495/inspection-report-20230622_113152.tar.gz)

#### Can you suggest a fix?
no

#### Are you interested in contributing with a fix?
no

Here is full detail:
```
# microk8s version
MicroK8s v1.27.2 revision 5372

# microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 170.64.164.121:19001 170.64.165.146:19001 170.64.165.136:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    rbac                 # (core) Role-Based Access Control for authorisation
  disabled:
    cert-manager         # (core) Cloud native certificate management
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    kube-ovn             # (core) An advanced network fabric for Kubernetes
    mayastor             # (core) OpenEBS MayaStor
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    minio                # (core) MinIO object storage
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated

# microk8s enable community
Infer repository core for addon community
Traceback (most recent call last):
  File "/snap/microk8s/5372/scripts/wrappers/addons.py", line 11, in <module>
    import jsonschema
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema._format import (
  File "/usr/lib/python3/dist-packages/jsonschema/_format.py", line 10, in <module>
    from jsonschema.exceptions import FormatError
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 13, in <module>
    from jsonschema import _utils
  File "/usr/lib/python3/dist-packages/jsonschema/_utils.py", line 12, in <module>
    import importlib_resources as resources  # type: ignore
ModuleNotFoundError: No module named 'importlib_resources'
```

**Comment by neoaggelos** [comment]
Hi @jamest-portainer 

This looks eerily similar to https://github.com/canonical/microk8s-core-addons/issues/192, can you check if setting the PYTHONPATH deals with the problem?

```
export PYTHONPATH=/snap/microk8s/current/usr/lib/python3.8:/snap/microk8s/current/lib/python3.8/site-packages:/snap/microk8s/current/usr/lib/python3/dist-packages

microk8s enable community
```

Background: This is an open bug where some Python packages are loaded from the host instead of the snap, we should have a fix for this soon.

**Comment by jamest-portainer** [comment]
Hi @neoaggelos

I tried setting the PYTHONPATH as per your comment, but it didn't resolve the issue. The exact same error occurred.

**Comment by jamest-portainer** [comment]
I tried this on MicroK8s 1.27.2 and it worked (so this is pointing to `/snap/core20/1950` instead of `/snap/microk8s/5372`):
```
export SNAP=/snap/core20/1950
export PYTHONPATH=$SNAP/usr/lib/python3.8:$SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
microk8s enable community
```

**Comment by jamest-portainer** [comment]
Any thoughts as to when the 1.27 patch with this in will be released? Thanks!

**Comment by neoaggelos** [comment]
Hi @jamest-portainer, I have pushed a development build which should fix the issue, would you mind testing to verify whether it solves your issue?

```
# install
sudo snap install microk8s --classic --channel latest/edge/python-path

# or, if already installed, refresh to that channel
sudo snap refresh microk8s --channel latest/edge/python-path
```

I'd like a second confirmation that it solves the issue. Thanks!

**Comment by jamest-portainer** [comment]
Hi @neoaggelos, yes, I tried your build and it works.

As follows...
`root@ubuntu:~# snap install microk8s --classic
Download snap "microk8s" (5372) from channel "1.27/stable"                                             9% 4.76MB/s 34.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          16% 6.38MB/s 23.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          17% 6.47MB/s 22.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          18% 6.56MB/s 22.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          18% 6.57MB/s 22.Download snap "microk8s" (5372) from channel "1.27/stable"                                                         19% 6.80MB/s 21.0Download snap "microk8s" (5372) from channel "1.27/stable"                                                         20% 6.81MB/s 20.9Download snap "microk8s" (5372) from channel "1.27/stable"                                                         21% 6.95MB/s 20.3Download snap "microk8s" (5372) from channel "1.27/stable"                                                          25% 7.32MB/s 18.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          25% 7.38MB/s 17.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          26% 7.43MB/s 17.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          26% 7.43MB/s 17.Download snap "microk8s" (5372) from channel "1.27/stable"                                                          27% 7.59MB/s 17.Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       Run configure hook of "microk8s" snap if present                                                                                       microk8s (1.27/stable) v1.27.2 from Canonical✓ installed
root@ubuntu:~# microk8s enable community
Infer repository core for addon community
Traceback (most recent call last):
  File "/snap/microk8s/5372/scripts/wrappers/addons.py", line 11, in <module>
    import jsonschema
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 12, in <module>
    from jsonschema._format import (
  File "/usr/lib/python3/dist-packages/jsonschema/_format.py", line 10, in <module>
    from jsonschema.exceptions import FormatError
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 13, in <module>
    from jsonschema import _utils
  File "/usr/lib/python3/dist-packages/jsonschema/_utils.py", line 12, in <module>
    import importlib_resources as resources  # type: ignore
ModuleNotFoundError: No module named 'importlib_resources'
root@ubuntu:~# snap refresh microk8s --channel latest/edge/python-path
microk8s (edge/python-path) v1.27.3 from Canonical✓ refreshed
root@ubuntu:~# microk8s enable community
Infer repository core for addon community
Cloning into '/var/snap/microk8s/common/addons/community'...
done.
Community repository is now enabled`

Thank you!

**Comment by neoaggelos** [comment]
Perfect, thanks a lot for confirming. Merging the fix and will backport to 1.27. The fix will be out on `1.27/edge` later today and on `1.27/stable` with the next patch-level release.

Thanks again!

**Comment by angelcervera** [comment]
@neoaggelos I had the same problem. Fixed after moving into `latest/edge/python-path`.
Could you confirm how to back to the stable one after the next release? Is it with `sudo snap refresh microk8s --channel stable`?

**Comment by jamest-portainer** [comment]
@neoaggelos, you mention that 1.27.3 will be stable with the next patch-level release. Do you have any idea when that might be, or is it hard to say?

**Comment by neoaggelos** [comment]
Hi @angelcervera @jamest-portainer the fix has been backported to 1.27 tracks now, and it is available on the `1.27/edge` channel, i.e.

```
sudo snap refresh microk8s --channel 1.27/edge
```

And it is currently in progress to be pushed to `1.27/stable` (should land in a couple of days)

**Comment by jamest-portainer** [comment]
Fab, thanks @neoaggelos

**Comment by jamest-portainer** [comment]
Any idea when 1.27.3 will get into stable channel? Thanks.

**Comment by neoaggelos** [comment]
Hi @jamest-portainer, this is typically done with new Kubernetes patch-level releases. The fix should now be in `1.27/stable`:

```
$ snap info microk8s | grep 1.27/
  1.27/stable:           v1.27.4         2023-08-02 (5643) 177MB classic
  1.27/candidate:        v1.27.4         2023-07-22 (5643) 177MB classic
  1.27/beta:             v1.27.4         2023-07-22 (5643) 177MB classic
  1.27/edge:             v1.27.4         2023-07-21 (5643) 177MB classic
```

**Comment by jamest-portainer** [comment]
Thanks for pushing the patch @neoaggelos.
Understood. Yeah, I was watching for a while and no further patch came through, hence my prompting. All good now.

**Comment by jamest-portainer** [comment]
All good now. Closing issue.
