### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by r00ta** [canonical/microk8s#4052]
#### Summary
When I tried to install microk8s on an LXC container I've got the following error message
```
..
+ printf -- '\e[1;31mERROR: \033[0m the lxc profile for MicroK8s might be missing. \n'
ERROR:  the lxc profile for MicroK8s might be missing. 
+ printf -- '\t  Refer to this help document to get MicroK8s working in with LXD: \n'
	  Refer to this help document to get MicroK8s working in with LXD: 
+ printf -- '\t  https://microk8s.io/docs/lxd \n'
	  https://microk8s.io/docs/lxd 
..
```

But the link `https://microk8s.io/docs/lxd` does not exist (ref https://github.com/canonical/microk8s/blob/af64960aecea395a59d3d849e044040d23045831/snap/hooks/install#L26)

#### What Should Happen Instead?
Provide a link to the current documentation

#### Reproduction Steps

1.start an LXC container
2. run `sudo snap install --classic microk8s`

**Comment by ktsakalozos** [comment]
Thank you for reporting this @r00ta, we will have a fix for that broken link soon. For now you can read the lxc related info in https://microk8s.io/docs/install-lxd
