### ISSUE TITLE
When enabling community, you must do so on each node

### ISSUE THREAD

**Issue by jamest-portainer** [canonical/microk8s#4053]
#### Summary
For most addons, you seem to enable once and it enables the addon on all nodes in your cluster. However, when enabling community, you have to do so on each node.
If you don't do so, when you subsequently enable _any of the community addons_, they only get enabled on node(s) that have community itself enabled (in this case, only the initial node).

#### What Should Happen Instead?
Perhaps it's expected behaviour, but it wasn't expected to me - I would have thought that you enable on one node and it gets enabled on all. I know there are a few addons that require per node enabling, but they seem to be node-specific kind of ones. Please do correct me if I'm mistaken and explain why, if you wouldn't mind.

#### Reproduction Steps
1. Set up a MicroK8s cluster - I used 1.24 to 1.26 _(I have a separate issue logged about a problem enabling community on 1.27)_
2. Visit a node (I was on a control plane node) on a MicroK8s cluster (I had three control plane nodes on Digital Ocean VMs)
3. Run the command `microk8s enable community`
4. Run the command `microk8s status` and you'll see community enabled
5. Shell to one of the other nodes and run the same `microk8s status` - and you won't see community enabled

#### Introspection Report
[inspection-report-20230625_232040.tar.gz](https://github.com/canonical/microk8s/files/11861231/inspection-report-20230625_232040.tar.gz) - this is from the node I ran `microk8s enable community` on

#### Can you suggest a fix?
No.

#### Are you interested in contributing with a fix?
No.

**Comment by jamest-portainer** [comment]
Hello?

**Comment by ktsakalozos** [comment]
Hi @jamest-portainer, 

enabling an addon may produce some local state that is not replicated across all nodes. Such state may include creating local (lock) files, adding plugins under the `microk8s` command, configuring services and more. Similarly when a repository is added it is added on the nodes the respective commands where called from. Indeed this produces inconsistencies in the UX. It is not trivial to address these inconsistencies in a multinode cluster where nodes may be added at any point in time.

Apologies for this inconvenience.

**Comment by jamest-portainer** [comment]
Ok, from what you've put, I think you're saying that `microk8s enable community` will always have to be run on each node then.
