### ISSUE TITLE
install launch configuration failes with kube-ovn enabled

### ISSUE THREAD

**Issue by emalzer** [canonical/microk8s#4062]
#### Summary
installing microk8s with a launch configuration and kube-ovn enabled fails to install and enable kube-ovn
Some informations about my setup :

OS : Ubuntu 20.04 LTS
Snap version : 2.59.5
MicroK8s channel : 1.27/stable

#### What Should Happen Instead?
install and enable kube-ovn

#### Reproduction Steps

1. create launch configuration like
```
---
version: 0.1.0
addons:
  - name: dns
  - name: kube-ovn
```
2. install microk8s `snap install microk8s --classic --channel=1.27/stable` succeeds, but kube-ovn is not installed.

Error message in /var/log/syslog:
```
<30>2023-07-02T22:02:27+02:00 gs-dev00.ong.lab microk8s.daemon-cluster-agent[1515650]: Infer repository core for addon kube-ovn
<30>2023-07-02T22:02:27+02:00 gs-dev00.ong.lab microk8s.daemon-cluster-agent[1515756]: Warning: this is a potentially destructive operation. Please enable kube-ovn
<30>2023-07-02T22:02:27+02:00 gs-dev00.ong.lab microk8s.daemon-cluster-agent[1515756]: with:
<30>2023-07-02T22:02:27+02:00 gs-dev00.ong.lab microk8s.daemon-cluster-agent[1515756]:     microk8s enable kube-ovn --force
<30>2023-07-02T22:02:27+02:00 gs-dev00.ong.lab microk8s.daemon-cluster-agent[1513162]: 2023/07/02 22:02:27 Failed to apply configuration file /var/snap/microk8s/common/etc/launcher/install.yaml: failed to apply config part 0: failed to reconcile addons: failed to enable addon "kube-ovn": command [/snap/microk8s/5372/microk8s-enable.wrapper kube-ovn] failed with exit code 1: exit status 1
```

only running `microk8s enable kube-ovn --force` after the installation fixes the problem and installs kube-ovn.

**Comment by neoaggelos** [comment]
Hi @emalzer 

Can you try with the following configuration instead?

```yaml
---
version: 0.1.0
addons:
  - name: kube-ovn
    args: [--force]
  - name: dns
```

**Comment by emalzer** [comment]
Hi @neoaggelos 

Adding this argument works. I tried adding `--force` before, but did not put it into brackets.

To me it seems that this only works with `--force` - even when running the command by hand on the cli it gives a warning and the `--force` is required to switch from calico to kube-ovn. So an update of the documentation would be nice.

**Comment by neoaggelos** [comment]
@emalzer documentation has been updated accordingly, thank you very much for spotting!
