### ISSUE TITLE
Unable to connect to harbor, prompting that the certificate is invalid

### ISSUE THREAD

**Issue by jepson66** [canonical/microk8s#4066]
When I try to connect to the built harbor and run the pod, the following error is prompted
![image](https://github.com/canonical/microk8s/assets/108441697/884686b1-9b5e-4238-b17e-0020d791e4f1)
I refer to https://github.com/canonical/microk8s/issues/2521, but it still can't solve my problem. Has anyone encountered it? It has troubled me for many days

**Comment by neoaggelos** [comment]
Hi @jepson66,

Are you using the `registry` addon to build the image? If so, can you check if specifying the image as `localhost:32000/library/mynginx:v2` solves your issue?

**Comment by jepson66** [comment]
tanks，@neoaggelos The registry plug-in is enabled, but localhost: 32000 is not allowed. My harbor address is not localhost. Where should I configure it?
![image](https://github.com/canonical/microk8s/assets/108441697/d1c21d71-6286-4976-9786-263177113268)
![image](https://github.com/canonical/microk8s/assets/108441697/8e3717c3-d026-4879-b740-04e462980fa4)

**Comment by jepson66** [comment]
解决了
