### ISSUE TITLE
How modify certificate validity to 100 years？

### ISSUE THREAD

**Issue by jepson66** [canonical/microk8s#4085]
How modify certificate validity to 100 years？

**Comment by ktsakalozos** [comment]
Hi @jepson66, I am afraid you will need to provide your own certificate in this case. All certificates can be found under `/var/snap/microk8s/current/certs`. Which one do you plan to update? Please be aware that depending on the certificate you update you may need to update any kubeconfig files using it. Config files are in `/var/snap/microk8s/current/credentials/`.
