### ISSUE TITLE
cannot launch the storage pool more than 1 TB in mayastor 

### ISSUE THREAD

**Issue by narindergupta** [canonical/microk8s#4093]
#### Summary
microk8s enable core/mayastor --default-pool-size 2048G.will get stuck initializing the disk.. 

#### What Should Happen Instead?
mayastor pods should come up and initialize pods of required size

#### Reproduction Steps
Enable huge pages (needed for Mayastor).
Enable nvme_tcp module (needed for Mayastor). 
Install Microk8s snap
Configure Microk8s cluster with three nodes.
Mount second disk on /var of 3TB.

Enable mayastor with microk8s with 3TB /var/disk.

microk8s enable core/mayastor --default-pool-size 2048G

Workaround is to use the size less than a 1024 GB for example here we used 800G then no issues and mayastore is enabled with pods up and running and PVCs can be created.

**Comment by AlexsJones** [comment]
This is not enough information - what is the size of the attached disks on each node?
Can you `lsblk` each node?

**Comment by narindergupta** [comment]
Size of the disk attached and mounted was 3 TB. Unfortunately I do not have access to environment right now. Can not get lsblk as do not have access to environment right now.

**Comment by AlexsJones** [comment]
Can you share the mayastorpool information? By default the block storage is carved out of /var/snap unless you specifically define the path in the mayastorpool?

**Comment by narindergupta** [comment]
i mounted 3 TB disk on /var filesystem so that we have enough space on /var/snap and then run below command to enable it with pool size of 2048G. As you mentioned it will use /var/snao and it was using /var/snap and trying to create a device there.
microk8s enable core/mayastor --default-pool-size 2048G

**Comment by AlexsJones** [comment]
How does the error manifest, what do you/or not see happen?
Do the `/var/snap/microk8s/common/mayastor/data` files get created?

**Comment by neoaggelos** [comment]
@narindergupta if this is a separate disk, you do not have to mount it at `/var`. You should instead do (assuming the disk is at `/dev/sdb`):

```
microk8s enable mayastor
microk8s mayastor-pools add --host $hostname --device /dev/sdb
```

Which will consume the block device directly

**Comment by narindergupta** [comment]
I do not remember now but i used this method as well and have same issue where hangs says can not initialize the disk. All this is on Azure Gov cloud.
