### ISSUE TITLE
MicroK8s (1.27.4) installation using launch configurations - CIDR settings not applied

### ISSUE THREAD

**Issue by TecIntelli** [canonical/microk8s#4106]
Hello everybody,

#### Summary
We are doing some tests installing microk8s with launch configurations new in v1.27. 
Unfortunately our settings to change the cluster cidr will not be applied. 

#### What Should Happen Instead?
The IPv4 cluster cidr should be changed from 10.1.0.0/16 (default) to 10.109.0.0/16

#### Reproduction Steps
For installation of microk8s based on snap we provided the following launch configuration in /etc/microk8s.yaml:

```---
version: 0.1.0
extraCNIEnv:
  IPv4_SUPPORT: true
  IPv4_CLUSTER_CIDR: 10.109.0.0/16
extraConfigFiles:
  flannel-network-mgr-config: |
    {"Network": "10.109.0.0/16", "Backend": {"Type": "vxlan"}}
extraKubeProxyArgs:
  --cluster-cidr: 10.109.0.0/16
``` 

Installation of snap package with: 
`sudo snap install microk8s --classic --channel 1.27/candidate`
microk8s (1.27/candidate) v1.27.4 from Canonical✓ installed

Even the default pod `pod/calico-kube-controllers-6c99c8747f-tw8rx` in namespace `kube-system` came up with IP `10.1.61.65`. 

#### Introspection Report
What report might be of interest to solve this issue?

#### Can you suggest a fix?
No

#### Are you interested in contributing with a fix?
If we can.

Any idea what might be wrong with my configuation? Or can this somebody reproduce?

Thanks,
Michael

**Comment by neoaggelos** [comment]
Hi @TecIntelli, thank you for trying it the CNI configuration work! This is currently only on `master`, and expected to be released along with 1.28.

If you want to try it out, you can install MicroK8s from the latest development build:

```
# this installs 1.27 from latest development branch
sudo snap install microk8s --classic --channel latest/edge

# OR, install 1.28.0-beta.0
sudo snap install microk8s --classic --channel 1.28/beta
```

Also, the configuration should look like this:

```yaml
# /etc/microk8s.yaml
version: 0.1.0
extraCNIEnv:
  IPv4_SUPPORT: true
  IPv4_CLUSTER_CIDR: 10.109.0.0/16
```

Thanks! Let me know how this works for you!

**Comment by TecIntelli** [comment]
Hi @neoaggelos, thanks for your fast response. Just to give you a brief feedback.
Using the edge version of 1.27 doesn't change the behaviour. CNI configuration will not be applied. Have you already tested such a configuration? 
Regarding v1.28/beta, even without launch configuration this version failed at initial start after installation via snap.  `microk8s status --wait-ready` doesn't end with any response. What part of the inspection report (tarball) might be of interest to find the reason v1.28/beta failed? Just to be clear, v1.27/edge started after installation, just without customized CNI.


Thanks!

**Comment by neoaggelos** [comment]
Hi @TecIntelli 

Yes, see an example run with `latest/edge`:

```bash
root@t1:~# cat /etc/microk8s.yaml 
---
version: 0.1.0
extraCNIEnv:
  IPv4_CLUSTER_CIDR: 10.109.0.0/16

# make sure /etc/microk8s.yaml exists before installation 
root@t1:~# snap install microk8s --classic --channel latest/edge
root@t1:~# snap alias microk8s.kubectl k

# deploy some pods
root@t1:~# k create deploy nginx --image nginx --replicas 3
deployment.apps/nginx created

root@t1:~# k get pod -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP               NODE   NOMINATED NODE   READINESS GATES
nginx-77b4fdf86c-j22c2   1/1     Running   0          10s   10.109.114.198   t1     <none>           <none>
nginx-77b4fdf86c-vkpmm   1/1     Running   0          10s   10.109.114.194   t1     <none>           <none>
nginx-77b4fdf86c-nmkx2   1/1     Running   0          10s   10.109.114.200   t1     <none>           <none>
```

If MicroK8s is already installed, make sure to do `sudo snap remove microk8s --purge` and then install from scratch, otherwise it might be that you are using older configs.

**Comment by TecIntelli** [comment]
Hi @neoaggelos,

thanks again. You are right. v1.27.4 (installed with `1.27/edge`) is build 5643 and your mentioned version `latest/edge` is v1.27.4 build 5673. With the build 5673 the configuration of CNI works as expected.

Just to clarify, if we change the `IPv4_CLUSTER_CIDR` in CNI environment wouldn't we have to adopt the `--cluster-cidr` in the kube-proxy arguments and `flannel-network-mgr-config` too (as described in the [docs](https://microk8s.io/docs/ref-launch-config)), just to avoid inconsistencies?

We would suggest the following configurations if we change the CNI (pod network addresses):
```
---
version: 0.1.0
extraCNIEnv:
  IPv4_SUPPORT: true
  IPv4_CLUSTER_CIDR: 10.109.0.0/16
extraConfigFiles:
  flannel-network-mgr-config: |
    {"Network": "10.109.0.0/16", "Backend": {"Type": "vxlan"}}
extraKubeProxyArgs:
  --cluster-cidr: 10.109.0.0/16
```

Thanks for your support. 
cheers

**Comment by neoaggelos** [comment]
> Just to clarify, if we change the IPv4_CLUSTER_CIDR in CNI environment wouldn't we have to adopt the --cluster-cidr in the kube-proxy arguments and flannel-network-mgr-config too (as described in the [docs](https://microk8s.io/docs/ref-launch-config)), just to avoid inconsistencies?

Setting `IPv4_CLUSTER_CIDR` in the `extraCNIEnv` section is enough, MicroK8s will set up the rest of the arguments across the control plane components as needed.
