### ISSUE TITLE
community addons missing (e.g. keda)

### ISSUE THREAD

**Issue by klemensl** [canonical/microk8s#4110]
#### Summary
I have recently installed microk8s @ ubuntu 22 (hosted via parallels on a Mac M1) and I enabled the community addon, but the list of community addons is missing many addons e.g. keda. I have found an issue saying "keda is not available on arm64" but this should be not the case anymore, right?
I have installed 1.27.3 (snap info microk8s)
Is there anything I am missing regarding the community addons? Thank you!

#### What Should Happen Instead?
I would have expected to see keda and many other addons after enabling the community addon.

#### Reproduction Steps

1. microk8s status -> see the addon list before enabling the community addon
2. microk8s enable community -> enable the community addon
3. microk8s status -> now shows some community addons, but e.g. not keda

**Comment by ktsakalozos** [comment]
Hi @klemensl, the community addons are maintained by community members and partners. If a support for an architecture is missing it might be because the addon maintainer does not have the hardware to test it. In this case you can step in and help by deploying, testing and maintain the addon in the architecture you need.

**Comment by klemensl** [comment]
Hi @ktsakalozos, thx for the fast respone. How can I see, if a particular addon is available for arm64?

**Comment by ktsakalozos** [comment]
If you do not see it in `microk8s status` it is not available in your arch.

**Comment by klemensl** [comment]
Ok, so the the microk8s documentation is wrong (https://microk8s.io/docs/addon-keda)? keda also claims to have an arm64, this is also wrong?
Sorry for asking probably dumb questions.

**Comment by neoaggelos** [comment]
Also, adding to this, a list of addons and the supported architectures/versions can be found in the documentation https://microk8s.io/docs/addons

You are right, the addon page for the keda addon is not correct.

Also, probably the most up to date source for this information is the `addons.yaml` file, see https://github.com/canonical/microk8s-community-addons/blob/main/addons.yaml#L103-L109

Hope this helps! Sorry for the confusion.

**Comment by klemensl** [comment]
Alright, got it! Thank you for the help and the quick docu fix :)
