### ISSUE TITLE
v1.27.4 (5681) Mayastor io engine failed init if RBAC is enabled

### ISSUE THREAD

**Issue by TecIntelli** [canonical/microk8s#4112]
Hello everybody,

#### Summary
We are still doing some tests on microk8s v1.27.4 (build 5681) installed via snap with cannel `latest/edge`.
Doing so noticed that the pod `mayastor-io-engine-68pxg` get stuck with status `Init:2/3` and no diskpool is created. All other pods in namespace mayastor come up as expected.

If we delete the mentioned pod manually after a while the pod comes up in status `Running`. However the initial diskpool is not created after all. 
Just to be clear, a diskpool can be created manually after the mentioned pod is running. 

This behaviour occurs only if the addon `rbac` is installed first. Without addon `rbac` all works as expected. 

#### What Should Happen Instead?
An initial diskpool should be created automatically when the addon `mayastor` is getting enabled. 

#### Reproduction Steps
1. Installed microk8s latest/edge version via snap
2. Enable addon rbac
3. Enable addon mayastor 

#### Introspection Report

The logs of the init containers of mentioned pod are as follows:
`Defaulted container "io-engine" out of: io-engine, agent-core-grpc-probe (init), etcd-probe (init), initialize-pool (init)`

agent-core-grpc-probe:
```
...
Waiting for agent-core-grpc services...
nc: bad address 'mayastor-agent-core'
nc: bad address 'mayastor-agent-core'
Sat Jul 29 20:03:07 UTC 2023
Waiting for agent-core-grpc services...
mayastor-agent-core (10.1.166.135:50051) open
```

etcd-probe:
```
etcd-client (10.152.183.131:2379) open
```

initialize-pool:
```
...
curl: (22) The requested URL returned error: 403
Creating disk pool failed, will retry
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 36   610    0     0  100   220      0  27217 --:--:-- --:--:-- --:--:-- 31428
curl: (22) The requested URL returned error: 403
Creating disk pool failed, will retry
...
```

#### Can you suggest a fix?
No

Can anybody confirm this behaviour? 

Thanks for your efforts.
Cheers
Michael

**Comment by neoaggelos** [comment]
Hi @TecIntelli thanks for reporting this!

https://github.com/canonical/microk8s-core-addons/pull/215 should fix it
