### ISSUE TITLE
Installing Cert Manager via helm causing the cert manager add on to enable in microk8s

### ISSUE THREAD

**Issue by allanedwardslab651** [canonical/microk8s#4114]
#### Summary
We installed the latest version of microk8s last week via snap on an ubuntu 22.04 instance in ec2 aws.  Previous to this current version we had been able to successfully install cert manager via helm into microk8s by turning off the add on in microk8s then installing the helm chart for cert manager.  We disabled cert manager in microk8s via the add on disable command then proceeded to install cert manager.  The helm install fails and sticks and then when we stop the process we see that cert manager add on in microk8s was enabled.  

#### What Should Happen Instead?
Our expected behavior is to be able to disable the add on in microk8s, then install the cert manager helm chart and everthing run successfully together.  

#### Reproduction Steps
1.  install microk8s snap, or reset the cluster totally.
2. Make sure cert manager is disabled
3. Install cert manager with is jetstack helm chart 

#### Introspection Report
None

#### Can you suggest a fix?
Probably some documentation around this behavior... how do we disable cert manager from the add on then install with the helm chart.  

#### Are you interested in contributing with a fix?
Currently, we know of no known workaround.  Whatever is going on with the current version of microk8s seems broken.

**Comment by neoaggelos** [comment]
Hi @allanedwardslab651 

This is pretty much a harmless behavior that you can ignore. For reference, MicroK8s checks if an addon by identifying whether a specific resource exists on the cluster. For the `cert-manager` addon, that is [`deployment.apps/cert-manager`](https://github.com/canonical/microk8s-core-addons/blob/master/addons.yaml#L177), which is what you also get with the helm chart.

This is nothing more than a false positive. You can rest assured that MicroK8s does not affect your Helm deployment in any way. Hope this clears the confusion!
