### ISSUE TITLE
Microk8s / multipass v 1.25.11  for Mac "steals" shortcut from Chrome

### ISSUE THREAD

**Issue by commadelimited** [canonical/microk8s#4121]
#### Summary
When Microk8s / multipass is running it "steals" the keyboard shortcut View Page Source from Mac Chrome (Option + Command  + U) to launch the shell. If I shut down Microk8s / multipass the keyboard shortcut works as expected.

<img width="428" alt="image" src="https://github.com/canonical/microk8s/assets/563460/65de23d3-7846-441a-aac6-40cf86ade74a">

I'm running the following version:
```
$ microk8s version
MicroK8s v1.25.11 revision 5472
```

#### What Should Happen Instead?
An existing shortcut for another running application should not be overridden.

#### Reproduction Steps
This can be reproduced every time.

#### Introspection Report
[inspection-report-20230801_084920.tar.gz](https://github.com/canonical/microk8s/files/12229899/inspection-report-20230801_084920.tar.gz)

#### Can you suggest a fix?
I can't suggest a fix, but this seems fairly straightforward.

#### Are you interested in contributing with a fix?
I'm only a user of this software, not part of the devops team implementing it.

**Comment by neoaggelos** [comment]
Hi @commadelimited, thank you for reporting this. In MacOS we use multipass to launch and manage a VM where microk8s is running. Perhaps you can report this to the multipass project instead?

https://github.com/canonical/multipass/issues

**Comment by commadelimited** [comment]
@neoaggelos, sure thing sorry about that. That's how much I know about this software, I assumed they were one and the same.
