### ISSUE TITLE
MTU not properly set for veth interfaces

### ISSUE THREAD

**Issue by markbeierl** [canonical/microk8s#4142]
#### Summary
If microk8s is bootstrapped on a server with a non-standard MTU (for example, in a VM with Geneve overlay, the MTU would be 1442), Calico continues to use 1500 as the MTU for the veths, although the main vxlan.calico has the correct MTU

#### What Should Happen Instead?
Both the vxlan and all veths should have the same MTU.

#### Reproduction Steps

1. Start with a server that has an MTU lower then 1500.
2. Install Microk8s snap
3. View the interfaces and note the MTU:

```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1442 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:1d:77:bb brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 192.168.122.91/24 metric 100 brd 192.168.122.255 scope global dynamic ens3
       valid_lft 23992sec preferred_lft 23992sec
    inet6 fe80::f816:3eff:fe1d:77bb/64 scope link 
       valid_lft forever preferred_lft forever
11: cali8f849197aa4@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-a0090244-f7d3-e0dd-6738-7bcc89313657
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
12: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1392 qdisc noqueue state UNKNOWN group default 
    link/ether 66:76:5b:16:16:8d brd ff:ff:ff:ff:ff:ff
    inet 10.1.15.192/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::6476:5bff:fe16:168d/64 scope link 
       valid_lft forever preferred_lft forever
```

#### Introspection Report
[inspection-report-20230811_141358.tar.gz](https://github.com/canonical/microk8s/files/12322344/inspection-report-20230811_141358.tar.gz)

**Comment by neoaggelos** [comment]
Hi @markbeierl, #4149 should help resolve the issue
