### ISSUE TITLE
Have to turn on all incoming ports tcp 0-65535 to make microk8s work in aws ec2

### ISSUE THREAD

**Issue by allanedwardslab651** [canonical/microk8s#4148]
#### Summary
EC2 in aws has security groups that lock down network traffic.  The only way I can get microk8s to function is to open all incoming ports 0 - 65535 from source 0.0.0.0/0 (everywhere)

#### What Should Happen Instead?
I am trying to figure out how to lock down microk8s under security in ec2 with security groups.  My goal is to stop all incoming traffic from all sources and just have microk8s run in ec2 with only what I need open port wise.    

#### Reproduction Steps

1. open all tcp ports 0 - 65535 through from source 0.0.0.0/0 to the ec2 instances that run microk8s
2. run a command from the command line and the commands will run
3. turn off all tcp ports 0 -65535 from source 0.0.0.0/0 to the ec2 instances that run microk8s
4. the microk8s will no longer run commands from the master node

If I run microk8s status or get pods the command will block.  Not sure why turning off all incoming tcp ports would cause this.

#### Introspection Report
NA

#### Can you suggest a fix?
I am trying to figure out what ports to shut down without stopping microk8s

#### Are you interested in contributing with a fix?
yes, if I can figure out the ports

I have seen your ports document with microk8s but when I analyze the open ports listening in microk8s with netstat it lists ports not in the document you have.

**Comment by ktsakalozos** [comment]
Hi @allanedwardslab651, the ports MicroK8s services use are in https://microk8s.io/docs/services-and-ports . These ports  need to be accessible among the machines of the cluster. For external traffic (users accessing workloads) you will need to open the ports the services are exposed on, unless you have a loadbalancer.
