### ISSUE TITLE
MicroK8s v1.28 - Ceph and MicroK8s - Ceph CSI Provisioner only?

### ISSUE THREAD

**Issue by Aaron-Ritter** [canonical/microk8s#4166]
#### Summary
The new Rook Ceph addon is a really great next step. But in our case we have already a Ceph cluster. 

Is there a way to only setup the addon as a storage provisioner and storage client for RBD and CephFS?

Similar to:
https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-rbd
https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs

#### Why is this important?
There are multiple ways to setup Ceph cluster and it would be great to just setup a ceph-csi provisioner.

#### Are you interested in contributing to this feature?
yes - testing for sure

**Comment by Aaron-Ritter** [comment]
is this provisioner only?

    sudo microk8s connect-external-ceph \
        --ceph-conf /path/to/cluster/ceph.conf \
        --keyring /path/to/cluster/ceph.keyring \
        --rbd-pool microk8s-rbd

but still requires the module enabled `sudo microk8s enable rook-ceph` which allows for a k8s based ceph cluster?

**Comment by ktsakalozos** [comment]
Hi @Aaron-Ritter, if you prefer to use the ceph csi provisioners you should be able to install them following the instructions in https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs and https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-rbd. Note that helm is part of MicroK8s so you can do `microk8s helm ....` and that the `kubeletDir` value in the helm charts has to be set to `/var/snap/microk8s/common/var/lib/kubelet`, see the openebs addon as an example [1].

The `connect-external-ceph` command is part of the rook-ceph addon so it gets installed only after you enable it.

[1] https://github.com/canonical/microk8s-community-addons/blob/main/addons/openebs/enable#L72

**Comment by Aaron-Ritter** [comment]
Thanks for the additional details @ktsakalozos

But do I understand it correctly, the rook-ceph cant be used as a CSI provisioner only?

**Comment by ktsakalozos** [comment]
The rook-ceph addon will deploy the rook operator that integrates some ceph csi drivers so it is not only the CSI provisioners but maybe you treat it as such. See https://rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/
