### ISSUE TITLE
KEDA : keda could not run on microk8s 1.28.0 due to HPA deprecate the autoscaling/v2beta2 since kubernate 1.26.

### ISSUE THREAD

**Issue by xunavy** [canonical/microk8s#4167]
#### Summary

We found that keda could not run on microk8s 1.28.0,as below error:
2023-08-18T05:39:25Z ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {“kind”: “HorizontalPodAutoscaler.autoscaling”, “error”: "no matc ││ [sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1](http://sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1) {“kind”: “HorizontalPodAutoscaler.autoscaling”, “error”: “no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"”} │

That error hit the HPA deprecate the autoscaling/v2beta2 since 1.26.
Here is the [Kubernetes Removals, Deprecations, and Major Changes in 1.26 | Kubernetes](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#removal-of-the-v2beta2-horizontalpodautoscaler-api)

Here are my microk8s env:
root:# microk8s version
MicroK8s v1.28.0 revision 5788
root:~/airgap/keda-example# kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2
#### Reproduction Steps

1. clone this https://github.com/turbaszek/keda-example#redis-example
2. follow the guide to enable https://microk8s.io/docs/addon-keda
3. found that keda operator restart:
 │ keda                keda-metrics-apiserver-5566c8759-pllv5                     ●  1/1          0 Running             8  29      8      0     29      2 10.1.40.89    airgap1.fyre.ibm.com  7h34m ││ keda                keda-operator-5598cc57d7-c59d9                             ●  0/1         65 CrashLoopBackOff    0   0      0      0      0      0 10.1.40.84    airgap1.fyre.ibm.com  7h34m
4. check the error log:
  2023-08-18T05:39:25Z ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {“kind”: “HorizontalPodAutoscaler.autoscaling”, “error”: "no matc ││ [sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1](http://sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1) {“kind”: “HorizontalPodAutoscaler.autoscaling”, “error”: “no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"”} │
#### Can you suggest a fix?

That error hit the HPA deprecate the autoscaling/v2beta2 since 1.26.
Here is the [Kubernetes Removals, Deprecations, and Major Changes in 1.26 | Kubernetes](https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#removal-of-the-v2beta2-horizontalpodautoscaler-api)
so we need to upgrade the yaml to use autoscaling/v2 API.
#### Are you interested in contributing with a fix?

Yes,but I don't find the related code.

**Comment by balchua** [comment]
Hi @xunavy in case you are looking for the sources, the keda addon is in the community addons repo.

https://github.com/canonical/microk8s-community-addons/tree/main/addons%2Fkeda

**Comment by xuhjbj** [comment]
@balchua ，thanks for your update.
I hit that error is under the addons repo for community is  26 version,detail as below:
root:~# microk8s addons repo list
REPO       ADDONS SOURCE
core           21 /snap/microk8s/current/addons/core@37e04e
community      26 /snap/microk8s/current/addons/community@f5bdea

When I upgrade that addons to 28:
root@:~# microk8s addons repo list
REPO       ADDONS SOURCE
core           21 /snap/microk8s/current/addons/core@37e04e
community      28 /snap/microk8s/current/addons/community@80fea0

And restart the keda ,all errors are gone. 

Thanks,I will close this. It is better to notice that in the doc to let  customer use latest community addons.

**Comment by ktsakalozos** [comment]
Thank you both for figuring this out. We decided we would not update addons along with the rest of the k8s services when the snap refreshes. The reason for this is that addons represent workloads that may have been customized by the user to match their needs.
