### ISSUE TITLE
I can't manage to install microk8s from my ubuntu VPS with only a IPv6 address.

### ISSUE THREAD

**Issue by pajbraam** [canonical/microk8s#4169]
#### Summary
Not sure if this is a bug or should be a feature 😏
I have a brand new VPS with Ubuntu with only an IPv6 address (so no ipv4) and I get an error installing microk8s

sudo snap install microk8s --classic --channel=1.27/stable
[sudo] password for paul:
error: cannot install "microk8s": persistent network error: Post
       "https://api.snapcraft.io/v2/snaps/refresh": dial tcp 185.125.188.59:443: connect: network
       is unreachable

I have a workaround: buying a ipv4 address for my vps, but reporting it as I can imagine this could become more blocking for people in the future.

This link is from a website that checks if your site is IPv6 ready:
https://ready.chair6.net/?url=https%3A%2F%2Fapi.snapcraft.io%2Fv2%2Fsnaps%2Frefresh

[Is your site IPv6 ready?
https://ready.chair6.net/

Test results for: https://api.snapcraft.io/v2/snaps/refresh
TestResultDetail
DNS (IPv6 NS)WARNCould not resolve nameservers for hostname api.snapcraft.io.
DNS (IPv6 TLD NS)PASSHostname top-level domain (io.) does have IPv6-addressed nameservers defined.
DNS (IPv4 A Record)PASSHostname api.snapcraft.io does have an IPv4 A record (185.125.188.54, 185.125.188.55, 185.125.188.58, 185.125.188.59).
DNS (IPv6 AAAA Record)FAILHostname does not have IPv6 AAAA record.
DNS (MX Record)WARNHostname api.snapcraft.io does not have MX records.
DNS (Glue)WARNCould not resolve nameservers for hostname api.snapcraft.io.
IPv4 ConnectivityPASSSuccessfully connected to api.snapcraft.io on port 443 over IPv4.
IPv6 ConnectivityFAILCould not connect to api.snapcraft.io on port 443 over IPv6.
IPv4 LiteralsWARNCould not establish connection to URL https://api.snapcraft.io/v2/snaps/refresh.

![SCR-20230821-rbe]

(https://github.com/canonical/microk8s/assets/11958481/009f84b1-2001-4176-981f-2a2567d269a1)

=== OS INFO ===
# $ cat /etc/lsb-release
# DISTRIB_ID=Ubuntu
# DISTRIB_RELEASE=22.04
# DISTRIB_CODENAME=jammy
# DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

Running "sudo apt update/upgrade" worked all fine (lots of downloads and no issues).

#### What Should Happen Instead?
Me being super-excited to start playing around with microk9s 😝

#### Reproduction Steps
yes, shown earlier. Using avVPS from a provider that serves ipv4 as an add-on (probably I will buy it now).

1. ...
2. ...

#### Introspection Report
I wish I could run it 🙏 🤪

$ microk8s inspect
Command 'microk8s' not found 😫, but can be installed with:
sudo snap install microk8s

#### Can you suggest a fix?
See resuls of the testing website:

1) Could not resolve IPv6 nameservers for hostname api.snapcraft.io.
>>> SOLUTION >> ADD IPv6 nameservers

2) Hostname does not have IPv6 AAAA record.
>>> ADD IPv6 AAAA record(s)

3) Could not connect to api.snapcraft.io on port 443 over IPv6.
>>> Make url accessible with IPv6 

4) Could not establish connection to URL 
https://api.snapcraft.io/v2/snaps/refresh.
>>> Same same...

#### Are you interested in contributing with a fix?
I never contributed to OS/github. Guess the full solution might not be all code related (also DNS etc). I'll try to have a look around and see if I could contribute something.

**Comment by pajbraam** [comment]
Issue below is also about IPv6, but thats about kubernetes itself. My issue is already just with downloading/installing:

https://github.com/canonical/microk8s/issues/1343

**Comment by sachinkumarsingh092** [comment]
Hey @pajbraam,
Seems like an issue on the snap side of things. Can you please raise this same issue in the snap forum: https://forum.snapcraft.io/, so that they can look into this? Do let us know if you need any help with that.
Thanks.
