### ISSUE TITLE
Support snap parallel installs

### ISSUE THREAD

**Issue by lengau** [canonical/microk8s#4174]
#### Summary
Please support the snap [Parallel installs](https://snapcraft.io/docs/parallel-installs) feature. Currently this fails while running the configure hook. I believe swapping out `${SNAP_NAME}` for `${SNAP_INSTANCE_NAME}` could help, but I'm not sure what else might be needed

#### Why is this important?

I'd like to be able to run multiple versions of microk8s simultaneously in order to test/ensure that charms run with different versions of microk8s

#### Are you interested in contributing to this feature?

yes

**Comment by neoaggelos** [comment]
Hi @lengau, thank you for bringing this up. Multiple MicroK8s installs on the same host is not really supported at the moment. Other than ${SNAP_NAME} -> ${SNAP_INSTANCE_NAME} in numerous locations, this would also require:

- manually change all the default service ports for k8s (apiserver, kubelet, etc) and microk8s (cluster-agent, k8s-dqlite, etc) services
- manually update all paths for calico (or whatever cni is in use) that mount `/var/snap/microk8s/...` paths.
- manually update all paths for csi components that mount `/var/snap/microk8s/...` paths.

Note that the above is noted just for clarity and is entirely unsupported at the moment.

I would instead recommend using LXD to start multiple containers instead: https://microk8s.io/docs/install-lxd
