### ISSUE TITLE
unable to edit Prometheus alertmanager.env.yaml

### ISSUE THREAD

**Issue by venkatshivap** [canonical/microk8s#4176]
Hi I'm trying to enable email alerts in Alertmanager, but I couldn't edit alertmanager.env.yaml. Please help me if there is a alternative soultion.

**Comment by sachinkumarsingh092** [comment]
Hi @venkatshivap, the description is not very clear of what you want to do and how that is related to MicroK8s. Can you please give more information about what are you trying to achieve?

Thanks.

**Comment by venkatshivap** [comment]
I'm trying to implement email alerts using Prometheus Alert
Manager with kube-prom-stack on microk8s, I tried editing admin:///var/snap/microk8s/common/var/lib/kubelet/pods/e19a0526-cd5c-450b-abc5-52c489a29322/volumes/kubernetes.io~empty-dir/config-out/alertmanager.env.yaml,
but I'm unable to edit the file to give my own email address.
