### ISSUE TITLE
addon metrics-server is enabled but kubectl top pods fails with: "Metrics API not available"

### ISSUE THREAD

**Issue by karawitan** [canonical/microk8s#4190]
#### Summary

addon metrics-server is enabled but kubectl top pods fails with: "Metrics API not available"

#### What Should Happen Instead?

kubectl top pods should show the top summary for pods

#### Reproduction Steps

microk8s enable metrics-server
kubectl top pods

#### Introspection Report
may be available on request
n9  Report tarball is at /var/snap/microk8s/5650/inspection-report-20230901_185652.tar.gz

#### Can you suggest a fix?
do not yet

#### Are you interested in contributing with a fix?
yes

**Comment by karawitan** [comment]
```
Sep 05 08:41:09 node3 microk8s.daemon-kubelite[24517]: E0905 08:41:09.698781   24517 available_controller.go:460] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.152.183.222:443/apis/metrics.k8s.io/v1beta1: Get "https://10.152.183.222:443/apis/metrics.k8s.io/v1beta1": dial tcp 10.152.183.222:443: connect: connection refused
Sep 05 08:41:09 node3 microk8s.daemon-kubelite[24517]: W0905 08:41:09.702665   24517 handler_proxy.go:93] no RequestInfo found in the context
Sep 05 08:41:09 node3 microk8s.daemon-kubelite[24517]: E0905 08:41:09.702872   24517 controller.go:143] Error updating APIService "v1beta1.metrics.k8s.io" with err: failed to download v1beta1.metrics.k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
Sep 05 08:41:09 node3 microk8s.daemon-kubelite[24517]: , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
Sep 05 08:41:10 node3 systemd[1]: run-containerd-runc-k8s.io-4c270781caea950e384f4c8f1dd83bb21dc540b00e99d6eb91249cd579d1d89a-runc.q6g7Fd.mount: Deactivated successfully.
```

**Comment by neoaggelos** [comment]
Hi @karawitan, sorry for the delay.

This typically means that `kube-apiserver` cannot reach the metrics-server service/pod to return the metrics.

Is there an http proxy in the environment? Can you try `curl https://10.152.183.222:443/ -v` from the node where microk8s (the kube-apiserver) is running?
