### ISSUE TITLE
Microk8s not working within LXD containers

### ISSUE THREAD

**Issue by yhaliaw** [canonical/microk8s#4196]
#### Summary
In newer version of microk8s, if apparmor is not in confined mode the following error message is returned:
```
> microk8s status --wait-ready
snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks
Please make sure that the snapd.apparmor service is enabled and started.
```
However, according to our test and the documentation here: https://microk8s.io/docs/install-lxd, using microk8s in LXD containers requires the apparmor to be unconfined.

Our use case of microk8s within LXD containers is for testing only.

#### What Should Happen Instead?
Microk8s should work within LXD containers under certain configurations.

#### Reproduction Steps

Follow the steps in the following guide:
https://microk8s.io/docs/install-lxd

**Comment by ktsakalozos** [comment]
Hi @yhaliaw, from a quick search on the error it seems this might not be a MicroK8s only issue. It seems others have reported this for other snaps as well [1, 2]. Can you snap install any other snap without problems? Which MicroK8s channel are you using? Can you try the fixes suggested in the links below? 

[1] https://stackoverflow.com/questions/70053614/snap-confine-has-elevated-permissions-and-is-not-confined-but-should-be-refusin
[2] https://forum.snapcraft.io/t/snap-applications-not-launching-due-to-a-snap-confine-elevated-permissions-issue/19010

**Comment by yhaliaw** [comment]
It seems this issue is due to snapd and not microk8s.
