### ISSUE TITLE
Better handling of updating modules

### ISSUE THREAD

**Issue by scottsananderson** [canonical/microk8s#4199]
#### Summary
Disabling modules deletes all resources created and not a good approach.  A far better way would be to implement a update module.

#### Why is this important?
Disabling modules can cause downtime and lose of configuration.

#### Are you interested in contributing to this feature?
No

**Comment by neoaggelos** [comment]
Thanks for raising the issue @scottsananderson

Ref #3678, including a suggestion regarding how we could approach this: https://github.com/canonical/microk8s/issues/3678#issuecomment-1397301414
