### ISSUE TITLE
The dual stack is useful, but when the ipv6 address changes, an error occurs.

### ISSUE THREAD

**Issue by yaoqiangpersonal** [canonical/microk8s#4209]
#### Summary
The performance is good when running the dual stack for the first time, but when the IPv6 address is changed, the cni component will be abnormal. Abnormalities can also occur in ipv6 address interactions between clusters. As a result, dual-stack services cannot be accessed using IPv6 addresses.

#### What Should Happen Instead?
When the IPv6 address changes, it can automatically identify and switch to ensure that the cluster can be accessed normally by the IPv6 address.

#### Reproduction Steps
1. Create a dual-stack service
2. Allow him to access using ipv6 address
3. Use pppone to redial
4. When the service uses ipv6, it becomes inaccessible

#### Introspection Report
```
Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy asnycio usage and limits to the final report tarball
  Copy inotify max_user_instances and max_user_watches to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

Building the report tarball
  Report tarball is at /var/snap/microk8s/5916/inspection-report-20230918_075121.tar.gz
```

#### Can you suggest a fix?
If the update component is valid

###cni log
```
[INFO][105] monitor-addresses/autodetection_methods.go 103: Using autodetected IPv6 address on interface eth0: xxxx:xxxx/64
[WARNING][103] felix/vxlan_mgr.go 545: Failed to configure VXLAN tunnel device, retrying... error=Unable to find parent interface with address [xxxx:xxxx] ipVersion=0x6
```
The ipv6 address in the info information is valid, but the ipv6 address in the warning is outdated.

**Comment by neoaggelos** [comment]
Hi @yaoqiangpersonal 

I assume these logs come from the Calico CNI pods. Can you check if restarting them helps?

```
sudo microk8s kubectl rollout restart -n kube-system ds/calico-node
```

**Comment by yaoqiangpersonal** [comment]
> Hi @yaoqiangpersonal
> 
> I assume these logs come from the Calico CNI pods. Can you check if restarting them helps?
> 
> ```
> sudo microk8s kubectl rollout restart -n kube-system ds/calico-node
> ```

yes, I deleted the cni pod of the control panel and service node and it worked.

**Comment by neoaggelos** [comment]
@yaoqiangpersonal can you specify the situation under which the issue you experience occurs? Can you share a list of reproduction steps that lead to the problem?

**Comment by yaoqiangpersonal** [comment]
> @yaoqiangpersonal can you specify the situation under which the issue you experience occurs? Can you share a list of reproduction steps that lead to the problem?

Ahhh, the pppoe replay works fine this time and I can't get the same error. But obviously this error occurred in the cni pods of all nodes last time. Maybe this is my illusion. I can't replay it because I have too many ipv6 addresses. You can close this issue at any time.

**Comment by neoaggelos** [comment]
Thanks, as there is nothing actionable from our side, I will close the issue.

Please re-open the issue if it occurs again. Also, if anyone finds the issue in the future, please see above for a workaround by restarting the calico pods.

Thanks!
