### ISSUE TITLE
microk8s-hostpath broken on v1.27.5

### ISSUE THREAD

**Issue by djjudas21** [canonical/microk8s#4210]
#### Summary
On a brand new v1.27.5 MicroK8s cluster, creating a PersistentVolumeClaim for microk8s-hostpath storage does not provision a PersistentVolume

#### What Should Happen Instead?
The hostpath-provisioner should provision a volume

#### Reproduction Steps

1. Start with a brand new Ubuntu Server 22.04 VM

2. Install MicroK8s
```
sudo snap install microk8s --classic --channel=1.27/stable
```

3. Enable storage addon
```
microk8s enable hostpath-storage
```

4. Observe the StorageClass is ready
```
$ kubectl get sc
NAME                          PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
microk8s-hostpath (default)   microk8s.io/hostpath   Delete          WaitForFirstConsumer   false                  5d23h
```

5. Observe the hostpath-provisioner is ready
```
$ kubectl get po -n kube-system
NAME                                       READY   STATUS    RESTARTS      AGE
coredns-7745f9f87f-vzzf8                   1/1     Running   3 (44h ago)   5d23h
calico-kube-controllers-6c99c8747f-7wk74   1/1     Running   3 (44h ago)   5d23h
calico-node-5srlr                          1/1     Running   3 (44h ago)   5d23h
hostpath-provisioner-58694c9f4b-rkplh      1/1     Running   0             16m
```

6. Create a PersistentVolumeClaim
```
$ cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webroot
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

$ kubectl apply -f pvc.yaml 
persistentvolumeclaim/webroot created
```

7. Observe PVC is stuck in Pending
```
$ kubectl get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
webroot   Pending                                      microk8s-hostpath   67s
```
8. Observe no PV created
```
$ kubectl get pv
No resources found
```

9. Observe no relevant logs output by the hostpath-provisioner
```
$ kubectl logs -n kube-system hostpath-provisioner-58694c9f4b-rkplh
I0919 15:07:43.301246       1 hostpath-provisioner.go:97] Using busybox image: "busybox:1.28.4"
I0919 15:07:43.301557       1 leaderelection.go:248] attempting to acquire leader lease kube-system/microk8s.io-hostpath...
I0919 15:08:00.893301       1 leaderelection.go:258] successfully acquired lease kube-system/microk8s.io-hostpath
I0919 15:08:00.893614       1 controller.go:810] Starting provisioner controller microk8s.io/hostpath_hostpath-provisioner-58694c9f4b-rkplh_5596bcaa-7099-4486-a3d6-daa3e573841e!
I0919 15:08:00.893646       1 event.go:285] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"microk8s.io-hostpath", UID:"6fe043a7-6eb8-48d8-8afd-dfac319ab1a5", APIVersion:"v1", ResourceVersion:"791476", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' hostpath-provisioner-58694c9f4b-rkplh_5596bcaa-7099-4486-a3d6-daa3e573841e became leader
I0919 15:08:00.994677       1 controller.go:859] Started provisioner controller microk8s.io/hostpath_hostpath-provisioner-58694c9f4b-rkplh_5596bcaa-7099-4486-a3d6-daa3e573841e!
```

#### Introspection Report

[inspection-report-20230919_152847.tar.gz](https://github.com/canonical/microk8s/files/12663280/inspection-report-20230919_152847.tar.gz)

#### Can you suggest a fix?

Seems like the storage provisioner isn't picking up the PVC and attempting to act upon it

#### Are you interested in contributing with a fix?

No

**Comment by neoaggelos** [comment]
Hi @djjudas21 

The behavior that you see is the expected. The microk8s-hostpath storageclass is using the `WaitForFirstConsumer` binding mode, which means that it will not be provisioned before a pod tries to use it.

This is intentional, and meant to work around limitations of the hostpath provisioner itself (the volume must be created with node affinity rules, and these are not known prior to scheduling a pod).

Can you check whether creating a simple busybox pod that uses the PVC helps? Thanks!

**Comment by neoaggelos** [comment]
For cross-reference, this was also recently discussed in the following Slack thread: https://kubernetes.slack.com/archives/CAUNWQ85V/p1693225360439699
