### ISSUE TITLE
There is no audit.k8s.io/v1 API group

### ISSUE THREAD

**Issue by adubkov** [canonical/microk8s#4215]
It would be great to have audit.k8s.io/v1 group in MicroK8s to configure requests\response logging policy.

**Comment by ktsakalozos** [comment]
Hi @adubkov,

You can enable auditing following the instructions in [1]. The arguments to the API server go in `/var/snap/microk8s/current/args/kube-apiserver`. For the new arguments to take effect you need to restart MicroK8s with `sudo microk8s.stop; sudo microk8s start` or just the k8s services with `systemctl restart snap.microk8s.daemon-kubelite`.  

Is this what you are looking for? If not can you please provide more info on this issue?

[1] https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

**Comment by adubkov** [comment]
@ktsakalozos hm, I don't think that providing policy file in kube-apiserver parameters will work because there is no CRD for audit.k7s.io. maybe I'm wrong, haven't actually tried it yet.

**Comment by neoaggelos** [comment]
Hi @adubkov 

The `audit.k8s.io/v1` API group is not available through the API server, but it is indeed the format to use for the audit policy config file. You can see https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#audit-policy for more details
