### ISSUE TITLE
NodePort services aren't exported to the host

### ISSUE THREAD

**Issue by VikSh404** [canonical/microk8s#4219]
#### Summary
I created microk8s installation on ubuntu + multipass (MacOS) (also i checked it in the vbox) and faced with the problem when I have nodePort-service I can't see it in the list of local opened sockets:

#### What Should Happen Instead?
Services (nodePort) after creating should be available on the node.

#### Reproduction Steps

1. Install microk8s (+ turn off ufw)
2. Create any pod/deployment
3. Create nodePort serice 
4. try to connect to the service or get this port in output via "ss/netstal -lntp"

```bash
ubuntu@microk8s-vm:~$ k get svc
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes         ClusterIP   10.152.183.1    <none>        443/TCP        8h
microbot-service   NodePort    10.152.183.19   <none>        80:32654/TCP   8h
ubuntu@microk8s-vm:~$ ss -lntp | greo 32654
```

**Comment by ktsakalozos** [comment]
Are the pods running? Can you please attach an inspection report?

**Comment by VikSh404** [comment]
I resolved the issue. The problem was in my network configuration. Thx.
