### ISSUE TITLE
rbac addon missing in 1.28?

### ISSUE THREAD

**Issue by jasonumiker** [canonical/microk8s#4223]
I depend on the built-in admin ClusterRole with my use case. It appears that in prior versions, like 1.27 I rolled back to, that was added by doing a `microk8s enable rbac`. I see that the rbac addon is missing with 1.28.

Is there a reason for this change (some change upstream in K8s in 1.28?), or is it a bug/omission?

**Comment by neoaggelos** [comment]
Hi @jasonumiker,

The `rbac` addon is still there for 1.28, what is the issue that you are experiencing?

https://github.com/canonical/microk8s-core-addons/tree/1.28/addons/rbac

**Comment by jasonumiker** [comment]
I swear that I was running `microk8s enable rbac` and it threw a "Addon rbac was not found in any repository" error - but I just tried it again, and it is working. So maybe it was broken briefly and was fixed? Whatever happened, it is working now, and I'll close the Issue...
