### ISSUE TITLE
networkd-dispatcher[xxx]: WARNING:Unknown index xxxxxx seen, reloading interface list

### ISSUE THREAD

**Issue by karawitan** [canonical/microk8s#4230]
#### Summary
Logs of all nodes are polluted by recurrent message ( 3000 per hour )

#### What Should Happen Instead?
No error message

#### Reproduction Steps
Install Ubuntu 22.04 with microk8s 1.28.1

#### Introspection Report
/var/snap/microk8s/5922/inspection-report-20231004_152717.tar.gz available on request

#### Can you suggest a fix?
no

**Comment by neoaggelos** [comment]
Hi @karawitan 

Can you check if the following solves the issue?

```
sudo apt install linux-modules-extra-$(uname -r)
```

**Comment by karawitan** [comment]
Whow indeed it fixes the issue thanks ! Where should I put my fingers to have it included in next release ? Isn't that part of 22.04 LTS regular updates ?

**Comment by neoaggelos** [comment]
Where is this running? Is this a Raspberry Pi? I remember this issue happening on Raspberry Pis in the past.

**Comment by karawitan** [comment]
yes indeed, raspi
```
ubuntu@node9:~/$ uname -a
Linux node9 5.15.0-1038-raspi #41-Ubuntu SMP PREEMPT Fri Sep 8 12:38:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@node9:~/ceph$ grep -E "NAME|VERSION" /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ubuntu@node9:~/ceph$
```
