### ISSUE TITLE
Access dqlite

### ISSUE THREAD

**Issue by xl204431** [canonical/microk8s#4243]
## Background
a pod can be get under namespace, and the status stick as "Terminating"

but when `get` by name, `describe` or` delete` this pod , it shows that the pod can not be found.
`Error from server (NotFound): pods "XXX" not found`

## Support need

I guess the data is corrupted and want to investigate dqlite's data.
How can I access dqlite?

**Comment by neoaggelos** [comment]
It would also help if you share some details about what is the issue that are you experiencing. Thanks again!

**Comment by xl204431** [comment]
@neoaggelos 
Thank you so much for your response!! I think I might need more help!

# Issue
I can view the pod when get namespace
```
root@somehost# microk8s.kubectl get pod -n some-namespace
NAME                        READY   STATUS    RESTARTS       AGE
problem-pod              1/1     Terminating   0              447d
normal-pod                1/1     Running       0              xxd
...
normal-pod                 1/1     Running       0              xxd
```

But I can not get, describe or delete this problem pod
```
root@somehost# microk8s.kubectl get pod problem-pod -n some-namespace
Error from server (NotFound): pods "problem-pod" not found
root@somehost# microk8s.kubectl describe pod problem-pod -n some-namespace
Error from server (NotFound): pods "problem-pod" not found
root@somehost# microk8s.kubectl delete pod problem-pod -n some-namespace
Error from server (NotFound): pods "problem-pod" not found
```
So, this problem-pod keeps its data and affect velero node-agent

# Reproduce

Have no idea how it happened

# Try to debug

I use `microk8s dbctl --debug backup`, and got some data, but some data can be displayed in text format, others are binary format. Why? How can I inspect this data?

I tried
```
/snap/microk8s/current/bin/dqlite \
  --cert /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt \
  --key /var/snap/microk8s/current/var/kubernetes/backend/cluster.key \
  --servers file:////var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml \
  k8s
```
It connected, but I want to inspect what tables are in the db for further check, however, the command turns out to be error

```
dqlite> .tables
Error:  exec: near ".": syntax error
```

I try to learn k8s-dqlite's code, and only find migrator without any other tools to use.

I don't know how to solve this issue and need your help.

**Comment by xl204431** [comment]
@neoaggelos 
I tried this. The problem is that I don't know `$index.value` file's format thus I cannot recognize its data. Are there any tools to inspect this data file?

**Comment by neoaggelos** [comment]
Hi @xl204431 

I imagine this is using the internal protobufs found on the Kubernetes project, so I am not sure if I can help more in this direction. The type definition would be https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4333

I am not aware of any tooling to directly inspect the data.
