### ISSUE TITLE
MicroK8s addon enabled checks can give false positives for unrelated resources/files that contain the check_status value

### ISSUE THREAD

**Issue by testA113** [canonical/microk8s#4245]
#### Note
This issue is raised as part of [issue 165](https://github.com/canonical/microk8s-community-addons/issues/165) logged in the community addons repo. I've made this issue here because the fix could require updating the is_enabled function mentioned [here](https://github.com/canonical/microk8s-community-addons/pull/166#discussion_r1300392129).

#### Summary
I'm working at Portainer, and we came across a bug relating to the way that our addon is detected...
Given I have community addons enabled
When I install the portainer-agent (not the portainer server) in my MicroK8s cluster using a manifest file [like this](https://downloads.portainer.io/ee2-18/portainer-agent-k8s-nodeport.yaml)
And I run microk8s status, then currently Portainer shows up as an enabled addon
![image](https://github.com/canonical/microk8s/assets/83188384/5a3be928-791b-440b-b662-a731bbc8bed8)

#### What Should Happen Instead?
The portainer addon should not be detected as enabled.

#### Reproduction Steps

1. Enable community addons microk8s enable community
2. Install the portainer agent from a manifest `microk8s kubectl apply -f https://downloads.portainer.io/ee2-18/portainer-agent-k8s-nodeport.yaml`
3. Run `microk8s status` to check the enabled addons

#### Can you suggest a fix?
The current Portainer addon check_status, pod/portainer is matching for both pod/portainer-agent-xxx and pod/portainer-xxx causing Portainer to be detected as enabled when the agent is installed, as well as the server.
I propose to introduce an optional regex_check_status field, that when specified, does a more exact regex search (in the [is_enabled util function](https://github.com/canonical/microk8s/blob/40275f34e2ae1dc74b5fed052d427c43ac2a2302/scripts/wrappers/common/utils.py#L553-L579)) for matching files or kube resources, as well as updating the portainer section of addons.yaml to use this new regex_check_status. In [issue 165](https://github.com/canonical/microk8s-community-addons/issues/165) I suggested other fixes, but this seems like the best one while also enhancing MicroK8s.

#### Are you interested in contributing with a fix?

yes

**Comment by testA113** [comment]
Closing this PR as it's no longer an issue with https://github.com/canonical/microk8s-community-addons/pull/166 merged

**Comment by ben-z** [comment]
Can we reopen this? The same issue exists with many other addons (`pod/coredns`) in my case.
