### ISSUE TITLE
Unable to start microk8s in ubuntu core 22

### ISSUE THREAD

**Issue by ACodingfreak** [canonical/microk8s#4250]
#### Summary
I am not able to successfully start microk8s snap in ubuntu core 22 

#### What Should Happen Instead?
microk8s should be working fine in ubuntu core 22

#### Reproduction Steps
Yes I am able to reproduce the issue consistently in my setup

All instructions needed for the same is shared in below discourse link

https://discourse.ubuntu.com/t/unable-to-start-microk8s-on-ubuntu-core-22/39070

#### Introspection Report
Tarball is attached in below google drive location
https://drive.google.com/file/d/1Ws7eIBs41A06kHScmLNegU0mpJW5YgeG/view?usp=sharing

**Comment by ACodingfreak** [comment]
Hi All

Incase if additional information is needed please share the respective commands.
I am able to consistently reproduce the issue.

**Comment by bschimke95** [comment]
Hello @ACodingfreak,

Thank you for creating this issue.

I tried to reproduce this issue but it works just fine on my machine with:
```
multipass launch --name core core22
multipass shell core
> sudo snap install microk8s --channel=1.27-strict/stable
> sudo microk8s start
> sudo microk8s status --wait-ready
```

I assume there is something going on with your hardware setup.
Could you:
1. Upload the tarball again? It seems to be gone.
2. Collect the k8s service logs with
   `snap logs microk8s -n 1000000000`

**Comment by ACodingfreak** [comment]
Hi @bschimke95 

Please find the requested tarball in below link
https://drive.google.com/file/d/1Ws7eIBs41A06kHScmLNegU0mpJW5YgeG/view?usp=sharing

With respect to my topology, I have a physical server which is deployed with ubuntu-core-22 using MAAS on a private subnet which is connected to a NAT gateway to connect with internet. I have other servers running ubuntu-server-22.04 in the same private subnet where microk8s is successfully installed without any issue.
