### ISSUE TITLE
Node Reboot Hangs (with rook-ceph volume)

### ISSUE THREAD

**Issue by rogerwegmanneit** [canonical/microk8s#4257]
#### Summary

After setting up a single node microk8s (1.28) cluster with rook-ceph enabled I connect to an external ceph cluster with "sudo microk8s connect-external-ceph ...".

I create a PVC and a pod that mounts that PVC.

When I reboot the node with "reboot", the system hangs at "lvm2-monitor.service/stop running (...).

#### What Should Happen Instead?

The node should reboot. But the system hangs (see above).

#### Are you interested in contributing with a fix?

I cannot.

#### Notes

I use now Ubuntu 23.04. Before, with 22.04 I got systemd error messages because the mount path that cephcsi creates is too long.

**Comment by berkayoz** [comment]
Hey @rogerwegmanneit,

We'll try to reproduce the issue and see what might be causing this behavior.
I'll keep you updated.

Many thanks.

**Comment by rogerwegmanneit** [comment]
I found this: #https://github.com/rook/rook/issues/2517.

**Comment by sabaini** [comment]
This does look like network connectivity between Microk8s / Ceph was impacted somehow:

```
libceph: osdN (1) ... connect error
libceph: monN (1) ... connect error
```

**Comment by rogerwegmanneit** [comment]
I tested more and I think as long as the idea is not to stop running pods when a shutdown or reboot is done, there is no way to fix the issue - the pods need their volumes.

And not stopping the pods is what we want, correct?

**Comment by berkayoz** [comment]
I've been able to reproduce the issue, both with microceph and microk8s running together and on seperate machines.

The pods will be stopped during a reboot as they are like processes running on the OS, so it is expected. Although on a Kubernetes cluster we'd approach it in a more graceful way.

So what it seems like is that the volumes are not getting unmounted cleanly during the shutdown, which turns into the cycle of pods restarting and trying to mount the same volume. Usually if a node needs to go through a reboot, the node would get drained and tainted so all of the running pods would be evicted which in turn will unmount the volumes used by those pods. Hopefully this should resolve the reboot issue temporarily.

The linked issue on the rook repository seems like it was adressed but there were some activity lately. I'll try to check upstream as we don't deviate from there and verify our configs again.

**Comment by rogerwegmanneit** [comment]
Thanks for your investigation.
