### ISSUE TITLE
Backups are broken since upgrade to 1.27

### ISSUE THREAD

**Issue by franco-martin** [canonical/microk8s#4259]
#### Summary
Backup consists of a 213-215 byte tar.gz file containing nothing. This started happening after upgrading to 1.27
#### What Should Happen Instead?
The backup should work and probably (and statistically) be around 1.3mb.

#### Reproduction Steps
I tried reproducing with a fresh install, but I wasn't able to. Tried the backup command on all three nodes with the same result.

#### Introspection Report
[inspection-report-20231019_220512.tar.gz](https://github.com/canonical/microk8s/files/13048110/inspection-report-20231019_220512.tar.gz)

#### Are you interested in contributing with a fix?
Ill help with whatever I can

**Comment by berkayoz** [comment]
Hey @franco-martin,

Are there any errors thrown during the backup process? I've tried with the revision you have installed and could not reproduce the issue.  

There is a newer revision that you can refresh to(for 1.27.6), let me know if doing a snap refresh helps with the situation.

**Comment by franco-martin** [comment]
Ill try the refresh and share the results. No error are thrown during the
backup process.

**Comment by franco-martin** [comment]
`snap info microk8s` has 1.27.6 as the current versions for stable, candidate and beta. Edge has 1.27.7... but I'm not very comfortable using edge. Is that the one you are referring to?

**Comment by berkayoz** [comment]
Yes, refreshing to the 1.27.6 on the stable if it's not refreshed yet.

**Comment by franco-martin** [comment]
Im already running 1.27.6

**Comment by franco-martin** [comment]
Im going to try upgrading to 1.28 on the stable channel to see if that fixes the issue

**Comment by franco-martin** [comment]
After upgrading all nodes to v1.28.2 I can confirm the issue persists. Any pointers to where to look?

**Comment by berkayoz** [comment]
Hey @franco-martin,

I've not been able to replicate the issue both in single node and in HA scenarios. Having no error messages also makes this a bit challenging. Have you tried running the backup command on other control plane nodes as well?

**Comment by franco-martin** [comment]
I understand, thats why Im creating a ticket. This cluster has been
upgraded from 1.18 over the years with some nodes being recreated.
Yesterday I replaced one of them because it wouldnt become ready after
upgrading to 1.28, do you think replacing all nodes would help?
Any flags I can add to dqlite or the backup command to see what happens
during the process?
Any way I can run a backup using an external tool?

**Comment by franco-martin** [comment]
Quick update, Im reviewing the wrapper for dbctl and found the function that is run when a backup is started. Im gonna try to run the following command 
`/snap/microk8s/current/bin/migrator --endpoint unix://${SNAP_DATA}/var/kubernetes/backend/kine.sock:12379 --mode backup-dqlite --db-dir ./`
For now it looks like its doing something, I'm gonna wait and see if it does anything. Its progress, since the wrapper finishes instantly and yields an empty tar.

**Comment by franco-martin** [comment]
Another update, I did a rolling recreation of all nodes and it seems like the problem persists. Ill try to replicate by copying the DB data to another cluster

**Comment by berkayoz** [comment]
As a workaround you can to take a copy of the dqlite node with
```
tar -cvf backup.tar /var/snap/microk8s/current/var/kubernetes/backend
```
Check out [here](https://microk8s.io/docs/restore-quorum) for some more info on how to recover with the copy if needed. Let me know if the issue is reproducable with your data on another cluster.

**Comment by franco-martin** [comment]
Hi! any updates on this? I was able to reproduce the error in a new
cluster, youd just need to import the backup into a single node cluster

**Comment by franco-martin** [comment]
@neoaggelos sorry to tag you, I saw you've been helping folks on other dqlite related issues. Perhaps you can help here?
