### ISSUE TITLE
`microk8s ip` error on Mac install

### ISSUE THREAD

**Issue by domdomegg** [canonical/microk8s#4292]
#### Summary

On a Mac, when running `microk8s ip` to get the IP for the cluster the following error occurs:

```
% microk8s ip
An error occurred when trying to execute 'sudo microk8s.ip' with 'multipass': returned exit code 1.
```

#### What Should Happen Instead?

Should print the IP for the cluster

#### Reproduction Steps

1. Run `microk8s ip`

#### Introspection Report

I'm not sure what the full tarball contains, so have just included this for now:
[bom.json](https://github.com/canonical/microk8s/files/13289541/bom.json)

If helpful to know, I installed it microk8s using brew following the instructions on the microk8s site just a couple days ago.

Happy to provide narrower scope of files as required.

#### Can you suggest a fix?

Not sure what's needed here. If helpful to know, running `multipass list` or `multipass info --all` works, and results in showing the IP correctly:

```
% multipass list      
Name                    State             IPv4             Image
microk8s-vm             Running           192.168.64.2     Ubuntu 22.04 LTS
                                          10.1.254.64
```

#### Are you interested in contributing with a fix?

Not at the moment

**Comment by nibrasmuhammed** [comment]
I am getting the same from m1 mac

sudo: microk8s.ip: command not found
An error occurred when trying to execute 'sudo microk8s.ip' with 'multipass': returned exit code 1.

**Comment by neoaggelos** [comment]
Hi @nibrasmuhammed 

`microk8s ip` is not a valid Microk8s command, so I am closing the issue. Are you following a particular guide that includes it?
