### ISSUE TITLE
Kubelite keeps restart with "key failed with : missing content for serving cert"

### ISSUE THREAD

**Issue by movsb** [canonical/microk8s#4296]
#### Summary

Pods periodically restart with Status Unknown → Running → Unknown. Kubelte Events says Pod SandBox changed, will recreate it. What I saw is that from the `ps` command output,  kubelite crashes again and again.

Below are some `journalctl -f -u snap.microk8s.daemon-kubelite.service` logs:

```
Nov 09 18:31:12 nuc microk8s.daemon-kubelite[1529577]: E1109 18:31:12.884589 1529577 dynamic_serving_content.go:218] key failed with : missing content for serving cert "serving-cert::/var/snap/microk8s/6102/certs/server.crt::/var/snap/microk8s/6102/certs/server.key"
Nov 09 18:31:12 nuc microk8s.daemon-kubelite[1529577]: E1109 18:31:12.891749 1529577 dynamic_serving_content.go:218] key failed with : missing content for serving cert "aggregator-proxy-cert::/var/snap/microk8s/6102/certs/front-proxy-client.crt::/var/snap/microk8s/6102/certs/front-proxy-client.key"
Nov 09 18:31:13 nuc microk8s.daemon-kubelite[1529577]: I1109 18:31:13.255597 1529577 daemon.go:59] Stopping Kubelet
Nov 09 18:31:13 nuc microk8s.daemon-kubelite[1529577]: Stopping kubelite
Nov 09 18:31:13 nuc microk8s.daemon-kubelite[1529577]: I1109 18:31:13.255629 1529577 server.go:224] "Requested to terminate, exiting"
Nov 09 18:31:13 nuc systemd[1]: Stopping Service for snap application microk8s.daemon-kubelite...
Nov 09 18:31:13 nuc systemd[1]: snap.microk8s.daemon-kubelite.service: Deactivated successfully.
Nov 09 18:31:13 nuc systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
Nov 09 18:31:13 nuc systemd[1]: snap.microk8s.daemon-kubelite.service: Consumed 7.217s CPU time.

Nov 09 18:31:16 nuc systemd[1]: Started Service for snap application microk8s.daemon-kubelite.
Nov 09 18:31:16 nuc microk8s.daemon-kubelite[1535374]: + export PATH=/snap/microk8s/6102/usr/sbin:/snap/microk8s/6102/usr/bin:/snap/microk8s/6102/sbin:/snap/microk8s/6102/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

If I `cat` those certs files, they do have contents.

I'm not pretty sure if this is the reason why kubelite keeps crashing and the Pods get Status Unknown.

#### What Should Happen Instead?

`kubelite` shouldn't crash.

#### Reproduction Steps

No precise way to reproduce. 

#### Introspection Report

[inspection-report-20231109_181304.tar.gz](https://github.com/canonical/microk8s/files/13307076/inspection-report-20231109_181304.tar.gz)

#### Are you interested in contributing with a fix?

yes.

**Comment by neoaggelos** [comment]
Hi @movsb 

I see the following line constantly appearing in the logs of the `apiservice-kicker`, which then restarts the Kubernetes services to get the new certificates (the error you experience happens while the certificates are being refreshed).

This typically happens when the networking configuration of the host is fluctuating. If there is nothing you can think about, can you check whether the following fixes your issues?

```
sudo touch /var/snap/microk8s/current/var/lock/no-cert-reissue
```

This would prevent MicroK8s from constantly refreshing the certificates, therefore avoid constantly restarting the K8s services.

**Comment by movsb** [comment]
@neoaggelos  Many many thanks! After two days of observation, microk8s never crashes again.

When you said that the networking configuration of my host is fluctuating, may I know what is that? Something like IP changing, or interface up and down?

And, what's the impact of no-cert-reissue?

**Comment by neoaggelos** [comment]
Hi @movsb 

Indeed, that could be an IP address that changes on the host. Hard to tell without more information.

MicroK8s watches for these changes to refresh the kube-apiserver certificates so that they include all IP addresses from the host. `no-cert-reissue` is a lock file that prevents MicroK8s from doing that.

**Comment by movsb** [comment]
Hi @neoaggelos ,

I found that almost all my interfaces' IP addresses (even those from Docker containers) are listed under `[ alt_names ]` of file `certs/csr.conf`. So if any one of them changed, [`produce_certs()`](https://github.com/canonical/microk8s/blob/5b0e6bdcda7b12098495d90a15914143d644ba35/microk8s-resources/actions/common/utils.sh#L679) will re-generate certs and then kick-restart *kube-apiserver*, right?

As a single-node cluster, should I just make the [`--bind-address`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) option for *kube-apiserver* configured to stop the *kicker* from re-generating certs?

**Comment by neoaggelos** [comment]
Hi @movsb, sorry for missing this.

> As a single-node cluster, should I just make the [--bind-address](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) option for kube-apiserver configured to stop the kicker from re-generating certs?

This might become problematic if the node changes its IP address (e.g. DHCP gives out a different one after rebooting). The easiest way approach would be to create the `no-cert-reissue` lockfile:

```
sudo touch /var/snap/microk8s/current/var/lock/no-cert-reissue
```

**Comment by movsb** [comment]
@neoaggelos It's ok, no worry.

> DHCP gives out a different one after rebooting

It'll be OK since this is a crucial node that I've already bound its MAC with a static IP address on my router DHCP.

I just wanted to let you know that I'm going to close this issue as solved. BTW, I didn't find this solution at <https://microk8s.io/docs/troubleshooting>.  😊
