### ISSUE TITLE
Installing cnpg (cloud native postgres) operator silently fails with no matches for "PodDisruptionBudget"

### ISSUE THREAD

**Issue by FritsHoogland** [canonical/microk8s#4312]
#### Summary
Unable to successfully install the cloud native postgres controller 

#### What Should Happen Instead?
`microk8s kubectl apply -f \
  https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.17/releases/cnpg-1.17.5.yaml`
Does return the prompt, but when the logs are minored using: `microk8s kubectl logs -n cnpg-system  deployment/cnpg-controller-manager --all-containers=true -f`, the following error is shown:
```
{"level":"error","ts":1700498857.5022511,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"PodDisruptionBudget.policy","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:139\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\tpkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\tpkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:660\nk8s.io/apimachinery/pkg/util/wait.poll\n\tpkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:594\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\tpkg/mod/k8s.io/apimachinery@v0.24.4/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/source/source.go:132"}
```

It looks like `PodDisruptionBudget` cannot be found in Microk8s? This does work in Colima and common k8s.

OS: Mac M1 Mini Sonoma 14.1.1
MicroK8S version: MicroK8s v1.28.3 revision 6210

#### Reproduction Steps
The issue is consistent.

1. Above microk8s kubectl apply ...
2. This installs the controller, so postgres is not even installed. The controller installation throws the above error indicating it has no matches for PodDisruptionBudget.

#### Introspection Report
I do believe the error and reproduction are obvious. 

#### Can you suggest a fix?
It seems like microk8s is lagging in version?

#### Are you interested in contributing with a fix?
If there's anything that I can do please let me know.

**Comment by neoaggelos** [comment]
Hi @FritsHoogland 

The error message looks right to me. `PodDisruptionBudget` from `policy/v1beta1`, has been removed in Kubernetes versions 1.25+ ([link](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25)). The `policy/v1` api version should be used instead.

Looks like this is because you are using a old and EOL version of CNPG https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.17.5? I would recommend trying a newer version of CloudNativePG

**Comment by neoaggelos** [comment]
I also see this matrix from the CloudNativePG project for the supported Kubernetes versions, https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/supported_releases.md#support-status-of-cloudnativepg-releases

**Comment by FritsHoogland** [comment]
That is a good and valid point. I did follow the CloudNativePG documentation, but somehow ended up on a previous version.
I tested it with the latest version (1.21.1), and the controller now gets deployed.
