### ISSUE TITLE
Need help with TLS when accessing cluster remotely

### ISSUE THREAD

**Issue by mike-pisman** [canonical/microk8s#4324]
Hi, I am trying to setup load balancer to access my multi-node cluster, specifically, I want to access cluster server API using HAproxy. I have setup HAproxy to listen to address at 0.0.0.0:16433 and balance the load between each of my nodes.

I have a bit of a gap in understanding the SSL, so I am sorry if I am doing something completely wrong. I will replace my actual domain with `mydomain.com`. 

To connect to server using SSL, I have setup SSL offloading. I assume I need to provide SSL certificate issued by the cluster.

Using documentation, I have added the DNS record to my cluster:
```
[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
DNS.6 = k8s.mydomain.com
```

Then I refreshed the certificates with `microk8s refresh-certs --cert server.crt`

After this, I assumed, I need to add the certificate to my firewall, so I can use it to in HAproxy for offloading. I used `client.crt` and `client.key` to create(import) a certificate. However, when trying to connect, I get an error:
```
Unable to connect to the server: tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match k8s.mydomain.com
```

***Question 1:** Do I need to add DNS and refresh certificates only once, or I need to do it on each node in the cluster?*

***Question 2:** There are many certificates in `/var/snap/microk8s/current/certs`, which one should I use? Is it client, server, or front-proxy*

**Comment by neoaggelos** [comment]
Hi @mike-pisman, sorry for missing this

The steps you follow to add the `k8s.mydomain.com` SAN to your certificate are correct. However, if you are using HAproxy, you should make sure to configure as a Layer-4 proxy instead, and make sure all the TLS termination happens at the kube-apiserver instead.

Avoid setting a client certificate on the HAproxy side, since that could be a potential security vector (i.e: unauthenticated users getting access to kube-apiserver due to the certificate of the reverse proxy).

**Comment by mike-pisman** [comment]
@neoaggelos, Thank you for the reply. I did as you suggested.

Here is my haproxy config:
```
# Frontend: k8s-api (Kubernetes API server)
frontend k8s-api
    bind 0.0.0.0:16443 name 0.0.0.0:16443 
    mode tcp
    default_backend k8s-api

    # logging options

# Backend: k8s-api (K8S API)
backend k8s-api
    # health checking is DISABLED
    mode tcp
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    server apollo-microk8s 10.0.2.248:16443 
    server artemis-microk8s 10.0.2.249:16443 
    server poseidon-microk8s 10.0.2.246:16443
```

I can now get health with `curl -X GET https://k8s.mydomain.com:16443/healthz -k`
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
However, I still get the tls error. 
```
tls: failed to verify certificate: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, not k8s.mydomain.com
```

Could you please share a link on how to add tls certs for custom domain? For some reason, I assumed that after adding the domain name to `[ alt_names ]` and refreshing the certificates, it should generate a certificate automaticaly. 

Also, the first question is still unanswered? Do I need to add DNS and refresh certificates only once(on one node), or I need to issue commands on each node in the cluster?
