### ISSUE TITLE
dns addon can fail to configure correctly with ipv6

### ISSUE THREAD

**Issue by al8ba** [canonical/microk8s#4327]
I've noticed when using microk8s 1.27/stable and 1.28/stable, that microk8s can fail to configure coredns to use /etc/exports as expected on systems that use ipv6.

The issue comes about because the microk8s snap is using python 3.8.

On the systems that fail, the system's resolv.conf contains ipv6 addresses with scope ids, like so:

    nameserver 192.168.121.1
    nameserver fe80::5054:ff:fe00:b61d%2

The microk8s script, scripts/find-resolv-conf.py, tries to check that none of these addresses are loopbacks (they aren't), but fails because feeding an ipv6 address with a scope id (the trailing '%2') into `ipaddress.ip_address(address)` explodes with an address validation error, despite it being a perfectly valid ipv6 address. This causes the script to determine that there is no valid resolv.conf on the system, which results in coredns falling back to use 8.8.8.8 etc.

The snap need to use at least python 3.9 to prevent `ipaddress.ip_address(address)` of a scoped ipv6 address from failing.

**Comment by neoaggelos** [comment]
Hi @al8ba thank you for raising this. I have opened #4328 which should address the problem.
