### ISSUE TITLE
1.28.3 on RHEL9 - daemon-cluster-agent Permission denied error

### ISSUE THREAD

**Issue by arjen-s** [canonical/microk8s#4339]
#### Summary
I'm trying to install microk8s (1.28.3 revision 6089) on RHEL9 and although it seems to install ok, it doesn't start completely.
Looking at the logs of the different services I suspect the problem is with the daemon-cluster-agent that gives permission errors for **/var/snap/microk8s/common/addons/core/addons/dns/enable** and possibly **/var/snap/microk8s/common/etc/launcher/install.yaml**

I have disabled SE linux (that was enabled originally) as well as tried with a number of different file permissions on the addons folder (recursively) but to no avail.

Do you have any suggestions what else I could try?

**microk8s status** says microk8s is not running.

snap.microk8s.daemon-apiserver-kicker -> active
snap.microk8s.daemon-cluster-agent -> active (despite the errors)
snap.microk8s..daemon-containerd -> active
snap.microk8s.daemon-k8s-dqlite -> active
snap.microk8s.daemon-kubelite -> active

inspection report attached.

#### What Should Happen Instead?
microk8s to become active

#### Reproduction Steps
Started with a new VM on Azure using the CIS L2 RHEL9 image as image.
Installed microk8s using snap

[inspection-report-20231213_150242.tar.gz](https://github.com/canonical/microk8s/files/13662655/inspection-report-20231213_150242.tar.gz)

**Comment by neoaggelos** [comment]
Hi @arjen-s, From the inspection report, I see the following error is repeating:

```
Dec 13 10:54:24 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[8682]: 2023/12/13 10:54:24 Failed to apply configuration file /var/snap/microk8s/common/etc/launcher/install.yaml: failed to apply config part 0: failed to reconcile addons: failed to enable addon "dns": command [/snap/microk8s/6089/microk8s-enable.wrapper dns] failed with exit code 1: exit status 1
Dec 13 10:54:24 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[8682]: 2023/12/13 10:54:24 Applying /var/snap/microk8s/common/etc/launcher/install.yaml
Dec 13 10:54:55 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]: Infer repository core for addon dns
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]: Traceback (most recent call last):
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/scripts/wrappers/enable.py", line 41, in <module>
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     enable(prog_name="microk8s enable")
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     return self.main(*args, **kwargs)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 717, in main
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     rv = self.invoke(ctx)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     return ctx.invoke(self.callback, **ctx.params)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     return callback(*args, **kwargs)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/scripts/wrappers/enable.py", line 37, in enable
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     xable("enable", addons)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 470, in xable
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     protected_xable(action, addon_args)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 498, in protected_xable
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     unprotected_xable(action, addon_args)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 545, in unprotected_xable
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     p = subprocess.run(
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 493, in run
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     with Popen(*popenargs, **kwargs) as process:
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 858, in __init__
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     self._execute_child(args, executable, preexec_fn, close_fds,
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:   File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]:     raise child_exception_type(errno_num, err_msg, err_filename)
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[49196]: PermissionError: [Errno 13] Permission denied: PosixPath('/var/snap/microk8s/common/addons/core/addons/dns/enable')
Dec 13 10:55:25 calibrate3-arjen-rhel9-test-1 microk8s.daemon-cluster-agent[8682]: 2023/12/13 10:55:25 Failed to apply configuration file /var/snap/microk8s/common/etc/launcher/install.yaml: failed to apply config part 0: failed to reconcile addons: failed to enable addon "dns": command [/snap/microk8s/6089/microk8s-enable.wrapper dns] failed with exit code 1: exit status 1
```

I remember some distros having trouble executing things from `/var/...`, could this be the same problem? Can you try doing the following:

```
# remove the launch configuration (which handles the automatic dns install)
sudo rm /var/snap/microk8s/commn/etc/launcher/install.yaml

# manually enable dns
sudo microk8s enable dns
```

**Comment by arjen-s** [comment]
Hi @neoaggelos and thanks for the quick reply.

I ahve tried your suggestion and although it has removed the error in the daemon-cluster-agent logs and it suggests that start now, microk8s still isn't very happy.
'microk8s status' still shows it as not running, but i can see namespaces have been created, albeit with nothing running in them. Looking at their age I suspect they were actually created when I first deployed microk8s and ran into these issues.

`
$ k get ns
NAME              STATUS   AGE
kube-system       Active   42h
kube-public       Active   42h
kube-node-lease   Active   42h
default           Active   42h
`

When I start the dns addon manually I get the permission error for 'addons/dns/enable':

`
$ microk8s enable dns
Infer repository core for addon dns
Traceback (most recent call last):
  File "/snap/microk8s/6089/scripts/wrappers/enable.py", line 41, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/6089/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/6089/scripts/wrappers/enable.py", line 37, in enable
    xable("enable", addons)
  File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 470, in xable
    protected_xable(action, addon_args)
  File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 498, in protected_xable
    unprotected_xable(action, addon_args)
  File "/var/lib/snapd/snap/microk8s/6089/scripts/wrappers/common/utils.py", line 545, in unprotected_xable
    p = subprocess.run(
  File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/microk8s/6089/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/var/snap/microk8s/common/addons/core/addons/dns/enable')
`

I have attached the inspect output, but with a cleaned up version of the logs so it only shows logs of this startup session.
[inspection-report-20231215_104838.zip](https://github.com/canonical/microk8s/files/13684439/inspection-report-20231215_104838.zip)

Do you have any more ideas?
