### ISSUE TITLE
Unable to install Microk8s on Raspberry Pi 4

### ISSUE THREAD

**Issue by rickyd394** [canonical/microk8s#4343]
#### Summary

Installing using snap gives me an error about not being able to install on architecture armhf

error: snap "microk8s" is not available on stable for this architecture (armhf) but exists on other
       architectures (amd64, arm64).

#### What Should Happen Instead?

It should install as normal
#### Reproduction Steps

1. sudo snap install microk8s —classic

**Comment by ktsakalozos** [comment]
Hi @thgust, MicroK8s is not available on armhf it is however available for arm64.

Please try to install the 64bit version of your OS, you probably have the 32bit one.
