### ISSUE TITLE
Cannot mount secrets with Hashicorp Vault

### ISSUE THREAD

**Issue by jjolidon** [canonical/microk8s#4346]
Hello everyone, any help with the following issue would be appreciated! Thanks in advance...

#### Summary

I tried following the guidance at Hashicorp's Vault explaining how to mount secrets to a pod using secret store CSI driver, as described here: <https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-secret-store-driver#install-the-secrets-store-csi-driver>

I started with a bare 22.04 server image in Azure, and ran the following commands:

```bash
snap install core
snap install --classic microk8s
microk8s enable helm
```

Followed by the commands in the linked tutorial, starting with the `Install Vault Helm chart` section.

The result is that all commands succeed, and the mount folder is created in the pod, however the file containing the secret is not present.

The CSI provider's log include the following line, which seems to indicate that the file was created:

```plaintext
vault-csi-provider 2023-12-22T10:35:55.515Z [INFO]  server.provider: secret added to mount response: directory=/var/snap/microk8s/common/var/lib/kubelet/pods/3f3ec14f-8711-4cd0-ab7c-6b7c311b32a2/volumes/kubernetes.io~csi/secrets-store-inline/mount file=db-password
```

However the host's directory at `/var/snap/microk8s/common/var/lib/kubelet/pods/3f3ec14f-8711-4cd0-ab7c-6b7c311b32a2/volumes/kubernetes.io~csi/secrets-store-inline/mount` is empty.

This works properly in minikube installed on the same image (docker driver).

#### What Should Happen Instead?

The secret file should exist in pod.

#### Reproduction Steps

1. snap install core
2. snap install --classic microk8s
3. microk8s enable helm
4. Follow steps at <https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-secret-store-driver#install-the-vault-helm-chart>

#### Introspection Report

[inspection-report-20231222_104545.tar.gz](https://github.com/canonical/microk8s/files/13751642/inspection-report-20231222_104545.tar.gz)

#### Can you suggest a fix?

No suggestion.

#### Are you interested in contributing with a fix?

Not sure I can.

**Comment by neoaggelos** [comment]
Hi @jjolidon 

MicroK8s uses `/var/snap/microk8s/common/var/lib/kubelet` for the Kubelet dir, so deployed CSI drivers must be adjusted.

For the secrets-store-csi-driver, that means installing the chart like this (see https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/values.yaml#L82)

```
helm install csi secrets-store-csi-driver/secrets-store-csi-driver \
    --set syncSecret.enabled=true \
    --set linux.kubeletRootDir=/var/snap/microk8s/common/var/lib/kubelet
```

This should improve things.

**Comment by jjolidon** [comment]
Hello and thanks for that, it sounds promising ! I'll try it right away when I get back from vacation. Will keep you posted.

**Comment by jjolidon** [comment]
Yep, that worked, thanks a lot for the support!
