### ISSUE TITLE
microk8s is not running. microk8s inspect shows no errors

### ISSUE THREAD

**Issue by stkona** [canonical/microk8s#4347]
Running `microk8s status`: 
microk8s is not running. Use microk8s inspect for a deeper inspection.

Running `microk8s inspect`: 

Inspecting system
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy asnycio usage and limits to the final report tarball
  Copy inotify max_user_instances and max_user_watches to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite

[inspection-report-20231224_131722.tar.gz](https://github.com/canonical/microk8s/files/13761855/inspection-report-20231224_131722.tar.gz)

**Comment by neoaggelos** [comment]
Hi @stkona

In the system logs, I see the following error:

```
дек 24 12:15:15 teko-vivobook-asuslaptop-x512fj-x512fj microk8s.daemon-kubelite[504968]: E1224 2:15:15.738731  504968 server.go:179] "Failed to listen and serve" err="listen tcp 0.0.0.0:10250: bind: address already in use"
```

This means that something is already using kubelet's port (10250), and MicroK8s is crash looping.

See https://microk8s.io/docs/services-and-ports

**Comment by stkona** [comment]
Many thanks, something else was indeed using port 10250, now it works.
