### ISSUE TITLE
Unable to use multipass bridge network as default network interface device

### ISSUE THREAD

**Issue by JCzz** [canonical/microk8s#4348]
```
multipass version
multipass   1.12.2+mac
multipassd  1.12.2+mac

```
1.
`multipass launch --name main  --bridged --cpus 6 --mem 6G --disk 100G`

2.
`sudo snap install microk8s --classic`

3.
```
cd $HOME
mkdir .kube
cd .kube
microk8s config > config

```
4.
```
multipass list
Name                    State             IPv4             Image
main                    Running         192.168.64.162   Ubuntu 22.04 LTS
                                                   192.168.2.68
                                                   10.1.76.0
```

5.
`microk8s config view`
Wrong ip address, it uses 192.168.64.162  and not 192.168.2.68, which is the bridge interface.

Info: I am running multiple vms, so I need the nodes to communicate, that and I want to kubectl to the cluster from host machines.

6. Tried setting interface
```
ip a
sudo microk8s config set network interface enp0s2
```

7.
sudo snap restart microk8s

Still using 192.168.64.162  and not 192.168.2.68

How can I make it use 192.168.2.68, so I can use kubectl and not "microk8s kubectl" ?

Thanks

**Comment by neoaggelos** [comment]
Hi @JCzz 

MicroK8s will bind the kube-apiserver on all interfaces by default, so if the goal is to get a kubeconfig over the bridge interface, you could simply do:

```
microk8s config -l | sed 's/127.0.0.1/192.168.2.68/' > ~/.kube/config
```

Also, `microk8s config set network interface enp0s2` is _not_ a MicroK8s command.

**Comment by JCzz** [comment]
Thanks I will try that

**Comment by JCzz** [comment]
That worked, thanks gain
