### ISSUE TITLE
How to continue to use the IP 192.168.64.2 after reinstalling microk8s.

### ISSUE THREAD

**Issue by VicenteZhu** [canonical/microk8s#4353]
Sorry this may not be a bug, but I'm running into some problems right now. I uninstalled and reinstalled microk8s on MacOS, but I found that the new Mcirok8s-vm IP is 192.168.64.3. How can I clear the old IP record and continue to use 192.168.64.2 ?

**Comment by neoaggelos** [comment]
Hi @VicenteZhu 

The IP address is outside of MicroK8s' control, and comes from the dhcp lease. It's probably to retrieve a fresh kubeconfig file and use the new IP:

```
microk8s config -l | sed 's/127.0.0.1/192.168.64.3/' > ~/.kube/config
```

**Comment by VicenteZhu** [comment]
Thank you very much, I know what to do.
