### ISSUE TITLE
Using k8s alpha features

### ISSUE THREAD

**Issue by saeid93** [canonical/microk8s#4355]
Hi Microk8s team,
Is there a way to enable K8S alpha features during installation like how it is possible in minikube https://minikube.sigs.k8s.io/docs/handbook/config/#enabling-feature-gates ?

**Comment by neoaggelos** [comment]
Hi @saeid93 

You should be able to do this using [launch configurations](https://microk8s.io/docs/add-launch-config). As an example config, have a look at https://microk8s.io/docs/ref-launch-config#specify-kubelet-arguments-19

In general, you can use the `extra$ComponentArgs` configs to specify the feature flags that you need (and perhaps any other config). See [Launch configurations version 0.1.0](https://microk8s.io/docs/ref-launch-config#launch-configurations-version-010-2) for the complete configuration file schema

**Comment by saeid93** [comment]
Hi @neoaggelos ,

Thank you for your help. It was exactly what I was looking for and worked perfectly!
