### ISSUE TITLE
When will microk8s 1.29 be added to the latest/stable snap?

### ISSUE THREAD

**Issue by Borrelhapje** [canonical/microk8s#4358]
The 1.29/stable was released nearly a month ago (though I understand everyone is busy with the holidays). Is there a timelime as to when the latest/stable snap will be updated to 1.29?

**Comment by TecIntelli** [comment]
Currently I would not recommand to change to v1.29/stable. There is still an issue open [4361](https://github.com/canonical/microk8s/issues/4361)

**Comment by Borrelhapje** [comment]
Ah, so there is a larger bug left. Sure, I'll wait until that is fixed.
