### ISSUE TITLE
Unable to use ingress using metallb - it gets 127.0.0.1

### ISSUE THREAD

**Issue by JCzz** [canonical/microk8s#4373]
Hi there

I have enabled ingress & metallb
```
microk8s enable metallb:192.168.1.240-192.168.1.250
microk8s enable ingress
```
Now when creating ingress, it uses 127.0.0.1. Is there a way to make ingress use MetalLb to expose an external ip?
Used this description: https://microk8s.io/docs/addon-ingress

I have looked at:
`microk8s kubectl -n ingress edit configmaps nginx-load-balancer-microk8s-conf`

But with out any luck.

Thanks in advance

#### What Should Happen Instead?

Ingress will expose a Loadbalancer incl. external ip

**Comment by pedrofragola** [comment]
Hello,

Have you checked the doc[0] with the metallb/ingress examples?

Using the doc, my lab below:

kubectl  get svc -n ingress
NAME      TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
ingress   LoadBalancer   10.152.183.94   192.168.8.100   80:30440/TCP,443:32443/TCP   42s


[0] https://microk8s.io/docs/addon-metallb

**Comment by neoaggelos** [comment]
Hi @JCzz

Note that the IP address of the ingress is purely informative. You can access the ingress using any of the node IPs.

**Comment by JCzz** [comment]
Thanks both @neoaggelos and @pedrofragola

I do in fact have:
```
kubectl get svc -n ingress
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
ingress LoadBalancer 10.152.183.94 192.168.8.100 80:30440/TCP,443:32443/TCP 42s
```

Sorry, I did not mention this as I disregarded it as I can't see how it is a "normal" ingress. 
The yaml configuration is as a service as described here: 
https://microk8s.io/docs/addon-metallb
But I dont see any way to define the path?
Also why pointing at 80:30440?

So I looked at this:
https://microk8s.io/docs/addon-ingress
hoping that it would pickup from the metallb and create an external ip(I have seen this for cloud providers).
But this one, is the one creating an ingress for 127.0.0.1 and not using metallb.

**Comment by neoaggelos** [comment]
Hi @JCzz sorry for taking long to reply here.

So, `microk8s enable ingress` deploys `nginx-ingress` with the daemonset mode, which means that you can use ports 80 and 443 on any cluster node to access the services, no need to get a separate loadbalancer service.

If you create more than one ingress (and there is no conflicts between them), then they will work as expected.

`80:30440` is just a port mapping that Kubernetes creates for the services, you can consider this an implementation detail.

**Comment by JCzz** [comment]
Thanks @neoaggelos
