### ISSUE TITLE
docker doesn't want to start: unknown service containerd.services.namespaces.v1.Namespaces: not implemented

### ISSUE THREAD

**Issue by kopchik** [canonical/microk8s#4388]
Docker-in-docker (dind) doesn't want to start in microk8s.

I'm implementing a CI pipeline, which needs docker. So far all my attempts failed. Here is the shortest way to reproduce the problem:

```sh
$ kubectl run -i -t docker --image=docker --privileged=True --restart=Never --rm=True
[skip]
failed to start daemon: failed to dial "/var/run/docker/containerd/containerd.sock": unknown service containerd.services.namespaces.v1.Namespaces: not implemented
```

I tried different docker images, including `docker:dind-rootless`, all fail with the same above.
Same image works just fine in docker:

```
$ docker run -it --privileged --rm docker
[skip]
INFO[2024-01-31T10:01:01.376971149Z] Daemon has completed initialization          
INFO[2024-01-31T10:01:01.482162089Z] API listen on /var/run/docker.sock           
INFO[2024-01-31T10:01:01.482175638Z] API listen on [::]:2376
```

Any ideas how to make docker working in microk8s?

OS: Ubuntu Core 22, MicroK8s v1.29.0 revision 6370, Intel i5-1340P.

**Comment by neoaggelos** [comment]
Hi @kopchik, the containerd socket path for microk8s is at `/var/snap/microk8s/common/run/containerd.sock`.

Can you check if mounting this host path as `/var/run/docker/containerd/containerd.sock` inside the container helps?

**Comment by kopchik** [comment]
Hi @neoaggelos ! Thank you for the reply. My intention is to run docker entirely inside the pod (for security and isolation purposes). As I understand, your solution will expose host container engine (used by microk8s) to the pod, is that correct?

**Comment by neoaggelos** [comment]
Hi @kopchik, yes that is true, apologies I believed this was what you attempted to do. I see you are using Ubuntu Core 22, which means you are using the strict version of microk8s as well, right?

In this case, a restricted security profile is applied for the workload, and this is probably playing into what you are experiencing. Can you check if there are any apparmor denials with `dmesg`?

**Comment by kopchik** [comment]
Aha! Yes, @neoaggelos , that's the case. I use strict version of microk8s. I installed microk8s locally on my ubuntu desktop, and I was able to reproduce the issue. In `strict` version docker-in-docker doesn't work. When I installed "classic" microk8s docker was able to start.

Now onto dmesg. Indeed there this error:
```
audit: type=1400 audit(1706723665.607:6211): apparmor="DENIED" operation="file_lock" class="file" profile="snap.microk8s.daemon-containerd" name="/var/lib/docker/containerd/daemon/io.containerd.metadata.v1.bolt/meta.db" pid=3479503 comm="containerd" requested_mask="k" denied_mask="k" fsuid=0 ouid=0
```

I tried to add this annotation, but it did nothing: `container.apparmor.security.beta.kubernetes.io/docker: unconfined`. Either I didn't apply it correctly, or it simply has no-op as containerd is already running inside apparmor, so not sure how this annotation supposed to help.

I also tried to mount `/var/lib/docker/` inside the container with `hostpath-storage`, but that didn't change anything, the error message remains the same. I.e., apparmor shows filepath relative to container, not the host path.

So, is this a bug or a feature?) I kinda feel like restriction to forbid locks is a bit too strict to my liking, as I, for example, cannot do "apk add telnet" inside containers with the same error:
```
$ kubectl run -i -t alpine --image=alpine --privileged=True --restart=Never --rm=True
# apk add telnet
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```
So, it seems I won't be able to build images inside k8s containers even if I somehow make docker work? I mean, file locking is pretty natural system call for package managers.

**Comment by neoaggelos** [comment]
Hi @kopchik, your observation is correct. Given that containerd itself runs under an apparmor profile, it is not allowed to run unconfined workloads. It is true that this is limiting, hence why MicroK8s is classic by default.

When installed with strict confinement, MicroK8s is running under a profile that, as you found, might be too restrictive at times. This is by design, and there is future work to make the profile selection for the workloads more powerful, but that is not currently possible.

Currently, the solution would be to use classic MicroK8s instead, with Ubuntu Server rather than Ubuntu Core.
