### ISSUE TITLE
Is it Possible to Change the Expiry Dates in DLL files

### ISSUE THREAD

**Issue by RamShukla2022** [canonical/microk8s#4409]
Having few files dll and exe after running it exipery dates come to 2023 needs to extend further for 10 yers can any one help me

**Comment by ktsakalozos** [comment]
Probably not the right place for this question.

**Comment by RamShukla2022** [comment]
Having DLL files which were using earlier but now it shows Exipy of 2023
need to extend the same for another 10 yers can you help
