### ISSUE TITLE
Creating two containers of WSO2 Apim (Active-Active Setup)

### ISSUE THREAD

**Issue by broknight** [canonical/microk8s#4443]
apiVersion: apps/v1 kind: Deployment metadata: name: wso2-apim spec: replicas: 2 selector: matchLabels: app: wso2-apim template: metadata: labels: app: wso2-apim spec: containers: - name: wso2-apim image: wso2/wso2am:3.2.0 ports: - containerPort: 9443

Run: kubectl apply -f wso2-apim-deployment.yaml

Above info script from Chatgpt. Please help me if this script is accurate to deploy a container with active-active setup? I'm going to deploy a WSO2, someone could help me to check the script or any suggestion to update this. It is really appreciated. I'm using here microk8s.

**Comment by neoaggelos** [comment]
Sorry, this is not relevant.
