### ISSUE TITLE
Disabling addons not working properly

### ISSUE THREAD

**Issue by marwenbk** [canonical/microk8s#4466]
#### Summary

im trying to uninstall helm using microk8s disable helm. it remain active
#### What Should Happen Instead?

i expect helm to be disabled when i run microk8s status
#### Reproduction Steps

1. microk8s disable helm
2. Infer repository core for addon helm
   Helm comes pre-installed with MicroK8s
3. miccrok8s status , helm is still enabled

#### Can you suggest a fix?

This is above my technical skills

#### Are you interested in contributing with a fix?

[Uploading inspection-report-20240319_141042.tar.gz…]()

**Comment by bschimke95** [comment]
Hi marwenbk,

Please upload the inspection report. The link you provided leads to this issue, not the report.
Thanks!

**Comment by marwenbk** [comment]
i apologize for the confusion, Here you go 
[Uploading inspection-report-20240319_141042.tar.gz…]()

**Comment by marwenbk** [comment]
[inspect.tar.gz](https://github.com/canonical/microk8s/files/14731488/inspect.tar.gz)
There's an issue with file attachement, is there another ways to send the file?

**Comment by bschimke95** [comment]
Got the inspection report - all good.

Note that you cannot disable helm for microk8s. That should have been printed when you ran `microk8s disable helm` (see https://github.com/canonical/microk8s-core-addons/blob/main/addons/helm3/disable).
Disabling other addons should work just fine.
