### ISSUE TITLE
Unable To Interact With Microk8s on Windows 2022 With Virtual Box

### ISSUE THREAD

**Issue by ThePieMonster** [canonical/microk8s#4476]
#### Summary
Unable to interact wth microk8s

microk8s kubectl get pods

`E0331 18:54:13.759087    3084 memcache.go:265] couldn't get current server API group list: Get "https://10.0.2.15:16443/api?timeout=32s": dial tcp 10.0.2.15:16443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

#### What Should Happen Instead?
kubectl command provides information

#### Reproduction Steps
Install microk8s with Oracle Virtual Box on Windows Server 2022 and try to interact with the cluster. 

#### Introspection Report

[inspection-report-20240331_185644.tar.gz](https://github.com/canonical/microk8s/files/14817982/inspection-report-20240331_185644.tar.gz)

**Comment by ThePieMonster** [comment]
Found a similar issue from some time ago. 
https://github.com/canonical/microk8s/issues/3388

If the IP of the master node changed, how would I know? Where would I find the new IP?

**Comment by neoaggelos** [comment]
Hi @ThePieMonster, you should either ensure that the VM has the same IP address across reboots (see linked issue for some steps), or simply see the current IP (by means of `ifconfig` on the VM) and adjust your kubeconfig accordingly.

**Comment by ThePieMonster** [comment]
@neoaggelos The host machine that is running MicroK8S is a physical windows server machine with a static IP.
I don't see how that would impact this however.

**Comment by neoaggelos** [comment]
Ah, okay, this could probably be a different kind of issue than the one you linked. I am seeing this in the logs of `k8s-dqlite`:

```
Mar 31 18:07:44 microk8s-vm microk8s.daemon-k8s-dqlite[1776]: /snap/microk8s/6541/bin/grep: /usr/local/lib/sysctl.d/: No such file or directory
```

Can you try to create this directory manually? Running something along those lines on the VM should help:

```
sudo mkdir -p /usr/local/lib/sysctl.d/
sudo snap restart microk8s
```

Then, observe the logs to see if k8s-dqlite is coming up with:

```
sudo journalctl -u snap.microk8s.daemon-k8s-dqlite -f
```

**Comment by ThePieMonster** [comment]
I ended up switching to MiniKube as it runs in the context of Docker or Hyper-V without issue.
