### ISSUE TITLE
docs : please add *.svc as no_proxy in install guide behind a proxy

### ISSUE THREAD

**Issue by mottoslo** [canonical/microk8s#4540]
#### Summary

In the document for installing behind proxy (https://microk8s.io/docs/install-proxy), *.svc should be added to no_proxy variable
The document says to add internal IP ranges to no_proxy to prevent requests within cluster going through proxy.
Considering that domains ending with .svc is also only used kubernetes coreDNS, I think *.svc should be included in no_proxy variable for kube-api configuration

I am quite new to the programming world, so please let me know if I'm getting something wrong.
Thank you :)

#### What Should Happen Instead?

document should add *.svc to no_proxy and NO_PROXY variable

#### Are you interested in contributing with a fix?

yes ?

**Comment by neoaggelos** [comment]
Thank you for raising this @mottoslo! I've updated the docs to include `.svc,localhost` in the no proxy lines. These are probably quite common and harmless for most setups.

**Comment by mottoslo** [comment]
@neoaggelos Thank you for your quick response ! Although, I think what should've been added is *.svc, not .svc   ...?
