### ISSUE TITLE
docs: follow up issue for #4540

### ISSUE THREAD

**Issue by mottoslo** [canonical/microk8s#4541]
https://github.com/canonical/microk8s/issues/4540
my suggestion was accepted, but .svc was added to docs instead of *.svc
I don't think leaving a comment is reaching out, hence a new issue

thank you !

**Comment by neoaggelos** [comment]
Hi @mottoslo, `.svc` should suffice for traffic towards service endpoints. Are you having any issues? I'm asking because the format accepted by `no-proxy` can vary across tools, so I would like to know if something is breaking for you.

**Comment by mottoslo** [comment]
Thank you ! @neoaggelos , nevermind this issue.
This issue was raised due to my lack of understanding of the no_proxy environment variable.
I though for some reason that * should be present to specify that any subdomain should match the variable.
But I found out that .svc matches the intended no proxy, and nothing breaks for me for now
Have a great day :)

**Comment by antony-jr** [comment]
is this somehow related?

![image](https://github.com/canonical/microk8s/assets/33930174/de681927-b2ed-46f3-94c5-81a883c8dc3e)
