### ISSUE TITLE
Use real names for private registry images

### ISSUE THREAD

**Issue by waldner** [canonical/microk8s#4575]
#### Summary

I'm able to use images from a private registry following the instructions here https://microk8s.io/docs/registry-private and here https://microk8s.io/docs/install-offline. However, when I run `microk8s ctr image ls`, they are shown with their original names (eg `docker.io/whatever`) rather than their real names (eg `myregistry.com/whatever`).

#### Why is this important?

This behavior is confusing and makes it harder to check whether images are really being pulled from the private registry or the original registry.

#### Are you interested in contributing to this feature?

Might be, but I'm not familiar enough with the microk8s code. If this can already be done, apologies but I didn't find instructions.

**Comment by waldner** [comment]
All the methods you suggest are clumsy at best, and depending on the exact scenario, might even be downright not doable.
As far as I know, no other kubernetes distro behaves this way, but ok, I just wanted to make sure I wasn't missing anything.

**Comment by neoaggelos** [comment]
Well, microk8s is not doing any magic here, this is how containerd behaves when given a private registry mirror. you should be able to see the mirror image tags if you use those images directly (i.e. you edit deployments to use `mirror:5050/calico/node:v3.25.0` instead of `docker.io/calico/node:v3.25.0`).

Hope this helps

**Comment by waldner** [comment]
Well, then I'd appreciate a way to be able to specify direct external names for eg this set of images https://github.com/canonical/microk8s/blob/master/build-scripts/images.txt (because then for normal workloads I can already use the external names in deployment/pod etc definitions). Is that possible at all?

**Comment by neoaggelos** [comment]
Hi @waldner. No, unfortunately, this is not easy to do out of the box.

**Comment by waldner** [comment]
Ok, thanks for your comments!
