### ISSUE TITLE
MicoK8s issues with Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by node077** [canonical/microk8s#4607]
#### Summary

Yes I am having issues with MicroK8s in an LXD container for Ubuntu Server LTS 24.04 for both hypervisor and lxd instance version with Microk8s  v1.29.7  7018  1.29/stable  canonical  classic . Im receving apparmor issues stating it cannot find the profile for app armor but the service is running when I run **microk8s kubectl get pods --all-namespaces** I get several errors: 

Error Output:

NAMESPACE       NAME                                                     READY   STATUS                  RESTARTS         AGE
kube-system     calico-kube-controllers-77bd7c5b-bp89p                   0/1     Error                   206              27d
kube-system     calico-node-p2dd4                                        0/1     Init:CrashLoopBackOff   10 (4m30s ago)   7d2h
kube-system     coredns-864597b5fd-4lcsz                                 0/1     Unknown                 2                27d
kube-system     dashboard-metrics-scraper-5657497c4c-vnzvx               0/1     Unknown                 2                27d
kube-system     kubernetes-dashboard-54b48fbf9-9f58p                     0/1     Error                   169              27d
kube-system     metrics-server-848968bdcd-5fdrt                          0/1     Unknown                 2                27d
observability   alertmanager-kube-prom-stack-kube-prome-alertmanager-0   0/2     Unknown                 3                26d
observability   kube-prom-stack-grafana-5d449986fb-s94qp                 0/3     Unknown                 3                26d
observability   kube-prom-stack-kube-prome-operator-7744b7b479-q2qdz     0/1     Unknown                 1                26d
observability   kube-prom-stack-kube-state-metrics-548b48db88-bp9bd      0/1     Unknown                 1                26d
observability   kube-prom-stack-prometheus-node-exporter-pz4qs           1/1     Running                 11 (15m ago)     26d
observability   loki-0                                                   0/1     Unknown                 1                26d
observability   loki-promtail-mqbvn                                      0/1     Unknown                 1                26d
observability   prometheus-kube-prom-stack-kube-prome-prometheus-0       0/2     Unknown                 2                26d
observability   tempo-0                                                  0/2     Unknown                 2                26d

Im trying to initialize MPS on this Microk8s instance and cannot get past this MicroK8s issue. I am wondering if there are some differences between Ubuntu Server LTS versions for the packages that might be the issue. Any Help would be much appreciated

#### Reproduction Steps

1. ...
2. ...

**Comment by eaudetcobello** [comment]
Hi @node077,

Could you check out this page and let me know if it helps you? https://microk8s.io/docs/install-lxd.
