### ISSUE TITLE
Can't get insecure registry working uses https instead

### ISSUE THREAD

**Issue by jrgleason** [canonical/microk8s#4640]
#### Summary
I have a docker registry running in another namespace 

```
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
    - name: registry-port
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
```

It works fine and I have no trouble pushing to it from my local box...

```
$ docker push 10.0.0.58:30500/block-party:latest
The push refers to repository [10.0.0.58:30500/block-party]
...
latest: digest: sha256:6923ac9281f4ed9c5c2fdb1e70acf906d014a104f130f04bcc7878793f8a3479 size: 1988
```

But when I try to use it like

```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-party
  template:
    metadata:
      labels:
        app: block-party
    spec:
      containers:
        - name: block-party
          image: 10.0.0.58:30500/block-party:latest
          ports:
            - containerPort: 80
 ```

It can't get the image if I do 

```
$ sudo microk8s.ctr images pull 10.0.0.58:30500/block-party:latest
INFO[0000] trying next host                              error="failed to do request: Head \"https://10.0.0.58:30500/v2/block-party/manifests/latest\": http: server gave HTTP response to HTTPS client" host="10.0.0.58:30500"
ctr: failed to resolve reference "10.0.0.58:30500/block-party:latest": failed to do request: Head "https://10.0.0.58:30500/v2/block-party/manifests/latest": http: server gave HTTP response to HTTPS client
```

I have followed the instructions here 

https://microk8s.io/docs/registry-private

```
~$ cat /var/snap/microk8s/current/args/certs.d/10.0.0.58:30500/hosts.toml
server = "http://10.0.0.58:30500"

[host."http://10.0.0.58:30500"]
capabilities = ["pull", "resolve"]
```

I also tried locally using `registry.network.svc.cluster.local:5000` instead but I still can't get it to use the registry as insecure.

#### What Should Happen Instead?
As seen from the error message it is still using https instead of http

#### Introspection Report
[inspection-report-20240823_215125.tar.gz](https://github.com/user-attachments/files/16733966/inspection-report-20240823_215125.tar.gz)

#### Can you suggest a fix?
Better documentation

#### Are you interested in contributing with a fix?
yes

**Comment by jrgleason** [comment]
seems similar to 

https://github.com/canonical/microk8s/issues/3288

But my url matches the example

**Comment by jrgleason** [comment]
NM after restarting for the 100th time it started working so I think it was a hung process

**Comment by jcabrerazuniga** [comment]
If using Self Signed Cert:

Trust the certificate authority (recommended)
Identify the CA: If the certificate is self-signed, it's its own CA. If it's signed by an internal CA, you need that CA's certificate.
Add the CA to your system's trust store: On most Linux distributions, you can add the CA certificate to /usr/local/share/ca-certificates/ and then run sudo update-ca-certificates to incorporate it into the system's trust store.
Then the provided instructions worked for me
