### ISSUE TITLE
Second node is not reflected in microk8s status after successful join

### ISSUE THREAD

**Issue by louiseschmidtgen** [canonical/microk8s#4649]
## Description
This issue occurs when you join a second node (node2) to a first microk8s node (node1). The join is successful but the node does not appear in node status.
This example is observed on mk 1.28 but I've also observed it on recent versions:
```
ubuntu@node2:~$ sudo microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 10.223.255.75:19001
  datastore standby nodes: none
```
When we add a third node the status gets updated:
```
ubuntu@node2:~$ sudo microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 10.223.255.75:19001 10.223.255.175:19001 10.223.255.12:19001

```

**Comment by ktsakalozos** [comment]
Hi @louiseschmidtge, this is how it is supposed to work. The second node is not part of the raft quorum so it is not in the list of "datastore master nodes". The second node is also not able to act as a master node in case the first node fails. Therefore the second node is not part of the "datastore standby nodes" either. If we had a list of "k8s cluster control plane nodes" we would have includes the second node there.
