### ISSUE TITLE
 invalid configuration: memorySwap.swapBehavior "UnlimitedSwap"

### ISSUE THREAD

**Issue by koss822** [canonical/microk8s#4704]
#### Summary
(error: invalid configuration: memorySwap.swapBehavior "UnlimitedSwap" must be one of: "", "LimitedSwap" or "NoSwap", path: &TypeMeta{Kind:,APIVersion:,})

#### What Should Happen Instead?
but according to https://kubernetes.io/blog/2023/08/24/swap-linux-beta/ it is a valid option

#### Reproduction Steps
**/var/snap/microk8s/7232/args/kubelet**
--config=/var/snap/microk8s/current/args/kubelet.yml

**/var/snap/microk8s/7232/args/kubelet.yml**
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
ImageMaximumGCAge: 240h
memorySwap:
  swapBehavior: UnlimitedSwap

#### Introspection Report
[inspection-report-20241014_135827.tar.gz](https://github.com/user-attachments/files/17363552/inspection-report-20241014_135827.tar.gz)

#### Are you interested in contributing with a fix?
no

**Comment by berkayoz** [comment]
Hey @koss822 

I believe `UnlimitedSwap` option is removed in 1.30, check out:
* https://kubernetes.io/blog/2024/03/12/kubernetes-1-30-upcoming-changes/#node-memory-swap-support-kep-2400-https-kep-k8s-io-2400
* https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory

**Comment by koss822** [comment]
thanks, missed this one
