### ISSUE TITLE
There should be a way to configure custom DNS

### ISSUE THREAD

**Issue by giner** [canonical/microk8s#543]
We have Google DNS blocked in our networks and hardcoded DNS is a headache.

Documentation [explains](https://microk8s.io/docs/) how to change DNS configuration however it doesn't work for long because it is soon overridden by something else, for example, if I install Istio the original DNS servers (8.8.8.8 and 8.8.4.4) are back.

It would be nice to have a way of configuring DNS in a more permanent way so that enabling/disabling of the DNS plugin would not override the settings.

**Comment by balchua** [comment]
I think its better to have this in the coredns config `forward . $SNAP_DATA/etc/resolv.conf`.  While the default content of this file points to 8.8.8.8 and 8.8.4.4.  This will allow users to change this.  Wdyt?

**Comment by giner** [comment]
This could be an option if it worked in the case when resolve.conf points to loopback.

**Comment by balchua** [comment]
Does coredns accept loopback `127.0.0.1` on forward config?  I thought it will not allow it.

**Comment by giner** [comment]
This is what I'm saying. Pointing coredns to resolv.conf may not work in certain cases.

**Comment by ktsakalozos** [comment]
I think, extending the work described in https://github.com/ubuntu/microk8s/issues/465 to also configure add-ons would help.

**Comment by giner** [comment]
Still valid

**Comment by dkozlov** [comment]
You can use the following script as a workaround:
```bash
kubectl get -n kube-system cm/coredns --export -o yaml | cat <<EOF | kubectl replace -n kube-system -f -
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        log . {
          class error
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          policy sequential
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: coredns
EOF
```

**Comment by giner** [comment]
Still valid

**Comment by ca-scribner** [comment]
I think the documentation has changed this the original message - I didn't see what notes it gave that would get overridden later.  But in current docs I see [this](https://microk8s.io/docs/addon-dns).  Does that handle what we're looking for here?

**Comment by krishhtof** [comment]
> I think the documentation has changed this the original message - I didn't see what notes it gave that would get overridden later. But in current docs I see [this](https://microk8s.io/docs/addon-dns). Does that handle what we're looking for here?

I have tried doing `microk8s enable dns:/etc/resolv.conf` and I have also tried `microk8s enable dns:<DNS_IP>`, despite of which the Google DNS servers persist in the Config Map of CoreDNS. So, for me the link you mentioned in your comment, doesn't help.

**Comment by giner** [comment]
The following works now, so the issue is resolved:
```shell
microk8s enable dns:"DNS_IP1,DNS_IP2"
```
