### ISSUE TITLE
how can I get JSON logs to be recognized by the fluentd addon?

### ISSUE THREAD

**Issue by sam-github** [canonical/microk8s#803]
> Please run `microk8s.inspect` and attach the generated tarball to this issue.

Will do if necessary, but my system is very vanilla.

I did a `microk8s.reset; microk8s.enable dns fluentd`, then ran one app that logs lines in JSON to stdout. I can see the lines in Kibana after adding the data source, but the entire json log line is showing up as the value of the `log: ` property, and I can't access its structured internal info.

I thought this might be a problem with the es or fluentd config for a while, but I now think that some microk8s component responsible for taking container log output and writing it to /var/log is breaking the json by prepending the non-json data, but I can't find the component, or how to configure it so that it doesn't do that.

The fluentd config map has
```
# CRI Log Example:
# 2016-02-17T00:04:05.931087621Z stdout F [info:2016-02-16T16:04:05.930-08:00] Some log text here
```

After that is the multi_format config that looks like it should handle that prefixed format _or_ JSON, but I can't see a way to make it understand lines that are "JSON after a prefix", and I'm starting to think that isn't what it is supposed to do, it shouldn't be getting broken JSON in the first place.

What I see in `/var/log/{pod,containers}/` matches the "CRI" log format described in the configmap:

> 2019-11-14T13:54:44.26232227-08:00 stdout F {"level":30,"time":157376848426 ... more JSON

`kubectl log MYPOD` is outputing valid json lines like:

>  {"level":30,"time":157376848426 ... more JSON

Whatever is reading from the kube container's log stream and writing to disk needs to be informed that my logs are JSON, or at least some lines are, there is some noise not under my control like `npm start blah` at the beginning that is not JSON.

I thought it might be "journald" doing this, but I haven't found how/if microk8s is running it, much less how to configure it.

I also found a "cri" plugin in `microk8s.ctr plugins ls`, but haven't found a way to configure it either.

I'd appreciate any suggestions!

Thanks.

**Comment by balchua** [comment]
I think you will have to play with the fluentd configuration, by record transformer.  What is happening as i understand it, fluentd is actually converting the raw log to json.
```
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
```
Since you are outputting json, it becomes a nested json document.  The field `log` now contains a raw json, which is your output.
I'm not super familiar with fluentd, but maybe you can try this https://stackoverflow.com/questions/56049210/fluentd-nested-json-parsing

**Comment by sam-github** [comment]
Thanks for the pointers. I can look at that, and will, but I'd still like if someone could explain to me what component is taking my container's log output line, and prepending the unstructured text. The pipeline is  this, AFAICT:

```
container writes:
   JSON to stdout
kubelet (or containerd?):
   collects and buffers the JSON, `kubectl log ` can display it
SOMETHING?:
  reads log from kube,
  transforms `JSON` to `TIME stdout F JSON`
  writes the transfomed line to /var/log/pods/...
fluentd:
   reads /var/log/pods/...
   pushes to elastic search
```
I'd like to know the entity named "SOMETHING" above, and where its configuration can be found.

Note that fluentd's current microk8s config would already parse the logs perfectly if they were what the container had written, verbatim (JSON), because it came setup to parse whole JSON lines.

**Comment by balchua** [comment]
AFAICT its the containerd writing it to `/var/log/pod`.

**Comment by sam-github** [comment]
https://github.com/containerd/cri/pull/421/files#r152399214 makes me think, that, too, and I haven't found any configuration switches for it. So, it looks like fluentd will have to handle this.

**Comment by balchua** [comment]
@sam-github when you have figured out how to configure fluentd to handle nested json, please let me know. 😁. It will surely come in handy.
Thanks!

**Comment by lehmamic** [comment]
@sam-github do you already have a solution for this problem? Also the Kubernetes logs like pod name, namespace etc seems to be logged as json instead of beeing parsed.

**Comment by sam-github** [comment]
No solution, its still broken, I believe that it is caused by an incomplete implementation of the contained/cri log format, the fluented config lost JSON support at that time. See some of the linked issues above. Not something I work with directly ATM, though, so I won't be looking into  it anymore.

**Comment by RoSk0** [comment]
Things getting a bit more complicated as current fluentd plugin is broken and outdated. See https://github.com/ubuntu/microk8s/issues/701

**Comment by balchua** [comment]
We recently updated fluentd addon.  Perhaps it will be in 1.19 channel or latest/edge.

**Comment by raftario** [comment]
@lehmamic Any luck on this ?

**Comment by lehmamic** [comment]
The version should work. We don’t use the addon anymore, we installed a proper efk stack
