### ISSUE TITLE
Chrome OS Crostini support

### ISSUE THREAD

**Issue by wpwoodjr** [canonical/microk8s#818]
At Kubecon, Tim Van Steenburgh and Konstantinos Tsakalozos suggested for me to post here because microk8s on Crostini doesn't work, either in classic mode or sandboxed.

[inspection-report-20191121_134510.tar.gz](https://github.com/ubuntu/microk8s/files/3877010/inspection-report-20191121_134510.tar.gz)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by wpwoodjr** [comment]
Still hoping this gets resolved...

**Comment by gregloveskhi** [comment]
Any work on this? I installed snapd on buster crostini

`sudo apt install snapd`

but when I try to install microk8s

`sudo snap install microk8s --classic --channel=stable
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       /tmp/sanity-mountpoint-075436786: mount failed: Operation not permitted.`

Is something missing, like a squash fuse component or something?
